### ISSUE TITLE
What is SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID, TOKEN_PROGRAM_ID, TOKEN_METADATA_PROGRAM_ID in src/candy-machine.ts

### ISSUE THREAD

**Issue by itxshakil** [metaplex-foundation/metaplex#1002]
I was checking the source code and found these
`SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID, TOKEN_PROGRAM_ID, TOKEN_METADATA_PROGRAM_ID`

 in `src/candy-machine.ts`

Its value is hard coded.

I'm bit worried , How these are being used. As I have listened some story of scam.

Where mint money automatically transferred to someone else's wallet.

**Comment by praskoson** [comment]
TOKEN_PROGRAM_ID is the address of the [token program](https://spl.solana.com/token)
SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID is the address of the [associated token program](https://spl.solana.com/associated-token-account)
and lastly, TOKEN_METADATA_PROGRAM_ID is the address of the Metaplex Token Metadata program.

Each program has an account on Solana that represents it. Usually you would get these constants from libraries like [web3js](https://solana-labs.github.io/solana-web3.js/) and [spl-token](https://www.npmjs.com/package/@solana/spl-token). Why they hardcoded them like this instead, I don't know, maybe it was just more convenient.

**Comment by itxshakil** [comment]
Is it safe to use that constant value? Because I don't want to be scammed, and money goes to someones else's wallet.

**Comment by Yuriy-Ihor** [comment]
yes, its safe
you can check all of these ids in solana's docs

**Comment by itxshakil** [comment]
Thanks for confirmation.
