### ISSUE TITLE
Problem getting fair launch / candy machine state

### ISSUE THREAD

**Issue by danh00** [metaplex-foundation/metaplex#1004]
**Describe the bug**
Problem getting fair launch state and candy machine state

**To Reproduce**
1. Followed steps to create fair launch and candy machine
2. Input relevant details into  js/packages/fair-launch/.env
3. yarn start 
4. Connected phantom wallet
5. UI hangs on Loading...Waiting for you to connect your wallet.
6. Inspecting page gives the following errors
Problem getting fair launch state
Home.tsx:397 TypeError: Cannot read properties of null (reading 'data')
    at Function.fetchIdl (index.ts:311)
    at async getFairLaunchState (fair-launch.ts:119)
    at async Home.tsx:344

Problem getting candy machine state
Home.tsx:409 TypeError: Cannot read properties of null (reading 'data')
    at Function.fetchIdl (index.ts:311)
    at async getCandyMachineState (candy-machine.ts:143)
    at async Home.tsx:401

**Expected behavior**
Retrieves the fair launch stage and executes the fair launch protocol followed by candy machine mint

**Desktop (please complete the following information):**

 - Chrome
 - Metaplex master branch commit : 6f233fc42f346c039412af4aaf895a5391295774

**Comment by TheCurryMan** [comment]
Running into the same issue - @danh00 did you find a fix?

**Comment by ProjectSytras** [comment]
Having the same problem too.... Anyone has a solution to this?

**Comment by Medienor** [comment]
Same problem! Will be paying for a fix! Please help us.

**Comment by Medienor** [comment]
@ProjectSytras did you find a fix? @TheCurryMan

**Comment by danh00** [comment]
hi sorry guys, i can't fully remember how I fixed it but it was but it was an error I made in the process. I would suggest trying again from scratch but being very careful to doublecheck each step is correctly followed.
