### ISSUE TITLE
lerna ERR! yarn run build exited 2 in '@metaplex/cli'

### ISSUE THREAD

**Issue by georgiod9** [metaplex-foundation/metaplex#1007]
After cloning from master, yarn install and yarn bootstrap work fine. However, when I run yarn build inside metaplex/js I get an error right after `less-watch-compiler src/ dist/lib/ --run-once`

It seems to work on mac. However on windows you get the error.

**To Reproduce**
1. Go to https://github.com/metaplex-foundation/metaplex
2. Clone from master branch
3. cd into metaplex/js
4. Run  yarn install && yarn bootstrap && yarn build
5. On terminal, you will see: `lerna ERR! yarn run build exited 2 in '@metaplex/cli'`

**Expected behavior**
Running yarn build is expected to output 'lerna success' on all lerna runs (@metaplex/cli, @oyster/common, candy-machine-mint, gumdrop and web)

**Screenshots**
![err](https://user-images.githubusercontent.com/56872994/142455954-63898a6f-ff29-43e8-be82-e600bd36bf5f.PNG)

**Desktop Info**
 - OS: [Windows 10]
 - Browser [brave]
 - Version [1.32]

**Additional details**
It seems like the error is related to mocha-js or something. Might be a conflict with jest, but I am unsure. Any help is appreciated.

Thanks

**Comment by garrettbear** [comment]
I'm on mac and also seeing this same error. The `yarn install` took forever for me

**Comment by georgiod9** [comment]
Yeah, yarn install takes alot of time, that's normal. I just tried it on mac it worked.. So don't really know what to figure out of that.
 It was working 24hrs ago, I don't know what kind of bugs were pushed in the recent commits

**Comment by georgiod9** [comment]
> I'm on mac and also seeing this same error. The `yarn install` took forever for me

are you also getting that mocha error too?

**Comment by garrettbear** [comment]
I'm mostly hitting this error within the cli package 

`../../node_modules/@types/three/src/renderers/WebGLRenderer.d.ts:38:34 - error TS2304: Cannot find name 'OffscreenCanvas'.`

**Comment by garrettbear** [comment]
Curious what node version you were using on mac to get it working?

**Comment by georgiod9** [comment]
On mac, I used nvm to choose node v14.18.1

**Comment by georgiod9** [comment]
Really, this is mind boggling. How did the build fail, yet when i run `yarn start` the project deploys on localhost as expected. But i'm unsure whether this means that metaplex wasn't built successfully

**Comment by garrettbear** [comment]
@georgiod9 I saw that the last two commits on master are actually failing to build, so I went back to codebase of the last successful commit: https://github.com/metaplex-foundation/metaplex/tree/6f233fc42f346c039412af4aaf895a5391295774

**Comment by lillichoung** [comment]
Yeah, I can't yarn build either (fresh clone, yarn install & yarn bootstrap work fine).  I'm getting a different error, though. On MacOS: 

```
lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/packCreate/components/Header/data.ts:4:14
Type error: Property '3' is missing in type '{ 0: { title: string; }; 1: { title: string; }; 2: { title: string; }; 4: { title: string; }; }' but required in type 'Record<CreatePackSteps, HeaderContentRecord>'.

  2 | import { HeaderContentRecord } from './interface';
  3 | 
> 4 | export const HEADER_CONTENT: Record<CreatePackSteps, HeaderContentRecord> = {
    |              ^
  5 |   [CreatePackSteps.SelectItems]: {
  6 |     title: 'Select items for your Pack Listing',
  7 |   },
error Command failed with exit code 1.

```

**Comment by spencercoder** [comment]
> Yeah, I can't yarn build either (fresh clone, yarn install & yarn bootstrap work fine). I'm getting a different error, though. On MacOS:
> 
> ```
> lerna ERR! yarn run build stderr:
> Failed to compile.
> 
> ./src/views/packCreate/components/Header/data.ts:4:14
> Type error: Property '3' is missing in type '{ 0: { title: string; }; 1: { title: string; }; 2: { title: string; }; 4: { title: string; }; }' but required in type 'Record<CreatePackSteps, HeaderContentRecord>'.
> 
>   2 | import { HeaderContentRecord } from './interface';
>   3 | 
> > 4 | export const HEADER_CONTENT: Record<CreatePackSteps, HeaderContentRecord> = {
>     |              ^
>   5 |   [CreatePackSteps.SelectItems]: {
>   6 |     title: 'Select items for your Pack Listing',
>   7 |   },
> error Command failed with exit code 1.
> ```

same error im getting. every time they update something new errors come its redicoulous

**Comment by georgiod9** [comment]
Yeah, it's not your fault @spencercoder . Seems like demand is exceeding supply when it comes to metaplex devs. Too many updates needed in a short time.

Kudos for the team for doing a great job tho

**Comment by aheckmann** [comment]
@georgiod9 Please confirm you continue to observe the same issue on Windows after pulling from the latest master. OSX is working and CI is green.

**Comment by aheckmann** [comment]
@spencercoder @lillichoung that is a separate error. Please pull latest master and rerun. If the issue persists, please open a new issue if one doesn't already exist. Thanks!

**Comment by georgiod9** [comment]
Yep, it worked the next day when i pulled the updated version. Thanks

**Comment by coladimeji** [comment]
just add lerna -- then bootstrap and build
example
yarn add lerna -W
yarn add bootstrap -W
yarn build

**Comment by rockomatthews** [comment]
> just add lerna -- then bootstrap and build example yarn add lerna -W yarn add bootstrap -W yarn build

I tried this to fix the issue during build becasue my site was running fine on localhost but not on Vercel.  It is the the same build issue.  So I tried to above suggestion and got the same result locally when trying to build.  

But also now my site forever freezes on the frist loading of my marketplace when doing 'yarn start.' woof...
<img width="238" alt="Screen Shot 2022-06-01 at 12 04 04 PM" src="https://user-images.githubusercontent.com/3928985/171460804-0c64447d-33de-4288-8ee2-5dec24532717.png">
<img width="511" alt="Screen Shot 2022-06-01 at 11 58 28 AM" src="https://user-images.githubusercontent.com/3928985/171460808-6dea7c36-4df5-45cd-88ec-319841717225.png">

My console looks like this and stays here. I am reverting to hopefully get it working on 'yarn start' again

**Comment by coladimeji** [comment]
I have similar issues before, It was loading for almost 9 minutes, then I did the followings:
1. check is you have rust installed if not install it. then configure your API
2. try that,  and let me know if the freezes
3. Oh one last thing, try connecting to vercel directly from your VS IDE , it's  better if you are using vercel

**Comment by coladimeji** [comment]
//your .env.production  folder should look like this for the API:
REACT_APP_SOLANA_NETWORK=solana-mainnet
REACT_APP_SOLANA_RPC_HOST=https://divinity-solo-water.solana-mainnet.quiknode.pro/aa1daab0a5d272f47d9263abb04e0eae7uw71ov7/

**Comment by coladimeji** [comment]
It seems the network is slow

**Comment by rockomatthews** [comment]
thanks a ton. will try.  I am seeing also that my production launch that was working fine and has not been touched, is throwing an error. I think more is going on... When I clone my project and try to use any branch, I am getting issues.  Seems like a network thing! The eroor can be dismissed then it just loads... 

I tried installing rust but don't see a .env.production folder anywhere.  Do I need to make one at the same level as the .env file that has my store address?

<img width="967" alt="Screen Shot 2022-06-01 at 12 39 33 PM" src="https://user-images.githubusercontent.com/3928985/171468705-7b185fb1-e0ca-4961-855b-64038ca229ad.png">
?
