### ISSUE TITLE
Remove/Delete/Burn partially sold candy machine in Production?

### ISSUE THREAD

**Issue by amanprak** [metaplex-foundation/metaplex#1011]
Hey Guys

Can anyone please help how can we remove/delete/burn partially sold candy machine created using Metaplex in Production?

**Comment by Kameeno** [comment]
why don't create a new one ? 
for the rest, you burn buy the spl-token commands (easly scriptable in NodeJS)

**Comment by amanprak** [comment]
Thanks for your reply @Kameeno 

I want to delete my collection because it partially sold and I want to list my project to the secondary market

I am quite new to this can you please help me with the metaplex commands or the process...I am struggling with this for quite some time now

Any help is highly appreciated

Thanks in advance

**Comment by Kameeno** [comment]
Few weeks ago i wrote a code to burn all the supply of the tokens on a wallet ( set on the solana cli config) 
but i'm not pretty sure if with the candy works.
what you have if you execute this ?
`spl-token accounts --owner PUTHERETHEWALLETADDRESS`

**Comment by amanprak** [comment]
Thanks for the help @Kameeno

**Comment by Kameeno** [comment]
youre welcome. is just before to give you some code or burn i wanted to be sure if before the minting, the candy machine wallet still have the nft's (i dont remember right now :/ )

**Comment by Kameeno** [comment]
for the rest. some projects buy-back theirs nft on the secondary market and they burn using my script as bot discord. 

you cant burn or delete a nft if is not on a wallet you have

**Comment by zyhuang86** [comment]
Were you able to burn the partially unsold candy machine collections? I am about to launch my collection and want to do something similar in case my collection is only partially sold. I am hoping to avoid having to mint unsold NFTs since network fee alone is 0.011 even if the candy machine price is set to a neglible amount.
