### ISSUE TITLE
Yarn build failing

### ISSUE THREAD

**Issue by Mahesh-Vemula** [metaplex-foundation/metaplex#1012]
**Describe the bug**
Forked master branch and trying to build it

**To Reproduce**
1. Go to js folder
2. run >yarn
3. run >yarn bootstrap
4. run >yarn build

Step 4 is throwing error. I am using mac, tried using node 14 and 16. Both failed

**Desktop (please complete the following information):**
- OS: [macOS Catalina 10.15.7]

 

**Additional context**
yarn build
yarn run v1.22.10
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 5 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@oyster/common' in 15.4s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna info run Ran npm script 'build' in '@metaplex/cli' in 25.7s:
$ tsc -p ./src
lerna ERR! yarn run build exited 1 in 'web'
lerna ERR! yarn run build stdout:
$ next build
info  - Loaded env from /Users/AF47702/Space/Self/Projects/Snowcrash/metaplex/js/packages/web/.env.production
info  - Loaded env from /Users/AF47702/Space/Self/Projects/Snowcrash/metaplex/js/packages/web/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/packCreate/components/Header/data.ts:4:14
Type error: Property '3' is missing in type '{ 0: { title: string; }; 1: { title: string; }; 2: { title: string; }; 4: { title: string; }; }' but required in type 'Record<CreatePackSteps, HeaderContentRecord>'.

  2 | import { HeaderContentRecord } from './interface';
  3 | 
> 4 | export const HEADER_CONTENT: Record<CreatePackSteps, HeaderContentRecord> = {
    |              ^
  5 |   [CreatePackSteps.SelectItems]: {
  6 |     title: 'Select items for your Pack Listing',
  7 |   },
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Mahesh-Vemula** [comment]
After switching from master branch to release tag v1.0.0 issue no longer exists.
In docs it is recommended to use release tags. I missed it. Thanks

**Comment by spencercoder** [comment]
wait how do you do it bro im a noob @Mahesh-Vemula

**Comment by Mahesh-Vemula** [comment]
run below commands @spencercoder 

>git reset --hard
>git fetch
>git tag
v1.0.0
>git checkout tags/v1.0.0 -b localBranch
>cd js
>yarn
>yarn bootstrap
>yarn build

and then use yarn start to run in local
