### ISSUE TITLE
help mee

### ISSUE THREAD

**Issue by ulu99** [metaplex-foundation/metaplex#1014]
![k](https://user-images.githubusercontent.com/94657414/142520797-9a476615-018e-48ee-bd8d-065a22ad64af.JPG)

**Comment by Kameeno** [comment]
Can you show your 0.json or 1.json ?

**Comment by emlcpfx** [comment]
I think your metadata is formatted incorrectly.

**Comment by ulu99** [comment]
> 0.json veya 1.json'unuzu gösterebilir misiniz?
it's just a trial but i get error

{
  "name": "Your Collection #1",
  "description": "Remember to replace this description",
  "image": "ipfs://NewUriToReplace/1.png",
  "dna": "a07a9dad7fa467f9841644fe96e551bec34fca68",
  "edition": 1,
  "date": 1637279955216,
  "attributes": [
    {
      "trait_type": "Background",
      "value": "Black"
    },
    {
      "trait_type": "Eyeball",
      "value": "Red"
    },
    {
      "trait_type": "Eye color",
      "value": "Yellow"
    },
    {
      "trait_type": "Iris",
      "value": "Small"
    },
    {
      "trait_type": "Shine",
      "value": "Shapes"
    },
    {
      "trait_type": "Bottom lid",
      "value": "Middle"
    },
    {
      "trait_type": "Top lid",
      "value": "Middle"
    }
  ],
  "compiler": "HashLips Art Engine"
}
