### ISSUE TITLE
store is not initializing

### ISSUE THREAD

**Issue by tayab2468** [metaplex-foundation/metaplex#1018]
My Store is not initializing, I'm on devnet and have 12 sol in my Phantom wallet but still it saying this.

![Screenshot from 2021-11-19 16-22-40](https://user-images.githubusercontent.com/74657936/142615071-0842de5c-1bf9-4c4c-9c32-4fe865b85c7b.png)

**Comment by VadimGrozinok** [comment]
Make sure that you changed network to DevNet in application as well not only in Phantom wallet

**Comment by tranqy** [comment]
I have the same problem.  I have tried both v1 and main. 

I follow the init store instructions, I choose the same chain as my phantom wallet, and I always get this error.

![image](https://user-images.githubusercontent.com/171/143681948-5b3b0308-ef88-4959-9da9-8bc99817ea69.png)

**Comment by VadimGrozinok** [comment]
Try to run front end with [ngrok](https://ngrok.com/)
So run `ngrok http 3000` and then run front end
Once you done it go to the web page with **https**

**Comment by ahmadsjn** [comment]
i have the same problem
