### ISSUE TITLE
run yarn build  ERR

### ISSUE THREAD

**Issue by Maha-code-star** [metaplex-foundation/metaplex#1019]
yarn run v1.22.17
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 5 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@oyster/common' in 26.7s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna info run Ran npm script 'build' in '@metaplex/cli' in 66.4s:
$ tsc -p ./src
lerna ERR! yarn run build exited 1 in 'web'
lerna ERR! yarn run build stdout:
$ next build
info  - Loaded env from /Users/mahasaad/Desktop/solana/metaplex-master/js/packages/web/.env.production
info  - Loaded env from /Users/mahasaad/Desktop/solana/metaplex-master/js/packages/web/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/packCreate/components/Header/data.ts:4:14
Type error: Property '3' is missing in type '{ 0: { title: string; }; 1: { title: string; }; 2: { title: string; }; 4: { title: string; }; }' but required in type 'Record<CreatePackSteps, HeaderContentRecord>'.

  2 | import { HeaderContentRecord } from './interface';
  3 | 
> 4 | export const HEADER_CONTENT: Record<CreatePackSteps, HeaderContentRecord> = {
    |              ^
  5 |   [CreatePackSteps.SelectItems]: {
  6 |     title: 'Select items for your Pack Listing',
  7 |   },
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by spencercoder** [comment]
getting same error!

**Comment by spencercoder** [comment]
some one help

**Comment by p9t3k** [comment]
I have same error, running on MAC OS

**Comment by spencercoder** [comment]
same on mac, everytime they update the file a error happens lol

**Comment by miloradbozic** [comment]
I am getting same error on my windows 10 machine.

**Comment by p9t3k** [comment]
@miloradbozic can you please link it?

**Comment by invictus2010** [comment]
same error when attempting to deploy on vercel

**Comment by Salad124** [comment]
Any update on this? I am having the same error

**Comment by aheckmann** [comment]
Please pull latest master and reply here with the result. `yarn build` is working for me on OSX and CI is green.

**Comment by bkhoward2001** [comment]
Has anyone found solution to this.... been battling this for a week now?

**Comment by KlausMillenial** [comment]
> Please pull latest master, rerun the command and reply here with the result. `yarn build` is working for me on OSX and CI is green.

hello, how do you pull latest master??

**Comment by emersonthis** [comment]
@KlausMillenial `$ git pull origin master`

(This didn’t solve the problem for me. For me, both master and v1.0.0 fail when deployed to Vercel following the instructions in the docs)

**Comment by SkippCode** [comment]
first make sure you are in your ...metaplex\js and then do yarn install, after that run the build. worked for me

**Comment by davidabuu** [comment]
How did it work for you

**Comment by miloradbozic** [comment]
I think this is fixed now, thank you.

**Comment by AwakenDevSolana** [comment]
Yoo For windows users, run cmd.exe as an administrator 
cd js
yarn install
yarn build
in cmd
not in vs studio.. it worked for me !!!!!
