### ISSUE TITLE
0x139

### ISSUE THREAD

**Issue by ilooha125** [metaplex-foundation/metaplex#1020]
hi , this error isnt new here , but as ive seen so far, solutions are very different and the one with onchain-false replacement is the most working so far. when i run the command to check which files arent uploaded , it somehow shows only the ones , that didnt have any issues . for example if: file 1 - working ; 2 - failed ; 3 - working . in cache file i only see 1 and 3 , and the ones with error arent there somehow . so in order to fix error 0x139 i need to see these ones , but i dont . can some1 pls tell how to make them visible ?

**Comment by ProPratik1405** [comment]
When i faced this issue i used the verfiy command with a subcommand called log-level and with this i was able to find the asssets which were having issues. So after detecting these assets i went to the config file and made it onchain:false and rerun the upload command.
