### ISSUE TITLE
Sorry, there was an error!  Transaction is invalid or not enough funds provided to push this file

### ISSUE THREAD

**Issue by dropero2** [metaplex-foundation/metaplex#1023]
**Describe the bug**
Hey guys getting this error when minting on tesnet but there is money on the wallet. Where would this problem be at? 

**To Reproduce**
1. Go to " Create NFT"
2. Click on 'Mint NFT'
4. See error " Once transaction is approve on the wallet"
5. Error 
Sorry, there was an error!

Transaction is invalid or not enough funds provided to push this file

**Comment by 541joehill** [comment]
Getting same error here.

**Comment by daniel-icarus** [comment]
+1

**Comment by shkshubham** [comment]
+1

**Comment by h3xag0nx** [comment]
I've found some different between `uploadArweave` function on CLI and the one on store.
You can see here, the function on CLI estimate the size of `manifest.json` file, but the one on the store didn't. (see https://github.com/metaplex-foundation/metaplex/blob/d6fd7f1075ea3d875bc57668f020cd1933c450e8/js/packages/web/src/actions/nft.tsx#L361)

I've tried to include, but still get the same error
 
https://github.com/metaplex-foundation/metaplex/blob/d6fd7f1075ea3d875bc57668f020cd1933c450e8/js/packages/cli/src/helpers/upload/arweave.ts#L57

**Comment by shkshubham** [comment]
Found the solution `uploadArweave` is not working for `testnet`, just switch to `devnet` it will start working again

**Comment by gaozp** [comment]
> +1
> 
> Getting the error from uploadFile.
> 
> Network: testnet
> 
> <img alt="Screenshot 2021-12-13 at 6 34 32 AM" width="782" src="https://user-images.githubusercontent.com/30808070/145737481-f9f4a8c6-b088-449d-9f33-0e985b30acaf.png">
> 
> <img alt="Screenshot 2021-12-13 at 6 34 40 AM" width="790" src="https://user-images.githubusercontent.com/30808070/145737485-8e94f53c-29d1-4169-ae2e-0a55d41f77dd.png">
> 
> My Fund: <img alt="Screenshot 2021-12-13 at 6 35 53 AM" width="354" src="https://user-images.githubusercontent.com/30808070/145737525-10a8423d-8e8f-4291-88ba-25678316b4e6.png">

@shkshubham I'm facing the same issue here. plz help me with this. 

1.29 sol , which env this sol is on ?  I don't have any sol on mainnet env , but I airdrop 3 sol on devnet . 
Does it means that I must buy some sols before I upload files on devnet?

**Comment by Venus68281** [comment]
Hi.
I am facing the same error in Testnet.

**Comment by shkshubham** [comment]
> > +1
> > Getting the error from uploadFile.
> > Network: testnet
> > <img alt="Screenshot 2021-12-13 at 6 34 32 AM" width="782" src="https://user-images.githubusercontent.com/30808070/145737481-f9f4a8c6-b088-449d-9f33-0e985b30acaf.png">
> > <img alt="Screenshot 2021-12-13 at 6 34 40 AM" width="790" src="https://user-images.githubusercontent.com/30808070/145737485-8e94f53c-29d1-4169-ae2e-0a55d41f77dd.png">
> > My Fund: <img alt="Screenshot 2021-12-13 at 6 35 53 AM" width="354" src="https://user-images.githubusercontent.com/30808070/145737525-10a8423d-8e8f-4291-88ba-25678316b4e6.png">
> 
> @shkshubham I'm facing the same issue here. plz help me with this.
> 
> 1.92 sol , which env this sol is on ? I don't have any sol on mainnet env , but I airdrop 3 sol on devnet . Does it means that I must buy some sols before I upload files on devnet?

uploadArweave is not working for testnet, just switch to devnet it will start working again

**Comment by shkshubham** [comment]
> Hi.
> I am facing the same error in Testnet when minting NFT.
> ![image](https://user-images.githubusercontent.com/64267602/151995266-d128b5d7-36a6-45e3-ac98-f5313aee768e.png)

uploadArweave is not working for testnet, just switch to devnet it will start working

**Comment by keisukew53** [comment]
"@metaplex/arweave-cost": "^1.0.4",
Please try to use correct version of @metaplex/arweave-cost
