### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Mamu9** [metaplex-foundation/metaplex#1029]
The command : ts-node packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet.json

gives following output 

![Screenshot from 2021-11-21 01-17-15](https://user-images.githubusercontent.com/92148901/142759204-d4242d53-af90-417d-a5d8-b3010b628059.png)

**Comment by adilanchian** [comment]
Hey @yamijuan -

Been dealing with this as well, but I think I found the problem which I referenced a solution in #736 

Let me know if this works for you

**Comment by Mamu9** [comment]
Hey @adilanchian just saw your reply and #736 

My json didn't have the creator and symbol. Just trying and will update the progress.
