### ISSUE TITLE
Gumdrop `Transaction too large`

### ISSUE THREAD

**Issue by 21e8** [metaplex-foundation/metaplex#1033]
**Describe the bug**
Created a gumdrop with 4000 items, could not claim. My guess is that the size of a long `proof` exceeds the size allowed for transactions.

EDIT: This seems to be related more to the number of wallets being distributed to. For me it failed in one instaces at a set with 194 different claimants.

**To Reproduce**
1. Create Candy Machine with 4k items
2. Create Gumdrop with said Candy machine
3. Try to claim one of the items.

**Expected behavior**
CLI should warn before this becomes the case.

**Comment by lwus** [comment]
Good catch! This seems to be an artifact of the large number of accounts used for the candy-machine / metadata-print instructions (and, by extension, should not be a limiter for fungible-token gumdrops).

There is a (partial) simple client-side solution to this by splitting the transaction for setting up the NFT / edition mint from the actual claim. This was implemented in https://github.com/lwus/metaplex/commit/9ab2868280a4b42be83f1840a36ea308494c99ec and deployed to https://lwus.github.io/metaplex/. This should allow a whitelist of up to `2**15` users.

A more complete solution might be to separate the verification of the proof and the candy-machine / metadata-print call.

**Comment by 21e8** [comment]
@lwus so you are saying that this has been fixed already? I will retest this later

**Comment by 21e8** [comment]
@lwus pls merge asap lol
