### ISSUE TITLE
When I create an NFT by uploading a PNG it doesn't seem to store the image anywhere.  

### ISSUE THREAD

**Issue by benchow** [metaplex-foundation/metaplex#104]
Is there a size limit?  The image was 376kB

![Screen Shot 2021-07-01 at 2 38 33 AM](https://user-images.githubusercontent.com/441238/124077561-968e2b00-da15-11eb-96bb-fbd82027ce46.png)

**Comment by benchow** [comment]
Attached is a screenrecording + chrome console log of my error
![metaplex create nft](https://user-images.githubusercontent.com/441238/124317534-55953400-db45-11eb-914b-13bf1448b537.gif)
[metaplex create nft.log](https://github.com/metaplex-foundation/metaplex/files/6756491/metaplex.create.nft.log)

**Comment by benchow** [comment]
Here is arweave and solana address of the resultant token

https://zqsdftwesin7mfw4lkepalevpwa674owmaof2mpvotbtrjaen56a.arweave.net/zCQyzsSSG_YW3FqI8CyVfYHv8dZgHF0x9XTDOKQEb3w/

https://explorer.solana.com/address/BghiUvwZUVuVyG6nCyzGUa3LfWGbtbPPnqcog7inyb18

**Comment by bhgames** [comment]
Holaplex is looking into this one, it has to do with I think spaces in the image names

**Comment by PigeonSolToken** [comment]
This is a space issue with the file, can be resolved using this, https://github.com/metaplex-foundation/metaplex/issues/103

**Comment by bhgames** [comment]
Closing as is duplicate as flappy says
