### ISSUE TITLE
git Clone issues

### ISSUE THREAD

**Issue by Max-coder9** [metaplex-foundation/metaplex#1042]
this is what pops up when i try to run the git clone on my macbook 

git clone https://github.com/metaplex-foundation/metaplex.git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by VadimGrozinok** [comment]
The problem is that Xcode Command-line Tools needs to be updated.
Do this one: `xcode-select --install`

**Comment by Max-coder9** [comment]
> The problem is that Xcode Command-line Tools needs to be updated. Do this one: `xcode-select --install`

where do i run this, this is my first time using this type of software. Thanks in advance

**Comment by aheckmann** [comment]
| where do i run this, this is my first time using this type of software. Thanks in advance

This is a command line tool you run from your Terminal app.
