### ISSUE TITLE
feat: support multiple image formats in a generic manner

### ISSUE THREAD

**Issue by thlorenz** [metaplex-foundation/metaplex#1044]
The following PRs attempted to do this for one added image format at a time:

- https://github.com/metaplex-foundation/metaplex/pull/689
- https://github.com/metaplex-foundation/metaplex/pull/759
- https://github.com/metaplex-foundation/metaplex/pull/1028

However we need a solution that works for any image format in order to not have to supply changes for each format we want to support going forward.

**Comment by JamisonO** [comment]
This would be excellent. Want to use Metaplex but my collection are gifs.
