### ISSUE TITLE
Translating error Error: Transaction was not confirmed in 60.04 seconds. It is unknown if it succeeded or failed.

### ISSUE THREAD

**Issue by cbpaw** [metaplex-foundation/metaplex#1049]
Hi all,

15 SOL has been transferred from my account while trying to upload NFT's, however the assets have not been uploaded, please help.

I tried uploading 8,888 NFT's (png + json) to mainnet after testing on devnet, using the command: 
`ts-node /metaplex/js/packages/cli/src/candy-machine-cli.ts upload . --env mainnet-beta --keypair ~/.config/solana/mainnet.json -n 8888`

This gave me the following error:
`Translating error Error: Transaction was not confirmed in 60.04 seconds. It is unknown if it succeeded or failed. Check signature sGhhovVDKMb9do2uNz666pEfn9dSkssJVQ9yVtow9Po1djpfdDnMbSmjQ9gaRFyj2myq2ikWg5KJwPToo7L8EfM using the Solana Explorer or CLI tools.`

How do I troubleshoot this? On devnet I had no issues uploading these assets.

**Comment by cbpaw** [comment]
I solved the issue. I needed to construct the file in the .cache directory using the Candy Machine Config ID from the successful Solana transaction. Please contact me if you read this and need help!

**Comment by justinphan3110** [comment]
@cbpaw hi can you share the config id that works
