### ISSUE TITLE
candy-machine-cli verify and metachacters in NFT  and cache names

### ISSUE THREAD

**Issue by ncarrara** [metaplex-foundation/metaplex#1053]
The verify option of the candy-machine-cli does not support NFT/cache names with metacharacters for example "name of the nft [version 1]".

I am pretty sure it is because you are comparing strings using a regex match and it conflicts with metachars:

In candy-cli-machine.ts you are doing this:

if (!name.match(cacheItem.name) || !uri.match(cacheItem.link)) {

**Comment by jasonruncie** [comment]
I have fixed this in my PR to improve verify https://github.com/metaplex-foundation/metaplex/pull/985
