### ISSUE TITLE
Arweave upload endpoint timeouts

### ISSUE THREAD

**Issue by cannc4** [metaplex-foundation/metaplex#1059]
**Describe the bug**
Arweave timeouts 

**To Reproduce**
Boot up the default project and attempt to create an item

**Expected behavior**
Created item

**Desktop (please complete the following information):**
 - OS: Monterey 12.0
 - Browser: Chrome
 - Version:  96.0.4664.55 (Official Build) (arm64)

**Additional context**

As of today, I've been getting some 408 and 405s from the following endpoint after getting stuck at "Waiting for Final Confirmation" step

```
export const ARWEAVE_UPLOAD_ENDPOINT =
  'https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile';
```

Any thoughts?

**Comment by cannc4** [comment]
Was caused by a miss data problem within the mint function - closing it now as it's not relevant.

**Comment by cxctvs** [comment]
hi im presenting same problem can you define the miss data problem? thanks.
