### ISSUE TITLE
Cannot read properties of undefined (reading 'xr') TypeError: cannot read properties of undefined (reading 'xr') at new...

### ISSUE THREAD

**Issue by best-lucky1030** [metaplex-foundation/metaplex#1062]
I cloned the Metaplex latest code and followed tot the guide.
And after run the `yarn start`, I got the following error.
I attached the error image.

![image](https://user-images.githubusercontent.com/89365150/143684192-6a9e0911-fa52-433f-818b-da7fe18eb622.png)

Please see the image and let me know what's the problem for this.

**Comment by DojoSoMope** [comment]
Found a fix for this? Encountering the same problem on both the repo and metaplex website install docs
