### ISSUE TITLE
"View profile" link is broken

### ISSUE THREAD

**Issue by emersonthis** [metaplex-foundation/metaplex#1065]
**Describe the bug**
When I click the "View profile" link under my wallet address, the URL changes to a profile route, but the screen is the default homepage.

**To Reproduce**
1. Connect your wallet to the site
2. Click on the wallet address to open the drop-down menu
3. Click the "View profile" link
4. See the default homepage instead of a profile page

**Expected behavior**
A profile page should appear when the link is clicked

**Screenshots**
<img width="1319" alt="Screen Shot 2021-11-28 at 10 10 00 AM" src="https://user-images.githubusercontent.com/1728139/143780738-245c40c3-0568-49c4-91c7-34614a60aa4d.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser: Firefox
 - Version 94.0.2

**Additional context**
I'm open to submitting a PR for this with a bit of clarity as to the desired UX.

**Comment by jasonansellto** [comment]
same issue following

**Comment by Moikapy** [comment]
There isn't a view created for the /profiles path.
If you look at next.config.js it auto rewrites missing routes to the home.
You need to create a view for the user profile and add it to the routes file

**Comment by emersonthis** [comment]
Interesting. So this is an intentional architectural choice? I'm wondering if the plan is to add a default profile view at some point. Either way, I propose either of two interim solutions:
1. Add some documentation that explains this.
2. Instead of rerouting back to the homepage, reroute missing views to a placeholder view that explains something like "you need to implement this view yourself..."
I believe either solution would avoid confusion, and I'd be willing to submit a PR if there's interest for this.
