### ISSUE TITLE
Gumdrop impossible to deploy.

### ISSUE THREAD

**Issue by SerhatAkar** [metaplex-foundation/metaplex#1083]
Hi, 

I've followed all the available tutorials but Gumdrop doesn't want to deploy, whether it is Vercel or Cloudflares. I always get SIGKILL errors or errors linked to memory.

![image](https://user-images.githubusercontent.com/45693102/144132433-13480a11-58d1-4f56-95e1-da4eac98f779.png)

Are there known issues?

**Comment by lwus** [comment]
What steps are you using to install / build / deploy? The fully built static page example should only be a few MB.

**Comment by erdnc13** [comment]
Serhat merhaba, gumdrop da wl yapmamda bana yardımcı olur musun?
