### ISSUE TITLE
Yarn run build error with "lerna ERR! yarn run build exited 1 in 'candy-machine-mint'" please HELP :(

### ISSUE THREAD

**Issue by KlausMillenial** [metaplex-foundation/metaplex#1084]
yarn run v1.22.17
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 5 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@metaplex/cli' in 72.5s:
$ tsc -p ./src
lerna info run Ran npm script 'build' in '@oyster/common' in 116.7s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna ERR! yarn run build exited 1 in 'candy-machine-mint'
lerna ERR! yarn run build stdout:
$ react-scripts build
Creating an optimized production build...
Failed to compile.

/Volumes/maxone/metaplex-master/js/node_modules/@solana/wallet-adapter-slope/node_modules/@solana/wallet-adapter-base/lib/index.js
Error: [BABEL] /Volumes/maxone/metaplex-master/js/node_modules/@solana/wallet-adapter-slope/node_modules/@solana/wallet-adapter-base/lib/index.js: Cannot find module './transformation/file/file'
Require stack:
- /Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/node_modules/@babel/core/lib/index.js
- /Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js
- /Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/available-plugins.js
- /Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/plugins-compat-data.js
- /Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/normalize-options.js
- /Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/index.js
- /Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/dependencies.js
- /Volumes/maxone/metaplex-master/js/node_modules/@babel/core/lib/config/files/plugins.js
- /Volumes/maxone/metaplex-master/js/node_modules/@babel/core/lib/config/files/index.js
- /Volumes/maxone/metaplex-master/js/node_modules/@babel/core/lib/index.js
- /Volumes/maxone/metaplex-master/js/node_modules/@babel/plugin-proposal-async-generator-functions/lib/index.js
- /Volumes/maxone/metaplex-master/js/node_modules/@babel/preset-env/lib/available-plugins.js
- /Volumes/maxone/metaplex-master/js/node_modules/@babel/preset-env/lib/filter-items.js
- /Volumes/maxone/metaplex-master/js/node_modules/@babel/preset-env/lib/index.js
- /Volumes/maxone/metaplex-master/js/node_modules/workbox-build/build/lib/bundle.js
- /Volumes/maxone/metaplex-master/js/node_modules/workbox-webpack-plugin/build/generate-sw.js
- /Volumes/maxone/metaplex-master/js/node_modules/workbox-webpack-plugin/build/index.js
- /Volumes/maxone/metaplex-master/js/packages/fair-launch/node_modules/react-scripts/config/webpack.config.js
- /Volumes/maxone/metaplex-master/js/packages/fair-launch/node_modules/react-scripts/scripts/build.js (While processing: "/Volumes/maxone/metaplex-master/js/node_modules/babel-preset-react-app/dependencies.js")

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'candy-machine-mint'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Hello, I've tried everything for 2 days but I just can't install yarn build in my js file. always something wrong either with oyster or candy machine, please please can some one help??? im almost desperate

**Comment by tina1998612** [comment]
Me too have the oyster problem..

**Comment by khanfromasia** [comment]
Hi there! I hope you are trying to start development on metaplex framework. I find some first steps on this readme.md quite old, you should try reading docs.metaplex.com/create-store
