### ISSUE TITLE
Redeeming your funds out of your losing bid post auction should not mark bid as cancelled

### ISSUE THREAD

**Issue by bhgames** [metaplex-foundation/metaplex#110]
Title says it all, and it should also not remove the bid from the bidders array. This really needs to be a separate action that is almost identical but is slightly different behaivor. Maybe reuse the logic but use some booleans :)

**Comment by PigeonSolToken** [comment]
Can we also have the button disabled once the redeem is complete, so that the user knows he has already redeemed it.

**Comment by ysavchenko** [comment]
I've checked the code and I think the easiest option would be to update `cancel_bid` code and simply move removing bid from the auction only if auction did not end yet (basically move this line within the `if` block above it). Do you agree? @bhgames 
https://github.com/metaplex-foundation/metaplex/blob/4c34eec87bb1a4a26a57807cef8ba858d42918a7/rust/auction/program/src/processor/cancel_bid.rs#L236

**Comment by bhgames** [comment]
Yeah I agree. Basically once auction ends, cancel bid serves as a refund mechanism, and bid state should be considered frozen. This works for me.
