### ISSUE TITLE
signatureUnsubscribe error: Invalid subscription id.

### ISSUE THREAD

**Issue by gioNJIT** [metaplex-foundation/metaplex#1100]
```
Beginning the upload for 1151 (png+json) pairs
started at: 1638464095754
wallet public key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
USING CUSTOM URL https://solana-mainnet.phantom.tech/
Processing file: 0, 0.png
Processing file: 1000, 863.png
initialized config for a candy machine with publickey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
signatureUnsubscribe error: Invalid subscription id.
```
currently getting this error when i upload over 1000 pngs and json.

I'm using a custom RPC and this is confirmed by the console log ```USING CUSTOM URL 'url I use' ```

does anyone have any idea why this is happening?

**Comment by MiguelRogerio** [comment]
I'm getting the same error, if you find out how to fix it please tell, I will do the same

**Comment by AlexVanDyne** [comment]
yup me too. seems like something broke on this last update.

**Comment by alvaropacokink** [comment]
Same here. I will try to downgrade the mateplex foundation.

**Comment by kevin-dev71** [comment]
same here... should we downgrade?

**Comment by alvaropacokink** [comment]
I had used Arweave uploader instead [https://github.com/0xEnrico/arweave-nft-uploader](https://github.com/0xEnrico/arweave-nft-uploader)

**Comment by cultureofwomen** [comment]
Hi Guys, I am getting the same error. I have 10k assets. 

Any luck?

**Comment by mustafabalci** [comment]
I checkout to the last commit I was able to upload successfully. And it worked

`git checkout `938116471dcdb69a233a7ec3e167c83540c2eae4``

**Comment by jclmnop** [comment]
> Hi Guys, I am getting the same error. I have 10k assets.
> 
> ```
> Rejecting for timeout...
> Timeout Error caught { timeout: true }
> Error uploading file 2113 Error: Timed out awaiting confirmation on transaction
>     at /User//Dev/CoW-NFT/production2/metaplex/js/packages/cli/src/helpers/transactions.ts:121:13
>     at step (/User//Dev/CoW-NFT/production2/metaplex/js/packages/cli/src/helpers/transactions.ts:33:23)
>     at Object.throw (/User//Dev/CoW-NFT/production2/metaplex/js/packages/cli/src/helpers/transactions.ts:14:53)
>     at rejected (/User//Dev/CoW-NFT/production2/metaplex/js/packages/cli/src/helpers/transactions.ts:6:65)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> signatureUnsubscribe error: Invalid subscription id.
> signatureUnsubscribe error: Invalid subscription id.
> signatureUnsubscribe error: Invalid subscription id.
> signatureUnsubscribe error: Invalid subscription id.
> ```
> 
> Any luck?

I'm currently uploading 10k assets. Had this issue when using the default batch size (1000), trying again with batch size of 10000 now. 

So far it's taking longer but seems to be throwing less of a fuss.

**Comment by bishop1701** [comment]
How can I set the batch size ?

**Comment by MiguelRogerio** [comment]
> I checkout to the last commit I was able to upload successfully. And it worked
> 
> `git checkout 938116471dcdb69a233a7ec3e167c83540c2eae4`

So far this is working for me , at least I stopped getting the invalid signature error

**Comment by BeeBop21** [comment]
> > I checkout to the last commit I was able to upload successfully. And it worked
> > `git checkout 938116471dcdb69a233a7ec3e167c83540c2eae4`
> 
> So far this is working for me , at least I stopped getting the invalid subscription error

Me too, but it's MUCH slower to upload this time around. Probably should have cleared/deleted the .cache folder from the previous attempt first.

**Comment by CircuitBreaker88** [comment]
I am also having this issue when trying to upload my assets

**Comment by lucastonon** [comment]
+1

**Comment by jclmnop** [comment]
> I am also having this issue when trying to upload my assets

You should try using a paid RPC endpoint, or set the batch size to be larger than the collection. These are the only two things which worked for me. 

The advantage of a paid RPC endpoint is that you can actually lower the batch size, which dramatically reduces the amount of time needed to finish uploading all of your assets.

**Comment by Andi-fx** [comment]
> 

Hi, im new to this, what would be the batch size?

**Comment by bishop1701** [comment]
By default it is set to 1000

**Comment by shaghaar** [comment]
> > > I checkout to the last commit I was able to upload successfully. And it worked
> > > `git checkout 938116471dcdb69a233a7ec3e167c83540c2eae4`
> > 
> > 
> > So far this is working for me , at least I stopped getting the invalid subscription error
> 
> Me too, but it's MUCH slower to upload this time around. Probably should have cleared/deleted the .cache folder from the previous attempt first.

lol yes its working for me as well but indeed MUCH slower, like 1 file each minute
Can anyone explain to me tho how to change the batchSize ?

**Comment by jclmnop** [comment]
> > > > I checkout to the last commit I was able to upload successfully. And it worked
> > > > `git checkout 938116471dcdb69a233a7ec3e167c83540c2eae4`
> > > 
> > > 
> > > So far this is working for me , at least I stopped getting the invalid subscription error
> > 
> > 
> > Me too, but it's MUCH slower to upload this time around. Probably should have cleared/deleted the .cache folder from the previous attempt first.
> 
> lol yes its working for me as well but indeed MUCH slower, like 1 file each minute Can anyone explain to me tho how to change the batchSize ?

With the `--batch-size` option in the command line args

**Comment by brettsloan** [comment]
> 

I tried that git checkout but it only gave me a new error. 
I also can't seem to access the --batch-size (--batchSize) args anywhere?

How can I access those in order to raise the default? I also tried combing the js files and all I could find was in candy-machine-cli.ts but it had no default size.

Any help is greatly appreciated

**Comment by MrAlexWinkler** [comment]
adding `-b 10000 ` did the trick for me but I somehow lost 3 sol in this whole process for 1845 images less than 370mb that should cost less than $4 based on arweavefees. Super doesn't make sense. How do I get those funds back?

**Comment by JohnJoe24** [comment]
Still getting the same problem. The `git checkout 938116471dcdb69a233a7ec3e167c83540c2eae4` spits out fatal: reference is not a tree.

Maybe I'm doing it wrong, could you please explicate how exactly to use this fix? Thank you

**Comment by hulkhogan2024** [comment]
> Still getting the same problem. The `git checkout 938116471dcdb69a233a7ec3e167c83540c2eae4` spits out fatal: reference is not a tree.
> 
> Maybe I'm doing it wrong, could you please explicate how exactly to use this fix? Thank you

I am getting the same thing. I think it might have to do with how git is installed, but I am a noob here so. Would be great if there is a solution to this.

**Comment by jclmnop** [comment]
> adding `-b 10000 ` did the trick for me but I somehow lost 3 sol in this whole process for 1845 images less than 370mb that should cost less than $4 based on arweavefees. Super doesn't make sense. How do I get those funds back?

Once you're finished with your candy machine use the withdraw command to close it and retrieve your funds.

**Comment by Fayramz** [comment]
hello guys, im trying to upload 8888 png and jsons but it seems supeeeeer sloww like 1 image per 10 minutes. How can i solve this problem plz. Would appreciate help... thank you

**Comment by jclmnop** [comment]
> hello guys, im trying to upload 8888 png and jsons but it seems supeeeeer sloww like 1 image per 10 minutes. How can i solve this problem plz. Would appreciate help... thank you

use a private RPC endpoint

if you want a decent free one try https://datahub.figment.io

**Comment by Fayramz** [comment]
> > hello guys, im trying to upload 8888 png and jsons but it seems supeeeeer sloww like 1 image per 10 minutes. How can i solve this problem plz. Would appreciate help... thank you
> 
> use a private RPC endpoint
> 
> if you want a decent free one try https://datahub.figment.io

Thank you for your response. I have a problem when i use this command 

"curl https://solana--devnet--rpc.datahub.figment.io/health -H Authorization: <myapikey>


 it says to me "{
  "message":"No API key found in request"
}curl: (6) Could not resolve host: \"

i dont know why, any idea bro ?

**Comment by jclmnop** [comment]
> > > hello guys, im trying to upload 8888 png and jsons but it seems supeeeeer sloww like 1 image per 10 minutes. How can i solve this problem plz. Would appreciate help... thank you
> > 
> > 
> > use a private RPC endpoint
> > if you want a decent free one try https://datahub.figment.io
> 
> Thank you for your response. I have a problem when i use this command
> 
> i have set the private RPC (devnet) but when i want to "solana airdrop 1" it gives me
> 
> "Error: RPC request error: cluster version query failed: error decoding response body: expected value at line 1 column 1"
> 
> any ideas ? with the default rpc it was working
> 
> even "solana balance" same error

If this is when using the datahub RPC, I think I had a similar issue. 

All I needed to do was add the API key to the url in my config because it wasn't included automatically.

**Comment by bernardiss** [comment]
Someone got the fiz?
