### ISSUE TITLE
Cannot create a candy machine with a price in a SPL token + SOLANA

### ISSUE THREAD

**Issue by Skowizzz** [metaplex-foundation/metaplex#1105]
Hello,

I am trying to create a presale candy machine, I will send a SPL token to all whitelisted users that they will use to mint their NFT.

That is why I would like to know how to create a candy machine that require for a mint 1 SPL Token + the NFT price in SOL.

Can you tell me how to do it, please !

**Comment by Skowizzz** [comment]
Can you help me please

**Comment by HereFrank** [comment]
Look this my friend:
