### ISSUE TITLE
Can anyone please help how can we remove/delete/burn partially sold candy machine created using Metaplex in Production?

### ISSUE THREAD

**Issue by ulu99** [metaplex-foundation/metaplex#1114]
Can anyone please help how can we remove/delete/burn partially sold candy machine created using Metaplex in Production?

**Comment by MarkSackerberg** [comment]
Just use the withdraw command

**Comment by MattiaLeoni** [comment]
Hi @ulu99 , were you able to do it? 
@MarkSackerberg Can you tell me more about how to use the withdraw command?
Thank you.

**Comment by MarkSackerberg** [comment]
https://docs.metaplex.com/create-candy/withdraw
