### ISSUE TITLE
Gumdrop - generate a single url for all whitelisted wallets

### ISSUE THREAD

**Issue by elliott-w** [metaplex-foundation/metaplex#1119]
Is there a way to generate a single url for all whitelisted wallets? When setting `--distribution-method wallets`, the gumdrop cli generates urls with `index` and `proof` query variables. However, because these variables are different for each handle/wallet, these URLs have to be distributed manually to every whitelisted user.

Could somebody please explain to me why these query variables are needed? Willing to go down the rabbit hole on this one, so would be appreciated if you could link any related resources (e.g. on Merkle trees).

Am I correct in assuming the fundamental problem is that it's too expensive to store all the the public keys of the whitelisted wallets on the blockchain?

If not, could I get some general pointers on how I would go about adding a whitelist of wallets when creating the candy machine?

**Comment by lwus** [comment]
It's certainly possible to just store a list of pubkeys on chain for a program to verify but that comes with high rent costs. In that case, a 'proof' is simply providing the offset into the list to find the matching Pubkey.

Gumdrop uses a merkle tree to compress all this information so it only needs to store a single 32-byte value on-chain to represent the whitelist. The tradeoff is that now the proof involves passing in more information (namely all the sibling hashes of the tree).

IIRC someone built a page that allows users to just search the list of urls (in the log files) for their specific URL.

**Comment by elliott-w** [comment]
Oh that tool sounds amazing. Are there any security risks associated with anybody being able to see the list of urls, or is it safe because you need to be the owner of the wallet to be able to claim the gumdrop?

**Comment by FeiShepherd** [comment]
Why not just store a hashmap on the front end of handles to index & proofs. then grab address from wallet adapter and do the look up. only downside of this is that whitelist addresses are exposed

**Comment by elliott-w** [comment]
@FeiShepherd because people can bypass the front end and interact directly with the blockchain without any restrictions

**Comment by FeiShepherd** [comment]
> @FeiShepherd because people can bypass the front end and interact directly with the blockchain without any restrictions

Yes, but the proof will fail.

**Comment by elliott-w** [comment]
> Yes, but the mint attempt will be rejected.

I think you are right because you need to sign the transaction as the owner of the wallet. However I would like to know for sure if this is safe and secure.

**Comment by swimalick** [comment]
Reopening since this wasn't clearly answered. I'm also wondering if it's secure to have a generic link that we can distribute to all our whitelisted users. 

In my mind, I'm thinking of creating a small WL redemption app where we store this mapping for every WL user:
```
{
  wallet_id: merkle_proof
}
```
If a user inputs their wallet ID, then the app fills in their corresponding merkle proof.

It's true that an attacker wouldn't be able to mint unless they have the passphrase of the WL wallet; but is there a different attack they could use if they have access to all of the WL wallet IDs, which would give them access to the merkle proofs?
