### ISSUE TITLE
signatureUnsubscribe error: Invalid subscription id.

### ISSUE THREAD

**Issue by zNiinZe** [metaplex-foundation/metaplex#1133]
**Hi iv just run into a problem not sure if its a bug or not  but i cannot process more than 9 files**

> 'C:\Users\ssebo\OneDrive\Desktop\sol\metaplex>ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet-test.json

> Beginning the upload for 10000 (png+json) pairs

> started at: 1638874040070

> wallet public key: **********************
> Processing file: 1045, 1939.png
> Processing file: 2043, 2837.png
> Processing file: 3044, 3738.png
> Processing file: 4046, 464.png 
> Processing file: 5044, 5538.png
> Processing file: 6045, 6439.png
> Processing file: 7045, 7339.png
> Processing file: 8046, 824.png
> Processing file: 9045, 9139.png'
> 

**and after the 9 it gives an 

> 'C:\Users\ssebo\OneDrive\Desktop\sol\metaplex\js\node_modules\node-fetch\lib\index.js:1461
>                         reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', `err));`
>           ^
> FetchError: request to https://api.devnet.solana.com/ failed, reason: socket hang up
>     at ClientRequest.<anonymous> (C:\Users\ssebo\OneDrive\Desktop\sol\metaplex\js\node_modules\node-fetch\lib\index.js:1461:11)
>     at ClientRequest.emit (node:events:390:28)
>     at ClientRequest.emit (node:domain:475:12)
>     at TLSSocket.socketOnEnd (node:_http_client:471:9)
>     at TLSSocket.emit (node:events:402:35)
>     at TLSSocket.emit (node:domain:475:12)
>     at endReadableNT (node:internal/streams/readable:1343:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   type: 'system',
>   errno: 'ECONNRESET',
>   code: 'ECONNRESET'
> }'

**sorry if its a obvious error I'm quite new to this**

**Comment by jclmnop** [comment]
Had the same issue. 

Change batch size to 10000 with `-b 10000` and see what happens then. Might take a while, and you might need to run it a few times (make sure you don't delete the cache) to upload all of them.

**Comment by zNiinZe** [comment]
> Had the same issue.
> 
> Change batch size to 10000 with `-b 10000` and see what happens then. Might take a while, and you might need to run it a few times (make sure you don't delete the cache) to upload all of them.

srry to bother but where would i config the batch size in the termial when running it or in a actual file? 
srry again...

**Comment by jclmnop** [comment]
> > Had the same issue.
> > Change batch size to 10000 with `-b 10000` and see what happens then. Might take a while, and you might need to run it a few times (make sure you don't delete the cache) to upload all of them.
> 
> srry to bother but where would i config the batch size in the termial when running it or in a actual file? srry again...

No worries man, you just need to add `-b 10000` to the end of your command. 

So your cmd would be:

```
'C:\Users\ssebo\OneDrive\Desktop\sol\metaplex>ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet-test.json -b 10000
```

Hope this helps.

**Comment by zNiinZe** [comment]
> > > Had the same issue.
> > > Change batch size to 10000 with `-b 10000` and see what happens then. Might take a while, and you might need to run it a few times (make sure you don't delete the cache) to upload all of them.
> > 
> > 
> > srry to bother but where would i config the batch size in the termial when running it or in a actual file? srry again...
> 
> No worries man, you just need to add `-b 10000` to the end of your command.
> 
> So your cmd would be:
> 
> ```
> 'C:\Users\ssebo\OneDrive\Desktop\sol\metaplex>ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet-test.json -b 10000
> ```
> 
> Hope this helps.
will try it, thx so much for the help so far. Much love
