### ISSUE TITLE
I cannot init my store

### ISSUE THREAD

**Issue by halimabergaoui** [metaplex-foundation/metaplex#114]
Hello, I am unable to init my store. I am always blocked in this page.

https://user-images.githubusercontent.com/16075710/124580366-f20e4d80-de47-11eb-8382-a9945306fa5a.mp4

Can anyone help me with this?

**Comment by MartinSchere** [comment]
How did you fix this?

**Comment by beepboprobop** [comment]
I've got the same issue, how to fix?

**Comment by halimabergaoui** [comment]
Hey,
You just need to change your network to testnet both in your chrome
extension and application.

Le dim. 12 sept. 2021 à 17:13, beepboprobop ***@***.***> a
écrit :
