### ISSUE TITLE
docs: add info on token burning

### ISSUE THREAD

**Issue by C0mberry** [metaplex-foundation/metaplex#1141]
add doc about token burning from this thread https://metaplex.slack.com/archives/C02CZC7THNX/p1637044419000600

**Comment by aheckmann** [comment]
I put a gist together to explain how to burn. Might help: https://gist.github.com/aheckmann/df6fdf795bb0843b4aea112b2b98a97e

**Comment by SolSister** [comment]
this looks done. can we close?
