### ISSUE TITLE
file size? 

### ISSUE THREAD

**Issue by KlausMillenial** [metaplex-foundation/metaplex#1187]
My goal is to deploy 10,000 NFT collection and it seems like I cannot run command "yarn build"  every single time I have more than 10 JSON PNG combo. 

I just succeeded running "yarn build" with only 1 json png combo, and I just don't know to fix this problem. 

Is it linked to each file size?? 

Each of mine is around 10MB. 

Thank you for your insight 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samuelvanderwaal** [comment]
It's unclear what exactly the error you're experiencing is. `yarn build` shouldn't be affected by the number of assets that you have and you should need to run that command anyway. You can use the candy machine cli by running it with `ts-node` without running `yarn build`. 

Can you provide more details on what you are doing and what is the error you are seeing?
