### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_bn')

### ISSUE THREAD

**Issue by zNiinZe** [metaplex-foundation/metaplex#1188]
**Hi im having a problem with the candy machine repo iv changed the .env.example to .env added my properties to the file and did yarn build / start and im getting this problem in react app not sure what im doin wrong since im quite new to this any help would be much appreciated**

> 32 | /**
  33 |  * A public key
  34 |  */
> 35 | export class PublicKey extends Struct {
  36 |   /** @internal */
  37 |   _bn: BN;

**And sometimes i get this in the terminal**

> Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by smidd47** [comment]
I am having this same error when trying to create_candy_machine

**Comment by qwrki** [comment]
Did you ensure that the timestamp was added?

**Comment by smidd47** [comment]
Adrian, thank you so much for reaching out. I cloned the updated repository
yesterday and everything works great now.

Regards,

Steven

**Comment by Deveshb15** [comment]
I still have this issue🤷‍♂️
![image](https://user-images.githubusercontent.com/72264218/148683364-2f60a94c-40db-4f49-80e9-9678c7936a07.png)

**Comment by huzefa69** [comment]
> I still have this issue🤷‍♂️ ![image](https://user-images.githubusercontent.com/72264218/148683364-2f60a94c-40db-4f49-80e9-9678c7936a07.png)

did u solve it?

**Comment by jignesh6990** [comment]
I'm also facing the same issue. Did we miss something?

![Screenshot 2022-04-01 115856](https://user-images.githubusercontent.com/4235471/161207574-4b30bdf2-438d-4505-923a-e9ff5d89cefd.jpg)

**Comment by Momentuuum** [comment]
I have the same issue, no solution... anyone solved this?
![image](https://user-images.githubusercontent.com/103331013/162585813-f00c87b5-2916-4b5c-bbcb-6c54c57b4bbc.png)

**Comment by JRB-y** [comment]
I have the same Issue anyone solve it ?

**Comment by ds-hamza** [comment]
Hello All..!

I was executing the following piece of code from the documentation ([Link](https://docs.metaplex.com/programs/auction-house/cli#execute-sale)) and getting this same error:

```
ts-node auction-house-cli.ts execute_sale
  -k ~/mywallet.key \
  -ah HsKwc8dQtm8KLxshw67dwsNePkH6wMXo5Lwn1FuKjVYVS \
  --buy-price 2 \
  --mint DCqt9QQ3ot3qv53EhWrYAWFuh4XgSvFJvLRjgsDnhLTp \
  --buyer-wallet 3DikCrEsfAVHv9rXENg2Hdmc16L71EjveQEF4NbSfRak \
  --seller-wallet CCJC2s8FDGAs8GqmngE9gviusEuNnkdUwchcYMZ8ZmHB \
  --token-size 1
```

I was able to fix this by adding a ```"\"``` after the execute_sale command

You should run the commands followed by a ```"\"```

i.e. in my case this should be

```
ts-node auction-house-cli.ts execute_sale \
  -k ~/mywallet.key \
  -ah HsKwc8dQtm8KLxshw67dwsNePkH6wMXo5Lwn1FuKjVYVS \
  --buy-price 2 \
  --mint DCqt9QQ3ot3qv53EhWrYAWFuh4XgSvFJvLRjgsDnhLTp \
  --buyer-wallet 3DikCrEsfAVHv9rXENg2Hdmc16L71EjveQEF4NbSfRak \
  --seller-wallet CCJC2s8FDGAs8GqmngE9gviusEuNnkdUwchcYMZ8ZmHB \
  --token-size 1
```

Replacing ```execute_sale``` with ```execute_sale \```  solved this error for me...
