### ISSUE TITLE
mainnet \ custom rpc upload error

### ISSUE THREAD

**Issue by genius665** [metaplex-foundation/metaplex#1189]
hello everyone, i have a problem, when i type this command:
`npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --keypair /Users/vts666/Desktop/NFT-custom/metaplex/wallet.json`

i get this error

```
(node:17685) UnhandledPromiseRejectionWarning: Error: The arweave-sol storage option only works on mainnet. For devnet, please use either arweave, aws or ipfs

    at Command.<anonymous> (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/src/candy-machine-cli.ts:121:13)
    at Command.listener [as _actionHandler] (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/node_modules/commander/lib/command.js:473:17)
    at /Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1173:65
    at Command._chainOrCall (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1091:12)
    at Command._parseCommand (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1173:27)
    at Command._dispatchSubcommand (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/node_modules/commander/lib/command.js:998:25)
    at Command._parseCommand (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1139:19)
    at Command.parse (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/node_modules/commander/lib/command.js:845:10)
    at Object.<anonymous> (/Users/vts666/Desktop/NFT-custom/metaplex/js/packages/cli/src/candy-machine-cli.ts:1173:4)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by samuelvanderwaal** [comment]
For devnet use a different storage option: `arweave-bundle` or `arweave` as `arweave-sol` doesn't work on devnet.

```bash
npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --keypair /Users/vts666/Desktop/NFT-custom/metaplex/wallet.json -s arweave-bundle
```

**Comment by amarjeet987** [comment]
Same here, getting this error. I tried implementing some other storages as well using --storage tag but it was showing errors too.

**Comment by seranotannason** [comment]
Try adding `--storage arweave`. @amarjeet987 What errors are you getting?

**Comment by amarjeet987** [comment]
It was causing this issue :
https://github.com/metaplex-foundation/metaplex/issues/1190

Deployed a fix for it just now and made a PR : 
https://github.com/metaplex-foundation/metaplex/pull/1194

**Comment by vts666** [comment]
> Try adding `--storage arweave`. @amarjeet987 What errors are you getting?

not working, same error

**Comment by amarjeet987** [comment]
@vts666 https://github.com/metaplex-foundation/metaplex/pull/1194/files try these changes.

**Comment by tka85** [comment]
@seranotannason Adding the `--storage arweave` resolved the initial `The arweave-sol storage option only works on mainnet...` error. 

And the [MR changes](https://github.com/metaplex-foundation/metaplex/pull/1194/files) solved the error the followed regarding duplicating the `.json` suffix:

```
ENOENT: no such file or directory, open '.../metaplex/js/packages/cli/kraken-assets/0.json.json'
```

**Comment by amarjeet987** [comment]
> @seranotannason Adding the `--storage arweave` resolved the initial `The arweave-sol storage option only works on mainnet...` error.
> 
> And the [MR changes](https://github.com/metaplex-foundation/metaplex/pull/1194/files) solved the error the followed regarding duplicating the `.json` suffix:
> 
> ```
> ENOENT: no such file or directory, open '.../metaplex/js/packages/cli/kraken-assets/0.json.json'
> ```
https://github.com/metaplex-foundation/metaplex/pull/1194/files try these changes.

**Comment by DutchKevv** [comment]
@seranotannason @amarjeet987 

Having the same problems (bit of a crypto noob though ...)

After fixing the errors, I get the double .json error also.. 

Should I wait until PR is merged? Don't wanna change source files because it gets deployed multi machine... 

Thanks

**Comment by amarjeet987** [comment]
> @seranotannason @amarjeet987
> 
> Having the same problems (bit of a crypto noob though ...)
> 
> After fixing the errors, I get the double .json error also..
> 
> Should I wait until [PR ](https://github.com/metaplex-foundation/metaplex/pull/1194/files)is merged? Don't wanna change source files because it gets deployed multi machine...
> 
> Thanks

PR is merge, you can pull the latest code from master branch

**Comment by vts666** [comment]
> @vts666 https://github.com/metaplex-foundation/metaplex/pull/1194/files try these changes.

after these changes, i have this error
`(node:1026) UnhandledPromiseRejectionWarning: Error: The file /Users/vts666/Desktop/NFT-custom/metaplex/assets/.DS_Store is not a supported file type.`

**Comment by vts666** [comment]
hello everyone, SOLUTION FOUND!! clone this repo
`git clone https://github.com/ashish140399/metaplex.git`, 0 ERRORS - works as it should

p.s. thx for help to everyone

**Comment by amarjeet987** [comment]
> > @vts666 https://github.com/metaplex-foundation/metaplex/pull/1194/files try these changes.
> 
> after these changes, i have this error `(node:1026) UnhandledPromiseRejectionWarning: Error: The file /Users/vts666/Desktop/NFT-custom/metaplex/assets/.DS_Store is not a supported file type.`

Check the files that you have inside your assets folder. They should be just pairs of supported assets (let's assume png files) and jsons, starting from 0 (0.png, 0.json) till (n-1) where n is the total number of assets. Try removing any other files if there are any.

**Comment by Theo4** [comment]
Same here, checked 3 times there is no hidden file on my assets/ folder and I got the same error : .DS_Store is not a supported file type

**Comment by systemtechs** [comment]
Open the  candy-machine-cli.ts ( or whatever .ts file you invoked) file and replace arweave-sol with arweave and save. This will then work

**Comment by vts666** [comment]
> Same here, checked 3 times there is no hidden file on my assets/ folder and I got the same error : .DS_Store is not a supported file type


try this flag "-b 5000" 
5000 - numbers of pares png+json

**Comment by guillemavila** [comment]
Probalby related, trying:
`ts-node src/candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair ~/.config/solana/[keypair-file].json --storage arweave-sol -c [cache-file]`

Output:
```
upload was not successful, please re-run. [Error: ENOENT: no such file or directory, stat 'assets/0'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'assets/0'
}
```

It seems `candy-machine-cli.ts` is missing file extensions at some point

**Comment by vts666** [comment]
> Probalby related, trying:
> 
> `ts-node src/candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair ~/.config/solana/[keypair-file].json --storage arweave-sol -c [cache-file]`
> 
> 
> 
> Output:
> 
> ```
> 
> upload was not successful, please re-run. [Error: ENOENT: no such file or directory, stat 'assets/0'] {
> 
>   errno: -2,
> 
>   code: 'ENOENT',
> 
>   syscall: 'stat',
> 
>   path: 'assets/0'
> 
> }
> 
> ```
> 
> 
> 
> It seems `candy-machine-cli.ts` is missing file extensions at some point

wrong PATH to ./assets

**Comment by guillemavila** [comment]
Thanks for the quick answer! Doesn't seem to fix it, same error using:
`/Users/[user]/[...]/metaplex/js/packages/cli/assets`
`~/[...]/metaplex/js/packages/cli/assets`
`./assets`
`assets`

Every time the error points to a path with no file extension, ending with /0 like:
```
upload was not successful, please re-run. [Error: ENOENT: no such file or directory, stat 
'/Users/[user]/[...]/metaplex/js/packages/cli/assets/0'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/[user]/[...]/metaplex/js/packages/cli/assets/0'
}
```

**Comment by vts666** [comment]
> Thanks for the quick answer! Doesn't seem to fix it, same error using:
> 
> `/Users/[user]/[...]/metaplex/js/packages/cli/assets`
> 
> `~/[...]/metaplex/js/packages/cli/assets`
> 
> `./assets`
> 
> `assets`
> 
> 
> 
> Every time the error points to a path with no file extension, ending with /0 like:
> 
> ```
> 
> upload was not successful, please re-run. [Error: ENOENT: no such file or directory, stat 
> 
> '/Users/[user]/[...]/metaplex/js/packages/cli/assets/0'] {
> 
>   errno: -2,
> 
>   code: 'ENOENT',
> 
>   syscall: 'stat',
> 
>   path: '/Users/[user]/[...]/metaplex/js/packages/cli/assets/0'
> 
> }
> 
> ```

1. Opel terminal in a folder "metaplex"
2. Use full path to candy-machine-cli.ts and assets
3. Pares png+json must be in a folder assets(not like assets/png and assets/json etc.)

ts-node ~/metaplex/js/packages/cli/src/candy-machine-cli.ts upload /metaplex/assets/ --env mainnet-beta --keypair ~/.config/solana/[keypair-file].json --storage arweave-sol -c [cache-file]

**Comment by amarjeet987** [comment]
> Same here, checked 3 times there is no hidden file on my assets/ folder and I got the same error : .DS_Store is not a supported file type

Open the .ts file that was invoked in this case, check what is default for the "storage" parameter there. Change the default storage to "arweave", or pass the parameter `--storage arweave` on executing the command from the CLI.

**Comment by amarjeet987** [comment]
@vts666 I'd suggest you consider reopening the issue since many are already facing similar issues.

**Comment by RushiChandalia** [comment]
hello there, as i am new to candy machine, i tested on devnet creating candy machine and minting and all, but when i tried on main-net with the flag --storage arweave-sol it uploaded the image but when i verified it, it threw an error saying "Name hello Items #2 with https://arweave.net/Aa3XNX2gtzXyDM8zfx16T8w5ebBtKz9yYALJaq_ylpE returned no json from link"
can anyone help me getting this error solved

**Comment by amarjeet987** [comment]
> hello there, as i am new to candy machine, i tested on devnet creating candy machine and minting and all, but when i tried on main-net with the flag --storage arweave-sol it uploaded the image but when i verified it, it threw an error saying "Name hello Items #2 with https://arweave.net/Aa3XNX2gtzXyDM8zfx16T8w5ebBtKz9yYALJaq_ylpE returned no json from link" can anyone help me getting this error solved

It's called `mainnet-beta` and not `main-net`. I guess, can you try it with this once.

**Comment by guillemavila** [comment]
> 1. Opel terminal in a folder "metaplex"
> 2. Use full path to candy-machine-cli.ts and assets
> 3. Pares png+json must be in a folder assets(not like assets/png and assets/json etc.)

Tried it all with full paths for `candy-machine-cli.ts` & `assets` folder (of course all named 0.png 0.json 1.png 1.json etc) again same error. It seems to come from candy-machine-cli.ts referencing a path with no file extensions

**Comment by eideri** [comment]
hey, im also new here and had the same error with candy-machine. Solved a part adding in the command -s but now a timeout is given. Seems the transaction is not confirmed. Any suggestions? Is different from all errors i have seen...

Processing asset: [object Object]
Rejecting for timeout...
Timeout Error caught { timeout: true }
Error uploading file [object Object] Error: Timed out awaiting confirmation on transaction

**Comment by KlausMillenial** [comment]
> hey, im also new here and had the same error with candy-machine. Solved a part adding in the command -s but now a timeout is given. Seems the transaction is not confirmed. Any suggestions? Is different from all errors i have seen...
> 
> Processing asset: [object Object] Rejecting for timeout... Timeout Error caught { timeout: true } Error uploading file [object Object] Error: Timed out awaiting confirmation on transaction

Hey, i'm still stuck at the DS_store cannot be found part, how did you solve it??

**Comment by eideri** [comment]
> > hey, im also new here and had the same error with candy-machine. Solved a part adding in the command -s but now a timeout is given. Seems the transaction is not confirmed. Any suggestions? Is different from all errors i have seen...
> > Processing asset: [object Object] Rejecting for timeout... Timeout Error caught { timeout: true } Error uploading file [object Object] Error: Timed out awaiting confirmation on transaction
> 
> Hey, i'm still stuck at the DS_store cannot be found part, how did you solve it??

Maybe referenced to a wrong path? I did not get that error anywhere

**Comment by Khushhal23** [comment]
Guys before u upload the assets, remove the .ds_store file, ur should not be there

**Comment by atenidegbeolanrewaju** [comment]
I had to reopen a keypair.json file manual at the mint directory cos it seems it never did create and I copied the list of numbers in the keypair.json file and vs code and paste it on the notepad I opened for the manually opened keypair.json. but I face a fresh error of FetchError

**Comment by Khushhal23** [comment]
@vts666 and others, just go to your config.json file and change the storage: arweave-sol to arweave
