### ISSUE TITLE
upload is expecting ".json.json" for the json files.

### ISSUE THREAD

**Issue by numisman** [metaplex-foundation/metaplex#1190]
**Describe the bug**
When you use the current master branch (#1172) and attempt to upload using the candy machine cli, you will encounter an error where the job is expecting a file with an extension of ".json.json"

**To Reproduce**
1. clone the current master
2. attempt to use the upload CLI
``` npx ts-node $CM_HOME/candy-machine-cli.js upload output --env $ENV --keypair $WALLET --log-level $LOGLEVEL --cache-name $CACHENAME --rpc-url $RPC_URL```
3. You will get an error 
``` upload was not successful, please re-run.  Error: ENOENT: no such file or directory, open 'assets\0.json.json'```

**Expected behavior**
.png and .json are uploaded to arweave successfully.

**Screenshots**
![ss_json_json](https://user-images.githubusercontent.com/87335441/145694094-a410f72b-f83c-46db-8411-c4d91ff672a0.png)

![ss_codeToFix](https://user-images.githubusercontent.com/87335441/145694120-02b660fe-1187-43d7-940d-7d6d09e6049c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave

**Comment by numisman** [comment]
The code screenshot is from metaplex/js/packages/cli/build/commands/upload.ts and shows where I think the change needs to be made.

**Comment by brantchoate** [comment]
same problem. when I remove the extra ".json" I get a timeout. Not sure if it's related or another problem I'm having. All of my other config was working before upgrading though

**Comment by anzeskulj02** [comment]
error can be fixed by changing 366 line in file js/packages/cli/src/commands/upload.ts to `assetKey.index,` . Error is now fixed

**Comment by stegaBOB** [comment]
Just merged in the fix. This issue should be resolved
