### ISSUE TITLE
Error: Transaction was not confirmed in 30.01 seconds

### ISSUE THREAD

**Issue by BeeBop21** [metaplex-foundation/metaplex#1206]
Hello. When running the upload ./assets cmd for mainnet-beta etc:
...Desktop\metaplex> 
ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair ~/config/solana/mainnet-beta.json
 
...the upload starts, and it runs like this for about 20 seconds...

  { mediaExt: '.png', index: '187' },
  { mediaExt: '.png', index: '188' },
  ... 257 more items

Then, the upload process just STOPS, and I get this exact message:
]
Saved bundle upload result to cache.
Computed Bundle range, including 66 file pair(s) totaling 99.212MB.
Uploading bundle... in multiple transactions
0.006340997 SOL to upload
upload was not successful, please re-run. Error: Transaction was not confirmed in 30.01 seconds. It is unknown if it succeeded or failed. Check signature (long tx hash)

Attempts: 
-Have rerun multiple times. 
-Deleted cache and rerun. 
-Saved, closed, rebooted and rerun. 

Note: The same process worked flawlessly during my devnet testing, but hangs when attempting to upload mainnet-beta.

If my SOL balance was the issue, then it should return that specific error, but am having trouble isolating 'transaction was not confirmed' etc

Help! Thanks.

**Comment by w4t3r-45** [comment]
any solutions ?? same problem here

**Comment by YosephAlves** [comment]
> Hello. When running the upload ./assets cmd for mainnet-beta etc: ...Desktop\metaplex> ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair ~/config/solana/mainnet-beta.json
> 
> ...the upload starts, and it runs like this for about 20 seconds...
> 
> { mediaExt: '.png', index: '187' }, { mediaExt: '.png', index: '188' }, ... 257 more items
> 
> Then, the upload process just STOPS, and I get this exact message: ] Saved bundle upload result to cache. Computed Bundle range, including 66 file pair(s) totaling 99.212MB. Uploading bundle... in multiple transactions 0.006340997 SOL to upload upload was not successful, please re-run. Error: Transaction was not confirmed in 30.01 seconds. It is unknown if it succeeded or failed. Check signature (long tx hash)
> 
> Attempts: -Have rerun multiple times. -Deleted cache and rerun. -Saved, closed, rebooted and rerun.
> 
> Note: The same process worked flawlessly during my devnet testing, but hangs when attempting to upload mainnet-beta.
> 
> If my SOL balance was the issue, then it should return that specific error, but am having trouble isolating 'transaction was not confirmed' etc
> 
> Help! Thanks.

Hey, you probably have a mainnet beta .cache file in .cache, you need to remove it from the folder.
