### ISSUE TITLE
Error: Token metadata account is not executable

### ISSUE THREAD

**Issue by gabrieldemian** [metaplex-foundation/metaplex#1208]
Hello! I'm creating my own program to mint NFTs using the [spl-token-metadata](https://crates.io/crates/spl-token-metadata) crate as a dependency.

But when I try to mint, an error occurs that says the token metadata account is not executable. This error happens when my contract calls the `create_metadata_accounts` of the token metadata program.

![image](https://user-images.githubusercontent.com/42912075/145894066-1d401b9e-306c-4bb0-9a97-e79242b2eb44.png)

The code where the error is happening
![image](https://user-images.githubusercontent.com/42912075/145894556-8b616844-a17d-4dec-85f6-138b10a89422.png)

Thanks in advance :)

**Comment by LambyPants** [comment]
@gabrieldemian did you ever figure this out?

**Comment by anoushk1234** [comment]
@LambyPants Did you manage to figure it out?

**Comment by aplimrek** [comment]
@LambyPants  and @anoushk1234 , is there any progress here?

**Comment by philetos** [comment]
@aplimrek @LambyPants @LambyPants could this be because you are testing in `localnet` and that `metaplex` program doesn't exist there? If so...try testing against `devnet`

**Comment by dcb9** [comment]
@philetos Is it possible to deploy token metadata account on localhost?
