### ISSUE TITLE
Error: The file assets/.DS_Store is not a supported file type. (Mac)

### ISSUE THREAD

**Issue by AchilleBS** [metaplex-foundation/metaplex#1215]
Hey, I just got this problem when using the command to upload my assets : 

% npx ts-node /~/solana-mint/metaplex/js/packages/cli/src/candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair /~/solana-mint/wallet.json

"**Error: The file assets/.DS_Store is not a supported file type.** 
    at /~/solana-mint/metaplex/js/packages/cli/src/candy-machine-cli.ts:177:15
    at Array.forEach (<anonymous>)
    at Command.<anonymous> (/~/solana-mint/metaplex/js/packages/cli/src/candy-machine-cli.ts:175:16)
    at Command.listener [as _actionHandler] (/~/solana-  mint/metaplex/js/packages/cli/node_modules/commander/lib/command.js:488:17)
    at /~/solana-mint/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/~/solana-mint/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/~/solana-mint/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/~/Desktop/solana-mint/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1050:25)
    at Command._parseCommand /~/solana-mint/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1193:19)
    at Command.parse (/~/solana-mint/metaplex/js/packages/cli/node_modules/commander/lib/command.js:897:10)"
    
In my assets file, there are only 10 .json and 10.png (from 0 to 9), 
I can not see the .DS_Store in the assets file. 
I tried this terminal command : defaults write com.apple.Finder AppleShowAllFiles TRUE;
And Restart it but it doesnt change the result, I don't have access to this field.

After some research, it looks like this is a Mac secret field automatically created to safe so parameters

I try to check, how does the candy-machine cli works to maybe find a solution this way
After excluding the JSON files, this "metaplex/js/packages/cli/src/candy-machine-cli.ts:177:15" check if all the fields are in the good format (jpeg, png,...) this .DS_Store is just breaking up the process because of his format
 
I tried to modifie the "metaplex/js/packages/cli/src/candy-machine-cli.ts" to make him accept this extension. It worked but obviously after this step, it does count 11 images for 10 json and return another error. 
 
I don't know if anyone got this problem recently, I guess a solution could be to add an function that make it ignore the DS_Store, for the count and for the build after. 

Maybe this is a recent problem, I could try to use old metaplex version maybe to verify it.

Thx for reading, if you have any idea to test I would be happy

**Comment by AchilleBS** [comment]
Nvm, I just "rm .DS_Store" it seems working

**Comment by pumapunks** [comment]
This should be ignored moving forward though.

**Comment by ck256-2000** [comment]
interesting - was running into the same problem again with CMv2.  This is as of 1/10/2022.

**Comment by Uranium94** [comment]
Hi Guys, anyone have a solution for this .DS_store error? Tried rm .DS_Store without any luck. Looked through apple hidden folders and only .png and .json files. Cannot find the .DS_Store file it's talking about? Any help appreciated.

**Comment by roederw** [comment]
This is fixed. Please pull `master` and try again.
