### ISSUE TITLE
Move ongoing / unstable development to a branch

### ISSUE THREAD

**Issue by brantchoate** [metaplex-foundation/metaplex#1253]
**Is your feature request related to a problem? Please describe.**
A very significant volume of help requests in Discord + Issues are related to people not understanding that "main" is an unstable state.  Even people with significant development chops are getting tripped up by this. It's not well explained.

**Describe the solution you'd like**
Move ongoing development to any other branch besides main. Make 1.0.0 -> main for the time being.

**Describe alternatives you've considered**
More broadly their could be semver introduced but that's a bigger undertaking. 

**Additional context**
Pop into "candy-machine" channel on Discord and you'll quickly see that 75% of problems are related to people not understanding their using the canary version of metaplex. It doesn't match with the tutorials they are following. And things are broken without any warning.

**Comment by stegaBOB** [comment]
This is something we are working on right now. It's easier said than done unfortunately. We are making a candy machine cli release that will be stable for the time being and plan to do the same for the rest of the Metaplex repos soon. Thanks for your feedback! Closing this issue.
