### ISSUE TITLE
Having an issue uploading new assets

### ISSUE THREAD

**Issue by thugrugs** [metaplex-foundation/metaplex#1260]
I've been getting this error for a few days trying to upload to arweave :    

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 14476 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d

**Comment by emersonthis** [comment]
Did you run the `upload` command once, and then add new files and run `upload` again?

I have the `v1.0.0` branch checked out and I get a very similar error when I do this. I'm not sure if this is the expected behavior or not. The only way I know to add additional files is by deleting the entire .cache/* file and starting over. (This will mean re-upload the previous assets and paying for arweave again.)

**Comment by stegaBOB** [comment]
I'm not entirely sure if the v1.0.0 branch even works right now. we are working on a new candy machine cli release branch that will replace the 1.0 and should fix all the uploading issues that people are having right now. I'm closing this issue. If you are still having this issue, please open a new one that includes more information by following the steps in the issue template.

**Comment by emersonthis** [comment]
> I'm not entirely sure if the v1.0.0 branch even works right now.

@stegaBOB what is the recommended branch that people should be currently using? The README made it seem like v1.0.0 was supposed to be the most stable release. But the docs mention features that aren’t in it. And your comment sounded surprised…

**Comment by stegaBOB** [comment]
> 

That's the issue we are working on fixing now. I don't think we have a recommended branch at the moment. That will change very soon though and the docs will be updated to reflect the new suggested branch. If you want to follow along with us we are working on perfecting this branch: https://github.com/metaplex-foundation/metaplex/tree/candy-machine-cli-v1.1.0

**Comment by emersonthis** [comment]
That’s great news. Thanks!
