### ISSUE TITLE
loading artwork is terribly slows

### ISSUE THREAD

**Issue by cormacncheese** [metaplex-foundation/metaplex#1264]
Every time I revisit my store it takes a solid 2-3 minutes to initialize my wallet and load all the artwork. My servers are fully upgraded.

Does anyone have a good way around this?

**Comment by numisman** [comment]
Following this.  It's really REALLY annoying.

**Comment by thatotherkid86** [comment]
Can confirm... locally it takes 2-3 minutes... on vercel... it won't even load... any updates on this?
