### ISSUE TITLE
No create_candy_machine in CLI v2

### ISSUE THREAD

**Issue by joshwolff1** [metaplex-foundation/metaplex#1265]
**Is your feature request related to a problem? Please describe.**
There is a `create_candy_machine` CLI command in v1

https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/candy-machine-cli.ts

**Describe the solution you'd like**
A `create_candy_machine` CLI command for v2

https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/candy-machine-v2-cli.ts

**Describe alternatives you've considered**
Reproducing v1, but the entire machine is stored differently in v1

**Additional context**
N/A

**Comment by garrettbear** [comment]
v2 the upload process also creates the candy machine. watch the office hours and jordan talks about it. also take a look at the docs for v2
