### ISSUE TITLE
using upload to increase more NFTs failed

### ISSUE THREAD

**Issue by RealSamwiseGamgee** [metaplex-foundation/metaplex#1267]
**Describe the bug**
Using upload to increase more NFTs failed

**To Reproduce**
1. copy 1 NFT in directory at first
2. exec candy_machine upload success
2. copy more NFT assets in directory
3. exec candy_machine upload failed with `Program log: panicked at 'range end index 731 out of range for slice of length 496', nft-candy-machine/src/lib.rs:320:18`

**Expected behavior**
Increase NFTs success, `max_number_of_lines` increase as the assets did

**Comment by stegaBOB** [comment]
You cannot increase the number of lines after the initial upload command. If you want to specify the number of NFTs for a config account, you can add `-n Number` to the upload command. This is a limitation of the way Solana account sizes are made. The size cannot be increased after being created.
