### ISSUE TITLE
Upload [object Object] error & Verify troubles

### ISSUE THREAD

**Issue by CryptoWrek** [metaplex-foundation/metaplex#1269]
**Describe the bug**
Fresh install of Metaplex (pulled the current version 3 hours ago), getting to the Upload phase and just running into a number of issues i'd never seen before. This is running Devnet, trying to upload 5 test files (0.png, 0.json through to 4). 

1) When I initiate upload, the "processing assets" just shows [object Object] rather than the relevant numbers
2) When it completes, it doesn't confirm success or failure
3) When I run Verify, it returns each as "non-200 from uploaded 404" then sets all my links to "null"

**To Reproduce**
Steps to reproduce the behavior, download a fresh Metaplex fork from the current build, install/update the latest Solana command lines, then run through steps per the website until the Upload phase

**Expected behavior**
(0,0) (1,1), etc
Success printout
Items to properly verify

**Screenshots**
![image](https://user-images.githubusercontent.com/94507159/146712819-a2a7eee3-a97e-4e32-ad76-53bbcdcf9b51.png)

![image](https://user-images.githubusercontent.com/94507159/146712681-5e339954-8a24-44ef-9bf6-10c709ff479b.png)

**Comment by CryptoWrek** [comment]
I semi-solved my problem as I wrote this issue log, but wanted to post it anyways to (a) help others, and (b) to keep this open and figure out the [object Object] thing.

So I was able to resolve the returning non-200 error that was "Null"ing out my links on Verify - I needed to change the "image.png" link in all my JSON files to say "0.png","1.png", etc. Doing that, I was able to get these uploaded and could mint the test images properly.

**Comment by indigofficial** [comment]
Hi there! 

I have the same issue - the odd thing is, I've run the same commands, (including creating and updating the Candy Machine) over ten times, so I don't know why the terminal is giving me this error now.

Also, if I update it from "image.png" to "0.png", etc. I'll have to do that for 5,000 images when I do it on the mainnet-beta. For now, I'm just testing with 5 PNG + JSON pairs on the devnet.

**Comment by jasonruncie** [comment]
My PR fixes the verify issues
https://github.com/metaplex-foundation/metaplex/pull/985

**Comment by TocoToucanMan** [comment]
I have the same issue.

**Comment by TocoToucanMan** [comment]
I'm pretty sure image.png shouldn't need to be changed in the off chain json, so hesitant to make that change.

**Comment by indigofficial** [comment]
Try this release: https://github.com/metaplex-foundation/metaplex/releases/tag/v1.0.0

**Comment by brettsloan** [comment]
To fix the [object Object] i had to add a '0.png' and '0.json' to my assets folder and that made it work.

I did not get 'Done. Successful = true' however I also did not get 'Upload unsuccessful'
I also got a Candy Machine Public Key so I'll let you know if it actually worked on my end

**Comment by brettsloan** [comment]
> Try this release: https://github.com/metaplex-foundation/metaplex/releases/tag/v1.0.0

Adding this tag to the current Master Branch worked for me! Thank you

**Comment by indigofficial** [comment]
> > Try this release: https://github.com/metaplex-foundation/metaplex/releases/tag/v1.0.0
> 
> Adding this tag to the current Master Branch worked for me! Thank you ![image](https://user-images.githubusercontent.com/25353203/147152927-1283c0c6-5610-4730-9ad2-df40ae1ca640.png)

No worries!
