### ISSUE TITLE
How to mint multiple tokens on tag v1.0.0

### ISSUE THREAD

**Issue by epomatti** [metaplex-foundation/metaplex#1274]
Hello

Following the [documentation](https://docs.metaplex.com/create-candy/mint-tokens#mint-multiple-tokens), I can see it is possible to use `mint_multiple_tokens` command in the candy-machine.

However, I'm using tag `v1.0.0` and this option is not there:

```
$ ts-node ./js/packages/cli/src/candy-machine-cli.ts mint_multiple_tokens --env devnet --keypair ... --number 2

error: unknown command 'mint_multiple_tokens'
```

What should I do in this situation where I have 10K+ tokens to mint? What are my alternatives?

The version of my candy-machine is `0.0.2`:

```
$ ts-node ./js/packages/cli/src/candy-machine-cli.ts --version
0.0.2
```

When listing the commands it is really not there. Only option is `mint_one_token`.

```
$ ts-node ./js/packages/cli/src/candy-machine-cli.ts -h
Usage: candy-machine-cli [options] [command]

Options:
  -V, --version                                      output the version number
  -h, --help                                         display help for command

Commands:
  upload [options] <directory>
  verify_token_metadata [options] <directory>
  verify [options]
  verify_price [options]
  show [options]
  create_candy_machine [options]
  update_candy_machine [options]
  mint_one_token [options]
  sign [options]
  sign_all [options]
  generate_art_configurations [options] <directory>
  create_generative_art [options]
  help [command]                                     display help for command
```

**Comment by epomatti** [comment]
Since no response came we decided to move to `CMv2` from `master` branch.

**Comment by srajeevan** [comment]
there is a mint_tokens function there.
i tried but i get a diff error.

**Comment by epomatti** [comment]
@srajeevan you should move to v2, I was able to deploy to mainnet with it.

v1 deprecates tomorrow.

**Comment by srajeevan** [comment]
I myself tried it today and it worked.
👍

**Comment by MoneshROR** [comment]
we need to pass  number of token we want upload nft 
This errore fix when we pass number of token we want to mint
 
npx ts-node /home/dell/Desktop/last_nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts mint_multiple_tokens     -e devnet     -k /home/dell/Desktop/last_nft/keypair.json -n 4

**Comment by Haseebshah936** [comment]
@MoneshROR is there a way that we can do multiple minting using candy machine v3 in javascript react/next.
