### ISSUE TITLE
The file assets/.DS_Store is not a supported file type.

### ISSUE THREAD

**Issue by KlausMillenial** [metaplex-foundation/metaplex#1279]
Everytime i hit command  **ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair /Users/.config/solana/devnet-.json**

i keep getting **The file assets/.DS_Store is not a supported file type.** error. 

What can I do???

**Comment by Theo4** [comment]
You have to remove the .DS_Store file which is not a supported extension/file.
It is a hidden file, so you will have to run a command to delete or display/remove it.

**Comment by zkhalapyan** [comment]
Yeh, just run `rm -rf .DS_Store` in your assets folder; would be nice to update the script to automatically figure this out.

**Comment by KlausMillenial** [comment]
> Yeh, just run `rm -rf .DS_Store` in your assets folder; would be nice to update the script to automatically figure this out.

Thank you I solved this issue by running "find . -name '.DS_Store' -type f -delete"
