### ISSUE TITLE
Shows image: "2.png" in metadata on arweave

### ISSUE THREAD

**Issue by AlexLup06** [metaplex-foundation/metaplex#1286]
When I upload the NFTs it should change the "2.png" to the url of the picture of the NFT. And it also does but only for the first 2 (0 and 1) but after that I just puts 2.png, 3.png etc. inside the metadata file.

Why is that happening and how do I fix that?

**Comment by bernardchanrcap** [comment]
I have the exact same problem. 

If I minted just 10, it seems to be fine. but anything more than 10, even if its 11: only the first 2 json is linked to the arweave link

**Comment by bernardchanrcap** [comment]
Any update on this. I simply can’t do anything if this isn’t fixed? 
metaplex?

**Comment by AlexLup06** [comment]
It is fixed. The candy machines were broken. Spend 5 hours in that discord yesterday to find out they are broken... Now everything works!!!
Overall Situation: https://hackmd.io/@dearsantanft/By5H5peiF
About v2: https://hackmd.io/@MarkSackerberg/candyV2

shouldn't be any problems now! The front end of the exiled apes does not work for v2 but everything is explained in those two articles!

**Comment by AlexLup06** [comment]
> Any update on this. I simply can’t do anything if this isn’t fixed?
> metaplex?

**Comment by AlexLup06** [comment]
> Any update on this. I simply can’t do anything if this isn’t fixed?
> metaplex?

It is fixed. The candy machines were broken. Spend 5 hours in that discord yesterday to find out they are broken... Now everything works!!!
Overall Situation: https://hackmd.io/@dearsantanft/By5H5peiF
About v2: https://hackmd.io/@MarkSackerberg/candyV2

shouldn't be any problems now! The front end of the exiled apes does not work for v2 but everything is explained in those two articles!
