### ISSUE TITLE
Artwork doesn't load in my wallet

### ISSUE THREAD

**Issue by Lopezz11** [metaplex-foundation/metaplex#1287]
**Describe the bug**
When I test the candy machine in solana devnet, at the time i mint it appears as succesfuly, but the artwork (png) doesn't load on my phantom wallet. (Everything else is fine, metadata shows up).

**To Reproduce**
1. Test candy machine on a Localhost

**Expected behavior**
It should mint succesfuly, then the NFT's artwork should appear in the wallet with their respective metadata

**Screenshots**
![image](https://user-images.githubusercontent.com/96498768/146993694-b34aabbd-4043-478a-ba73-4b18e88f44fc.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [96.0.4664.110]

**Comment by singularity-saggio** [comment]
I noticed this too. A few things i've noticed...if you look at the Token Metadata Standard (https://docs.metaplex.com/nft-standard) you will see a property for image which should resolve to the arweave image (url + png) :

"image": "https://www.arweave.net/abcd5678?ext=png"

But if you look up an example of what the CLI uploads, its missing that property all together https://solscan.io/token/D9DzKWmprE3N33PnxQz3eLX2JeQPe1G2xTFzAMNMLHc3?cluster=devnet#metadata

**Comment by singularity-saggio** [comment]
Make sure your json files are properly structured > each file should point SPECIFICALLY to the file it represents: https://docs.metaplex.com/create-candy/prepare-assets

**Comment by AlexLup06** [comment]
Hi, I have the same problem. The uri of the image doesn't get updated. It just says `"image": "2.png"` etc.. Or to be specific it says that for >1. For the first 2 NFTs it works like it should by replacing the 0.png an 1.png with the image uri. But for the upcoming ones it does not. I am so frustrated.

**Comment by Lopezz11** [comment]
I have to say that at the time I upload the assets no info from lamport costs from arweave pops up as it is shown in this yt video screenshoot.
![image](https://user-images.githubusercontent.com/96498768/147103589-e1e19aeb-f2a2-4d0a-8a2d-d1c324c6b611.png)

**Comment by Lopezz11** [comment]
Hi. I have found what was causing the problem. At the time I generated my NFTs with Hashlips art engine code, something gone wrong. I don't really know why, but my metadata references of the pics files weren't correct. The metada kept generating itself by applying "images.png" to all pics and not "1.png", "2.png", "3.png" and so...

My solution went through changing (main.js) that `image.png` with `${_edition}.png`, so the references were correct and... It worked!!
At the time I updated my assets with the new metadata to the candy machine and minted again in the devnet, artwork shows correctly!! Hope this helps anyone is reading

if (network == NETWORK.sol) {
    tempMetadata = {
      //Added metadata for solana
      name: tempMetadata.name,
      symbol: solanaMetadata.symbol,
      description: tempMetadata.description,
      //Added metadata for solana
      seller_fee_basis_points: solanaMetadata.seller_fee_basis_points,
      image: `${_edition}.png`,
      //Added metadata for solana
      external_url: solanaMetadata.external_url,
      edition: _edition,
      ...extraMetadata,
      attributes: tempMetadata.attributes,
      properties: {
        files: [
          {
            uri: "image.png",
            type: "image/png",
          },
        ],
        category: "image",
        creators: solanaMetadata.creators,
      },
    };
  }
  metadataList.push(tempMetadata);
  attributesList = [];
};

**Comment by catsonmats** [comment]
V2 or V1 of the cli?
