### ISSUE TITLE
Fresh clone of Metaplex can't build

### ISSUE THREAD

**Issue by summerplaybook** [metaplex-foundation/metaplex#1291]
Running yarn build crashes on a fresh clone after running yarn install

**To Reproduce**
- clone the repo
- run yarn in /js
- run yarn build in /js

**Screenshots**
See the screenshot below 

![Group 1 (7)](https://user-images.githubusercontent.com/12703955/147145475-a7daa635-49f8-4d3a-9c1a-e6d0a956f354.png)

I'm using Apple silicon on the new pro

**Comment by summerplaybook** [comment]
I've also downgraded my node to 16.1.0 and that hasn't allowed me to run it either

**Comment by bernardchanrcap** [comment]
Yup just tried to do a fresh clone. same problem

**Comment by summerplaybook** [comment]
toss me upvotes so we can get some help on this one. It's due to a ts error, but we should let the project owners make that change

**Comment by revnology** [comment]
same issue with 3 different pc

**Comment by MetaMarlo** [comment]
Same issue for me as well. Both OSX and Linux.

**Comment by revnology** [comment]
Temporary solved it by doing `git checkout 8ad311a4f1725b479d3bc84192286b0db1846d7a`

**Comment by JosephFerano** [comment]
Confirmed that commit `11c641c3  Bunch of fixes for entangler (#1283)` introduced this regression.

**Comment by xygz5f9vbkst** [comment]
also errors in the / js directory with the commands yarn install, yarn build, yarn bootstrap. on windows, product versions are the newest.

**Comment by PapaBearDoes** [comment]
Nothing to add troubleshooting wise other than a confirmation of inability to get past "yarn build" on a fresh clone.

**Comment by summerplaybook** [comment]
A fix i did was finding an older copy of the project and running it--but haven't found a fix for the latest

**Comment by stegaBOB** [comment]
This issue should be fixed. The latest version of metaplex builds properly. Closing this issue.
