### ISSUE TITLE
Allow Authority to mint ordered NFT on Candy Machine V2

### ISSUE THREAD

**Issue by AnderUstarroz** [metaplex-foundation/metaplex#1295]
Although  having the NFT shuffled to avoid bots predicting rare items is a great feature, most projects still want to be able to mint specific NFT before launch. But with CM2 the NFT are randomised even for the authority. That would be a step backwards from CM1, forcing users to create additional candy machines for such a common requirement.

**Proposed solution**

Mint NFT in order by default when using the Mint authority:
```
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts mint_one_token
```
and maybe add an additional parameter to **mint_one_token** like `-s, --shuffle` in case someone actually want to get random tokens, but I doubt it...

**Comment by AlexLup06** [comment]
Agree!

**Comment by peterschwarzdev** [comment]
Although I really like this new CM2, I also found this particular issue a step backwards.

**Comment by Inoublii** [comment]
It would be great to add the feature to mint specific id from terminal

**Comment by spreadmycode** [comment]
So, is there any solution to mint ordered?
Please help me.
I need to mint ordered to airdrop specific NFTs to some wallets.

**Comment by AnderUstarroz** [comment]
Metaplex guys didn't come back to us on this matter... Right now the only possibilities I know would be creating another candy machine V1 or mint manually 🤷‍♂️

**Comment by AnderUstarroz** [comment]
@spreadmycode I haven't done it manually but according some devs on discord (Metaplex channels) it shouldn't be too hard. But you probably don't even need to do that, if you are more used to CM2 and you just want to airdrop a bunch of NFTs to some addresses,  you  can just create a Candy Machine V2 and mint all items for free using the Mint Authority, then airdrop each NFT to his corresponding final owner.

**Comment by YrgkenKoutsi** [comment]
> @spreadmycode I haven't done it manually but according some devs on discord (Metaplex channels) it shouldn't be too hard. But you probably don't even need to do that, if you are more used to CM2 and you just want to airdrop a bunch of NFTs to some addresses, you can just create a Candy Machine V2 and mint all items for free using the Mint Authority, then airdrop each NFT to his corresponding final owner.

you still need to pay gas fee no?

**Comment by YrgkenKoutsi** [comment]
my question is: how much would it cost to make a CM2 and mint 1k+ NFTs and then airdrop them to the addresses on a snapshot list?
The initial idea was to make a CM2 and let the addresses from the snapshot list mint their own NFTs but this seems difficult with all the randomization in place

**Comment by AlexLup06** [comment]
> my question is: how much would it cost to make a CM2 and mint 1k+ NFTs and then airdrop them to the addresses on a snapshot list?
> The initial idea was to make a CM2 and let the addresses from the snapshot list mint their own NFTs but this seems difficult with all the randomization in place

It would cost 0.0012*1000=1.2Sol to mint those NFTs. If you just want to airdrop those NFTs then don’t use candy machine at all and just create the NFTs on the go for each. I mean you could just create your own candy machine program which does exactly what you want it to do. This shouldn’t be that hard because we have the CM code In the Metaplex and you will be able to copy most of the stuff and only change minor parts.

**Comment by YrgkenKoutsi** [comment]
> 



> > my question is: how much would it cost to make a CM2 and mint 1k+ NFTs and then airdrop them to the addresses on a snapshot list?
> > The initial idea was to make a CM2 and let the addresses from the snapshot list mint their own NFTs but this seems difficult with all the randomization in place
> 
> It would cost 0.0012*1000=1.2Sol to mint those NFTs. If you just want to airdrop those NFTs then don’t use candy machine at all and just create the NFTs on the go for each airdrop. I mean you could just create your own candy machine program which does exactly what you want it to do. This shouldn’t be that hard because we have the CM code In the Metaplex repo and you will be able to copy most of the stuff and only change minor parts.
> 
> I don’t even think it’s the on chain program that randomizes but just the script calling the program. So you would just be able to modify the script so it mints exactly the one you need.

Thank you for the quick reply! 

If I create my own candy machine program and do this wouldn't it charge me extra for uploading the images to the blockchain plus arweave fees? I am just trying to figure out which one is the easiest and cheapest way to do this since I am airdroping the nfts on a list of addresses

**Comment by summerplaybook** [comment]
has anyone found a way to do this manually?

**Comment by stegaBOB** [comment]
The solution to this would be to chain two candy machines together (the initial ones you want to mint) along with the random ones. Or mint the in order NFTs just individually. You can make them be in the same collection using our UI (https://collections.metaplex.com). A fix to allow this isn't something we have planned for the current candy machine v2, but may be something we do at some point in the future with a new machine potentially.

**Comment by stegaBOB** [comment]
> > my question is: how much would it cost to make a CM2 and mint 1k+ NFTs and then airdrop them to the addresses on a snapshot list?
> > The initial idea was to make a CM2 and let the addresses from the snapshot list mint their own NFTs but this seems difficult with all the randomization in place
> 
> It would cost 0.0012*1000=1.2Sol to mint those NFTs. If you just want to airdrop those NFTs then don’t use candy machine at all and just create the NFTs on the go for each airdrop. I mean you could just create your own candy machine program which does exactly what you want it to do. This shouldn’t be that hard because we have the CM code In the Metaplex repo and you will be able to copy most of the stuff and only change minor parts.
> 
> I don’t even think it’s the on chain program that randomizes but just the script calling the program. So you would just be able to modify the script so it mints exactly the one you need.

And it actually is the on chain program that randomizes it to clarify.

**Comment by AnderUstarroz** [comment]
> The solution to this would be to chain two candy machines together (the initial ones you want to mint) along with the random ones. Or mint the in order NFTs just individually. You can make them be in the same collection using our UI (https://collections.metaplex.com). A fix to allow this isn't something we have planned for the current candy machine v2, but may be something we do at some point in the future with a new machine potentially.

hey @stegaBOB regarding that link you mentioned [https://collections.metaplex.com](https://collections.metaplex.com), is there a way to create a collection NFT out of already existing collections?
