### ISSUE TITLE
hi i've been getting this issue when working on my cli on solana and metaplex 

### ISSUE THREAD

**Issue by TheRhythmicRhythm** [metaplex-foundation/metaplex#1297]
Compiled with problems:
X
ERROR in-/node_modules /@project- serum/anchor/dist/esm/program/ event . Js 2:0-33
Module not found: Error: Can't resolve 'assert' in 'D:\ole setupkcandy-ma cháne-ndnt -main\nodey nodules @project-serun .anchor\dist lesn\progran'
BREAKTNG CHANGE: Webpack « 5 used to include polyfills for node.js core modules by default.
Th2s 2s no longer the case. Verify if you need this module and configure polyf1ll for it.
If you want to include a polyfAl, you need to:
add a fallback resolve. fallback: ( "assert"; require.resolve("assert/") '
install "assert
If you don't want to include a polyfill, you can use an empty module 1ike this:
resolve.fallback: "assert" : false }
ERROR in -/node_modules/eproject-serum/anchor/dist/esm/provider.js 53:28-38
Module not found: Error: Can't resolve process' in "D: \mole setupleandy-machine-aint -nain\node nodulen @project-serum\anchor\dist \eam'
BREAKING CHANGE: Mebpack S used to include polyfills fon nodejs core modules by default
Th2s 1s no longer the cese. Verify 1f you need this module and configure apolyfill for it.
If you want to include polyl, you need to
dd a fallback resolve.fallback: process"i require.resolve ("process/browser") }'
insta11 proce
If you don't want to include polyfill, you can use an empty module 11ke this:
resolve,fallback: { "process"i false .

**Comment by harshkn** [comment]
Hi, I am facing the same issue. Any luck in resolving this ?

**Comment by adityabharadwaj198** [comment]
hey, were you able to fix this?
