### ISSUE TITLE
Candy Machine verified the result  shows 'key size 0' , was that normal?

### ISSUE THREAD

**Issue by huaming93** [metaplex-foundation/metaplex#1298]
> Key size 0
uploaded (666) out of (666)
ready to deploy!

BTW， when I started the fair lauch front end, I got an error here: 

> TypeError: Cannot read properties of undefined (reading 'slice')
(anonymous function)
src/WalletDialog.tsx:96
  93 | return (React.createElement(Dialog, Object.assign({ open: open, onClose: handleClose, className: styles.root }, props),
  94 |     React.createElement(DialogTitle, null,
  95 |         title,
> 96 |         React.createElement(IconButton, { onClick: handleClose },
     | ^  97 |             React.createElement(CloseIcon, null))),
  98 |     React.createElement(DialogContent, null,
  99 |         React.createElement(List, null,

**Comment by jeremybeal11** [comment]
Experiencing the same issue, on the latest branch: 

```
wallet public key: 5L...p5
Key size 0
uploaded (20) out of (20)
ready to deploy!
```

**Comment by kcsuden** [comment]
> Any update on this? Experiencing the same issue, on the latest branch:
> 
> ```
> wallet public key: 5L...p5
> Key size 0
> uploaded (20) out of (20)
> ready to deploy!
> ```

I am having the same issue. Help would be much appreciated

**Comment by stegaBOB** [comment]
Thats normal. It just means that all items have been successfully checked. Thats something that should be made more clear in our CLI logs. I'm planning on fixing that soon.
