### ISSUE TITLE
Blank homepage when there are no live auctions running

### ISSUE THREAD

**Issue by sultanpeyek** [metaplex-foundation/metaplex#130]
After **Participated Auctions** menu was implemented on `js/packages/web/src/views/home/index.tsx`. The homepage went blank when there are no live auctions running.

Maybe we can search for another alternative instead of showing the tab only when the are live auctions going.
Users should still be able to see **Ended Auctions** and **Participated Auctions** despite no live auctions running.

Before
```
{liveAuctions.length > 1 && (<Row> ... // show the tabs)
```

After **(TBD)**
```
// show all tabs by default
```

**Comment by bhgames** [comment]
I think we recently fixed this by showing the tabs even when there is only one auction, yeah? @sultanpeyek
