### ISSUE TITLE
Error installing yarn in metaplex / js directory

### ISSUE THREAD

**Issue by TonyZZZ13** [metaplex-foundation/metaplex#1301]
I use "Create a Solana NFT collection - Ultimate guide (devnet)." youtube https://www.youtube.com/watch?v=35RO0lAEIxE
Reproduced the following steps:
1. Installed node, git, visual studio code
2. npm install yarn
3. npm install -g ts-node
4. installed solana command line
5. solana config set --url https://api.mainnet.solana.com
6. solana config set --keypair ~ / .config / solana / mainnet-TEST.json
default key pair
7. go to the js catalog (cd js)
8. when executing the yarn install command, an error pops up, the screen is prefixed.

Guys help please how to fix this error?

Windows 10, Google Chrome version 96.0.4664.110 (Official assembly), (64 bit).
git - version 2.34.1.windows.1
npm - 8.1.2
node - v16.13.1
yarn - 1.22.17
ts-node - v10.4.0

![1111](https://user-images.githubusercontent.com/96183288/147348414-4ec43cb8-b428-46a2-8831-2f9ae079b163.png)

**Comment by Khushhal23** [comment]
Try do to npm install, or else, try changing the 6tg command to solana config set --keypair ~/.config/solana/mainnet-TEST.json

**Comment by Deveshb15** [comment]
even I'm facing the same issue any updates or fixes on this?

**Comment by TonyZZZ13** [comment]
> даже я столкнулся с той же проблемой, какие-либо обновления или исправления по этому поводу?

try to install yarn via git
