### ISSUE TITLE
Yarn install and build

### ISSUE THREAD

**Issue by caresseduvisage** [metaplex-foundation/metaplex#1303]
Hello everyone,

I have some issues going on on this version. I'm actually using ubuntu 20.04 LTS. With stable node js and npm. When i do "sudo yarn install" on cli folder i got those warning : 

warning "workspace-aggregator-11666114-0e18-4913-bd7a-b17c2acfb9a7 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-reserved-words@7.16.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-11666114-0e18-4913-bd7a-b17c2acfb9a7 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.16.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-11666114-0e18-4913-bd7a-b17c2acfb9a7 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-spread@7.16.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-11666114-0e18-4913-bd7a-b17c2acfb9a7 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.16.0" has unmet peer dependency "@babel/core@^7.0.0-0".

Then when i do "sudo yarn build" i got those issues that i didn't get before : 

2 declare module '@solana/web3.js' {
  ~~~~~~~

  ../../node_modules/@solana/web3.js/lib/index.d.ts:2:1
    2 declare module '@solana/web3.js' {
      ~~~~~~~
    Conflicts are in this file.

../../node_modules/@solana/web3.js/lib/index.d.ts:2:1 - error TS6200:

I'm going crazy.... Need some help 

Thanks,

**Comment by catsonmats** [comment]
`yarn add @babel/core @babel/preset-env`
