### ISSUE TITLE
NFT Image is not showing in SolScan or Phantom Wallet

### ISSUE THREAD

**Issue by saadqayyum-troon** [metaplex-foundation/metaplex#1305]
**Describe the bug**
Hello Everyone,
                         I am facing issue about NFT image is not showing up on Solscan or Phantom Wallet.

**To Reproduce**
In Metadata file as you can see in attached screenshot, image property value is image.png. It is not pointing to any url. I think thats why NFT Image is not loading.

**Expected behavior**
In Metadata file, image property should point to a valid url

![Capture](https://user-images.githubusercontent.com/95741641/147374931-2312ce7b-d4ab-4fa1-83f5-dd0d026ba1e4.PNG)

 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by guillemavila** [comment]
Make sure the values in the .json of each NFT are

```
...
  "image": "0.png",
...
        "uri": "0.png",
...
```

(or the corresponding number) instead of 

```
...
  "image": "image.png",
...
        "uri": "image.png",
...
```
