### ISSUE TITLE
Fair Launch TypeError. Doesnt launch correctly.

### ISSUE THREAD

**Issue by Fiercevd** [metaplex-foundation/metaplex#1306]
Fair Launch isn't work correctly.

When yarn start in the FLP folder there is an issue:

TypeError: Cannot read properties of undefined (reading 'slice')

![image](https://user-images.githubusercontent.com/96639493/147375618-1db97cb3-171a-427d-97f9-f6dfaffdf057.png)
![image](https://user-images.githubusercontent.com/96639493/147375625-92d5f8a2-7df6-4c8a-a306-6ddc02b9b0a3.png)

**Comment by catsonmats** [comment]
Also receiving this error. My steps:

1. Successfully run the upload command from the v2 cli
2. Input candy machine ID into the .env
3. Uncomment devnet options in .env, comment out mainnet options
4. yarn start
5. Successful start of dev server, try to reach localhost:3000, receive error

**Comment by guillemavila** [comment]
The problem comes when loading the canvas-confetti module. 
Don't want to submit a PR as this is not a _real_ fix, but you can circumvent the compiling error by editing the file `~/[...]/fair-launch/src/confetti.tsx` and adding `// @ts-ignore` right before `import confetti from 'canvas-confetti';`:

```
import confetti from 'canvas-confetti';    ->    // @ts-ignore
                                                 import confetti from 'canvas-confetti';
```

**Comment by trimpage** [comment]
@guillemavila i tried this but it still doesn't work

**Comment by Aaron-ATL** [comment]
@guillemavila @trimpage I am having the exact same issue. `Cannot read properties of undefined (reading 'slice')`

@guillemavila's fix did not work unfortunately. Why is this happening?

**Comment by JFK344** [comment]
Anyone managed to get it started ?

**Comment by akserikawa** [comment]
Having the same problem. @guillemavila fix doesn't work. Do you have any other ideas about what it might be causing this?

**Comment by limjame28** [comment]
im having the same trouble here

**Comment by epomatti** [comment]
same same, fresh from `master`

![image](https://user-images.githubusercontent.com/6530769/147439026-48e0814a-0350-4c45-b17f-95a44567bada.png)

**Comment by marcelc63** [comment]
Error comes from other folders, not fair-launch folder. Since its a monorepo ts checks for everything it seems.

Solution:
Copy paste fair-launch to a different directory and build separately

or checkout to this commit 56de262a3ea3f0f47d2f98d270e95085b25739b8

That works for me.

**Comment by epomatti** [comment]
> Error comes from other folders, not fair-launch folder. Since its a monorepo ts checks for everything it seems.
> 
> Solution: Copy paste fair-launch to a different directory and build separately
> 
> or checkout to this commit [56de262](https://github.com/metaplex-foundation/metaplex/commit/56de262a3ea3f0f47d2f98d270e95085b25739b8)
> 
> That works for me.

👎  This only lead me to another issue:

```
Failed to compile.

/extras/fair-launch/src/confetti.tsx
TypeScript error in /extras/fair-launch/src/confetti.tsx(2,22):
Could not find a declaration file for module 'canvas-confetti'. '/extras/fair-launch/node_modules/canvas-confetti/src/confetti.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/canvas-confetti` if it exists or add a new declaration (.d.ts) file containing `declare module 'canvas-confetti';`  TS7016

    1 | import React, { useContext, useEffect, useMemo, useRef } from 'react';
  > 2 | import confetti from 'canvas-confetti';
      |                      ^
    3 | 
    4 | export interface ConfettiContextState {
    5 |   dropConfetti: () => void;
```
![image](https://user-images.githubusercontent.com/6530769/147468951-09f761ad-c809-48e8-bb01-3ed04d72b756.png)

**Comment by akserikawa** [comment]
@epomatti Try what the error says ;) 

`npm i --save-dev @types/canvas-confetti`

**Comment by akserikawa** [comment]
It's seems it's an error known by the team, try running the frontend from this branch, instead of master

`git checkout fix-arweave-upload`
`yarn install`
`yarn start`

**Comment by epomatti** [comment]
@akserikawa yes did that, but still getting this:

![image](https://user-images.githubusercontent.com/6530769/147471321-c1853322-650b-4c1e-b21e-43d0845653f8.png)

**Comment by epomatti** [comment]
@akserikawa I also don't feel comfortable with using different branches for different modules.

I'm running a production project and the monorepo is supposed to keep everything compatible across the different modules, as everything depends pretty much on the candy machine behavior, and don't want to run into weird incompatibility scenarios.

Looking at the `fix-arweave-upload` name it doesn't look like it is related to at all to the problem we're facing, so I have no idea what it's in there.

If it if fixed, then why whoever did it didn't just create a small new branch and did the PR separately?

**Comment by akserikawa** [comment]
Totally agree with you. `master` branch should have working, deployable code. 

But it seems the team knows about the issue and I guess they will work on it.

For now, I got it working extracting the whole `fair-launch` folder from the `fix-arweave-upload` branch to my own repository and installing the confetti package with `npm i --save-dev @types/canvas-confetti`

**Comment by marcelc63** [comment]
> > Error comes from other folders, not fair-launch folder. Since its a monorepo ts checks for everything it seems.
> > Solution: Copy paste fair-launch to a different directory and build separately
> > or checkout to this commit [56de262](https://github.com/metaplex-foundation/metaplex/commit/56de262a3ea3f0f47d2f98d270e95085b25739b8)
> > That works for me.
> 
> 👎 This only lead me to another issue:
> 
> ```
> Failed to compile.
> 
> /extras/fair-launch/src/confetti.tsx
> TypeScript error in /extras/fair-launch/src/confetti.tsx(2,22):
> Could not find a declaration file for module 'canvas-confetti'. '/extras/fair-launch/node_modules/canvas-confetti/src/confetti.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/canvas-confetti` if it exists or add a new declaration (.d.ts) file containing `declare module 'canvas-confetti';`  TS7016
> 
>     1 | import React, { useContext, useEffect, useMemo, useRef } from 'react';
>   > 2 | import confetti from 'canvas-confetti';
>       |                      ^
>     3 | 
>     4 | export interface ConfettiContextState {
>     5 |   dropConfetti: () => void;
> ```
> 
> ![image](https://user-images.githubusercontent.com/6530769/147468951-09f761ad-c809-48e8-bb01-3ed04d72b756.png)

Ok ill delete my answer

**Comment by beaubrewer** [comment]
I can confirm the steps posted by @akserikawa worked for me. Not a great solution, but the best option we have at the moment to mint with CMv2.

**Comment by guillemavila** [comment]
> The problem comes when loading the canvas-confetti module. Don't want to submit a PR as this is not a _real_ fix, but you can circumvent the compiling error by editing the file `~/[...]/fair-launch/src/confetti.tsx` and adding `// @ts-ignore` right before `import confetti from 'canvas-confetti';`:
> 
> ```
> import confetti from 'canvas-confetti';    ->    // @ts-ignore
>                                                  import confetti from 'canvas-confetti';
> ```

A detail I ignored and might be important: I've copied the fair-launch folder in another location, which is what I'm deploying to cloudflare pages.
@MarkSackerberg explains a possible [solution here too](https://hackmd.io/@MarkSackerberg/candyV2#TypeError-Cannot-read-properties-of-undefined-reading-‘slice’--FLP-Frontend-not-working).

**Comment by unboxedsolutions** [comment]
> @MarkSackerberg explains a possible [solution here too](https://hackmd.io/@MarkSackerberg/candyV2#TypeError-Cannot-read-properties-of-undefined-reading-%E2%80%98slice%E2%80%99--FLP-Frontend-not-working).

`Remote branch fix-arweave-upload not found in upstream origin`

**Comment by nikhilm056** [comment]
It seems like the branch fix-arweave-upload is no longer available and master is still not working. @akserikawa If possible, can you please share the working copy of the fair-launch folder on some secure location? That would be really helpful for the other developers as well.

**Comment by devcodeash** [comment]
I copied fair-launch folder to another location then deleted node_modules and did
`yarn install`
`yarn add @types/canvas-confetti --dev`
now minting is working

**Comment by unboxedsolutions** [comment]
> I copied fair-launch folder to another location then deleted node_modules and did `yarn install` `yarn add @types/canvas-confetti --dev` now minting is working

Follow those steps, then moved the folder back and it works.
Thanks!

**Comment by nikhilm056** [comment]
Yes, now it's working for me as well. Thank you @devcodeash !
