### ISSUE TITLE
ts-node candy ts-node candy-machine-v2-cli.ts

### ISSUE THREAD

**Issue by caresseduvisage** [metaplex-foundation/metaplex#1310]
Hello,

I have this issue after downloading the last version of the project. I'm on Ubuntu 20.04 after yarn install and build (all was going well). Then when i'm trying to upload i have this :
--------------------------------------
sudo ts-node candy-machine-v2-cli.ts upload /home/test/test/assets/ --env devnet --keypair /home/test/test/wallet/test.json 
wallet public key: ****************************************************************************
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at getCandyMachineV2Config (/home/test/metaplex-master/js/packages/cli/src/helpers/various.ts:49:27)
    at Command.<anonymous> (/home/test/metaplex-master/js/packages/cli/src/candy-machine-v2-cli.ts:98:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
 code: 'ERR_INVALID_ARG_TYPE'
}
--------------------------------------

Could you help me pls ?

thx,

**Comment by sefayasar** [comment]
Heyy , your uplaod command should look like smthng like this;
sudo ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet  -k ~/.config/solana/devnet.json -cp config.json -c example  /home/test/test/wallet/test.json

Make sure you edit your config.json correctly and you are on the metaplex folder directory
Regards..

**Comment by caresseduvisage** [comment]
Thx Sefayasar,

But nothing changes i moved my key to ~/.config/solana/ and did your command but the command asked me the path for my assets and : sudo ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload /home/test/test/assets -e devnet -k ~/.config/solana/test.json

But same error : The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

Where i need to configure the config.json and what is it for ? 

Thx again

**Comment by caresseduvisage** [comment]
> Heyy , your uplaod command should look like smthng like this; sudo ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp config.json -c example /home/test/test/wallet/test.json
> 
> Make sure you edit your config.json correctly and you are on the metaplex folder directory Regards..

**Comment by sefayasar** [comment]
You can find the all necessary infos about creating your config in this link:
https://docs.metaplex.com/candy-machine-v2/Configuration
I recommend you to follow this helpful dev document for every step.
Merry Christmas ...
