### ISSUE TITLE
Candy Machine ID is not shown up after succesful upload

### ISSUE THREAD

**Issue by sefayasar** [metaplex-foundation/metaplex#1311]
I am currently using candy_machine_V2 . After uploading assets and verifying succesfully , only candy machine config is created. I can see no CM ID. I checked the cache but there is only CM config exists related to CM. I am on devnet.
Any help is appreciated.

**Comment by matthews-code** [comment]
have u found a solution to this? having the same problemr right now..

**Comment by sefayasar** [comment]
There is no create candy machine anymore sir. When you upload it will be created already

**Comment by londonbridges13** [comment]
> There is no create candy machine anymore sir. When you upload it will be created already

But how do you get the candy_machin_id for the mint website?

**Comment by skimaharvey** [comment]
having the same problem

**Comment by alicantutumlu** [comment]
same problem. Is there anybody solve?

**Comment by londonbridges13** [comment]
use candy machine v2 builder from soul dogs:
https://github.com/Soul-Dogs-City/candy-machine-v2-mint

They only require the candy machine config that will be generated from the upload (inside the .cache/ temp file)
