### ISSUE TITLE
Can't find my upload links

### ISSUE THREAD

**Issue by caresseduvisage** [metaplex-foundation/metaplex#1315]
Hello guys,

![image](https://user-images.githubusercontent.com/63931199/147405389-b303f4eb-8281-4c96-9ddd-c406d2a53df3.png)

My upload was successful, but the command doesn't show me any links ? Where can i find the cache file created when i did the upload command ? Please

Thx alot,

**Comment by Khushhal23** [comment]
The .cache file would be in the metaplex folder only, u can try too tuck the option that allows to view hidden files, cause .cache file can be hidden too
