### ISSUE TITLE
The NFT minting has stopped working. "Unable to fetch balance changes"

### ISSUE THREAD

**Issue by glbk17** [metaplex-foundation/metaplex#1316]
Mint was working fine for 2 weeks, recently had a problem with RPC, solved by switching to RunNode. For three days everything was fine, and I can't check NFT again, I keep getting the error "Unable to fetch balance changes" when I connect, what could this be about?

The console gives this error "findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference."

![image](https://user-images.githubusercontent.com/96689560/147410287-cdcd2546-cbc8-465b-b4d7-83506e19e406.png)
![image](https://user-images.githubusercontent.com/96689560/147410297-626755ef-8900-4f3a-8d9d-13d6d2bd7ce4.png)

**Comment by Khushhal23** [comment]
Check your .env file if the host is correct or not, sometimes the default host blocks the dapp

**Comment by glbk17** [comment]
> Check your .env file if the host is correct or not, sometimes the default host blocks the dapp

Checked and changed to another, the problem remained.

**Comment by glbk17** [comment]
A solution to the problem was found:
1- Change the RPC to https://solana-api.projectserum.com/ either the API from quicknode.com or runnode.com
2- Mint 1 NFT via CLI using the command: npx ts-node js/packages/cli/src/candy-machine-cli.ts mint_one_token --env mainnet-beta --keypair ~/.config/solana/main.json
3- If you get an error refill your SOL purse with an amount higher than the NFT coin value. And try again.
