### ISSUE TITLE
Replace ensureWrappedSolAccount with an ATA implementation

### ISSUE THREAD

**Issue by bhgames** [metaplex-foundation/metaplex#132]
Lots of places where we create auxiliary wrapped sol accounts instead of using an ATA based SOL account. Need to switch to using the ATA version. It's a bit more legwork to use but people are ending up with half a dozen of these random sol accounts sometimes when txns dont finish and cleanup doesn't happen. Let's clean it up.

**Comment by jordansexton** [comment]
Closed as stale per discussion with @bhgames.
