### ISSUE TITLE
Why is it so expensive for uploading assets ? 

### ISSUE THREAD

**Issue by shingsoso** [metaplex-foundation/metaplex#1320]
Why is it so expensive for uploading assets ?

**Comment by Khushhal23** [comment]
U can reduce the rent of candy machine from 2 years to 1 month or something according to ur needs

**Comment by epomatti** [comment]
@Khushhal23 can you provide link to the docs where it talks about it?

**Comment by Khushhal23** [comment]
@epomatti Here's an article - hackmd.io/@hnbl/hector

**Comment by epomatti** [comment]
@Khushhal23 the rent should be a parameter in the candy machine, why would someone hardcoded it at random 2 years and not even document it?

Is there anything about this in the official docs? I couldn't find.

**Comment by SeanOverton** [comment]
Not that I have found @epomatti took me a a bit of digging to realise this too. I accept the above link as the official docs XD
