### ISSUE TITLE
Error uploading file Error: Timed out awaiting confirmation on transaction

### ISSUE THREAD

**Issue by shingsoso** [metaplex-foundation/metaplex#1321]
I am trying to upload my assets with the metaplex upload command. 
But some files fails to upload with following message : "Error uploading file Error: Timed out awaiting confirmation on transaction". 

What should I do on the failed files ? How can I reload them ?

**Comment by TriEdgeAI** [comment]
Same shit. I also get Processing asset: [object Object], which seems like a bug.

**Comment by Khushhal23** [comment]
The processing asset: [object Object] is not a bug..@shingsoso could you please show the command u used

Make sure the paths are correct, and --env mainnet-beta or devnet is there

**Comment by TriEdgeAI** [comment]
Using v1.0.0 helped with the timeout.

**Comment by Khushhal23** [comment]
@shingsoso Try contacing your rpc provider

**Comment by emersonthis** [comment]
I'm getting this same error using v2.

**Comment by emersonthis** [comment]
I think this is a duplicate of: https://github.com/metaplex-foundation/metaplex/issues/949
