### ISSUE TITLE
Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by calcajack3** [metaplex-foundation/metaplex#1322]
##  Cannot read properties of undefined (reading 'slice')

I was following the 'candy machine V2' tutorial on the metaplex docs to create a fair launch

Every step worked since the last one, when the guide says to run `yarn install` and `yarn start`
when the browser opens it gave me this error 
![image](https://user-images.githubusercontent.com/96479697/147417539-eaeb8078-56f8-4956-933a-346b7617a96e.png)

I have done all the previous step exactly

**Desktop**
 - OS: Windows 11
 - Browser: Brave
- Version: 1.33.106 (Chromium: 96)

**Comment by limjame28** [comment]
i have the same issue here

**Comment by ludusdigital** [comment]
Try to run **npm install**

**Comment by devansh-chotai** [comment]
> Try to run **npm install**

Thanks! that works

**Comment by calcajack3** [comment]
> Try to run **npm install**

i did it but it tells me that is already installed

**Comment by Blueberry94** [comment]
For starting the server in development mode you should go with npm start. 

Worked for me too. Thanks a lot!

**Comment by HaoCherHong** [comment]
This is due to fair launch is depending on `@solana/wallet-adapter-react@0.13.1`
while some other dependencies are using `@solana/wallet-adapter-react@0.7.2`.
you can see that by using the following command:
```
yarn list @solana/wallet-adapter-react
```
multiple instances of `wallet-adapter-react` is created, so `WalletProvider` is not working.

**Comment by ck256-2000** [comment]
> Try to run **npm install**

thanks for this  - worked on my end as well!
