### ISSUE TITLE
CMv2 verify --config-path not available

### ISSUE THREAD

**Issue by epomatti** [metaplex-foundation/metaplex#1323]
In the [CMv2 Verfiy](https://docs.metaplex.com/candy-machine-v2/VerifyUpload) documentation there should be an option to set the `--config-path`:

![image](https://user-images.githubusercontent.com/6530769/147418959-4e627689-8edc-434d-8def-b2daf84b4cd7.png)

I got the code fresh from `master`.

However, this is not the case when executing CM:

```sh
$ ts-node ./js/packages/cli/src/candy-machine-v2-cli.ts verify \
>   --env "..." \
>   --keypair "..." \
>   --config-path "config.json"

error: unknown option '--config-path'
```

Output when running `ts-node ./js/packages/cli/src/candy-machine-v2-cli.ts verify -h`:

```
Usage: candy-machine-v2-cli verify [options]

Options:
  -e, --env <string>         Solana cluster env name (default: "devnet")
  -k, --keypair <path>       Solana wallet location (default: "--keypair not provided")
  -l, --log-level <string>   log level
  -c, --cache-name <string>  Cache file name (default: "temp")
  -r, --rpc-url <string>     custom rpc url since this is a heavy command
  -h, --help                 display help for command
```

**Comment by epomatti** [comment]
Same problem with `candy-machine-v2-cli.ts show`

**Comment by stegaBOB** [comment]
The config file is only used to set the candy machine up and shouldn't be needed during minting.

**Comment by epomatti** [comment]
Opened an issue on the docs repository, linking here to close both when fixed.

https://github.com/metaplex-foundation/docs/issues/122

**Comment by epomatti** [comment]
Update, I can confirm that removing `-cp` allowed me to mint the tokens. Closing this since only the documentation needs to updated.

**Comment by CryptoPique** [comment]
did you guys found how to fix this issue:
error: required option '-cp, --config-path <string>' not specified
when trying to upload nft ?

**Comment by hunlaca** [comment]
> did you guys found how to fix this issue: error: required option '-cp, --config-path ' not specified when trying to upload nft ?

I have the same issue please tell me the solution if you have worked it out.

**Comment by nthprime** [comment]
read the docs : https://docs.metaplex.com/candy-machine-v2/Configuration

**Comment by YosephAlves** [comment]
Hi guys, it's simple. Just create a configpath,json file with this code inside. change the parameters to yours and that's it `{
    "price": 1.0,
    "number": 10,
    "gatekeeper": null,
    "solTreasuryAccount": "<YOUR WALLET ADDRESS>",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "25 Dec 2021 00:00:00 GMT",
    "endSettings": null,
    "whitelistMintSettings": null,
    "hiddenSettings": null,
    "storage": "arweave-sol",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}`

**Comment by bigsecret17** [comment]
Hello guys, please please help if you have the solution. i keep getting error: required option '-cp, --config-path <string>' not specified. I will give you my nft once its been deployed. Thank you this community is filled with amazing people!

**Comment by SolSecSociety** [comment]
> Hello guys, please please help if you have the solution. i keep getting error: required option '-cp, --config-path ' not specified. I will give you my nft once its been deployed. Thank you this community is filled with amazing people!

When you launch the upload command? this mean that the Candy Machine can't find your config.json file and so it can't read your configuration setting, you jsut need to specify the path, so just add it like this to your upload command: 

-cp ~/metaplex/js/packages/cli/config.json
