### ISSUE TITLE
To add more items to a collection gives errors in a candy machine

### ISSUE THREAD

**Issue by sissi-luaty** [metaplex-foundation/metaplex#1327]
**The commands verify and create_candy_machine fail after upload of two sets of images**
When we upload the 1st part of a collection, and then create candy machine, if we upload the 2nd part of the collection, then candy machine gives various errors. The files were uploaded with success to arweave, and the fees were paid, but the candy machine does not work.

**To Reproduce**
steps to reproduce the behavior:
1. install node, git, solana-cli, and metaplex;
2. create a wallet through command line:
$ solana-keygen new --outfile key.json
$ solana config set --keypair key.json
3. create assets folder with 0-{n-1} pngs and jsons;
4. upload images:
$ ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets/ --env mainnet-beta --keypair key.json
5. create the candy machine:
$ ts-node js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env mainnet-beta --keypair key.json --price 0.7
6. add items to ./assets/ folder between n and m-1, such that it will contain m items;
7. upload the next images:
$ ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets/ --env mainnet-beta --keypair key.json
8. then there are errors:
i.: with verify cmd we get the error: "ERROR: not all NFTs checked out"
ii.: with create_candy_machine cmd we get the error: "ERROR: account address {...} already in use".
The m images and the candy machine become unusable, even though they are registered on arweave and the fees were paid.

**Expected behavior**
We expected that the full images would be usable through the candy machine.

**Screenshots**
![cropped](https://user-images.githubusercontent.com/47221009/147490045-0716011b-c8b6-4bc5-ab62-cc9e41c6c636.png)
"ERROR: not all NFTs checked out"

![screenshot_20211226_232231](https://user-images.githubusercontent.com/47221009/147490073-dc62025f-0e18-4f0a-95f4-1891671eb8d5.png)
"ERROR: account address {...} already in use"

**Desktop (please complete the following information):**
 - OS: linux kubuntu 20.04
 - browser: chrome

**Additional context**
I tried to upload the full collection, but I got a different error related to the payments fees... That's why I split the collection in two parts. Since the fees for all the images are paid (in a total of ~190€) and all the images are registered in the arweave and solscan I expect that there should be possible to gain access of the images through the candy machine. I have checked that all the images and their URLs in arweave are registered in ./.cache/mainnet-beta-temp.json .
The main problem is that I dont't want to let the full collection of images on the blockchain or arweave to be lost without usage. I hope that there is a fix to this.
I hope that there is a way to deactivate the 1st candy machine, and to create an updated candy machine with a different address such that the full project would be ok.
Thank you.

**Comment by overdeveloping** [comment]
Unfortunately, I don't think there is a way to deactivate the candy machine on the blockchain, however, you can initiate the candy machine withdraw command and get some money back if there is SOL in the candy machine, then you can start the process over again with new upload and new candy machine.

**Comment by sissi-luaty** [comment]
Thanks for the reply. I have tried to re-initiate the full process with a different account but I got the ERROR: "server responded with 429 too many requests".
As the images were already uploaded in the 1st account there should be a way to use them...

**Comment by overdeveloping** [comment]
> Thanks for the reply. I have tried to re-initiate the full process with a different account but I got the ERROR: "server responded with 429 too many requests". As the images were already uploaded in the 1st account there should be a way to use them...

I don't know if you can use images uploaded in the first account, maybe someone with more experience with Metaplex could answer that. For that you can try going on the [Discord](https://discord.gg/bBCvp6z69v) server, much more active there.
But with the 429 too many requests error it may be rate limits, you just need a custom RPC with a bigger limit to upload all of them again.

**Comment by lefeverela** [comment]
Have you ever found how to solve that issue?
