### ISSUE TITLE
Errors in Yarn Start 

### ISSUE THREAD

**Issue by Rickyn13** [metaplex-foundation/metaplex#1330]
Hi, 

I just did yarn start but i get this error and not sure what i need to do?
<img width="1436" alt="Screen Shot 2021-12-28 at 3 47 37 PM" src="https://user-images.githubusercontent.com/48068340/147522423-eca46948-1206-40bf-91c8-68e8d4da9b11.png">

**Comment by Khushhal23** [comment]
I suppose you are doing this in the candy machine mint folder.

U can delete all the node modules, reinstall them

**Comment by Rickyn13** [comment]
Yes got this working now thank you
