### ISSUE TITLE
Metaplex- How to use hiddenSettings in Candy Machine V2? 

### ISSUE THREAD

**Issue by Rana-xD** [metaplex-foundation/metaplex#1331]
I try to look at https://docs.metaplex.com/candy-machine-v2/Configuration. 
I am not clear about hiddenSetting part 

```
"hiddenSettings": {
    "name":"My Hidden Collection ",
    "uri":"uri",
    "hash":"44kiGWWsSgdqPMvmqYgTS78Mx2BKCWzd"
}
```
Regarding **hash**, is it random generate 32 character string or do we have to take it from another file? 

Another question.
Can I get sample code or step for off-chain process to update the metadata for each item after the mint is complete? 

Thank you

**Comment by kyanokashi** [comment]
Following this

**Comment by Executyr** [comment]
Hello, do you eventually got an answer?

**Comment by HaoCherHong** [comment]
I think the hash is not used at all according to the current source code on `master` branch.

**Comment by tserevE8848** [comment]
Hey guys do you know how to reveal after using hiddensetting?

**Comment by HaoCherHong** [comment]
> Hey guys do you know how to reveal after using hiddensetting?

I use a custom version of candy machine v2 to let metadata uri to have number appended to the base url.
like `https://example.com/token/1`
then update the response json when I want to reveal

**Comment by SolProtection** [comment]
> > Hey guys do you know how to reveal after using hiddensetting?
> 
> I use a custom version of candy machine v2 to let metadata uri to have number appended to the base url. like `https://example.com/token/1` then update the response json when I want to reveal.
> 
> If you don't do that, you may use update metadata instruction directly to the nft address to update

Can you share some information on what it took to accomplish this or the repo?

**Comment by TheDruidsKeeper** [comment]
> > > Hey guys do you know how to reveal after using hiddensetting?
> > 
> > 
> > I use a custom version of candy machine v2 to let metadata uri to have number appended to the base url. like `https://example.com/token/1` then update the response json when I want to reveal.
> > If you don't do that, you may use update metadata instruction directly to the nft address to update
> 
> Can you share some information on what it took to accomplish this or the repo?

@SolProtection I'm not OP, but looking through the code myself for this same thing - it looks [like this](https://github.com/metaplex-foundation/metaplex-program-library/blob/72992892e4b6549ab58edfc14bb50924223d884b/candy-machine/program/src/lib.rs#L957) is where you would want to modify the uri to replace with the `mint_number`.

**Comment by HaoCherHong** [comment]
> > > > Hey guys do you know how to reveal after using hiddensetting?
> > > 
> > > 
> > > I use a custom version of candy machine v2 to let metadata uri to have number appended to the base url. like `https://example.com/token/1` then update the response json when I want to reveal.
> > > If you don't do that, you may use update metadata instruction directly to the nft address to update
> > 
> > 
> > Can you share some information on what it took to accomplish this or the repo?
> 
> @SolProtection I'm not OP, but looking through the code myself for this same thing - it looks [like this](https://github.com/metaplex-foundation/metaplex-program-library/blob/72992892e4b6549ab58edfc14bb50924223d884b/candy-machine/program/src/lib.rs#L957) is where you would want to modify the uri to replace with the `mint_number`.

Exactly.
And in order to make update and deploy the program. You'll need some extra steps.
Basically 1. deploy the program. 2. deploy the IDL for this new program 3. deploy the candy machine account and 4. update the frontend.
Sorry for replying late it's Chinese New Year here so I don't have time to make a complete instructions yet.

**Comment by TheDruidsKeeper** [comment]
@HaoCherHong Better yet: a PR to replace a tokenized string 🥇. This seems like a worth-while improvement.

**Comment by HaoCherHong** [comment]
> @HaoCherHong Better yet: a PR to replace a tokenized string 🥇. This seems like a worth-while improvement.

Good idea. This will involves some address updates. But I'll do it these 2 days and see how they'll respond.

**Comment by JulienK03** [comment]
![image](https://user-images.githubusercontent.com/58232121/153081706-e703b4d2-58f8-48f4-82ee-008c1fa83199.png)
we replace both uri by mint_number?

**Comment by HaoCherHong** [comment]
> ![image](https://user-images.githubusercontent.com/58232121/153081706-e703b4d2-58f8-48f4-82ee-008c1fa83199.png) we replace both uri by mint_number?

Yes, check this out:
https://github.com/metaplex-foundation/metaplex/pull/1765/files

**Comment by samuelvanderwaal** [comment]
See [the docs](https://docs.metaplex.com/candy-machine-v2/configuration#hidden-settings) and [this comment](https://github.com/metaplex-foundation/metaplex-program-library/pull/208#issuecomment-1035552498) for an explanation of how the hidden settings work.

**Comment by Moreozz** [comment]
When I create config.json with hiddensettings inside, my candy machine start to mint only hidden images with its description. on mainnet it was awful so I withdraw it all. Its hiden, but how it could be unhide after? usually everybody hide it to place in marketplace, and then it how  must to be unpacked?

**Comment by joysiriban** [comment]
> When I create config.json with hiddensettings inside, my candy machine start to mint only hidden images with its description. on mainnet it was awful so I withdraw it all. Its hiden, but how it could be unhide after? usually everybody hide it to place in marketplace, and then it how must to be unpacked?

same question. did you get an answer for this already?
