### ISSUE TITLE
Getting can't find candy machine error when uploading:

### ISSUE THREAD

**Issue by dhruvkshah0** [metaplex-foundation/metaplex#1334]
C:\Users\xxxx>%CM2% upload -e devnet -k C:\Users\XXXX\.config\solana\id.json -cp C:\Users\xxxx\workspace\metaplexV2\config.candy C:\Users\drpotanist\workspace\hashlips_art_engine\assets -r https://solana--devnet.datahub.figment.io/apikey/XXXXXXXX
wallet public key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
USING CUSTOM URL https://solana--devnet.datahub.figment.io/apikey/XXXXXXXX
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 10000 (img+json) pairs
started at: 1640673864395
Size 0 undefined
Writing indices 4790-4799
saving config line 4790-4799 failed Error: Invalid arguments: candyMachine not provided.

why is it saying candyMachine not provided? Here is my config:
{
    "price": 4.2,
    "number": 10000,
    "gatekeeper": null,
    "solTreasuryAccount": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "28 Dec 2021 02:00:00 EST",
    "endSettings": {
        "endSettingType": { "amount":true },
        "value":10
    },      
    "whitelistMintSettings": {
        "mode" : { "burnEveryTime": true },
        "mint" : "xxxxxxxxxx",
        "presale" : true,
        "discountPrice" : 0.5
    },
    "hiddenSettings": null,
    "storage": "arweave",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}

**Comment by prashantcrypto** [comment]
I can create your candy machine successfully. 
I know its new problem due to the updating of arweave. 
Please contact if you want help from me 
Dischord shyaid#5168
My fee is too low than others

**Comment by Khushhal23** [comment]
C:\Users\xxxx>~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k C:\Users\XXXX.config\solana\id.json -cp C:\Users\xxxx\workspace\metaplexV2\config.json C:\Users\drpotanist\workspace\hashlips_art_engine\assets -r https://solana--devnet.datahub.figment.io/apikey/XXXXXXXX


also, rename your config file to config.json, not config.candy
