### ISSUE TITLE
I have created my candy machine V2, but this error is prompted when I start it with fair launch.

### ISSUE THREAD

**Issue by forbename** [metaplex-foundation/metaplex#1335]
![image](https://user-images.githubusercontent.com/49100842/147540863-7c9a5337-a888-4630-8629-2e677be708fd.png)
TypeError: Cannot read properties of undefined (reading 'slice')
I have created my candy machine V2, but this error is prompted when I start it with fair launch.
Who can tell me what the problem is? Thank you.
![image](https://user-images.githubusercontent.com/49100842/147541057-58ed098e-d618-4567-809b-c6613f66a853.png)
![image](https://user-images.githubusercontent.com/49100842/147541100-3a876bd0-b69a-4af1-9139-020f3ea79e66.png)

**Comment by forbename** [comment]
TypeError: Cannot read properties of undefined (reading 'slice')
I have created my candy machine V2, but this error is prompted when I start it with fair launch.
Who can tell me what the problem is? Thank you.

**Comment by ROMGOFF68** [comment]
I have the same problem , did you find a solution ?

**Comment by Blueberry94** [comment]
I have the same error. Please help us out some one? Thanks a ton!

**Comment by moonvision2020** [comment]
#1322 check out this issue

the solution worked for me.
had to run:

npm nistall

and then did yarn start and website worked

hope it works for you too

**Comment by moonvision2020** [comment]
oops npm install

**Comment by Khushhal23** [comment]
u can also fix it by upgrading the metaplex branch by git checkout -b fix-arweave-upload

**Comment by HaoCherHong** [comment]
same issue to #1322
