### ISSUE TITLE
Candy Machine V2 whitelist

### ISSUE THREAD

**Issue by shoevan** [metaplex-foundation/metaplex#1336]
**Describe the bug**
I can't get the whitelist functioning through the front end provided by the fair launch protocol. I've created an SPL token and have taken the 'Authority' address for the token as the 'mint address' for the whitelist in the Candy Machine V2 config, sent the token to the wallet that is used to connect to the mint page, but no mint button appears when the live date/time is after the current date/time. Does the whitelist functionality not work through the current iteration of the front end? Does the whitelist only work through mainnet and not devnet?

**To Reproduce**
1. Create an SPL token, mint a token and note its authority address
2. Send the SPL token to a wallet which will be used to connect to the front end 
3. Set up candy machine V2 as described by the documentation, set the "whitelistMintSettings" as follows: 
    "whitelistMintSettings": {
        "mode": {
            "burnEveryTime": true
        },
        "mint": "<SPL TOKEN AUTHORITY>",
        "presale": true,
        "discountPrice": 0.5
    },
4. Set the "goLiveDate" to a date in the future
5. upload assets and create the candy machine
6. Start the fair launch front end mint page
7. Connect wallet where the SPL token was sent to
8. Once connected, there will be a blank page, no button to mint will appear
**Expected behavior**
Expected that at step 8 with the SPL token within the connected wallet, the whitelist system should allow for the wallet to mint prior to the goLiveDate as part of the "presale" functionality.

![image](https://user-images.githubusercontent.com/62692466/147554870-27945123-1c1c-4cd4-b960-d7b7530206f5.png)
As above, no mint button

**Comment by jack21m** [comment]
I have same issue

**Comment by calebporzio** [comment]
Same here

**Comment by darek292** [comment]
I got this working but it requires heavy tweaks to the frontend as quite few things are broken there.

**Comment by calebporzio** [comment]
@darek292 - mind throwing out some of what you had to do? I'm capable of heavily tweaking and any tips or shortcuts that would save me time would be much appreciated! Thanks!

**Comment by alvinsga** [comment]
Wrote a new frontend for Candy Machine V2 which should work for whitelisting - https://github.com/alvinsga/candy-machine-v2

**Comment by kelvin2180** [comment]
+1
