### ISSUE TITLE
"A Front End Experience for Minting"

### ISSUE THREAD

**Issue by caresseduvisage** [metaplex-foundation/metaplex#1338]
Good Morning everyone,

I was following correctly the tutorial for the candymachine V2. All was going well until i decided to add the front end experience (the button mint). I dont want to use the fair launch protocol, just want to add the button mint connected to my candy machine. Here is my .env file :

![image](https://user-images.githubusercontent.com/63931199/147561560-ab628584-3b80-467e-b62e-1745a2226b70.png)

Here is the error when i did the yarn install and start on the fair launch directory :

Could you please help me ?

Kind Regards,

----------------------------------------------------------------
**TypeError: wallets is undefined**
(anonymous function)
src/WalletDialog.tsx:96

  93 | return (React.createElement(Dialog, Object.assign({ open: open, onClose: handleClose, className: styles.root }, props),
  94 |     React.createElement(DialogTitle, null,
  95 |         title,
> 96 |         React.createElement(IconButton, { onClick: handleClose },
     | ^  97 |             React.createElement(CloseIcon, null))),
  98 |     React.createElement(DialogContent, null,
  99 |         React.createElement(List, null,

mountMemo
node_modules/react-dom/cjs/react-dom.development.js:15846
useMemo
node_modules/react-dom/cjs/react-dom.development.js:16219
useMemo
node_modules/react/cjs/react.development.js:1532
WalletDialog
src/WalletDialog.tsx:96

  93 | return (React.createElement(Dialog, Object.assign({ open: open, onClose: handleClose, className: styles.root }, props),
  94 |     React.createElement(DialogTitle, null,
  95 |         title,
> 96 |         React.createElement(IconButton, { onClick: handleClose },
     | ^  97 |             React.createElement(CloseIcon, null))),
  98 |     React.createElement(DialogContent, null,
  99 |         React.createElement(List, null,

renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:14985
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js:17811
beginWork
node_modules/react-dom/cjs/react-dom.development.js:19049
callCallback
node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4056
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js:23964
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:22776
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js:22707
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js:22670
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:22293
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:21881
updateContainer
node_modules/react-dom/cjs/react-dom.development.js:25482
legacyRenderSubtreeIntoContainer/<
node_modules/react-dom/cjs/react-dom.development.js:26021
unbatchedUpdates
node_modules/react-dom/cjs/react-dom.development.js:22431
legacyRenderSubtreeIntoContainer
node_modules/react-dom/cjs/react-dom.development.js:26020
render
node_modules/react-dom/cjs/react-dom.development.js:26103
./src/index.tsx/<
src/index.tsx:7

   4 | import App from './App';
   5 | import reportWebVitals from './reportWebVitals';
   6 | 
>  7 | ReactDOM.render(
   8 |   <React.StrictMode>
   9 |     <App />
  10 |   </React.StrictMode>,

./src/index.tsx
http://192.168.XXX.XXX:3000/static/js/main.chunk.js:4455:30
__webpack_require__
/home/ongang/metaplex/js/packages/fair-launch/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

fn
/home/ongang/metaplex/js/packages/fair-launch/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

1
http://192.168.XXX.XXX:3000/static/js/main.chunk.js:4769:18
__webpack_require__
/home/ongang/metaplex/js/packages/fair-launch/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

checkDeferredModules
/home/ongang/metaplex/js/packages/fair-launch/webpack/bootstrap:45

  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 

webpackJsonpCallback
/home/ongang/metaplex/js/packages/fair-launch/webpack/bootstrap:32

  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;

(anonymous function)
http://192.168.xxx.xxx:3000/static/js/main.chunk.js:1:8

**Comment by ROMGOFF68** [comment]
I have the same problem, did you find a solution ?

**Comment by moonvision2020** [comment]
I am getting the same problem as well... I hope you can find a solution

**Comment by moonvision2020** [comment]
https://github.com/metaplex-foundation/metaplex/issues/1322 check out this issue 

the solution worked for me. 
had to run:

npm nistall

and then did yarn start and website worked

hope it works for you too

**Comment by moonvision2020** [comment]
oops 

npm install

**Comment by samuelvanderwaal** [comment]
There are some dependency issues for FLP which should be fixed soon. Until then you should be able to use `npm install` instead of `yarn` or you can move the FLP folder to a separate directory and run `yarn` there.

You can also check out these community frontends if you want other options:

https://github.com/tonyboylehub/candymachine-v2-boiler-mint-site-noFLP
https://github.com/Soul-Dogs-City/candy-machine-v2-mint
https://github.com/rez-cpu/next-candy-machinev2

**Comment by emersonthis** [comment]
I had the same problem and `$ npm install` fixed it
