### ISSUE TITLE
Candy machine pubkey

### ISSUE THREAD

**Issue by ROMGOFF68** [metaplex-foundation/metaplex#1342]
I try to run this command to have the candy machine pubkey : 
npx ts-node ~/solana_mint/metaplex/js/packages/cli/src/candy-machine-cli.ts upload ./assets -e devnet -k ~/solana_mint/keypair.json -n 1 --storage arweave   

but it return this 
    
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 1 (image+json) pairs
started at: 1640719469022
wallet public key: XXXXXXXXXXXXX
ended at: 2021-12-28T19:24:30.025Z. time taken: 00:00:01

but don't give the candy machine pubkey .
Someone know what to do ? 
Thanks

**Comment by unwantedpollo** [comment]
have u solved it?

**Comment by ROMGOFF68** [comment]
No I don't find any solution


Le mar. 28 déc. 2021 à 21:49, unwantedpollo ***@***.***> a
écrit :

**Comment by ROMGOFF68** [comment]
Do you have one solution ? Or th same problem ?

Le mar. 28 déc. 2021 à 21:49, unwantedpollo ***@***.***> a
écrit :

**Comment by Deadstop1** [comment]
I am getting the same problem

**Comment by KrehyDev** [comment]
same here

**Comment by samuelvanderwaal** [comment]
The public key of the deployed Candy Machine V2 is `cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ`. If you're talking about the public key of your candy machine account for your specific candy machine, you can find it from your cache file.

**Comment by ankitdsgn** [comment]
> The public key of the deployed Candy Machine V2 is `cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ`. If you're talking about the public key of your candy machine account for your specific candy machine, you can find it from your cache file.

but there is no public key in the cache file also :(

Need help asap
