### ISSUE TITLE
Error: Custom: Invalid blockhash when deploy it to devnet

### ISSUE THREAD

**Issue by kazunetakeda25** [metaplex-foundation/metaplex#1348]
Command: `solana program deploy --buffer fair_launch-keypair.json fair_launch.so -u devnet`
Error: `Error: Custom: Invalid blockhash`

References:
Solana CLI version: `solana-cli 1.9.2 (src:f58b87be; feat:4100269022)`
Rustc Version: `rustc 1.57.0 (f1edd0429 2021-11-29)`

**Comment by imentus-rahul** [comment]
I'm facing same issue while deploying program on devnet
Git Repository: https://github.com/gemworks/core

**Comment by kazunetakeda25** [comment]
Hi @imentus-rahul do you still get the same issue?

**Comment by imentus-rahul** [comment]
> Hi @imentus-rahul do you still get the same issue?

Yes I am still getting same error on other repository: https://github.com/gemworks/core
Is it a issue from solana devnet cluster or some bug in repository? As it is getting deployed on Localnet and Testnet.

Thanks

![Screenshot from 2022-01-12 11-22-10](https://user-images.githubusercontent.com/86224847/149071757-cc35b553-abf3-4e46-a028-ed18aadf6cb9.png)

**Comment by aaron5738** [comment]
This error was caused by the solana version. When I changed to the stable version, there was no such error.

**Comment by sriharsh1104** [comment]
can u metion which is the latest stable version of solana
