### ISSUE TITLE
Mint fee not updates after changing in config.json and runnig update_candy_machine

### ISSUE THREAD

**Issue by digz6666** [metaplex-foundation/metaplex#1351]
**Describe the bug**
Mint fee not updates after changing in config.json and runnig update_candy_machine

**To Reproduce**
1. Create candy machine with price 0.1 SOL
2. Mint 1 token -> costs 0.1 SOL
3. Change mint price to 0.00001 SOL
4. Run candy-machine-v2-cli.ts update_candy_machine -e devnet -k ~/.config/solana/devnet.json -cp candy_machine_config_dev.json -c dev
5. Mint 1 more token -> costs 0.1 SOL, should cost 0.00001 SOL

**Expected behavior**
After changing price adn run update_candy_machine it should update the mint cost

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by samuelvanderwaal** [comment]
Do you have a link to your Tx so I can see what the errors were?

**Comment by summerplaybook** [comment]
Any solutions to this? Running into issues with the cli to update this
