### ISSUE TITLE
Incorrect image upload validation after upload errors

### ISSUE THREAD

**Issue by epomatti** [metaplex-foundation/metaplex#1352]
This issue happened when deploying to `mainnet-beta`, today using the master branch.

While uploading 2026 files we had a bunch of errors along the way.  It looks like 1996 files are ok. Now we're getting errors for `upload` and `verify` as well.

**When trying to `upload`**:

![image](https://user-images.githubusercontent.com/6530769/147675018-c6698139-5e33-4c98-b014-e5943ce33cf2.png)

**When trying to `verify`**. This is weird because it says "2026 smaller than 1996", which doesn't look right.

```
Error: predefined number of NFTs (2026) is smaller than the uploaded one (1966)
    at Command.<anonymous> (C:\Users\abada\project\candyv2\js\packages\cli\src\candy-machine-v2-cli.ts:417:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

And for last we get this when running `show`:

```
itemsAvailable:  2026
itemsRedeemed:  0
```

I counted in the `.cache` for "onChain":false" and it is _exactly_: 2026 - 1966 = 60.

Yes, images are available on `arweave-sol` link in the cache URL.

![image](https://user-images.githubusercontent.com/6530769/147675575-b8b1c9e6-3763-417a-b5ee-32417c3db2ec.png)

**Comment by Khushhal23** [comment]
just change all to false and then reupload

**Comment by epomatti** [comment]
@Khushhal23 which all? and what field(s)? Can't make head or tails of what you're talking about.

**Comment by Khushhal23** [comment]
@epomatti Just change all onChain:true to onchain: false, and then reupload
