### ISSUE TITLE
How to get just a "mint" button and not using fair launch

### ISSUE THREAD

**Issue by moonvision2020** [metaplex-foundation/metaplex#1355]
When I follow the instructions for candy machine v2, at the mint page section, when I input yarn start, it just takes me to localhost metaplex store, so then I add in the fair launch script and yarn start then everything works fine but the whole launch system is too complicated, I just want a simple "mint" button to show, 

I am planning on giving my members the mint link on the day of mint and have it just be live indefinitely until we sell out.

I can already set the parameters in the candymachine config.json to end the mint when it sells out, just wondering how i can remove all the extra features of the Fair Launch ie. auctions, bidding, price range, etc.
Just a simple "mint" to buy and select quantity

Please help, any help or ideas will be much appreciated, thank you

**Comment by numisman** [comment]
This was possible using the Exiled Apes repo - you may try reviewing how that one connects and transacts using a wallet connector and then modify to interact with the V2 button.  As of 1/5 you will not be able to create V1 candy machines, so this route is something I plan to explore as well.

**Comment by moonvision2020** [comment]
so i ended up taking out my fair launch id in the .env file, and then yarn start in the fair-launch directory, and it worked and i just got a basic mint button that worked and after the test nfts were sold out, automatically transaction failed. 

just wondering if there are any tips on how to style?

**Comment by samuelvanderwaal** [comment]
@moonvision2020 you can try these community frontends if you want something simpler than FLP. Note: these are community efforts and aren't directly supported by Metaplex:

https://github.com/tonyboylehub/candymachine-v2-boiler-mint-site-noFLP
https://github.com/Soul-Dogs-City/candy-machine-v2-mint
https://github.com/rez-cpu/next-candy-machinev2
