### ISSUE TITLE
V2 Whitelist - SPL Token Consumption

### ISSUE THREAD

**Issue by Occvlt21** [metaplex-foundation/metaplex#1356]
Hi,

I've been testing V2 in devnet, tried whitelisting with the following settings:

```
"whitelistMintSettings": {
    "mode" : { "burnEveryTime": true },
    "mint" : "XXXXXXXXXXXXXXXXXXXXX",
    "presale" : true,
    "discountPrice" : null
    },
```

Now, the problem I'm facing with this is that I can't find a way to define how MUCH of said token to be consumed upon minting. It shows as default -<0.00001 as can be seen in the screenshots.

Is there a way to change for example to 1 token? As this allows essentially "infinite" mint.

Balance changes prompt:
![image](https://user-images.githubusercontent.com/95923009/147747864-0a168650-184f-4d2b-b54d-657767825d36.png)

SPL Token balance changes after mint:
![image](https://user-images.githubusercontent.com/95923009/147747877-70268f82-5cb5-4549-a64b-12af91061ce7.png)
![image](https://user-images.githubusercontent.com/95923009/147747880-17b8ecff-b29c-4c57-b7c2-dbb13335f943.png)

**Comment by TonyChG** [comment]
do you found a workaround for this?
