### ISSUE TITLE
Yarin install on Metaplex V2 throwing error

### ISSUE THREAD

**Issue by charles811** [metaplex-foundation/metaplex#1360]
I completed all the steps to install candy machine V2 mentioned in the below link.
I was able mint token mentioned in Step 6.

https://docs.metaplex.com/candy-machine-v2/mint-frontend

Step 7 consits of minting website.
REACT_APP_CANDY_MACHINE_ID="My candy machine ID"

REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://api.devnet.solana.com
# Phase 1
REACT_APP_FAIR_LAUNCH_ID=

**The last step is to run yearn install** 
After these changes are made, run the commands yarn install and yarn start inside the folder ~/metaplex/js/packages/fair-launch. This will start a local server with a mint front end. From here, you should customise the mint page and deploy it your host service.

Below is the error Message I get.
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I have already installed git since it is mentioned as dependency.
Have been breaking my head for two days now.
Any advise is greatly welcome.

**Comment by Leo4815162342** [comment]
@charles811 what is the output of running `git --version` ?

**Comment by charles811** [comment]
Figured out the issue. I had just to reinstall and it worked fine.

**Comment by Leonardojt22** [comment]
Hi man, i'm having trouble with this, are you reinstalling with older version of node?

**Comment by artrepreneur** [comment]
Try running npm install instead of yarn install, and stay on node 16.13.* or greater.
