### ISSUE TITLE
Allow For Multiple CMv2 Treasury Accounts with Percentage Allocation

### ISSUE THREAD

**Issue by solanacryptodev** [metaplex-foundation/metaplex#1364]
**Is your feature request related to a problem? Please describe.**
Yes, this feature is being requested due to a problem that I've noticed concerning a particular project. The problem with 1 wallet being the treasury wallet is that in a small team with only a handful of devs, you're forced to trust that the person who controls the treasury account will do right by the other people on the team and won't hold funds that should be dispersed. Really, the entire process should be trustless. Teams, especially small teams, shouldn't need to worry that they may or may not get what was agreed to because someone rugged or held funds until they felt like distributing them. 

**Describe the solution you'd like**
My suggestion is the ability to add multiple accounts with the ability to add in a certain percentage. Sort of like how the Metaplex JSON Creator array used for royalties.

**Describe alternatives you've considered**
I thought about a multisig as well, but that could over-complicate things and that still doesn't prevent abuse if enough members on the team are colluding. The only way to truly prevent abuse and increase trustlessness, is to have it where when users mint, the SOL is already distributed into the treasury wallets by default based on the Config file.

**Comment by somozadev** [comment]
any updates on this topic?

**Comment by stegaBOB** [comment]
Fanout wallet is the fix to this. Its close to being done but that is the solution.
