### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'candyMachineAddress' of undefined when trying to update candy machine

### ISSUE THREAD

**Issue by Vlad-Games** [metaplex-foundation/metaplex#1367]
**Describe the bug**
When i want to update the date on my candy machine i get the following error:
`(node:3900) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'candyMachineAddress' of undefined
    at Command.<anonymous> (C:\Users\REDACTED\Desktop\REDACTED\metaplex\js\packages\cli\src\candy-machine-cli.ts:834:53)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**To Reproduce**
1.Upload the nfts with the comamnd:
`ts-node .\js\packages\cli\src\candy-machine-cli.ts upload ./assets -env devnet --keypair .\path\to\keyfile.json`
2.Create candy machine with the command:
`ts-node .\js\packages\cli\src\candy-machine-cli.ts create_candy_machine ./assets -env devnet --keypair .\path\to\keyfile.json --price 1`
3.Update the candy machine using the following command:
`ts-node .\js\packages\cli\src\candy-machine-cli.ts update_candy_machine --env devnet --keypair .\path\to\keyfile.json --date '4 Nov 2021 00:00:00 UTC'` or any other date including "now"

**Expected behavior**
The candy machine should update and the timestamp should be printed in the terminal

**Screenshots**
[https://im-a.richboy.uk/0351f46e.png](https://im-a.richboy.uk/0351f46e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version Dev(OS Build 22489.1000)
 - Browser Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit) (cohort: Stable)
 - Revision: d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
 - Terminal: PowerShell

**Additional context**
The part where it says REDACTED or .\path\to\keyfile.json has ben redacted for privacy reasons, and in the acctual command execution the real paths were used

**Comment by Khushhal23** [comment]
Please check if your create_candy_machine command was completed successfully, if it's still not fixed, try reuploading

**Comment by Vlad-Games** [comment]
Tried reuploading and the create candy machine works once if i reupload and recreate it gives an error saying that it already exists

**Comment by Khushhal23** [comment]
Change all the onchain:true to onchain:false in the cache file and then reupload, then create candy machine and then update

**Comment by Vlad-Games** [comment]
This issue is still present dont close it and how has it passed 30 days i dont get it, it didnt even pass a week

**Comment by gbrads** [comment]
i have the exact same issue, anyone able to help?

**Comment by Khushhal23** [comment]
Just change all onChain:true to false in ur cache file and reupload, then
run update candy machine

**Comment by gbrads** [comment]
@Khushhal23 the collection is already live and in like 2500 wallets, will doing this mess with anything?

**Comment by Khushhal23** [comment]
Yeah it will, don't change anything now, but you can use metaboss of you
still wanna update

**Comment by gbrads** [comment]
@Khushhal23 How would i go about doing that? what command would i run in metaboss. Can you walk me through it please.

**Comment by stegaBOB** [comment]
You can check the metaboss docs at https://metaboss.rs. Closing this issue
