### ISSUE TITLE
Failed to mint NFT with candy machine v2 tutorial

### ISSUE THREAD

**Issue by tokchin** [metaplex-foundation/metaplex#1369]
**Describe the [bug**](URL)
try to proceed tutorial described [here](https://docs.metaplex.com/candy-machine-v2/mint-tokens), but I can not mint NFT.

Below is my failed transaction.

https://explorer.solana.com/tx/4vYJwwFyrybRXeNn9EgcT1mNjb5yfqaYdwa6Frwim6PwvTv4dknnPkiX51tawrDHMgAjVxDsBmRixpgL7VYTsyiF?cluster=devnet

**Comment by numisman** [comment]
Experiencing this as well

**Comment by samuelvanderwaal** [comment]
The error you're receiving is:

```bash
0x13F: 
        NFT Candy Machine V2      |     GatewayTokenMissing: Missing gateway token when required
```

Make sure you have your config setup correctly. If you're enabling a Gateway token, make sure you have it setup correctly.
