### ISSUE TITLE
How can i burn a specific ammount from an nft collection?

### ISSUE THREAD

**Issue by Gomez0015** [metaplex-foundation/metaplex#1372]
Hey, I was wondering how can I burn a specific amount from an NFT collection? While the mint is currently happening?

**Comment by samuelvanderwaal** [comment]
To burn existing NFTs you can use `spl-token burn` from the Solana CLI suite, or [Metaboss](https://metaboss.rs). There's no CLI command in the current tool to erase specific sections of your config account so effectively you can't burn unminted NFTs in your candy machine without writing custom code.
