### ISSUE TITLE
Gatekeeper causing CMv2 minting to fail

### ISSUE THREAD

**Issue by kyleqian** [metaplex-foundation/metaplex#1374]
**>> FYI: I forked and re-deployed my own CMv2 Program to create my CandyMachine account, so it's possible this issue is due to that. But posting anyway in case it's not <<**

**Describe the bug**
Setting the gatekeeper settings to enable CAPTCHA causes minting to fail on devnet. It works if I turn off gatekeeper.

Settings causing failure:
```
    "gatekeeper": {
        "gatekeeperNetwork": "ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6",
        "expireOnUse": true
    },
```

Error:
```
Timeout Error caught {err: {…}, slot: 105217445, confirmations: 0}
Minting error: Error: Transaction failed: panicked at 'index out of bounds: the len is 0 but the index is 1', integration-lib/src/state.rs:178:13
```

I traced this to https://github.com/metaplex-foundation/metaplex/blob/master/rust/nft-candy-machine-v2/src/lib.rs#L87, which eventually errors at `integration-lib/src/state.rs:178:13`.

**Desktop (please complete the following information):**
 - MacOS M1

**Comment by ybsat** [comment]
Hello, have you found a solution for this?
Using the metaplex candy machine address, I have similar problem when I enable gateKeeper. Although in my case, the metaplex program returns: "custom program error: 0x140"

**Comment by nelsontky** [comment]
Hey I have that issue too and it happens on mainnet and devnet. What I found helped me was that I waited 2 minutes after the golive date to mint and it worked

**Comment by Metroxe** [comment]
This is still occuring

**Comment by cheunghingyung** [comment]
yes it's still happened

**Comment by rojasjuniore** [comment]
yes it's still happened
