### ISSUE TITLE
 Error when trying to minting an mp4 or a giff in devnet

### ISSUE THREAD

**Issue by Nicolas0Martinez1** [metaplex-foundation/metaplex#1380]
Error when trying to minting an mp4 or a giff in devnet
In creating. Press click, select the mp4 file, press next. when you write the attributes and plaff You're getting the "Aw, Snap" error instead of a web page.

i use brave on windows.

It is expected that a video can be minted normally as an image.

**Comment by stegaBOB** [comment]
hm thats not right
