### ISSUE TITLE
candy machine v2 cacheName issue

### ISSUE THREAD

**Issue by aschmidhofer** [metaplex-foundation/metaplex#1389]
When using the candy-machine-v2-cli.ts you have to specify the cache name (-c) AFTER the config path (-cp) because otherwise the cacheName is set to "p" (because of -cp).

Example: 
ts-node candy-machine-v2-cli.ts show -e devnet -k key.json -l debug  -cp cmsetup.json -c cm2test
works, but
ts-node candy-machine-v2-cli.ts show -e devnet -k key.json -l debug -c cm2test -cp cmsetup.json 
doesn't work. 

so either change -cp to a different letter (maybe just -p) or fix it in reading parameters that -c can be used before -cp as well (that's also the order it appears in help). 

Hope i explained that well enough. Feel free to ask if you have questions. If I find the time I will make a pull-request myself. Just wanted to let you know about the issue right away!

-Andy

**Comment by DeceptiveGmR** [comment]
I applied this change. I am able to upload and verify however; the file is not created in .cache and only showing MINT button on localhost
