### ISSUE TITLE
Minting before uploading all tokens generate failed tokens

### ISSUE THREAD

**Issue by epomatti** [metaplex-foundation/metaplex#1396]
I produced a failed state by following these steps:

1. Create a candy machine for 10 NFTs (`"number": 10`).
2. Upload only 3 NFTs by leaving only 3 NFTs on the asset directory for upload.
3. Mint 2 NFTs (as the authority, using `mint_multiple_tokens`)

In the Phantom wallet and NFT Armory the tokens are not displayed correctly. Prints below. I couldn't find a way to fix it.

This is not optimal, as the candy machine should allow either 1) Not mint if not ready / 2) Mint successfully. Breaking like this should not be an expected behavior.

![image](https://user-images.githubusercontent.com/6530769/148127734-e63cd5b3-b2e2-4f42-8373-b0d09991ff00.png)

![image](https://user-images.githubusercontent.com/6530769/148127835-bbf5c8f8-8105-431a-8b55-18fedb69aa3f.png)

**Comment by needman0914** [comment]
I have a same issue.
I want to mint 10 NFTs but mint only 5 NFTs first for whitelist users then mint 5 NFTs for all members.
In this case. I can't mint using CMv2 like you.

**Comment by epomatti** [comment]
@needman0914 The only alternative I found was to mint extra tokens outside the candy machine.

https://metaboss.rs/mint.html

**Comment by epomatti** [comment]
@needman0914 I didn't find a workaround for this. As of now, I'll upload all my 10k assets in one shot.

**Comment by needman0914** [comment]
@epomatti 
Thanks a lot. If I solve this issue, I will let you know. Let's continue to share.
