### ISSUE TITLE
Attempted import error: 'getPhantomWallet' is not exported from '@solana/wallet-adapter-wallets' (imported as 'getPhantomWallet').

### ISSUE THREAD

**Issue by angushk** [metaplex-foundation/metaplex#1401]
All modules like ts-node is the most updated, environment is Win10, thank you.

At the beginning I got the same error of #1322  so I typed npm install and then yarn start again, after that it gave me these error messages:
(These's too many errors and just copy the first one here)

yarn run v1.22.17
$ react-scripts start
(node:3660) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:3660) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...
Failed to compile.

Attempted import error: 'getPhantomWallet' is not exported from '@solana/wallet-adapter-wallets' (imported as 'getPhantomWallet').
assets by path static/js/*.js 5.65 MiB
  asset static/js/bundle.js 5.64 MiB [emitted] (name: main) 1 related asset
  asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.54 KiB [emitted] 1 related asset
asset index.html 1.71 KiB [emitted]
asset asset-manifest.json 458 bytes [emitted]
orphan modules 768 KiB [orphan] 322 modules
runtime modules 31.5 KiB 17 modules
modules by path ./node_modules/ 4.35 MiB
  javascript modules 4.35 MiB 730 modules
  json modules 3.72 KiB 2 modules
modules by path ../../node_modules/ 137 KiB 24 modules
modules by path ./src/ 138 KiB
  modules by path ./src/*.tsx 100 KiB 9 modules
  modules by path ./src/*.css 7.58 KiB 4 modules
  modules by path ./src/*.ts 30.2 KiB 4 modules
crypto (ignored) 15 bytes [built] [code generated]
buffer (ignored) 15 bytes [optional] [built] [code generated]
crypto (ignored) 15 bytes [optional] [built] [code generated]
buffer (ignored) 15 bytes [optional] [built] [code generated]

If I type yarn install and yarn build, the results are:

yarn run v1.22.17
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve './blocto' in 'C:\Users\xxxxxxxxxx\metaplex\js\packages\fair-launch\node_modules\@solana\wallet-adapter-wallets\lib'
Did you mean 'blocto.js'?
BREAKING CHANGE: The request './blocto' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file
where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by angushk** [comment]
It's strange that I updated the metaplex (git pull https://github.com/metaplex-foundation/metaplex.git) error messages changed, but still no idea how to resolve (sorry I can't amend those code)

yarn run v1.22.17
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve './errors' in 'C:\Users\xxxxxxxxxx\NFT\metaplex\js\packages\fair-launch\node_modules\@solana\wallet-adapter-react\lib'
Did you mean 'errors.js'?
BREAKING CHANGE: The request './errors' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file
where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by prashantcrypto** [comment]
i can make your candy machine for just 1.5 sol.
i had already  made many candy machine and also on v2.
my disocrd shyaid#3516

**Comment by angushk** [comment]
sorry that my boss don't allow this

**Comment by dshaw002** [comment]
Try to run:

npm install

and then 

yarn serve

It worked for me. Just running npm run build or npm run serve won't work.
