### ISSUE TITLE
Made CM upload v1 before shutdown, today I can't activate CM? What will happen to my CM and SOL?

### ISSUE THREAD

**Issue by franraknic** [metaplex-foundation/metaplex#1402]
**Describe the bug**
Did the CM upload step before recent vulnerability shutdown, need to activate and set start date but CM1 is now disabled. What will happen to my CM and SOL that was used for upload?

**To Reproduce**
Can't be reproduced since you would have to make a CM v1 upload - but that is no longer possible.

**Comment by Solseum** [comment]
If you have the cache file just run withdraw to collect the rent

**Comment by franraknic** [comment]
> If you have the cache file just run withdraw to collect the rent

When I do withdraw dry run there is 0 sol. Just to be clear I uploaded my images over night while v1 was still active, in the morning I was going to create_candy_machine but v1 was deactivated. At the moment I am trying to find the equivalent command in v2 to just continue the process - using the saved `temp` json.

Thank you very much for the replying!

**Comment by franraknic** [comment]
since my CM was uploaded using v1 i had to use the v1 cli:

`ts-node .\src\candy-machine-v1-cli.ts withdraw -k creator-keypair.json -e mainnet-beta`

sends sol spent on v1 upload. Nice features in v2, thanks again.
