### ISSUE TITLE
Cant create Candy Machine

### ISSUE THREAD

**Issue by Wanackon** [metaplex-foundation/metaplex#1407]
PS C:\Solana\metaplex-master (1)\metaplex-master\js\packages\cli\src> ts-node candy-machine-v2-cli.ts upload C:/Solana/assets  --env devnet --keypair C:/Solana/devnet-test.json
wallet public key: Hd5ymGSGFw4byf6cJ6WS3TGMBXfmMyknoXG59VckbAJz
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at getCandyMachineV2Config (C:\Solana\metaplex-master (1)\metaplex-master\js\packages\cli\src\helpers\various.ts:49:27)
    at Command.<anonymous> (C:\Solana\metaplex-master (1)\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:99:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by FlyingMonkes** [comment]
same error here

**Comment by haomaaax** [comment]
same error here when I tried to switch my metaplex from v1 to v2. Any thoughts?

**Comment by rudebono** [comment]
@Wanackon @FlyingMonkes @haomaaax 

Please set Candy's configuration
- https://docs.metaplex.com/candy-machine-v2/configuration
- https://docs.metaplex.com/candy-machine-v2/creating-candy-machine

example 
```sh
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json \
    ./assets
```

**Comment by haomaaax** [comment]
> @Wanackon @FlyingMonkes @haomaaax
> 
> Please set Candy's configuration
> 
> * https://docs.metaplex.com/candy-machine-v2/configuration
> * https://docs.metaplex.com/candy-machine-v2/creating-candy-machine
> 
> example `-cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json`
> 
> ```shell
> ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
>     -e devnet \
>     -k ~/.config/solana/devnet.json \
>     -cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json \
>     ./assets
> ```

Thanks for the update! Followed the document and it works.

I found that I used wrong argument and that's why. the config.json solved my issue.

**Comment by rudebono** [comment]
> > @Wanackon @FlyingMonkes @haomaaax
> > Please set Candy's configuration
> > 
> > * https://docs.metaplex.com/candy-machine-v2/configuration
> > * https://docs.metaplex.com/candy-machine-v2/creating-candy-machine
> > 
> > example `-cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json`
> > ```shell
> > ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
> >     -e devnet \
> >     -k ~/.config/solana/devnet.json \
> >     -cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json \
> >     ./assets
> > ```
> 
> Thanks for the update! Followed the document and it works.
> 
> I found that I used wrong argument and that's why. the config.json solved my issue.

Good Luck !!

**Comment by Wanackon** [comment]
Thx

**Comment by green4you** [comment]
plz fix ur tutorial

**Comment by b3ucx** [comment]
hi, i got an error with candy machine can you help me?
TSError: ⨯ Unable to compile TypeScript:
helpers/accounts.ts:47:43 - error TS2554: Expected 0 arguments, but got 1.

47     accountInfo.delegatedAmount = new u64(0);
                                             ~

    at createTSError (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820:12)
    at reportTSError (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:824:19)
    at getOutput (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1014:36)
    at Object.compile (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1322:43)
    at Module.m._compile (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2554 ]

**Comment by maksimonishchenko** [comment]
Even with exampled config file
C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json \ ./example-assets
Or with one from configuration guide 
C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/config.json \ ./example-assets
result is the same
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\PC\~\metaplex\js\packages\cli\src\commands\upload.ts:119:24)
    at Command.<anonymous> (C:\Users\PC\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:271:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Ugochukwu-On** [comment]
> Even with exampled config file C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json \ ./example-assets Or with one from configuration guide C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/config.json \ ./example-assets result is the same upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (node:internal/errors:372:5) at validateString (node:internal/validators:120:11) at Object.dirname (node:path:654:5) at uploadV2 (C:\Users\PC~\metaplex\js\packages\cli\src\commands\upload.ts:119:24) at Command. (C:\Users\PC~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:271:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'ERR_INVALID_ARG_TYPE' }
> 
> updated: did found that on windows same error in cmd produced if \ not removed from a command tho:During this guide, we will use \ within example commands prior to new lines. On most shells (such as the shells on MacOS and Linux), this symbol means a new line. However, on Windows Command Prompt, it does not. If you are on Windows and are using the Command Prompt, enter the commands in a single line and remove the \ characters that we use in our examples. this part of tutorial is skipped

I’m still having the same error despite following all the step

**Comment by Ugochukwu-On** [comment]
> > Even with exampled config file C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json \ ./example-assets Or with one from configuration guide C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/config.json \ ./example-assets result is the same upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (node:internal/errors:372:5) at validateString (node:internal/validators:120:11) at Object.dirname (node:path:654:5) at uploadV2 (C:\Users\PC~\metaplex\js\packages\cli\src\commands\upload.ts:119:24) at Command. (C:\Users\PC~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:271:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'ERR_INVALID_ARG_TYPE' }
> > updated: did found that on windows same error in cmd produced if \ not removed from a command tho:During this guide, we will use \ within example commands prior to new lines. On most shells (such as the shells on MacOS and Linux), this symbol means a new line. However, on Windows Command Prompt, it does not. If you are on Windows and are using the Command Prompt, enter the commands in a single line and remove the \ characters that we use in our examples. this part of tutorial is skipped
> 
> I’m still having the same error despite following all the step

![Uploading image.jpg…]()
