### ISSUE TITLE
Unable to mint (Please help)

### ISSUE THREAD

**Issue by Medienor** [metaplex-foundation/metaplex#1408]
Hello, everything is okey.. except for mint part..
can't seem to mint.

i use this command: **ts-node candy-machine-v2-cli.ts mint_one_token -e devnet -k DEV9PBu7gJDfxhuui5X4Yy1m6SABmXKfoupycrCe3PCQ.json -c cm2test**

here is console log:

<img width="953" alt="mintproblem" src="https://user-images.githubusercontent.com/73185535/148300109-5abd3d99-2cc3-4d87-9716-a52570ff64da.png">

**Comment by jzsiggy** [comment]
Same issue here!

**Comment by alialani1993** [comment]
same issue with u, one thing i noticed when uploading is the size. see how it says size 0 undefined. does urs say that when you upload?

![image_2022-01-07_101843](https://user-images.githubusercontent.com/30391298/148564785-633b0ddf-c67f-45e7-b08e-5988792de466.png)

**Comment by Medienor** [comment]
Yes it does, but it's successfull

fre. 7. jan. 2022, 16:20 skrev alialani1993 ***@***.***>:

**Comment by Medienor** [comment]
It look just like urs

fre. 7. jan. 2022, 17:15 skrev Josef Eines ***@***.***>:

**Comment by calam1** [comment]
I got a similar error 

```
REST null result for 2wiTwqt9sE5Hh1xABrYMvxkLXgaEftoSZawWsiYfHweqbYKzEebKXfq5dhxdaeRF99Yj6VjcnFvu6cdNjoFfkdf8 null
Rejected via websocket { InstructionError: [ 4, { Custom: 319 } ] }
Timeout Error caught {
  err: { InstructionError: [ 4, [Object] ] },
  slot: 106257777,
  confirmations: 0
}
```

**Comment by alialani1993** [comment]
anybody find a solution yet?

**Comment by calam1** [comment]
> I got a similar error
> 
> ```
> REST null result for 2wiTwqt9sE5Hh1xABrYMvxkLXgaEftoSZawWsiYfHweqbYKzEebKXfq5dhxdaeRF99Yj6VjcnFvu6cdNjoFfkdf8 null
> Rejected via websocket { InstructionError: [ 4, { Custom: 319 } ] }
> Timeout Error caught {
>   err: { InstructionError: [ 4, [Object] ] },
>   slot: 106257777,
>   confirmations: 0
> }
> ```

So I got the above error on my MacBook Pro, I decided to try this on my Ubuntu laptop. It worked. So maybe there is some underlying differences in some packages, not sure

**Comment by Bladen1** [comment]
Having the same issue. Using a Macbook.

››
![image](https://user-images.githubusercontent.com/89113308/148628497-02ef2753-d431-4b12-a087-cad98b934c55.png)

**Comment by alialani1993** [comment]
what helped me was starting over.

**Comment by calam1** [comment]
> what helped me was starting over.

yeah, it's odd for me. I deleted the repo and tried it again on my Mac just now. I got the same error. Not sure what I am doing wrong if you got it to work (assuming you ran on a mac). But running on my Ubuntu setup, was a lot less problems, I uploaded multiple times, and minted. Guess I will stick with my linux setup when I run metaplex, at least for now.

**Comment by alialani1993** [comment]
> 

Im on windows, but i found that i need to delete the .cache folder that gets generated when i restart

**Comment by reynolkb** [comment]
i'm running into this problem as well on a mac, if anyone finds a fix please let me know.

**Comment by Bladen1** [comment]
Well I tried to restart and start again, but again failed. I followed the metaplex documents guidelines.

Has anyway strayed away from the metaplex docs and still got it to work?

**Comment by what-name** [comment]
> same issue with u, one thing i noticed when uploading is the size. see how it says size 0 undefined. does urs say that when you upload?
> 
> ![image_2022-01-07_101843](https://user-images.githubusercontent.com/30391298/148564785-633b0ddf-c67f-45e7-b08e-5988792de466.png)

Please paste in here the exact command you used for uploading.

The issue here is that you're not uploading any assedts. Maybe you didn't execute the upload command right. Make sure to input where your assets are located when you run `upload`. See: https://docs.metaplex.com/candy-machine-v2/creating-candy-machine

**Comment by alialani1993** [comment]
I've learned lots about candymachine cli in the last day or two. I've found that deleting the file in the .cache folder or using a different file name for -c in ur upload command helps this issue. Others may not be having the issue for the same reason as I did, but this is what solved it for me. If you're following the metaplex documentation u will be using "-c example". After you upload once, you cannot use "example" anymore until you delete the 'devnet-example' file from inside the .cache folder OR use something else like "-c example2".
Hope that helps someone.

**Comment by Bladen1** [comment]
Uploading seems to be ok for me....

I then verify the upload which seems to be fine


But then when i come to mint, it crashes


![image](https://user-images.githubusercontent.com/89113308/148660149-788b6361-9e6c-4cca-ab3b-308d91b21fe5.png)![image](https://user-images.githubusercontent.com/89113308/148660178-7ac9df7f-883f-47ba-9bb2-6627611cd0a7.png)
![image](https://user-images.githubusercontent.com/89113308/148660149-788b6361-9e6c-4cca-ab3b-
308d91b21fe5.png)
![image](https://user-images.githubusercontent.com/89113308/148660225-7166e10e-a0c2-41fd-aadb-9a00b45feb01.png)

**Comment by Bladen1** [comment]
> I've learned lots about candymachine cli in the last day or two. I've found that deleting the file in the .cache folder or using a different file name for -c in ur upload command helps this issue. Others may not be having the issue for the same reason as I did, but this is what solved it for me. If you're following the metaplex documentation u will be using "-c example". After you upload once, you cannot use "example" anymore until you delete the 'devnet-example' file from inside the .cache folder OR use something else like "-c example2". Hope that helps someone.

Ok cool, will try that

**Comment by reynolkb** [comment]
I was having issues with the command line and also trying to get the [minting react app](https://docs.metaplex.com/candy-machine-v2/mint-frontend) to work. Below are the solutions I found.

**Command Line**
I updated `gatekeeper` to `null` which seemed to fix the issue for me. I'm able to mint now through the command line.

The one thing i'm not sure about is the command line is returning `No instructions provided`, but is minting the tokens. Not sure if this matters or not?

**Minting React App**
i was given this tip, if you change line 170 to `const presale = state.data.whitelistMintSettings?.presale &&` it worked for me. essentially all you're adding is the new es6 optional chaining operator. i was getting an error in the console which is below. By adding the `?` you're essentially saying that if the data before `?.` is nullish then it will return `undefined`.

![](https://media.discordapp.net/attachments/898625218426339448/929493734188515349/Screen_Shot_2022-01-08_at_1.55.50_PM.png)

**Comment by calam1** [comment]
> I was having issues with the command line and also trying to get the [minting react app](https://docs.metaplex.com/candy-machine-v2/mint-frontend) to work. Below are the solutions I found.
> 
> **Command Line** I updated `gatekeeper` to `null` which seemed to fix the issue for me. I'm able to mint now through the command line.
> 
> The one thing i'm not sure about is the command line is returning `No instructions provided`, but is minting the tokens. Not sure if this matters or not?
> 
> **Minting React App** i was given this tip, if you change line 170 to `const presale = state.data.whitelistMintSettings?.presale &&` it worked for me. essentially all you're adding is the new es6 optional chaining operator. i was getting an error in the console which is below. By adding the `?` you're essentially saying that if the data before `?.` is nullish then it will return `undefined` which fixed the issue for me.
> 
> ![](https://camo.githubusercontent.com/a07a192f628205975bb24ab0f47e9a4f5e84287b847407869fa1d6d4563269e4/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3839383632353231383432363333393434382f3932393439333733343138383531353334392f53637265656e5f53686f745f323032322d30312d30385f61745f312e35352e35305f504d2e706e67)

regarding the CLI on a mac, the changing the gateway to null worked for me just now

**Comment by what-name** [comment]
See fix https://github.com/metaplex-foundation/metaplex/pull/1470 for the error seen on screenshot above.

**Comment by calam1** [comment]
If I understand the error message maps to not enough SOL to mint; not sure why the gatekeeper, which is a captcha thing, causes this error

```
Timeout Error caught { InstructionError: [ 4, { Custom: 319 } ] }
RESULT { err: { InstructionError: [ 4, [Object] ] } }
Rejected via websocket { InstructionError: [ 4, { Custom: 319 } ] }
...
...
Error: Transaction failed: Custom program error: 0x13f
    at sendSignedTransaction (/Users/xcxl200/git/solana/metaplex/js/packages/cli/src/helpers/transactions.ts:142:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

https://raw.githubusercontent.com/metaplex-foundation/metaplex/master/rust/test/fair-launch-types.ts
```
{"code":319,"name":"NotEnoughSOL","msg":"Not enough SOL to pay for this minting"}
```

**Comment by Bladen1** [comment]
> I was having issues with the command line and also trying to get the [minting react app](https://docs.metaplex.com/candy-machine-v2/mint-frontend) to work. Below are the solutions I found.
> 
> **Command Line** I updated `gatekeeper` to `null` which seemed to fix the issue for me. I'm able to mint now through the command line.
> 
> The one thing i'm not sure about is the command line is returning `No instructions provided`, but is minting the tokens. Not sure if this matters or not?
> 
> **Minting React App** i was given this tip, if you change line 170 to `const presale = state.data.whitelistMintSettings?.presale &&` it worked for me. essentially all you're adding is the new es6 optional chaining operator. i was getting an error in the console which is below. By adding the `?` you're essentially saying that if the data before `?.` is nullish then it will return `undefined` which fixed the issue for me.
> 
> ![](https://camo.githubusercontent.com/a07a192f628205975bb24ab0f47e9a4f5e84287b847407869fa1d6d4563269e4/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3839383632353231383432363333393434382f3932393439333733343138383531353334392f53637265656e5f53686f745f323032322d30312d30385f61745f312e35352e35305f504d2e706e67)

This worked for me. Switching off the captcha and stating it as null.

I guess this is a little win. Gonna have to turn on the Captcha when going live.

**Comment by goriunov** [comment]
https://github.com/metaplex-foundation/metaplex/pull/1458

**Comment by ricarra08** [comment]
Per Documentation: 
When you use a captcha, you will not be able to mint from the CLI command mint_one_token. If you want to pre-mint from a CMv2 and are planning to use a captcha, you should set the goLiveDate to null and turn captcha (temporarily) off. This will allow you to mint from the command line, but only you as the CMv2 authority. Once you complete the pre-mint, turn captch on and set the correct goLiveDate.

Solution: 
Change the configuration file properties in metaplex. Set:  
"gatekeeper" : null 
"goLiveDate" : null

Update your config file by running this command: 
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts update_candy_machine 

and including the necessary flags and you should be good to go

**Comment by sirateck** [comment]
> Per Documentation: When you use a captcha, you will not be able to mint from the CLI command mint_one_token. If you want to pre-mint from a CMv2 and are planning to use a captcha, you should set the goLiveDate to null and turn captcha (temporarily) off. This will allow you to mint from the command line, but only you as the CMv2 authority. Once you complete the pre-mint, turn captch on and set the correct goLiveDate.
> 
> Solution: Change the configuration file properties in metaplex. Set: "gatekeeper" : null "goLiveDate" : null
> 
> Update your config file by running this command: ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts update_candy_machine
> 
> and including the necessary flags and you should be good to go

Nice answer! It's working for me 👏

**Comment by victorajayi** [comment]
how do i check the candymachine authority?

**Comment by ricarra08** [comment]
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts show \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -c example
    
    But with your own flags

**Comment by sheldonsmickley** [comment]
> > Per Documentation: When you use a captcha, you will not be able to mint from the CLI command mint_one_token. If you want to pre-mint from a CMv2 and are planning to use a captcha, you should set the goLiveDate to null and turn captcha (temporarily) off. This will allow you to mint from the command line, but only you as the CMv2 authority. Once you complete the pre-mint, turn captch on and set the correct goLiveDate.
> > Solution: Change the configuration file properties in metaplex. Set: "gatekeeper" : null "goLiveDate" : null
> > Update your config file by running this command: ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts update_candy_machine
> > and including the necessary flags and you should be good to go
> 
> Nice answer! It's working for me 👏

This also worked for me - use https://docs.metaplex.com/candy-machine-v2/update for correct flags for update_candy_machine
