### ISSUE TITLE
Starter kit to deliver webview as native app

### ISSUE THREAD

**Issue by maximkoretskiy** [metaplex-foundation/metaplex#141]
It would be nice to have a scaffold project to publish an already made site as native without additional development.

A React Native application with webview could be a simple solution with a lower entrance threshold.  

I could contain guides on how to configure and deliver applications.

**Comment by bhgames** [comment]
This sounds more like a grant application and less like an issue. Please visit our grants page on our website and apply! I'm closing this for now.
