### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'index')

### ISSUE THREAD

**Issue by serverhan** [metaplex-foundation/metaplex#1412]
Hey, i tried to upload about 2000 .gif NFT's to CmV2 on mainnet-beta. Upload took about 6 hours and got this response:
Done. Successful = false.
When i tried to upload again i got this error:

![image](https://user-images.githubusercontent.com/49041819/148347381-32c7c186-6358-4f66-97fa-44d911a3da92.png)

And when i use verify-upload comment, I got this:

Error: predefined number of NFTs (xxxxx) is smaller than the uploaded one (yyyy). It says 10 of my NFT's did not uploaded. Please help about this, I have mint about hours!

**Comment by stegaBOB** [comment]
How did you run upload again? Please share the commands you used exactly

**Comment by serverhan** [comment]
> How did you run upload again? Please share the commands you used exactly

Used the same command when i first start uploading

This is the command:

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/mainnet-beta.json -cp config.json -c sbb ./assets --rpc-url https://ssc-dao.genesysgo.net/

This is the verify command:

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts verify -e mainnet-beta -k ~/.config/solana/mainnet-beta.json -c sbb

**Comment by stegaBOB** [comment]
Are you on the `release/v1.1.0` branch or `master` branch? The issue should be fixed in the release branch

**Comment by serverhan** [comment]
I installed from the following link https://docs.metaplex.com/candy-machine-v2/getting-started

I think it follows master branch, thank you for your help.

**Comment by Fulgurus** [comment]
Same issue here, any idea ?

**Comment by serverhan** [comment]
Solved by downloading release/v1.1.0 branch with zip file and and extract it the same place you cloned metaplex folder. Before you do, delete the old metaplex file ofc :)

You can download here: https://github.com/metaplex-foundation/metaplex/tree/release/v1.1.0

**Comment by stegaBOB** [comment]
Like @serverhan said, this issue is resolved in the release v1.1.0 branch. Thanks! Closing this issue

**Comment by lawncegoh** [comment]
hi i have the same issue as the stated, the upload function doesn't allow for re-upload of those assets that failed to got onto chain i.e onChain = 'false', hence index stays at 0, what is the workaround given that I'm already on the release version

**Comment by stegaBOB** [comment]
We will investigate this issue. Thanks for letting us know

**Comment by Fulgurus** [comment]
Encountered this issue. We fixed it by setting all onChain=false assets **link attribute to empty string**.
Then re-typed command. Then 2 scenarios:
- it works
- it doesn't work. You end up with a new error looking like :

```
Size 220 { mediaExt: '', index: '150' }
Saved bundle upload result to cache.
upload was not successful, please re-run. [Error: ENOENT: no such file or directory, stat 'C:\Users\eve22\metaplex\assets\150'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\Users\eve22\metaplex\assets\150'
}
```

Then to fix it, i had to go to **upload.ts** file and update this :

line 468 : `acc.push({ mediaExt: <your asset extension>, index: key });` instead of `acc.push({ mediaExt: ext, index: key });`

**Comment by stegaBOB** [comment]
I actually wasn't able to reproduce the issue. @lawncegoh, can you confirm that you are on the latest version of master branch?

**Comment by stegaBOB** [comment]
Same with you, @Fulgurus

**Comment by lawncegoh** [comment]
@stegaBOB Hey i fixed it, realised i was indeed on the wrong branch, my bad!

**Comment by stegaBOB** [comment]
No worries. Thanks for the quick reply! Glad you were able to get it fixed. Closing this issue now :)
