### ISSUE TITLE
Candy Machine with gateway can only be minted 2 minutes after goLiveDate

### ISSUE THREAD

**Issue by nelsontky** [metaplex-foundation/metaplex#1414]
**Describe the bug**
A candy machine that uses a gatekeeper that has a go live date of `2022-01-06T08:00:00.000Z` can only be minted at `2022-01-06T08:02:00.000Z`

**To Reproduce**
Use the config below:
```
{
  "price": 0.5,
  "number": 10,
  "gatekeeper": {
    "gatekeeperNetwork": "ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6",
    "expireOnUse": true
  },
  "solTreasuryAccount": "WALLET_ADDRESS",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "CURRENT_TIME_IN_ISO_FORMAT (e.g. 2022-01-06T08:00:00.000Z)",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "storage": "arweave",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "awsS3Bucket": null,
  "noRetainAuthority": false,
  "noMutable": false
}
```
If we try to mint with the FLP UI on the same minute as the `goLiveDate`, mint would fail.

**Expected behavior**
If we try to mint with the FLP UI on the same minute as the `goLiveDate`, mint should pass.

**Screenshots**
Screenshot of mint attempt that would fail. CM `goLiveDate` is `2022-01-06T08:12:00.000Z`, which was more than 1 minute before the time I tried to mint.
![fail](https://user-images.githubusercontent.com/7272103/148354004-6cfc2e81-4216-4c90-802c-79be90f85ef3.png)

When 2 minutes has passed from the `goLiveDate` mint would be successful.
![pass](https://user-images.githubusercontent.com/7272103/148354626-6af4ee35-1498-483a-b319-eab614ac68d1.png)

**Comment by prashantcrypto** [comment]
i can make your candymcahine for 1 sol.
if you are interseted message me on discord shyaid#3516
