### ISSUE TITLE
Unable to mint due to api.civic.com 400

### ISSUE THREAD

**Issue by eryuan6939** [metaplex-foundation/metaplex#1416]
Hi,

Unable to mint, this happened after I done the captcha verification.
Anyone triggered same error with me? May I know is it possible to turn off/ disabled this verification?
 

![400 Bad Request](https://user-images.githubusercontent.com/52315288/148361070-aab3b5d2-17d7-4d31-9d62-7ec3850c7992.PNG)
![RecaptchaCheckStrategy Failed](https://user-images.githubusercontent.com/52315288/148361605-46627c3a-5a29-41ea-9e5f-5cc0f4d38431.PNG)

**Comment by nelsontky** [comment]
You could set the `"gateway": null` in the config to disable captcha. But if you still want captcha on devnet, you should use this `https://api.devnet.solana.com` RPC url. Other RPC urls on devnet did not work for me except for the official one

**Comment by stegaBOB** [comment]
Closing this issue.

**Comment by athmane2197** [comment]
> Refere

Thank you for your answer but in which file exactly should I put it?

"gateway": null
