### ISSUE TITLE
Candy Machine V2 CLI doesn't install and ts-node candy-machine-v2-cli.ts upload gives path error !!

### ISSUE THREAD

**Issue by mnadirs** [metaplex-foundation/metaplex#1418]
Candy Machine V2 CLI doesn't install and ts-node candy-machine-v2-cli.ts upload gives path error.

command: 
ts-node candy-machine-v2-cli.ts upload ./example-assets/ --env devnet --keypair /home/ubuntu/.config/solana/devnet.json

output: 
(node:7801) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:490:10)
    at Object.readFileSync (fs.js:394:35)
    at getCandyMachineV2Config (/home/ubuntu/metaplex/js/packages/cli/src/helpers/various.ts:49:27)
    at Command.<anonymous> (/home/ubuntu/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:99:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LukaszKrzywda** [comment]
the same error

**Comment by prashantcrypto** [comment]
I can make your candy machine just for 1.5-2 sol. 
I can make from my pc. 
Dm me if you are interested. 
My discord shyaid#3516

**Comment by martinwhitman** [comment]
I assume you've tried the same command but with /example-assets/ or with example-assets or with "example-assets"?

**Comment by willtai** [comment]
Same error. Have also tried this with an incorrect directory on purpose e.g. `example-assets-wrong` it clearly manages to try and scan for the directory 

```
Error: ENOENT: no such file or directory, scandir 'example-assets-wrong'
```

**Comment by victorajayi** [comment]
having the exact same issue with the new metaplex

**Comment by rudebono** [comment]
Try `yarn install`
- https://docs.metaplex.com/candy-machine-v2/getting-started

```sh
$ git clone https://github.com/metaplex-foundation/metaplex.git ~/metaplex
```

```sh
$ yarn install --cwd ~/metaplex/js/
```

**Comment by victorajayi** [comment]
All the dependencies are already installed with yarn install.
 I'm currently trying to use the code below to upload the assets on the devnet but I keep getting the error message.

"npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair /Users/victo/.config/solana/devnet-victo.json" 

Error message:
wallet public key: 4nKrvRmb6B3feKxRM8UgedJ6cBADv7qHJde6D4sF9zuu
(node:15272) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:490:10)
    at Object.readFileSync (fs.js:394:35)
    at getCandyMachineV2Config (C:\Users\victo\Downloads\metaplex\js\packages\cli\src\helpers\various.ts:49:27)
    at Command.<anonymous> (C:\Users\victo\Downloads\metaplex\js\packages\cli\src\candy-machine-cli.ts:99:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero 
exit code.

**Comment by rudebono** [comment]
@victorajayi

Did you set up `-cp` options ?

**Comment by victorajayi** [comment]
there is no config.json file to change configurations. or maybe i just cant seem to find it

**Comment by stegaBOB** [comment]
For everyone that is having issues in this thread, the answer is documented in our candy machine v2 documentation. You are missing a config file. Please read our docs first at https://docs.metaplex.com/candy-machine-v2

**Comment by nthprime** [comment]
read docs: https://docs.metaplex.com/candy-machine-v2/Configuration

**Comment by maksimonishchenko** [comment]
Even with exampled config file
C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/example-candy-machine-upload-config.json \ ./example-assets
Or with one from configuration guide 
C:\Users\PC>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~/metaplex/js/packages/cli/config.json \ ./example-assets
result is the same
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\PC\~\metaplex\js\packages\cli\src\commands\upload.ts:119:24)
    at Command.<anonymous> (C:\Users\PC\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:271:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
any help appreciated. ive tried to run metaplex front to mint some nft there in issues someone typed about sdk and candymachine so since frontend is not working (endless loading loop after wallet connection) i did gived it a try to mint using cli tools ended up stuck here :( windows 10 if it can matter any help really appreciated

**Comment by Xalipso21** [comment]
Error: Cannot find module './candy-machine-v2-cli.ts'
