### ISSUE TITLE
Unknow command 'create_candy_machine'

### ISSUE THREAD

**Issue by skimaharvey** [metaplex-foundation/metaplex#1423]
After entering in my terminal
`ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts create_candy_machine --env devnet --keypair ~/.config/solana/devnet.json -p 1`

I get `error: unknown command 'create_candy_machine' `

What is the new command we should enter with the v2 cli? 

Thank you

**Comment by Solseum** [comment]
CMv2 dont use create_candy_machine command. You just need upload and then verify. When verify says "ready to deploy" you are ready to mint or create the mint Page.

Please read the docs so you dont have any issue in the future, also check the available commands using the help command!

https://docs.metaplex.com/candy-machine-v2/introduction

**Comment by stegaBOB** [comment]
Please review our docs. https://docs.metaplex.com. It has detailed explanations/guides for how to use v2. Closing this issue
