### ISSUE TITLE
Obtaining Hash List

### ISSUE THREAD

**Issue by serverhan** [metaplex-foundation/metaplex#1428]
Hey there, is there a way to obtain hash list for future mint to pre-applying secondary markets?

For example, we could generate in https://magiceden.io/mintlist-tool with Candy Machine ID or a creator address in CmV1. But in v2 we just can see the minted ones, not all of them. This is a problem for a future mint.

I'm glad if someone helps.

**Comment by solsoccer** [comment]
same issue please help

**Comment by solsoccer** [comment]
@bhgames please help we can get hashlift for listing NFT's on secondary market its a major issue

**Comment by solsoccer** [comment]
@bhgames we have alreadt minted 100X nfts with v2 candy machine  and is not vefired because we cant extract hash list now with candy machine v2

**Comment by goriunov** [comment]
Did you try to use metaboss ?

**Comment by solsoccer** [comment]
@goriunov  can you share me the link to find it

**Comment by goriunov** [comment]
https://github.com/samuelvanderwaal/metaboss

**Comment by samuelvanderwaal** [comment]
Just a note for anyone who finds this issue:

> Hey there, is there a way to obtain hash list for future mint to pre-applying secondary markets?

You cannot get mint lists (hash lists) for NFTs that have not been minted yet. NFTs that aren't minted don't have mint accounts.

**Comment by solsoccer** [comment]
Hi Guys
 we have completed our min ,But Still we cannot get the haslist from https://tools.abstratica.art/ 
or  magic eden 

what could be the issues?

**Comment by samuelvanderwaal** [comment]
@solsoccer try `metaboss snapshot mints -c <candy_machine_id> --v2`
