### ISSUE TITLE
"Warning: Failed prop type" Error

### ISSUE THREAD

**Issue by DevMarcosss** [metaplex-foundation/metaplex#1429]
Hello, I get this error when I set a goLiveDate;
![b7c48c211375bcbd12e59b5a6d85b0a4](https://user-images.githubusercontent.com/56926590/148442727-9f8a22f4-fd3d-418f-9d86-f2bb4a4eb9b5.png)

What could be causing this? Thanks in advance for your help <3

**Comment by tolgaand** [comment]
I have this problem.

**Comment by DevMarcosss** [comment]
> I have this problem.

When your Date is finished, you can see mint container. This is how UI works. So there is no countdown

**Comment by tolgaand** [comment]
He also doesn't work on the white list.
I don't know if I'm making a mistake.
![2022-01-07_21-20](https://user-images.githubusercontent.com/26303690/148589058-923ee267-6456-49cc-af3d-991e2115e705.png)
![2022-01-07_21-18](https://user-images.githubusercontent.com/26303690/148588920-c73716fe-9d2e-4dda-b29b-0c8f642b04c3.png)

**Comment by DevMarcosss** [comment]
I haven't tried presale yet. but you can add the address you want to whitelist there like this;
`"mint" : ["7nE1GmnMmDKiycFkpHF7mKtxt356FQzVonZqBWsTWZNf","ADDNEWADDRESS"]` to this section.

Then update your candymachine
I don't want to give wrong info. Try this and see.

**Comment by tonyboylehub** [comment]
Prop errors are design errors based on React, not actual computation or logic errors in the code itself.

I'd still look at using a different community built UI as this has too many errors for beginners to fix on their own.
