### ISSUE TITLE
candymachine state fields itemsRedeemed & itemsRemaining not updating

### ISSUE THREAD

**Issue by franraknic** [metaplex-foundation/metaplex#1443]
**Describe the bug**
Candy machine state `itemsRedeemed` value always 0

**To Reproduce**
1 Clone metaplex
2 start fair-launch web
3. setup a valid candy machine & put the id into config
4. log results of `getCandyMachineState` function
5. mint a couple of your NFTs and repeat step 4

**Expected behavior**
Fields `itemsRedeemed` & `itemsRemaining` should change after successful mints and display number of minted NFTs and remaining NFTs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96

This used to work on CM v1 and I used it to setup a progress bar (itemsRedeemed / itemsRemaining) on the minting websites.

**Comment by roederw** [comment]
Fair Launch is not longer a directory in our repro. Could you pull and use `candy-machine-ui`?

**Comment by stegaBOB** [comment]
In addition, even in the most updated version, the state isn't intended to change immediately. We are working on potential fixes to make it smoother from a UX perspective to reflect the supply after someone mints.
