### ISSUE TITLE
Candy Machine Upload Cost

### ISSUE THREAD

**Issue by Wanackon** [metaplex-foundation/metaplex#1447]
Hi, I use CMv2 to upload images to arweave and it costs ~0.005 SOL per token. It means I need aprox 25 SOL to prepare to mint my collection of 5000 nfts.

There is a way to upload images to arweave with lesser cost, or there is a different way?

**Comment by samuelvanderwaal** [comment]
I don't know where you're getting 0.005 SOL to upload data to Arweave, are your files extremely large? I just ran a test upload with 10 small files using the `arweave-sol` storage method (Bundlr) and it cost 0.000023144 SOL. For 5000 asset pairs that's only 0.01157 SOL which is negligible compared to the Solana rent costs. 

See this for Arweave costs: https://arweavefees.com/
And this for calculator Solana rent: https://feecalc.live/

**Comment by Wanackon** [comment]
Thx for answer, I try to compress images and it already significantly cut fee.

**Comment by Wanackon** [comment]
Thx for answer, I try to compress images and it already significantly cut fee.
