### ISSUE TITLE
candy machine v2 configuration struct members aren't public

### ISSUE THREAD

**Issue by ozgrakkurt** [metaplex-foundation/metaplex#1448]
**Is your feature request related to a problem? Please describe.**
struct members of EndSettings, HiddenSettings, WhitelistMintSettings, GatekeeperConfig

**Describe the solution you'd like**
make members public

**Additional context**
we are trying to construct instructions through this library and then we want to send the instructions to chain with Solana Rpc Client in rust

**Comment by samuelvanderwaal** [comment]
Fixed by [this PR](https://github.com/metaplex-foundation/metaplex-program-library/pull/82) in the `metaplex-program-library` repo. A crates.io crate will be published this week.

**Comment by samuelvanderwaal** [comment]
A crate was not published that week, but there is one up now: https://crates.io/crates/mpl-candy-machine
