### ISSUE TITLE
Error when creating candy machine

### ISSUE THREAD

**Issue by Baklaza** [metaplex-foundation/metaplex#1449]
Good evening! Guys, tell me. I enter the command into the console (all paths are specified correctly), this is how it looks:

ts-node C:\Users\Esh\Desktop\FortePiano\FortePianoSite\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp C:\Users\Esh\Desktop\FortePiano\FortePianoSite\metaplex\js\packages\cli\config.json -c example C:\Users\Esh\Desktop\Assets

Throws this error:

Beginning the upload for 10 (img+json) pairs
started at: 1641587507925
Size 10 { mediaExt: '.png', index: '1' }
upload was not successful, please re-run. TypeError: Cannot read properties of u
ndefined (reading '0')
at getAssetManifest (C:\Users\Esh\Desktop\FortePiano\FortePianoSite\metaplex
\js\packages\cli\src\commands\upload.ts:488:28)
at C:\Users\Esh\Desktop\FortePiano\FortePianoSite\metaplex\js\packages\cli\s
rc\commands\upload.ts:212:30
at Array.map (<anonymous>)
at uploadV2 (C:\Users\Esh\Desktop\FortePiano\FortePianoSite\metaplex\js\pack
ages\cli\src\commands\upload.ts:204:63)
at Command.<anonymous> (C:\Users\Esh\Desktop\FortePiano\FortePianoSite\metap
lex\js\packages\cli\src\candy-machine-v2-cli.ts:183:21)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
ended at: 2022-01-07T20:31:48.097Z. time taken: 00:00:00

What can be done about it? I will be very grateful for your advice, thank you!

**Comment by stegaBOB** [comment]
It looks like there may be an error with your asset files. Would you mind posting what your 0.json file looks like?

**Comment by Baklaza** [comment]
> It looks like there may be an error with your asset files. Would you mind posting what your 0.json file looks like?

Thank you for your feedback! File looks like this:

`{
    "name": "Forte & Piano #0",
    "symbol": "FP",
    "description": "description",
    "seller_fee_basis_points": 500,
    "image": "0.png",
    "external_url": "https://solflare.com",
    "attributes": [
        {
            "trait_type": "Background",
            "value": "#D0FFEA"
        },
        {
            "trait_type": "Piano Color",
            "value": "Mint"
        },
        {
            "trait_type": "Element on piano",
            "value": "Bar-Stool White"
        },
        {
            "trait_type": "Keyboard",
            "value": "Cups"
        }
    ],
    "collection": {
        "name": "Forte & Piano",
        "family": "Forte & Piano"
    },
    "properties": {
        "creators": [
            {
                "address": "3mZgKcZznBHtj6fYEgXh2T8he2vMb8J8LuK9bFKuwnLn",
                "share": 100
            }
        ]
    }
}`

**Comment by stegaBOB** [comment]
you're missing the files attribute in the properties array. Technically it isn't really needed though, and it shouldn't fail in the way it has. Check out our docs at https://docs.metaplex.com to view the metadata standard
