### ISSUE TITLE
Metaplex site stuck in loading loop!!

### ISSUE THREAD

**Issue by hippiemeraki** [metaplex-foundation/metaplex#1450]
**Describe the bug**
While loading the metaplex in local server its stuck in the loading page I mean forever its not returning from the loop.
My fork also has the same issue.

**To Reproduce**
1. Go to 'https://hippiemeraki.github.io/metaplex#/'
2. See error

**Expected behavior**
It should have shown the initializer but It doesn't.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by naseer-hussain** [comment]
I also face the same issue stuck in the forever loading loop!

**Comment by stegaBOB** [comment]
This should be fixed in the latest version. Please try pulling the latest commit. If it still doesnt work feel free to reopen this issue.
