### ISSUE TITLE
Required option CP not specified, need help on which path to put

### ISSUE THREAD

**Issue by digomattar21** [metaplex-foundation/metaplex#1451]
Hey,
Does somebody know why im getting this error when i use ts node to upload with candy machine? In the video he uses candy-machine-cli but that was not on my depdencies only candy-machine-v1-cli oir candy-machine-v2-cli, i tried with both of them and this is my error output

COMMAND IM RUNNING:
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet-test2.json

OUTPUT:

error: required option '-cp, --config-path <string>' not specified

OS:
Linux Ubuntu 20.04.3

**Comment by stegaBOB** [comment]
The guide you are using is old/outdated. Please check our documentation at https://docs.metaplex.com
