### ISSUE TITLE
Problem with uploading candy machine v2

### ISSUE THREAD

**Issue by BORRODA8** [metaplex-foundation/metaplex#1452]
C:\Users\chern\Desktop\mint121212>ts-node .\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp ./config.json./assets

error: missing required argument 'directory'

Can somebody help?????

**Comment by stegaBOB** [comment]
You're missing a space after `-cp ./config.json`, which is resulting in the mising directory argument
