### ISSUE TITLE
Add MP4 uploads to CM 

### ISSUE THREAD

**Issue by serverhan** [metaplex-foundation/metaplex#1454]
Hey, got skipping unsupported format error when trying to upload mp4 files with CmV2. Checked the issue in some places and found closest way to the solution in this link: 

https://hackmd.io/@archaeopteryx/By4bpbA4F#Upload-MP4s

But it seems it is for v1 and some files mentioned in the link has changed. 

Cannot upload video NFT's, please help.

**Comment by stegaBOB** [comment]
We don't currently support this in our cli, however this is definitely something that will change in the future.

**Comment by roederw** [comment]
This is something we'd love to add. We will try and get to it when we can. Someone is MORE THAN WELCOME to do it for us and push a PR. I can help.

**Comment by AlexeiMachk** [comment]
Looking forward to this ^🤩

**Comment by zion-earthyfrodo** [comment]
Hi @roederw 

I would like to develop for .mp4 and .glb support -> #1506
Is there a way to get your help?

Cheers,
Frodo

**Comment by guillemap** [comment]
Just submitted a PR #1601
