### ISSUE TITLE
Problem with verify Candy machine v2

### ISSUE THREAD

**Issue by BORRODA8** [metaplex-foundation/metaplex#1461]
C:\Users\chern\Desktop\mint121212>ts-node C:\Users\chern\Desktop\mint121212\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts verify -e devnet -k ~/.config/solana/devnet-test.json -cp ./config.json  ./assets

error: unknown command 'verify'

**Comment by ughodera** [comment]
Hi @BORRODA8 

use verify_upload instead of verify

https://docs.metaplex.com/candy-machine-v2/verify-upload
