### ISSUE TITLE
Problem with minting website

### ISSUE THREAD

**Issue by BORRODA8** [metaplex-foundation/metaplex#1463]
![изображение_2022-01-08_145953](https://user-images.githubusercontent.com/93973414/148645121-3fa19a1c-755d-473c-ac24-fe659a65cb59.png)

**Comment by BORRODA8** [comment]
> Fair Launch UI Has been deprecated, use new Candy machine UI
what is UI???

**Comment by stegaBOB** [comment]
This is an outdated version of the repo. Please pull from the latest commit or reclone the repo.
