### ISSUE TITLE
upload was not successful, please re-run. TypeError: Cannot read properties of undefined (reading 'files')

### ISSUE THREAD

**Issue by kvnuel** [metaplex-foundation/metaplex#1464]
Running a test on working with Candy Machine v2 and when I try to upload the PNGs+metadata, I get this error

![Capture](https://user-images.githubusercontent.com/97347816/148647103-75c509c7-a566-404b-abe1-a5887734dfe6.JPG)

**Comment by prashantcrypto** [comment]
Dmm me. 
I can teach you everything coreectly for just 2 sol.

**Comment by prashantcrypto** [comment]
If you are interested. 
My discord shyaid#3516

**Comment by Gwwm** [comment]
Hey @kvnuel . I have the same problem too. Mine is SyntaxError: Unexpected end of JSON input when tried to upload.

**Comment by Gwwm** [comment]
https://github.com/metaplex-foundation/metaplex/issues/1412
Kindly try this solution. Let me know if it works

**Comment by stegaBOB** [comment]
The issue is in your json files. Please share what your 0.json file looks like @kvnuel. It appears you are missing the properties.files property.

**Comment by kvnuel** [comment]
Hello! Yes I fixed the issue about 3 hours ago. Seemed the metadata for my
pngs we’re missing the properties and files attributes

**Comment by stegaBOB** [comment]
Perfect! I think we need some better error handling for that though. Glad you got it fixed.

**Comment by MunchMunchMunch** [comment]
> Hey @kvnuel . I have the same problem too. Mine is SyntaxError: Unexpected end of JSON input when tried to upload.

did you fix this?
