### ISSUE TITLE
Candy Machine V2  ts-node candy-machine-v2-cli.ts upload gives SyntaxError for -cp /path/config.json 

### ISSUE THREAD

**Issue by Gwwm** [metaplex-foundation/metaplex#1466]
**Describe the bug**
There is a SyntaxError when trying ts-node candy-machine-v2-cli.ts upload gives SyntaxError for -cp /path/config.json -e devnet. All env setup are checked and ready with the correct version. Mac m1-chip

**To Reproduce**
1. npx ts-node ~/NFT_trial/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload  -e devnet -k ~/NFT_trial/my-solana-wallet/my-keypair.json -cp ~/NFT_trial/config.json ~/NFT_trial/assets

**Screenshots**
<img width="963" alt="Screen Shot 2022-01-09 at 12 18 47 AM" src="https://user-images.githubusercontent.com/86285768/148651723-bcbe7a81-2601-4c05-bf20-b14db820e703.png">

**Desktop (please complete the following information):**
 - OS: iOS 12.0.1
 - Visual Studio
 - Version 1.58.2 (Universal)

**Additional context**
config.json
{
  "price": 1,
  "number": 1,
  "gatekeeper": {
    "gatekeeperNetwork": "ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6",
    "expireOnUse": true
  },
  "solTreasuryAccount": "9dfsqcvAdRTk8MADNw1RMxYMfaKnKvdS34ebAmEAGdfU",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "25 Dec 2021 00:00:00 GMT",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "storage": "arweave",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "awsS3Bucket": null,
  "noRetainAuthority": false,
  "noMutable": false
}

**Comment by Gwwm** [comment]
Highly appreciate if anyone can advise

**Comment by what-name** [comment]
The error is saying your config file is not valid json. Maybe you have something funky in there, what you pasted in here seems valid though. Try deleting the config file and pasting in the example one from the docs as is.

**Comment by stegaBOB** [comment]
I couldn't reproduce the issue. Like @what-name said, it seems to be something with your config. Make sure the config path is correct and that the config if formatted correctly. Feel free to add comments to this post if it still doesn't work.

**Comment by Gwwm** [comment]
Hey guys thanks so much for the help. Tried with the example doc and double checked the path but the problem still exists. Do you have any idea or I should delete everything and retry from the beginning?

**Comment by Gwwm** [comment]
(base) -MacBook-Air src % ts-node candy-machine-v2-cli.ts upload -e devnet -k /Users/NFT_trial/my-solana-wallet/my-keypair.json -cp /Users/NFT_trial/config.json /Users/NFT_trial/assets -c all
wallet public key: 9dfsqcvAdRTk8MADNw1RMxYMfaKnKvdS34ebAmEAGdfU
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type /Users/NFT_trial/assets/.DS_Store
Beginning the upload for 1 (img+json) pairs
started at: 1641715792988
Size 1 { mediaExt: '.png', index: '0' }
upload was not successful, please re-run. SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getAssetManifest (/Users/NFT_trial/metaplex/js/packages/cli/src/commands/upload.ts:489:35)
    at /Users/NFT_trial/metaplex/js/packages/cli/src/commands/upload.ts:213:32
    at Array.map (<anonymous>)
    at uploadV2 (/Users/NFT_trial/metaplex/js/packages/cli/src/commands/upload.ts:205:65)
    at Command.<anonymous> (/Users/NFT_trial/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

It gives "SyntaxError: Unexpected end of JSON input". Tried reinstall everything but the problem still exists. Do you guys have the same problem?
