### ISSUE TITLE
Dont work minting website

### ISSUE THREAD

**Issue by BORRODA8** [metaplex-foundation/metaplex#1469]
Dont work mint, maybe somebody know why?

![Снимок экрана (51)](https://user-images.githubusercontent.com/93973414/148660392-77d97729-bfcc-408c-bb75-7e4e6ee34586.png)

**Comment by what-name** [comment]
If you're asking for help, give as much information as possible. "Does not work, please help" is not enough information. Please paste here your CM configuration file, and a screenshot of what the browser's console is telling you (right click -> inspect -> console)

**Comment by BORRODA8** [comment]
![Снимок экрана (52)](https://user-images.githubusercontent.com/93973414/148661019-df9cea53-d3ca-4cae-87ed-8aa1902e5ba7.png)
![Снимок экрана (53)](https://user-images.githubusercontent.com/93973414/148661021-d2db7265-e270-4ae2-afc2-b5487f325358.png)

**Comment by bxuserx** [comment]
This is a common issue. LCAndy's discord has been talking about it all day, consistent among many users.

According to discord user Enciu:
"i found the problem. The bug with the lock button on mint. you have to comment line 170 and 171 in /metaplex/js/packages/candy-machine-ui/src/candy-machine.ts and put this code instead and it will work:"

const presale =
    state.data.whitelistMintSettings &&
    state.data.whitelistMintSettings.presale &&
    (!state.data.goLiveDate ||
      state.data.goLiveDate.toNumber() > new Date().getTime() / 1000);


I've verified this solution works, but the number remaining does not update live.

**Comment by stegaBOB** [comment]
This issue should be fixed in #1458. Thanks everyone!

**Comment by BORRODA8** [comment]
> This issue should be fixed in #1458. Thanks everyone!

but it doesnt work

**Comment by BORRODA8** [comment]
> This is a common issue. LCAndy's discord has been talking about it all day, consistent among many users.
> 
> According to discord user Enciu: "i found the problem. The bug with the lock button on mint. you have to comment line 170 and 171 in /metaplex/js/packages/candy-machine-ui/src/candy-machine.ts and put this code instead and it will work:"
> 
> const presale = state.data.whitelistMintSettings && state.data.whitelistMintSettings.presale && (!state.data.goLiveDate || state.data.goLiveDate.toNumber() > new Date().getTime() / 1000);
> 
> I've verified this solution works, but the number remaining does not update live.

can you give his discord pls

**Comment by BORRODA8** [comment]
> This issue should be fixed in #1458. Thanks everyone!

![изображение_2022-01-09_115843](https://user-images.githubusercontent.com/93973414/148677602-2a5afa43-a079-4e13-bc09-cb59a60580f5.png)

**Comment by stegaBOB** [comment]
Your .env file is not filled out correctly. Please make sure you fill that
out.
