### ISSUE TITLE
Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed

### ISSUE THREAD

**Issue by emersonthis** [metaplex-foundation/metaplex#1471]
**Describe the bug**
The `upload` command throws this error: `Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature ...`

**To Reproduce**
1. Create a config.json file
2. Create an assets folder full of png / json file pairs
3. Run the `upload` command (see example below)

```
$ ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/keypair.json -cp ./config.json -c cache-name --rpc-url https://solana--mainnet.datahub.figment.io/apikey/<REDACTED>/ ./nft_assets
wallet public key: <REDACTED>
USING CUSTOM URL https://solana--mainnet.datahub.figment.io/apikey/<REDACTED>/
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 60 (img+json) pairs
started at: 1641691927889
Size 0 undefined
Writing indices 0-9
Writing indices 30-39
Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5npsJb3gEbT39hcZoD3q9uPYhMroYWjYGefoCGyx6WxWVA57KGwirB2TygZBRCER1R4QimbE98JmLpzBar5zerM1 using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (/Users/me/Code/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:2602:13)
... (long strack trace)
saving config line 30-39 failed Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5npsJb3gEbT39hcZoD3q9uPYhMroYWjYGefoCGyx6WxWVA57KGwirB2TygZBRCER1R4QimbE98JmLpzBar5zerM1 using the Solana Explorer or CLI tools.
... (long stack trace)
Writing indices 40-49
Writing indices 50-59
Done. Successful = false.
```

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Metaplex CLI v2
 - Node v14.18

**Comment by prashantcrypto** [comment]
I can make candy machine for just 1-2 sol. 
My discord shyaid#3516

**Comment by prashantcrypto** [comment]
I can make candy machine for just 1-2 sol. 
My discord shyaid#3516

**Comment by stegaBOB** [comment]
The Solana network was most likely having issues at that time. That issue is due to the transaction not being found within 1 minute, which is out of our hands unfortunately. Please try again and let us know if it is working now. In addition, the `--storage arweave-sol` is usually better/faster for uploading on mainnet vs the arweave option.

**Comment by loosebucks** [comment]
I've been trying for hours now and getting the same result

**Comment by timadewale1** [comment]
@loosebucks  were you ever able to get past these issue
