### ISSUE TITLE
Typo in candy-machine-v2 page

### ISSUE THREAD

**Issue by RktCrypto** [metaplex-foundation/metaplex#1472]
https://docs.metaplex.com/candy-machine-v2/preparing-assets

Notice that the difference in the metadata between each image is on:

"name" property: "Number #0000" in the first image and "Number #0010" in the last image

should be

Number #0001 instead of Number #0000

**Comment by stegaBOB** [comment]
Thanks. Fix on docs is being made. In the future, you can open issues/prs on our docs repo instead of this one for docs related issues. Thanks again.
