### ISSUE TITLE
Retrieving hashlist on MagicEden

### ISSUE THREAD

**Issue by lawncegoh** [metaplex-foundation/metaplex#1475]
How do we retrieve the hashlist of the minted from the candy machine, on this site:

https://magiceden.io/mintlist-tool, 

1. input of creator address -> returns nothing
2. input of candy machine address -> returns nothing

The site mentions that we should key in creator address for v2, but i see nothing, is there a way for us to retrieve it manually?

**Comment by stegaBOB** [comment]
This is an issue on Magic Eden's side. They will have to implement support for v2 if they haven't already for that tool to work. In the meantime, you can use Metaboss. https://metaboss.rs/snapshot.html#snapshot-holders
