### ISSUE TITLE
The bug with the lock button on mint

### ISSUE THREAD

**Issue by BORRODA8** [metaplex-foundation/metaplex#1479]
![Снимок экрана (56)](https://user-images.githubusercontent.com/93973414/148680315-d0dd1531-235d-4eb2-bd16-6d0ea4088905.png)
![Снимок экрана (57)](https://user-images.githubusercontent.com/93973414/148680316-71aa3e60-56ed-4436-acee-37b9f494ee5b.png)
![Снимок экрана (55)](https://user-images.githubusercontent.com/93973414/148680319-ee9438b0-d530-41e0-a28d-116f9e0b4f80.png)

**Comment by what-name** [comment]
Please paste here your CM config and .env file for the `candy-machine-ui`. It seems you did not add the CandyMachine publickey to your .env file. See https://docs.metaplex.com/candy-machine-v2/mint-frontend#setting-up

**Comment by BORRODA8** [comment]
![Снимок экрана (58)](https://user-images.githubusercontent.com/93973414/148681808-79981354-5c0c-4a85-9fad-37405c7c4baf.png)
![Снимок экрана (59)](https://user-images.githubusercontent.com/93973414/148681811-fb927509-1636-42a2-810a-84e188519af1.png)


> Please paste here your CM config and .env file for the `candy-machine-ui`. It seems you did not add the CandyMachine publickey to your .env file. See https://docs.metaplex.com/candy-machine-v2/mint-frontend#setting-up

**Comment by PixelInvaderz** [comment]
you have to name the file .env

**Comment by BORRODA8** [comment]
but it's name .env but .example is type of file

**Comment by tokyoanonymous** [comment]
He probably means that you need to rename .env.example to .env
However, I am running into same bug at the moment.

**Comment by BORRODA8** [comment]
thanks!!!

**Comment by gambitboxdev** [comment]
> thanks!!!

So what helped you to resolve this? I was wondering since I am getting same bug even if files are named correctly

**Comment by stegaBOB** [comment]
what is in your .env file and what is its name?

**Comment by gambitboxdev** [comment]
> what is in your .env file and what is its name?

https://github.com/metaplex-foundation/metaplex/issues/1490
https://github.com/metaplex-foundation/metaplex/issues/1490#issue-1097492942

**Comment by gambitboxdev** [comment]
> what is in your .env file and what is its name?

https://github.com/metaplex-foundation/metaplex/issues/1490#issue-1097492942
