### ISSUE TITLE
Metaplex Metrics request

### ISSUE THREAD

**Issue by nkumar23** [metaplex-foundation/metaplex#148]
We would like to capture the following metrics across all Metaplex storefronts: 

**Number of unique wallet addresses that have engaged with Metaplex** 

- Engaged = have made at least one transaction with a Metaplex program

**Number of unique wallet addresses that have:**
- minted NFTs
- Published auctions
- Bid on auctions

**Total # NFTs Minted**

**Total # of Marketplaces**

**Avg # of bidders per auction**

**Total # of listings**

- By type of auction/sale (e.g. limited edition, open edition, etc)

----

**Total $$/SOL spent on winning bids**

**Total $$/SOL spent on minting**

**Total ##/SOL spent on publishing auctions**

**Avg Sale price**

**Highest Sale price**

**Distribution of sale prices (histogram)**

Ideally we would like to be able to view these metrics in a dashboard that stays up-to-date, but for now, we are happy with a snapshot for any of these metrics.

**Comment by nkumar23** [comment]
@bartosz-lipinski @bhgames

**Comment by bhgames** [comment]
Almost all resolved with https://github.com/metaplex-foundation/metaplex/pull/185
