### ISSUE TITLE
Tokens listing

### ISSUE THREAD

**Issue by mlutsiv** [metaplex-foundation/metaplex#1481]
What is correct way to list tokens on marketplace? After they was minted or right after upload on arweave? But they will be visible on marketplace before minting or what? Can someone help me with this process. Like when to do it and how?
Also I saw some SOL projects using up to 4 marketplaces at the same time. How it works?

**Comment by samuelvanderwaal** [comment]
Please contact the specific marketplaces you are trying to list with, this isn't an issue with Metaplex tools specifically. In general though, you can only list NFTs that are already minted. Candy machine doesn't store NFTs, it stores NFT *data*, so until the NFTs are minted they don't exist and can't be listed on any marketplace.
