### ISSUE TITLE
Deploying on Vercel or Netlify results in a build with no pages

### ISSUE THREAD

**Issue by bigicoin** [metaplex-foundation/metaplex#1484]
**Describe the bug**
I tried deploying to either Vercel or Netlify, using the Vercel steps on https://github.com/metaplex-foundation/metaplex/blob/master/docs/deploy.md

I tried both a SSR build (`.js` root dir, `next build` then output dir `.next`) or SSG build (`.js` root dir, then `next build && next export` then output dir `out`).

In both cases, on both Vercel and Netlify, it results in a homepage of 404. There seems to be no routes-manifest json file to define routes?

**To Reproduce**
1. Use the Vercel deploy instructions on https://github.com/metaplex-foundation/metaplex/blob/master/docs/deploy.md -- including creating the `js/pages` directory, then deploy with those settings
2. Navigate browser to the deployed URL
3. See 404 screen

**Expected behavior**
Metaplex loads

**Screenshots**
SSR: With `next build` and serving `.next`, I get this:
![image](https://user-images.githubusercontent.com/5854176/148706795-6a8fe12e-f634-4ad4-8516-b061fd0c947c.png)

SSG: With `next build && next export` and serving `out`, I get this:
![image](https://user-images.githubusercontent.com/5854176/148706815-ebd49ee3-0338-40e2-9587-0aac793ddc4d.png)

**Desktop (please complete the following information):**
 - OS: Windows, but I build purely on Vercel and Netlify
 - Browser: Chrome for me, but not browser specific problem
 - Version: Win10 Chrome 97

**Additional context**

**Comment by bigicoin** [comment]
I managed to get it to deploy on Netlify and Vercel with another way of config and build steps but the ones that came with the readme here still don't work.

**Comment by bigicoin** [comment]
@m33lucky-benny Yeah, I deploy on Netlify, and the deploy config looks like this:
Base dir: `./js`
Build command: `npm run build && cd packages/web && npm run build && npm run export`
Publish dir: `./js/build/web`
And that's basically it. Set your `REACT_APP_STORE_OWNER_ADDRESS_ADDRESS` env var in `.env.production` and the Netlify build and deploy env variable.

**Comment by thatotherkid86** [comment]
what's the proper configuration for vercel? 

with the current readme.md... the store deploys but hangs and stays in the loading state...

is there something missing?

**Comment by metasal1** [comment]
![image](https://user-images.githubusercontent.com/54984459/166182976-13aca9d7-9fc5-404d-bc64-125d36227e47.png)
These are the settings that worked for me.
