### ISSUE TITLE
Candy Machine Site Mint locked (bug)

### ISSUE THREAD

**Issue by gambitboxdev** [metaplex-foundation/metaplex#1490]
Upload "compiled successfully!", but when I finally yarn start and deploy candy-machine-mint site the mint button is locked. 

![Screenshot 2022-01-10 150008](https://user-images.githubusercontent.com/97396369/148724139-8c7b1666-f11a-4d2f-b9fd-0b9aebaa3ef7.png)
![Screenshot 2022-01-10 145811](https://user-images.githubusercontent.com/97396369/148724145-0a7cac9a-96ec-42bf-802c-1962b568fe7d.png)

.env file seems fine too 

![Screenshot 2022-01-10 145623](https://user-images.githubusercontent.com/97396369/148724191-4275715a-43f8-4538-afbd-7d941da36c1f.png)

config.json file too

![Screenshot 2022-01-10 145905](https://user-images.githubusercontent.com/97396369/148724218-71eb72b7-1ab5-4027-9187-946c03b36ffa.png)

Some tips to fix this bug will be much appreciated.

**Comment by vibraslap3** [comment]
Also having this issue after following the docs meticulously

**Comment by masterfapper72** [comment]
Same problem here

**Comment by stegaBOB** [comment]
Are you on the latest version?

**Comment by gambitboxdev** [comment]
Yes
![Screenshot 2022-01-11 062852](https://user-images.githubusercontent.com/97396369/148842323-8b60089d-f65f-4940-ad5e-4b3815ebde41.png)

**Comment by stegaBOB** [comment]
I mean the latest version of Metaplex. Should have specified sorry.

**Comment by gambitboxdev** [comment]
Oh, yes. I did git clone https://github.com/metaplex-foundation/metaplex.git 
a day a go so that should be the latest version
![Screenshot 2022-01-11 084129](https://user-images.githubusercontent.com/97396369/148856643-210e66c7-bf48-46d7-8030-b390e7085b41.png)
sion

**Comment by samdhesi** [comment]
Has anyone found a resolution? I'm having the same issue with the mint button.

.env file is fine. Have set date in config to a date last year. No luck...

**Comment by johnwise9** [comment]
anyone got pass this please?

**Comment by Pcartau** [comment]
Its your env file. Just remove the `< >` from the line 1 `REACT_APP_CANDY_MACHINE_ID`

It should look like this: `REACT_APP_CANDY_MACHINE_ID=5UZfMcxHKK9beT92Lv2fJt8SETJ7KEsn37F9CAffffffff`

**Comment by gambitboxdev** [comment]
> Its your env file.
> 
> Just remove the `< >` from the line 1 `REACT_APP_CANDY_MACHINE_ID` It should look like this: `REACT_APP_CANDY_MACHINE_ID=5UZfMcxHKK9beT92Lv2fJt8SETJ7KEsn37F9CAffffffff`
> 
> Also have a look at: https://en.wikipedia.org/wiki/Environment_variable

Hi! Thank you so much! Your solution worked !
