### ISSUE TITLE
CM v2 hashlist

### ISSUE THREAD

**Issue by franraknic** [metaplex-foundation/metaplex#1491]
**Describe the bug**
Cannot get hashlist of a deployed CM v2

**To Reproduce**
1. create CM v2
2. get the ID and/or creator wallet pubkey
3. try services like https://magiceden.io/mintlist-tool & https://aiphotos.art/hash-table with both CM id and wallet creator

**Expected behavior**
Mint hashlist for secondary marketplaces. The services provided return 0 results, my CM is fully uploaded and the goLiveDate is in the past.

**Comment by samuelvanderwaal** [comment]
This is a common misconception. You can't get mints of NFTs that doesn't exist yet. Mint list tools only work on minted NFTs. Candy machines don't store NFTs, they store NFT *data* and mint them on-the-fly when the `mintNFT` handler is called.

**Comment by Dopepirate** [comment]
hey! how i include hashlist in a candy machine to be uploaded?

Thanks

**Comment by samuelvanderwaal** [comment]
> hey! how i include hashlist in a candy machine to be uploaded?
> 
> Thanks

You can't, that's not how it works, see my comment above.

**Comment by samuelvanderwaal** [comment]
More info here: https://docs.metaplex.com/mint-lists
