### ISSUE TITLE
Upload not successsful, "TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by jingxuan98** [metaplex-foundation/metaplex#1493]
**Describe the bug**
Having "TypeError: Cannot convert undefined or null to object" when uploading

**To Reproduce**
1. quite sure that my path are correct
2. My assets folder is same as metaplex and i named it as "metaplextest" here
3. running `ts-node ./metaplextest/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/mainnet.json -cp config.json -c example assets`

**Expected behavior**
Should be able to upload

**Screenshots**
![image](https://user-images.githubusercontent.com/43902263/148764942-395d8b61-3743-4439-9c69-b0d57dc7eb23.png)v

**Desktop (please complete the following information):**
VScode, WIn11

**Additional context**

**Comment by gambitboxdev** [comment]
I had that problem before, but then I revised how my folders were arranged/path as well as double checked json metadata then It worked for me when my folders were arranged like this... 
![Screenshot 2022-01-11 001211](https://user-images.githubusercontent.com/97396369/148789349-0c6a1d38-a779-4b12-aaa1-0ccbd8ca8b1f.png)
and my code was this ... 
ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp ./config.json -c example ./assets
^ when running from t file.

Also need to make sure your assets start with 0.json
and corresponding json file's metadata have same 0.json written. 
![Screenshot 2022-01-11 002038](https://user-images.githubusercontent.com/97396369/148790748-c217928e-a0ff-44c7-a094-50a692b129cc.png)

In addition, I am not sure if this effects anything but I had more than 1 SOL in the dev wallet that time and I ran yarn install in metaplex/js before.

Finally I double checked my config.json file.
![Screenshot 2022-01-11 003120](https://user-images.githubusercontent.com/97396369/148792545-4b4bdbf6-3767-45ef-8b07-ae48bd8f6d1e.png)
