### ISSUE TITLE
Error: Invalid config owner. Gumdrop candy creation

### ISSUE THREAD

**Issue by uohoo** [metaplex-foundation/metaplex#1496]
After following the documentation:
NFT Candy Machine Pre-sale
The workflow for a Candy Machine pre-sale through the Gumdrop program is as follows:
1. Create a Candy Machine with at least as many assets as are to be distributed through the Gumdrop. See instructions to create a Candy Machine here
2. Set the Candy Machine start date to after the pre-sale ends (i.e when the mint should be open to all participants) or leave it None (so only whitelisted participants may ever mint).
3. Create the Gumdrop with the whitelist.
-> In this step "Invalid config owner" is thrown using the CLI and the frontend https://lwus.github.io/metaplex/create.

CLI instruction used:
ts-node src/gumdrop-cli.ts create -k ~/.config/solana/devnet.json --claim-integration candy --candy-config 39Uaw6YtadW7s6jeJTm5WUmpyeYhqkvuN8oHYHDpfAoJ --candy-uuid 39Uaw6 --distribution-method wallets --distribution-list gumdrop.json

The --keypair is the address used to upload the candymachine and the config is what i get in .cache folder when uploading.

Is it possible setting a whitelist directly to a candymachine already created? What's the way to get it?

**Comment by phonemyatkhine** [comment]
Encountering the same issue.  Has anyone figured this out?

**Comment by vladgardus** [comment]
It reproduces for me too. If I figure it out on my own I'll text back.

**Comment by novaknole** [comment]
Hey 👋 

Have you found any news or workarounds ?

**Comment by happyclan** [comment]
Same issue too.

**Comment by vladgardus** [comment]
Is nobody going to pick this up?

**Comment by vladgardus** [comment]
I see that someone fixed it, but it requires approval: https://github.com/metaplex-foundation/metaplex/pull/1589

**Comment by adheeshdh** [comment]
Same issue, anyone has idea what is wrong here? Is there a workaround?

**Comment by ccornen** [comment]
Hello,
any news about this critical issue ?

**Comment by stegaBOB** [comment]
When we disabled candy machine v1, this also broke the Candy Machine option with gumdrop. We need to improve our documentation and make a better UI to allow using gumdrop with the whitelist mint option of Candy Machine v2. 

In the meantime, you can make a whitelist mint for Candy Machine v2 (guide to this in our docs) and then airdrop the whitelist token using Gumdrop.

**Comment by realsbd** [comment]
encountering the same issue
