### ISSUE TITLE
Create Candy Machine Bug

### ISSUE THREAD

**Issue by jpal3** [metaplex-foundation/metaplex#1498]
After running the create candy machine cli, I am greeted with this error message:

C:\solana mint\metaplex\js\packages\cli\src\candy-machine-cli.ts:777
    const config = new PublicKey(cacheContent.program.config);
                                              ^
TypeError: Cannot read properties of undefined (reading 'program')
    at Command.<anonymous> (C:\solana mint\metaplex\js\packages\cli\src\candy-machine-cli.ts:777:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome

**Comment by stegaBOB** [comment]
You are on an old version of Metaplex. Please clone the latest version and try again. A lot has changed, so it might be helpful to check out our docs too. Here's a link: https://docs.metaplex.com
