### ISSUE TITLE
CMv2 uploading .glb files

### ISSUE THREAD

**Issue by Phreak0101** [metaplex-foundation/metaplex#1506]
**Describe the bug**
Candy machine is skipping .glb files while uploading( unsupported file type error) using CM V2

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '\metaplex\js\packages\cli\src> '
2. Run 'ts-node candy-machine-v2-cli.ts upload -e devnet -k D:\lock\devnetwallet.json -c cmdevnet -cp C:\metaplex\cmsetup.json C:\metaplex\assets'
3. See an error

**Expected behaviour**
The upload should be fine because in Metaplex docs it's stated that CM supports .glb files

**Screenshots**
![image](https://user-images.githubusercontent.com/90719386/148880959-0c3f2606-99fa-4cab-9b89-31d4ed3d5a7e.png)

**Desktop :**
 - OS: [Windows 10]
 - Version [Enterprise 64-bit build 19041]

**Additional context**
Trying test upload on devnet with 2 files 
![image](https://user-images.githubusercontent.com/90719386/148881198-909a6d0b-0863-4f1f-8890-dd88e8dcb6a4.png)
Metadata example 0.json
here are the community tweaks i tried
![image](https://user-images.githubusercontent.com/90719386/148881407-9a6d7518-fad1-4b0b-aa87-20e59fcf1568.png)
![image](https://user-images.githubusercontent.com/90719386/148881458-1ba56c11-9d8e-4325-a5f9-5e49bab5f090.png)

**Comment by zion-earthyfrodo** [comment]
@stegaBOB Is there an easy way to support .glb files as well?
Thanks for your feedback ;)

**Comment by Phreak0101** [comment]
through ar loader by Caleb its on github

Dňa št 13. 1. 2022, 23:34 zion-earthyfrodo ***@***.***>
napísal(a):

**Comment by Phreak0101** [comment]
but its definitely not easy

Dňa št 13. 1. 2022, 23:35 Dušan Dulka ***@***.***>
napísal(a):

**Comment by zion-earthyfrodo** [comment]
@Phreak0101 The easy way would be to have everything in metaplex cmv2 cli.
I'm double checking with Metaplex team if we can create together a PR -> Of course you are welcome as well to help.

**Comment by Phreak0101** [comment]
add me on on discord Phreak0101#2844 i am in chat with dev of arloader

Dňa št 13. 1. 2022, 23:41 zion-earthyfrodo ***@***.***>
napísal(a):

**Comment by Phreak0101** [comment]
he know the exact steps to upload glb but its through that ar loader , cmv2
cli should be changed to upload in steps and then overwrite that json files
with files uploaded on arweave because

Dňa pi 14. 1. 2022, 0:13 Dušan Dulka ***@***.***>
napísal(a):
