### ISSUE TITLE
Gumdrop BUG

### ISSUE THREAD

**Issue by Fiverr-Coin-Hunter** [metaplex-foundation/metaplex#1507]
Can't Create Airdrop 
Error : Number can only safely store up to 53 bits

**Comment by Fiverr-Coin-Hunter** [comment]
![image (1)](https://user-images.githubusercontent.com/94591206/148883942-513a0002-f42a-412d-b2ef-b84580ac8bda.png)

**Comment by Fiverr-Coin-Hunter** [comment]
can't create airdrop token with 9 decimals

**Comment by lwus** [comment]
IIRC these were fixed a while ago. The web page for gumdrop creation is also not as updated due to limited dev bandwidth. Can you confirm which version of the code you're running?

Most recent code is on my fork at `gumdrop/cm-tokens`
