### ISSUE TITLE
Not received reward for sell

### ISSUE THREAD

**Issue by clicman** [metaplex-foundation/metaplex#1513]
**Describe the bug**
Hi there! I'm testing metaplex. Cloned github repo, starte it on localhost. Minted an NFT listed it on auction for 10 usdc. From another account bought it. NFT successfully transferred to buyer, but 10 usdc stuck on program address and didn't land on creator wallet. Please help.
**To Reproduce**
1. As store owner create and instant list NFT (master)
2. As antoher user buy it

**Expected behavior**
1. another user receives NFT - OK
2. Store owner receives crypto - NOT OK

**Additional context**
1. Store owner: HrhzPzaDeSd3uVUqiQdeifYc3K8Z6JYEoMzVemD87WNB
2. another user: 78bCVPFiB9z62rDTKDfWgh4YFJuF8rSj6VeFRBdNTdW
3. NFT: https://solanabeach.io/address/Bwap4YWYEjXLHbwTnMKBN2UVnjK1gQk5ynSHgMtMKqC6
4. Auction: Dn8YXsEeeKxiKHo4rMoTTbcYogFx71vsb1RTJRtCnv4a
5. Last tracked 10 usdc: DZi5b6ngMkJ4Mzdf3rRnpvYSTmzcqVshkFB6ew3MpSCW

**Comment by nguyenson-kait** [comment]
Same issue here. There is any solution?

**Comment by stetommy** [comment]
same for me :(

**Comment by stegaBOB** [comment]
Do you know if the storefront is not offering a redeem button? Are there ways to force that instruction to happen?

**Comment by genuine-developer** [comment]
Yes.
To force that instruction to happen, you should navigate to _specific auction page + /beeling_.
And then you can see settlement button.
