### ISSUE TITLE
SPL Fixed Price Secondary Auctions revert back to SOL during bidding and reclaim process

### ISSUE THREAD

**Issue by solx-ventures** [metaplex-foundation/metaplex#1514]
**Describe the bug**
SPL Fixed Price Auctions revert back to SOL during bidding and reclaim process

**To Reproduce**
1. Enable the following:
- https://github.com/metaplex-foundation/metaplex/pull/788
- https://github.com/metaplex-foundation/metaplex/commit/e9841d4bb121fbea784ff60c83ddd3bb1a26d220
2. Start Fixed Price SPL currency Secondary Auction
3. When you go to make a bid in SPL currency, it actually shows SOL due to bug. However, this is not just superficial UX issue, it actually asks the wallet for X amount of SOL.

**Expected behavior**
Bidding should be in correct SPL token currency, not in SOL for Secondary Auctions.

**Screenshots**

<img width="207" alt="Screen Shot 2022-01-11 at 7 35 20 pm" src="https://user-images.githubusercontent.com/78846616/148935725-47775411-731c-4f60-88d6-b4075eaac390.png">

<img width="210" alt="Screen Shot 2022-01-11 at 7 35 34 pm" src="https://user-images.githubusercontent.com/78846616/148935745-0362dab1-b4f2-4c84-8234-dd734b6d4f63.png">

**Desktop (please complete the following information):**
 - Browser Chrome ( Mac, PC & Mobile)

**Comment by solx-ventures** [comment]
@JuanRdBO

**Comment by raphaelpc** [comment]
@solx-ventures GM! Were you able to find a way to fix the issue?

**Comment by solx-ventures** [comment]
> @solx-ventures GM! Were you able to find a way to fix the issue?

Had to shelve our unsustainable metaplex fork and move to Magic Eden. There was a load of different bugs that our small dev team didn't have resourcing to fix.
