### ISSUE TITLE
price difference, only network price is displayed on the phantom approved tab

### ISSUE THREAD

**Issue by malikh36** [metaplex-foundation/metaplex#1517]
the price on the front button gets updated but when we click on the approve only the  network fee is displayed .

In my case the price is 0.9 sol , this price is displayed on the mint button but after clicking the button  the approve wallet tab only shows the network fee which is 0.001 sol ususally .

**Comment by Pengucci** [comment]
same issue right here

**Comment by Amokstakov** [comment]
Bump

**Comment by samuelvanderwaal** [comment]
Are you trying to mint with your treasury wallet?
