### ISSUE TITLE
Candy Machine V2 UI Phantom transaction doesn't reflect the price in the config

### ISSUE THREAD

**Issue by vladgardus** [metaplex-foundation/metaplex#1519]
**Describe the bug**
Hello, I've started the UI and wanted to mint an NFT, but when I do so the price in my phantom wallet popup doesn't match with the one in my config file. I've done some debugging and the candy machine object coming from the contract is fine, but the issue is with the transaction.

Here's a screen shot:
![image](https://user-images.githubusercontent.com/43858789/148984713-b780f1cc-b24c-40bf-baac-d3dfec997918.png)

Here's my config file:
{
  "price": 0.75,
  "number": 6000,
  "gatekeeper": null,
  "solTreasuryAccount": "-",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "2022-01-10T00:00:00.000Z",
  "endSettings": {
    "endSettingType": { "date": true },
    "value": "2022-01-14T00:00:00.000Z"
  },
  "whitelistMintSettings": {
    "mode": { "burnEveryTime": true },
    "discountPrice": 0.5,
    "presale": false,
    "mint": "-"
  },
  "hiddenSettings": null,
  "storage": "ipfs",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "awsS3Bucket": null,
  "noRetainAuthority": false,
  "noMutable": false,
  "batchSize": 6000
}

**Comment by malikh36** [comment]
same problem we are facing as well

**Comment by roederw** [comment]
Can you provide a devnet Candy Machine ID I can reproduce this issue with?

**Comment by vladgardus** [comment]
Here it is: 37jwRUCiVWve6HjpKtqJnbiRxwXjDwcKxRsXxS9gJ3R5

**Comment by yamijuan** [comment]
isn't that just the Minting fee? do you get the price amount deducted from your wallet plus that number after minting?

**Comment by vladgardus** [comment]
Yeah, that is just the minting fee, and the amount deducted from the wallet is exactly that, without the price per token that I set in the candy machine.

**Comment by vladgardus** [comment]
@roederw did you manage to figure it out?

**Comment by samuelvanderwaal** [comment]
Are you minting with your treasury wallet?

**Comment by vladgardus** [comment]
I'm minting with the same wallet that I created the candy machine with, yeah. I see that after changing wallets and trying to mint with a new one, it shows the correct amount. Is there a backdoor implemented to that the owner of the candy machine can mint for free?

**Comment by samuelvanderwaal** [comment]
> I'm minting with the same wallet that I created the candy machine with, yeah. I see that after changing wallets and trying to mint with a new one, it shows the correct amount. Is there a backdoor implemented to that the owner of the candy machine can mint for free?

The wallet that creates the candy machine is the treasury wallet by default (you can specify a different one). It's not a backdoor, it's just that if you mint from your treasury wallet the mint price goes from your treasury wallet. . .back to your treasury wallet, so the net SOL difference to your wallet is only the actual small tx fee. Phantom is only showing the net result.
