### ISSUE TITLE
Error: Transaction failed: Custom program error: 0x1c

### ISSUE THREAD

**Issue by PapaBearDoes** [metaplex-foundation/metaplex#1521]
**Describe the bug**
Normally a Custom Program Error: 0x1c is a lack of funds in the particular wallet.  However, this is not the case here.

The bid was 0.0088, on a 0.007 initial bid (initial bid had not been placed yet), with a tick size of 0.0018. Wallet contains just over 0.078 SOL (just over $11) which should be enough for the bid (just under $1) & the transaction fees, so lack of funds is not the issue here to my current knowledge.

I could be wrong.

Also tried with the requested initial bid of 0.007 as well with the same result.

**To Reproduce**
1. Create limited edition auction
2. Attempt to bid on said auction using a different wallet
3. See error

**Expected behavior**
Expected behavior is for the bid to be accepted and continue on about my day.

**Screenshots**
![image](https://user-images.githubusercontent.com/73200436/149037470-e40a3d1a-fd2b-4f65-bbda-2e38a265bd13.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: /shrug, current

**Comment by PapaBearDoes** [comment]
Can't prove it, but it might have been network congestion, because I waited 30 minutes and tried again and no issues after that.

**Comment by samuelvanderwaal** [comment]
> Can't prove it, but it might have been network congestion, because I waited 30 minutes and tried again and no issues after that.

This seems likely. Thanks for the follow-up.
