### ISSUE TITLE
Metaplex not deploying to GitHub 

### ISSUE THREAD

**Issue by ggvick** [metaplex-foundation/metaplex#1523]
**Describe the bug**
Everything builds but it keeps brining up an error

**To Reproduce**
1. run yarn, everything works with no problems
2. run yarn bootstrap, again, works with no problems
3. run yarn build, everything works perfectly
4. and finally run yarn deploy.

**Expected behavior**
It deploys to my GitHub and I can run it on GitHub pages.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: On a remote server running coder/code-server with nodes
 - Browser Brave

**Additional context**
I have logs of the terminal right before it stopped with an error

```
$ lerna run deploy:app
lerna notice cli v3.22.1
lerna info versioning independent
lerna success run No packages found with the lifecycle script 'deploy:app'
ENOENT: no such file or directory, stat '/home/container/projects/metaplex/js/docs'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JohnRosey** [comment]
Hi,
you can try this :

`cd js/packages/web`
`yarn deploy`
