### ISSUE TITLE
'MODULE_NOT_FOUND' Error

### ISSUE THREAD

**Issue by Rooseveltthedev** [metaplex-foundation/metaplex#1524]
Im having issues accessing help command for solana cli package (candymachine). I am referencing this video: https://www.youtube.com/watch?v=cqNEoPT_1nM and the issue comes up around 7:58. Ive also attached a screenshot of said error.

Command being ran to build candy machine:

npx ts-node C:\Users\User_Here\solana-mint\metaplex\js\packages\cli\src\candy-machine-v1-cli.ts -h

Things I have checked:

I have made sure im on the testnet

My solana and node version are up to date.

I have tried both the complete and relative file path

Picture of given error

![image](https://user-images.githubusercontent.com/35243275/149063516-68e0b4dc-0cf8-462e-8871-02423cbb3cc1.png)

I have attached a photo above and would love feedback on how to better setup questions to learn and be assisted.

**Comment by Logan-Dang** [comment]
Metaplex is no longer supporting Candy Machine v1. https://docs.metaplex.com/candy-machine-v2/introduction
