### ISSUE TITLE
errno -4058

### ISSUE THREAD

**Issue by mojorek** [metaplex-foundation/metaplex#1529]
Hi, i have a problem. i try generate art configurations and i have errno -4058.
i use this: npx ts-node C:\users\user\art-test\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts generate_art_configurations ./traits
Error: ENOENT: no such file or directory, scandir '.\\traits'
i using windows 10

**Comment by Royhachem** [comment]
yes I have the same issue :

npx ts-node C:\Users\pc\Desktop\solana-mint\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts  upload ./assets -e devnet -k ~/solana-mint/keypair.json --config-path ~/.config/solana/devnet-test.json

**Error: ENOENT: no such file or directory, open '~/.config/solana/devnet-test.json'**

**Comment by realisttt** [comment]
Have you guys found a fix?
