### ISSUE TITLE
Some errors in the console

### ISSUE THREAD

**Issue by exromany** [metaplex-foundation/metaplex#153]
Errors appear when browsing the site in the browser console.
For example:
`Each child in a list should have a unique "key" prop.` and some others

A properly configured eslint can help prevent the similar occurrences in the future #156

**Comment by bhgames** [comment]
Realistically our team is still too small to address this issue right now. I can leave it open, but it will remain open for awhile. We'd love to have a contribution if you're interested in helping here, but for now I'm more interested in keeping the issues list clean and concise.

**Comment by bhgames** [comment]
Reopening

**Comment by bhgames** [comment]
Reopening
