### ISSUE TITLE
I am doing withdrawal from candy machine upload file and its giving error like this please hlepto remove rent from there.

### ISSUE THREAD

**Issue by prashantcrypto** [metaplex-foundation/metaplex#1534]
PS F:\ALL-NF> npx ts-node metaplex\js\packages\cli\src\candy-machine-v2-cli.ts withdraw -k keypair.json -e mainnet-beta -c temp
wallet public key: Fo1saYrG6NEB4tT6fR57g2UvDNVZvxpsx3LDG9SL8vPQ
Total Number of Candy Machine Config Accounts to drain 0
0 SOL locked up in configs
WARNING: This command will drain ALL of the Candy Machine config accounts that are owned by your current KeyPair, this will break your Candy Machine if its still in use
Congratulations, 0 config accounts have been successfully drained.
Now you rich again, please consider supporting Open Source developers.

I am doing withdrawal from candy machine upload file and its giving error like this please hlepto remove rent from there.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Window 10
 - Browser :- Microsoft Edge

**Comment by Logan-Dang** [comment]
Confirm that you're using the correct keypair and cache name. Also, confirm that they were uploaded to mainnet-beta.

**Comment by pfeifemc** [comment]
Hi there, I'm also having this issue but I'm fairly certain that my keypair and cache name are correct. My cmd and response:

`ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts withdraw \`
    `-e mainnet-beta \`
    `-k ~/.config/solana/mainnet.json`

wallet public key: 3kNKaGWpizc7QJNx8qJz8TNceBgkWeE17q2bSB4Wp8rT
Total Number of Candy Machine Config Accounts to drain 8
1.2347736 SOL locked up in configs
WARNING: This command will drain ALL of the Candy Machine config accounts that are owned by your current KeyPair, this will break your Candy Machine if its still in use
Rejecting for timeout...
Timeout Error caught { timeout: true }
Withdraw has failed for config account HkpUw1dtDkBdDJDKpkRxS9p8hSBfvySUeoHAion4tSWz Error: Timed out awaiting confirmation on transaction
Rejecting for timeout...
Timeout Error caught { timeout: true }
Withdraw has failed for config account 49o4ST25uiUv46qsAUwcmV2bF9AQP343y9ttxooES4Mh Error: Timed out awaiting confirmation on transaction
Rejecting for timeout...
Timeout Error caught { timeout: true }
Withdraw has failed for config account 31VmN1BzzzhECP652pSHPQCqxcFoAD4tyVpWpmN8m9ZU Error: Timed out awaiting confirmation on transaction

Desktop (please complete the following information):

OS: Mac OS Big Sur

Browser: N/A (terminal)

**Comment by pfeifemc** [comment]
Update: after downloading a fresh build off the master branch and testing both `withdraw_all` and `withdraw <CMID>`, I'm still encountering the same issue. There is a notable amount of SOL detected, and a nonzero number of associated candy machines, but each and every one returns a timeout. I've also tested this with a custom RPC from GenesysGo. Hoping for some help on this, thanks!

**Comment by brokenfiles** [comment]
> Update: after downloading a fresh build off the master branch and testing both `withdraw_all` and `withdraw <CMID>`, I'm still encountering the same issue. There is a notable amount of SOL detected, and a nonzero number of associated candy machines, but each and every one returns a timeout. I've also tested this with a custom RPC from GenesysGo. Hoping for some help on this, thanks!

I have the same issue. Did you find out how to do it ?

**Comment by pfeifemc** [comment]
Unfortunately no! I'm wondering if it has anything to do with the fact that some of my candy machines were from v1.

**Comment by brokenfiles** [comment]
> Unfortunately no! I'm wondering if it has anything to do with the fact that some of my candy machines were from v1. 

My CMs are from v2 only and I got a timeout error too. I'll retry today and keep you in touch!

**Comment by stegaBOB** [comment]
For v1 youll need to use the v1 withdraw command. As for timeout errors, theres nothing we can do about those on our end. That just has to do with the network not behaving. You should try to do this with a custom rpc. You can provide one with `--rpc "rpc url"`

**Comment by avanti36** [comment]
Hello! Did you manage this timeout error???? I have tried using genesys rpc, nothing helps, used both with metaboss and metaplex((((

**Comment by avanti36** [comment]
> Hello! Did you manage this timeout error???? I have tried using genesys rpc, nothing helps, used both with metaboss and metaplex((((

Did you manage to fix it?

**Comment by pfeifemc** [comment]
I'm still unable to withdraw, same timeout error!

**Comment by brokenfiles** [comment]
> Hello! Did you manage this timeout error???? I have tried using genesys rpc, nothing helps, used both with metaboss and metaplex((((

Did not tried last week, I'll retry tomorrow with a custom RPC. I'll keep you informed.

**Comment by avanti36** [comment]
I have tried it with custom rpc genesys on metaboss and got this error RPC response error -32002: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.

**Comment by avanti36** [comment]
The problem with withdrawing the CM was that the keypair for CM had 0 balance and you just could not pay the transaction for withdrawing your CM. I have sent 0.02 on this keypair and it worked.

**Comment by katshark** [comment]
> El problema con el retiro del CM era que el par de claves para el CM tenía saldo 0 y simplemente no podía pagar la transacción para retirar su CM. Envié 0.02 en este par de llaves y funcionó.

Dude, that really helped. I solve the problem.
