### ISSUE TITLE
Module '"mime"' has no exported member 'getType'

### ISSUE THREAD

**Issue by philried24** [metaplex-foundation/metaplex#1537]
Hey,

if i want to run the Candy Machine CLI command i am getting an error that there is no gettype in mine:
Does anybody know how to fix this?

![image](https://user-images.githubusercontent.com/91902572/149331427-cc02d076-bc08-474d-be25-c100835494a4.png)

**Comment by Pcartau** [comment]
Please try `npm i ts-node@latest`

Maybe you have deprecated version of ts-node

**Comment by philried24** [comment]
thanks for your answer but this didnt solve the problem. I have the v10.4.0 of ts-node.

**Comment by alanhabib** [comment]
My solution: ditch the old metaplex and cloned a new one. You need to go to v2 and I think v1 version have many thing deprecated. Mime is an npm package

**Comment by tolgaand** [comment]
My solution; Install types/mime again
`npm install --save @types/mime`

**Comment by philried24** [comment]
thanks, it worked to do it all from scratch
