### ISSUE TITLE
metadata display ".png" extension in json with ts-node candy-machine-cli.ts create_generative_art 

### ISSUE THREAD

**Issue by rxrxrxrx** [metaplex-foundation/metaplex#1548]
Hello, 

When I use ts-node candy-machine-cli.ts create_generative_art  to generate art, 
I end up with 2 files, 

0.json
0.png

So everything is fine but in my 0.json , value are like : 

        {
            "trait_type": "Background",
            "value": "Yellow.png"
        },

So when I upload it into the candy machine attribute display "Background: Yellow.png" instead of "Background: Yellow" 
Any help for this ? I would like to generate without the extension, im not gonna modify each .json to make it works

**Comment by Pcartau** [comment]
If you use Visual Studio Code (https://code.visualstudio.com), you can replace all values at the same time.
Try `option` + `shift` + `h` (MacOS) or  and you can then find and replace.

Also you can run this shell script to replace all of your JSON (**launch it directly from your asset folder !**):
`sed -i '' 's/Yellow.png/Yellow/g' *.json`

**Comment by rxrxrxrx** [comment]
thanks @Pcartau !
I was thinkin about doing that we sed comand too but I would like to know why its like this I mean I watched a lot of video, I read a lot of doc but i didnt find any answer.

**Comment by rxrxrxrx** [comment]
I really dont get it, Am I alone with this issue ? 
Why "create_generative_art" put the extension on my attributs file ? 
I didnt find someone with the same issue and im just using the regular CMV2 command line ...

**Comment by zamkamec** [comment]
If you are wiling to generate your collection again do the same thing but add "-ta true" to the end of the command 
 
`-ta, --treat-attributes-as-file-names <string>  If your attributes are filenames, trim the .png off if set to true`

**Comment by stegaBOB** [comment]
the generative art stuff has been removed from our repo. Please try using hashlips instead if you are still running into issues with the old code.

**Comment by rxrxrxrx** [comment]
@stegaBOB Oh that's sad why did you delete the generate-art command ? was a nice feature
