### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by exromany** [metaplex-foundation/metaplex#155]
some type declarations and code (utils) are duplicated between `packages/common/src/utils` and `packages/web/src/utils`

I suggest to resolve duplications, move common parts to `common` package and set up tools to check copy-paste/duplication (via `eslint` or some other)

**Comment by bhgames** [comment]
Not really a github issue. Happy to accept a PR, but this is not a pressing issue.

**Comment by bhgames** [comment]
Reopening

**Comment by jordansexton** [comment]
Closing as stale.
