### ISSUE TITLE
Prevents uploading of assets by asking for a -cp flag despite being filled.

### ISSUE THREAD

**Issue by jeremytinkers** [metaplex-foundation/metaplex#1553]
**Describe the bug**
It requires -cp being filled despite it being filled already as can be seen below.
![image](https://user-images.githubusercontent.com/63252520/149558142-263334ed-75c2-4c25-8459-ebe2492acec6.png)

**To Reproduce**
https://openquest.xyz/quest/create_candy_machine_for_minting_nft -> Until Step 8.

And for uploading, i used the command given in the docs:-
![image](https://user-images.githubusercontent.com/63252520/149558700-d4a24ae2-a255-4b3a-a24b-8dbe84f05d21.png)

**Desktop**
Windows 10

**Comment by zparnold** [comment]
Hi @jeremytinkers It looks like in the screenshot you sent, you passed `--cp` as opposed to `-cp` which the docs specify. Can you try again after removing the extra `-` and let me know if that works for you?

**Comment by zparnold** [comment]
@austbot ☝️ please correct me if I'm wrong

**Comment by jeremytinkers** [comment]
Hey @zparnold , i tried both but unfortunately this backfires as well. I get the same error.

**Comment by aliboy-lala** [comment]
You have to create config.json file with at least minimal configuration as in follow link
[https://docs.metaplex.com/candy-machine-v2/configuration](url)

**Comment by jeremytinkers** [comment]
Hey @aliboy-lala , ahh makes sense. The tutorial I was following overlooked this.  Thanks for getting back!

**Comment by timadewale1** [comment]
hello @jeremytinkers, i just want to ask how you did the set up for your minimal configuration right from the storage part to the end. I would really appreciate it if you can help
