### ISSUE TITLE
Reveal after using hiddenSettings

### ISSUE THREAD

**Issue by tserevE8848** [metaplex-foundation/metaplex#1558]
Hey guys, do you know in V2 if there is an automatic way of configuring the reveal date when using hiddenSettings? Or there is alternative. thanks

**Comment by Looktazz** [comment]
I'm following for the same reason !

**Comment by febo** [comment]
You can configure "end settings" to stop the mint at a specific amount/date, after that you will need to run your reveal process to update the metadata of the mints.
