### ISSUE TITLE
Property 'fieldKey' does not exist on type 'FormListFieldData'

### ISSUE THREAD

**Issue by jmorettoni** [metaplex-foundation/metaplex#1560]
I faced this error after update metaplex repo on my project. 

./src/views/artCreate/index.tsx:738:45
Type error: Property 'fieldKey' does not exist on type 'FormListFieldData'

**Comment by khoiuit99** [comment]
Same, how to fix it?

**Comment by yusefnapora** [comment]
It looks like `fieldKey` was removed in [this PR](https://github.com/ant-design/ant-design/pull/32689) and released in [4.18.0](https://ant.design/changelog#4.18.0).  

Metaplex is using `antd@^4.16.12`, which was resolved to `4.17.3` in the  `yarn.lock` that's currently checked into `master`. But if you have to regenerate the lockfile today, you'll get `4.18.4`, which doesn't have `fieldKey` any longer.
