### ISSUE TITLE
Module '"mime"' has no exported member 'getType'

### ISSUE THREAD

**Issue by cormacncheese** [metaplex-foundation/metaplex#1562]
Pull latest commit and get the following type error with mime package:

Module '"mime"' has no exported member 'getType'
Module '"mime"' has no exported member 'getExtension'

**Comment by davidmitesh** [comment]
I followed this : https://docs.metaplex.com/candy-machine-v2/getting-started and got the error. 

If you are on the same page then, navigate to the js folder under metaplex directory. And run " yarn add  @types/mime --ignore-workspace-root-check  " .  See, if that works.

**Comment by cormacncheese** [comment]
Yep, worked like charm!
