### ISSUE TITLE
code: 'MODULE_NOT_FOUND',  issue

### ISSUE THREAD

**Issue by tomtom1233** [metaplex-foundation/metaplex#1565]
When I am trying the upload command for metaplex I get this error and I do not know what is causing it. 
This error happens to me on candy machine V1 and V2. I am relly new to this so thanks in advance if anyone of you can help!

![image](https://user-images.githubusercontent.com/93504460/149647494-f7d228e2-7ed6-4379-b934-779da27ecbc6.png)

**Comment by davidmitesh** [comment]
This error is caused due to incorrect path. Go to the metaplex/js/packages/cli/src/ folder and try to run the candy-machine-v1-cli.ts script.

**Comment by tomtom1233** [comment]
Thanks for your response. I have tried running candy-machine-v1-cli.ts script with tsc command and I now get this error.
![image](https://user-images.githubusercontent.com/93504460/149665580-89e3cd49-c6fa-4ade-88d6-3ca54b5d3967.png)

**Comment by davidmitesh** [comment]
Try to run using ts-node instead of tsc. If you dont have the module, try installing it globally and then run it using ts-node.https://www.npmjs.com/package/ts-node

**Comment by tomtom1233** [comment]
I have tried using ts-node and it instead gives me this error. And what do you mean by installing the module globally?

![image](https://user-images.githubusercontent.com/93504460/149667059-952809c0-934f-465b-8f8b-5c554e3d0b62.png)

**Comment by davidmitesh** [comment]
By globally I mean : 
npm install -g typescript
npm install -g ts-node

have you already set-up solana on your machine?

**Comment by tomtom1233** [comment]
Solana is set up and I have already installed ts-node and typescript. Do you have any other solution? I appreciate your help.

**Comment by davidmitesh** [comment]
I think there is something specific we should do on the windows machine for this setup.As I am on mac, I can't help you.

**Comment by 333fLOW** [comment]
> When I am trying the upload command for metaplex I get this error and I do not know what is causing it. This error happens to me on candy machine V1 and V2. I am relly new to this so thanks in advance if anyone of you can help!
> 
> ![image](https://user-images.githubusercontent.com/93504460/149647494-f7d228e2-7ed6-4379-b934-779da27ecbc6.png)

https://github.com/metaplex-foundation/metaplex/issues/1566#issuecomment-1016094287
