### ISSUE TITLE
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by ringockmg** [metaplex-foundation/metaplex#1566]
I was running the following command:
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k config/solana/devnet.json \ -cp config.json \  ./assets

And I received the following errors:
beginning the upload for 10 (img+json) pairs
started at: 1642317937237
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\commands\upload.ts:97:24)
    at Command.<anonymous> (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by lucachapelle** [comment]
I have the same eror 
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (G:\dev\sol\mint_clean\~\metaplex\js\packages\cli\src\commands\upload.ts:97:24)
    at Command.<anonymous> (G:\dev\sol\mint_clean\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'



with this command :
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~\metaplex\js\packages\cli\example-candy-machine-upload-config.json \ G:\dev\sol\mint_clean\example-assets

**Comment by 333fLOW** [comment]
> I was running the following command: ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k config/solana/devnet.json \ -cp config.json \ ./assets
> 
> And I received the following errors: beginning the upload for 10 (img+json) pairs started at: 1642317937237 upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (node:internal/errors:371:5) at validateString (node:internal/validators:119:11) at Object.dirname (node:path:654:5) at uploadV2 (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\commands\upload.ts:97:24) at Command. (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'ERR_INVALID_ARG_TYPE' }



> **I have the same eror** upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (node:internal/errors:371:5) at validateString (node:internal/validators:119:11) at Object.dirname (node:path:654:5) at uploadV2 (G:\dev\sol\mint_clean~\metaplex\js\packages\cli\src\commands\upload.ts:97:24) at Command. (G:\dev\sol\mint_clean~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'ERR_INVALID_ARG_TYPE'
> 
> **with this command :** ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~\metaplex\js\packages\cli\example-candy-machine-upload-config.json \ G:\dev\sol\mint_clean\example-assets

Hey, try to open cmd in this directory : 
![image](https://user-images.githubusercontent.com/97945623/150068711-fae436be-e786-463e-8075-382f722dad76.png)

and enter this command: ts-node src/candy-machine-v2-cli.ts upload -e devnet -k YOUR FULL KEYPAIR LOCALTION -cp config.json -c example ./assets

![image](https://user-images.githubusercontent.com/97945623/150068908-4ac2bf5b-136a-43e3-a2af-84ee297beac6.png)

**Comment by 333fLOW** [comment]
> I was running the following command: ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k config/solana/devnet.json \ -cp config.json \ ./assets
> 
> And I received the following errors: beginning the upload for 10 (img+json) pairs started at: 1642317937237 upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (node:internal/errors:371:5) at validateString (node:internal/validators:119:11) at Object.dirname (node:path:654:5) at uploadV2 (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\commands\upload.ts:97:24) at Command. (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'ERR_INVALID_ARG_TYPE' }

https://github.com/metaplex-foundation/metaplex/issues/1566#issuecomment-1016094287

**Comment by akatzuka** [comment]
I've had the same error, running the following command from the cli directory:
ts-node src/candy-machine-v2-cli.ts upload \ -e devnet \ -k "H:/CM.json" \ -cp config.json \ -c example \ ./assets


I have created a Config.json file (which is in the cli directory), and the pubkey of the wallet is displayed so not sure what is causing the issue
![image](https://user-images.githubusercontent.com/24398401/150069369-68cc39c5-f7b9-48ab-ba79-578c32783cbf.png)

**Comment by 333fLOW** [comment]
> I've had the same error, running the following command from the cli directory: ts-node src/candy-machine-v2-cli.ts upload \ -e devnet \ -k "H:/CM.json" \ -cp config.json \ -c example \ ./assets
> 
> I have created a Config.json file (which is in the cli directory), have tried moving the keypair to the same directory (though given the pubkey of the wallet is displayed, I'm not sure if that is the issue) ![image](https://user-images.githubusercontent.com/24398401/150069369-68cc39c5-f7b9-48ab-ba79-578c32783cbf.png)

Have you tried to move your keypair to the js folder in metaplex?

**Comment by akatzuka** [comment]
Yeah I've tried moving the keypair into the JS folder, no difference. Same with and without quotes.

`ts-node src/candy-machine-v2-cli.ts upload \ -e devnet \ -k CM.json \ -cp config.json \ -c example \ ./assets`

**Comment by TheMarketfoxx** [comment]
im stuck here too

**Comment by TheMarketfoxx** [comment]
WARNING: Skipping unsupported file type \$Recycle.Bin
WARNING: Skipping unsupported file type \$WinREAgent
WARNING: Skipping unsupported file type \AMD
WARNING: Skipping unsupported file type \Config.Msi
WARNING: Skipping unsupported file type \Documents and Settings
WARNING: Skipping unsupported file type \DumpStack.log.tmp
WARNING: Skipping unsupported file type \hiberfil.sys
WARNING: Skipping unsupported file type \minerstat-windows
WARNING: Skipping unsupported file type \my-solana-wallet
WARNING: Skipping unsupported file type \NiceHash
WARNING: Skipping unsupported file type \OneDriveTemp
WARNING: Skipping unsupported file type \pagefile.sys
WARNING: Skipping unsupported file type \PerfLogs
WARNING: Skipping unsupported file type \PowerSpec
WARNING: Skipping unsupported file type \Program Files
WARNING: Skipping unsupported file type \Program Files (x86)
WARNING: Skipping unsupported file type \ProgramData
WARNING: Skipping unsupported file type \recovery
WARNING: Skipping unsupported file type \Riot Games
WARNING: Skipping unsupported file type \solana-install-tmp
WARNING: Skipping unsupported file type \swapfile.sys
WARNING: Skipping unsupported file type \System Volume Information
WARNING: Skipping unsupported file type \Users
WARNING: Skipping unsupported file type \Windows
Beginning the upload for 5 (img+json) pairs
started at: 1643603138119
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined      
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\Valentine\desktop\my_mint_site\metaplex\js\packages\cli\src\commands\upload.ts:100:24)
    at Command.<anonymous> (C:\Users\Valentine\desktop\my_mint_site\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:190:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'


i need help with this too.

**Comment by SiawaschAmootari** [comment]
i have the same issue

**Comment by Chetan-B-B** [comment]
> > I was running the following command: ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k config/solana/devnet.json \ -cp config.json \ ./assets
> > And I received the following errors: beginning the upload for 10 (img+json) pairs started at: 1642317937237 upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (node:internal/errors:371:5) at validateString (node:internal/validators:119:11) at Object.dirname (node:path:654:5) at uploadV2 (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\commands\upload.ts:97:24) at Command. (C:\Users\RignoK\Documents\code\nft\sol\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'ERR_INVALID_ARG_TYPE' }
> 
> > **I have the same eror** upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (node:internal/errors:371:5) at validateString (node:internal/validators:119:11) at Object.dirname (node:path:654:5) at uploadV2 (G:\dev\sol\mint_clean~\metaplex\js\packages\cli\src\commands\upload.ts:97:24) at Command. (G:\dev\sol\mint_clean~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'ERR_INVALID_ARG_TYPE'
> > **with this command :** ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~\metaplex\js\packages\cli\example-candy-machine-upload-config.json \ G:\dev\sol\mint_clean\example-assets
> 
> Hey, try to open cmd in this directory : ![image](https://user-images.githubusercontent.com/97945623/150068711-fae436be-e786-463e-8075-382f722dad76.png)
> 
> and enter this command: ts-node src/candy-machine-v2-cli.ts upload -e devnet -k YOUR FULL KEYPAIR LOCALTION -cp config.json -c example ./assets
> 
> ![image](https://user-images.githubusercontent.com/97945623/150068908-4ac2bf5b-136a-43e3-a2af-84ee297beac6.png)

This worked for me :)

**Comment by larbito** [comment]
guys, please help I need to fix this problem ASAP , ib tried everything but no result.

C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli>ts-node C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload \ -e devnet \ -k C:\Users\Larbi\.config\solana\devnet10.json \ -cp C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\config.json \ -c example \ C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\assets
wallet public key: Fmyu1UixtFbZ5MiKfqvK8FQzw8cbFMdW6BtsXoxnQFNK
(node:11088) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type \$Recycle.Bin
WARNING: Skipping unsupported file type \$WinREAgent
WARNING: Skipping unsupported file type \AITEMP
WARNING: Skipping unsupported file type \Documents and Settings
WARNING: Skipping unsupported file type \Drivers
WARNING: Skipping unsupported file type \DumpStack.log.tmp
WARNING: Skipping unsupported file type \hiberfil.sys
WARNING: Skipping unsupported file type \Intel
WARNING: Skipping unsupported file type \pagefile.sys
WARNING: Skipping unsupported file type \PerfLogs
WARNING: Skipping unsupported file type \Program Files
WARNING: Skipping unsupported file type \Program Files (x86)
WARNING: Skipping unsupported file type \ProgramData
WARNING: Skipping unsupported file type \Python310
WARNING: Skipping unsupported file type \Recovery
WARNING: Skipping unsupported file type \solana-install-tmp
WARNING: Skipping unsupported file type \swapfile.sys
WARNING: Skipping unsupported file type \System Volume Information
WARNING: Skipping unsupported file type \Users
WARNING: Skipping unsupported file type \Windows
Beginning the upload for 3 (img+json) pairs
started at: 1646734199763
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\commands\upload.ts:110:24)
    at Command.<anonymous> (C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:263:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
