### ISSUE TITLE
Error when trying to `mint_one_token` on testnet

### ISSUE THREAD

**Issue by jackkkonggg** [metaplex-foundation/metaplex#1567]
**Describe the bug**
`{ InstructionError: [ 4, { BorshIoError: 'Unknown' } ] }` when trying to `mint_one_token` on testnet.

**To Reproduce**
1. `solana config set --url https://api.testnet.solana.com`
2. `generate_art_configurations`
3. `create_generative_art`
4. `upload`
5. `mint_one_token`

**Expected behavior**
Should successfully mint one token.

**Screenshots**
```
REST error for 23hL5M75HRTGjhoyAmXLYZZFNuek8eauZjYR1EZCqDqS2Fng6YCttTppMSg1T7hBXXi1EdnsLijjsCqSZPKXLrVm {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: { InstructionError: [ 4, [Object] ] },
  slot: 113268639,
  status: { Err: { InstructionError: [Array] } }
}
Timeout Error caught { InstructionError: [ 4, { BorshIoError: 'Unknown' } ] }
(node:8796) UnhandledPromiseRejectionWarning: Error: Transaction failed: Error: BorshIoError
    at sendSignedTransaction //metaplex/js/packages/cli/src/helpers/transactions.ts:136:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendTransactionWithRetryWithKeypair (/metaplex/js/packages/cli/src/helpers/transactions.ts:59:26)
    at async mintV2 (/metaplex/js/packages/cli/src/commands/mint.ts:344:5)
    at async Command.<anonymous> (/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:716:16)
```
**Additional context**
Minting is successful on devnet.
Error on Solana Explorer: https://explorer.solana.com/tx/23hL5M75HRTGjhoyAmXLYZZFNuek8eauZjYR1EZCqDqS2Fng6YCttTppMSg1T7hBXXi1EdnsLijjsCqSZPKXLrVm?cluster=testnet

**Comment by UwebDevCom** [comment]
also dealing with the same problem

**Comment by stegaBOB** [comment]
There is no reason to be using Testnet. That is mainly for testing new versions of Solana. We don't have any recent candy machines (if any?) deployed on Testnet. Please use Devnet for testing and Mainnet Beta for production.

**Comment by jackkkonggg** [comment]
I see, thanks!

**Comment by shawnkd** [comment]
getting this error on devnet :(
