### ISSUE TITLE
Large code files

### ISSUE THREAD

**Issue by exromany** [metaplex-foundation/metaplex#157]
Some files are too large. Difficult to read and maintain

- [ ] `packages/web/src/views/auctionCreate/index.tsx` - 1906 lines
- [ ] `packages/common/src/actions/metadata.ts` - 1195 lines
- [ ] `packages/web/src/views/artCreate/index.tsx` - 1115 lines
- [ ] `packages/common/src/actions/auction.ts` - 1056 lines
- [ ] `packages/web/src/actions/sendRedeemBid.ts` - 1048 lines
- [ ] `packages/web/src/models/metaplex/index.ts` - 930 lines
- [ ] `packages/web/src/contexts/meta.tsx` - 841 lines
- [ ] `packages/common/src/actions/vault.ts` - 753 lines
- [ ] `packages/web/src/actions/createAuctionManager.ts` - 740 lines
- [ ] `packages/web/src/components/AuctionCard/index.tsx` - 703 lines
- [ ] `packages/common/src/contexts/connection.tsx` - 691 lines
- [ ] `packages/common/src/contexts/accounts.tsx` - 659 lines
- [ ] `packages/web/src/views/auction/billing.tsx` - 541 lines
- [ ] `packages/web/src/actions/claimUnusedPrizes.ts` - 501 lines
- [ ] `packages/web/src/components/Notifications/index.tsx` - 499 lines
- [ ] `packages/web/src/hooks/useAuctions.ts` - 432 lines
- [ ] `packages/web/src/views/auction/index.tsx` - 427 lines

**Comment by bhgames** [comment]
This is not a github issue. Happy to accept a PR.

**Comment by bhgames** [comment]
Ok, reopening. Apparently @bartosz-lipinski considers this, and all your other issues, to be priorities.

**Comment by jordansexton** [comment]
Closing as stale. While this would be nice to have, it's also a lot of work to refactor these files. PRs are welcome though!
