### ISSUE TITLE
mint_one_token error on TESTNET

### ISSUE THREAD

**Issue by anand-bitra** [metaplex-foundation/metaplex#1570]
Describe the bug

Timeout Error caught {
  err: { InstructionError: [ 4, [Object] ] },
  slot: 108254465,
  confirmations: 0
}

To Reproduce

solana config set --url https://api.testnet.solana.com
generate_art_configurations
create_generative_art
upload
mint_one_token
Expected behavior
Should successfully mint one token.

Screenshots

REST null result for 3VfRxHtuBq1YPwUEfkn6tjsNEtF2smfdEvtqbQdFkwC8gNdVcq1GZGHyo3WpePAk6JevoVycQ65vHtUBRSdpyEkD null
Rejected via websocket { InstructionError: [ 4, { Custom: 6019 } ] }
Timeout Error caught {
  err: { InstructionError: [ 4, [Object] ] },
  slot: 108254465,
  confirmations: 0
}
C\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x1783
    at sendSignedTransaction (C:\Users\nbitra\Downloads\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (C:\Users\nbitra\Downloads\metaplex-master\js\packages\cli\src\helpers\transactions.ts:59:26)
    at async mintV2 (C:\Users\nbitra\Downloads\metaplex-master\js\packages\cli\src\commands\mint.ts:344:5)
    at async Command.<anonymous> (C:\Users\nbitra\Downloads\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:714:16)

Additional context
C:\metaplex-master> ts-node js/packages/cli/src/candy-machine-v2-cli.ts mint_one_token -l debug -e devnet -k C:\Users\nbitra\.config\solana\devnet.json

**Comment by HaoCherHong** [comment]
6019 leads to GatewayTokenMissing Error
did you set the `gatekeeper` variable in your configuration file?

**Comment by anand-bitra** [comment]
Yes. I did set the gatekeeper variable in configuration file.
Thanks,Anand
    On Monday, January 17, 2022, 05:49:38 AM EST, Hao-Cher Hong ***@***.***> wrote:  
 
 


6019 leads to GatewayTokenMissing Error
did you set the gatekeeper variable in your configuration file?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoCherHong** [comment]
According to the [docs](https://docs.metaplex.com/candy-machine-v2/configuration#captcha-settings)
You won't be able to mint token from cli after you set the gatekeeper variable.

**Comment by stegaBOB** [comment]
You have to use devnet or mainnet-beta to use our programs. Testnet is for testing new versions of Solana, and a version of candy machine has not been deployed on that cluster.
