### ISSUE TITLE
Upload command issue

### ISSUE THREAD

**Issue by tomtom1233** [metaplex-foundation/metaplex#1578]
When I run the upload command:

 ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
    ./assets

a huge error pops up. it basically says in french that every option starting with an (-) in front of it is not recpgnise as a command.
Anyone know how to fix this issue?
![image](https://user-images.githubusercontent.com/93504460/149844889-a8f4b4e3-5fd7-4325-aa27-e38563d23d72.png)

**Comment by scxr** [comment]
put it all onto one line, like so:
`ts-node .\packages\cli\src\candy-machine-v2-cli.ts upload -e devnet -k .\wallets\seller.json -cp .\config.json ./MyAssets -c test`

**Comment by tomtom1233** [comment]
I have used this command to try and make it work:
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp config.json -c example-assets

But now it tells me: missing required argument 'directory'
![image](https://user-images.githubusercontent.com/93504460/149998143-2a28da38-85a7-4a00-9193-937f06267215.png)

Do you see anything wrong with my command ?

**Comment by scxr** [comment]
you arent giving it any assets to upload

**Comment by tomtom1233** [comment]
What do you mean by i'm not giving it any assets to upload? How would you make it work in this case.
Sorry if i'm annoying I am a total noob to this and you seem to know your stuff.

**Comment by 21e8** [comment]
you need to give it a path. after `upload` must be a path with all the assets and then some more parameters like your key ect....

`ts-node cli upload ~/nft-test/mini_drop --keypair ~/.config/solana/id.json`
