### ISSUE TITLE
Minting fails (0x177b)

### ISSUE THREAD

**Issue by scxr** [metaplex-foundation/metaplex#1579]
**Describe the bug**
My mint site has been working perfectly fine on devnet for a few days however i was testing out minting on mobile (it didnt work) i went to go try on my pc and it also didnt work. The error code is: 0x177b
See an example transaction here: https://solscan.io/tx/4jX68QQkx25J3bPmNiSFTkiFZaxhoCneedyWyLyC81gJuFTikZBRyS11viQvvYe5Ldj68zpz6fEALBCbk8hddUAF?cluster=devnet

**To Reproduce**
1. Use the candy-machine-ui template with a working config
2. Connect to the website 
3. Attempt to mint

**Expected behavior**
I expect it to function as it has been and send an nft to my wallet

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 97.0.4692.71 (Official Build) (64-bit) (cohort: Stable)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 13.5.1
 - Browser Solflare in app
 - Version i do not know

**Additional context**
NA

**Comment by stanleycyang** [comment]
any updates on this?

**Comment by jahanner** [comment]
Hey mate, I've been dealing with that error this morning too (pretty new to Solana/Metaplex/Candy Machine). I ended up getting it to work and I believe the error code refers to your `goLiveDate` inside `config.json`. I initially had it as `"16 Feb 2022 00:00:00 GMT"` but for some reason it wasn't working. I changed it to `"15 Feb 2022 00:00:00 GMT"` and reran `ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts update_candy_machine -e devnet -k ~/.config/solana/devnet.json -cp config.json` and it worked

**Comment by stanleycyang** [comment]
@jahanner thanks for following up. But why would changing it from a 16 to a 15 fix the issue?

**Comment by stanleycyang** [comment]
Ah it all makes sense now: https://hackmd.io/@halaprix/S1W4vc9CY#Error-list

**Comment by jahanner** [comment]
@stanleycyang Actually I realized that changing to "15 Feb 2022 00:00:00 **GMT-0600**" would also have fixed it, I guess it was just a datetime format issue

**Comment by scxr** [comment]
in my case i had accidentally left end settings in after testing it, triple check your config file ;)
