### ISSUE TITLE
Add Continuous integration

### ISSUE THREAD

**Issue by deanrad** [metaplex-foundation/metaplex#1581]
For verifying that the project continues to remain installable, and functioning, a CI process - is essential. I usually don't trust an OSS repo without a CI process (but this one seems the only game in town for Solana anyway)

It occurs to me, after a week of being unable to install dependencies, that a CI setup - with Appveyor for Windows, and Jenkins for various versions of node, would allow maintainers to not be pestered by user errors related to deps not installing/setup, as well as provide early notice if one of the deps became unavailable.

I think the project is far enough along to warrant better testing/CI practices- let me know if I've missed anything or what help or guidance you may need.

**Comment by 21e8** [comment]
thank you. I am also voting for very basic tests as right now the `cli-nft.ts` is broken
