### ISSUE TITLE
Mint button locked!!

### ISSUE THREAD

**Issue by 333fLOW** [metaplex-foundation/metaplex#1588]
The mint button is locked for me, did everything in the docs
![image](https://user-images.githubusercontent.com/97945623/150005186-e22fb370-99dd-4e28-a34d-ee7caee0e895.png)

**Comment by okaydev23** [comment]
Make sure you have the .env file properly configured with an active Candy Machines ID

**Comment by gambitboxdev** [comment]
https://github.com/metaplex-foundation/metaplex/issues/1490#issuecomment-1012161661

**Comment by 333fLOW** [comment]
> Make sure you have the .env file properly configured with an active Candy Machines ID

I do, I've checked thread #1490 (comment)(https://github.com/metaplex-foundation/metaplex/issues/1490#issuecomment-1012161661) too, but the fixes dint help. 

here is my .env file with my .cache file:
![image](https://user-images.githubusercontent.com/97945623/150066780-598eb295-6dda-41d4-9876-6fc6fe060b1c.png)
![image](https://user-images.githubusercontent.com/97945623/150066919-617af169-50fc-4a09-bdea-66465c06f960.png)

**Comment by Artistic-alpha** [comment]
do you have gate keeper enabled? i had the same issue because of it

**Comment by gambitboxdev** [comment]
> > Make sure you have the .env file properly configured with an active Candy Machines ID
> 
> I do, I've checked thread #1490 (comment)([#1490 (comment)](https://github.com/metaplex-foundation/metaplex/issues/1490#issuecomment-1012161661)) too, but the fixes dint help.
> 
> here is my .env file with my .cache file: ![image](https://user-images.githubusercontent.com/97945623/150066780-598eb295-6dda-41d4-9876-6fc6fe060b1c.png) ![image](https://user-images.githubusercontent.com/97945623/150066919-617af169-50fc-4a09-bdea-66465c06f960.png)

You did not have a space after REACT_ACT_CANDY MACHINE_ID= 
so it should be REACT_ACT_CANDY MACHINE_ID= Bu...

**Comment by aditya000099** [comment]
@Artistic-alpha i also have the same problem and no gatekeeper is enabled

**Comment by macolen** [comment]
I was experiencing the same error here when using the config.json example file from the documentation. 

To fix this, I've updated my config.json with an **Start and End Date** and with the **captcha** code too. Now it shows my number os NFTs available to mint, the cost and the button works. 

But a weirder thing is happening after. The NFT that I've minted is showing as a regular Token on my Phantom Wallet. It's not on the collectibles tab. 

This is the transaction: [Link](https://solscan.io/tx/3DLo47tquL5M2stBsXyHKnbwsyW89CMYAVumKL4F3wA4pULo3yr27c83JqGaUJASvEeZpe9Z5ULNGHMuFtDv9h87?cluster=devnet)

<img width="358" alt="Captura de Tela 2022-01-19 às 20 11 45" src="https://user-images.githubusercontent.com/98062847/150233544-3bc33c54-52c1-41d1-9b3f-12277d9ce93b.png">


<img width="358" alt="Captura de Tela 2022-01-19 às 20 15 20" src="https://user-images.githubusercontent.com/98062847/150233574-b6a958e7-9461-4dad-8eb1-b3aa56ab1a63.png">

**Comment by chengguo0719** [comment]
> I was experiencing the same error here when using the config.json example file from the documentation.
> 
> To fix this, I've updated my config.json with an **Start and End Date** and with the **captcha** code too. Now it shows my number os NFTs available to mint, the cost and the button works.
> 
> But a weirder thing is happening after. The NFT that I've minted is showing as a regular Token on my Phantom Wallet. It's not on the collectibles tab.
> 
> This is the transaction: [Link](https://solscan.io/tx/3DLo47tquL5M2stBsXyHKnbwsyW89CMYAVumKL4F3wA4pULo3yr27c83JqGaUJASvEeZpe9Z5ULNGHMuFtDv9h87?cluster=devnet)
> 
> <img alt="Captura de Tela 2022-01-19 às 20 11 45" width="358" src="https://user-images.githubusercontent.com/98062847/150233544-3bc33c54-52c1-41d1-9b3f-12277d9ce93b.png">
> 
> <img alt="Captura de Tela 2022-01-19 às 20 15 20" width="358" src="https://user-images.githubusercontent.com/98062847/150233574-b6a958e7-9461-4dad-8eb1-b3aa56ab1a63.png">
> 
> ---- EDIT
> 
> I did another try and it went ok. [hash](https://solscan.io/tx/2p3MkRE4t1EtwQ4NXZRUcaWdFsXdzihZoiGfPj6BXKUaWh7UjHYmd68WeEPpWp9XmKaM9uVu7rJTgSv2KiLFtG5J?cluster=devnet)
> 
> what just happened with the first mint? It still not showing
> 
> ---- EDIT 2 I think that happened because I haven't uploaded all the collection on the first time I ran CandyMachine. I did the upload command again the collection are all clear now. I came to that conclusion because there is no metadata inside the token.

If possible, can you please share your custom config.json file? Thanks.

**Comment by BHALEYART** [comment]
I've tried every suggestion I can find... Thinking this is a bug

**Comment by stegaBOB** [comment]
If you are still having this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). The UI is currently working fine on my end. this is probably an RPC issue. If you are using the default rpcs, they currently block access to the token metadata program since there are too many tokens to index from a free RPC.
