### ISSUE TITLE
can someone help me 

### ISSUE THREAD

**Issue by IntetsuParis** [metaplex-foundation/metaplex#1590]
when i load candy car i get this error what should i do ? (ignore the folder name)
![image](https://user-images.githubusercontent.com/97919071/150032009-21579f20-a67b-48fa-944a-ba9ed63b38e9.png)

**Comment by stegaBOB** [comment]
This is a question better asked in our [Discord](https://discord.gg/metaplex). GitHub issues is reserved for bug reports and feature requests.
