### ISSUE TITLE
upload was not successful, i need help please

### ISSUE THREAD

**Issue by JulienK03** [metaplex-foundation/metaplex#1591]
0.00000365 SOL to upload
upload was not successful, please re-run. Error: Not enough funds to send data
    at Uploader.<anonymous> (C:\Users\LEGION\Desktop\SOLANA NFT\metaplex-master\js\packages\cli\node_modules\@bundlr-network\client\build\src\upload.js:221:23) 
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\LEGION\Desktop\SOLANA NFT\metaplex-master\js\node_modules\tslib\tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
this happens even tho i have more than enough sol to upload, and even tho it pays the fee, but doesnt upload the pic. 
thank you guys

**Comment by rootsha256** [comment]
Faced the same issue, 
post to https://node1.bundlr.network:443/tx/solana
returns 402
Please help

**Comment by corybeevers** [comment]
I've had this issue for nearly 5 days. I have messaged in both the Solana chat & Metaplex chat on Discord and no one can seem to help. I have even messaged the developers in the group and was getting responses, but have been ignored since.

**Comment by rootsha256** [comment]
Yep, the same, bundlr said that everything is good on their side
Metaplex devs gave an advice, switch from arweave-sol to arweave, that actually what I did

**Comment by corybeevers** [comment]
But I have already managed to upload 7,100 to Arweave Sol, I only have 677 left to upload. Surely I won't change it now?

**Comment by rootsha256** [comment]
maybe you really didnt have sol on your account? it costs me about 15 SOL to upload 8888 images
if you didnt mint anything you can use withdraw 
check docs.metaplex.com/candy-machine-v2/withdraw
you will get your SOLs back and can start new upload

**Comment by corybeevers** [comment]
Yes it cost me that much. I have finished the upload now, I just needed to change from Arweave Sol to Arweave. 
All has been paid for and uploaded :) Really happy now it's all been resolved

**Comment by rootsha256** [comment]
nice to hear that

**Comment by cierra2016** [comment]
I faced the same issue.
Changing from 'arweave-sol' to 'arweave' is a good answer for that.
When I change the storage, the CLI works.
