### ISSUE TITLE
Rejected via websocket { InstructionError: [ 4, { Custom: 6008 } ] } Transaction failed: Custom program error: 0x1778  

### ISSUE THREAD

**Issue by UwebDevCom** [metaplex-foundation/metaplex#1597]
**Describe the bug**
using Devnet for minting some NFTs. 
Then  following by documentation, and mint_one_token which is working fine, and then trying to mint_multipe_tokens and im getting the error : 

wallet public key: 6qMuMq9bui4H8qQKX6QLoM7ExMhbaXHGzH25PYEiw1EF
Rejected via websocket { InstructionError: [ 4, { Custom: 6008 } ] }
Timeout Error caught {
  err: { InstructionError: [ 4, [Object] ] },
  slot: 108870640,
  confirmations: 0
}
<PATH>\metaplex\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x1778
    at sendSignedTransaction (<PATH>\metaplex\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (<PATH>\metaplex\js\packages\cli\src\helpers\transactions.ts:59:26)
    at async mintV2 (<PATH>\metaplex\js\packages\cli\src\commands\mint.ts:344:5)       
    at async Command.<anonymous> (<PATH>\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:714:16)

then trying to run mint_one_token again amd still getting the same error.

thanks

**Comment by marc-lassiter** [comment]
I'm getting the same error but its for _mint_one_token_

My code is:
`ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts mint_one_token -e devnet -k ~/.config/solana/devnet.json -c a3`

**Comment by kelvin2180** [comment]
+1

**Comment by marc-lassiter** [comment]
I figured it out. I didn't have authority to mint the token, at least in my case.

**Comment by victorajayi** [comment]
Im having this same issue

**Comment by victorajayi** [comment]
> I figured it out. I didn't have authority to mint the token, at least in my case.

how did you check this?

**Comment by marc-lassiter** [comment]
> > I figured it out. I didn't have authority to mint the token, at least in my case.
> 
> how did you check this?

For whatever reason, I had to change my `solTreasuryAccount` in `config.json` address to the address I was using to mint the token.
So `solTreasuryAccount` = mint address and it worked. 
I tried to change the `solTreasuryAccount` to the `creator` address of the token and that is what brought up this error.

**Comment by victorajayi** [comment]
that still doesn't work for me. I tried minting from candymachine ui and always get the message "Error failed, please try again!" when I try to mint using "mint_one_token" command I get this error message

wallet public key: 4nKrvRmb6B3feKxRM8UgedJ6cBADv7qHJde6D4sF9zuu
REST error for 5wLredTVy1J6rQt2R6KyMPioH5kHQyE8QDgzgL9N5RHYLc4qSBiThvdoKxfcn9zWM3w6TB7mpjD8spDWXDghJ8aG {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: { InstructionError: [ 4, [Object] ] },
  slot: 117115278,
  status: { Err: { InstructionError: [Array] } }
}
Timeout Error caught { InstructionError: [ 4, { Custom: 6008 } ] }
C:\Users\victo\OneDrive\Desktop\solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
    at sendSignedTransaction (C:\Users\victo\OneDrive\Desktop\solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)                                      s\transactions.ts:136:19)
    at async sendTransactionWithRetryWithKeypair (C:\Users\victo\OneDrive\Desktop\solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:59:26)                                                                   kages\cli\src\helpers\transactions.ts
    at async mintV2 (C:\Users\victo\OneDrive\Desktop\solana\metaplex-master\js\packages\cli\src\commands\mint.ts:344:5)                                                                                                       s:344:5)
    at async Command.<anonymous> (C:\Users\victo\OneDrive\Desktop\solana\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:714:16)        ndy-machine-v2-cli.ts:714:16)

**Comment by dericlima** [comment]
I had this issue today, my problem was that my wallet had insufficient funds. I had 0.07 SOL when trying to mint one token. After sending 1 SOL to the wallet the error was gone. A friend of mine mentioned that it's good to have at least 0.1 SOL in the wallet before trying to mint_tokens. I don't how the minimum amount that you need to have. Maybe someone here can give us some clue....

**Comment by ProCoreNFT** [comment]
I was having the same issue, Its a balance issue. Make sure your Treasury account is set properly. you can run the **show** command.
 
`ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts show -e mainnet-beta -k ~/.config/solana/devnet.json -c pName"` And this will pull the information from the candy machine itself.

**It will look like this.**
`Key: CANDYMACHINEID (redacted)
authority:  (Redacted) Treasury Wallet
wallet:  (Redacted) Treasury Wallet <- Generally the same.
tokenMint:  null
uuid:  A8iFMC
price:  250000000
itemsAvailable:  100
itemsRedeemed:  11
goLiveDate:  2022-01-15T22:00:00.000Z
symbol:  
sellerFeeBasisPoints:  1200
creators: 
(Redacted)uKfVA at 50 %
(Redacted)2Tpx3 at 50 %
maxSupply:  0
retainAuthority:  true
isMutable:  true
hidden settings:  null
No end settings detected
No captcha for this candy machine
no whitelist settings`

Make sure you have have enough sol in your wallet to cover at least 1 mint, then it will go though and you only pay gas.

**Comment by 0cv** [comment]
Not clear whether it was a balance issue, I had more than 2 SOL on the `devnet` and it failed. But I nonetheless added 2 SOL through airdrop as per the suggestion above, which brought me to 4 something. Then I retried and it worked. But the fee is very very small as shown below, far below my previous balance of 2 SOL. So, whether it's failing because apparently 2 SOL is too little, or something else? I'd bet on the latter, but not sure why trying a few times eventually does the trick.

![image](https://user-images.githubusercontent.com/1253866/151881297-f8b8b3f0-5dac-4084-ba01-87bcb411a550.png)

**Comment by luckoo-platform** [comment]
Yes it happened to me too, 
then after i added 1 more sol, suddenly it succeed. idk why.

**Comment by Zaouat** [comment]
Hello, guys, I have this problem when I want to mint in the devnet network 

`REST error for 4m7NAz1NoocVaSuftVxYrxjoPRj1jnMXs3yvwKPp7bjxM4gVuanier9dB78F7fmXRzexu3R5CoVYrGSdzXCaoXp4 {confirmationStatus: 'processed', confirmations: 0, err: {…}, slot: 114395225, status: {…}}
connection.ts:274

Rejected via websocket {InstructionError: Array(2)}InstructionError: Array(2)0: 41: {Custom: 6019}length: 2[[Prototype]]: Array(0)[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
mint.ts:191 Error: Transaction failed: Custom program error: 0x1783
    at sendSignedTransaction (connection.ts:197:19)`

**Comment by kecoje** [comment]
Did you manage to solve it?

**Comment by summerplaybook** [comment]
adding sol and retrying also worked for me!

**Comment by kcc0** [comment]
Facing this issue right now. Added SOL to the seller wallet but nothing seems to be working. This is on the mainnet.
Any help here is appreciated.
Could this be an issue with the token wallet?

<img width="1512" alt="Screenshot 2022-03-04 at 11 01 40 AM" src="https://user-images.githubusercontent.com/4690646/156705595-b4e183dc-ba27-40ab-8149-ae6db1254bd8.png">

**Comment by stegaBOB** [comment]
Everyone else's error seems to be resolved. As for @kcc0, this issue has been fixed as of yesterday. Please try to mint again.

**Comment by kcc0** [comment]
> Everyone else's error seems to be resolved. As for @kcc0, this issue has been fixed as of yesterday. Please try to mint again.  

Can confirm ser! Thank you. Please close 🙏

**Comment by SuhairiSubhi** [comment]
Hello guys, got the same error but with IO 
![image](https://user-images.githubusercontent.com/51889948/158029779-39f7183f-153c-4034-9ec9-ed9d47394b0c.png)

**Comment by y0unghe** [comment]
It definitely be lacking of balance. I set the mint price to 1 sol, but in my wallet, I only have 0.9 sol. After I airdrop 2 sol to my wallet, it worked.

**Comment by mrwolny** [comment]
Same for me, the `price` property in Candy Machine config was bigger than what I had in wallet. After changing it, it worked like a charm!
