### ISSUE TITLE
Upload issue missing required argument directory

### ISSUE THREAD

**Issue by tomtom1233** [metaplex-foundation/metaplex#1602]
When I run my upload command I get this missing required argument 'directory' error. My assets folder and my config.json file are ready and I can't find what's causing it.

If you're the one to finally liberate me from all my candy- machine issues I will tip you in SOL
![image](https://user-images.githubusercontent.com/93504460/150238085-e16109fb-5e6e-47ec-9bb7-86a8bfb01431.png)

**Comment by tomtom1233** [comment]
And what would that cache file be ? nowhere in the documentation have I read about a cache file

**Comment by wpollock12** [comment]
All You have to do is give it a name and metaplex writes it for you. 👍🏼
The documentation uses “example” for example. Also, no quote marks. 
good luck
