### ISSUE TITLE
errror upload 

### ISSUE THREAD

**Issue by josedanielchlu** [metaplex-foundation/metaplex#1603]
#error when upload
![Captura](https://user-images.githubusercontent.com/80082645/150244798-fa3e2038-815e-4f91-bc28-9b02d28b0d73.PNG)

need help is @ mainnet-beta

**Comment by stegaBOB** [comment]
This is a question better asked in our [Discord](https://discord.gg/metaplex). GitHub issues is reserved for bug reports and feature requests.
