### ISSUE TITLE
Hey my Nfts uploaded successfully but not all the pngs match the metadata. How can I fix ?

### ISSUE THREAD

**Issue by Franchise97** [metaplex-foundation/metaplex#1606]
**Describe the bug**
Hey my Nfts uploaded successfully but not all the pngs match the metadata. How can I fix ? Some are right and some mints are not

**Expected behavior**
What I expected was for the metadata to have the same description in the pngs. 

**Desktop (please complete the following information):**
 - Catalina OS
 - Brave Browser

**Comment by frosty214** [comment]
Hard to see when you haven't shared any examples!

My best guess is that the json and png files are not numbered accordingly, or some got missed.

**Comment by stegaBOB** [comment]
If you are still having this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). Thanks.
