### ISSUE TITLE
not uploading nfts to arweave-sol error on mainnet

### ISSUE THREAD

**Issue by avanti36** [metaplex-foundation/metaplex#1608]
Hello! I am trying to upload 3 NFTs to mainnet on "storage": "arweave-sol",
(balance on wallet is 0.6 Sol, seems to be enough for my test). Each time I get this error about funds. Could you please, help how to deal with this?

Uploading Size 3 { mediaExt: '.png', index: '0' }
Saved bundle upload result to cache.
Computed Bundle range, including 3 file pair(s) totaling 0.065MB.
Uploading bundle via bundlr... in multiple transactions
0.000009587 SOL to upload
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data
at Uploader. (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)
at Generator.next ()
at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 2) Error: Not enough funds to send data
at Uploader. (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)
at Generator.next ()
at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. Error: Not enough funds to send data
at Uploader. (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)
at Generator.next ()
at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by corybeevers** [comment]
I've had this issue for a week and no one has helped yet. 
I am just commenting on any post with my problem so it pings me if it gets fixed

**Comment by avanti36** [comment]
yes, just have solved today via discord help chat metaplex. I have changed  arweave-sol for "storage": "arweave" in config.json

**Comment by corybeevers** [comment]
Are you uploading to Mainnet? 
Did you start the whole candy machine again or is it with the same candy machine ID you initially created?

**Comment by corybeevers** [comment]
IT WORKED. WTAF. THAT MADE NO SENSE BUT I OWE YOU A FUCKING BJ!!!!
Thank you brother

**Comment by avanti36** [comment]
yes, uploading to mainnet, the same candy machine id, will update now. Glad it also worked for you!

**Comment by samuelvanderwaal** [comment]
`git pull` the latest version of the code and try `arweave-sol` method again. If you still have issues you can re-open this issue. Thanks!

**Comment by avanti36** [comment]
thank you

**Comment by samuelvanderwaal** [comment]
> @samuelvanderwaal hi, `arweave-sol` still give problem while `arweave` works for `mainnet-beta`

Are you on the latest version of the code? What are the errors you're getting?

**Comment by kevinh1534** [comment]
@samuelvanderwaal I'm having the same issue as @justinphan3110, the error I'm getting is:
"Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data"
also says:
"Error: predefined number of NFTs (3) is smaller than the uploaded one (0)"
I'm on the latest version of the code.

**Comment by kevinh1534** [comment]
> IT WORKED. WTAF. THAT MADE NO SENSE BUT I OWE YOU A FUCKING BJ!!!! Thank you brother

What exactly worked for you?

**Comment by samuelvanderwaal** [comment]
> > IT WORKED. WTAF. THAT MADE NO SENSE BUT I OWE YOU A FUCKING BJ!!!! Thank you brother
> 
> What exactly worked for you?

If the `arweave-sol` method isn't working for you, you can use `arweave` instead.

**Comment by billy93** [comment]
i still cant use arweave-sol storage method.. i already pull new source code, and error still same 

"Error: Not enough funds to send data"

any update for this?

**Comment by billy93** [comment]
> > > IT WORKED. WTAF. THAT MADE NO SENSE BUT I OWE YOU A FUCKING BJ!!!! Thank you brother
> > 
> > 
> > What exactly worked for you?
> 
> If the `arweave-sol` method isn't working for you, you can use `arweave` instead.

is it ok to use 'arweave' in mainnet-beta?

**Comment by avanti36** [comment]
just use arweave for both devnet or mainnet

**Comment by nftogetyourich** [comment]
Beginning the upload for 10000 (img+json) pairs
started at: 1648182104828
config for a candy machine with publickey: 3iidDi6fqyRWd1fLY28URSJ2piCBnB9qShZwZp5BrrjF has been already initialized
[10] out of [10000] items have been uploaded
Starting upload for [9990] items, format {"mediaExt":".png","index":"10"}
Progress: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 21/9990
Error uploading {"mediaExt":".png","index":"16"} asset (skipping) request to https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile failed, reason: connect ETIMEDOUT 216.239.36.54:443

**Comment by nftogetyourich** [comment]
> Beginning the upload for 10000 (img+json) pairs started at: 1648182104828 config for a candy machine with publickey: 3iidDi6fqyRWd1fLY28URSJ2piCBnB9qShZwZp5BrrjF has been already initialized [10] out of [10000] items have been uploaded Starting upload for [9990] items, format {"mediaExt":".png","index":"10"} Progress: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 21/9990 Error uploading {"mediaExt":".png","index":"16"} asset (skipping) request to https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile failed, reason: connect ETIMEDOUT 216.239.36.54:443

i got this error message, please help

**Comment by nftogetyourich** [comment]
> 

Error uploading {"mediaExt":".png","index":"3615"} asset (skipping) connect ETIMEDOUT 13.225.250.23:443

and this error as well

**Comment by MishaPetrov** [comment]
"IT WORKED. WTAF. THAT MADE NO SENSE BUT I OWE YOU A FUCKING BJ!!!!" - agree
