### ISSUE TITLE
Error while initializing candy machine

### ISSUE THREAD

**Issue by loosebucks** [metaplex-foundation/metaplex#1609]
When i try to run the code 
npx ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/mainnet-beta.json -cp metaplex/js/packages/cli/config.json -c example metaplex/js/packages/cli/assets

i keep getting this error message,
<img width="930" alt="Screen Shot 2022-01-20 at 4 00 14 PM" src="https://user-images.githubusercontent.com/59600062/150421662-5f9a0a46-1166-4a84-a5a6-7144e141e313.png">
 not sure what i'm doing wrong

**Comment by loosebucks** [comment]
I just realized also it's been charging me solana per attempt...

**Comment by loosebucks** [comment]
just switched over to devnet and it worked perfectly fine though

**Comment by citizenape** [comment]
I have this same problem... can anyone help?

**Comment by everyoneandnoone** [comment]
Inside of your assets folder, I would delete the "./DS_STORE" file, as it is a hidden file that appears to be out of place. Only image files and JSON files should be in there.

**Comment by stegaBOB** [comment]
It looks like this may be from when the network was congested prior to the fix. These kinds of questions are better for our Discord. After asking there, if you still have this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). Thanks.
