### ISSUE TITLE
I don't know if this is you guys or me but it's one heck of a problem that does not go away with deleting and restarting

### ISSUE THREAD

**Issue by airaallday** [metaplex-foundation/metaplex#1611]
When I try to run the npm install -g ts-node after I've gotten my MetaPlex file set up just started spitting this command at me and not letting me do anything. The error was specific and the timing was odd. I did look at installing something off of the brew.sh site for the rust dialog but all of that seems to be gone as far as any files or anything. If that is the issue I can deal with it. I don't expect you guys to help me with this. From what I see online it's a port issue and I do not understand that stuff. I can learn what I need to and the more I do the more it makes sense to me. Regardless if you have any tips, I'm probably going to backup everything important to an external HD and restore to factory if I can't find an answer soon. The project I'm in is moving and I need to understand this to a T

### **Debug looks like this:**
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'npm@8.3.2'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/chllc/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 8ms
18 timing npm:load:configload Completed in 8ms
19 timing npm:load:setTitle Completed in 18ms
20 timing npm:load:setupLog Completed in 1ms
21 timing config:load:flatten Completed in 3ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 33ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 4ms
28 timing idealTree:userRequests Completed in 1ms
29 silly idealTree buildDeps
30 silly fetch manifest npm@8.3.2
31 http fetch GET 200 https://registry.npmjs.org/npm 14ms (cache hit)
32 silly placeDep ROOT npm@8.3.2 OK for:  want: 8.3.2
33 timing idealTree:#root Completed in 34ms
34 timing idealTree:node_modules/npm Completed in 0ms
35 timing idealTree:buildDeps Completed in 35ms
36 timing idealTree:fixDepFlags Completed in 0ms
37 timing idealTree Completed in 42ms
38 timing reify:loadTrees Completed in 188ms
39 timing reify:diffTrees Completed in 4ms
40 silly reify mark retired [
40 silly reify   '/usr/local/lib/node_modules/npm',
40 silly reify   '/usr/local/bin/npm',
40 silly reify   '/usr/local/bin/npx'
40 silly reify ]
41 silly reify moves {
41 silly reify   '/usr/local/lib/node_modules/npm': '/usr/local/lib/node_modules/.npm-i9nnxROI',
41 silly reify   '/usr/local/bin/npm': '/usr/local/bin/.npm-uJtxIR1m',
41 silly reify   '/usr/local/bin/npx': '/usr/local/bin/.npx-xXo12k2C'
41 silly reify }
42 timing reify:rollback:retireShallow Completed in 1ms
43 timing command:install Completed in 253ms
44 verbose stack Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
45 verbose cwd /Users/chllc/Desktop
46 verbose Darwin 21.1.0
47 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@8.3.2"
48 verbose node v16.13.2
49 verbose npm  v8.1.2
50 error code EACCES
51 error syscall rename
52 error path /usr/local/lib/node_modules/npm
53 error dest /usr/local/lib/node_modules/.npm-i9nnxROI
54 error errno -13
55 error Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
55 error  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'] {
55 error   errno: -13,
55 error   code: 'EACCES',
55 error   syscall: 'rename',
55 error   path: '/usr/local/lib/node_modules/npm',
55 error   dest: '/usr/local/lib/node_modules/.npm-i9nnxROI'
55 error }
56 error The operation was rejected by your operating system.
56 error It is likely you do not have the permissions to access this file as the current user
56 error
56 error If you believe this might be a permissions issue, please double-check the
56 error permissions of the file and its containing directories, or try running
56 error the command again as root/Administrator.
57 verbose exit -13

**_The actual error code I keep getting_**
 is New minor version of npm available! 8.1.2 -> 8.3.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.2
npm notice Run npm install -g npm@8.3.2 to update!
npm notice 
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/npm',
npm ERR!   dest: '/usr/local/lib/node_modules/.npm-i9nnxROI'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by airaallday** [comment]
Ran a different script to get there and updated error as follows

To see a list of supported npm commands, run:
  npm help
chllc@Connecteds-MacBook-Air metaplex % npm install https://github.com/metaplex-foundation/metaplex.git
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/chllc/.npm/_cacache/tmp/git-clonebUgg6W/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/chllc/.npm/_cacache/tmp/git-clonebUgg6W/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by VitalSport** [comment]
сб, 22 янв. 2022 г. в 19:27, Alex ***@***.***>:
