### ISSUE TITLE
Public in admin page

### ISSUE THREAD

**Issue by khoiuit99** [metaplex-foundation/metaplex#1615]
When i set public in admin page, it allows to everyone create NFT but cannot to view or sell anything.

Is it a bug or function? If its a bug, how to fix it?
If its a function, what is solution to everyone can view or sell NFT?

Thank you

**Comment by stegaBOB** [comment]
If you are still having this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). Thanks.
