### ISSUE TITLE
Error message RangeError: indeterminate span when uploading is not appropriate

### ISSUE THREAD

**Issue by saito-kosuke** [metaplex-foundation/metaplex#1616]
**Is your feature request related to a problem? Please describe.**

Error message `RangeError: indeterminate span` when uploading is not appropriate.
When there is no symbol in the metadata file, the error above has occurred.
In discord, many users of metaplex ask what this error message means.

**Describe the solution you'd like**

We should add the validation to the function createCandyMachineV2 like below.

```
  if (!candyData.symbol) {
    throw new Error(`Invalid config, there must be a symbol.`);
  }
```

I can make a pull request.
If you like, give me the write rights of this repository.

**Describe alternatives you've considered**

**Additional context**

**Comment by Neoziion** [comment]
I got the same error message but I don't understand how to solve it. Can anyone help me?

**Comment by saito-kosuke** [comment]
@Neoziion 
Maybe, the property `symbol` is missing from your JSON files.

**Comment by RidhwanDev** [comment]
I also have this issue, but I do have symbol and I can see symbol if I do `console.log(candyData.symbol)` so I don't think it's exclusive to that property, maybe when other things are missing. I can't see what is required and what is optional though

**Comment by saito-kosuke** [comment]
@RidhwanDev 
Let me see your JSON file to reproduce your issue.

> I can't see what is required and what is optional though

Totally agree.
We are providing a free tool called Coinfra to check the metadata. 
https://app.gitbook.com/s/t3DGhcnB6Csc5Eht4Jm7/tutorials/step2-option-how-to-check-assets-of-metaplex-candy-machine

**Comment by stegaBOB** [comment]
@saito-kosuke Feel free to open a PR with your proposed fix! We'll merge that in (if it hasn't been added already). Thanks

**Comment by saito-kosuke** [comment]
@stegaBOB 
Could you review my PR https://github.com/metaplex-foundation/metaplex/pull/1693 ?

**Comment by DSellees** [comment]
What is the problem?

Beginning the upload for 1606 (img+json) pairs
started at: 1656495728060
initializing candy machine
Error deploying config to Solana network. RangeError: indeterminate span
    at Structure.getSpan
