### ISSUE TITLE
Storefront not showing NFTs that were minted outside of it

### ISSUE THREAD

**Issue by macolen** [metaplex-foundation/metaplex#1619]
**Describe the bug**
The Metaplex Storefront does not list the NFTs that were minted outside of it, for example with CandyMachines. 

**To Reproduce**
1. Install Metaplex StoreFront
2. Yarn Start
3. Initialize store and config the ENV file with given code
4. Storefront is empty
5. Go to Admin
6. Set PUBLIC, or whitelist the wallets and CandyMachine IDs that you want to feature on the storefront
7. Get to Creators page
8. Select one of the whitelisted creators
9. Infinite loading screen - nothing is showing on Storefront, but there is NFTs on the wallets. 

**Expected behavior**
I was expecting to create my collection with CandyMachine and then list the minted NFTs to my own Storefront. People should be able to navigate the creators collections and buy from there. 

**Screenshots**
Creator screen without content:

![Captura de Tela 2022-01-21 às 14 22 47](https://user-images.githubusercontent.com/98062847/150571837-31d67225-4acc-41b4-892a-5c6dd008ef98.png)

**Desktop (please complete the following information):**
 - OS: macOs Big Sur
 - Browser Chrome
 - Version : 97

**Additional context**
The storefront is running on localhost using DEVNET.

**Comment by bxuserx** [comment]
Same issue. Curious if it has to do with the react hook errors I am getting.
I have this issue on multiple pages... shown here is an individual creation page after upload through metaplex. Also have this problem with nfts minted on candymachine and attempting to view here.
<img width="1201" alt="Screen Shot 2022-01-22 at 1 24 14 AM" src="https://user-images.githubusercontent.com/86570251/150629263-94a6c023-bcc1-4820-a794-b880ac83be7e.png">

**Comment by bitcoinvsalts** [comment]
same issue her

**Comment by DI-TimDavenport** [comment]
Has anyone gotten an update? Still having this issue myself, NFT minted elsewhere show up on external marketplaces absolutely fine but not here, nft created via storefront show the loading loop.

**Comment by stegaBOB** [comment]
Have you added the creator wallets to the admin page? Only NFTs created by those creators will show up in a metaplex storefront

**Comment by macolen** [comment]
> Have you added the creator wallets to the admin page? Only NFTs created by those creators will show up in a metaplex storefront

Should I add the address from the Wallet that owns authority over a CandyMachinev2, or the address from the CandyMachine itself?

On my case, the wallet that has a CM is the same that I'm using to setup storefront. This wallet owns the store and the Candy Machine. Even in this way, Storefront can't retrieve any of the NFTs that this account have minted, or possesses. 

Another question: 
In the case of a user that don't have created any NFT, but have bought a couple and want to sell it on a Metaplex website, is that possible?

**Comment by SudarminThen** [comment]
Have the same problem, NFT from candy machine won't show up and can't be sell on Storefront, how to fix this?

**Comment by frosty214** [comment]
Did you use hashlips to generate the art? It's interesting, in most cases it is advised to have the metadata at the time of generation to have a URI of ".png" and not the standard "image.png". When I use ".png" as the URI, the images themselves will not load up in third parties or in wallets. But when I use "image.png" they will. Just a thought!

**Comment by SudarminThen** [comment]
Just learned that the creators inside the json metadata need to sign the NFT after being minted, you can sign it using metaboss
https://github.com/samuelvanderwaal/metaboss
After signing it, now the NFT showed on Storefront

**Comment by macolen** [comment]
> Did you use hashlips to generate the art? It's interesting, in most cases it is advised to have the metadata at the time of generation to have a URI of ".png" and not the standard "image.png". When I use ".png" as the URI, the images themselves will not load up in third parties or in wallets. But when I use "image.png" they will. Just a thought!

Yes. I did use hashlips to generate the NFTs. This makes me thing that were something wrong with my metadata structure inside json files. But @SudarminThen nailed it !! We need to verify the NFTs for metaplex show then

**Comment by macolen** [comment]
> Just learned that the creators inside the json metadata need to sign the NFT after being minted, you can sign it using metaboss https://github.com/samuelvanderwaal/metaboss After signing it, now the NFT showed on Storefront

Thanks a lot !! 
I did that and it worked for me. \0/ Never knew that we are supposed to verify the NFTs after minting then.

**Comment by frosty214** [comment]
> > Just learned that the creators inside the json metadata need to sign the NFT after being minted, you can sign it using metaboss https://github.com/samuelvanderwaal/metaboss After signing it, now the NFT showed on Storefront
> 
> Thanks a lot !! I did that and it worked for me. \0/ Never knew that we are supposed to verify the NFTs after minting then.

Oh yes, you need to run the ts-node verify_upload command after uploading :) Good job!

**Comment by khoiuit99** [comment]
Can yall help me explain detail how to fix it? 
Tried to access the link but dont know how to do :|
