### ISSUE TITLE
UpdateMetadataV2Args and DataV2 missing from borsh schema

### ISSUE THREAD

**Issue by 21e8** [metaplex-foundation/metaplex#1621]
**Describe the bug**
`update-metadata` is simply broken

**To Reproduce**
1. Try to use `update-metadata` in `cli-nft.ts`
2. Error thrown `Class UpdateMetadataV2Args is missing in schema`

**Expected behavior**
New schemas should be added to borsh and update should work

**Screenshots**
<img width="622" alt="grafik" src="https://user-images.githubusercontent.com/40480041/150577319-bb572a98-2d3e-4e06-b7bd-1745843fbde5.png">

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by 21e8** [comment]
Would be fixed by: https://github.com/metaplex-foundation/metaplex/pull/1554

**Comment by ab3llini** [comment]
Hello, any progress on this?

**Comment by mralbertchen** [comment]
#1554 was closed. Is there a new PR for this?

**Comment by 21e8** [comment]
@roederw ?

**Comment by roederw** [comment]
I'll take a look.

**Comment by 21e8** [comment]
any reason for closing that is perfectly fine for the meantime?

**Comment by stegaBOB** [comment]
I'll be overhauling the CLIs to use our packages. Closing this issue as the broader issue is addressed in #1896.
