### ISSUE TITLE
Guys, I broke my head. Please help me!

### ISSUE THREAD

**Issue by Baklaza** [metaplex-foundation/metaplex#1623]
Can I somehow issue a limited number of tokens for minting to one wallet? 

I searched for this information everywhere and could not find anything, I would be very grateful if you could tell me how this can be done!

**Comment by guillemap** [comment]
You can 

1. Use a WL only minting with this code for `whitelistMintSettings` in the **config.json** file for the CM:

```
  "whitelistMintSettings": {
    "mode" : { "burnEveryTime": true },
    "mint" : "[spl-token-address]",
    "presale" : false,
    "discountPrice" : null
  }
```

2. Send the same amount of SPL tokens as NFTs available to mint to the lucky wallet. Use the commands:

`spl-token create-token --decimals 0` --> Will output "Creating token [spl-token-address]"
`spl-token create-account [spl-token-address]`
`spl-token mint [spl-token-address] [units-of-NFT]`
`spl-token transfer --fund-recipient [spl-token-address] 1 [lucky-wallet-address]`

Useful also to limit amount available to be minted to 1 per wallet (by sending only 1 SPL token to each wallet), however the wallets must be known and the SPL tokens must be delivered beforehand. You can use [Gumdrop](https://hackmd.io/@MarkSackerberg/gumdrop) to ease this process.

**Comment by guillemap** [comment]
Btw could you rename the issue to something more specific as, eg: "How to issue a limited number of tokens for minting to one wallet?"

**Comment by stegaBOB** [comment]
This is a question better asked in our [Discord](https://discord.gg/metaplex). GitHub issues is reserved for bug reports and feature requests.
