### ISSUE TITLE
Trouble hosting metaplex store

### ISSUE THREAD

**Issue by rolandstudios** [metaplex-foundation/metaplex#1626]
Hey I tried following the documentation exactly as instructed to get the storefront up and running. It works fine when running off my local host, but when deploying to github pages, all the icons are missing and the whole site locks up. Also when trying to host the static pages from "\metaplex\js\build\web" the page comes up blank white. I'm at a loss as to what is going wrong.

This was last info I got back from terminel after running yarn deploy

Export successful. Files written to C:\Users\rolan\Desktop\metaplex\js\build\web
Cloning into 'C:\Users\rolan\Desktop\metaplex\js\packages\web\node_modules\.cache\gh-pages\https!rolandstudios.github.io!metaplex'...
fatal: repository 'https://rolandstudios.github.io/metaplex/' not found

error Command failed with exit code 1.

**Comment by ck256-2000** [comment]
did you look in your package json to see if the home page was correct?
