### ISSUE TITLE
$PATH

### ISSUE THREAD

**Issue by airaallday** [metaplex-foundation/metaplex#1628]
If anyone on Mac knows how to get this issue solved for good please let me know. I've been on the test net twice ready to test some nfts and then I lose connection to Solana commands and the install does this no matter how I install it or the advice on Solana.

metaplex % sh -c "$(curl -sSfL https://release.solana.com/v1.9.5/install)"

downloading v1.9.5 installer
⠲ [>                                       ] 87.50K⠴ [>                                       ] 215.37⠤ [>                                       ] 352.11⠤ [>                                       ] 503.37⠄ [>                                       ] 663.37⠄ [>                                       ] 839.37⠄ [>                                       ] 1015.3⠤ [>                                       ] 1.18Mi⠠ [>                                       ] 1.37Mi⠠ [>                                       ] 1.55Mi⠠ [>                                       ] 1.76Mi⠤ [>                                       ] 1.96Mi⠤ [>                                       ] 2.18Mi⠦ [>                                       ] 2.40Mi⠖ [=>                                      ] 2.62Mi⠖ [=>                                      ] 2.85Mi⠒ [=>                                      ] 3.09Mi⠐ [=>                                      ] 3.32Mi⠐ [=>                                      ] 3.52Mi⠐ [=>                                      ] 3.84Mi⠒ [=>                                      ] 4.09Mi⠒ [=>                                      ] 4.32Mi⠓ [=>                                      ] 4.55Mi⠋ [=>                                      ] 4.79Mi⠉ [=>                                      ] 5.04Mi⠉ [==>                                     ] 5.27Mi⠈ [==>                                     ] 5.51Mi⠈ [==>                                     ] 5.74Mi⠈ [==>                                     ] 5.98Mi⠁ [==>                                     ] 6.21Mi⠁ [==>                                     ] 6.44Mi⠁ [==>                                     ] 6.68Mi⠉ [==>                                     ] 6.91Mi⠙ [==>                                     ] 7.13Mi⠙ [==>                                     ] 7.37Mi⠚ [==>                                     ] 7.60Mi⠒ [===>                                    ] 7.84Mi⠒ [===>                                    ] 8.07Mi⠂ [===>                                    ] 8.29Mi⠂ [===>                                    ] 8.54Mi⠂ [===>                                    ] 8.77Mi⠒ [===>                                    ] 9.01Mi⠲ [===>                                    ] 9.26Mi⠲ [===>                                    ] 9.49Mi⠴ [===>                                    ] 9.73Mi⠤ [===>                                    ] 9.96Mi⠤ [====>                                   ] 10.19M⠄ [====>                                   ] 10.43M⠄ [====>                                   ] 10.66M⠄ [====>                                   ] 10.90M⠤ [====>                                   ] 11.13M⠠ [====>                                   ] 11.37M⠠ [====>                                   ] 11.60M⠠ [====>                                   ] 11.84M⠤ [====>                                   ] 12.07M⠤ [====>                                   ] 12.30M⠦ [====>                                   ] 12.54M⠖ [=====>                                  ] 12.77M⠖ [=====>                                  ] 13.01M⠒ [=====>                                  ] 13.24M⠐ [=====>                                  ] 13.48M⠐ [=====>                                  ] 13.71M⠐ [=====>                                  ] 13.94M⠒ [=====>                                  ] 14.18M⠒ [=====>                                  ] 14.41M⠓ [=====>                                  ] 14.65M⠋ [=====>                                  ] 14.88M⠋ [=====>                                  ] 15.12M⠉ [======>                                 ] 15.34M⠈ [======>                                 ] 15.57M⠈ [======>                                 ] 15.80M⠈ [======>                                 ] 16.04M⠁ [======>                                 ] 16.27M⠁ [======>                                 ] 16.51M⠁ [======>                                 ] 16.74M⠉ [======>                                 ] 16.98M⠉ [======>                                 ] 17.21M⠙ [======>                                 ] 17.44M⠚ [======>                                 ] 17.68M⠚ [=======>                                ] 17.91M⠒ [=======>                                ] 18.15M⠂ [=======>                                ] 18.38M⠂ [=======>                                ] 18.62M⠂ [=======>                                ] 18.85M⠒ [=======>                                ] 19.09M⠒ [=======>                                ] 19.32M⠲ [=======>                                ] 19.55M⠴ [=======>                                ] 19.79M⠤ [=======>                                ] 20.02M⠤ [=======>                                ] 20.26M⠄ [========>                               ] 20.49M⠄ [========>                               ] 20.73M⠄ [========>                               ] 20.96M⠤ [========>                               ] 21.19M⠠ [========>                               ] 21.43M⠠ [========>                               ] 21.66M⠠ [========>                               ] 21.90M⠤ [========>                               ] 22.13M⠤ [========>                               ] 22.37M⠦ [========>                               ] 22.60M⠖ [=========>                              ] 22.84M⠖ [=========>                              ] 23.07M⠒ [=========>                              ] 23.30M⠐ [=========>                              ] 23.54M⠐ [=========>                              ] 23.77M⠐ [=========>                              ] 24.01M⠒ [=========>                              ] 24.24M⠒ [=========>                              ] 24.48M⠓ [=========>                              ] 24.71M⠋ [=========>                              ] 24.94M⠋ [=========>                              ] 25.12M⠉ [==========>                             ] 25.41M⠈ [==========>                             ] 25.65M⠈ [==========>                             ] 25.88M⠈ [==========>                             ] 26.12M⠁ [==========>                             ] 26.35M⠁ [==========>                             ] 26.59M⠁ [==========>                             ] 26.82M⠉ [==========>                             ] 27.05M⠉ [==========>                             ] 27.29M⠙ [==========>                             ] 27.52M⠚ [==========>                             ] 27.76M⠚ [===========>                            ] 27.99M⠒ [===========>                            ] 28.23M⠂ [===========>                            ] 28.46M⠂ [===========>                            ] 28.69M⠂ [===========>                            ] 28.93M⠒ [===========>                            ] 29.16M⠒ [===========>                            ] 29.40M⠲ [===========>                            ] 29.63M⠴ [===========>                            ] 29.87M⠤ [===========>                            ] 30.05M⠄ [===========>                            ] 30.05M⠄ [===========>                            ] 30.16M⠄ [===========>                            ] 30.16M⠠ [===========>                            ] 30.33M⠠ [===========>                            ] 30.34M⠠ [============>                           ] 30.49M⠤ [============>                           ] 30.73M⠤ [============>                           ] 30.96M⠦ [============>                           ] 31.23M⠖ [============>                           ] 31.48M⠖ [============>                           ] 31.71M⠒ [============>                           ] 31.94M⠐ [============>                           ] 32.17M⠐ [============>                           ] 32.41M⠐ [============>                           ] 32.65M⠒ [============>                           ] 32.88M⠒ [=============>                          ] 33.12M⠓ [=============>                          ] 33.35M⠋ [=============>                          ] 33.59M⠋ [=============>                          ] 33.82M⠉ [=============>                          ] 34.05M⠈ [=============>                          ] 34.29M⠈ [=============>                          ] 34.52M⠈ [=============>                          ] 34.76M⠁ [=============>                          ] 34.99M⠁ [=============>                          ] 35.23M⠁ [=============>                          ] 35.46M⠉ [==============>                         ] 35.69M⠉ [==============>                         ] 35.93M⠙ [==============>                         ] 36.16M⠚ [==============>                         ] 36.40M⠚ [==============>                         ] 36.63M⠒ [==============>                         ] 36.87M⠂ [==============>                         ] 37.10M⠂ [==============>                         ] 37.32M⠂ [==============>                         ] 37.57M⠒ [==============>                         ] 37.80M⠒ [==============>                         ] 38.04M⠲ [===============>                        ] 38.27M⠴ [===============>                        ] 38.51M⠴ [===============>                        ] 38.74M⠤ [===============>                        ] 38.98M⠄ [===============>                        ] 39.21M⠄ [===============>                        ] 39.44M⠄ [===============>                        ] 39.68M⠤ [===============>                        ] 39.91M⠤ [===============>                        ] 40.15M⠠ [===============>                        ] 40.38M⠠ [================>                       ] 40.62M⠠ [================>                       ] 40.85M⠤ [================>                       ] 41.09M⠦ [================>                       ] 41.32M⠦ [================>                       ] 41.55M⠖ [================>                       ] 41.79M⠒ [================>                       ] 42.02M⠒ [================>                       ] 42.26M⠐ [================>                       ] 42.49M⠐ [================>                       ] 42.73M⠐ [================>                       ] 42.96M⠒ [=================>                      ] 43.19M⠓ [=================>                      ] 43.43M⠓ [=================>                      ] 43.66M⠋ [=================>                      ] 43.88M⠉ [=================>                      ] 44.13M⠉ [=================>                      ] 44.37M⠈ [=================>                      ] 44.60M⠈ [=================>                      ] 44.84M⠈ [=================>                      ] 45.07M⠁ [=================>                      ] 45.30M⠁ [=================>                      ] 45.49M⠉ [==================>                     ] 45.79M⠉ [==================>                     ] 46.02M⠙ [==================>                     ] 46.26M⠚ [==================>                     ] 46.49M⠚ [==================>                     ] 46.73M⠒ [==================>                     ] 46.96M⠂ [==================>                     ] 47.19M⠂ [==================>                     ] 47.43M⠂ [==================>                     ] 47.66M⠒ [==================>                     ] 47.90M⠒ [==================>                     ] 48.13M⠲ [===================>                    ] 48.37M⠴ [===================>                    ] 48.60M⠴ [===================>                    ] 48.84M⠤ [===================>                    ] 49.07M⠄ [===================>                    ] 49.30M⠄ [===================>                    ] 49.54M⠄ [===================>                    ] 49.77M⠤ [===================>                    ] 50.01M⠤ [===================>                    ] 50.24M⠠ [===================>                    ] 50.48M⠠ [===================>                    ] 50.71M⠠ [====================>                   ] 50.94M⠤ [====================>                   ] 51.18M⠦ [====================>                   ] 51.41M⠦ [====================>                   ] 51.65M⠖ [====================>                   ] 51.88M⠒ [====================>                   ] 52.12M⠒ [====================>                   ] 52.35M⠐ [====================>                   ] 52.59M⠐ [====================>                   ] 52.82M⠐ [====================>                   ] 53.05M⠒ [=====================>                  ] 53.29M⠓ [=====================>                  ] 53.52M⠓ [=====================>                  ] 53.76M⠋ [=====================>                  ] 53.99M⠉ [=====================>                  ] 54.23M⠉ [=====================>                  ] 54.46M⠈ [=====================>                  ] 54.69M⠈ [=====================>                  ] 54.93M⠈ [=====================>                  ] 55.16M⠁ [=====================>                  ] 55.40M⠁ [=====================>                  ] 55.65M⠁ [======================>                 ] 55.88M⠉ [======================>                 ] 56.12M⠙ [======================>                 ] 56.35M⠙ [======================>                 ] 56.59M⠚ [======================>                 ] 56.82M⠒ [======================>                 ] 57.05M⠒ [======================>                 ] 57.27M⠂ [======================>                 ] 57.51M⠂ [======================>                 ] 57.74M⠂ [======================>                 ] 57.98M⠒ [======================>                 ] 58.21M⠲ [=======================>                ] 58.44M⠲ [=======================>                ] 58.68M⠴ [=======================>                ] 58.91M⠤ [=======================>                ] 59.15M⠤ [=======================>                ] 59.38M⠄ [=======================>                ] 59.62M⠄ [=======================>                ] 59.85M⠄ [=======================>                ] 60.09M⠤ [=======================>                ] 60.32M⠠ [=======================>                ] 60.55M⠠ [=======================>                ] 60.79M⠠ [========================>               ] 61.02M⠤ [========================>               ] 61.26M⠦ [========================>               ] 61.48M⠦ [========================>               ] 61.73M⠖ [========================>               ] 61.96M⠒ [========================>               ] 62.19M⠒ [========================>               ] 62.43M⠐ [========================>               ] 62.66M⠐ [========================>               ] 62.90M⠐ [========================>               ] 63.13M⠒ [========================>               ] 63.37M⠓ [=========================>              ] 63.60M⠓ [=========================>              ] 63.84M⠋ [=========================>              ] 64.07M⠉ [=========================>              ] 64.30M⠉ [=========================>              ] 64.54M⠈ [=========================>              ] 64.77M⠈ [=========================>              ] 65.01M⠈ [=========================>              ] 65.24M⠁ [=========================>              ] 65.48M⠁ [=========================>              ] 65.71M⠁ [=========================>              ] 65.94M⠉ [==========================>             ] 66.18M⠙ [==========================>             ] 66.43M⠙ [==========================>             ] 66.66M⠚ [==========================>             ] 66.90M⠒ [==========================>             ] 67.13M⠒ [==========================>             ] 67.37M⠂ [==========================>             ] 67.60M⠂ [==========================>             ] 67.84M⠒ [==========================>             ] 68.06M⠒ [==========================>             ] 68.30M⠲ [===========================>            ] 68.54M⠴ [===========================>            ] 68.77M⠴ [===========================>            ] 69.01M⠤ [===========================>            ] 69.24M⠄ [===========================>            ] 69.48M⠄ [===========================>            ] 69.71M⠄ [===========================>            ] 69.96M⠤ [===========================>            ] 70.19M⠤ [===========================>            ] 70.43M⠠ [===========================>            ] 70.66M⠠ [===========================>            ] 70.90M⠠ [============================>           ] 71.13M⠤ [============================>           ] 71.37M⠦ [============================>           ] 71.60M⠦ [============================>           ] 71.84M⠖ [============================>           ] 72.07M⠒ [============================>           ] 72.30M⠒ [============================>           ] 72.54M⠐ [============================>           ] 72.77M⠐ [============================>           ] 73.01M⠐ [============================>           ] 73.24M⠒ [============================>           ] 73.48M⠓ [=============================>          ] 73.71M⠓ [=============================>          ] 73.94M⠋ [=============================>          ] 74.18M⠉ [=============================>          ] 74.41M⠉ [=============================>          ] 74.65M⠈ [=============================>          ] 74.88M⠈ [=============================>          ] 75.12M⠈ [=============================>          ] 75.35M⠁ [=============================>          ] 75.59M⠁ [=============================>          ] 75.82M⠁ [=============================>          ] 76.05M⠉ [==============================>         ] 76.29M⠙ [==============================>         ] 76.52M⠚ [==============================>         ] 76.75M⠚ [==============================>         ] 76.99M⠒ [==============================>         ] 77.23M⠒ [==============================>         ] 77.44M⠂ [==============================>         ] 77.68M⠂ [==============================>         ] 77.91M⠂ [==============================>         ] 78.15M⠒ [==============================>         ] 78.38M⠲ [==============================>         ] 78.62M⠲ [===============================>        ] 78.85M⠴ [===============================>        ] 79.07M⠤ [===============================>        ] 79.29M⠤ [===============================>        ] 79.54M⠄ [===============================>        ] 79.77M⠤ [===============================>        ] 80.00M⠤ [===============================>        ] 80.49M⠠ [===============================>        ] 80.73M⠠ [===============================>        ] 80.96M⠠ [================================>       ] 81.19M⠤ [================================>       ] 81.43M⠦ [================================>       ] 81.66M⠦ [================================>       ] 81.90M⠖ [================================>       ] 82.13M⠒ [================================>       ] 82.37M⠒ [================================>       ] 82.60M⠐ [================================>       ] 82.84M⠐ [================================>       ] 83.07M⠐ [================================>       ] 83.30M⠒ [================================>       ] 83.49M⠓ [=================================>      ] 83.77M⠓ [=================================>      ] 84.01M⠋ [=================================>      ] 84.24M⠉ [=================================>      ] 84.48M⠉ [=================================>      ] 84.71M⠈ [=================================>      ] 84.94M⠈ [=================================>      ] 85.18M⠈ [=================================>      ] 85.41M⠁ [=================================>      ] 85.65M⠁ [=================================>      ] 85.88M⠁ [=================================>      ] 86.12M⠉ [==================================>     ] 86.35M⠙ [==================================>     ] 86.59M⠙ [==================================>     ] 86.82M⠚ [==================================>     ] 87.05M⠒ [==================================>     ] 87.29M⠒ [==================================>     ] 87.52M⠂ [==================================>     ] 87.76M⠂ [==================================>     ] 87.99M⠂ [==================================>     ] 88.23M⠒ [==================================>     ] 88.46M⠲ [==================================>     ] 88.69M⠲ [===================================>    ] 88.93M⠴ [===================================>    ] 89.16M⠄ [===================================>    ] 89.37M⠄ [===================================>    ] 89.90M⠄ [===================================>    ] 90.13M⠄ [===================================>    ] 90.37M⠤ [===================================>    ] 90.60M⠠ [===================================>    ] 90.84M⠠ [===================================>    ] 91.06M⠠ [===================================>    ] 91.30M⠤ [====================================>   ] 91.54M⠦ [====================================>   ] 91.77M⠦ [====================================>   ] 92.01M⠖ [====================================>   ] 92.24M⠒ [====================================>   ] 92.48M⠒ [====================================>   ] 92.71M⠐ [====================================>   ] 92.94M⠐ [====================================>   ] 93.18M⠐ [====================================>   ] 93.41M⠒ [====================================>   ] 93.65M⠓ [=====================================>  ] 93.88M⠓ [=====================================>  ] 94.12M⠋ [=====================================>  ] 94.35M⠉ [=====================================>  ] 94.59M⠉ [=====================================>  ] 94.82M⠈ [=====================================>  ] 95.05M⠈ [=====================================>  ] 95.30M⠈ [=====================================>  ] 95.54M⠁ [=====================================>  ] 95.77M⠁ [=====================================>  ] 96.01M⠁ [=====================================>  ] 96.23M⠉ [======================================> ] 96.46M⠙ [======================================> ] 96.69M⠙ [======================================> ] 96.93M⠚ [======================================> ] 97.16M⠒ [======================================> ] 97.40M⠒ [======================================> ] 97.63M⠂ [======================================> ] 97.87M⠂ [======================================> ] 98.10M⠂ [======================================> ] 98.34M⠒ [======================================> ] 98.57M⠲ [======================================> ] 98.80M⠲ [=======================================>] 99.04M⠴ [=======================================>] 99.27M⠤ [=======================================>] 99.51M⠤ [=======================================>] 99.74M⠄ [=======================================>] 99.98M⠄ [=======================================>] 100.21⠄ [=======================================>] 100.44⠤ [=======================================>] 100.68⠠ [=======================================>] 100.91⠠ [=======================================>] 101.15⠠ [=======================================>] 101.38⠦ [========================================] 101.47⠖ [========================================] 101.47⠒ [========================================] 101.47⠐ [========================================] 101.47⠐ [========================================] 101.47⠒ [========================================] 101.47⠓ [========================================] 101.47  ✨ 1.9.5 initialized

Please update your PATH environment variable to include the solana programs:
    PATH="/Users/chllc/.local/share/solana/install/active_release/bin:$PATH"

chllc@Connecteds-MacBook-Air metaplex % /Users/chllc/.local/share/solana/install/active_release/bin:$PATH"
dquote> $PATH
dquote> :$PATH
dquote> /Users/chllc/.local/share/solana/install/active_release/bin
dquote>     PATH="/Users/chllc/.local/share/solana/install/active_release/bin:$PATH"
dquote>

**Comment by stegaBOB** [comment]
```bash
Please update your PATH environment variable to include the solana programs:
PATH="/Users/chllc/.local/share/solana/install/active_release/bin:$PATH"

chllc@Connecteds-MacBook-Air metaplex % PATH="/Users/chllc/.local/share/solana/install/active_release/bin:$PATH"
```

You copied the wrong text and left a quote open. You have to copy and paste the full message.
