### ISSUE TITLE
update_candy_machine error

### ISSUE THREAD

**Issue by travzki** [metaplex-foundation/metaplex#1629]
![Screenshot_8](https://user-images.githubusercontent.com/26986388/150652399-cca869d7-69b9-444c-8193-ee609f6d6b4e.png)
this error wont allow me to update my candy machine
anyone solved this ?

 ts-node C:\Users\Travz\OneDrive\Desktop\NFTStuff\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts update_candy_machine -e mainnet-beta -c temp -k C:\Users\Travz\OneDrive\Desktop\NFTStuff\.config\solana\gsl-mainnet.json -cp C:\Users\Travz\OneDrive\Desktop\NFTStuff\metaplex\js\packages\cli\config.json --log-level debug -c temp
is the input

**Comment by samuelvanderwaal** [comment]
You have a invalid public key somewhere. Check your JSON files that your creators are actually using valid public keys. Try running the `verify-assets` command to check your assets. Re-open this issue if that doesn't solve the problem.
