### ISSUE TITLE
Getting SyntaxError: Unexpected token c in JSON at position 1 at first step of upload 

### ISSUE THREAD

**Issue by ErnestoMirandaT** [metaplex-foundation/metaplex#1630]
**Describe the bug**
I'm running code directly from the docs and other sources, and really stock at this point.. I'm running: 
`ts-node /Users/miordenador/Desktop/NFT/metaplex-master/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp /Users/miordenador/Desktop/NFT/hashlips_art_engine-main/src/config.json \
    -c example \
    /Users/miordenador/Desktop/NFT/metaplex-master/assets
`

Wallet appears, and then SyntaxError: Unexpected token c in JSON at position 1

`  wallet public key: xxxxxxxxxxxxxxxxxxxxx
/Users/miordenador/Desktop/NFT/metaplex-master/js/packages/cli/src/helpers/various.ts:56
  const config = JSON.parse('{configString}');
                      ^
SyntaxError: Unexpected token c in JSON at position 1
    at JSON.parse (<anonymous>)
    at getCandyMachineV2Config (/Users/miordenador/Desktop/NFT/metaplex-master/js/packages/cli/src/helpers/various.ts:56:23)
    at Command.<anonymous> (/Users/miordenador/Desktop/NFT/metaplex-master/js/packages/cli/src/candy-machine-v2-cli.ts:99:38)`

This is the code that is refered on file various.ts, on the path /metaplex-master/js/packages/cli/src/helpers

  `const configString = fs.readFileSync(configPath);

  //@ts-ignore
  const config = JSON.parse('{configString}');

  const {`

I'm uisng Mac OS, Monterey.

Going nuts, here thanks for any support!

**Comment by samuelvanderwaal** [comment]
Something is wrong with your JSON file. Try running the `verify-assets` command to check your JSON or manually inspect it to see what's wrong.

**Comment by stegaBOB** [comment]
If you are still having issues, feel free to ask in our Discord (discord.gg/metaplex).

**Comment by summerplaybook** [comment]
> Something is wrong with your JSON file. Try running the `verify-assets` command to check your JSON or manually inspect it to see what's wrong.

this is now `verify_assets` as well
