### ISSUE TITLE
Server responded with 429 Too Many Requests

### ISSUE THREAD

**Issue by inexplicableeth** [metaplex-foundation/metaplex#1631]
**Describe the bug**
I am trying to upload 1 PNG+JSON into mainnet with a storage: arweave-sol config and am receiving the following error:

```
Saved bundle upload result to cache.
Computed Bundle range, including 1 file pair(s) totaling 0.004MB.
Uploading bundle via bundlr... in multiple transactions
0.000001158 SOL to upload
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 1000ms delay...
Server responded with 429 Too Many Requests.  Retrying after 2000ms delay...
Server responded with 429 Too Many Requests.  Retrying after 4000ms delay...
upload was not successful, please re-run. Error: 429 Too Many Requests:  {"jsonrpc":"2.0","error":{"code": 429, "message":"Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com."}, "id": "f09b3234-0117-41d9-8e16-9bd198b894b6" } 
```

**To Reproduce**
1. Prepare 1 PNG+JSON asset
2. Fund solana account with enough SOL
3. Set storage to arweave-sol
4. Use upload cli command and set rpc-url to a custom quicknode (I am using $99 pro version)

**Expected behavior**
Expect transaction to go through using a custom RPC url.

I've pulled down the latest version of this metaplex repo just now and still getting the same error. When I use a bogus RPC url in the options e.g. https://testifthisworks.com...I do get appropriate errors saying it is invalid. So for some reason these RPCs are connecting, and looks like they are doing the appropriate calls (getaddrinfo), but I am still running into 429 errors? If I check my quicknode dashboard, I do see it getting hit as well. Anyone able to resolve this?

**Comment by inexplicableeth** [comment]
It seems to work if storage is just `arweave` instead of `arweave-sol`. Any idea why that is? And is there any drawback to using arweave? Will those assets be permanently stored into arweave with that free option (no sol deducted from account)

**Comment by chilam1234** [comment]
same issue need some help on this

**Comment by PatrykXDD** [comment]
check #1643

**Comment by GMnky** [comment]
have the same problem

**Comment by alexddo** [comment]
I came up with a temporary solution you could use, adding a timeout before uploading function.
You can modify the values of the time outs to fit your needs.

I added a value that separates the uploads in portions.
This is js/packages/cli/src/commands/upload.js file
![Screenshot 2022-01-25 003819](https://user-images.githubusercontent.com/32477612/150883288-f9f1b627-5155-4393-935e-b8da45f65a16.png)

And added the "sleep function" with this syntax to prevent the execution of the rest of the code.
This /js/packages/cli/src/helpers/upload/arweave.js
![Screenshot 2022-01-25 002722](https://user-images.githubusercontent.com/32477612/150882186-8abe967a-62cc-4de4-bcd7-d25695e97255.png)

I know that this makes the execution slower but this is the best I could do, I hope you find it useful.

I'll atach the files so you can see them better.
[429_error_fixes.zip](https://github.com/metaplex-foundation/metaplex/files/7929574/429_error_fixes.zip)

**Comment by samuelvanderwaal** [comment]
Use the `arweave` storage method for now. This is an issue with the Bundlr package that we will fix by upgrading to a new version.
