### ISSUE TITLE
Can't upload images using v2

### ISSUE THREAD

**Issue by gaozp** [metaplex-foundation/metaplex#1632]
![image](https://user-images.githubusercontent.com/3950594/150672110-51364547-11ad-4024-a4e6-1ccb3c0e7096.png)

plz help me with this. :(

**Comment by stegaBOB** [comment]
If you are still having this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). Thanks.
