### ISSUE TITLE
TypeError: _b.every is not a function

### ISSUE THREAD

**Issue by philried24** [metaplex-foundation/metaplex#1633]
Hi,

I am getting this error if I want to upload my assets. Any idea on how to solve the problem?
![image](https://user-images.githubusercontent.com/91902572/150673465-f1089973-db6c-4b50-baaa-58d6ff7a1be3.png)

**Comment by mikekitckchan** [comment]
Could you show your config file and json files of your assets as well? It may help.

**Comment by philried24** [comment]
the config file:
![image](https://user-images.githubusercontent.com/91902572/152191505-679779a0-b9a7-4f9d-afcb-3595e8c69950.png)

the json of the image:
![image](https://user-images.githubusercontent.com/91902572/152191592-a8473cac-abf9-4c2d-a38d-b8c3b7ec0e23.png)

Thank you in advance!

**Comment by mikekitckchan** [comment]
In json of the image, in property, it should be:

```
"creators":[ 
         {
            "address": "address of the creator",
            "share": 100
         }
```

**Comment by philried24** [comment]
oh thank you so much!! that helped
