### ISSUE TITLE
error: missing signature for supplied pubkey

### ISSUE THREAD

**Issue by Pixelapesnfts** [metaplex-foundation/metaplex#1635]
Hello, whenever I try to create an SPL token I get this error code:

error: missing signature for supplied pubkey: My Candy Machine Wallet Address>

Before that I already did this: solana config set -k My Candy Machine Wallet Address>

Its was confirmed.

My command: spl-token create-token To----------------------------------------------------------- --decimals 0

Anyone know where the error is? I can't get any further here.

I need this for whitelisting.

I hope someone can help me.

**Comment by samuelvanderwaal** [comment]
`solana config set -k My Candy Machine Wallet Address>` this should be the path to your candy machine wallet address. 

` spl-token create-token To----------------------------------------------------------- --decimals 0`

I don't understand what you are specifying here. Usually the argument is a path to a keypair file. What are you passing in?

**Comment by Lukaris** [comment]
I had the same problem..  for others who might have a similar problem..  
solana config set -k <My Candy Machine Wallet Address>.json

I forgot to add ".json" with the wallet address
afterwards it worked perfect

**Comment by tatikondarahul2001** [comment]
Error: Dynamic program error: missing signature for supplied pubkey: DKZDN1QM7ZGBfUZhQFPo233ccBxumjLGzFqKvMV43dzH

What is the solution for the above Solana transaction problem

**Comment by rzgarespo** [comment]
> Error: Dynamic program error: missing signature for supplied pubkey: DKZDN1QM7ZGBfUZhQFPo233ccBxumjLGzFqKvMV43dzH
> 
> What is the solution for the above Solana transaction problem

You should point to json file containing strings like [137,195,22,164,..,552,152]

**Comment by rzgarespo** [comment]
> Hello, whenever I try to create an SPL token I get this error code:
> 
> error: missing signature for supplied pubkey: My Candy Machine Wallet Address>
> 
> Before that I already did this: solana config set -k My Candy Machine Wallet Address>
> 
> Its was confirmed.
> 
> My command: spl-token create-token To----------------------------------------------------------- --decimals 0
> 
> Anyone know where the error is? I can't get any further here.
> 
> I need this for whitelisting.
> 
> I hope someone can help me.

---------------------
//Recover existing Solana wallet
`solana-keygen recover -o my-token-wallet.json`
//if not create one: (backup and save the json file and words)
`solana-keygen new --outfile my-token-wallet.json`
---creates token address, recovery words and wallet key.
///Now buy some SOL (amount: 0.3 will be enough for paying creating and transaction fees) and send it to your newly created wallet
`spl-token create-token`
--creating token [your token address]

`spl-token create-account [your token address]`
--Creating account [token account for your token address]

//mint 21M token. run it again if you want to create more supply.
`spl-token mint [your token address] 21000000 [token account for your token address]`

//check it

`spl-token accounts`

///send token to another solana based wallet like phantom or etc

`spl-token transfer --fund-recipient --allow-unfunded-recipient [your token ACCOUNT address] 1000 [token reciver wallet address]`
