### ISSUE TITLE
Creating Candymachine error

### ISSUE THREAD

**Issue by Datakeysystems** [metaplex-foundation/metaplex#1636]
so upon running the command :
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
    ./assets

on my mac I keep getting the following.. below (absolute noob so would appreciate any guidance)

Error: Non-base58 character
    at Object.decode (/Users/apple/solana-nft/metaplex/js/node_modules/base-x/src/index.js:111:11)
    at new PublicKey (/Users/apple/solana-nft/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:56:30)
    at getCandyMachineV2Config (/Users/apple/solana-nft/metaplex/js/packages/cli/src/helpers/various.ts:150:9)
    at Command.<anonymous> (/Users/apple/solana-nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:99:38)

**Comment by hunlaca** [comment]
I have almost the same issue on windows when I running this command 'ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload' I get this error: error: required option '-cp, --config-path <string>' not specified

**Comment by Datakeysystems** [comment]
> 

I have been chasing my tail all day trying to figure this out.. talk about making myself feel stupid haha

**Comment by rcturner7** [comment]
Hi, has anyone figured out these errors.  I have been getting either both of those errrors. It's one or the other error everytime.

throw new Error('Non-base' + BASE + ' character') or the -cp, --config-path' not specified.

**Comment by samuelvanderwaal** [comment]
The non-base 58 character error means one of your public keys is invalid. Check your creators array in your JSON file to make sure you're using valid public key(s) for each creator in the array. 

For the `-cp` error you need to specify the path to the config file in your command. Check out docs for an example: https://docs.metaplex.com/candy-machine-v2/creating-candy-machine and make sure there's a valid `config.json` file at whatever path you're providing.

**Comment by frosty214** [comment]
Did you check version of candy-machine-v2-cli? That command for me looks like this:

`ts-node C:/Users/YOURNAME/~/metaplex/js/packages/cli/src//candy-machine-v2-cli.ts --version`


You need to actually get the paths of where `candy-machine-v2-cli.ts`, your keypair, and your config.json all are. This is what my upload command looks like after I do that:

`ts-node C:/Users/YOURNAME/~/metaplex/js/packages/cli/src//candy-machine-v2-cli.ts upload -e devnet -k C:/Users/YOURNAME/~/config/solana/devnet.json -cp C:/Users/YOURNAME/~/config.json -c temp ./Assets

Actually go to where those files are located, right from what drive, and use that path.

**Comment by rcturner7** [comment]
Thank you very much for the advice. Yeah it took me awhile, I finally
figured out. Somehow I changed the paths of files, I had finally got it to
work. Now I just don't have enough funds.

**Comment by samuelvanderwaal** [comment]
@Datakeysystems did you resolve this?

**Comment by paul2234** [comment]
I had the same issue and @samuelvanderwaal 's solution was correct. I had mistakenly put the incorrect public key in my config.json
