### ISSUE TITLE
assets upload error

### ISSUE THREAD

**Issue by hunlaca** [metaplex-foundation/metaplex#1637]
So upon running this command :
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload ./assets --env devnet --keypair ~/config/solana/devnet-test.json

I get this error message (platform:windows): 
error: required option '-cp, --config-path <string>' not specified

**Comment by SeanOverton** [comment]
It means you need to supply the -cp option with a path which you are clearly not in your command. https://docs.metaplex.com/candy-machine-v2/configuration#minimal-configuration shows the minimal config file required.

**Comment by d12tupac** [comment]
in the option -cp you need to specify the config.json path.
in your case it's not in the main folder, so check or paste the full path, for exemple  ( -cp /home/user/Desktop/metaplex/config.json)

**Comment by samuelvanderwaal** [comment]
See community answers above and checkout the docs. They provide examples of how to use the CLI commands.
