### ISSUE TITLE
Error: Breakdown not within 1% of 100! It is: 1

### ISSUE THREAD

**Issue by 21e8** [metaplex-foundation/metaplex#1639]
**Describe the bug**
The sample configs and the script have diverged, script excpects the sum of a trait to add up to 100 whereas the samples add up to 1.

**To Reproduce**
1. Use sample files from candy machine upload v2
2. Try to generate art
3. see error `Breakdown not within 1% of 100! It is: 1`

**Expected behavior**
Examples should work out of the box

**Additional context**
Some kind of tests would be nice, this repo has been broken every day since its inception.

**Comment by OguzhanUmutOzgur** [comment]
Could you find any solution? I used Metaplex's generator before and it worked just fine but having this error now. 

I tried to change the source code but it gets stuck...

**Comment by stegaBOB** [comment]
Tests would definitely be good. From what I understand the generative art stuff hasn't really been touched at all. It was a one time addition a while back if I'm not mistaken. Personally I have been directing people to use hashlips instead for generative art. I'm going to remove it from the repo. I believe its out of the scope of what our CLI should do. There are already great community tools that do this (i.e. hashlips).
