### ISSUE TITLE
No longer own master NFT after completing auction (unlimited supply NFT)

### ISSUE THREAD

**Issue by VictorReynolds** [metaplex-foundation/metaplex#164]
I initiated this test auction
https://store.tvvrband.com/#/auction/GtJNp5tyjhZmJaCk6JFEy1HmQKTbadgdcTqXM4LixVR5

After completion of the action, the winning bidder redeemed their reward after I settled the auction, they and now own the minted copy of the original master NFT
https://store.tvvrband.com/#/art/5yWq3E9rLf2RBs75TZmMKFw5vndmWhXEdZsENTAVtGkh

The store owner wallet no longer owns the master NFT:
https://store.tvvrband.com/#/art/3c3HAaFLmPunSZmuLSRo8sXZovHdpVmEuiT4B9h5HgZ8

This appears to be a bug, or at least if there is some step missing the fact that it's this unclear should be considered a bug.

**Comment by sultanpeyek** [comment]
It seems that's expected, because u sold the `NFT 0`.
Next time if you want to sell a copy edition, choose the limited edition auction and define how many NFTs for winners. That way, your master NFT won't missing from creator/seller wallet.

**Comment by sultanpeyek** [comment]
And what do you mean by **unlimited supply NFT**? is it possible on Metaplex at the moment? (asking the real question here hehe).

**Comment by VictorReynolds** [comment]
> And what do you mean by **unlimited supply NFT**? is it possible on Metaplex at the moment? (asking the real question here hehe).

Uploading pictures, but according to @bartosz-lipinski when I create an NFT, if I leave the "Maximum Supply" field blank when I upload an NFT, that should mint result in a master NFT from which I can mint unlimited copies.

> It seems that's expected, because u sold the `NFT 0`.
> Next time if you want to sell a copy edition, choose the limited edition auction and define how many NFTs for winners. That way, your master NFT won't missing from creator/seller wallet.

According to the "Open Edition" action type, I should be able to "Mint unlimited copies of a single master NFT". According to the UI I'm actually not able to list an NFT that has no maximum supply cap for a limited edition auction. You can see there that the auction did produce a numbered NFT distinct from the master edition, which I own as a result of winning the auction, but now the master edition has no owner.

**Comment by bhgames** [comment]
This isn't a bug. If you check the documentation, you'll find that the auction owns the master edition of the Open Edition until you, the auctioneer, go and redeem it out of the auction. You just need to go back to the auction and hit the Reclaim Items button.
