### ISSUE TITLE
No mint button 

### ISSUE THREAD

**Issue by doranring** [metaplex-foundation/metaplex#1640]
When I run the yarn start command my minting website appears completely black and no mint button shows. Anyone knows what might be causing it ?
![image](https://user-images.githubusercontent.com/93504460/150716596-3bd28351-c10e-4a02-989a-b9a421b256f7.png)

**Comment by everyoneandnoone** [comment]
Be sure that your env file in the root or public directory is no longer named env.example, and rather just .env

**Comment by stegaBOB** [comment]
If you are still having this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). Thanks.
