### ISSUE TITLE
Buying NFT error in metaplex dev version

### ISSUE THREAD

**Issue by mrchaos** [metaplex-foundation/metaplex#1642]
When I click the NFT purchase button, the error continues to occur as shown in the attached picture. Please tell me what is the reason.
Network:devnet
Solscan URL : https://solscan.io/tx/3YAApmooPku21xUPVofBYiMa7ZSJscEHvtUYJCiPY7YZHMCe9oy2aicnevwjDqC49A8TUyn4H6nrXkxavfehb1K1?cluster=devnet

![screencapture-solscan-io-tx-3YAApmooPku21xUPVofBYiMa7ZSJscEHvtUYJCiPY7YZHMCe9oy2aicnevwjDqC49A8TUyn4H6nrXkxavfehb1K1-2022-01-24-14_07_25](https://user-images.githubusercontent.com/5639226/150725655-900406e2-69d5-4e40-bead-e507bb55add1.png)

**Comment by khoiuit99** [comment]
![image](https://user-images.githubusercontent.com/38470288/150895170-df5187eb-8082-4e75-984c-440db5e3bfeb.png)

**Comment by mrchaos** [comment]
Thank you very much!!!
It works!!
