### ISSUE TITLE
Fix for 429 Too many requests using arweave-sol HERE!

### ISSUE THREAD

**Issue by PatrykXDD** [metaplex-foundation/metaplex#1643]
So,
arweave-sol uses bundlr to upload the images.
The bundlr node module has the default solana mainnet RPC hardcoded during uploads. That is why you get limited even with a custom RPC.

To fix this error, open:
`metaplex\js\packages\cli\node_modules\@bundlr-network\client\build\src\currencies\solana.js` and change line 14 to:
`return new web3.Connection("YOUR RPC URL", "confirmed");`

Unfortunately it seems like bundlr doesn't support a custom RPC so you will have to do this everytime you update your packages or try to use arweave-sol. At least for now...

**Comment by samuelvanderwaal** [comment]
The bundlr package has been updated so we'll bump version to fix this.

**Comment by quickvee** [comment]
@PatrykXDD

> The bundlr node module has the default solana mainnet RPC hardcoded during uploads. That is why you get limited even with a custom RPC.

Do you know where this is hardcoded? I found https://ssc-dao.genesysgo.net/ in https://github.com/Bundlr-Network/js-client/blob/main/src/node/currencies/index.ts but the error message in #1631 (also below) seems to be pointing to `rpcpool.com` instead.

```
{ "jsonrpc": "2.0", "error": { "code": 429, "message": "Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com." }, "id": 1 }
```

**Comment by samuelvanderwaal** [comment]
> @PatrykXDD
> 
> > The bundlr node module has the default solana mainnet RPC hardcoded during uploads. That is why you get limited even with a custom RPC.
> 
> Do you know where this is hardcoded? I found https://ssc-dao.genesysgo.net/ in https://github.com/Bundlr-Network/js-client/blob/main/src/node/currencies/index.ts but the error message in #1631 (also below) seems to be pointing to `rpcpool.com` instead.
> 
> ```
> { "jsonrpc": "2.0", "error": { "code": 429, "message": "Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com." }, "id": 1 }
> ```

If you pull the latest commit from master you shouldn't have these issues any more.

**Comment by quickvee** [comment]
> If you pull the latest commit from master you shouldn't have these issues any more.

Yes, thanks! Was just curious where the error was in the source code since I wasn't able to find it.

**Comment by fxxkk** [comment]
I have the latest version and the problem is still there can anyone guide me how to solve this ?
