### ISSUE TITLE
CM2 is still looking for creators in the metadata when its deprecated

### ISSUE THREAD

**Issue by ken-vat** [metaplex-foundation/metaplex#1647]
Latest metadata v1.1.0 says 

//@deprecated -> do not use - may be removed in a future release
    "creators": [
      {
        "address": "xEtQ9Fpv62qdc1GYfpNReMasVTe9YW5bHJwfVKqo72u",
        "share": 100
      }

If I dont have it in my metadata CM2 does not work

**upload was not successful, please re-run. Error: Creator address is missing
    at uploadV2 (/home/echeren/solana/metaplex/js/packages/cli/src/commands/upload.ts:129:15)
    at Command.<anonymous> (/home/echeren/solana/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:184:2**

My art generation code does not have creator field as its not needed. Is there a way to bypass creator field with CM2 ?

**Comment by samuelvanderwaal** [comment]
Token-metadata v1.1.0 does deprecate the creators in the external JSON metadata, but while the Solana program is deployed on mainnet we haven't rolled out updates to all our tools yet, so for now continue to use candy machine as normal.
