### ISSUE TITLE
Unable to initialize store in production but working locally on mainnet

### ISSUE THREAD

**Issue by MikeOfTheGalaxy** [metaplex-foundation/metaplex#1651]
I am able to get my store to see that it has already been initialized once ive pushed to production

I have initialized the store locally.  But it just spins perpetually in production, never finishes.

Wallet has Sol in it (enough for another initialization).  Wallet and site are both on mainnet.

If anyone has thoughts on how to get it to initialize please let me know

**Comment by colinchen4** [comment]
I guess you need to enforce https in both the github page and the domain host.

**Comment by MikeOfTheGalaxy** [comment]
This worked. Thank you.
