### ISSUE TITLE
No unverified metadata

### ISSUE THREAD

**Issue by victorguima12** [metaplex-foundation/metaplex#1652]
![image](https://user-images.githubusercontent.com/73203416/151008312-5dfd3da7-e0b6-4c61-91d9-188a11be0d22.png)

![image](https://user-images.githubusercontent.com/73203416/151008351-cac50268-7b33-43d5-bd87-832f17de60ec.png)

When i run the metaboss sign all -k -c     with or without --v2 in the end, in both scenarios is says that theres no unverified metadata, but as you can see in the solana explorer still shows as unverified, even when i used this command for the first time it was the same response

**Comment by samuelvanderwaal** [comment]
You're probably trying to sign with the wrong keypair or on the wrong cluster, but this isn't the Metaboss repo. Metaboss is a community project not a Metaplex one. Please open an issue at github.com/samuelvanderwaal/metaboss.
