### ISSUE TITLE
Mint Button "not clickable"

### ISSUE THREAD

**Issue by Chrissyticky** [metaplex-foundation/metaplex#1655]
**Minting Error**
After executing the following command metaplex\js\packages\candy-machine-ui>yarn start

 I get the attached error:
![error](https://user-images.githubusercontent.com/98180202/151105946-2c54ed3c-b391-478c-9861-304558a83548.png)

I've tried removing all the dependencies and reinstalling but it hasn't worked. 
I was using Edge browser but switched to chrome and still, the issue is the same..

My env file is filled out correctly and so is my config file.

**Comment by Artistic-alpha** [comment]
are you using the latest version of candy-machine-ui?

**Comment by kevinh1534** [comment]
Having the same issue @Chrissyticky

**Comment by frosty214** [comment]
What is your GoLiveDate in configuration?

If it is set to "Null", that's probably why. Try setting a past date (ex. "25 Dec 2021 00:00:00 GMT"), and then run the update command:

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts update_candy_machine \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example

**Comment by Chrissyticky** [comment]
> What is your GoLiveDate in configuration?
> 
> If it is set to "Null", that's probably why. Try setting a past date (ex. "25 Dec 2021 00:00:00 GMT"), and then run the update command:
> 
> ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts update_candy_machine -e devnet -k ~/.config/solana/devnet.json -cp config.json -c example

![error](https://user-images.githubusercontent.com/98180202/151437043-209e5f8f-ae73-45c2-a99d-a8ce836f7f26.png)
 I've done this 15 times already.. still no luck.. I've even restarted the process from scratch and met with the same issue.

**Comment by Chrissyticky** [comment]
> Having the same issue @Chrissyticky

Were you able to resolve it?

**Comment by Chrissyticky** [comment]
> are you using the latest version of candy-machine-ui?

I would assume so.. I downloaded the latest version. I've tried this process multiple times. Still no luck. :(

**Comment by kevinh1534** [comment]
> > Having the same issue @Chrissyticky
> 
> Were you able to resolve it?

No, I also have the mint date set correctly. Still trying to troubleshoot.

**Comment by kevinh1534** [comment]
@Chrissyticky found the error. the .env rpc host needs to be set to 
REACT_APP_SOLANA_RPC_HOST=https://api.mainnet-beta.solana.com
instead of
REACT_APP_SOLANA_RPC_HOST=https://explorer-api.mainnet-beta.solana.com

**Comment by Chrissyticky** [comment]
> @Chrissyticky found the error. the .env rpc host needs to be set to REACT_APP_SOLANA_RPC_HOST=https://api.mainnet-beta.solana.com instead of REACT_APP_SOLANA_RPC_HOST=https://explorer-api.mainnet-beta.solana.com

Mine is 

REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://api.devnet.solana.com

I'm on devnet.. it didn't work for me  :(

**Comment by Chrissyticky** [comment]
> @Chrissyticky found the error. the .env rpc host needs to be set to REACT_APP_SOLANA_RPC_HOST=https://api.mainnet-beta.solana.com instead of REACT_APP_SOLANA_RPC_HOST=https://explorer-api.mainnet-beta.solana.com

@kevinh1534  How you checked on devnet or had this issue on devnet?

**Comment by jslopezg** [comment]
I have the exact same problem;... Im on mainnet

**Comment by margarita26** [comment]
update REACT_APP_CANDY_MACHINE_ID with candyMachine string from cache devnet-example.json file, **and only then** run `yarn install && yarn start`

**Comment by joe-git-dev** [comment]
im on mainnet and seem to have the correct rpc host but still getting mint not clickable. any ideas?
<img width="507" alt="Screen Shot 2022-01-30 at 10 58 28 PM" src="https://user-images.githubusercontent.com/51798204/151737092-d65a978f-1804-4771-b30c-94
<img width="581" alt="Screen Shot 2022-01-30 at 10 52 50 PM" src="https://user-images.githubusercontent.com/51798204/151737095-bb6079c1-59c8-48bf-b269-d972a0ae5d09.png">
2e460fb2f8.png">

**Comment by BHALEYART** [comment]
I was able to fix this on the local host by changing the RPC_HOST=https://api.mainnet-beta.solana.com
also ran an update on CMv2 and new yen build of React App.

But unfortunately about hosting on the web the issue magically returns...

**Comment by stegaBOB** [comment]
> 

This is most likely the issue.

**Comment by jlopezg93** [comment]
My solution to the mint button not working was that I needed to send the yarn build && yarn start command and after that the mint button worked

**Comment by victorajayi** [comment]
@BHALEYART you're right as soon as you host the build on a web server the mint button automatically stops working

**Comment by BHALEYART** [comment]
Ok so this is is RESOLVED:

Do not use Devnet, or Mainnet Api for the RPC section.

My issue: 
Quiknode RPC I bought wasn't actually working even though it was connected.
using solana mainnet endpoint only worked on Local host but would not on vercel.

To fix I used this RPC endpoint: https://ssc-dao.genesysgo.net

Other common issues: 

-Not using an RPC period.
-On the wrong api network (devnet/mainnet).
-People forget to remove "< >" and simply put their config from the cache inside the brackets.

Remember if you solve something to come back and tell others or we are part of a vicious cycle.

**Comment by frosty214** [comment]
I've also only had success using Genesys.go nodes. Best part is, they're free! Really smart guys over at their Discord.
