### ISSUE TITLE
Cant install yarn in js

### ISSUE THREAD

**Issue by BORRODA8** [metaplex-foundation/metaplex#1656]
![Screenshot_5](https://user-images.githubusercontent.com/93973414/151143859-4caddaf1-1524-4027-93ec-323f9eac63d4.png)

**Comment by frosty214** [comment]
I would try installing yarn globally on your machine. Open a new terminal and run yarn -g install

**Comment by ZayadZarrani** [comment]
I have this problem too

**Comment by ZayadZarrani** [comment]
thank is work

**Comment by stegaBOB** [comment]
This issue should be fixed as of #1673 I think.
