### ISSUE TITLE
Can't add metaplex dependencies.

### ISSUE THREAD

**Issue by zixerton** [metaplex-foundation/metaplex#1659]
hey guys, I keep getting an error after the metaplex installation, after I'm trying to install the dependencies. Here's the error:

jacklondon@Taysums-MacBook-Air solana-nft % yarn add /Users/jacklondon/solana-nft/metaplex/js
yarn add v1.22.17
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
error Can't add "": invalid package version "".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by knottwill** [comment]
run: yarn install --cwd /Users/jacklondon/solana-nft/metaplex/js

I can see you are on a Mac so this command may produce an error related to canvas (as it did for me). In this case you will need to install canvas from source:

https://github.com/Automattic/node-canvas/wiki/Installation%3A-Mac-OS-X

To do this, run: brew install pkg-config cairo pango libpng jpeg giflib librsvg
(if you have homebrew that is)

**Comment by zixerton** [comment]
> yarn install --cwd /Users/jacklondon/solana-nft/metaplex/js

Damn man that helped, much appreciated!

**Comment by ZayadZarrani** [comment]
what about the windows how will works
