### ISSUE TITLE
Cant Upload in Candymachine v2 

### ISSUE THREAD

**Issue by YoungSplix** [metaplex-foundation/metaplex#1665]
ARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type \$Recycle.Bin
WARNING: Skipping unsupported file type \$SysReset
WARNING: Skipping unsupported file type \$WinREAgent
WARNING: Skipping unsupported file type \Documents and Settings
WARNING: Skipping unsupported file type \DumpStack.log
WARNING: Skipping unsupported file type \DumpStack.log.tmp
WARNING: Skipping unsupported file type \hiberfil.sys
WARNING: Skipping unsupported file type \OneDriveTemp
WARNING: Skipping unsupported file type \pagefile.sys
WARNING: Skipping unsupported file type \PerfLogs
WARNING: Skipping unsupported file type \Program Files
WARNING: Skipping unsupported file type \Program Files (x86)
WARNING: Skipping unsupported file type \ProgramData
WARNING: Skipping unsupported file type \Recovery
WARNING: Skipping unsupported file type \solana-install-tmp
WARNING: Skipping unsupported file type \swapfile.sys
WARNING: Skipping unsupported file type \System Volume Information
WARNING: Skipping unsupported file type \Users
WARNING: Skipping unsupported file type \Windows
Beginning the upload for 0 (img+json) pairs
started at: 1643357760750
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\alish\OneDrive\Desktop\baaba\~\metaplex\js\packages\cli\src\commands\upload.ts:100:24)
    at Command.<anonymous> (C:\Users\alish\OneDrive\Desktop\baaba\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:190:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by stegaBOB** [comment]
You haven't provided enough information to figure out what went wrong. If you are still having this issue, please reopen another issue that follows our new issue template. Thanks.
