### ISSUE TITLE
Can't install Yarn 

### ISSUE THREAD

**Issue by GenMusic** [metaplex-foundation/metaplex#1668]
I keep getting the following error when trying to install Yarn in JS>

![image](https://user-images.githubusercontent.com/98533777/151584047-16c72299-98c2-4e9b-9e53-1a98917b1462.png)

**Comment by GenMusic** [comment]
Getting this after yarn build now

![image](https://user-images.githubusercontent.com/98533777/151601311-9212860b-dd6f-4870-b779-4e62998e1d00.png)

**Comment by goriunov** [comment]
It is known issue here is PR fix for that:

https://github.com/metaplex-foundation/metaplex/pull/1673
