### ISSUE TITLE
 error: required option '-cp, --config-path <string>' not specified

### ISSUE THREAD

**Issue by Secretbeef** [metaplex-foundation/metaplex#1675]
Whenever I go to use 

ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload ./assets --env mainnet-beta --keypair -o ~/.config/solana/mainnet-beta.json

I get this error. Cannot find a fix

error: required option '-cp, --config-path <string>' not specified. 

I've found the line of code in candymachine where the error is occuring, Im just not sure what to do with it.

**Comment by archangelcrypto** [comment]
I'm also having the same issue.

**Comment by joe-git-dev** [comment]
i had this same issue from watching a youtube video but then i used this command instead from candy-machine-v2 docs and it worked 
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
    ./assets

**Comment by stegaBOB** [comment]
You were missing an option. Many YouTube tutorials are out of date. Please check our Candy Machine v2 docs at https://docs.metaplex.com
