### ISSUE TITLE
[Mainnet] Throwing custom program error: 0x177a during mint

### ISSUE THREAD

**Issue by digz6666** [metaplex-foundation/metaplex#1678]
I created collection with 100 NFTs and the its throwing following error on 73th mint, first 72 mint ran successfully.
I tried 3 times and all of them are failed.
I have 9+ SOL in my wallet.

```
REST error for 5tu7JNSVnEakTY1eEFwYfQYShK86DfBqoS4XxJjShVGoVaLo6S4JsjWpiLHFnzLdmn3pAbEfRHeBJ7mPJSuAnQm1 {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: { InstructionError: [ 4, [Object] ] },
  slot: 118550870,
  status: { Err: { InstructionError: [Array] } }
}
Timeout Error caught { InstructionError: [ 4, { Custom: 6010 } ] }
metaplex\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x177a
    at sendSignedTransaction (metaplex\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (metaplex\js\packages\cli\src\helpers\transactions.ts:59:26)
    at async mintV2 (metaplex\js\packages\cli\src\commands\mint.ts:344:5)
    at async mintToken (metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:732:18)
    at async Command.<anonymous> (metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:741:5)
```

Transaction link on solscan: https://solscan.io/tx/3oWCFXBA499jLxA4qqiSXFVzKGzuh3jeb1W97ZLKpdPfhciPp1NkH13oKdci3Zu3rk8vBPxDnriwpZ8zpRXSSBSy

**Comment by Khushhal23** [comment]
Run git pull in your metaplex foder, then try again also, try using a custom rpc

**Comment by stegaBOB** [comment]
The 0x177a error means that the candy machine is empty. Someone else must have minted the other NFTs.

**Comment by imentus-rahul** [comment]
![Screenshot from 2022-02-14 20-14-09](https://user-images.githubusercontent.com/86224847/153999085-3aae7601-d7b0-4272-b3d5-d3bdaf7b82e1.png)

Repo: MPL>>Fixed-Price-Sale
Error while trying to run all test cases on devnet instead of localnet.
Error: _Error processing Instruction 0: custom program error: 0x177a._

**Comment by SwimmingPigLuvr** [comment]
> The 0x177a error means that the candy machine is empty. Someone else must have minted the other NFTs.

i had that error after running mint_one_token. funny think is 1 token made it into my wallet and the rest ended up in random wallets. is that nromal. out of the 10 nfts i minted 6 went to a wallet that was active.

**Comment by kingsaket** [comment]
Dear All ,  I am still gettint this error during minting . I am on main-net using candymachinev2 and  enough SOL in wallet . Please helo
REST error for 2fhdxjC7La5i32BrJMApbCmtwzZpCq1czvp8J3PC1tc5Lk9j7Qf8Bj9gSh5YmHo6eEH8UfjUTCMmMKVLebS21738 {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: { InstructionError: [ 4, [Object] ] },
  slot: 124852927,
  status: { Err: { InstructionError: [Array] } }
}
Timeout Error caught { InstructionError: [ 4, { Custom: 6010 } ] }
Rejected via websocket { InstructionError: [ 4, { Custom: 6010 } ] }
C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x177a
    at sendSignedTransaction (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:59:26)
    at async mintV2 (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\commands\mint.ts:344:5)
    at async Command.<anonymous> (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:840:16)

**Comment by digz6666** [comment]
> Dear All , I am still gettint this error during minting . I am on main-net using candymachinev2 and enough SOL in wallet . Please helo REST error for 2fhdxjC7La5i32BrJMApbCmtwzZpCq1czvp8J3PC1tc5Lk9j7Qf8Bj9gSh5YmHo6eEH8UfjUTCMmMKVLebS21738 { confirmationStatus: 'processed', confirmations: 0, err: { InstructionError: [ 4, [Object] ] }, slot: 124852927, status: { Err: { InstructionError: [Array] } } } Timeout Error caught { InstructionError: [ 4, { Custom: 6010 } ] } Rejected via websocket { InstructionError: [ 4, { Custom: 6010 } ] } C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136 throw new Error( ^ Error: Transaction failed: Custom program error: 0x177a at sendSignedTransaction (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136:19) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async sendTransactionWithRetryWithKeypair (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:59:26) at async mintV2 (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\commands\mint.ts:344:5) at async Command. (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:840:16)

Means bots minted your tokens from your candy machine. You should set null for goLiveDate so that only you can mint. Or you can use whitelist settings.

**Comment by digz6666** [comment]
> > The 0x177a error means that the candy machine is empty. Someone else must have minted the other NFTs.
> 
> i had that error after running mint_one_token. funny think is 1 token made it into my wallet and the rest ended up in random wallets. is that nromal. out of the 10 nfts i minted 6 went to a wallet that was active.

Bots minted your tokens. Read above comment.

**Comment by stegaBOB** [comment]
Your candy machine is empty. That's what the 177a error is

**Comment by kingsaket** [comment]
i modfied the config file to have "goLiveDate": ""  and  added  "whitelistMintSettings":{"mint" : "AXXXXXXXXXXXXXXXXXXXX"}
i am still getting the error:

REST error for 5uBSEN5eLNvjqVay54zNZBWFrPVNB8ksX2nNgNqyryZbw2zTWig3AnB2bvvCBMubJtbvRa3eb6Ksa7xHybEM9Fz5 {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: { InstructionError: [ 4, [Object] ] },
  slot: 124864450,
  status: { Err: { InstructionError: [Array] } }
}
Timeout Error caught { InstructionError: [ 4, { Custom: 6010 } ] }
C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x177a
    at sendSignedTransaction (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\helpers\transactions.ts:59:26)
    at async mintV2 (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\commands\mint.ts:344:5)
    at async Command.<anonymous> (C:\Raja\BlockChain\Solana\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:840:16)
