### ISSUE TITLE
Hi having the same issue but my goLiveDate is not null.

### ISSUE THREAD

**Issue by joe-git-dev** [metaplex-foundation/metaplex#1679]
Hi having the same issue but my goLiveDate is not null.

_Originally posted by @PixelInvaderz in https://github.com/metaplex-foundation/metaplex/issues/1459#issuecomment-1007988823_

did you ever figure this out? also not able to mint but i do have a go live date. just seeing a greyed out mint button

**Comment by joe-git-dev** [comment]
<img width="581" alt="Screen Shot 2022-01-30 at 10 52 50 PM" src="https://user-images.githubusercontent.com/51798204/151736667-a25b4d81-1670-4650-ae77-7bd42014c450.png">
image for reference

**Comment by JasonJvV** [comment]
Hey Joe - did you manage to resolve this? Im having the same issue. my go live date is not null and is in the past.Not sure what the issue is. Cheers

**Comment by nancyyyy333** [comment]
same issue here as well. Any solutions? Thanks:)
