### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by Yasoaa** [metaplex-foundation/metaplex#1682]
So I'm trying to upload my assets folder but I've been getting this error for a while now, I've tried so much but I just cant get this to work. Any help would be appreciated
![b2785c137934d2b6c37322d1d6edf88a](https://user-images.githubusercontent.com/98762606/151832679-7b9e627d-6a03-414f-86c8-e81b6ecde939.png)

**Comment by Yasoaa** [comment]
PS C:\Users\Cameron\~\metaplex> ts-node C:\Users\Cameron\~\metaplex\js\packages\cli\src/candy-machine-v2-cli.ts upload -e devnet -k C:\Users\Cameron\~\metaplex\~\.config\solana\devnet-cozypandatesting.json -cp C:\Users\Cameron\~\config.json -c example C:\Users\Cameron\~\metaplex\assets

wallet public key: Bju5gfeuL4dM9kCbj1B7mosFnbS52mKMwWTe4M52J2xt
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type C:\Users\Cameron\~\metaplex\assets\images
WARNING: Skipping unsupported file type C:\Users\Cameron\~\metaplex\assets\json
Beginning the upload for 15 (img+json) pairs
started at: 1643646093248
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\Cameron\~\metaplex\js\packages\cli\src\commands\upload.ts:97:24)
    at Command.<anonymous> (C:\Users\Cameron\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by Khushhal23** [comment]
@Yasoaa You actually have to create a folder assets with the pngs and json file in it, in your case you have the files i different folders i.e. images, jsons, so just pull all files out these folders, and put them in a new folder, then upload giving the oath of the new folder

**Comment by Yasoaa** [comment]
@Khushhal23 I actually can't thank you enough, I so much I spent 5 hours trying this yesterday and because of you it's now working so thank you.

**Comment by Khushhal23** [comment]
:)
