### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by Doughp** [metaplex-foundation/metaplex#1685]
Hello, hope everyone is doing well.

I am getting errors when trying to run the upload command for metaplex. It seems as if it is trying to upload my desktop files. I honestly have no clue why. (No this was not my first error I have been messing with metaplex for the last 5 hours from install to now, configuring with all types of errors). In VS code I am not even on the desktop directory, and all my option commands have their paths specified, as you can see in the screenshot the command given and the errors received.

 When I use the copy from the docs it says i must specify the options so I just stuck them all in one line instead.
![image](https://user-images.githubusercontent.com/94391490/151889387-e28dbffd-cb89-4034-897d-84c98cd8d1f0.png)

**Comment by Khushhal23** [comment]
Remove all \ from the command, if that doesn't work then also try using ./ for paths instead of ~/

**Comment by Doughp** [comment]
Removing the \ seems to work, but I am missing some image files so I am getting an error but it noticed that so I think that worked. Thank you!

> Remove all \ from the command, if that doesn't work then also try using ./ for paths instead of ~/
