### ISSUE TITLE
[Feature]: Way to connect to off-chain storage like smart contracts for ethereum

### ISSUE THREAD

**Issue by Doughp** [metaplex-foundation/metaplex#1690]
### Which package is this feature request for?

candy machine cli

### Feature

I don't know if this is already an option but I am not finding any documentation on it and I have been looking. What I am saying is I would like to be able to upload metadata and images to say IPFS and connect that as a baseURI or something similar for SOLANA NFTs. I am trying to upload 20,000 assets using the command line interface, and it is a major pain. I have been running the code over and over and over for 4 1/2 hours and I still have 18.600 left.

### Ideal solution or implementation

Maybe make something like Remix IDE for Solana, I don't develop for solana or anything so I have no clue with rust or anything. I know MetaPlex doesn't even create smart contracts it has some when we deploy or something I don't know but if you have deployed on Ethereum network you know what I mean. 

### Alternative solutions or implementations

Connect IPFS CID as "image": attribute and when it mints generates ipfs://<hash>/1.json and the image attribute states "image": ipfs://<hash>/1.png

**Comment by Doughp** [comment]
Supposed to be "<hash>" inside ipfs and /1.(png/json)

**Comment by Doughp** [comment]
> Supposed to be "" inside ipfs and /1.(png/json)

< /hash\>

**Comment by stegaBOB** [comment]
Thanks for the great feedback! This is definitely something we would like to do. NFTs on Solana work a bit differently from those on Eth. Each NFT has its own full URL. What we would have to do is have a script that generates the cache file from a baseURI, which users would then only have to upload on chain (and not to arweave/ipfs directly from the cli).

**Comment by Doughp** [comment]
> Thanks for the great feedback! This is definitely something we would like to do. NFTs on Solana work a bit differently from those on Eth. Each NFT has its own full URL. What we would have to do is have a script that generates the cache file from a baseURI, which users would then only have to upload on chain (and not to arweave/ipfs directly from the cli).

Is there a better way currently to upload 20k images and metadata?

If there is a documentation on it you could link if this is too loaded of a question, but what is the reason behind that, why it is not able to just generate like a smart contract, goes off of the minted token being 1,2,3, or if randomized in the array and then adds the token at the end of the hash/cid with .json suffix.

**Comment by stegaBOB** [comment]
https://github.com/CalebEverett/arloader That repo is great for uploading. From there it will give you a partial cache file that you can use. One of the big differences is the amount of data that is actually stored on chain. For eth NFTs, the only thing stored on chain is the token ID and a single URI. On Solana, each NFT stores its name, symbol, creators, and the full link to the json file.

**Comment by Doughp** [comment]
> https://github.com/CalebEverett/arloader That repo is great for uploading. From there it will give you a partial cache file that you can use. One of the big differences is the amount of data that is actually stored on chain. For eth NFTs, the only thing stored on chain is the token ID and a single URI. On Solana, each NFT stores its name, symbol, creators, and the full link to the json file.

Thank you I will try to use that right now, currently have 17,400 left to go haha.  That's interesting, thank you for your help.

**Comment by Doughp** [comment]
So, I am supposed to upload these to Arweave and then download a cache file with im assuming their links and then input that into my metaplex folder and it will use those links for the candy machine?

**Comment by samuelvanderwaal** [comment]
> So, I am supposed to upload these to Arweave and then download a cache file with im assuming their links and then input that into my metaplex folder and it will use those links for the candy machine? @stegaBOB

Arloader supports the Metaplex cache format. Read through the README and you'll see this:

![Selection_638](https://user-images.githubusercontent.com/1684605/152211408-60b71b9f-fffb-4bd9-8305-78d571c35659.png)

So it creates the data you need to update the cache file before running `upload` with the candy machine CLI.
