### ISSUE TITLE
Grey Mint Button on Custom Domain

### ISSUE THREAD

**Issue by everyoneandnoone** [metaplex-foundation/metaplex#1694]
### Which package is this bug report for?

candy machine ui

### Issue description

Having a bit of an issue with a minting website being hosted on a custom domain via Netlify.

The first Netlify subdomain site that the "yarn build, netlify deploy --prod" deploys to (example.netlify.app) works flawlessly. The "connect wallet" button is functional, and the presale timer works correctly. Users that hold the proper SPL tokens can mint early.

However, the custom domain (google domain of the .art type) simply has a greyed out "Mint" button after the user's wallet is connected. The site is fully functional otherwise. The custom DNS servers have been routed through Google Domains, the HTTPS protocol is active, but it appears that something is holding the custom domain back from being fully functional. Is it possible that the minter can only be active on one website at a time?

Tried to create a CNAME file as well as a _redirect file in my root directory with no apparent luck. Any thoughts are appreciated!

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Did you set environment variables in netlify?

**Comment by everyoneandnoone** [comment]
> Did you set environment variables in netlify?

Yes. The minter works as intended on the Netlify subdomain. (Can mint and receive NFTs.)

**Comment by BHALEYART** [comment]
Same issue. If I deploy local host it works fine, I can even mint. As soon as I yarn build and gitpush to vercel it stops working.
Even adjusted to custom .env settings in vercel and nothing.

**Comment by everyoneandnoone** [comment]
In my case, I tried doing a netlify.toml file in the public directory in the following format:

[[redirects]]
  from = "https://somenetlifysite.netlify.app"
  to = "https://mycustomdomain.com"
  status = 301
  force = true

This correctly redirects the Netlify subdomain to my custom domain, but it would appear that the minter is still active at the now unreachable Netlify subdomain. Crossing that off the list and looking into some environment variables.

**Comment by stegaBOB** [comment]
I'm not too familiar with Netlify unfortunately. Since it works on localhost I'd be inclined to believe it's an issue on the Netlify end. Let us know if you find a fix! It might be worth asking in our [Discord](https://discord.gg/metaplex).

**Comment by victorajayi** [comment]
@stegaBOB @everyoneandnoone I'm having a similar issue to this also. Everything is working fine when I deployed the build to local host. The mint butting is also working fine when I deployed it on netlify app, but as soon as i added a custom domain to the netlify app the mint button stopped working and stayed grey after connecting to it.

**Comment by everyoneandnoone** [comment]
> 

I haven't found a fix yet. I am still under the impression that since the react app is already running on the netlify subdomain, it (for whatever technical reason) cannot be running on a separate domain concurrently. Will update if I end up finding a solution!

**Comment by victorajayi** [comment]
@everyoneandnoone yes pls do

**Comment by CryptoPique** [comment]
i have the same problem, locally it works, when i build it and add it to custom domain it doesn't work anymore. Seems to be a problem fo Security/permissions of the rpc. possible ?

**Comment by BHALEYART** [comment]
Ok so this is is RESOLVED:

Do not use Devnet, or Mainnet Api for the RPC section.

My issue:
Quiknode RPC I bought wasn't actually working even though it was connected.
using solana mainnet endpoint only worked on Local host but would not on vercel.

To fix I used this RPC endpoint: https://ssc-dao.genesysgo.net/
You only need to save edits to the file and use "yarn build" to fix the issue.
New repository push, new vercel deployment and you're good to go.

Other common issues:

-Not using an RPC period.
-On the wrong api network (devnet/mainnet).
-People forget to remove "< >" and simply put their config from the cache inside the brackets.

Remember if you solve something to come back and tell others or we are part of a vicious cycle.

**Comment by everyoneandnoone** [comment]
> Ok so this is is RESOLVED:
> 
> Do not use Devnet, or Mainnet Api for the RPC section.
> 
> My issue: Quiknode RPC I bought wasn't actually working (they suck) even though it was connected. using solana mainnet endpoint only worked on Local host but would not on vercel.
> 
> To fix I used this RPC endpoint: https://ssc-dao.genesysgo.net/ You only need to save edits to the file and use "yarn build" to fix the issue. New repository push, new vercel deployment and you're good to go.
> 
> Other common issues:
> 
> -Not using an RPC period. -On the wrong api network (devnet/mainnet). -People forget to remove "< >" and simply put their config from the cache inside the brackets.
> 
> Remember if you solve something to come back and tell others or we are part of a vicious cycle.

Thanks for this. I was actually able to fix mine just by changing the RPC_HOST field in the .env file to the alternate mainnet one, https://solana-api.projectserum.com, and can confirm it is now working in both instances - the Netlify subdomain as well as the custom domain. Just a swap of RPC_HOST URLS, another yarn build and deploy to the Netlify side, and viola! 

If anyone else still has the same issue, it would be worth checking into other custom RPC nodes as mentioned by @BHALEYART. Thank you for the fix, fren!
