### ISSUE TITLE
[Feature]: Make candy-machine-ui its own submodule, allowing forking

### ISSUE THREAD

**Issue by mPaella** [metaplex-foundation/metaplex#1695]
### Which package is this feature request for?

candy machine ui

### Feature

I would like to fork `candy-machine-ui` allowing me to make my own changes while also keeping it up to date with metaplex's changes, without having to clone the whole `metaplex` repo.

### Ideal solution or implementation

Make `candy-machine-ui` its own git submodule, or make it its repo

**Comment by 21e8** [comment]
pls repo not git module
