### ISSUE TITLE
[Bug]: Immediately sold out.

### ISSUE THREAD

**Issue by GottliebGlob** [metaplex-foundation/metaplex#1696]
### Which package is this bug report for?

candy machine ui

### Issue description

Hi guys. I have such a problem. I've  successfully  upload 10 nfts to mainnet-beta (in devnet everything is working fine) then I minted one of them just to test. And it successfully minted. But then website refreshed and there was inactive sold out button instead of mint button. The commands I used are listed below. I would like to understand where the other 9 nft disappeared to. I will be glad for any help. 
Thank you for your time)
![image](https://user-images.githubusercontent.com/53971863/152125673-df0be2ee-645b-49b7-a4c8-4a2853302313.png)

### Command

```shell
npx ts-node C:/Users/MyUser/Data/Projects/solana/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k keypair.json -cp config.json ./assets

npx ts-node C:/Users/MyUser/Data/Projects/solana/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts verify_upload -e mainnet-beta -k keypair.json
```

### Operating system

Windows 10 

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by GottliebGlob** [comment]
Forgot to mention. I use netlify as hosting

**Comment by goriunov** [comment]
The price is too low, it is possible that it got completely bought by the bots.

**Comment by stegaBOB** [comment]
With a price that low, bots just mint if you don't have a captcha set up.
