### ISSUE TITLE
[Bug]: Cannot withdraw funds of candy machine on mainnet-beta

### ISSUE THREAD

**Issue by Kendrixdev** [metaplex-foundation/metaplex#1697]
### Which package is this bug report for?

candy machine cli

### Issue description

Hello, I have been retrying for one hour and still can't get the candymachine withdrawed... Always getting this error

### Command

```shell
ts-node ./~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts withdraw -e mainnet-beta -k ./~/.config/AFC4FpBPaBFzx1DyQbh6cJQEXe7Ga6CQbLMhwgjj4KYR.json
```

### Relevant log output

```shell
wallet public key: AFC4FpBPaBFzx1DyQbh6cJQEXe7Ga6CQbLMhwgjj4KYR
Total Number of Candy Machine Config Accounts to drain 1
1.67640648 SOL locked up in configs
WARNING: This command will drain ALL of the Candy Machine config accounts that are owned by your current KeyPair, this will break your Candy Machine if its still in use
Rejecting for timeout...
Timeout Error caught { timeout: true }
Withdraw has failed for config account 2va6XAGAZGur2TuWU2vEpXSKvypi6SLhLRYUNL1mEbkd Error: Timed out awaiting confirmation on transaction
Congratulations, 0 config accounts have been successfully drained.
Now you kinda rich, please consider supporting Open Source developers.
```

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Are you still having this issue?

**Comment by Randy808** [comment]
Looks like the funds were able to get drained from the account on Feb 5th: https://explorer.solana.com/tx/5cToDDY3Hvx9egp6twToJDtj3Y2HtnQNzPppyQcukkQk9a1dKx3TmsLmqG1GjBNC6ebtgM3oeK73nttwvwR1HR6A

**Comment by stegaBOB** [comment]
This was likely an RPC issue or a Solana network issue at the time. Closing this issue now.
