### ISSUE TITLE
[Bug]: Mint_multiple_tokens error

### ISSUE THREAD

**Issue by newjxmaster** [metaplex-foundation/metaplex#1701]
### Which package is this bug report for?

candy machine cli

### Issue description

REST error for HQzgfvc53QA1qCpf8aSNRgnvVWv5VnB8miJEmd3xoWYwFY8sJz3Keg8ASCMyuXnQDsc45WXbTXAC6wipEiqTeiT {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: { InstructionError: [ 4, [Object] ] },
  slot: 119148289,
  status: { Err: { InstructionError: [Array] } }
}
Timeout Error caught { InstructionError: [ 4, { Custom: 6019 } ] }
Rejected via websocket { InstructionError: [ 4, { Custom: 6019 } ] }
C:\CRYPTO\SOLANA\MFT\NFTmetaplex\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x1783
    at sendSignedTransaction (C:\CRYPTO\SOLANA\MFT\NFTmetaplex\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)      
    at async sendTransactionWithRetryWithKeypair (C:\CRYPTO\SOLANA\MFT\NFTmetaplex\js\packages\cli\src\helpers\transactions.ts:59:26)
    at async mintV2 (C:\CRYPTO\SOLANA\MFT\NFTmetaplex\js\packages\cli\src\commands\mint.ts:344:5)
    at async mintToken (C:\CRYPTO\SOLANA\MFT\NFTmetaplex\js\packages\cli\src\candy-machine-v2-cli.ts:735:18)
    at async Command.<anonymous> (C:\CRYPTO\SOLANA\MFT\NFTmetaplex\js\packages\cli\src\candy-machine-v2-cli.ts:744:5)

### Command

```shell
ts-node js\packages\cli\src\candy-machine-v2-cli.ts mint_multiple_tokens -e mainnet-beta -k ~/.config/solana/NFT.json -cp js\packages\cli\config.json -c example --number 232
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by gotys** [comment]
I have exact same problem.
My environment:

Candy Machine v2
Using DevNet
Running inside a docker ( port 443 opened )

**Comment by newjxmaster** [comment]
Hopefully someone will give us a solution 😀

**Comment by halaprix** [comment]
@newjxmaster  you can't mint from CLI with gatekeeper turned on.

You get this error: 
``Error: Transaction failed: Custom program error: 0x1783``

This is the error description:
``"1783"    => "GatewayTokenMissing: Missing gateway token when required",``

**Comment by newjxmaster** [comment]
Thank you, how do I deactivate the gatekeeper?

**Comment by halaprix** [comment]
in `config.json` => gatekeeper: null => `update_candy_machine`

**Comment by newjxmaster** [comment]
> in `config.json` => gatekeeper: null => `update_candy_machine`

thank you i'll try..

**Comment by stegaBOB** [comment]
Closing this issue.
