### ISSUE TITLE
Remove creator from storefront

### ISSUE THREAD

**Issue by RolandPixeldust** [metaplex-foundation/metaplex#1703]
### Which package is this feature request for?

storefront

### Feature

Removing Creator from storefront
There is an option to add creators but no clear directive on how to remove them. 
there is an "activate" toggle option, however this doesn't seem hide or remove any prior Addresses added

![creators](https://user-images.githubusercontent.com/67436086/152414096-1dcb1df4-5839-4807-af84-7ffc078077c0.png)
 

### Ideal solution or implementation

Add a clear remove button similar to Add button that removes any record of the address

### Alternative solutions or implementations

Add a way to hide antiquated addresses 

### Other context

This is a very critical feature, sometimes people make mistakes, people depart the project or wallets become compromised

**Comment by stegaBOB** [comment]
It does actually remove the addresses. It just remains in the admin panel as a UI thing since you added it in the past to make it easier to reenable.
