### ISSUE TITLE
[Bug]:  yarn build fails Failed to compile.  ./src/index.tsx Cannot find file './index.css' in './src'.

### ISSUE THREAD

**Issue by ajaysourcedigital** [metaplex-foundation/metaplex#1714]
### Which package is this bug report for?

gumdrop

### Issue description

this is what i am doing :

yarn install && yarn bootstrap --> works perfectly. 

yarn run build fails with below error:

```
Running less-watch-compiler once.
lerna ERR! yarn run build exited 1 in 'gumdrop'
lerna ERR! yarn run build stdout:
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/index.tsx
Cannot find file './index.css' in './src'.


info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 1.
```

### Command

```shell
yarn install
yarn bootstrap
export REACT_APP_STORE_OWNER_ADDRESS_ADDRESS='something here'

yarn run build
```

### Operating system

debian

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
I was unable to reproduce this issue. My gumdrop builds fine. If you are still having this issue, it would be better asked in our discord (https://discord.gg/metaplex). Our community champions will be happy to help. Thanks!
