### ISSUE TITLE
[Feature]: MINTING WEBSITE: update remaining items after minting button click

### ISSUE THREAD

**Issue by lucastoian** [metaplex-foundation/metaplex#1719]
### Which package is this bug report for?

candy machine ui

### Issue description

Hi, after successfully completing the minting by clicking on the button, the remaining items are not updated.

I would like state.itemsRedeemed to be updated immediately after every mint in the frontend...how could I modify the code to implement this?

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
You would have to manually subtract one from the itemsRedeemed after mint. Another possibility would be to use the subscription websocket to watch the candy machine account. Implementing one of these is a feature that we would like to add eventually (and would happily merge it in should someone from the community open a PR implementing this).

**Comment by lucastoian** [comment]
> You would have to manually subtract one from the itemsRedeemed after mint. Another possibility would be to use the subscription websocket to watch the candy machine account. Implementing one of these is a feature that we would like to add eventually (and would happily merge it in should someone from the community open a PR implementing this).

How should I manually subtract one from the itemsRedeemed after mint?

In Home.txt there is the `const onMint = async () => {...}`

should I add there the line ` candyMachine?.state.itemsRemaining-1` ?

**Comment by stegaBOB** [comment]
This feature was added in #1770
