### ISSUE TITLE
[Feature]: How to update maxSupply of MasterEdition NFT

### ISSUE THREAD

**Issue by blockchainlover2019** [metaplex-foundation/metaplex#1722]
### Which package is this bug report for?

other

### Issue description

I minted MasterEdition NFT with maxSupply of 1000.
and I want to extend it to 2000 now.
But I can't find any function (i.e. update_master_edition) on the metaplex.
How can I deal this? Please help me!

### Operating system

Ubuntu

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
It doesn't look like you can alter the max supply of a master edition after setting it. You will have to create a new master edition nft.
