### ISSUE TITLE
[Bug]: premadeCustoms is ignored

### ISSUE THREAD

**Issue by iconiccodes** [metaplex-foundation/metaplex#1725]
### Which package is this bug report for?

other cli

### Issue description

Setting this config in traits-configuration.json

```
"premadeCustoms": [
        {   
            "01Background":"foo.png",
            "02Accessory":"",
            "03Skin":"foo.png",
            "04Clothes":"foo.png",
            "05Eyes":"foo.png",
            "06Mouth":"foo.png",
            "07HatHair":"foo.png",
            "08Jewellry":"foo.png"
        }
    ],
```

running metaplex art gen with

`create_generative_art -c traits-configuration.json  -n 5 -ta true
`

but the premadecustom is not getting generated.

Am I using it wrong? 

### Command

```shell
create_generative_art -c traits-configuration.json  -n 5 -ta true
```

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
The generator isn't being maintained and currently has some issues. There are great alternatives that exist that I would recommend using instead such as HashLips.
