### ISSUE TITLE
[Bug]: Price (custom SPL token) mistake

### ISSUE THREAD

**Issue by clintnetwork** [metaplex-foundation/metaplex#1734]
### Which package is this bug report for?

storefront

### Issue description

Hi,

There are a big mistake for display the price (for instant sale), the price is good in the listing:

<img width="272" alt="Screenshot 2022-02-06 at 16 14 36" src="https://user-images.githubusercontent.com/5221349/152685045-9bdc2d61-0afa-4b49-b177-2f59d118d2ee.png">

but not in the auction page:

<img width="689" alt="Screenshot 2022-02-06 at 16 13 58" src="https://user-images.githubusercontent.com/5221349/152685010-421eadf2-9567-491b-b482-1a38ccefeee8.png">

### Operating system

macOS

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Looks like its not dividing by the token decimals correctly. Should be an easy fix. This is most likely a UI issue.

**Comment by clintnetwork** [comment]
Yes yes it is only UI

**Comment by clintnetwork** [comment]
Any news on this @stegaBOB?
