### ISSUE TITLE
[Bug]: You have items locked in a defective auction!

### ISSUE THREAD

**Issue by clintnetwork** [metaplex-foundation/metaplex#1736]
### Which package is this bug report for?

storefront

### Issue description

Hi,

There a bug with this feature, sometimes (on the authors page) when you click on "search of other auctions" and you have defective auctions the button is checked by default instead of be checked for "search of other auctions"

<img width="358" alt="Screenshot 2022-02-06 at 17 20 17" src="https://user-images.githubusercontent.com/5221349/152687800-dc0e7fb8-3dc4-4419-9d1a-b25236a29f4a.png">

### Operating system

Win10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by yamijuan** [comment]
I need this fix haha

**Comment by clintnetwork** [comment]
Yes everybody need it lol, anyway there a little trick shot
