### ISSUE TITLE
[Bug]: Custom Gumdrop not working properly

### ISSUE THREAD

**Issue by sugodeglind** [metaplex-foundation/metaplex#1737]
### Which package is this bug report for?

gumdrop

### Issue description

After deploying a custom gumdrop, some functionalities are not working on the gumdrop UI. 

Site gets deployed normally:
![Desktop Screenshot 2022 02 06 - 20 05 23 28](https://user-images.githubusercontent.com/97797873/152697458-4b9449f1-6afc-4739-875a-2a8fab90533b.png)

After clicking "Create" button in the top left, nothing happens and the domain changes like this:
![Desktop Screenshot 2022 02 06 - 20 05 38 81](https://user-images.githubusercontent.com/97797873/152697500-c0403ea6-78f9-4578-a26c-a4fd194860e4.png)
Adds: /undefined/create

I think it might be some issue with dependencies not linking properly, but I personally don't have a deep understanding of how React apps work. The issue is the same if deployed on Vercel as well.

### Command

```shell
./metaplex/js/packages/gumdrop> yarn start
```

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
What commands did you run to install the packages, and would you mind sharing the browser console output?

**Comment by sugodeglind** [comment]
> What commands did you run to install the packages, and would you mind sharing the browser console output?

I ran yarn install and yarn build in ./metaplex/js (got unmet peer dependency warnings)
Then ran yarn start in ./metaplex/js/packages/gumdrop

This is the browser console output:

log.js:24 [HMR] Waiting for update signal from WDS...
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at DomWrapper (http://localhost:3000/static/js/vendors~main.chunk.js:406701:94)
    at http://localhost:3000/static/js/vendors~main.chunk.js:406416:32
    at Mask (http://localhost:3000/static/js/vendors~main.chunk.js:396330:25)
    at div
    at Dialog (http://localhost:3000/static/js/vendors~main.chunk.js:396388:32)
    at http://localhost:3000/static/js/vendors~main.chunk.js:438154:25
    at PortalWrapper (http://localhost:3000/static/js/vendors~main.chunk.js:438267:94)
    at DialogWrap (http://localhost:3000/static/js/vendors~main.chunk.js:396606:23)
    at Modal (http://localhost:3000/static/js/vendors~main.chunk.js:273085:75)
    at DefaultModal (http://localhost:3000/static/js/main.chunk.js:25132:5)
    at WalletModal (http://localhost:3000/static/js/main.chunk.js:27719:85)
    at WalletModalProvider (http://localhost:3000/static/js/main.chunk.js:27826:5)
    at WalletProvider (http://localhost:3000/static/js/vendors~main.chunk.js:225305:5)
    at WalletProvider (http://localhost:3000/static/js/main.chunk.js:27879:5)
    at ConnectionProvider (http://localhost:3000/static/js/main.chunk.js:27249:5)

**Comment by stegaBOB** [comment]
Yarn bootstrap?

**Comment by sugodeglind** [comment]
Yes. I only did yarn install in metaplex/js and then pushed to github. Then I used yarn bootstrap && yarn build as build commands in Vercel. Are there more commands that I have to do before pushing to github? Thanks!

**Comment by sugodeglind** [comment]
Now I got some new browser outputs:
[HMR] Waiting for update signal from WDS...
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed: 
WebSocketBrowserImpl @ websocket.browser.js:47
index.js:1 ws error: undefined
console.<computed> @ index.js:1
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed: 
WebSocketBrowserImpl @ websocket.browser.js:47
index.js:1 ws error: undefined
console.<computed> @ index.js:1
metaplex.devnet.rpcpool.com/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
metaplex.devnet.rpcpool.com/:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed: 
WebSocketBrowserImpl @ websocket.browser.js:47
index.js:1 ws error: undefined
console.<computed> @ index.js:1
browser-ponyfill.js:480 Uncaught (in promise) TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (:3000/metaplex/static/js/vendors~main.chunk.js:231241:20)
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed: 
WebSocketBrowserImpl @ websocket.browser.js:47
index.js:1 ws error: undefined
console.<computed> @ index.js:1
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed: 
WebSocketBrowserImpl @ websocket.browser.js:47
index.js:1 ws error: undefined
console.<computed> @ index.js:1
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed: 
WebSocketBrowserImpl @ websocket.browser.js:47
index.js:1 ws error: undefined
console.<computed> @ index.js:1
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed: 
WebSocketBrowserImpl @ websocket.browser.js:47
index.js:1 ws error: undefined
console.<computed> @ index.js:1
websocket.browser.js:47 WebSocket connection to 'wss://metaplex.devnet.rpcpool.com/' failed:

**Comment by stegaBOB** [comment]
I can reproduce this issue. Thanks for letting us know. Looking into it now.

**Comment by sugodeglind** [comment]
Thanks a lot for your work! Another guy on discord had the same issue and fixed it by removing a .env file somewhere. I'm gonna see if it fixes it for me. Thought it might help you in your investigation.

**Comment by stegaBOB** [comment]
Would you be able to direct me to that conversation and if you are able to fix it let us know what you did? thanks

**Comment by sugodeglind** [comment]
Got an answer from the guy that fixed it. It managed to fix it for me aswell.
Here is his message:
There are 2 places you need to remove the ${process.env.REACT_APP_WEB_HOME} line

first is in 

metaplex/js/packages/gumdrop/src/Header/Header.tsx

Second is in 

metaplex/js/packages/gumdrop/src/App.tsx

<img width="505" alt="S
<img width="707" alt="Screen_Shot_2022-02-21_at_12 03 38_PM" src="https://user-images.githubusercontent.com/97797873/155010211-129d8ed6-21e8-4298-b31e-d634d0015673.png">
creen_Shot_2022-02-21_at_12 06 30_PM" src="https://user-images.githubusercontent.com/97797873/155010204-541c2d1c-a320-44ec-a2c7-d8288231ee28.png">

He said that he had dug through the code and couldn't find anything matching: ${process.env.REACT_APP_WEB_HOME}

Hope this helps!
