### ISSUE TITLE
[Bug]: Compilation error while starting the server

### ISSUE THREAD

**Issue by Ajaazahmed** [metaplex-foundation/metaplex#1750]
### Which package is this bug report for?

candy machine ui

### Issue description

It was working previously with this commit 48c492d8b0d25add6076e5095ecc6706f864a0e6

Latest master branch throws compilation error

### Command

```shell
yarn Start
```

### Relevant log output

```shell
TypeScript error in C:/Users/ahmed/metaplex/js/packages/candy-machine-ui/src/candy-machine.ts(441,40): 
Property 'SYSVAR_SLOT_HASHES_PUBKEY' does not exist on type 'typeof import("@solana/web3.js")'.  TS2339

    439 |         rent: anchor.web3.SYSVAR_RENT_PUBKEY,
    440 |         clock: anchor.web3.SYSVAR_CLOCK_PUBKEY,
  > 441 |         recentBlockhashes: anchor.web3.SYSVAR_SLOT_HASHES_PUBKEY,
        |                                        ^
    442 |         instructionSysvarAccount: anchor.web3.SYSVAR_INSTRUCTIONS_PUBKEY,
    443 |       },
    444 |       remainingAccounts:
```

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Khushhal23** [comment]
@Ajaazahmed Do yarn install in candy-machine-ui

**Comment by Ajaazahmed** [comment]
Yes my yarn version is 1.22.17 and yes i did yarn install in candy-machine-ui.. i even triple checked it and issue remains to be the same

**Comment by walter-grace** [comment]
> 

I am getting the same exact error when running yarn start- I have the issue on Mac. 
yarn --version
1.22.17

**Comment by warrenwoolseyiii** [comment]
Hey all - until this issue is fixed I was able to get a locally hosted webserver running for candy machine v2 using this repo - worked on the first try with the right config:
https://github.com/alvinsga/candy-machine-v2

**Comment by roederw** [comment]
Taking a look now.

**Comment by roederw** [comment]
PR is out to fix this.
