### ISSUE TITLE
[Bug]: Compilation error while starting the server 

### ISSUE THREAD

**Issue by Schelm231** [metaplex-foundation/metaplex#1761]
### Which package is this bug report for?

candy machine ui

### Issue description

I would start my server with the command:

I have already make "Yarn install" in the candy-machine-ui folder.

The local host page also opens, but I can't click the Mint button on it.

Anybody can help me?

### Command

```shell
PS C:\Users\Thoma\Desktop\v2\metaplex\js\packages\candy-machine-ui> yarn install
yarn install v1.22.17
[1/4] Resolving packages...
Failed to compile.

C:/Users/Thoma/Desktop/v2/metaplex/js/packages/candy-machine-ui/src/candy-machine.ts
TypeScript error in C:/Users/Thoma/Desktop/v2/metaplex/js/packages/candy-machine-ui/src/candy-machine.ts(441,40):
Property 'SYSVAR_SLOT_HASHES_PUBKEY' does not exist on type 'typeof import("@solana/web3.js")'.  TS2339

    439 |         rent: anchor.web3.SYSVAR_RENT_PUBKEY,
    440 |         clock: anchor.web3.SYSVAR_CLOCK_PUBKEY,
  > 441 |         recentBlockhashes: anchor.web3.SYSVAR_SLOT_HASHES_PUBKEY,
        |                                        ^
    442 |         instructionSysvarAccount: anchor.web3.SYSVAR_INSTRUCTIONS_PUBKEY,
    443 |       },
    444 |       remainingAccounts:
```

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Sonicfury** [comment]
I also just had this particular issue, my operating system is macOs v11.6.
I'll be looking into it today, I'll let you know if I find anything.

**Comment by Schelm231** [comment]
> I also just had this particular issue, my operating system is macOs v11.6.
> I'll be looking into it today, I'll let you know if I find anything.

Hope you find the issue! 😊 Thanks!

**Comment by SamFordGH** [comment]
> I also just had this particular issue, my operating system is macOs v11.6. I'll be looking into it today, I'll let you know if I find anything.

I hope you do it's driving me crazy 😩🤞🏽

**Comment by Sonicfury** [comment]
So far, I just saw that this constant is called in `mint.js` and is defined in `js/node_modules/@solana/web3.js/lib/index.d.ts`.
Yet, the `@solana/web3` called in the candy machine has this path for me `js/packages/candy-machine-ui/node_modules/@solana/web3.js/lib/index.d.ts` so maybe it has something to do with node_modules not being up to date between each other directory.
I'll try that later, because I'm actually at work so I'm supposed to work on other stuff lol

**Comment by wkwyatt** [comment]
Try `$ rm -rf node_modules` and deleting the yarn.lock file in the root directory of metaplex 

Then `cd` to the filepath for candy machine `js/packages/candy-machine-ui`
`$ cd js/packages/candy-machine-ui`

 and then do the same thing delete the yarn.lock file and remove node modules.

Next Pull the latest from the master repo

Then yarn install again in both places.  That fixed my errors lmk if it works for you

**Comment by Sonicfury** [comment]
Solved it for me too ! Thanks

**Comment by SamFordGH** [comment]
> rm -rf node_modules

sorry to act dumb but how do I pull the latest from master repo?

**Comment by ApesHunter231** [comment]
> 

Unfortunately, I don't understand it... Could you please explain it in a little more detail? :)

**Comment by soniatcs** [comment]
have the same issue in the most updated version, but using the old version of metaplex does not have this issue

**Comment by soniatcs** [comment]
same issue, but i used the old version of metaplex, it did not show this problem.

**Comment by shreyaskhadapkar** [comment]
Thank You!! It worked for me!!

**Comment by yamijuan** [comment]
upgrade the solana/web3 package on candymachine-ui to 1.33: `    "@solana/web3.js": "^1.33.0",`
