### ISSUE TITLE
[Bug]: candy-machine-v2 unable to upload external hosted images (V1 worked fine)

### ISSUE THREAD

**Issue by tskazinski** [metaplex-foundation/metaplex#1766]
### Which package is this bug report for?

candy machine cli

### Issue description

In my 0.json (nft file) I set the image and uri parameters to external loading assets like so:
I also have my 0.png image next to the 0.json file which has these parameters set for the image:

...
"image": "https://api-domain.com/image.png",
...
"properties": {
		"files": [
			{
				"uri": "https://api-domain.com/image.png",
				"type": "image/png"
			}
		],

When I run the candy machine upload command (shown below), I get an error that concatenates the location of the file and the URL in the json file. Using V1 of the candy machine this was working fine, I was able to mint files using the external domain so something changed or maybe there is another way of doing this?

Here is my candy-machine-config.json:

{
    "price": 0.1,
    "number": 1,
    "gatekeeper": null,
    "solTreasuryAccount": "XXX",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "25 Dec 2021 00:00:00 GMT",
    "endSettings": null,
    "whitelistMintSettings": null,
    "hiddenSettings": null,
    "storage": "arweave",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}

### Command

```shell
npx ts-node candy-machine-v2-cli.ts upload
-e devnet 
-k C:/path/keypair.json 
-cp candy-machine-config.json 
-c example ./output/minting-files
```

### Relevant log output

```shell
Error uploading file https://www.api-domain.com/image.png [Error: ENOENT: no such file or directory, stat 'D:\path\output\minting-files\https:\api-domain.com\image.png'] { 
  errno: -4058, 
  code: 'ENOENT', 
  syscall: 'stat', 
  path: 'D:\\path\\output\\minting-files\\https:\\api-domain.com\\image.png' 
}
```

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by BHALEYART** [comment]
This issue appears to be rampant rn. No known solution, maybe revert to a couple weeks ago (still v2)

**Comment by paulinhoAlmeida** [comment]
https://github.com/metaplex-foundation/metaplex/issues/1767 seems to be duplicated to this one

**Comment by uaktags** [comment]
My initial guess is it has to do with this:
https://github.com/metaplex-foundation/metaplex/blob/ccd9216d50ee85c936652f166e916cb3fe99225c/js/packages/cli/src/commands/upload.ts#L288
We're basically just assuming that we're always going to concate a folder path with the image in the json.

We then continue on through uploads without actually confirming the need for the uploads.

One thing I did to test this:
I use nftStorage so i did this check:
```
const imageUrl = (image.startsWith('http')? image : `${await uploadMedia(image)}?ext=${path
    .extname(image)
    .replace('.', '')}`);
```

not 100% this fixed it for me, but currently running through the testing.
