### ISSUE TITLE
[Bug]: upload was not successful, please re-run. [Error: ENOENT: no such file or directory, stat 

### ISSUE THREAD

**Issue by KENHAU** [metaplex-foundation/metaplex#1767]
### Which package is this bug report for?

candy machine cli

### Issue description

I try to upload my collection on-chain, I ensure that I follow the right steps and which was successful in my testing upload. However, when I try to upload my real collection on-chain, the following errors occur: 

wallet public key: xxxxxxxxxx
Beginning the upload for 10 (img+json) pairs
started at: 1644587242600
config for a candy machine with publickey: xxxxxxxxxxxx has been already initialized
Uploading Size 1 { mediaExt: '.png', index: '0' }
Saved bundle upload result to cache.
upload was not successful, please re-run. [Error: ENOENT: no such file or directory, stat 'C:\Users\ken\NFT\hashlips_art_engine\exports\image.png'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\ken\\NFT\\hashlips_art_engine\\exports\\image.png'
}

I have only 10 pairs .png and json, from 0-9.png and 0-9.json

I don't understand why it asks me to have the imapge.png in my exports folder. I think it is not necessary because it should be auto get the first file name and start the upload until I set the number of files in the config.js, I was successful to upload during my test progress and I sure that image.png is not required.

Could anyone please give me the direction to fix the problem, thank you.

### Command

```shell
ts-node candy-machine-v2-cli.js upload C:\Users\ken\NFT\hashlips_art_engine\exports -e mainnet-beta --keypair C:\Users\ken\.config\solana\id.json -cp C:\Users\ken\git\nft\metaplex\js\packages\cli\build\config.js
```

### Operating system

WIN10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by BHALEYART** [comment]
Also experiencing this issue. Used V2 about two weeks ago just fine, didn't try to call "image.png" randomly from no where.

**Comment by stegaBOB** [comment]
Are you still having this issue? Its likely calculating a path wrong in one of your json files resulting in it thinking image.png is a file it has to upload. Can you share one of the .json files? Thanks

**Comment by CuseTheJuice** [comment]
"config for a candy machine with publickey: xxxxxxxxxxxx has been already initialized" be sure to delete the .json file matching your candy machine -cp in the .cache directory I'm assuming you have already withdrawn this candy machine
