### ISSUE TITLE
[Bug]: Yarn start giving error Command failed with exit code 1 

### ISSUE THREAD

**Issue by SamFordGH** [metaplex-foundation/metaplex#1768]
### Which package is this bug report for?

candy machine ui

### Issue description

When running yarn start ui does not run and brings up error Command failed with exit code 1.

Have tried removing node modules, removing yarn and pulling latest and installing yarn again in all directories 

### Command

```shell
yarn start
```

### Relevant log output

```shell
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.5.0
error Command failed with exit code 1.
```

### Operating system

Mac OS

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
You should be using the 16.x LTS version. The newest node versions are buggy.
