### ISSUE TITLE
[Bug]: Buying is not working in storefront. Transactions are getting declined.

### ISSUE THREAD

**Issue by thangasblockchain** [metaplex-foundation/metaplex#1771]
### Which package is this bug report for?

storefront

### Issue description

I have created an NFT using storefront. I can see my NFT in Solana, when I try to Instant sale, auction is also working.

But when I create a new wallet and try to buy the NFT, I am getting transaction error. I have attached below.
<img width="694" alt="Screenshot 2022-02-12 at 1 53 04 PM" src="https://user-images.githubusercontent.com/40734900/153703560-fab0d803-b15b-442e-b908-4fdf293f5ae5.png">
<img width="1440" alt="Screenshot 2022-02-12 at 1 53 20 PM" src="https://user-images.githubusercontent.com/40734900/153703567-3386091d-7e8d-4cfb-9e79-4a786acc8f52.png">
<img width="1440" alt="Screenshot 2022-02-12 at 1 53 31 PM" src="https://user-images.githubusercontent.com/40734900/153703571-329c70cd-1d11-4f69-b826-c5aa49fa8f4d.png">

### Operating system

Mac

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by littleV** [comment]
Hey, I ran into the same issue. I used 2 test accounts on devnet, one for creating the nft one for buying.
When buying with the second account, I got this error: Unhandled Runtime Error: transaction failed, UninitializedAccount
Here's my transaction detail: https://solscan.io/tx/2gg4yWgAhedXNSopNt4xcxgp64K8dNknc3sCx4s6633nsqYqbKrfP3ioGZ7Z3YyQPLSbeavWpdGGVzTWJioUL665?cluster=devnet

**Comment by autronix** [comment]
I am seeing the same behavior, encountered this issue with branch v1.1.1.

Using:
- v1.1.1
- Devnet
- Phantom wallet
- 2 separate devnet accounts (purchasing with either results in the same issue - also tried wrapping SOL in one of the accounts, same result)

**Comment by stegaBOB** [comment]
Branch v1.1.1 is not working right now. There were breaking changes to Solana that forces us to change things. Our docs are a bit outdated. I'll go fix that now. Please try pulling from master. If the issue still exists after that feel free to let us know.

**Comment by stegaBOB** [comment]
I was able to successfully list and purchase one of my own NFTs. Closing this issue for now.
