### ISSUE TITLE
Selling a master edition as existing item seems to mark primarySaleHappened = true even if you made it

### ISSUE THREAD

**Issue by bhgames** [metaplex-foundation/metaplex#178]
Flow is this -> Mint a new master edition with supply 0. Sell it as existing item. Go to explore. Expect to see auction in Live Auctions since it has never been sold before, but it shows up in secondary markeptlace instead (for things that have been sold before). One of two things is happening. Either we are auto-marking the items right before we put them on the market for auction at that point as primarySaleHappened = true (which we may be doing, thinking they got it via a crank turn from auctioneer) which causes them to get sorted into the secondary marketplace tab OR the secondary marketplace tab is falsely filtering primarySaleHappened = false items into itself. I think the former is more likely. We have in place some logic in the auction creation where if we detect an item you have that has primarySaleHappened = false that we will try to mark it true for you to prevent you from losing all your fees to the creators in the creator array, assuming you got this item via a remote crank turn from the auctioneer, but this should not fire if you are the creator selling the item (easy to check - compare wallet selling item to creator array wallets).

**Comment by noobsk8** [comment]
https://user-images.githubusercontent.com/88256604/127755031-3e636f5a-f345-4c2a-9e03-c885ef54db87.mp4

video of error

**Comment by kespinola** [comment]
https://tophatchicks.holaplex.com/#/

I'm doing an audit of the issue for the above storefront.

All the auctions listed under secondary marketplace are first time auctions.

The action item has info.primarySaledHappened marked as 1.

https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/web/src/views/home/index.tsx#L51

**Comment by bhgames** [comment]
Fixed with https://github.com/metaplex-foundation/metaplex/pull/183
