### ISSUE TITLE
[Bug]: Unable to upload the artwork to Arweave.

### ISSUE THREAD

**Issue by kiarashplusplus** [metaplex-foundation/metaplex#1780]
### Which package is this bug report for?

storefront

### Issue description

<img width="1442" alt="Screen Shot 2022-02-13 at 12 09 48 AM" src="https://user-images.githubusercontent.com/1780945/153739652-93c6a262-fe65-462c-b135-fc0af2aa01f5.png">

Post requests to Artweave endpoint returns with a 413 
https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile

Before it was showing a cors error when called from [here](https://persianheritagecoin.web.app/#/art/create/ ), so I added a ['no-cors'](https://github.com/kiarashplusplus/metaplex/commit/e4ddc2a2258c6bf9406f386dcdcae829c4562a22) header, yet it's a 413.

### Operating system

web

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by kiarashplusplus** [comment]
Retry worked! Reduced image size too! 

https://solscan.io/token/FZ7JV6m4pr8S7iyPh4K9nFzgby2Gn2FHVJeAGJjdHNup

**Comment by aliiqbal436** [comment]
i'm facing the same issue with .mp4 files.
