### ISSUE TITLE
[Bug]: Mint Button greyed out

### ISSUE THREAD

**Issue by JasonJvV** [metaplex-foundation/metaplex#1781]
### Which package is this bug report for?

candy machine ui

### Issue description

After running "yarn install && yarn start" for candy-machine-ui (on the devnet) I am redirected to a web page with a "connect wallet" button. I am able to collect the wallet just fine. Once connected however the Mint button is greyed out.

I have checked my goLiveDate in my config.json which is in the past and correctly configured: 

"goLiveDate": "01 Feb 2022 00:00:00 GMT",

My wallet has enough fake sol in it to cover the cost of the mint and is set onto the devnet.

What am I missing folks?

### Operating system

Mac M1

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by slimmsyd** [comment]
Did you check if the dAPP is pointing to the correct .env file?

**Comment by stegaBOB** [comment]
If you have done this, please open up your browser console (using inspect element) and share the error message you got. Thanks.

**Comment by stegaBOB** [comment]
Actually it most certainly is your .env file. https://docs.metaplex.com/candy-machine-v2/mint-frontend

**Comment by JasonJvV** [comment]
> Actually it most certainly is your .env file. https://docs.metaplex.com/candy-machine-v2/mint-frontend

I dont believe it is the .env file. See below

![env file](https://user-images.githubusercontent.com/89633579/154039057-bafab23c-8cc0-46d6-a818-7c61d460f86f.jpeg)

**Comment by JasonJvV** [comment]
> Actually it most certainly is your .env file. https://docs.metaplex.com/candy-machine-v2/mint-frontend

I then run the yarn install && yarn start in the directory seen in the screen shot. Am I missing something basic? Thanks for your time

**Comment by JasonJvV** [comment]
> Hm. Would you mind sharing the browser console?
<img width="1310" alt="Screenshot 2022-02-16 at 10 19 27" src="https://user-images.githubusercontent.com/89633579/154224138-a1a6889c-dfd3-490d-b031-15a4d12bbfe3.png">

**Comment by JasonJvV** [comment]
A few error messages below the last error message included here for completeness
<img width="1359" alt="Screenshot 2022-02-16 at 10 22 26" src="https://user-images.githubusercontent.com/89633579/154225501-50c90cc7-1f61-495e-9564-4546e080ae03.png">

**Comment by Yupiyoung** [comment]
> Hm. Would you mind sharing the browser console?
> […](#)

I have this problem too, mint don’t work

**Comment by JasonJvV** [comment]
Solved it. 
In the .env file use an alternative RPC. Don’t use https://api.mainnet-beta.solana.com/ => https://docs.metaplex.com/community#rpc.

The following alternative worked for me:

https://psytrbhymqlkfrhudd.dev.genesysgo.net:8899/    for Devnet, or

https://ssc-dao.genesysgo.net/    for Mainnet

**Comment by JasonJvV** [comment]
> > Hm. Would you mind sharing the browser console?
> > […](#)
> 
> I have this problem too, mint don’t work

See solve above - use an alternative RPC all the links above for you.

**Comment by loganrihn** [comment]
hey guys. just following up on this. . I am in dire need of help. I tried to solve this for the last couple of days and am going insane. I have 2 problems. When I go to mint after upload verification in VSC i get this error:

PS C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli> ts-node C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts mint_one_token -e devnet -k C:/Users/Logan/.config/solana/devnet.json -c example C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli\assets
wallet public key: dGsL3eVcmC6HWj6RyhWcKu55Kf7tgJVxuRmhwdw2SEm
Rejected via websocket { InstructionError: [ 4, { Custom: 6019 } ] }
Timeout Error caught {
  err: { InstructionError: [ 4, [Object] ] },
  slot: 116180647,
  confirmations: 0
}
C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli\src\helpers\transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x1783
    at sendSignedTransaction (C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli\src\helpers\transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli\src\helpers\transactions.ts:59:26)
    at async mintV2 (C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli\src\commands\mint.ts:344:5)
    at async Command.<anonymous> (C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:714:16)
PS C:\Users\logan\Desktop\CYBER\~\metaplex\js\packages\cli> 

![image](https://user-images.githubusercontent.com/3206463/154997933-933b30be-0109-4bc3-be83-cdcff3a2ca1e.png)


Alternatively, when I go to try and do npm install and start after editing my .env file, I am able to connect my wallet but the 'Mnt" button is greyed out and I am unable to click on it. I tried re editing my .env file and I tried an alternative RPC (https://psytrbhymqlkfrhudd.dev.genesysgo.net:8899/). I am stuck and have no clue how to solve this. Any advice would be greatly appreciated!!!
