### ISSUE TITLE
[Bug]:  Error: Transaction failed: Custom program error: 0x178a     at sendSignedTransaction

### ISSUE THREAD

**Issue by slimmsyd** [metaplex-foundation/metaplex#1784]
### Which package is this bug report for?

candy machine ui

### Issue description

When I onclick the preMade mint button to mint a NFT, it returns this error 

Custom program error: 0x178a  everytime. Not sure what is causing this? I haven't found anyone in the community who has received this error code 
![MintSOlNFT](https://user-images.githubusercontent.com/84546691/153769578-1326ca19-2b8d-459a-9c9a-ba713e252a77.PNG)

### Operating system

Windows 

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
I am not having this issue on my end. If you are still having this issue, it would be better asked in our discord (https://discord.gg/metaplex). Our community champions will be happy to help. Thanks!
