### ISSUE TITLE
[Bug]: Error when trying to upload my nfts.

### ISSUE THREAD

**Issue by JonathanLau2046** [metaplex-foundation/metaplex#1788]
### Which package is this bug report for?

candy machine cli

### Issue description

Hello guys, I am using OS to create my NFTs. This shows up when I try to upload my nfts, have been working on it for 2 hours and still have no idea what to fix this.

<img width="669" alt="螢幕截圖 2022-02-14 下午5 35 33" src="https://user-images.githubusercontent.com/99647798/153839522-0b8768a7-fa5c-4c1f-9a71-0a11a6530a7e.png">

### Operating system

OS

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
This is most likely due to a formatting issue on your end. Please ask in our discord (https://discord.gg/metaplex) for more help.
