### ISSUE TITLE
[Bug]: Payments on sales do not arrive!!!

### ISSUE THREAD

**Issue by stetommy** [metaplex-foundation/metaplex#1796]
### Which package is this bug report for?

Metaplex storefront

### Issue description

Hi there! I'm testing Metaplex. 
Cloned dowloaded and edit repo, started it on localhost. Minted an NFT listed it on auction for 0.01 SOL. From another account bought it. NFT successfully transferred to buyer, but 0.01 SOL stuck on program address and didn't land on creator wallet. Why? 

Please help.

As store owner create and instant list NFT (master)
As antoher user buy it
Expected behavior

another user receives NFT - OK
Store owner receives crypto - NOT OK

### Priority this issue should have

High (immediate attention needed)

**Comment by yamijuan** [comment]
that does not happen automatically, once the auction finishes you need to go to that auction page + `/billing` and settle the funds

**Comment by stetommy** [comment]
> that does not happen automatically, once the auction finishes you need to go to that auction page + `/billing` and settle the funds

Yes, now I have seen where I can find this information? Can I also remove auctions that ended later from the store? I did not find it specified that to put an NFT's up for auction you need $ 6 in commissions I think from the store bot. Could you help me with these questions?

**Comment by l8nit3tr0ubl3** [comment]
Does this also apply to those using a cany machine mint?? because I have made sales, and not received my payment split between our creator wallets. Using the supplied candy machine UI and CM2
