### ISSUE TITLE
[Bug]: Error uploading file [object Object] FetchError: invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile reason: Unexpected  token E in JSON at position 0

### ISSUE THREAD

**Issue by ram-nullbytess** [metaplex-foundation/metaplex#1797]
### Which package is this bug report for?

other cli

### Issue description

try will upload ts-node upload command

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
    ./assets
```

### Relevant log output

```shell
expected behavior it should upload the assets. the metadata JSON files are correct. instead, it throws error invalid JSON which is unexpected behaviour
```

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by vr-nissage** [comment]
Same error for me as well...

**Comment by stegaBOB** [comment]
We fixed the issue. It was an issue with our GCP. Closing this issue now. If you are still having this issue feel free to open a new issue. Thanks.
