### ISSUE TITLE
[Bug]: Invoke WebRequest "--output".

### ISSUE THREAD

**Issue by Jricobeats** [metaplex-foundation/metaplex#1800]
### Which package is this bug report for?

other

### Issue description

Just before starting work, I ran into an error. How is it possible to solve it? Thanks!

Invoke-WebRequest : Cannot find a positional parameter that takes argument "--output".
string:1 character:1
+ curl https://release.solana.com/v1.9.6/solana-install-init-x86_64-pc- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

### Command

```shell
curl https://release.solana.com/v1.9.6/solana-install-init-x86_64-pc-windows-msvc.exe --output C:\solana-install-tmp\solana-install-init.exe --create-dirs
```

### Relevant log output

```shell
Just before starting work, I ran into an error. How is it possible to solve it? Thanks!

Invoke-WebRequest : Cannot find a positional parameter that takes argument "--output".
string:1 character:1
+ curl https://release.solana.com/v1.9.6/solana-install-init-x86_64-pc- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
You are trying to install the tool using PowerShell. For whatever reason the curl method in PowerShell is actually an alias for a different method that accepts different parameters. Try installing via the windows cmd prompt or git bash.
