### ISSUE TITLE
[Bug]: Candy Machine cache file is not updated when uploading to Arweave

### ISSUE THREAD

**Issue by hordur84** [metaplex-foundation/metaplex#1804]
### Which package is this bug report for?

candy machine cli

### Issue description

![example](https://user-images.githubusercontent.com/70026658/154166747-55638802-cc93-4daa-b172-35ce0d6e4be6.png)

If the "animation_url" entry is present in the .json metadata, the IF statement at the bottom will always fail since **arweaveUpload** does not assign **animationLink** any value. Thus, the generated .json cache file contains no items (i.e. the arweave links and such).

### Command

ts-node packages/cli/src/candy-machine-v2-cli.ts upload -k key.json -cp config.json

### Relevant log output

No log output. "items. object is just empty in the generated cache .json file.

### Operating system

Ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Are you trying to upload animation files via the `arweave` method?

**Comment by hordur84** [comment]
> Are you trying to upload animation files via the `arweave` method?

No, I am just pointing out that if you have the "animation_url" entry in your .json metadata (which I had even though I am not using it, it's just empty as such "animation_url":""), the upload through arweave will not work correctly since it won't update the candy machine .json cache file with the arweave item links. So when you are running the upload command everything seems to work all right, except it never gets to the "writing indices..." step because the .json cache file contains no items and thus there is nothing to write.

**Comment by stegaBOB** [comment]
Ah I see the issue. Thats definitely something we should fix. Thanks.
