### ISSUE TITLE
[Bug] [ERR] error: unknown command 'upload'

### ISSUE THREAD

**Issue by Jricobeats** [metaplex-foundation/metaplex#1806]
### Which package is this bug report for?

other

### Issue description

Good day! Please tell me how can I solve this error?

![errr1](https://user-images.githubusercontent.com/98556699/154271105-ddb294db-c208-432c-823d-690c0e60e8af.jpg)

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v1-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet-test.json
```

### Relevant log output

```shell
[ERR] error: unknown command 'upload'
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Upload is no longer a command with v1. If you want to edit an existing Candy Machine v1 you can use the update_candy_machine command. For new uploads, you need to use v2. Our docs provide more info.
