### ISSUE TITLE
Always time out when run upload command on macos terminal with http/https proxy turned on

### ISSUE THREAD

**Issue by singletooon** [metaplex-foundation/metaplex#1808]
### Which package is this bug report for?

candy machine cli

### Issue description

Firstly, I had to turn the proxy on, or I couldn't access any URL of Solana because of the GFW. 

To reproduce: 
1. have the v2ray proxy installed. 
2. on the terminal, run `export http_proxy="http://127.0.0.1:8001"; export HTTP_PROXY="http://127.0.0.1:8001"; export https_proxy="http://127.0.0.1:8001"; export HTTPS_PROXY="http://127.0.0.1:8001"`.
3. run the upload command. then the issue will occur.
![Screen Shot 2022-02-16 at 4 23 22 PM](https://user-images.githubusercontent.com/97838777/154288783-0493164e-6b69-45ce-ba38-158e6666d0d2.png)

Other Solana commands below worked fine when the proxy turned on.
`solana balance` 
`solana airdrop 2` 
`curl https://api.devnet.solana.com/`

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/id.json \
    -cp '/Users/bin/Documents/tryMetaplex/candy-machine-upload-config.json' \
    -c example \
    '/Users/bin/Documents/tryMetaplex/example-assets'
```

### Operating system

macos 10.15.7

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by sluck430** [comment]
Same problem, did you figure it out?

**Comment by stegaBOB** [comment]
Have you tried on other RPC endpoints?
