### ISSUE TITLE
End sale & claim item doesn't work

### ISSUE THREAD

**Issue by stetommy** [metaplex-foundation/metaplex#1809]
### Which package is this bug report for?

Metaplex Storefront

### Issue description

When I go to the live section, and I want to remove a nft listed for sale, and I click on end sale & claim items nothing happens and it does not make me close the auction and collect the nft. Does the same thing happen to anyone? i don't know how to remove the rod and collect the nft.

Thanks a lot and anyone helping me to fix this.

**Comment by stegaBOB** [comment]
What does the browser console say?

**Comment by stetommy** [comment]
> What does the browser console say? You can find it using inspect element

when I press the end sale & claim item the console doesn't say anything. As if it did nothing, however, there are these warnings. Once pressed, the green button disappears and remains black and fine.
<img width="786" alt="Schermata 2022-02-17 alle 17 33 58" src="https://user-images.githubusercontent.com/99267639/154527688-88a3a825-bf45-4a8c-bbd0-e86e7fa95a8c.png">

**Comment by andyfife** [comment]
i am having the same issue

**Comment by stetommy** [comment]
> i am having the same issue

as of today I have no solution for this.

**Comment by degodsnft** [comment]
We are currently experiencing the same issue with one of our auctions
