### ISSUE TITLE
[Bug]: error: required option '-cp, --config-path <string>' not specified

### ISSUE THREAD

**Issue by Jricobeats** [metaplex-foundation/metaplex#1811]
### Which package is this bug report for?

other

### Issue description

Good day! I ran into an error, although I do everything step by step according to the video lesson
https://www.youtube.com/watch?v=4LLx7SMAOag&ab_channel=ReeceHunter

i use:
`ts-node js/packages/cli/src/candy-machine-v2-cli.ts`

because there is no file in my directory `candy-machine-cli.ts`, there is only one file candy-`machine-v1-cli.ts` and `candy-machine-v2-cli.ts`.

![e2](https://user-images.githubusercontent.com/98556699/154342224-640b4014-e9af-451c-92af-5197e4c0af4c.jpg)

Yes, and having studied the video lessons, everything is completely different with him ..

I've looked through the libraries, and videos about it, but haven't found anything. I hope you'll give me a hand. Thanks!

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet-test.json
```

### Relevant log output

```shell
error: required option '-cp, --config-path <string>' not specified
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
https://docs.metaplex.com
