### ISSUE TITLE
[Bug]:  npm install fails on Gumdrop 

### ISSUE THREAD

**Issue by DataKnox** [metaplex-foundation/metaplex#1812]
### Which package is this bug report for?

gumdrop

### Issue description

1. I clone the repo
2. I navigate to ~/metaplex/js/packages/gumdrop

### Command

```shell
npm install
```

### Relevant log output

```shell
knox@DESKTOP-9BDANSS:~/knoxmeta/metaplex/js/packages/gumdrop$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gumdrop@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.4.0 || ^16.0.0" from material-ui@0.20.2
npm ERR! node_modules/material-ui
npm ERR!   material-ui@"^0.20.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/knox/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/knox/.npm/_logs/2022-02-16T22_41_00_657Z-debug.log
```

### Operating system

ubuntu 20.04 LTS (WSL)

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by yamijuan** [comment]
use `yarn install` instead

**Comment by DataKnox** [comment]
> use `yarn install` instead

Thanks - Ive used yarn install which does successfully install; however the site fails to compile because of a missing @oyster/common dependency. I manually created a symlink to @oyster/common in the /metaplex/js/node_modules/@oyster/common directory and then it successfully compiles but the website itself is blank.
