### ISSUE TITLE
[Bug]:Empty Candy Machine ID

### ISSUE THREAD

**Issue by pepynd1r** [metaplex-foundation/metaplex#1815]
### Which package is this bug report for?

candy machine cli

### Issue description

Hey, I'm trying to get the Mint Hash List, using this tool -> https://magiceden.io/mintlist-tool

When I place my candy machine ID(on mainnet), no info comes out ( http://prntscr.com/26xxqu2 ), even though, I have minted 2 nfts. I need this hash list so that I can provide it to a secondary marketplace ( solsea.io ). Is it because the collection is still not fully minted or is it another problem?

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Please read this: https://docs.metaplex.com/mint-lists. It should solve your issue.
