### ISSUE TITLE
[Bug]: error: instruction requires an initialized account

### ISSUE THREAD

**Issue by Harish88s** [metaplex-foundation/metaplex#1818]
### Which package is this bug report for?

storefront

### Issue description

Hey

I am facing this problem when clicking buy button in the metaplex store.  Any idea what could be the cause of this ?

8 Token Program instruction
> Program log: Instruction: Revoke
> Program log: Error: UninitializedAccount
> Program Token Program  consumed 1313 of 200000 compute units
> Program returned error: instruction requires an initialized account

Thanks
Harish

### Operating system

Mac OS

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Khushhal23** [comment]
Please verify if the name of NFTs is too long

**Comment by ha2709** [comment]
I got these when I change account to buy NFT 
"breadcrumbs.ts:111 Timeout Error caught {err: {…}, slot: 119237637, confirmations: 0}
(anonymous) @ breadcrumbs.ts:111
overrideMethod @ react_devtools_backend.js:4061
sendSignedTransaction @ connection.js?f663:489
async function (async)
sendSignedTransaction @ connection.js?f663:465
sendTransactionWithRetry @ connection.js?f663:449
async function (async)
sendTransactionWithRetry @ connection.js?f663:431
sendPlaceBid @ sendPlaceBid.ts?dd20:55
async function (async)
sendPlaceBid @ sendPlaceBid.ts?dd20:44
instantSale @ index.tsx?1ac8:402
instantSaleAction @ index.tsx?1ac8:377
handleClick @ button.js?0554:201
callCallback @ react-dom.development.js?a814:3945
sentryWrapped @ helpers.ts:85
invokeGuardedCallbackDev @ react-dom.development.js?a814:3994
invokeGuardedCallback @ react-dom.development.js?a814:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?a814:4070
executeDispatch @ react-dom.development.js?a814:8243
processDispatchQueueItemsInOrder @ react-dom.development.js?a814:8275
processDispatchQueue @ react-dom.development.js?a814:8288
dispatchEventsForPlugins @ react-dom.development.js?a814:8299
eval @ react-dom.development.js?a814:8508
batchedEventUpdates$1 @ react-dom.development.js?a814:22396
batchedEventUpdates @ react-dom.development.js?a814:3745
dispatchEventForPluginEventSystem @ react-dom.development.js?a814:8507
attemptToDispatchEvent @ react-dom.development.js?a814:6005
dispatchEvent @ react-dom.development.js?a814:5924
unstable_runWithPriority @ scheduler.development.js?e22e:468
runWithPriority$1 @ react-dom.development.js?a814:11276
discreteUpdates$1 @ react-dom.development.js?a814:22413
discreteUpdates @ react-dom.development.js?a814:3756
dispatchDiscreteEvent @ react-dom.development.js?a814:5889
sentryWrapped @ helpers.ts:85
breadcrumbs.ts:111 sendPlaceBid Error: Transaction failed: Error: UninitializedAccount
    at sendSignedTransaction (connection.js?f663:503)
    at async sendTransactionWithRetry (connection.js?f663:449)
    at async sendPlaceBid (sendPlaceBid.ts?dd20:55)
    at async instantSale (index.tsx?1ac8:402)"

**Comment by ha2709** [comment]
I got these when I try to buy NFT :
        1. confirmations: 0
        2. err:
            1. InstructionError: Array(2)
                1. 0: 5
                2. 1: "UninitializedAccount"
                3. length: 2
                4. [[Prototype]]: Array(0)
            2.

**Comment by ha2709** [comment]
#1System Program Instruction> Program returned success
--
#2Token Program Instruction> Program log: Instruction: InitializeAccount> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3391 of 200000 compute units> Program returned success
