### ISSUE TITLE
[Bug]: yarn build failed

### ISSUE THREAD

**Issue by SamSLSystem** [metaplex-foundation/metaplex#1820]
### Which package is this bug report for?

storefront

### Issue description

Try to build without sucess:
node 14.17
node 17.5
node 16.13

lerna ERR! yarn run build exited 2 in '@metaplex/cli'
lerna ERR! yarn run build stdout:
$ tsc -p ./src
src/helpers/upload/nft-storage.ts(18,7): error TS2322: Type '{ 'Content-length': number; Authorization: string; }' is not assignable to type 'HeadersInit'.
  Types of property ''Content-length'' are incompatible.
    Type 'number' is not assignable to type 'string'.
src/helpers/upload/nft-storage.ts(54,5): error TS2322: Type '{ 'Content-length': number; Authorization: string; }' is not assignable to type 'HeadersInit'.
  Types of property ''Content-length'' are incompatible.
    Type 'number' is not assignable to type 'string'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 2.

lerna ERR! yarn run build exited 2 in '@metaplex/cli'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Operating system

MAc os10.15.7 

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Khushhal23** [comment]
Hello!
1. You don't need to do yarn build, yarn install is enough
2. If you still want to do it, then first do npm install lerna, then yarn build:)
