### ISSUE TITLE
[Failure]:Notable to init store

### ISSUE THREAD

**Issue by frankcjw** [metaplex-foundation/metaplex#1821]
### Which package is this bug report for?

storefront

### Issue description

clone repo
cd metaplex/js
yarn install && yarn bootstrap && yarn build
yarn start
navigate to IP:3000
only connect on the screen
no init button shown on the screen
after click on connect and connect my wallet , finally stuck in loading.
![微信图片_20220219000026](https://user-images.githubusercontent.com/6236022/154717718-f719dcf9-0e7b-4066-bbb1-da6c01d74120.png)

### Operating system

Centos

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by THEOGHANGMAN** [comment]
same.. any solve for this?

**Comment by cctogs** [comment]
Same issue here? Any help??

**Comment by stegaBOB** [comment]
For the initial init it takes a really long time to load. There are a ton of issues with the storefront right now. Sometimes stuff works, sometimes it doesn't. Really hard to debug since everything is technically working on my end. This will be changing hopefully soon. In the meantime Holaplex is a great alternative if you want to set up your own store! Sorry for the inconvenience.

**Comment by comicsaint** [comment]
> 

After a reinstallation and updating the wallet to devnet where there are funds I got it to play. It took a very long time and init didn't work the first time either but after a reload it seems to be up and running.

**Comment by frankcjw** [comment]
> After a reinstallation and updating the wallet to devnet where there are funds I got it to play. It took a very long time and init didn't work the first time either but after a reload it seems to be up and running.

Did you init it successfully ?

**Comment by comicsaint** [comment]
> > After a reinstallation and updating the wallet to devnet where there are funds I got it to play. It took a very long time and init didn't work the first time either but after a reload it seems to be up and running.
> 
> Did you init it successfully ?

Yes it worked after reinstallation and setting up the wallet correctly
