### ISSUE TITLE
Whitelist Token not burned whilst in Presale with Captcha [Bug]: 

### ISSUE THREAD

**Issue by billionairesharksociety** [metaplex-foundation/metaplex#1824]
### Which package is this bug report for?

candy machine cli

### Issue description

There seems to be an error with CandymachineV2 and the captcha that won't allow whitelist tokens to be spent while the Gatekeeper is on in the candy machine config and the start date is in the future (whitelist presale mode). I think this is an issue the candy machine itself and the way it deals with its own captcha process. You'll have to have the captcha turned off during whitelist/presale and then turn it back on if you want to use it for public sale.

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DojoSoMope** [comment]
Did you create the spl-token with decimals 0 ?

**Comment by Khushhal23** [comment]
Please set "mode" : { "burnEveryTime": true }, in whitelistSettings and also check if the token address is correct and if it's 0 decimals
