### ISSUE TITLE
[Bug]: error: unknown command 'generate_art_configurations' -Missing command?

### ISSUE THREAD

**Issue by acesaiah** [metaplex-foundation/metaplex#1825]
### Which package is this bug report for?

candy machine cli

### Issue description

![image](https://user-images.githubusercontent.com/100072798/154840462-82c2dc3f-6b1a-404b-81ed-a53d3e1d2e70.png)

### Command

```shell
ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts
```

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DojoSoMope** [comment]
as per the commit listed below, the generator has been deprecated
[https://github.com/metaplex-foundation/metaplex/commit/4072643f9c3a572ffeb212e9f89e605bb19854e3](url)

**Comment by chronicthread** [comment]
So should we use hashlips instead to generate the art and the json files?

**Comment by febo** [comment]
Have a look at https://docs.metaplex.com/community - there are a couple of options listed there.
