### ISSUE TITLE
[Bug]: Class DataV2 is missing in schema: data

### ISSUE THREAD

**Issue by lminor** [metaplex-foundation/metaplex#1830]
### Which package is this bug report for?

storefront

### Issue description

Running on localhost for both devnet and Mainnet-beta while following the information here https://docs.metaplex.com/storefront/create to create an NFT I receive the attached error every time.
<img width="580" alt="Screen Shot 2022-02-21 at 11 48 49 AM" src="https://user-images.githubusercontent.com/4603043/154997749-a7e66859-6bb2-42c9-8884-daa29ade82b0.png">

### Operating system

Mac OS 11.6.4

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by KaijuC** [comment]
I am running into the same issue. Is this due to not changing something from the repo?

**Comment by Fazatholomew** [comment]
Having the same issue:

- MacOS 11.6
- Main Net

**Comment by NIDAYIFU** [comment]
Having the same issue:
MacOS 12.2.1
DevNet

**Comment by contract1** [comment]
Having the same issue:
Windoews 10
TestNet

"Class DataV2 is missing in schema: data"

**Comment by p0sidonz** [comment]
Same issue on the master branch
Windows11
DevNet
"Class DataV2 is missing in schema: data"

**Comment by andyfife** [comment]
I get same response on localhost, on vercel deployment i get "class g is missing in schema :data"

**Comment by AN8991** [comment]
Have the same issue: Ubuntu 20.04 /Test

**Comment by catalincatuna** [comment]
same issue windows 10 devnet :(

**Comment by jx-bamboo** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/21121565/165881850-f59f5c0a-3e7a-43a4-917c-13864b50ee3c.png">

**Comment by zac404** [comment]
The problem still exists. Please open this issue again!

MacOS 12.4
localhost
DevNet

<img width="446" alt="Bildschirmfoto 2022-07-04 um 19 25 52" src="https://user-images.githubusercontent.com/65722765/177198241-bed485ea-04a8-4a6c-94aa-c21cdcaaa804.png">
