### ISSUE TITLE
[Bug]:  Error: 429 Too Many Requests

### ISSUE THREAD

**Issue by frasil1** [metaplex-foundation/metaplex#1832]
### Which package is this bug report for?

candy machine cli

### Issue description

Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 4000ms delay...
Server responded with 429 Too Many Requests.  Retrying after 2000ms delay...
C:\Users\bugae\v1\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:849
        callback(new Error(`${res.status} ${res.statusText}: ${text}`));
                 ^
Error: 429 Too Many Requests:  {"jsonrpc":"2.0","error":{"code": 429, "message":"Too requests from your IP, contact your app developer or support@rpcpool.com."}, "id": "16a9332a-0440-4ac7-9101-26a86278cd7e" }

    at ClientBrowser.callServer (C:\Users\bugae\v1\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:849:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 Please help, I can't find a fix for this problem
![image](https://user-images.githubusercontent.com/96686007/155032785-eea033cb-2e96-45c5-9794-96297e6efddf.png)

### Command

```shell
ts-node \metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k slrnew.json \
    -cp config.json \
    -c cache \
    \assets
```

### Operating system

WIndows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DojoSoMope** [comment]
use an rpc

**Comment by frasil1** [comment]
![image](https://user-images.githubusercontent.com/96686007/155102593-0e0896c5-946e-4722-95ac-faa97df90953.png)
this solved my problem

**Comment by frasil1** [comment]
"batchSize": 5000

**Comment by labyla** [comment]
where is the config.json file located?

**Comment by edujr1** [comment]
Guys, 
where is the config.json file located? Pls

**Comment by KrsnaAgr** [comment]
very helpfull, thanks !!

**Comment by hoyame** [comment]
> use an rpc

?

**Comment by ameliazsabrina** [comment]
solved the problem by changing the wifi into using my personal hotspot, this is because the IP address changed into my mobile's IP
