### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'program')

### ISSUE THREAD

**Issue by Squidskerz** [metaplex-foundation/metaplex#1833]
### Which package is this bug report for?

candy machine cli v2

### Issue description

After running candy machine upload command I tried deleting and reimporting the original .cache file since the mint resulted in unrecognized tokens and a large loss of SOL... I am trying to verify the upload since everything seems to be working and can be viewed in arweave. Please help! I just want to mint a portion to be freely distributed and have another portion able to be minted by the user.

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts verify_upload --keypair ~/.config/solana/mainnet.json
```

### Relevant log output

```shell
wallet public key: DHM1mtD6wSMwSwYGMYkZ7uMPa5jBG67HFqkBWNu83nFf
C:\Users\Zgkra\OneDrive\Desktop\PROJECT FILES\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:471
                                 ^
TypeError: Cannot read properties of undefined (reading 'program')
    at Command.<anonymous> (C:\Users\Zgkra\OneDrive\Desktop\PROJECT FILES\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:471:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Khushhal23** [comment]
Hello! Please add -e (--env) according to the network and also add -c It's not a bug
