### ISSUE TITLE
[Feature]: Gumdrop wallets airdrop limit

### ISSUE THREAD

**Issue by yamijuan** [metaplex-foundation/metaplex#1835]
### Which package is this feature request for?

gumdrop

### Feature

There is nothing in the docs that tells users what's the technical limit of gumdrop

### Ideal solution or implementation

I'd like to know the technical limitations of wallets for gumdrop airdrop

**Comment by stegaBOB** [comment]
Please reopen this PR in the docs repo. https://github.com/metaplex-foundation/docs/issues.
Thanks!
