### ISSUE TITLE
[Bug]: Class g is missing in schema: data

### ISSUE THREAD

**Issue by andyfife** [metaplex-foundation/metaplex#1836]
### Which package is this bug report for?

storefront

### Issue description

When I go to mint an NFT i get the following error alert..."Class g is missing in schema: data"
What is the class g schema data?

### Operating system

ubuntu 20.04

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by KurtCMrD** [comment]
Got this error as well.
