### ISSUE TITLE
Auctions with reservation prices can accidentally kill bids for users that try to reset bid underneath reservation price

### ISSUE THREAD

**Issue by bhgames** [metaplex-foundation/metaplex#184]
If you try to bid 0 in reservation price auction, it'll fail, but way to change bid right now is cancel and place are in separate tx's, so bidding 0 and it failing causes you to lose your current bid. Should place ins ame tx for atomicity.

Wallet with this example:
7iGCFYLUJczcHwpUnCCK5QFBCvYwznnj82RoYQQnWu6d
SPL wallet used for Monk auction
j_ — Today at 11:17 AM
https://explorer.solana.com/tx/46ddLdJFhFUoYqt9sFF3sBKkfTWKiDmZq44hwRvrHxE1jjrBWbKGx1KiGEFXobiAgR39hZRm6jWHGVjM6xtaWG1u so it looks lik ehere was your last successful bid for maybe 1.5 SOL. Then you tried to reset your bid to 0 several times but this was not allowed due to the reservation price setting of the auction, but the way the UI was set up it issued a cancel in one txn and then a bid in another txn so the cancel went through but the place bid did not (due to the reservation price restriction). So what happened was you ended up after the "0" attempt with no bid, when you would reasonably expect to just end up backw here you startd (with a 1.5 sol bid). So this is a bug in the UI, it should put the cancel and place bid in a single txn so if one fails, the other does too, and nothing bad happens to your bid. (The only way to change a bid in the current setup is to cancel and then re-place it). Then you tried to place a bid one more time but it failed because auction ended here, but by then you had no active bids so you got nothing. https://explorer.solana.com/tx/3YpPVkxcS7yvYpQML2Fzp6AFZSdWtFRSqYrYPxSdxgW4TJZkUUZbGpXsr8XauvP9r72zo6iU1WYv2VBiZPwqhPLU

**Comment by bhgames** [comment]
Also should note that the user never entered 0 themselves. Somehow though it did happen:

https://explorer.solana.com/tx/4JchsP1cepcAh1DusjbrvUfhUa2M65mA127qqEDr4Q1KqKNvQbX4aq4N64SinogeobR4P6QNouTKPWZDu5fGfJTa

We got to a place where 0 bids being submitted. Either the rust contract transmuted submitted bid number to 0 or the UI falsely submitted 0 after converting from input.

**Comment by bariOmymen** [comment]
hey, how to reproduce this and test my changes on localhost?
