### ISSUE TITLE
[Bug]: Cannot select nft to sell/auction

### ISSUE THREAD

**Issue by andyfife** [metaplex-foundation/metaplex#1842]
### Which package is this bug report for?

storefront

### Issue description

After creating nft, it shows up in my phantom wallet. however i can not select it when i want to initiate a sell/auction.
the created nft shows up on solscan as  "minted 0 of 1 "

![Screenshot from 2022-02-22 19-49-57](https://user-images.githubusercontent.com/75646113/155258899-4db69a71-aa26-4cb3-a109-7f085ac0a7c7.png)

### Operating system

ubuntu 20.04

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by yamijuan** [comment]
Have you tried going to `my items` menu option first and then try to sell

**Comment by andyfife** [comment]
Yes,
Even though the NFT’s appear in my wallet( browser) they do not appear in
“my items”
On solscan it says 0of1 minted .
If I send the nft from my wallet I just created in the store to another
phantom wallet then connect the second wallet to my metaplex store those
“sent” NFT’s show up in “my items”....

**Comment by yamijuan** [comment]
are them verified by all creators? I think the storefront don't allow to sell non verified NFTs

**Comment by andyfife** [comment]
I am the only creator.... I create them in my store, then when I am
presented with the option to then sell the nft they do not show up. Even
though they are now in my phantom wallet.

**Comment by cryptorrivem** [comment]
that usually happens when you added more creators for royalties, please confirm in solscan the creators section of the nft is only one and that it has the ✅

**Comment by andyfife** [comment]
Thanks for your reply. That is not the issue. Here is the state of play.
I have a metaplex store, address xyz.......
I can create an NFT
this NFT shows up thereafter in my wallet.
I can send this NFT to another wallet.
I CANNOT put the NFT up for sale/ auction. My metaplex store does not
recognize the NFT I just created. See original screenshot above.

**Comment by andyfife** [comment]
my store is
spaceresearchlab.com

i have the following in my phantom wallet, which i created.. yet i cannot
sell it in my store....
https://solscan.io/token/C7m78LoPt9HbuTmaf6AR4fL5ohR5MgnyFNPMjTkVR7rZ

not sure how to share admin page as it is connected to my store address...

**Comment by stegaBOB** [comment]
> not sure how to share admin page as it is connected to my store address...
Very good point. I think I meant just sharing the store address haha. Thanks!

**Comment by stegaBOB** [comment]
I'm not entirely sure why it isn't showing. Everything looks correct? Would you be able to update to the latest version? Looks like your storefront is a bit behind right now.

**Comment by andyfife** [comment]
I updated to latest version... same problem.
If I create another “creator” with a different wallet address then it
works... it doesn’t work when the creator wallet address = store address
(env).

**Comment by stegaBOB** [comment]
what do you mean by "creator wallet address = store address"?

**Comment by andyfife** [comment]
I have a phantom wallet address 9........
I used that address in the .env file when I deployed the store.
When my wallet address is connected to my store, my store does not
recognize any nft,’s in my wallet, hence I cannot sell any NFT’s I create
in my own store.

**Comment by stegaBOB** [comment]
I'm not quite sure why that is happening. On my store that I created I can indeed see the NFTs I have minted using that wallet. I'm going to check the RPC requests and see what it is saying

**Comment by andyfife** [comment]
I can create another "creator" in the admin. This creator can function
properly on the site... they can create and sell items . my problem is the
store wallet address cannot slell items it creates..... store wallet
address = address in .env file

**Comment by reynolkb** [comment]
@stegaBOB I actually am running into this issue as well. I created an NFT collection with the candy machine and was able to mint them to multiple wallets fine. However, they are not showing up when I go to sell them on the storefront. 

I have three wallets (Wallet A, Wallet B and Wallet C). I created the Candy Machine collection with Wallet A. I minted 1 NFT with Wallet B and 1 NFT with Wallet C. I created the storefront with Wallet B. I whitelisted Wallet A, Wallet B and Wallet C on the storefront.

When I try to sell the NFTs I minted with Wallet B and Wallet C from the candy machine created by Wallet A they are not appearing to sell on the storefront. Do you have any suggestions?
