### ISSUE TITLE
CandyMachine UI mint sales not sending/splitting properly

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [metaplex-foundation/metaplex#1844]
> that does not happen automatically, once the auction finishes you need to go to that auction page + `/billing` and settle the funds

>Yes, now I have seen where I can find this information? Can I also remove auctions that ended later from the store? I did not find it specified that to put an NFT's up for auction you need $ 6 in commissions I think from the store bot. Could you help me with these questions?

>_Originally posted by @stetommy in https://github.com/metaplex-foundation/metaplex/issues/1796#issuecomment-1041582559_

Does the above also apply to those still minting? I have used CM2  and have a live mint, and upon testing the split does not occur as it is supposed to.

I have 3 creators the funds should split between, 50%, 45% and 5%. Price is 0.03 sol per nft. And only one has received aby payment, and not the correct amount.

TX: 
https://explorer.solana.com/tx/4W8jNYS8N2nvY5BpUkoqGBSAfLjg9MNbLkxsNan1M62cx2VS6C2jNpVxRXpotEdAaZyLMQdcPBAm8ypveZdAhrdo

**Comment by yamijuan** [comment]
You will only receive payments in the treasury account you set in the CM config

**Comment by l8nit3tr0ubl3** [comment]
so the creators split in metadata is only for secondary sales? I must have misunderstood that. By the documentation I assumed the creator split applied to minting proceeds aswell.
