### ISSUE TITLE
[Bug]: Auction House CLI buy fails with error 0x7d0

### ISSUE THREAD

**Issue by rzcoder** [metaplex-foundation/metaplex#1848]
### Which package is this bug report for?

other cli

### Issue description

Auction House CLI buy command started to fail with code 0x7d0 recently

step to reproduce:
1. call ah cli buy command

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/auction-house-cli.ts buy \
-k <my keypair> \
-ah <my auction house> \ 
--buy-price 0.01 \
--token-size 1 \
--mint <my mint key>
```

### Relevant log output

```shell
wallet public key: 2jZ7EmMSb19DpdkmDk1Jy2KHi7TQk2UVQCi2NNwXDMqH
Rejected via websocket { InstructionError: [ 0, { Custom: 2000 } ] }
Timeout Error caught {
  err: { InstructionError: [ 0, [Object] ] },
  slot: 117007441,
  confirmations: 0
}
/Users/rzcoder/metaplex/js/packages/cli/src/helpers/transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: Custom program error: 0x7d0
    at sendSignedTransaction (/Users/rzcoder/metaplex/js/packages/cli/src/helpers/transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (/Users/rzcoder/metaplex/js/packages/cli/src/helpers/transactions.ts:59:26)
    at async Command.<anonymous> (/Users/rzcoder/metaplex/js/packages/cli/src/auction-house-cli.ts:1039:5)
```

### Operating system

mac os

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by RustySol** [comment]
Also encountering this issue!

**Comment by junedkR** [comment]
Facing same error

**Comment by RustySol** [comment]
I think this is related to the `transferAuthority`. If you change the value passed into `transferAuthority` to the `wallet` address, should probably work

**Comment by RustySol** [comment]
should be related to this https://github.com/metaplex-foundation/metaplex/pull/1847#issue-1149782857

**Comment by rzcoder** [comment]
It was `transferAuthority`, fixed now
