### ISSUE TITLE
Cannot Load Airdrop Funds in New Wallet

### ISSUE THREAD

**Issue by cctogs** [metaplex-foundation/metaplex#1852]
### Which package is this bug report for?

candy machine cli

### Issue description

When I use Solana Airdrop 2 / I get: Error: airdrop request failed. This can happen when the rate limit is reached.
There are no funds in this wallet.

### Operating system

Mac OS

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
The solana airdrop tool has been shaky for quite a while. Try using https://solfaucet.com/ instead.
