### ISSUE TITLE
Upload is 'successful' but verification fails

### ISSUE THREAD

**Issue by summerplaybook** [metaplex-foundation/metaplex#1856]
### Which package is this bug report for?

candy machine cli

### Issue description

The upload says it is successful, but then the verification fails. When I rereun upload, it continues to say that the upload was successful but the verification keeps failing.

As this is the core workflow for people, I'm escalating its severity due to usage/ core integrity

![image](https://user-images.githubusercontent.com/12703955/155852710-c7e52efa-e8c0-4b22-b230-172688ab0541.png)

### Command

```shell
npx ts-node candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/abcnft.json -l debug -cp cmConfig.json -c cache assets

npx ts-node candy-machine-v2-cli.ts verify_upload -e mainnet-beta -k ~/.config/solana/abcnft.json -l debug  -c cache
```

### Relevant log output

```shell
after the 'successful upload'
setting the log value to: debug
wallet public key: EaBsNrVR8EMcDXzwsNAULbtXcotLSA3GJp41crX6Erws
program id from anchor cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ
WARNING: Skipping unsupported file type assets/.DS_Store
Beginning the upload for 501 (img+json) pairs
started at: 1645895979663
config for a candy machine with publickey: HoikDsE1TjjRb5WpEcGakZK3CVzDaH1VKyYZ3EMcsVmF has been already initialized
Uploading Size 0 undefined
Writing indices 120-130
Done. Successful = true.
ended at: 2022-02-26T17:20:15.999Z. time taken: 00:00:36


verification output
wallet public key: EaBsNrVR8EMcDXzwsNAULbtXcotLSA3GJp41crX6Erws
program id from anchor cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ
Key size 10
Looking at key  120
Looking at key  121
Looking at key  122
Looking at key  123
Looking at key  124
Looking at key  125
Looking at key  126
Looking at key  127
Looking at key  129
Looking at key  130

/Users/lukeheine/Documents/abcnftWorkspace/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:524
      throw new Error(
            ^
Error: not all NFTs checked out. check out logs above for details
    at Command.<anonymous> (/Users/lukeheine/Documents/abcnftWorkspace/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:524:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

Mac OS Monterrey 12.0.1

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Our logs should definitely be improved for the verify command. its difficult to tell what exactly is going on there.

**Comment by summerplaybook** [comment]
Yeah I have zero idea - any tips @stegaBOB? I've withdrawn from the candy machine and rerun multiple times (obviously deleting the cache). I've also reprepared my metadata and found that the error occured again but at a different index.

**Comment by stegaBOB** [comment]
Okay I think I know the problem. This seems to be a duplicate of #1516. The fix for that is listed there. I will investigate further and work on fixing this problem.

**Comment by stegaBOB** [comment]
@summerplaybook can you try again on the latest version?

**Comment by andrey792** [comment]
I have the exact same error, I need immediate help 
<img width="1091" alt="Screenshot 2022-04-08 at 23 50 12" src="https://user-images.githubusercontent.com/95539629/162477724-3b94a40c-20f9-40ab-98cb-2f99c727f39f.png">
