### ISSUE TITLE
Edit Front end[Feature]: 

### ISSUE THREAD

**Issue by KIMLIcrea** [metaplex-foundation/metaplex#1872]
### Which package is this feature request for?

storefront

### Feature

How to edit the front end? what software do you recommend for beginner professional dev ?

thank you

### Ideal solution or implementation

It would be great if you could import esayly the website in html editor
thank you

**Comment by stegaBOB** [comment]
The storefront is built in React right now. If you want to learn how to customize it (and are willing to spend a bit of time learning to code in react!), there are some great resources out there. There's a react course on codecademy.com thats quite helpful.
