### ISSUE TITLE
[Bug]: Candy Machine cannot upload a set of mixed format assets

### ISSUE THREAD

**Issue by srazzak** [metaplex-foundation/metaplex#1874]
### Which package is this bug report for?

candy machine cli

### Issue description

I was trying to upload a set of assets with different file formats (MP4 and PNG) and it appears that it won't accept multiple types of assets. The upload command will raise the error I've added below.

After reviewing those lines of code, my guess is that after it filters the supported files, it does a count of both animated files and image files within the `animatedFileCount` and `imageFileCount` variables. But then when the asset to JSON file count check happens it compares only one of them. So if one were to have 8 PNG files and 2 MP4 files, the comparison will always fail since 8  != 10 and 2 != 10. 

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp config.json -c example assets
```

### Relevant log output

```shell
(node:28512) UnhandledPromiseRejectionWarning: Error: number of animation files (2) is different than the number of json files (96)
    at Command.<anonymous> (C:\Users\User\Documents\GitHub\minting\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:201:13)
```

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Ah I get the issue here. I didn't read this properly. All NFTs need an image field. Explorers and wallets will default to that if they don't support the animation file yet.

**Comment by DominicTobias** [comment]
> Ah I get the issue here. I didn't read this properly. All NFTs need an image field. Explorers and wallets will default to that if they don't support the animation file yet.

Thanks I didn't get this either

**Comment by CurrencG** [comment]
@DominicTobias were you able to find out any more about this? I am also trying to figure out how the mp4 format needs to be labeled.
