### ISSUE TITLE
[Bug]: Not able to find my NFT

### ISSUE THREAD

**Issue by sarangjain40** [metaplex-foundation/metaplex#1882]
### Which package is this bug report for?

candy machine cli

### Issue description

I have uploaded 2 NFTs on Arweave succesfully ( Its actually 2 images so I guess they will be counted as 2 NFTs)

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet -k ~/.config/solana/mywallet.json -cp config.json  -c example4 assets/
wallet public key: A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type assets/.cache
WARNING: Skipping unsupported file type assets/0.json_bkp
WARNING: Skipping unsupported file type assets/backup
Beginning the upload for 2 (img+json) pairs
started at: 1646239550137
initializing candy machine
initialized config for a candy machine with publickey: 8shAHzQzzJjqikDmiAaeskU4rSUmuC4bW7p8ZUFVRGZe
Uploading Size 2 { mediaExt: '.png', index: '0' }
Processing asset: 0
Processing asset: 0
Processing asset: 1
Writing indices 0-1
Done. Successful = true.
ended at: 2022-03-02T16:46:35.351Z. time taken: 00:00:45
------------------------------------------------------------------------------------------
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts show     -e mainnet     -k ~/.config/solana/mywallet.json     -c example4
wallet public key: A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
...Candy Machine...
Key: 8shAHzQzzJjqikDmiAaeskU4rSUmuC4bW7p8ZUFVRGZe
authority:  A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
wallet:  A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
tokenMint:  null
uuid:  8shAHz
price:  1000000000
itemsAvailable:  2
itemsRedeemed:  0
goLiveDate:  2021-12-25T00:00:00.000Z
symbol:  SJ1
sellerFeeBasisPoints:  500
creators:
A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4 at 100 %
maxSupply:  0
retainAuthority:  true
isMutable:  true
hidden settings:  null
No end settings detected
No captcha for this candy machine
no whitelist settings
--------------------------------------------------------------------------------------------
After this i did the minting part 

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts mint_multiple_tokens     -e mainnet     -k ~/.config/solana/mywallet.json     -c example4     --number 2
Minting 2 tokens...
wallet public key: A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
No instructions provided
No instructions provided
transaction 1 complete 3hSp2fhXSqNLtbVWJoDtWuoy7iDLyXcAGuCAbLeTMhVNiYA9NCbuJ2uGJNtZ2e7LSGknci2gvxXrqAu8mUSQi9Ma
minting another token...
wallet public key: A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
No instructions provided
No instructions provided
transaction 2 complete 5L755xvpm9k64yNtsdVexdnX3CGrJyh3xfixG4NXipDrug5JvwA24Qw5fPc4Pd7SwpqD94LFE7c8JdEPox36u4Ev
minted 2 tokens
mint_multiple_tokens finished

----------------------------------------
Still I see nothing on my Phantom APP. Please help me and tell me where am I going wrong or I am missing something,.

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet -k ~/.config/solana/mywallet.json -cp config.json  -c example4 assets/
```

### Relevant log output

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet -k ~/.config/solana/mywallet.json -cp config.json  -c example4 assets/
wallet public key: A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type assets/.cache
WARNING: Skipping unsupported file type assets/0.json_bkp
WARNING: Skipping unsupported file type assets/backup
Beginning the upload for 2 (img+json) pairs
started at: 1646239550137
initializing candy machine
initialized config for a candy machine with publickey: 8shAHzQzzJjqikDmiAaeskU4rSUmuC4bW7p8ZUFVRGZe
Uploading Size 2 { mediaExt: '.png', index: '0' }
Processing asset: 0
Processing asset: 0
Processing asset: 1
Writing indices 0-1
Done. Successful = true.
ended at: 2022-03-02T16:46:35.351Z. time taken: 00:00:45
```

### Operating system

linux

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
The file system wallet isnt neccesarily the same as the wallet in phantom. Youd need to import that file system wallet by copy/pasting the text inside the keypair.json file into the import private key option in phantom. The wallet the nfts were minted to (on devnet) is A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
