### ISSUE TITLE
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by jakoboo1** [metaplex-foundation/metaplex#1886]
### Which package is this bug report for?

candy machine cli

### Issue description

After i ran the following command:

ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet-poging.json \ -cp config.json \ -c js/packages/cli/example-assets 

This error message showed up

wallet public key: EFcLTyRgWkwcHgAHTVU3mnZfX1KN3fHNPt..............(My wallet address)
(node:31368) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type \$RECYCLE.BIN
WARNING: Skipping unsupported file type \$WinREAgent
WARNING: Skipping unsupported file type \ComboKey
WARNING: Skipping unsupported file type \Documents and Settings

Beginning the upload for 10 (img+json) pairs
started at: 1646298020025
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\Users\user\OneDrive\Bureaublad\testen nft\SolDingen\metaplex-master\js\packages\cli\src\commands\upload.ts:102:24)
    at Command.<anonymous> (C:\Users\user\OneDrive\Bureaublad\testen nft\SolDingen\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:228:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'

I tried to re-run the command but it still didn't work.
I have no idea how it happens. I followed the metaplex documentation and everything went well until this moment. 
Help please!

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet-poging.json \ -cp config.json \ -c js/packages/cli/example-assets
```

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
You're missing the path argument. You need to add the path to the folder of assets you are uploading.
