### ISSUE TITLE
Create Auction Screen stuck when transaction failed

### ISSUE THREAD

**Issue by jamland** [metaplex-foundation/metaplex#189]
UI ISSUE:

Auction creation failed when I'm trying to sell the limited item with more copies than allowed.
Which is good but I can't see any messages about it only 99% screen.

![image](https://user-images.githubusercontent.com/188568/128386306-d2634adf-a8b2-4a07-943f-843b46d72728.png)

I checked console for the error and later noticed RECLAIM message in notifications list. But this is kinda unclear .
Would be better to show some error message instead of the loading screen.

![image](https://user-images.githubusercontent.com/188568/128386474-0de55139-faa7-4e0b-9682-01ee5c2dd56c.png)

**Comment by SolariumNFT** [comment]
bump. also ran into this issue when simulating a buyer using the secondary marketplace. except my NFT has actually left the auctioneers wallet and i can't find it.
