### ISSUE TITLE
[Bug]: Error: Transaction failed: Custom program error: 0xbba

### ISSUE THREAD

**Issue by kcc0** [metaplex-foundation/metaplex#1891]
### Which package is this bug report for?

candy machine cli

### Issue description

I've been facing this issue on the `mainnet` since last night. 
Seems like there's an issue with CandyMachine. We're not able to mint anything right now and it's a MAJOR issue at this point.

Any help here would be much appreciated.

<img width="1512" alt="Screenshot 2022-03-04 at 11 01 40 AM" src="https://user-images.githubusercontent.com/4690646/156735341-7ac681c4-3b4e-4f89-a847-731061fcf825.png">

[mint.breadheads.io-1646385681113.log](https://github.com/metaplex-foundation/metaplex/files/8184597/mint.breadheads.io-1646385681113.log)

### Relevant log output

```shell
Log file attached in the description.
```

### Operating system

Mac OS Monterey 12.2.1

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by CryptoCooka1** [comment]
Same issue here.

**Comment by stegaBOB** [comment]
Are you still running into this issue? I believe we fixed this?

**Comment by Rafagom** [comment]
Same issue here. I'm only able to mint NFTs using the whitelistMintSettings. 
Without the whitelist token the the contract does not load, as if the candy machine is not yet open.

**Comment by stegaBOB** [comment]
Have you tested this within the past 10 hours?

**Comment by stegaBOB** [comment]
Please send examples of txns that are failing

**Comment by Romahlio** [comment]
Hey @stegaBOB This is Mahlio from the discord. This is the exact issue I'm having

**Comment by kcc0** [comment]
> Have you tested this within the past 10 hours?

Yes! Still happening!
Tested 1 minute ago.

https://solscan.io/tx/2Na1dU4KvAJUsfeSRGG7NUfjRzUzW3oob3VifcsaAGhjAVFpiVhSj5Xv4VDYUsvVqTsvKyEG9k38NkHv4MpTbbsc

**Comment by kcc0** [comment]
> Please send examples of txns that are failing

Another example from 12 hours ago.

https://solscan.io/tx/5UuTWV2FYvGLv1KTsKuN8fyJHFPu6Fg9inkoGrzExqtBVTY7jVhpG7QrhFuFAQ5Wb98TYVHTJHdLbbPU6S2rWBjY

**Comment by stegaBOB** [comment]
Thank you! My #1 priority right now is resolving this issue.

**Comment by kcc0** [comment]
> Thank you! My first priority right now is resolving this issue.

Appreciate it ser. Thank you!
Will keep a close eye on this.

**Comment by alfongj** [comment]
hundreds of transactions failing on this CM with this error -> https://explorer.solana.com/address/B3cQeaz4wBD52cT6bgFBk3Vi1hLm3wsL5TFFequ7E3mr

**Comment by stegaBOB** [comment]
I believe we have a fix. We are just doing some final testing.

**Comment by breadheadsnft** [comment]
> I believe we have a fix. We are just doing some final testing.

Excited, your work is much appreciated!

**Comment by stegaBOB** [comment]
Fix is live on devnet. Should hopefully be on mainnet soon.

**Comment by stegaBOB** [comment]
Deployed on mainnet. Please test out your mints and let us know if they work!

**Comment by kcc0** [comment]
> Deployed on mainnet. Please test out your mints and let us know if they work!

Hell yeah brother!!! 

You are the duuuuuude! Working fine on mainnet right now. 

Thank you so much ser. And to anyone else who contributed to the fix!
