### ISSUE TITLE
[Bug]: Candy Machine Initialization on Devnet fails

### ISSUE THREAD

**Issue by MaximeLassalleHub** [metaplex-foundation/metaplex#1893]
### Which package is this bug report for?

candy machine cli

### Issue description

1. Install CLI
2. Upload the docs collection

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/id.json -cp config.json -c example ./assets
```

### Relevant log output

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/id.json -cp config.json -c example ./assets
wallet public key: EHi2fewwqBkmEXZPcN5iTc6qKQbw54y2vSfdxp6nRz5i
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.
Beginning the upload for 10 (img+json) pairs
started at: 1646394250253
config for a candy machine with publickey: <key> has been already initialized
[10] out of [10] items have been uploaded
Writing all indices in 1 transactions...
Progress: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 0/1Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded.
Done. Successful = false.Transaction (metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2781:13)
ended at: 2022-03-04T11:45:15.486Z. time taken: 00:01:05metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
```

### Operating system

MacOS & Ubuntu

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DavidBarrick** [comment]
Same for me on `mint_one_token` command. Timeout with both `https://api.devnet.solana.com` and custom quicknode rpc endpoint.

**Comment by stegaBOB** [comment]
Devnet is indeed having some issues. Nothing we can do on our end :/.

**Comment by cruncher87** [comment]
Same issue here, 
Is this only devnet fault? So should not happen on the mainnet? 
Thanks

**Comment by DavidBarrick** [comment]
> Same issue here, Is this only devnet fault? So should not happen on the mainnet? Thanks

I haven't seen any reports of mainnet issues, just devnet. Even the cli airdrop command doesn't work on devnet.
