### ISSUE TITLE
[Bug]: When minting returns findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by uraxlizard** [metaplex-foundation/metaplex#1898]
### Which package is this bug report for?

candy machine ui

### Issue description

Just yarn start and try to mint.

### Operating system

Ubuntu 20.04

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by PedroLealLopes** [comment]
This is because in the index.tsx it is rendering 
`<React.StrictMode>
  <App />
  </React.StrictMode>
` if you change this to just be <App /> it fixes the error

**Comment by uraxlizard** [comment]
Now it returns TypeError: signers is undefined
