### ISSUE TITLE
[Bug]: Mint button Grayed Out

### ISSUE THREAD

**Issue by ThePanthersClub** [metaplex-foundation/metaplex#1905]
### Which package is this bug report for?

candy machine ui

### Issue description

Did everything as usual but mid-way in the project encountered an error that had me trying to withdraw candy machine. It didn't work. Eventually was able to upload the NFTs but with the same candy machine ID. Ran the verify command and it worked. When I build or use localhost the mint button is greyed out with the error.

![error](https://user-images.githubusercontent.com/92586275/156918733-aa988f6e-f8c4-4043-b541-234d030780ab.PNG)
Error: Account does not exist
at AccountClient.fetch (vendors~main.chunk.js:69796:13)
at async getCandyMachineState (main.chunk.js:1512:17)
at async main.chunk.js:644:22
I have confirmed that this is the candy machine id present in my cache file. It is also present when I run the show command.
Please can anyone help me with this

### Relevant log output

```shell
There was a problem fetching Candy Machine state
Error: Account does not exist
at AccountClient.fetch (vendors~main.chunk.js:69796:13)
at async getCandyMachineState (main.chunk.js:1512:17)
at async main.chunk.js:644:22
I have confirmed that this is the candy machine id present in my cache file. It is also present when I run the show command.
Please can anyone help me with this
```

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by merlox** [comment]
Two possible cases:
- Make sure you rename .env.example to .env. Then make sure you have the RIGHT candy machine smart contract ID. You can see it in the .cache folder.
- It could be because in the config.json (or however you called it) you've setup a wrong `goLiveDate`. If you set it to null or something like that it won't work. I recommend you do `Date.now()` in the chrome dev tools and use that timestamp there. Remember `null` will result in a grayed out mint button

**Comment by stegaBOB** [comment]
Also you have to use a custom RPC as well if you aren't doing so already.

**Comment by ThePanthersClub** [comment]
> ###

Is there any you recommend? I am doing everything correctly.

**Comment by ThePanthersClub** [comment]
> Two possible cases:
> 
> * Make sure you rename .env.example to .env. Then make sure you have the RIGHT candy machine smart contract ID. You can see it in the .cache folder.
> * It could be because in the config.json (or however you called it) you've setup a wrong `goLiveDate`. If you set it to null or something like that it won't work. I recommend you do `Date.now()` in the chrome dev tools and use that timestamp there. Remember `null` will result in a grayed out mint button

I correctly set the date settings, I know it sound stupid but is this my candy machine id? 
{ "program": { "uuid": "6JQs2i", "candyMachine": "redacted" },....

**Comment by dantgw** [comment]
@ThePanthersClub No it isn't. When you run the upload command on the terminal, look out for the message "initialized config for a candy machine with publickey: " It should appear slightly before the upload progress bar. Enter the public key that follows into REACT_APP_CANDY_MACHINE_ID in your .env file. The instructions weren't very clear so I had to figure this out too.

**Comment by stegaBOB** [comment]
https://docs.metaplex.com/candy-machine-v2/mint-frontend
