### ISSUE TITLE
[Bug]: How can I show the Mint button in real time?

### ISSUE THREAD

**Issue by ozknozsrt** [metaplex-foundation/metaplex#1912]
### Which package is this bug report for?

candy machine ui

### Issue description

I don't know whether this is a bug but, I have a problem, like this:

I use MintCountdown, and the MintButton comes when goLiveDate is finished, ok. But I have to refresh the page for the MintButton to come up. The MintButton does not coming in real time. How can I do that?

That's important for me. Because if a lot of people refresh the page at a time the server can crash.

Thanks in advance

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [x] I have checked the docs and it didn't solve my issue

**Comment by poisendev91** [comment]
[Third eye](https://discord.gg/UurzmJW3bC) 

Here I will help. Join discord to get some hint.
