### ISSUE TITLE
[Bug]: Can't mint because of the "0x7dc" error

### ISSUE THREAD

**Issue by merlox** [metaplex-foundation/metaplex#1915]
### Which package is this bug report for?

candy machine ui

### Issue description

1. Deploy the cli candy machine to the testnet with this config:
```json
{
    "price": 0.01,
    "number": 7,
    "gatekeeper": {
        "gatekeeperNetwork" : "ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6",
        "expireOnUse" : true
    },
    "solTreasuryAccount": "6z9nhc3VzRJ2UwFZqbgu6ZxRtmnBc32JvSFtizvcFZrU",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": 1646583165849,
    "endSettings": {
        "endSettingType": { "amount":true },
        "value": 7
    },
    "whitelistMintSettings": null,
    "hiddenSettings": null,
    "storage": "nft-storage",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "nftStorageKey": "(I'm using a real API key here)",
    "arweaveJwk": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false 
}
```
2. After a successful `upload` to testnet I start the candy machine UI by updating the `.env` file with the right candy machine deployed program ID.
3. I tried to mint and everytime I get this error:
```js
Signed txns length 1 vs handed in length 2
connection.tsx:366 Started awaiting confirmation for 3RzvVoWm4c4KGq9W3uq47QJd5ESy4t8VFfoprLHNRcsmic5z6E3Y4ZoFDcGmEDi5Cat8UoWf5wDnpyacGuqJH47m
connection.tsx:511 REST null result for 3RzvVoWm4c4KGq9W3uq47QJd5ESy4t8VFfoprLHNRcsmic5z6E3Y4ZoFDcGmEDi5Cat8UoWf5wDnpyacGuqJH47m null
candy-machine.ts:535 Error: Transaction failed: Custom program error: 0x7dc
    at sendSignedTransaction (connection.tsx:411:1)
```

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload -e testnet -k /Users/merunas/.config/solana/devnet.json -cp ./upload.json -c solarbears ./upload-files
```

Then inside `candy-machine-ui` I do:

```js
yarn start
```

### Relevant log output

```shell
Signed txns length 1 vs handed in length 2
connection.tsx:366 Started awaiting confirmation for 3RzvVoWm4c4KGq9W3uq47QJd5ESy4t8VFfoprLHNRcsmic5z6E3Y4ZoFDcGmEDi5Cat8UoWf5wDnpyacGuqJH47m
connection.tsx:511 REST null result for 3RzvVoWm4c4KGq9W3uq47QJd5ESy4t8VFfoprLHNRcsmic5z6E3Y4ZoFDcGmEDi5Cat8UoWf5wDnpyacGuqJH47m null
candy-machine.ts:535 Error: Transaction failed: Custom program error: 0x7dc
    at sendSignedTransaction (connection.tsx:411:1)
```

### Operating system

Mac OS big sur 11.0.1

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by merlox** [comment]
I execute the mint but the transaction in phantom always fails. Not sure why, have you guys tried to run it in testnet?

**Comment by merlox** [comment]
I execute the mint but the transaction in phantom always fails. Not sure why, have you guys tried to run it in testnet?

**Comment by merlox** [comment]
It looks like a CLI error. Can someone explain what that 0x7dc means?

**Comment by stegaBOB** [comment]
Our programs aren't deployed on testnet. Try using mainnet-beta or devnet, although the latest solana devnet release is like basically broken and nothing is working for our programs :/

**Comment by merlox** [comment]
can you deploy them to testnet or tell me which ones are so I can deploy them to testnet? testnet works sooo good tho

**Comment by merlox** [comment]
sounds like a pretty big deal that you can't run the app without deploying to mainnet. We should be able to run in all test networks AND localhost.
