### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of null (reading 'meta')

### ISSUE THREAD

**Issue by markm1992** [metaplex-foundation/metaplex#1920]
### Which package is this bug report for?

candy machine cli

### Issue description

Hi there, I'm trying to upload my collection to mainnet-beta, however I'm getting a type error.

This is my json...
`
{
  "price": 1,
  "number": 50,
  "gatekeeper": null,
  "solTreasuryAccount": "ACCOUNT HERE",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "07 Mar 2022 4:00:00 GMT",
  "endSettings": null,
  "whitelistMintSettings": {
    "mode": { "burnEveryTime": true },
    "mint": "TOKEN ADDR HERE",
    "presale": true,
    "discountPrice": null
  },
  "hiddenSettings": null,
  "storage": "arweave-sol",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "awsS3Bucket": null,
  "noRetainAuthority": false,
  "noMutable": false
}
`

And this is one of the jsons...

`
{
  "name": "NAME",
  "symbol": "",
  "description": "DESCRIPTION.",
  "seller_fee_basis_points": 500,
  "updateAuthority": "WALLET ADDR HERE",
  "image": "0000.png",
  "external_url": "URI HERE",
  "attributes": [
   // SEVERAL TRAITS HERE
  ],
  "collection": {
    "name": "NAME",
    "family": "NAME"
  },
  "properties": {
    "files": [
      {
        "uri": "0000.png",
        "type": "image/png"
      }
    ],
    "category": "png",
    "creators": [
      {
        "address": "WALLET HERE",
        "share": 100
      }
    ]
  }
}
`

### Command

```shell
ts-node ./src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/mainnet.json -cp candy-machine-upload-config.json -c test ./assets
```

### Relevant log output

```shell
`Uploading bundle via bundlr... in multiple transactions
0.020785503 SOL to upload
upload was not successful, please re-run. TypeError: Cannot read properties of null (reading 'meta')`
```

### Operating system

Ubuntu through WSL

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by merlox** [comment]
My dude you didn't change your json parameters you can't do this `"solTreasuryAccount": "ACCOUNT HERE"` you have to set your actual account. Same thing with the other fields.

**Comment by markm1992** [comment]
> My dude you didn't change your json parameters you can't do this `"solTreasuryAccount": "ACCOUNT HERE"` you have to set your actual account. Same thing with the other fields.

I obviously replaced this when posting here to github to not expose all of my details. Can  you please re-open this issue?

**Comment by markm1992** [comment]
@stegaBOB Hi there! Just pinging you for above. The issue is still present.
