### ISSUE TITLE
False display of successful redemption even if redeem fails due to rpc failure or other issue

### ISSUE THREAD

**Issue by bhgames** [metaplex-foundation/metaplex#193]
We need to correctly display that there was an issue when a redemption fails for some reason.

**Comment by jackson-sandland** [comment]
I'd like to take this on. Could you provide some more context regarding the issue?

**Comment by bhgames** [comment]
Go redeem an item after an auction is over. If it fails or something, it still says you won.

**Comment by jackson-sandland** [comment]
Is there a way to reproduce this locally?
