### ISSUE TITLE
[Docs]: Update Metaplex Docs To Include Pinata Storage Options

### ISSUE THREAD

**Issue by polluterofminds** [metaplex-foundation/metaplex#1933]
### Which package is this feature request for?

candy machine cli

### Feature

With the recent merge of Pinata support, we should get the Metaplex docs updated. I tried to find where those were hosted so I could open a PR to do so, but I couldn't find it. If I'm overlooking it, please point me in the right direction and I'd be glad to open a PR. 

The necessary info for the docs is included in the merged PR here: https://github.com/metaplex-foundation/metaplex/pull/1753

### Ideal solution or implementation

Update docs according to specification here: https://github.com/metaplex-foundation/metaplex/pull/1753

**Comment by stegaBOB** [comment]
https://github.com/metaplex-foundation/docs

**Comment by polluterofminds** [comment]
@stegaBOB One of my teammates opened a PR for the docs here: https://github.com/metaplex-foundation/docs/pull/232

Thanks!
