### ISSUE TITLE
[Bug]: Error: must use an integer for funding amount

### ISSUE THREAD

**Issue by cryptoboole** [metaplex-foundation/metaplex#1937]
### Which package is this bug report for?

candy machine cli

### Issue description

everything set up correctly, deployment on devnet works fine 20+ sol in authority wallet, candy machine creates but there is an issue with @bundlr-network 

### Command

```shell
ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
  -e mainnet-beta \
  -k ~/.config/solana/nft_deploy.json \
  -cp ./collection/config.json \
  -c nftcollection \
  ./collection/generated
```

### Relevant log output

```shell
NaN SOL to upload 132.900MB with buffer. Sending fund txn...
upload was not successful, please re-run. Error: must use an integer for funding amount
    at Fund.fund (/home/boole/repos/metaplex/js/node_modules/@bundlr-network/client/build/common/fund.js:21:19)
    at NodeBundlr.fund (/home/boole/repos/metaplex/js/node_modules/@bundlr-network/client/build/common/bundlr.js:34:28)
    at processBundle (/home/boole/repos/metaplex/js/packages/cli/src/helpers/upload/arweave-bundle.ts:615:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async uploadV2 (/home/boole/repos/metaplex/js/packages/cli/src/commands/upload.ts:245:11)
    at async Command.<anonymous> (/home/boole/repos/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:265:7)
```

### Operating system

Ubuntu 20.02

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by merlox** [comment]
can you show us your config.json? I'm 99% sure the error is there

**Comment by stegaBOB** [comment]
I got this error once I think as well. I think it has to due with the api call to check the price for a specific amount of bytes with bundlr failing and our cli interpreting that as NaN instead of throwing an error. Having better error handling on that method would be better. The solution in the meantime for this would just be to retry the upload.

**Comment by cryptoboole** [comment]
Update on my end. The temporary solution for it was to keep retrying. I might be wrong but I believe a component of this process relies on fetching the latest price from external services. That service was 

a) at times unavailable (mitigation: perhaps good to put in a check or more elaborate error catching)
b) some RPC clusters block the fetching all together (quicknode would not let me through)

Do you welcome outside contributions?

**Comment by cryptoboole** [comment]
@stegaBOB I think you are 100% right
