### ISSUE TITLE
[Bug]: Probably outdated docs, unusable software

### ISSUE THREAD

**Issue by hjertefolger** [metaplex-foundation/metaplex#1941]
### Which package is this bug report for?

storefront

### Issue description

Following all steps in docs, several times, using different wallets (Phantom, Solflare) - locally and also deployed (GitHub Pages, Netlify, Vercel) code has always resulted in error or in unusable state:

1. Loading animation is spinning without any progress/reason after every refresh (unusable site) - first loading after yarn start, also fresh first load, and also after initialising the store - single refresh on any subpage or home page, for example on Create a new item takes just 10 minutes to stop loading, and often resulting in a browser error stopping the page anyway
2. Create NFT after store init always resulting in error - minting is unusable (whether I'm trying to do it locally or deployed online)
3. I've tried several wallets, fresh clones/forks, deployed also to github pages/Netlify/Vercel, code is just unusable. On top of that, every transaction was paid and checked on Solscan as finalized and success - however, no NFT is showing in wallet nor in storefront.

You can see it for yourself, it's just loading and so slow, that it is unusable. Home page is blinking while loading with "Connect to configure store", although it was initialised and admin submitted. Deployed to Netlify > https://hungry-mayer-af82d7.netlify.app/

![Screenshot 2022-03-12 at 19 35 10](https://user-images.githubusercontent.com/54318006/158031033-904ce847-7e16-4da7-9de7-b6b8d9bd89e3.png)

### Command

```shell
git clone https://github.com/metaplex-foundation/metaplex.git
cd metaplex/js
yarn install && yarn bootstrap && yarn build
yarn start
```

### Operating system

MacOS 12, Chrome 99.0.4844.51, Phantom & Solflare wallet

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by swimmingyoshi** [comment]
first initial startup can take a few minutes,
sometimes itll work if you can add the devnet url extension
 
 i've managed to get it working and mint but i have issues actually selling a mint
. 

check out https://auction-pink.vercel.app/#/

the only issue i've found is

**Comment by hjertefolger** [comment]
Thank you. The main issue I have is that it's loading at start, when you visit the site - and it is unpredictable. Sometimes it's loading fast, but in most cases it takes very long time to stop. This scenario is simply not usable in production. You could see any NFT marketplace out there, it loads fast, you could explore it even without wallet connected, it behaves in most cases like "normal"website. Unfortunately this isn't the case - the code and system is so complex there is no way to start optimising it. And even using the best of the best hosting for next js - Vercel didn't help with load speed, it is extremely slow overall in loading any asset/image/subpage.
