### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GottliebGlob** [metaplex-foundation/metaplex#1951]
### Which package is this bug report for?

candy machine cli

### Issue description

Hello. Faced a problem. when uploading 300 images to devnet (arweave storage), such an error occurs. It begins to appear on pictures that are completely different in number (from 9 to 60). 
![image](https://user-images.githubusercontent.com/53971863/158201230-36c8fb3f-420c-4151-aaf2-65b8f65cfb6e.png)
`verify_assets` command showed no errors. 
All of my JSONs are correct and look like:
`{
  "name": "Your Collection #0",
  "symbol": "RS",
  "description": "Remember to replace this description",
  "seller_fee_basis_points": 1000,
  "image": "0.png",
  "external_url": "https://www.youtube.com/c/hashlipsnft",
  "edition": 0,
  "attributes": [
    {
      "trait_type": "Background",
      "value": "five"
    },
    {
      "trait_type": "Geometrics",
      "value": "first"
    },
    {
      "trait_type": "Letters",
      "value": "fourth"
    }
  ],
  "properties": {
    "files": [
      {
        "uri": "0.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "AKwTinC3CZMpbagx7dXwKH1cVr81VcWiojPMwVcaUQ3p",
        "share": 100
      }
    ]
  }
}`

When uploading 10-50 images, no errors occur.

### Command

```shell
npx ts-node C:/Users/Data/Projects/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k Se4Gf2GsjgzZZyUfnhFVzVLcijsCXx5a9Erhsp5uoUF.json -cp config.json ./assets
```

### Relevant log output

```shell
Error uploading {"mediaExt":".png","index":"19"} asset (skipping) invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/upl
oadFile reason: Unexpected token E in JSON at position 0
```

### Operating system

Win 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by psavva** [comment]
I'm facing the same issue, 

I'm uploading only 5 images.  4 of the 5 are onChain, 1 of the file is not, and with the same error:

```
PS C:\repos\NFT\OiKattes> ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k solana-mint/devnet-keypair.json -cp solana-mint/config.json -c testcache solana-mint/assets     
wallet public key: EoQFqam61FNeNLymwPEMm9SSrJK2S8GvBFpUuihZdeuf
(node:19172) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19172) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 5 (img+json) pairs
started at: 1647286866542
initializing candy machine
No collection set
initialized config for a candy machine with publickey: Hea6EGFW22DBpKjzk66p9NYZ2urc52ubFsNVJJk25SRQ
[0] out of [5] items have been uploaded
Starting upload for [5] items, format {"mediaExt":".png","index":"0"}
Progress: [████████████████████████████████████████] 100% | 5/5
Error uploading {"mediaExt":".png","index":"3"} asset (skipping) invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile reason: Unexpected token E in JSON at position 0

Writing all indices in 1 transactions...
Progress: [████████████████████████████████████████] 100% | 1/1
Done. Successful = false.
ended at: 2022-03-14T19:44:48.558Z. time taken: 00:03:42
```

**Comment by stegaBOB** [comment]
Try uploading with the arweave-sol option. The arweave option shouldn't really be used.

**Comment by andrewau322** [comment]
Wha

> Try uploading with the arweave-sol option. The arweave option shouldn't really be used.

What our for devnet? I got the same error while uploading to devnet thankss

**Comment by psavva** [comment]
> > Try uploading with the arweave-sol option. The arweave option shouldn't really be used.
> 
> What about devnet? I got the same error while uploading to devnet thankss



> Try uploading with the arweave-sol option. The arweave option shouldn't really be used.

The issue here is on devnet.
Arweave-sol works on devnet???

**Comment by stegaBOB** [comment]
Yeah it works on devnet. Make sure you're on the latest version of Metaplex

**Comment by psavva** [comment]
I will test it now 😸

**Comment by psavva** [comment]
Confirmed.  Suggest to close this issue, and update the documentation to reflect that only "arweave-sol" should be used on devnet, instead of arweave.

**Comment by GottliebGlob** [comment]
![image](https://user-images.githubusercontent.com/53971863/158341885-7c20939c-b37a-4376-9e7f-21173edcefc3.png)
I get this error using arweave-sol, although there are about 1.2 sol left on the wallet

**Comment by GottliebGlob** [comment]
> Try uploading with the arweave-sol option. The arweave option shouldn't really be used.
![image](https://user-images.githubusercontent.com/53971863/158342569-f11f8165-c166-4f5f-b817-97cc7ec93394.png)
I've got this error using arweave-sol. Although there are about 1.2 sol left on the wallet

**Comment by phillmorgan28** [comment]
> > Try uploading with the arweave-sol option. The arweave option shouldn't really be used.
> 
> ![image](https://user-images.githubusercontent.com/53971863/158342569-f11f8165-c166-4f5f-b817-97cc7ec93394.png) I've got this error using arweave-sol. Although there are about 1.2 sol left on the wallet

Same issue and commented here too https://github.com/metaplex-foundation/metaplex/issues/1885#issuecomment-1067862064

**Comment by GottliebGlob** [comment]
Fixed with the last update. Thanks
