### ISSUE TITLE
Metaplex not displaying owned NFTs after minting with another wallet

### ISSUE THREAD

**Issue by IntelMin** [metaplex-foundation/metaplex#1953]
### Which package is this bug report for?

storefront

### Issue description

I just forked metaplex and initiated a new store and minted a few NFTs. It works well and they are listed as owned myself. (used owner wallet for minting)
Then, I tried minting another NFTs with other wallets (e.g. Wallet 2 in Phantom). Of course, it's not the owner wallet, but already set it from "whitelist only" to "public" in the admin panel so that other wallets could mint on my store. (if that's the correct option for it)
On create page, it was going well and successfully minted a new NFT, it came into the Phantom collective.
But not displaying on the Metaplex store list.

Is the owner only allowed to mint on the store? Is there any way to allow other users minting on my store?

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by maxeordea** [comment]
How you change from whitelist to public mint? thanks

**Comment by IntelMin** [comment]
In admin panel, I was able to toggle a button turning into public from whitelist.
![image](https://user-images.githubusercontent.com/76229434/160208292-0b2bf9f3-c143-4c63-8e7b-857a5edd71cc.png)
->
![image](https://user-images.githubusercontent.com/76229434/160208328-ce1d0e8d-6ee1-49c8-8042-02278064b75d.png)

**Comment by maxeordea** [comment]
thank you....i have your same problem with minting
