### ISSUE TITLE
[Bug]: FetchError: invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile reason: Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by andrewau322** [metaplex-foundation/metaplex#1958]
### Which package is this bug report for?

candy machine cli

### Issue description

I have been getting this error on Devnet for a while. Appreciate if someone can help me out. Thanksss a lot

<img width="800" alt="Screenshot Bug" src="https://user-images.githubusercontent.com/77886987/158300237-1cf8bbef-131d-4c01-8194-fce118d39611.png">

### Command

 ts-node ./js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ./~/my-solana-wallet/my_wallet.json~/my-solana-wallet/my_wallet.json -cp ./js/packages/cli/config.json -c example  ./Assets

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by iamoperand** [comment]
I've been getting this error as well. Can't mint NFTs since yesterday.

**Comment by BigPun86** [comment]
you will need to set the storage to *arweave-sol*. it works for devnet as well, but u need to have the latest metaplex

**Comment by iamoperand** [comment]
> you will need to set the storage to _arweave-sol_. it works for devnet as well, but u need to have the latest metaplex

This would work only for candy machine, right? Is there a way to fix this error for NFTs created via the "Create" UI in metaplex?
