### ISSUE TITLE
Recaptcha Timeout when trying to Mint 

### ISSUE THREAD

**Issue by NeedzBeez** [metaplex-foundation/metaplex#1965]
### Which package is this bug report for?

candy machine ui

### Issue description

I am trying to mint on the main net and my candy machine Times out and just disappears.

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Andre-Inklusion** [comment]
This is still happening.

**Comment by NeedzBeez** [comment]
> 

Where you able to figure out this issue?

**Comment by NeedzBeez** [comment]
> This is still happening.

Where you able to figure out this issue?
