### ISSUE TITLE
[Bug]: Candy machine UI broken with WL mint

### ISSUE THREAD

**Issue by Vipulsin13** [metaplex-foundation/metaplex#1972]
### Which package is this bug report for?

candy machine ui

### Issue description

I am trying to whitelist a token with burn set to true.. I am connected to Devnet.. NFT minting goes through for the wallets holding the token.. But on checking the transaction on Solscan.. it shows the revoke instruction is being called and the token balance change shows that the tokens were not burnt and neither does the nfts appear in my collectibles on my Phantom wallet. On refreshing the page, the entire collection is there to be minted again..

### Command

```shell
I am using the following command to upload the assets and initialize the candy-machine:
ts-node ./src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/keypair.json -cp config.json -c temp ./assets
```

### Relevant log output

```shell
The log output on Solscan is:
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
Program log: Instruction: Revoke
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1616 of 200000 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
```

### Operating system

Win 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
This issue should be fixed now.
