### ISSUE TITLE
Secondary Auctions screen flickers and randomizes

### ISSUE THREAD

**Issue by bhgames** [metaplex-foundation/metaplex#198]
Go to squidstuff marketplace or any active secondary and view it for a few seconds. It flickers and re-arranges cards. Not noticeable on dev but does seem to happen on mainnet. Might be websocket thing. To look into.

**Comment by flappy-07** [comment]
This should resolve it, does not happen in dev so squid needs to update to see if this works.

https://github.com/metaplex-foundation/metaplex/pull/202
