### ISSUE TITLE
[Bug]:  ts-node ./candy-machine-cli.ts upload ./assets --env devnet -k <keypair-path> zsh: parse error near `\n'

### ISSUE THREAD

**Issue by Grahamrad9333** [metaplex-foundation/metaplex#1983]
### Which package is this bug report for?

candy machine cli

### Issue description

solve
 ts-node ./candy-machine-cli.ts upload ./assets --env devnet -k <keypair-path>
zsh: parse error near `\n'

### Command

```shell
ts-node ./candy-machine-cli.ts upload ./assets --env devnet -k <keypair-path>
zsh: parse error near `\n'
```

### Relevant log output

```shell
ts-node ./candy-machine-cli.ts upload ./assets --env devnet -k <keypair-path>
zsh: parse error near `\n'
```

### Operating system

mac

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
This file isn't in our repo anymore. Please pull from master to get the latest version of metaplex and try again. If you are still having issues feel free to open a new issue.
