### ISSUE TITLE
[Bug]: Problem with execute_sale in auction-house-cli.ts

### ISSUE THREAD

**Issue by leewenjie** [metaplex-foundation/metaplex#1988]
### Which package is this bug report for?

other cli

### Issue description

**Steps to reproduce with**

1. Mint Metaplex NFT with Wallet A
2. Create Auction House with with Wallet A
3. Sell NFT with Wallet A
4. Buy listed NFT with Wallet B
5. Execute Sale with Wallet A

All the CLI commands below work fine, only the last step `5) Execute Sale in Auction House` produces an error. Any suggestion on how to fix this? The broken step reference the `auction-house/cli#execute-sale` page in the [doc](https://docs.metaplex.com/auction-house/cli#execute-sale).

**Command lines steps**

Prepare Wallet A and B, airdrop Sol into them.
- A (seller) - `~/.config/solana/a.json` - address is `3GbBuccQtMfyMXVgoPn2eKcjxDAG1FDp4D41LGrSP7gW`
- B (Buyer) - `~/.config/solana/b.json` - address is `3Ms3L229P4Ygt6ZVHdhAAmhwzqjGXDRjQuXQRTCeEd9y`

1) Mint a Metaplex NFT

`ts-node src/cli-nft.ts mint -k ~/.config/solana/a.json -u https://api.npoint.io/93a4f1c65143506498a3`

NFT mint which we use in devnet is `BGxKEY8ux8Eby56UmGH93Q4o9FV9ZYpqmn8HSizX2P9v`

2) Create Auction House

`ts-node src/auction-house-cli.ts create_auction_house -k ~/.config/solana/a.json -e devnet -sfbp 1000 -ccsp false -rso false`

3) Sell NFT in Auction House using Wallet A

`ts-node src/auction-house-cli.ts sell -k ~/.config/solana/a.json -ah 7hoSzegdXmis2gPUGrJ5ymWzZqUGC6iuWKtJRStHYhE9 --buy-price 1 --mint BGxKEY8ux8Eby56UmGH93Q4o9FV9ZYpqmn8HSizX2P9v --token-size 1`

4) Buy NFT in Auction House using Wallet B

`ts-node src/auction-house-cli.ts buy  -k ~/.config/solana/b.json -ah 7hoSzegdXmis2gPUGrJ5ymWzZqUGC6iuWKtJRStHYhE9 --buy-price 1  --token-size 1  --mint BGxKEY8ux8Eby56UmGH93Q4o9FV9ZYpqmn8HSizX2P9v`

5) Execute Sale in Auction House

`ts-node src/auction-house-cli.ts execute_sale -k ~/.config/solana/a.json -ah 7hoSzegdXmis2gPUGrJ5ymWzZqUGC6iuWKtJRStHYhE9 --buy-price 1 --mint BGxKEY8ux8Eby56UmGH93Q4o9FV9ZYpqmn8HSizX2P9v --buyer-wallet 3Ms3L229P4Ygt6ZVHdhAAmhwzqjGXDRjQuXQRTCeEd9y --seller-wallet 3GbBuccQtMfyMXVgoPn2eKcjxDAG1FDp4D41LGrSP7gW -token-size 1`

### Command

```shell
ts-node src/auction-house-cli.ts execute_sale -k ~/.config/solana/a.json -ah 7hoSzegdXmis2gPUGrJ5ymWzZqUGC6iuWKtJRStHYhE9 --buy-price 1 --mint BGxKEY8ux8Eby56UmGH93Q4o9FV9ZYpqmn8HSizX2P9v --buyer-wallet 3Ms3L229P4Ygt6ZVHdhAAmhwzqjGXDRjQuXQRTCeEd9y --seller-wallet 3GbBuccQtMfyMXVgoPn2eKcjxDAG1FDp4D41LGrSP7gW -token-size 1
```

### Relevant log output

```shell
Rejected via websocket { InstructionError: [ 0, 'ProgramFailedToComplete' ] }
Timeout Error caught {
  err: { InstructionError: [ 0, 'ProgramFailedToComplete' ] },
  slot: 122434297,
  confirmations: 0
}
/GitHub/metaplex/js/packages/cli/src/helpers/transactions.ts:136
            throw new Error(
                  ^
Error: Transaction failed: panicked at 'index out of bounds: the len is 0 but the index is 0', src/lib.rs:1166:255
    at sendSignedTransaction (/GitHub/metaplex/js/packages/cli/src/helpers/transactions.ts:136:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendTransactionWithRetryWithKeypair (/GitHub/metaplex/js/packages/cli/src/helpers/transactions.ts:59:26)
    at async Command.<anonymous> (/GitHub/metaplex/js/packages/cli/src/auction-house-cli.ts:885:5)
```

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by leewenjie** [comment]
No issue with the Metaplex storefront sales & purchase sequence - just that the cli command failed at the `execute_sale` for myself

**Comment by paul-hl** [comment]
@leewenjie Have you managed to solve this, please?

**Comment by paul-hl** [comment]
@leewenjie I am getting the same error, so the problem disappeared?

**Comment by leewenjie** [comment]
Hi @paul-hl , the errors in the CLI remains, unfortunately.

However, the Metaplex store UI codes worked fine, so I just bootstrapped and got the codes I needed from there.

**Comment by paul-hl** [comment]
@leewenjie Ok, I will take a look at the code, thank you.

**Comment by paul-hl** [comment]
@leewenjie Just to clarify I understood your comment right..

Have you found a solution for using AuctionHouse CLI and its execute sale command? Thus, you changed something in the Auction House CLI code to get it to work? And this change was inspired by Storefront?

Or have you used a different solution that meets your needs? (e.g. Metaplex Storefront and its auctions?)

Thank you very much.

**Comment by leewenjie** [comment]
`Have you found a solution for using AuctionHouse CLI and its execute sale command?`

Nope, did not get the CLI to work fully.

`Or have you used a different solution that meets your needs? `

I just lifted the codes I needed from the Metaplex Storefront (which worked - esp the secondary sales userflow) into my app.

Hope this helps!

**Comment by th-yoo** [comment]
I have exactly the same problem, except different error message.
```Timeout Error caught { err: 'InvalidRentPayingAccount', slot: 132890641, confirmations: 0 }```

Solana describes the error in [the source code](https://github.com/solana-labs/solana/blob/4520c253307c08add9b00ca8c272d5c077a63d9c/sdk/src/transaction/error.rs#L129) like this:

```javascript
    /// Transaction leaves an account with a lower balance than rent-exempt minimum
    #[error("Transaction leaves an account with a lower balance than rent-exempt minimum")]
    InvalidRentPayingAccount,
```
One of accounts has not enough money...?
I'm innocent. I have already airdropped 2 SOL on `Fee Payer Acct` as [the manual](https://docs.metaplex.com/auction-house/cli)!

The only suspect was `Treasury Acct`. I airdropped 2 SOL on it and then tried again.
**Voila!** `execute_sale` succeeded.

I tested `the Treasury Acct` of your AuctionHouse.
```
$ solana balance -u devnet ChMoYzPCbSgXvrZcBfnwsKzTx9U5CY6UveSkdkYxPhMR
0 SOL
```
I bet you will succeed if you deposit some SOL in it.

The manual does not mention the need for `Treasury Acct Balance`.
The real criminal turns out to be the manual.

**Comment by leewenjie** [comment]
Well done @th-yoo, thanks for the updates!
