### ISSUE TITLE
[Bug]: error: required option '-k, --keypair <path>' not specified

### ISSUE THREAD

**Issue by MaWads** [metaplex-foundation/metaplex#1998]
### Which package is this bug report for?

candy machine cli

### Issue description

I have done numerous tutorials, followed everything step by step but I keep getting stuck at this one step, running the following command: 

```
npx ts-node ~/solana-nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ 
-e devnet \
-k keypair.json \ 
-cp config.json \ 
./assets
```

I have done this in multiple variations but I keep getting the error: 
**error: required option '-k, --keypair <path>' not specified**

Help?! Driving me nuts

Yarn version 1.22.18
Node version v14.17.0
solana-cli 1.9.13 
ts-node version v10.7.0

### Operating system

macOS

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Perhaps try running the command in one single line? It could be that the new lines are throwing it off somehow?
