### ISSUE TITLE
[Bug]: Candy Machine that takes SPL token won't upload

### ISSUE THREAD

**Issue by pfeifemc** [metaplex-foundation/metaplex#2001]
### Which package is this bug report for?

candy machine cli

### Issue description

I am attempting to upload a test Candy Machine config that accepts an SPL token called $DUST instead of $SOL, but I continue to receive the attached error message (INVALID_ACCOUNT_OWNER). Here is my current config:
`{
  "price": 1,
  "number": 4,
  "gatekeeper": null,
  "solTreasuryAccount": null,
  "splTokenAccount": "3kNKaGWpizc7QJNx8qJz8TNceBgkWeE17q2bSB4Wp8rT",
  "splToken": "DUSTawucrTsGU8hcqRdHDCbuYhCPADMLM2VcCb8VnFnQ",
  "goLiveDate": "22 March 2022 19:30 EST",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "storage": "arweave-sol",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "awsS3Bucket": null,
  "nftStorageKey": null,
  "noRetainAuthority": false,
  "noMutable": false
}`

My understanding for this is that:
1. solTreasuryAccount is null since there is no SOL revenue
2. splTokenAccount is set to the test wallet that already contains a token program for the associated SPL token
3. splToken is the token address for the SPL token

One note is that I did not create this SPL token myself and I don't know whether it was created through candy machine.

I checked all the obvious issues. Hope someone can help with this ASAP as we're trying to do this mint on Saturday!

### Command

```shell
ts-node ./src/candy-machine-v2-cli.ts upload \                                   
    -e mainnet-beta \
    -k ~/.config/solana/mainnet.json \
    -cp config-dust.json \
    -c example-dust \
    ./assets3
```

### Relevant log output

```shell
/Users/matthewpfeifer/Documents/mickey-degods-menu/metaplex-rev/js/node_modules/@solana/spl-token/client/token.js:771
      throw new Error(INVALID_ACCOUNT_OWNER);
            ^
Error: Invalid account owner
    at Token.getAccountInfo (/Users/matthewpfeifer/Documents/mickey-degods-menu/metaplex-rev/js/node_modules/@solana/spl-token/client/token.js:771:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getCandyMachineV2Config (/Users/matthewpfeifer/Documents/mickey-degods-menu/metaplex-rev/js/packages/cli/src/helpers/various.ts:137:26)
    at async Command.<anonymous> (/Users/matthewpfeifer/Documents/mickey-degods-menu/metaplex-rev/js/packages/cli/src/candy-machine-v2-cli.ts:157:9)
```

### Operating system

Mac OS Big Sur 11.4

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by pfeifemc** [comment]
This issue was due to the token program ID being wrong. I was inputting my wallet address and not the address of the SPL token program. This issue is resolved.

**Comment by stegaBOB** [comment]
I was about to comment that exact thing! Beat me by 30 seconds haha

**Comment by Salro1g** [comment]
Hi!

I resolve this, ok, same problem, need to create an spl token account for the DUST token. Since here all ok, but then, how can I recover this DUST or others SPL tokens? I mean, ok I have a public account created by me to deposit that DUST but how can I enter into this wallet or how can I send this DUST to my phantom wallet?

Thanks a lot!

**Comment by arturobroker** [comment]
> Hi!
> 
> I resolve this, ok, same problem, need to create an spl token account for the DUST token. Since here all ok, but then, how can I recover this DUST or others SPL tokens? I mean, ok I have a public account created by me to deposit that DUST but how can I enter into this wallet or how can I send this DUST to my phantom wallet?
> 
> Thanks a lot!

You will see those Dust token automatically on your phantom wallet, you just have to create the spl account through the wallet you want to receive them.
