### ISSUE TITLE
Nft photo shows up only in solscan but not in phantom

### ISSUE THREAD

**Issue by Goldslasthowl** [metaplex-foundation/metaplex#2003]
### Which package is this bug report for?

other

### Issue description

Ok so I have double checked all of the meta data and the namecfor my png files is correct on the Metadata but for some reason the photo does not show up in phantom but shows up in in solscan. Here is the link for it on solcan (https://solscan.io/token/Hf7aHFE7Vwenz1Vr2YFXYjF6XvRR2KB3s2xL6zZsoX21?cluster=devnet)

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Can you link your NFT please? Thanks

**Comment by Goldslasthowl** [comment]
@

> Can you link your NFT please? Thanks

ok i did

**Comment by SeanOverton** [comment]
Did this eventually show up? @Goldslasthowl

**Comment by SeanOverton** [comment]
I can see in your metadata it might be broken 
![image](https://user-images.githubusercontent.com/59163024/163280175-4ac9c831-dbd8-432c-b9c9-35ab984f4472.png)
