### ISSUE TITLE
ts-node not found

### ISSUE THREAD

**Issue by ArmaBloody** [metaplex-foundation/metaplex#2006]
### Which package is this bug report for?

other

### Issue description

User@ArmaBloody MINGW64 ~/nft
$ ts-node /metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
>     -e devnet \
>     -k seller.json \
>     -cp config.json \
>     -c example \
>     /assets
bash: ts-node: command not found

### Command

```shell
ts-node /metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k seller.json \
    -cp config.json \
    -c example \
    /assets
```

### Relevant log output

```shell
User@ArmaBloody MINGW64 ~/nft
$ ts-node /metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
>     -e devnet \
>     -k seller.json \
>     -cp config.json \
>     -c example \
>     /assets
bash: ts-node: command not found
```

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Install ts-node. https://docs.metaplex.com/candy-machine-v2/getting-started#tooling-required
