### ISSUE TITLE
[Bug]: SoldOut button continues to mint on click.

### ISSUE THREAD

**Issue by aungthumoe5** [metaplex-foundation/metaplex#2011]
### Which package is this bug report for?

candy machine ui

### Issue description

The mint button should be unclickable once the collection is sold out. The steps to reproduce is as below:
1. Create candy machine.
2. Run candy machine ui.
3. Mint until remaining is 0.
4. Click SoldOut button again.
5. (Bug) Transaction is submitted to wallet to mint.
6. (Bug) If transaction is confirmed, Remaining counter drops to -1.
7. (Bug) Step 5+6 can be repeated and Remaining counter drops even further.

### Operating system

Mac

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by terrier-lover** [comment]
I tried to reproduce the issue but I was not able to do it. In my dev environment, after I minted until the remaining number is 0, the button became disabled like this. 
![Screen Shot 2022-04-03 at 12 39 46 AM](https://user-images.githubusercontent.com/68787800/161446295-733cb845-0136-4d39-8e53-126689f970e7.png)

So, the issues mentioned in 5, 6, and 7 cannot be reproduced. 

What kind of configuration (config.json) and which version did you use when you encountered the issue?
