### ISSUE TITLE
[Bug]: arweave-sol option does not update properties.files.uri attribute in metadata

### ISSUE THREAD

**Issue by aungthumoe5** [metaplex-foundation/metaplex#2013]
### Which package is this bug report for?

candy machine cli

### Issue description

1. Create a candy machine config.json with the value, "storage": "arweave".
2. Upload and verify upload.
3. Check arweave metadata and observe "properties": {"files": [{"uri": "https://www.arweave.net/xxxx"}]} is using arweave link.
4. Change config.json value to "storage": "arweave-sol"
5. Delete .cache to generate another candy machine.
6. Upload and verify upload.
3. (Bug) Check arweave metadata and "properties": {"files": [{"uri": "xxxx.png"}]} is still using local filename, which is wrong.

### Operating system

Mac

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by oboxodo** [comment]
@aungthumoe5 my fix for this in #2052 got merged by @stegaBOB :muscle: I think this issue should be resolved now.
