### ISSUE TITLE
[Bug]: Storefront auction - update authority is transferred to the auction winner rather than retained by the minter / seller.

### ISSUE THREAD

**Issue by jarvisjohnson** [metaplex-foundation/metaplex#2014]
### Which package is this bug report for?

storefront

### Issue description

- Launch a new storefront
- Mint an NFT on the storefront, with either Max supply 0 or 1
- Auction it
- After winner redeems, they are given the update authority

this transaction is from my store: https://solscan.io/tx/4xboWPh13VmJ9S5oMboRgT2duUajrmTJwC4nmr2Sd252pSc1eatTkdJhdu1zHUWbhsTr9Qc4hmnb9qbHRHioMYmR

![image](https://user-images.githubusercontent.com/12746936/160267485-2e9ceeb3-cfb4-4dc5-b037-a80cfc5dc1bd.png)

This one is from another person's store:
https://solscan.io/tx/2839yYvSdkd8WhcSBYmjpeUKdzEgUBHnhdL52TPbjt5GVHJfpAasS5A1HdwERLQMMnAvu81h6EpbAjeKgnXpb4NN

![image](https://user-images.githubusercontent.com/12746936/160267488-3685b571-fbcf-4da0-8f74-19fb11653d8f.png)

Ours for some reason invokes "Redeem Full Rights Transfer Bid" while theirs invokes "Redeem Normal Token Bid"

### Operating system

Storefront deployed to Vercel

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Are you on the latest version of the repo?

**Comment by jarvisjohnson** [comment]
> 

Ah sorry for the delay - 1.1.0 

I see now there is a new release - I will try that out @stegaBOB.
