### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NabiiBux** [metaplex-foundation/metaplex#2016]
### Which package is this bug report for?

other cli

### Issue description

Too many requests 429 , please contact your developer, please I need to fix this urgent , where in metaplex , i want to RPC tell me with screenshot

### Command

```shell
npx ts-node candy-machine-v2-cli.ts upload -e mainnet-beta -k C:/Users/Nabibux/Desktop/solana/metaplex/wallet/.config/solana/Gorrilosmainnet.json -l debug -c example C:/Users/Nabibux/Desktop/solana/assets -cp C:/Users/Nabibux/Desktop/solana/config.json
```

### Relevant log output

```shell
Error: 429 Too Many Requests:  {"jso
nrpc":"2.0","error":{"code": 429, "message":"Too many requests from your IP, contact your app developer or support@rpcpool
.com."}, "id": "b2e48801-c7af-4111-9ab4-c51dd64f112d" }
```

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Check our docs for RPCs. The default RPC is rate limited. https://docs.metaplex.com/community#services

**Comment by NabiiBux** [comment]
How to use rpcs in the metaplex project can you guide me?

**Comment by NabiiBux** [comment]
> Check our docs for RPCs. The default RPC is rate limited. https://docs.metaplex.com/community#services

Please tell me a way how to use those rpcs in the projects of metaplex that I downloaded in my system I tried to upload it gives this error and I lost my 1.3 sol
