### ISSUE TITLE
[Bug]: load time issues with site 

### ISSUE THREAD

**Issue by DavidYenATUM** [metaplex-foundation/metaplex#2018]
### Which package is this bug report for?

storefront

### Issue description

http://atumtech.io/#/   is the site with the very slow load time  i have been tryin to resolve this issue for weeks now and i even have went to the discord and have not gotten help 

### Operating system

windows 

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by born8** [comment]
![Screenshot_20220329-133801~2](https://user-images.githubusercontent.com/65473167/160549026-f117b7aa-8937-4df2-8f4a-016a2687dfd1.png)

if u test on devnet:
1. click http://atumtech.io/#/?network=devnet 
2. refresh ur browser (url: http://atumtech.io/#/?network=devnet) wait +1 minutes
3. connect to configure store
4. change REACT_APP_STORE_OWNER_ADDRESS_ADDRESS= <ur pubkey/wallet address>
5. done

**Comment by DavidYenATUM** [comment]
it wont let me initialize the store on devnet

**Comment by born8** [comment]
re-deploy, try this:
create 2 file:
1. _config.yml (read, https://docs.metaplex.com/storefront/deploy), and
2. CNAME (your host, etc: atumtech.io)
save as the file above into js/packages/web/public

terminal command:
cd metaplex/js/packages/web
'yarn deploy'

I just tried it and it worked
look my gh-pages: https://github.com/born8/metaplex/tree/gh-pages
