### ISSUE TITLE
[Bug]: candy machine upload crashed

### ISSUE THREAD

**Issue by nikolala13** [metaplex-foundation/metaplex#2019]
### Which package is this bug report for?

candy machine cli

### Issue description

![image](https://user-images.githubusercontent.com/91738592/160629575-2c7aba37-d82c-4d3d-a849-ec9c09696e97.png)
I have this error when I try to upload cmv2

### Command

```shell
ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ./config/.config/solana/devnet.json -cp ./config.json ./assets
```

### Relevant log output

```shell
wallet public key: 4foTFditgfNFG7EjX6VFcXC9X3kWM9sY2w8sA7V79AQ1
C:\Users\amate\NFT\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:203
      throw new Error(
            ^
Error: max number (1) cannot be smaller than the number of images in the source folder (5)
    at Command.<anonymous> (C:\Users\amate\NFT\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:203:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Looks like you have set the number of items to 1 in the config file. That should be the number of nfts in your candy machine.

**Comment by Zaryab-Programmer** [comment]
I'm facing an issue, I have 100 artworks and their metadata. When I command upload
`ts-node candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/id.json -cp ~/metaplex/js/packages/cli/config.json -c example ./assets`
it gives an error : `Error: max number (10) cannot be smaller than the number of images in the source folder (100)`

**But in config file it is ->  "number": 15, **
