### ISSUE TITLE
Infinite loading except from admin browsers

### ISSUE THREAD

**Issue by IvanAnikin** [metaplex-foundation/metaplex#2020]
### Which package is this bug report for?

storefront

### Issue description

Hey, I'm running into an issue with the NFT Metaplex Storefront being loading perpetually after initting the store in every browser except from the one, I've logged in as an admin of the store. Do you have any ideas what nmay cause the problem? It seems i'm not the only one having the issue, and the community on discord didn't find the solution as well.
Could you give a recommendation y the way of how to debug the Metaplex from VS Code? I've made a confuiguration and run the debugging, however it displays my breakpoins in meta.js file as Unbound Breakpoints. I'm trying to find where the program gets stucks during loading.

Thanks in advance.

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by ArtOfThings** [comment]
I'm facing the same issue even with an admin login

**Comment by BlockchainDataMiner** [comment]
What I don't understand is why a lot of people have been able to deploy the UI and it works well for them...

**Comment by andrejsim** [comment]
I NOTICED THAT INFINITE LOADING FOR THE STOREFRONT CAN BE ADDRESSED IN DEVELOPER TOOL SETTINGS IN YOUR BROWSER BY 'ENABLE JAVA SOURCE MAP'=FALSE. 
This is not something that most non developer users will know, is there a way to address this with an error message or a chrome setting?

**Comment by andrejsim** [comment]
Sorry: The above does allow you to go further in the download process but does not help with a non admin (aka creator whitelist)
