### ISSUE TITLE
[Bug]: Candy Machine Mint - ERROR newTokenRequestFlow TypeError

### ISSUE THREAD

**Issue by Andre-Inklusion** [metaplex-foundation/metaplex#2028]
### Which package is this bug report for?

candy machine ui

### Issue description

Steps to reproduce:
1. Connect wallet
2. Click the mint button

No error message is shown to the user.

Checking the console log:
ERROR newTokenRequestFlow TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### Relevant log output

```shell
ERROR newTokenRequestFlow TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (index.js:311:1)
    at from (index.js:137:1)
    at Function.push../node_modules/node-libs-browser/node_modules/buffer/index.js.Buffer.from (index.js:149:1)
    at createSolanaTransactionFromBase64 (chainImplementation.js:14:1)
    at Object.handleUserSignedTransaction (chainImplementation.js:54:1)
    at usePOWO.js:66:1
```

### Operating system

Mac OS

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Andre-Inklusion** [comment]
This apparently is a problem with using the Civic gateway.

**Comment by nikkoagustino** [comment]
> 

Hi there, I have same problem as yours. How do you increase the timeout?
