### ISSUE TITLE
mint mutton not active 

### ISSUE THREAD

**Issue by ArmaBloody** [metaplex-foundation/metaplex#2031]
### Which package is this bug report for?

other

### Issue description

i click on (connect wallet ) button hi  connects and show mi mint button  and it not active 

### Command

```shell
a
```

### Relevant log output

```shell
a
```

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Try asking in our discord. Thanks
