### ISSUE TITLE
[Bug]: Unable to fetch balance changes, whitelist

### ISSUE THREAD

**Issue by jjclinton** [metaplex-foundation/metaplex#2032]
### Which package is this bug report for?

candy machine cli

### Issue description

1 I try to mint with my WL token and sol with a wallet that didn't create the candy machine, and I keep getting "Unable to fetch balance changes". If I do it with the wallet that deployed the candy machine it does work.

If I turn off the WL functionality it also works with the other wallet.

My config file:
`{
    "price": 1.0,
    "number": 10,
    "gatekeeper": null,
    "solTreasuryAccount": "3DpbJNcUq1yPmCZpECECRx8Bh6KyhdXRWjGBtANmc8ao",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "25 Dec 2021 00:00:00 GMT",
    "endSettings": null,
    "whitelistMintSettings": {
        "mode" : { "burnEveryTime": true },
        "mint" : "WLjsj7uVxu1FNCAabkozZCKVNAT5fb2KXVn2Mv7hVT5",
        "presale" : true,
        "discountPrice" : 0.6
    },
    "hiddenSettings": null,
    "storage": "arweave-sol",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "nftStorageKey": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}`

How can this be?

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by mr365k** [comment]
Yeah same error on my end, has been going on for hours now. People are complaining about lost Solana in fees trying to mint.

**Comment by stegaBOB** [comment]
Are you using the latest version of metaplex? Also, what are your candy machine IDs?

**Comment by jjclinton** [comment]
> Are you using the latest version of metaplex? Also, what are your candy machine IDs?

Yes I believe I am. This is my env, in which you can also find my candy machine ID. I hide my quicknode api key:
`REACT_APP_CANDY_MACHINE_ID=99p5aEZadMED3FjFUkc6ESrYMk4D5Gt6bcm6E5HffCVs

REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://hidden-solitary-dew.solana-devnet.quiknode.pro/xxx/
SKIP_PREFLIGHT_CHECK=true
`

**Comment by mr365k** [comment]
I am using the most recent version to my understanding. It was working earlier that day, the suddenly stopped and hasnt worked since then.

**Comment by b124816** [comment]
Got same error while minting Fellow Apes. Thought these logs might be useful.  Application was showing this transaction as successful. Fee deducted but actual transaction timeout.
![FellowApes_Failure1](https://user-images.githubusercontent.com/103295831/162552062-a24427e0-48e0-4331-8495-e921e58c236f.JPG)
![FellowApes_Failure2](https://user-images.githubusercontent.com/103295831/162552077-a7db71db-59f9-430d-9dc9-b4f2d7460cba.JPG)
![FellowApes_Failure3](https://user-images.githubusercontent.com/103295831/162552089-569747d8-1dfd-48d1-b454-b6d130e667f5.JPG)

The following failed gracefully.
![FellowApes_Success](https://user-images.githubusercontent.com/103295831/162552127-d3768793-fc45-4b18-8327-ea2fea92240f.JPG)

**Comment by cdric** [comment]
I am running into the same issue :-/ 
Anyone has found a solution for this?

**Comment by jjclinton** [comment]
> I am running into the same issue :-/ Anyone has found a solution for this?

Nope, got no response
