### ISSUE TITLE
Transaction was not confirmed in 60.01 seconds

### ISSUE THREAD

**Issue by vadimShlyapa** [metaplex-foundation/metaplex#2036]
### Which package is this feature request for?

candy machine cli

### Feature

I tried to create a candy machine, but I got this error.  My money was debited, how can I get it back?  I received the candy machine code, but there are no files in the cache folder.

### Ideal solution or implementation

![3C213F71-6F2E-4203-AA2C-5E92FCFE6A8A](https://user-images.githubusercontent.com/46841070/161975585-1b3763bd-4521-45a0-aed5-a7e30cb8bf6e.jpeg)

**Comment by GottliebGlob** [comment]
Same issue

**Comment by GottliebGlob** [comment]
![image](https://user-images.githubusercontent.com/53971863/162058026-aa83fe1d-87b5-4688-b333-2725ef3713c7.png)
Now facing this

**Comment by nagendraK6** [comment]
Same issue. Sol debited from the account

**Comment by alexjs-dev** [comment]
+1

**Comment by nagendraK6** [comment]
@vadimShlyapa  you can get the money from withdraw_all method.

**Comment by alexjs-dev** [comment]
> @vadimShlyapa  you can get the money from withdraw_all method.

99% of the sum would be given back, some amount is lost on gas fees

**Comment by calebrcannon** [comment]
Having timeout issues too.

**Comment by mcfriend99** [comment]
Anyone ever found a solution to this issue??
