### ISSUE TITLE
[Bug]: Creating auction - NFTs leave wallet but auction not created

### ISSUE THREAD

**Issue by jarvisjohnson** [metaplex-foundation/metaplex#2038]
### Which package is this bug report for?

storefront

### Issue description

Steps to reproduce:
1. Mint NFT on storefront (latest release 1.2.0)
2. Set auction live using a custom SPL token for 36 hrs

I tried many different times to create 8 auctions, eventually all 8 nfts left my wallet but no auctions were created.

Always gets stuck here 
![image](https://user-images.githubusercontent.com/12746936/162077541-b9d2e842-7983-4ddc-bdf8-96a9ea9011d6.png)

Site: https://pappataz-auctions-b426rwhkz-jarv.vercel.app/#/

Example transaction of trying to create auction:
https://explorer.solana.com/tx/3wtUfu4NBTgxvVhJCA4ywnN2JHhvQ86nH8dXCDnAFEDfFCSF1KRXug3isFWQkdZjZBefYeUGcuKD2zAajcxcpYv8
The item in question: https://pappataz-auctions-40m4tjia5-jarv.vercel.app/#/art/GFET5u6U1sfBK5PtWJRgVx2YTgBnszvX97YhRr3LCMwi

Can see the created artworks here: https://pappataz-auctions-b426rwhkz-jarv.vercel.app/#/artists/7k3QPfaQAWBf2yMDwRW2DEFd6uLYE1pJcyYY1VocKSZR.  Sometimes I can see the last 8 that I uploaded, but right now only 1 (the ones with human names are from a previous auction) - 
![image](https://user-images.githubusercontent.com/12746936/162077765-f76d8225-e931-43b5-a7b0-2ca8a21d6ca3.png)

Would appreciate it anyone has thoughts on this.  We've used this site before for auctions and it has mostly worked, this is the first time experiencing this issue of the auction not being created despite the NFTs leaving the wallet.

### Operating system

Vercel hosting

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by bbjansen** [comment]
> ### Which package is this bug report for?
> storefront
> 
> ### Issue description
> Steps to reproduce:
> 
> 1. Mint NFT on storefront (latest release 1.2.0)
> 2. Set auction live using a custom SPL token for 36 hrs
> 
> I tried many different times to create 8 auctions, eventually all 8 nfts left my wallet but no auctions were created.
> 
> Always gets stuck here ![image](https://user-images.githubusercontent.com/12746936/162077541-b9d2e842-7983-4ddc-bdf8-96a9ea9011d6.png)
> 
> Site: https://pappataz-auctions-b426rwhkz-jarv.vercel.app/#/
> 
> Example transaction of trying to create auction: https://explorer.solana.com/tx/3wtUfu4NBTgxvVhJCA4ywnN2JHhvQ86nH8dXCDnAFEDfFCSF1KRXug3isFWQkdZjZBefYeUGcuKD2zAajcxcpYv8 The item in question: https://pappataz-auctions-40m4tjia5-jarv.vercel.app/#/art/GFET5u6U1sfBK5PtWJRgVx2YTgBnszvX97YhRr3LCMwi
> 
> Can see the created artworks here: https://pappataz-auctions-b426rwhkz-jarv.vercel.app/#/artists/7k3QPfaQAWBf2yMDwRW2DEFd6uLYE1pJcyYY1VocKSZR. Sometimes I can see the last 8 that I uploaded, but right now only 1 (the ones with human names are from a previous auction) - ![image](https://user-images.githubusercontent.com/12746936/162077765-f76d8225-e931-43b5-a7b0-2ca8a21d6ca3.png)
> 
> Would appreciate it anyone has thoughts on this. We've used this site before for auctions and it has mostly worked, this is the first time experiencing this issue of the auction not being created despite the NFTs leaving the wallet.
> 
> ### Command
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Operating system
> Vercel hosting
> 
> ### Priority this issue should have
> Medium (should be fixed soon)
> 
> ### Check the Docs First
> * [x]  I have checked the docs and it didn't solve my issue

can confirm similar behavior. we gave up on metaplex storefront and are migrating to candy shop.
