### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by izzyx6** [metaplex-foundation/metaplex#2051]
### Which package is this bug report for?

candy machine ui

### Issue description

After launching my Candy Machine on the mainnet, I discovered users can mint while on mobile devices just on the desktop. They can't mint using either while on Android or IOS browsers. I have gone through the docs but no solution. Any idea how to solve this?

### Operating system

Android IOS

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by spp-a** [comment]
make sure they are visiting your mint site on a web3 browser - like the built in browser from SolFlare and Phantom mobile apps. You can check this yourself then close the issue

**Comment by izzyx6** [comment]
Thanks
