### ISSUE TITLE
[Feature]: Are there any ways to set exact time on whitelist presale?

### ISSUE THREAD

**Issue by tierracity** [metaplex-foundation/metaplex#2062]
### Which package is this feature request for?

candy machine cli

### Feature

I need to implement WL to my candy machine and I need to sex exact time of WL drop. How can I do this if presale has only true/false option

### Ideal solution or implementation

Maybe there are some hidden functions I don't know about or it just wasn't mentioned in metaplex docs

**Comment by HectorNBL** [comment]
You could distribute the WLST token once you've decided to start the presale.

**Comment by stegaBOB** [comment]
You can also update the candy machine with the WL option when you want the WL to start.
