### ISSUE TITLE
[Bug]: mainnet \ uploading assets missing item in config file

### ISSUE THREAD

**Issue by jocruz** [metaplex-foundation/metaplex#2064]
### Which package is this bug report for?

other

### Issue description

I had 2 sol in my wallet and I ran the command to upload to the mainnet and I got a message saying it is not known if the assets were uploaded successfully or not. I checked my config file and I do not see objects in the items array. I checked solana explorer and I received a successful status. My sol was taken out of my wallet however I do not know if my assets were successfully uploaded. Is there a way to check this or did the candy machine eat up my sol? 

### Command

```shell
$ ts-node .\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload --env mainnet-beta -k .\cm-two-devnet.json -c collection -cp .\metaplex\js\config.json --rpc-url https://spring-red-dew.solana-
```

### Relevant log output

```shell
initialized config for a candy machine with publickey: 2JmdjevFmjdBKHG6SZv7WhyZxW9N33Gv6HnoWNnFfTGL
[0] out of [1000] items have been uploaded
Starting upload for [1000] items, format {"mediaExt":".png","index":"0"}
0.088794553 SOL to upload 475.891MB with buffer
Current balance 0. Sending fund txn...
upload was not successful, please re-run. {
  message: 'Transaction was not confirmed in 30.01 seconds. It is unknown if it succeeded or failed. Check signature 57NAcAkQCQV7uYCHut3JhNK7UVVK6CPT8WKBRAnyusDPgCngd3wNqbipW4jqrwJRsQN18papecRr9w4NaE8FbZrY using the Solana Explorer or CLI tools.',
  txId: '57NAcAkQCQV7uYCHut3JhNK7UVVK6CPT8WKBRAnyusDPgCngd3wNqbipW4jqrwJRsQN18papecRr9w4NaE8FbZrY'
```

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by HectorNBL** [comment]
Based on the message from the console you probably have to re-run the upload command. You can also verify your upload. I suggest checking the verify section in the docs.

**Comment by HZfive** [comment]
run 

candy-cli show --env mainnet-beta -k .\cm-two-devnet.json --cache-name collection 

and check  the candy status
candy-cli is 

alias candy-cli="ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts"

on linux
