### ISSUE TITLE
[Bug]: Unable to load balance changes

### ISSUE THREAD

**Issue by Shaik-Sirajuddin** [metaplex-foundation/metaplex#2074]
### Which package is this bug report for?

candy machine ui

### Issue description

Hi , I have setup a candy machine with spltoken as mint , I have given the right splmintaddress and spltokenaccount , when I am on devnet the candy machine works perfectly fine with devnet spl token , but with mainnet it doesnt work good. 
Phatom says = Unable to fetch balance changes.
I dont know whats causing the error , I have tried spltoken address and but still its same.
Please look into it as early as possible.
Thanks

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by HectorNBL** [comment]
Can you try running `solana config get` and posting what you get?
