### ISSUE TITLE
[Bug]: Uploading NFT+json on metaplex

### ISSUE THREAD

**Issue by realsbd** [metaplex-foundation/metaplex#2075]
### Which package is this bug report for?

candy machine cli

### Issue description

Steps to reproduce:
ts-node src/candy-machine-v2-cli.ts upload -e devnet -k C:/Users/Test/Desktop/crypto_job/7fp/~/.config/solana/devnet-wallet.json -cp C:/Users/Test/Desktop/crypto_job/7fp/~/dev/config.json -c example --rpc-url https://api.devnet.solana.com ./assets

I get the following error message:

```
wallet public key: EhiAyuCUppXW9mMbh1QVoXiiPYkJV7wgQTDqMLs2WZU3
USING CUSTOM URL https://api.devnet.solana.com
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 100 (img+json) pairs
started at: 1650630433645
initializing candy machine
Error deploying config to Solana network. Error: Invalid config, creators shares must add up to 100
    at createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:136:11)
    at uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:45)
    at Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. Error: Invalid config, creators shares must add up to 100
    at createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:136:11)
    at uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:45)
    at Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Command

```shell
ts-node src/candy-machine-v2-cli.ts upload -e devnet -k C:/Users/Test/Desktop/crypto_job/7fp/~/.config/solana/devnet-wallet.json -cp C:/Users/Test/Desktop/crypto_job/7fp/~/dev/config.json -c example --rpc-url https://api.devnet.solana.com ./assets
```

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by overdeveloping** [comment]
This means that something is not right in your royalty structure, it needs to add up to 100.

**Comment by realsbd** [comment]
Finally figure it out, I set share to string ("100") instead of number

**Comment by DiegoDexx** [comment]
> 

But. where? in config.json or in metadata?

**Comment by overdeveloping** [comment]
> > 
> 
> But. where? in config.json or in metadata?

Creators array is in metadata so metadata is where you will see it.

**Comment by realsbd** [comment]
> > 
> 
> But. where? in config.json or in metadata?

You'll have to check each metadata for the NFT you're uploading

**Comment by tuncatunc** [comment]
What is creators array? Do  cmv2 support royalties for creators?
Just like, when the owner of the nft sells it on secondary market the 10% goes to creator?

**Comment by overdeveloping** [comment]
> What is creators array? Do cmv2 support royalties for creators? Just like, when the owner of the nft sells it on secondary market the 10% goes to creator?

Yes, CMv2 supports creators array. 

The creator array is: 
```
 "creators": [
      { "address": "N4f6zftYsuu4yT7icsjLwh4i6pB1zvvKbseHj2NmSQw", "share": 100 }
    ],
```

As you can see from this example metadata `.json` file

```
{
  "name": "Number #0010",
  "symbol": "NB",
  "description": "Collection of 10 numbers on the blockchain. This is the number 10/10.",
  "seller_fee_basis_points": 500,
  "image": "9.png",
  "attributes": [
    { "trait_type": "Layer-1", "value": "0" },
    { "trait_type": "Layer-2", "value": "0" },
    { "trait_type": "Layer-3", "value": "1" },
    { "trait_type": "Layer-4", "value": "0" }
  ],
  "properties": {
    "creators": [
      { "address": "N4f6zftYsuu4yT7icsjLwh4i6pB1zvvKbseHj2NmSQw", "share": 100 }
    ],
    "files": [{ "uri": "9.png", "type": "image/png" }]
  },
  "collection": { "name": "numbers", "family": "numbers" }
}
```

**Comment by tuncatunc** [comment]
What are those percentages mean?
Considering the following scenario 
The user mints the nft for 10 solanas
And lists the same nft on magic Eden what does the nft creator receives?
Thanks

**Comment by overdeveloping** [comment]
> What are those percentages mean? Considering the following scenario The user mints the nft for 10 solanas And lists the same nft on magic Eden what does the nft creator receives? Thanks

When creating a Solana Candy Machine, in the Config File, you will designate a `treasury address` in which **all mint funds** will be sent to.

In this case, the seller fee basis points is set at 500 which is 5%, so creators, in the creators array will get 5% royalty fees on secondary markets.

In the creators array, previously posted, all addresses in this array will receive secondary royalties when listed and sold on Marketplaces like Magic Eden and OpenSea, etc. 

Creators array must equal 100 in case you have more than 1 creator.

This array can also help to split the royalty fees to multiple creators based on shares (maximum 100).

**Comment by tuncatunc** [comment]
The cmv2 documentation doesn't mention about _****seller fee basis points****_ cmv1 does. Is it still a valid parameter?

**Comment by overdeveloping** [comment]
> The cmv2 documentation doesn't mention about _****seller fee basis points****_ cmv1 does. Is it still a valid parameter?

Yes, still valid parameter.

**Comment by tuncatunc** [comment]
Thank you again!
I did my research and find out the following information I think it can be useful for others too.

seller_fee_basis_points is a metadata field that's used by secondary markets.

https://docs.opensea.io/docs/contract-level-metadata

https://cdn.avanawallet.com/assets/media/blog/posts/72fc9fb3/metadata.json

I've been looking for it on candy machine documents however it's actually part of the metadata and used by secondary market
