### ISSUE TITLE
[Bug]: error: unknown command 'create_generative_art'

### ISSUE THREAD

**Issue by zoomz1337** [metaplex-foundation/metaplex#2077]
### Which package is this bug report for?

candy machine cli

### Issue description

hi =)
can someone help?
I'm getting this error at testing.

![grafik](https://user-images.githubusercontent.com/95316207/165120094-6916d304-af2d-4427-a803-1f3f545af863.png)

### Command

```shell
ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts create_generative_art -c traits-configuration.json -n 10 -ta true
```

### Operating system

Win 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by overdeveloping** [comment]
The _create_generative_art_ command was recently removed from the Metaplex candy machine repo, you will need to use another program like Hashlips to generate art.

**Comment by zoomz1337** [comment]
Thanks alot!!!
