### ISSUE TITLE
[Bug]: Undefined collection for an NFT mint using CM V2 (Invalid Account Discriminator)

### ISSUE THREAD

**Issue by SF-Prog** [metaplex-foundation/metaplex#2082]
### Which package is this bug report for?

candy machine ui

### Issue description

1. Used Metaplex candy-machine-ui code to perform a mint(mintOneToken) from an existing Candy Machine V2 uploaded through Metaplex's cli.
2. The collection for the minted NFT's metadata is set as undefined as the instruction `setCollectionDuringMint` is not being pushed to the instructions array.
3. [Link to the complete code](https://github.com/metaplex-foundation/metaplex/blob/2782e2710ac099238115f31682999fe553cc01be/js/packages/candy-machine-ui/src/candy-machine.ts#L559-L571)
```js 
const collectionData = (await anchorProgram.account.collectionPda.fetch( collectionPDA ));
``` 
This line is returning an error stating: `Invalid account discriminator`.
![Screen Shot 2022-04-26 at 13 24 14](https://user-images.githubusercontent.com/51452559/165347420-30e847ae-853b-45c7-862a-becfba3688de.png)

We are unable to understand how/why the Account types are not matching (as stated on the error).

Notes: 
 - This was tested in devnet for both candy machine creation alternatives: Manually setting the collection and letting Metaplex automatically set the collection.
 - Minting from the CLI pointing to the same CM works fine as the NFT has the collection set as expected.
 

### Operating system

macOS & Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by banafederico** [comment]
+1

**Comment by stegaBOB** [comment]
What version were you using before you downgraded?

**Comment by SF-Prog** [comment]
0.18.0

**Comment by Tonyce** [comment]
I also have this question，and resovle with https://github.com/metaplex-foundation/metaplex-program-library/pull/553
