### ISSUE TITLE
[Bug]: Mint fail and Unknown token in wallet.

### ISSUE THREAD

**Issue by Shaik-Sirajuddin** [metaplex-foundation/metaplex#2086]
### Which package is this bug report for?

candy machine ui

### Issue description

Hi , I have created a candy machine with spltoken as mint price . 
But when trying to mint , sometimes it succeeds but sometimes it fails and an unknown token appears in the wallet. 
This unexpected behaviour is causing our auction mint to go under issues. 
Please look into this as soon as possible because more projects might suffer due to this.
One of failed transaction : https://solscan.io/tx/4d95v3pfKm4iGVrM3fTZAfYe2NuYvYT1rbqBWjaAWEcyn1L2x33EGMALQVRGVp422sKvhmstjpdmGXVj7nzrFbzq
* I am using quicknode rpc.
Thank you in advance.

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by ingsoto83** [comment]
Hi have the same issue!
![Captura de Pantalla 2022-05-14 a la(s) 4 21 15](https://user-images.githubusercontent.com/8494550/168419641-2167d9ea-2958-43aa-959b-06c7981d34f1.png)

![Captura de Pantalla 2022-05-14 a la(s) 4 20 34](https://user-images.githubusercontent.com/8494550/168419592-2d807d6f-edda-41e2-95f0-989254d1ce24.png)
