### ISSUE TITLE
[Bug]: Ths new updated verson doest work he has a lot of bugs get error

### ISSUE THREAD

**Issue by Kunal123ETH** [metaplex-foundation/metaplex#2100]
### Which package is this bug report for?

candy machine cli

### Issue description

metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:240
      throw new Error(
            ^
Error: number of img files (0) is different than the number of json files (1)

### Relevant log output

```shell
metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:240
      throw new Error(
            ^
Error: number of img files (0) is different than the number of json files (1)
```

### Operating system

WD

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by spreadcharm** [comment]
Are your json files, and image files matching properly?
Like
0.png 0.json
1.png 1.json
2.png 2.json
...

**Comment by Kunal123ETH** [comment]
Yes my json files is matching properly

**Comment by spreadcharm** [comment]
https://github.com/metaplex-foundation/metaplex/issues/825
Hope this could help you.

**Comment by Kunal123ETH** [comment]
now  get this error Unexpected string in JSON at position 235
