### ISSUE TITLE
[Bug]: Error deploying config to Solana network. SendTransactionError: failed to send transaction: Node is behind by 38635 slots

### ISSUE THREAD

**Issue by realsbd** [metaplex-foundation/metaplex#2101]
### Which package is this bug report for?

candy machine cli

### Issue description

I want to upload my NFT on CMv2 using IPFS storage and I get this error.

![image](https://user-images.githubusercontent.com/29095985/166423199-3c651bd6-79c7-4c2f-8bc3-d39a24b4ead2.png)

HERE IS THE COMMAND
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ./mainnet-key.json -cp ~/dev/config.json -c mainnet --rpc-url https://solana--mainnet.datahub.figment.io/apikey/xxxxxxxx/ ~/metaplex/js/packages/cli/assets-original

Error deploying config to Solana network. SendTransactionError: failed to send transaction: Node is behind by 38635 slots

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ./mainnet-key.json -cp ~/dev/config.json -c mainnet --rpc-url https://solana--mainnet.datahub.figment.io/apikey/API_KEY/ ~/metaplex/js/packages/cli/assets-original
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by spreadcharm** [comment]
I have deployed two candymachine yesterday, they worked without any error.
By the way, I will advice you one important thing.
Please remove your private RPC url in your sentences.
https://solana--mainnet.datahub.figment.io/apikey/..................................
I don't know whether you are on paid or free API plan but 
even you are on free plan, it's not good to post here.

**Comment by realsbd** [comment]
> I have deployed two candymachine yesterday, they worked without any error. By the way, I will advice you one important thing. Please remove your private RPC url in your sentences. https://solana--mainnet.datahub.figment.io/apikey/.................................. I don't know whether you are on paid or free API plan but even you are on free plan, it's not good to post here.

Thank you for the heads up, I have removed it.

**Comment by realsbd** [comment]
> I have deployed two candymachine yesterday, they worked without any error. By the way, I will advice you one important thing. Please remove your private RPC url in your sentences. https://solana--mainnet.datahub.figment.io/apikey/.................................. I don't know whether you are on paid or free API plan but even you are on free plan, it's not good to post here.

Could it be because I don't have enough sol in my wallet?

I have 5 sol in my wallet because am trying to deploy to mainnet.

What is the total cost to deploy CM to mainnet

**Comment by realsbd** [comment]
I have to pull a new metaplex to get it working
