### ISSUE TITLE
[Bug]: Metaplex storefront: Network request failed

### ISSUE THREAD

**Issue by ernitingarg09** [metaplex-foundation/metaplex#2108]
### Which package is this bug report for?

storefront

### Issue description

1. git clone https://github.com/metaplex-foundation/metaplex.git
2. cd metaplex/js
3. yarn install && yarn bootstrap
4. yarn start
5. [localhost:3000](http://localhost:3000/#/)

Reference link: https://docs.metaplex.com/storefront/installation 

![image](https://user-images.githubusercontent.com/20875452/166913144-62056652-6f11-4256-a47c-88e386ba19bc.png)

![image](https://user-images.githubusercontent.com/20875452/166913236-bb982a4e-7a6b-48a6-ac95-f6bf3ca695ee.png)

### Operating system

Windows-10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by k0d3d** [comment]
For me, this happens when this request fails. check your console or network tab  
```
fetch("https://api.metaplex.solana.com/", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site",
    "sec-gpc": "1"
  },
  "referrer": "http://localhost:3000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"method\":\"getProgramAccounts\",\"jsonrpc\":\"2.0\",\"params\":[\"p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98\",{\"encoding\":\"base64\"}],\"id\":\"706ab600-87ab-46e9-954c-6f4276369223\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```
