### ISSUE TITLE
[Bug]: nft image and metadata not displayed on the solscan

### ISSUE THREAD

**Issue by Pengucci** [metaplex-foundation/metaplex#2109]
### Which package is this bug report for?

candy machine cli

### Issue description

using candy machine v2 i have  succefully uploaded metadata to arweave sol. following is the one of the nft meta data
""name": "SAGC Diamond Collection #0",
  "symbol": "SAGC",
  "description": "The SAGC Diamond Collection is an honorary collection made for our genesis collection top holders, partners and friends.",
  "seller_fee_basis_points": 800,
  "image": "0.png",
  "external_url": "https://shreddedapes.io/",
  "edition": 0,
  "attributes": [
    {
      "trait_type": "Name",
      "value": "Zeus"
    }
  ],
  "properties": {
    "files": [
      {
        "uri": "0.png",
        "type": "image/png"
      }
    ],
    "creators": [
      {
        "address": "cR95hfSfcGmXdHG2HcQdVw18o9BsNs83eEFDfjzepWT",
        "share": 100
      }
    ]
  },
  "collection": {
    "name": "SAGC Diamond Collection",
    "family": "Shredded Apes"
  }
}"
 

the uri is also working on the browser , but the issue is that nft metadata is not displayed on the solscan as well as in phantom wallet nft appears as  unknown token.

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Akardeon666** [comment]
Same for me

**Comment by cryptoart4fun** [comment]
Same here too

**Comment by Akardeon666** [comment]
i solved the problem. there is small paragraph in the metaplex manual that says: if you want to mint your tokens from cmd, you must set gatekeeper and livedate to null in the config file and then create a candy machine.

(This will enable a gatekeeper challenge once the mint button is clicked—only after passing the challenge you will be allowed to mint.

When you use a gatekeeper, you will not be able to mint from the CLI command mint_one_token. If you want to pre-mint from a CMv2 and are planning to use a gatekeeper, you should set the goLiveDate to null and turn gatekeeper (temporarily) off. This will allow you to mint from the command line, but only you as the CMv2 authority. Once you complete the pre-mint, turn gatekeeper on and set the correct goLiveDate.)
