### ISSUE TITLE
[Bug]: Error: not all NFTs checked out. check out logs above for details

### ISSUE THREAD

**Issue by realsbd** [metaplex-foundation/metaplex#2120]
### Which package is this bug report for?

candy machine cli

### Issue description

all 7777 NFTs have been uploaded but verify_upload cannot verify some of the NFT, I use Quicknode and figment to do the  upload.

![image](https://user-images.githubusercontent.com/29095985/167701709-17368436-c5bc-4a68-a096-ede452721191.png)

Quicknode rpc gives this error
![image](https://user-images.githubusercontent.com/29095985/167701974-325f5c75-d600-4faf-ae4d-a383d7289278.png)

but figment shows successful is true.

I am uploading to mainnet
How can I fix this, I really help

### Command

```shell
ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ./.config/solana/mainnet-key.json -cp ./dev/config.json -c example --rpc-url https://fragrant-purple-feather.solana-mainnet.quiknode.pro/xxxxxxxxxxxxxxx/ ./assets-original
```

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by apejawn** [comment]
stuck on the same part
upload said Done. Successful = true but the verify is a no go. Let me know if someone helps you out.

**Comment by realsbd** [comment]
I edit the cache file and set onChain to false for everything but still
stuck at the same exact number not checked out

**Comment by apejawn** [comment]
ahh dang and i re ran the upload cmd and got the same error, what's goofy about this all is there isn't much help from metaplex, nor is there a lot of info on errors like this concerning the candy machine creation. If i find something sooner than later ill let you know.

**Comment by apejawn** [comment]
it seems like the file size of the images may be too small. https://github.com/metaplex-foundation/metaplex/issues/638
check that thread out. im going to resize my collection and try again.

**Comment by apejawn** [comment]
nope same issue after i changed the file size, so idk what to do from here.

**Comment by joysiriban** [comment]
did anybody solve this? still getting same error
