### ISSUE TITLE
[Error] TypeError: Cannot read properties of undefined (reading 'program')

### ISSUE THREAD

**Issue by apejawn** [metaplex-foundation/metaplex#2127]
### Which package is this bug report for?

candy machine ui

### Issue description

trying to update config info in Candy Machine and im getting this message. 

const candyMachine = new PublicKey(cacheContent.program.candyMachine);
                                                    ^
TypeError: Cannot read properties of undefined (reading 'program')

where did I mess up?

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts update_candy_machine \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
 
```

### Operating system

mac

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by barjakuzu** [comment]
Same issue, I am unable to update Config file

**Comment by data-intelligence-analysis** [comment]
Running into the same issue for Devnet mint Test. Has there been a solution yet?

**Comment by aUsABuisnessman** [comment]
I dont know what a SRC is can Someone explain
