### ISSUE TITLE
[Bug]: error Couldn't find the binary git

### ISSUE THREAD

**Issue by arduinopng** [metaplex-foundation/metaplex#2137]
### Which package is this bug report for?

other

### Issue description

Why I am getting this error "error Couldn't find the binary git" and how can solve that problem?

### Command

```shell
yarn
```

### Relevant log output

```shell
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Operating system

Windows 11

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by arduinopng** [comment]
Solved it. What you guys have to do is just run your ide that you are using as an administrator.

**Comment by arthurbolsoni** [comment]
i have the same problem, with windows don't install only with linux. nothing solution working until now.
