### ISSUE TITLE
[Bug]: unkown collection on phantom, good on solscan ?

### ISSUE THREAD

**Issue by rxrxrxrx** [metaplex-foundation/metaplex#2163]
### Which package is this bug report for?

candy machine cli

### Issue description

I setup my candy machine : 

```
Key: 6v8FFTTNx1LA3Jx6sck2EpspwAo8J6pjXj8Ymfc6hXXX
1st creator : 6XC4ji3U1Bh6A1WK7ctRd2ufknmJ6y5tsADKHzyXXXX
authority:  BjKqKkvh77HdsBhZNBVKem42Hft5CAAWiH5z6b8XXXX
wallet:  BjKqKkvh77HdsBhZNBVKem42Hft5CAAWiH5z6bXXXX
Collection mint:  8NrZMYcMAk2QChiCKJxn8d4ge1Xqz43qXJTYXXXXX
Collection PDA:  DQU7uaY3uVHWVskYJ1B4mH5WPTjXrg3KSj3HXXXXX
tokenMint:  null
uuid:  100000
price:  0
itemsAvailable:  474
itemsRedeemed:  2
```

I minted 2 NFTs, with mint_one_token command, 
They show with the good metadata, picture, but in unknown collection. 

Here on solcan : 
https://solscan.io/collection/69f014ac9f2afba4a181b8f43534ea69286b5bdde9f101e6d949cbba349d76fd

Here on my wallet : 
<img width="1320" alt="Screenshot 2022-06-01 at 10 31 45" src="https://user-images.githubusercontent.com/91226684/171440303-227bc99f-5b2e-4a66-9f02-cfb362372e33.png">

I saw a new command with set_collection and -m but I dont get which ID I have to put after the M is it  69f014ac9f2afba4a181b8f43534ea69286b5bdde9f101e6d949cbba349d76fd ? 

Also why it seems to be perfect on solscan and not on phantom ? 
Thanks a lot for your help, I tried to find a solution during hours on this

- I would like to set the collection for the future mint
- I think I could use this https://collections.metaplex.com/create-collection to set up the collection on the one that I minted

I have to release this collection asap so, sorry I will put a high priority :/ 

### Operating system

MacOS

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by EF08** [comment]
<img width="668" alt="Solscan" src="https://user-images.githubusercontent.com/81588556/171549246-0e818855-7392-4849-bbfa-bc2bfbc17fe0.png"> 

From your link to solscan, I checked your NFT's Metaplex metadata and found that tokenStandard: 0. For popular collections that trade on Magic Edens like Okay Bears, this field "tokenStandard" doesn't even show up, let alone display a 0 value. I think this suggests that something about your .json files does not comply with the NFT token standard metadata that wallets like Phantom are currently using (which is probably weeks/months old). If I had to speculate what exactly is the deviation from Phantom's standard, it's probably related to the new set_collection command, as this was not in place at the time when the other NFT collections were minting (of which do not have "unknown collection issues on Phantom").

**Comment by ruskkartel** [comment]
> <img alt="Solscan" width="668" src="https://user-images.githubusercontent.com/81588556/171549246-0e818855-7392-4849-bbfa-bc2bfbc17fe0.png">
> 
> From your link to solscan, I checked your NFT's Metaplex metadata and found that tokenStandard: 0. For popular collections that trade on Magic Eden like Okay Bears, this field "tokenStandard" doesn't even show up, let alone display a 0 value. I think this suggests that something about your .json files does not comply with the NFT token standard metadata that wallets like Phantom are currently using (which is probably weeks/months old). If I had to speculate what exactly is the deviation from Phantom's standard, it's probably related to the new set_collection command, as this was not in place at the time when the other NFT collections were minting (of which do not have "unknown collection issues on Phantom").
> 
> (2) possible solutions:
> 
> Either (1): wait for Phantom to integrate this new "set_collection" feature into their NFT standard (maybe msg a dev there and ask when they'll do this?)
> 
> or
> 
> (2): Re-upload but include "-nc" in the command to turn off the on-chain collection feature from Metaplex (more info on line 117-120 in metaplex/js/packages/cli/src/candy-machine-v2-cli.ts --screenshot included: <img alt="Screen Shot 2022-06-02 at 6 06 38 PM" width="718" src="https://user-images.githubusercontent.com/81588556/171746746-5b5d0cf7-2d99-4752-8638-731676cdb236.png">) This should allow Phantom to show your NFT collection based on it's name.
> 
> Let me know your thoughts.

The amount of trial and error trying so many different possible solutions. Just wanted to say thanks!

**Comment by ruskkartel** [comment]
> > <img alt="Solscan" width="668" src="https://user-images.githubusercontent.com/81588556/171549246-0e818855-7392-4849-bbfa-bc2bfbc17fe0.png">
> > From your link to solscan, I checked your NFT's Metaplex metadata and found that tokenStandard: 0. For popular collections that trade on Magic Eden like Okay Bears, this field "tokenStandard" doesn't even show up, let alone display a 0 value. I think this suggests that something about your .json files does not comply with the NFT token standard metadata that wallets like Phantom are currently using (which is probably weeks/months old). If I had to speculate what exactly is the deviation from Phantom's standard, it's probably related to the new set_collection command, as this was not in place at the time when the other NFT collections were minting (of which do not have "unknown collection issues on Phantom").
> > (2) possible solutions:
> > Either (1): wait for Phantom to integrate this new "set_collection" feature into their NFT standard (maybe msg a dev there and ask when they'll do this?)
> > or
> > (2): Re-upload but include "-nc" in the command to turn off the on-chain collection feature from Metaplex (more info on line 117-120 in metaplex/js/packages/cli/src/candy-machine-v2-cli.ts --screenshot included: <img alt="Screen Shot 2022-06-02 at 6 06 38 PM" width="718" src="https://user-images.githubusercontent.com/81588556/171746746-5b5d0cf7-2d99-4752-8638-731676cdb236.png">) This should allow Phantom to show your NFT collection based on it's name.
> > Let me know your thoughts.
> 
> Such a beauty ... Works like a charm

Ran this for the upload and it shows now on phantom though your uploads are prone to bots setting the collections.


ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k keypair.json \
    -nc \
    -cp config.json \
    ./assets

**Comment by rxrxrxrx** [comment]
Thanks for the help,

So I get this result, it's better, but still, I would like to have the real name and not just "collection NFT" 
Any way to manage this ?
<img width="250" alt="Screenshot 2022-06-03 at 11 23 22" src="https://user-images.githubusercontent.com/91226684/171873387-f8275656-0c2b-4073-8eb0-8e0746a5d44b.png">

**Comment by EF08** [comment]
@rxrxrxrx we tested it and it will work if you start the process all over again with a new candy machine and the -nc function. However, if you want to keep this candy machine and you have updateAuthority + it is a mutable collection (changeable) then you should be able to remove_collection. Described in the screenshots from metaplex docs here ![image](https://user-images.githubusercontent.com/81588556/171902657-12b86e70-6194-4146-97cd-f354b6ddce43.jpeg)  

![image](https://user-images.githubusercontent.com/81588556/171902675-e7ced219-3420-4e56-a00f-26b1b86a83d9.jpeg)

Try this first ^ if that removes the on-chain collection metadata you should be good to go. Let us know if it works. If it does not, you'll have to re-upload to a new candy machine with -nc in the upload command.
