### ISSUE TITLE
[Feature]: generate_art command disapear ?

### ISSUE THREAD

**Issue by rxrxrxrx** [metaplex-foundation/metaplex#2181]
### Which package is this feature request for?

candy machine cli

### Feature

I use to generate my metadata with create_generative_art command from the candy machine v2,
But it seems its not available anymore...any reason for this ? 
This was a dope feature, way faster and easier than hashlips to handle rarity

### Ideal solution or implementation

Any way to get this feature back ? 
I tried to clone old repo but I didnt manage to make it works

**Comment by halaprix** [comment]
The command has been removed from metaplex cli, try here : https://github.com/halaprix/simple-NFT-generator
