### ISSUE TITLE
get NFT owner from NFT mint address

### ISSUE THREAD

**Issue by haris-aqeel** [metaplex-foundation/metaplex#2257]
I am able to get NFT details from the NFT mint address using metaplex.

![image](https://user-images.githubusercontent.com/56465230/194302428-6014976d-90a6-438d-99c0-24ddc410b8f3.png)

The above part is my code and in response I am getting a long NFT object, which contains 

`type Nft = Readonly<{
    model: 'nft';
    address: PublicKey;
    metadataAddress: Pda;
    updateAuthorityAddress: PublicKey;
    json: Option<Json>;
    jsonLoaded: boolean;
    name: string;
    symbol: string;
    uri: string;
    isMutable: boolean;
    primarySaleHappened: boolean;
    sellerFeeBasisPoints: number;
    editionNonce: Option<number>;
    creators: Creator[];
    tokenStandard: Option<TokenStandard>;
    collection: Option<{
        address: PublicKey;
        verified: boolean;
    }>;
    collectionDetails: Option<{
        version: 'V1';
        size: BigNumber;
    }>;
    uses: Option<{
        useMethod: UseMethod;
        remaining: BigNumber;
        total: BigNumber;
    }>;
    mint: {
        model: 'mint';
        address: PublicKey;
        mintAuthorityAddress: Option<PublicKey>;
        freezeAuthorityAddress: Option<PublicKey>;
        decimals: number;
        supply: SplTokenAmount;
        isWrappedSol: boolean;
        currency: SplTokenCurrency;
    };
    edition:
        | {
            model: 'nftEdition';
            isOriginal: true;
            address: PublicKey;
            supply: BigNumber;
            maxSupply: Option<BigNumber>;
        }
        | {
            model: 'nftEdition';
            isOriginal: false;
            address: PublicKey;
            parent: PublicKey;
            number: BigNumber;
        };
}>`

The above sample is of NFT response, I am receiving. Everything is fine, but now I want to get all nfts by owner of this particular nft.
I understand that metaplex provides us a function like this 

![image](https://user-images.githubusercontent.com/56465230/194303686-31f7269d-71d3-4670-b45d-f6d1fdac052a.png)

Here, if I can get the owner address in response, so I can be able to pass in owners address but unable to do so because the nft response does not contains the nft owners info(i.e, address).

**Comment by haris-aqeel** [comment]
@oboxodo @steveluscher @skypher @TomLisankie  Could you please respond to this issue?

**Comment by steveluscher** [comment]
Hi @haris-aqeel!

Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Metaplex itself.

Questions like yours deserve a purpose-built Q&A forum. Unless there exists evidence that this is a bug with Metaplex itself, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask

**Comment by lorisleiva** [comment]
Hey @haris-aqeel 👋 

As @steveluscher mentioned, the Solana stack exchange is a great place to ask questions like that.

The Metaplex JS SDK allows you to also fetch the "Token Account" associated with an NFT but for that, you either need to provide the `tokenAddress` or the `tokenOwner`. If you wanted to search for the owner of that NFT, you'd need a slightly more complicated approach as you'd have to perform a `getProgramAccount` call on the SPL Token program such that the mint address is equal to your NFT address.

Currently, the JS SDK does not support this operation but I think it would be a good feature request. In this case, I suggest creating an issue on [the Metaplex JS SDK repository](https://github.com/metaplex-foundation/js) directly explaining your use case and I will mark it as a feature request.

But please in the future, default to using Q&A forums first so we can focus our issues on bugs and improvements. Thank you for your understanding.

**Comment by haris-aqeel** [comment]
@lorisleiva I have opened an issue as per your direction. 

https://github.com/metaplex-foundation/js/issues/341
