### ISSUE TITLE
 Mainnet Candy Machine Number of items (11) do not match cache items (500).  Item number in the config should only include asset files, not the collection file.

### ISSUE THREAD

**Issue by 3alola** [metaplex-foundation/metaplex#2292]
PS C:\Users\3alola\Desktop\Solana\metaplex-master\Carsolautofinal\MyProject> sugar deploy  

Error running command (re-run needed): Number of items (11) do not match cache items (500).
            Item number in the config should only include asset files, not the collection file.
PS C:\Users\xxx\Desktop\Solana\metaplex-master\Carsolautofinal\MyProject> sugar deploy
[1/2] Loading candy machine
[1/2] Loading candy machine
Candy machine ID: 7PJcK16etzbS8T179tGGkU5XQ8Qi87nv37xGiGFxxxxx

[2/2] Writing config lines
Sending config line(s) in 29 transaction(s): (Ctrl+C to abort)
[00:01:34] Deploy failed ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/29
Error running command (re-run needed): Command failed due to the following reason(s):
  • Candy Machine: IndexGreaterThanLength: Index greater than length
  • Candy Guard: DataIncrementLimitExceeded: Exceeded account increase limit

**Comment by samuelvanderwaal** [comment]
The error message is giving you a strong hint:

> Error running command (re-run needed): Number of items (11) do not match cache items (500).
Item number in the config should only include asset files, not the collection file.

However, this kind of issue is better for [Discord](https://discord.gg/6FaDSP2zms) where you can get help troubleshooting it. If you find an actual bug in Sugar or Candy Machine please open an issue on those respective repos:  
* [Sugar](https://github.com/metaplex-foundation/sugar)  
* [Candy Guard](https://github.com/metaplex-foundation/mpl-candy-guard)
