### ISSUE TITLE
arweave mint NFT code.

### ISSUE THREAD

**Issue by jossemii** [metaplex-foundation/metaplex#232]
When metaplex mint an NFT, the Arweave's transactions are signed and submit on a cloudfunction.net service, anyone knows where is this code ????

Is in this code:

  // TODO: convert to absolute file name for image

  const result: IArweaveResult = await (
    await fetch(
      // TODO: add CNAME
      env.startsWith('mainnet-beta')
        ? 'https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFileProd2'  // CENTRAL
        : 'https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile2',    // CENTRAL
      {
        method: 'POST',
        body: data,
      },
    )
  ).json();

**Comment by fletchertyler914** [comment]
bump. Id like to see this code as well, and add NFT.storage pinning as an alternative.

**Comment by jossemii** [comment]
Yes, perhaps it would be convenient to store only the IPFS identifiers in the metadata, and from there incentivize their storage in Arweave or Filecoin without directly depending on one in particular.
I know that Arweave can be used over IPFS, but I don't know exactly how.

But definitely writing to the metadata, not even the Arweave identifier, if not its address in the Arweave.net node, doesn't seem like the best decision in terms of Byzantine fault tolerance. Not even relying on the storage incentive layer seems like a better decision in this context.

**Comment by BertrandBev** [comment]
I'd be down to have access to that code as well. It seems like it's responsible for replacing the url in the meta

**Comment by fletchertyler914** [comment]
Bump. 

Its been a while on this and i'm having issues uploading with metaplex cli.

```
Error uploading file 0 FetchError: invalid json response body at https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile4 reason: Unexpected token E in JSON at position 0
    at /snapshot/js/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
```

Would probably be easy to debug my issues if I knew what the function was doing.

**Comment by jossemii** [comment]
> Yes, it’s a very simple code, we can open source it later this week or next week.

Hi, could you share this code please ?

**Comment by cdric** [comment]
I am also running into the same error while trying to upload 2 png using the devnet environment
I use the following command:

`ts-node js/packages/cli/src/candy-machine-cli.ts upload ../assets --env devnet --keypair ../my-keypair.json --log-level trace -n 2`

Would love to get an update on this from the Metaplex team! 

Here is my console log:

```
setting the log value to: trace
Beginning the upload for 2 (png+json) pairs
started at: 1633289498998
wallet public key: {REDACTED]
program id from anchor cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ
Processing file: 0
Processing file: 0
Started awaiting confirmation for 2o7b7sTw95f79kxQCzGUBRZvBhiLJEv3DcVu8GihwtWLDAipvkQtbcHxpEzLBUffjs2K2v4jzMMPfXYqV9WLbHAS
REST null result for 2o7b7sTw95f79kxQCzGUBRZvBhiLJEv3DcVu8GihwtWLDAipvkQtbcHxpEzLBUffjs2K2v4jzMMPfXYqV9WLbHAS null
Resolved via websocket { err: null }
Returning status { err: null, slot: 84967604, confirmations: 0 }
Latency 2o7b7sTw95f79kxQCzGUBRZvBhiLJEv3DcVu8GihwtWLDAipvkQtbcHxpEzLBUffjs2K2v4jzMMPfXYqV9WLbHAS 1.4780001640319824
transaction for arweave payment: {
  txid: '2o7b7sTw95f79kxQCzGUBRZvBhiLJEv3DcVu8GihwtWLDAipvkQtbcHxpEzLBUffjs2K2v4jzMMPfXYqV9WLbHAS',
  slot: 84967604
}
trying to upload 0.png: #2
Error uploading file 0 FetchError: invalid json response body at https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile4 reason: Unexpected token E in JSON at position 0
    at /Users/cedric/Dev/Crypto/metaplex/js/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}
Processing file: 1
Started awaiting confirmation for 3YqMRjxbxDtcv1Vc4cqYk2kjviGAutimbbSy8vwQxuV1ZXYfNzSFKgSTrNXU5HptM8X6G9JXcaMXuVToZq9SmeF
REST no confirmations for 3YqMRjxbxDtcv1Vc4cqYk2kjviGAutimbbSy8vwQxuV1ZXYfNzSFKgSTrNXU5HptM8X6G9JXcaMXuVToZq9SmeF {
  confirmationStatus: 'confirmed',
  confirmations: 0,
  err: null,
  slot: 84968070,
  status: { Ok: null }
}
Resolved via websocket { err: null }
Returning status { err: null, slot: 84968073, confirmations: 0 }
Latency 3YqMRjxbxDtcv1Vc4cqYk2kjviGAutimbbSy8vwQxuV1ZXYfNzSFKgSTrNXU5HptM8X6G9JXcaMXuVToZq9SmeF 2.132999897003174
transaction for arweave payment: {
  txid: '3YqMRjxbxDtcv1Vc4cqYk2kjviGAutimbbSy8vwQxuV1ZXYfNzSFKgSTrNXU5HptM8X6G9JXcaMXuVToZq9SmeF',
  slot: 84968073
}
trying to upload 1.png: #1
Error uploading file 1 FetchError: invalid json response body at https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile4 reason: Unexpected token E in JSON at position 0
    at /Users/cedric/Dev/Crypto/metaplex/js/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}
Done. Successful = false.
upload was not successful, rerunning
[...]
```

**Comment by cdric** [comment]
Ok I just re-run the command and now it has been going through. So not sure what is going on. I will keep watching this issue though in case there is some underlying infrastructure issue.

**Comment by mattchiang777** [comment]
Very strange, I was running into the same things you were

**Comment by lnrssll** [comment]
I am getting the same error as @cdric. I was curious how the upload command would work with arweave on devnet because you aren't using mainnet sol and the upload command is said to convert sol to ar for storage... I'm guessing that may be the issue here? However, I haven't seen any commentary on this in any tutorials, which is surprising because they all use devnet. My devnet wallet balance has some balance deducted by about .024 devnet sol, which I assume is mostly for the arweave exchange (arweave fees for my upload of 335M are estimated at about $3.40USD = .017 SOL), which presumably isn't successfully being converted into AR. My hypothesis is that the JSON response error from https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile has to do with this. Any advice?

**Comment by samuelvanderwaal** [comment]
Upload functionality is being reworked to deprecate the cloud function and provide more storage options.
