### ISSUE TITLE
Why is Page always blank when creating a new NFT ?

### ISSUE THREAD

**Issue by zdbrig** [metaplex-foundation/metaplex#25]
![Screen Shot 2021-06-07 at 11 16 40 AM](https://user-images.githubusercontent.com/934740/121000249-e57fd200-c781-11eb-8f00-3cfcdf4580cf.png)

**Comment by gching** [comment]
Have you created a NFT already on the platform? A reason why this might be blank is cause your wallet does not have any NFTs associated to it

**Comment by zdbrig** [comment]
@gching I don't see any button  / tool to create an NFT ?

**Comment by gching** [comment]
That might mean you have not created your store, or have not whitelisted yourself as a creator. See if this guide helps you with your issue: https://github.com/metaplex-foundation/metaplex/blob/master/docs/create-store.md

If you have any questions, I would suggest to get onto the Discord and ask your questions there! I am on there as well :).

**Comment by bartosz-lipinski** [comment]
Please create a store.

**Comment by halimabergaoui** [comment]
I also have this issue. I tried creating a store but I m blocked

https://user-images.githubusercontent.com/16075710/124579388-f7b76380-de46-11eb-9b2a-fbcf8220b5fd.mp4
