### ISSUE TITLE
Vercel Build Issues - TS6200: Definitions of the following identifiers conflict with those in another file

### ISSUE THREAD

**Issue by shrimpyuk** [metaplex-foundation/metaplex#264]
I followed the deploy guide as mentioned, however get a confliction preventing it from being built at stage 5/5:
`[5/5] Building fresh packages...
00:04:13.685
Done in 95.15s.
00:04:13.725
Detected Next.js version: 11.0.1
00:04:13.726
Running "yarn run build"
00:04:14.071
yarn run v1.22.10
00:04:14.107
$ lerna run build
00:04:14.524
lerna notice cli v3.22.1
00:04:14.528
lerna info versioning independent
00:04:14.528
lerna info ci enabled
00:04:14.579
lerna info Executing command in 3 packages: "yarn run build"
00:04:30.116
lerna info run Ran npm script 'build' in '@oyster/common' in 15.5s:
00:04:30.116
$ run-s build-ts build-css
00:04:30.116
$ tsc
00:04:30.117
$ less-watch-compiler src/ dist/lib/ --run-once
00:04:30.117
Running less-watch-compiler once.
00:04:30.165
lerna ERR! yarn run build exited 2 in '@metaplex/cli'
00:04:30.166
lerna ERR! yarn run build stdout:
00:04:30.166
$ tsc -p ./src
00:04:30.167
../../node_modules/@solana/web3.js/lib/index.d.ts(2,1): error TS6200: Definitions of the following identifiers conflict with those in another file: Struct, Enum, SOLANA_SCHEMA, MAX_SEED_LENGTH, PublicKeyInitData, PublicKeyData, PublicKey, Account, Blockhash, BPF_LOADER_DEPRECATED_PROGRAM_ID, EpochSchedule, NONCE_ACCOUNT_LENGTH, NonceAccount, Keypair, MessageHeader, CompiledInstruction, MessageArgs, Message, TransactionSignature, PACKET_DATA_SIZE, AccountMeta, TransactionInstructionCtorFields, SerializeConfig, TransactionInstruction, SignaturePubkeyPair, TransactionCtorFields, NonceInformation, Transaction, TokenAccountsFilter, Context, SendOptions, ConfirmOptions, ConfirmedSignaturesForAddress2Options, SignaturesForAddressOptions, RpcResponseAndContext, Commitment, Finality, LargestAccountsFilter, GetLargestAccountsConfig, SignatureStatusConfig, ContactInfo, VoteAccountInfo, VoteAccountStatus, InflationGovernor, InflationReward, EpochInfo, LeaderSchedule, Version, SimulatedTransactionResponse, ParsedInnerInstruction, TokenBalance, ParsedConfirmedTransactionMeta, CompiledInnerInstruction, ConfirmedTransactionMeta, TransactionResponse, ConfirmedTransaction, PartiallyDecodedInstruction, ParsedMessageAccount, ParsedInstruction, ParsedMessage, ParsedTransaction, ParsedConfirmedTransaction, BlockResponse, ConfirmedBlock, ConfirmedBlockSignatures, PerfSample, Supply, TokenAmount, TokenAccountBalancePair, AccountBalancePair, SlotUpdate, SlotInfo, ParsedAccountData, StakeActivationData, DataSlice, MemcmpFilter, DataSizeFilter, GetProgramAccountsFilter, GetProgramAccountsConfig, GetParsedProgramAccountsConfig, AccountInfo, KeyedAccountInfo, AccountChangeCallback, ProgramAccountChangeCallback, SlotChangeCallback, SlotUpdateCallback, SignatureResultCallback, SignatureStatusNotification, SignatureReceivedNotification, SignatureSubscriptionCallback, SignatureSubscriptionOptions, RootChangeCallback, Logs, LogsFilter, LogsCallback, SignatureResult, TransactionError, TransactionConfirmationStatus, SignatureStatus, ConfirmedSignatureInfo, HttpHeaders, FetchMiddleware, ConnectionConfig, Connection, BPF_LOADER_PROGRAM_ID, BpfLoader, Loader, STAKE_CONFIG_ID, Authorized, Lockup, CreateStakeAccountParams, CreateStakeAccountWithSeedParams, InitializeStakeParams, DelegateStakeParams, AuthorizeStakeParams, AuthorizeWithSeedStakeParams, SplitStakeParams, WithdrawStakeParams, DeactivateStakeParams, StakeInstruction, StakeInstructionType, StakeAuthorizationType, StakeAuthorizationLayout, StakeProgram, CreateAccountParams, TransferParams, AssignParams, CreateAccountWithSeedParams, CreateNonceAccountParams, CreateNonceAccountWithSeedParams, InitializeNonceParams, AdvanceNonceParams, WithdrawNonceParams, AuthorizeNonceParams, AllocateParams, AllocateWithSeedParams, AssignWithSeedParams, TransferWithSeedParams, SystemInstruction, SystemInstructionType, SystemProgram, CreateSecp256k1InstructionWithPublicKeyParams, CreateSecp256k1InstructionWithEthAddressParams, CreateSecp256k1InstructionWithPrivateKeyParams, Secp256k1Program, VALIDATOR_INFO_KEY, Info, ValidatorInfo, VOTE_PROGRAM_ID, Lockout, EpochCredits, VoteAccount, SYSVAR_CLOCK_PUBKEY, SYSVAR_RECENT_BLOCKHASHES_PUBKEY, SYSVAR_RENT_PUBKEY, SYSVAR_REWARDS_PUBKEY, SYSVAR_STAKE_HISTORY_PUBKEY, SYSVAR_INSTRUCTIONS_PUBKEY, Cluster, LAMPORTS_PER_SOL`

**Comment by nftintern** [comment]
This should be fixed with #270, please fork my repo or apply my patch locally in the interim

**Comment by jordansexton** [comment]
Thanks @nftintern. Closing as your PR has been merged.
