### ISSUE TITLE
Store Creation - Blank "White" Homepage.

### ISSUE THREAD

**Issue by TheCryptoKing-NFT** [metaplex-foundation/metaplex#273]
When running Yarn build, command executes successfully.
However homepage is blank.

```
┌──(kali㉿kali)-[~/metaplex/js]
└─$ sudo yarn build                                                                                                                                             1 ⨯ 1 ⚙
yarn run v1.22.11
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@oyster/common' in 24.9s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna info run Ran npm script 'build' in '@metaplex/cli' in 26.8s:
$ tsc -p ./src
lerna info run Ran npm script 'build' in 'web' in 33.3s:
$ next build
info  - Loaded env from /home/kali/metaplex/js/packages/web/.env.production
info  - Loaded env from /home/kali/metaplex/js/packages/web/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/3)
info  - Generating static pages (3/3)
info  - Finalizing page optimization...

Page                              Size     First Load JS
┌ ○ /                             2.51 kB        74.2 kB
├   /_app                         0 B            71.7 kB
└ ○ /404                          1.37 kB        73.1 kB
+ First Load JS shared by all     71.7 kB
  ├ chunks/framework.797e44.js    42.6 kB
  ├ chunks/main.c36859.js         24.2 kB
  ├ chunks/pages/_app.569de5.js   2.51 kB
  ├ chunks/webpack.68fc45.js      2.37 kB
  └ css/167ee118182b8b4410af.css  75.3 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

lerna success run Ran npm script 'build' in 3 packages in 58.2s:
lerna success - @metaplex/cli
lerna success - @oyster/common
lerna success - web
Done in 59.06s.
```
![image](https://user-images.githubusercontent.com/89927340/131744518-5c9be4e6-a0b7-41e5-9401-eee882380bee.png)

**Comment by BoitToken** [comment]
@TheCryptoKing-NFT Same thing is happening with me also. If you got the solution please share it

**Comment by TheCryptoKing-NFT** [comment]
I still don't have a solution but it appears the web application cant load the scripts. I have a feeling this may be a user configuration issue as the files are definitely loaded into git GH pages. 

This is the errors i'm seeing.

![image](https://user-images.githubusercontent.com/89927340/131822605-eeb0d28c-bc90-445d-ba88-ce3ebca06f13.png)

**Comment by Thesnipergecko** [comment]
I had this issue, I assume you are hosting your own domain via Github pages?

You need to change the path to the scripts in package.json. Just under where you edit the path to your Git repo.

ASSET_PREFIX needs to be blank like below.

"deploy": "cross-env ASSET_PREFIX= yarn build && yarn deploy:gh",

**Comment by TheCryptoKing-NFT** [comment]
Thanks for the response. 
I have changed this line so that it matches the above however experiencing the same issue. 
Any further advice?

![image](https://user-images.githubusercontent.com/89927340/132007557-f6ba1a70-73a5-47bf-b50a-600a978d1772.png)

**Comment by Thesnipergecko** [comment]
You could try to delete your build folder and re-run yarn deploy.

It could also be using cached files from GIT. Try a hard refresh a couple of times. Check the source of the page to see if its still trying to load the assets from /metaplex/foo/bar/baz.js

**Comment by TheCryptoKing-NFT** [comment]
Thanks, i can confirm this has resolved this issue. 
Also needed to run "yarn deploy" from the "web" directory which i didn't realise.

Thanks for thelp.
Closing.
