### ISSUE TITLE
Non-whitelisted Creator can not create new auction on Public Store

### ISSUE THREAD

**Issue by phamngocmy177** [metaplex-foundation/metaplex#276]
_The store also can be either public or private, which determines whether or not AuctionManagers can sell items that have all non-whitelisted creators on them or not_

I read this line in the documentation and understood that if the store is public, anyone can create an auction. (correct me if I'm wrong)

I have made the store public, but I can't create an auction with an account that is not a whitelist creator (I can create NFT with this account). The create auction process returns these errors: **Uninitialized** and **AuctionManagerMustBeValidated** (Auction manager must be validated to start auction!)

Please let me know how everyone can create auctions. (e.g. modify the contract, modify web code, need more actions from the store owner,....)

**Comment by jordansexton** [comment]
I'm not sure what action is desired here so I'm closing this issue. Please comment if there's more detail on what your issue is.

**Comment by gabrielkoerich** [comment]
@jordansexton I got the same issue. I'm creating an instant sale auction with a store which has `public = true`, but  `validate_safety_deposit_box_v2` is returning an error that the creator is not whitelisted.. If I keep it blank it returns **Uninitialized**. It looks like is ignoring the public flag.  I'm testing it on devnet.

**Comment by jordansexton** [comment]
Thanks for the additional detail, I'll leave this open for the core maintainers.
