### ISSUE TITLE
Can't see the NFT I create

### ISSUE THREAD

**Issue by catxii** [metaplex-foundation/metaplex#277]
anything is successful,unit when i run it at localhost,i change network to testnet,i creatored a nft，but i can't see it.it's not work in the localhost?

**Comment by catxii** [comment]
![搬砖怪谈0902192319](https://user-images.githubusercontent.com/2385075/131855103-868a7656-6f90-436a-8f2c-80aa7afd0e75.png)
![搬砖怪谈0902192657](https://user-images.githubusercontent.com/2385075/131855129-508d8485-5916-4cd5-8815-3e86a6c4c432.png)
![搬砖怪谈0902192703](https://user-images.githubusercontent.com/2385075/131855137-db809eb0-f24c-48b9-96b0-de7069a9c94b.png)

**Comment by catxii** [comment]
![搬砖怪谈0902192159](https://user-images.githubusercontent.com/2385075/131855260-fb585b7f-8603-4c8e-a70b-18a94442a0d7.png)
![搬砖怪谈0902192226](https://user-images.githubusercontent.com/2385075/131855269-0a1f508f-f01b-4aab-ad1b-6ad681c56ffd.png)

**Comment by catxii** [comment]
![搬砖怪谈0902214842](https://user-images.githubusercontent.com/2385075/131855451-6ea34c43-cc1d-40d8-a8f1-77e040258233.png)
![搬砖怪谈0902214847](https://user-images.githubusercontent.com/2385075/131855484-a13246c1-0ddd-43e9-9ed9-550fe599fb40.png)
![搬砖怪谈0902214906](https://user-images.githubusercontent.com/2385075/131855488-d6e364ce-2b5c-4201-93a3-88498d2ec292.png)

**Comment by tunnckoCore** [comment]
Same here. With Holaplex, on devnet.

**Comment by catxii** [comment]
I succeeded on the mainet bate, but found another problem. Sometimes I submit the NFT only once for confirmation, and then get stuck at 99%. After the manual refresh, it prompts success, but in fact it did not succeed. A normally successful NFT will have two wallet confirmations.

**Comment by keikumata** [comment]
I'm unable to get this to work in neither `devnet` nor `testnet`. I would prefer not to test this out in `mainnet-beta` since this requires real SOL tokens. Is there a workaround for this?

**Comment by peeper35** [comment]
Can we reopen this, I am having this same behaviour on testnet. Is there any explaination regarding this?
