### ISSUE TITLE
Add metadata for a token without mint authority results in error

### ISSUE THREAD

**Issue by dvcrn** [metaplex-foundation/metaplex#279]
When trying to create a simple NFT token and adding metadata for it to metaplex I'm getting:

```
Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa
    Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
    Program log: Instruction: Create Metadata Accounts
    Program log: Mint authority provided does not match the authority on the mint
    Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 22108 of 200000 compute units
    Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom program error: 0xa
```

Token created with

```
spl-token create-token
spl-token create-account <token>
spl-token mint <token>
spl-token authorize <mint> --disable
```

When I leave the mint authority I can register it, but isn't the point of adding metadata to NFTs that those NFTs don't have a mint authority? Why does the metadata program only permit metadata for tokens with mint authority? 

Is it fine to remove the mint authority after I've added it to metaplex? 

Line in question: https://github.com/metaplex-foundation/metaplex/blob/e1ab4494c45f37a874ad674a0d43ca31065485dc/rust/token-metadata/program/src/utils.rs#L807-L809

**Comment by cihantas** [comment]
Same issue here. Anybody got any clue?
