### ISSUE TITLE
metaplex store showing blank white page

### ISSUE THREAD

**Issue by MuzziTrading** [metaplex-foundation/metaplex#284]
so I decided to make a nft store on metaplex. I did all the steps in to video exactly and when I go to check out my store it is just a blank white page.

**Comment by fengyuanlin** [comment]
I'm also at this point. On my phone, it's just a blank page and on my pc, it's just loads until timeout error. But Github Pages shows it as being published and completely fine. Just doesn't show the "Theme" option.

**Comment by Skyfz** [comment]
Localhost Running fine, gh-pages White-Screen for some reason...
Appreciate the work @bhgames

**Comment by MuzziTrading** [comment]
here is the site I used for reference. [https://solana.blog/solana-metaplex-tutorial-deploy-your-own-store-mint-nfts-and-setup-auctions/](url)

**Comment by Thesnipergecko** [comment]
Try this.

https://github.com/metaplex-foundation/metaplex/issues/273

**Comment by pencaster** [comment]
Here it is the deployment guide:
https://github.com/metaplex-foundation/metaplex/blob/master/docs/deploy.md
However in case of custom domain deploying to GitHub pages, the only way I was able to get it to work is to change in js\packages\web\package.json as shown below :

    **"deploy:gh": "gh-pages -d ../../build/web --repo https://github.com/pencaster/CryptoNFTs -t true",
    "deploy": "gh-pages -d ../../build/web --repo https://github.com/pencaster/CryptoNFTs -t true",**



 in the deployment guide it is specified using "yarn export" for  "deploy:gh" , which did not work for me

"deploy:gh": "**yarn export &&** gh-pages -d ../../build/web --repo https://github.com/my-name/my-metaplex -t true"
"deploy": "yarn build && yarn deploy:gh",

**Comment by MuzziTrading** [comment]
that did the trick! thank you! 

now closing
