### ISSUE TITLE
createAuctionManager : Runtime Error (failed to create)

### ISSUE THREAD

**Issue by Skyfz** [metaplex-foundation/metaplex#293]
![Screenshot 2021-09-04 032317](https://user-images.githubusercontent.com/68149800/132077854-f4d28dc9-72a7-451e-a425-952fc6d89417.png)

**Comment by jordansexton** [comment]
Closing this issue as there is no context on how to reproduce it. Please comment with detailed steps if this is still occurring for you.

**Comment by ilanoh** [comment]
this issue happen when following the creation store https://docs.metaplex.com/create-store/create
after creating a NFT, and trying to sell a fixed number of copies, when creation is at 99% we receive this error
