### ISSUE TITLE
spl-token-metadata and spl-token-vault are owned by 3rd party on crates.io

### ISSUE THREAD

**Issue by jstarry** [metaplex-foundation/metaplex#301]
Hey @amgmoyo, thanks for holding onto https://crates.io/crates/spl-token-metadata and https://crates.io/crates/spl-token-vault! We'd like to keep those crates up-to-date in CI for the community, can you please add `solana-grimes` as an owner to match existing spl crates like https://crates.io/crates/spl-token?

Thanks 🍻

**Comment by amgmoyo** [comment]
Yeah no worries, sorry about stealing it, It wasn't uploaded onto crates for a few days and I needed it for some tests, will add as owner.

**Comment by amgmoyo** [comment]
Sent the invite, feel free to remove me once you've accepted. You are the rightful owners, after all.

**Comment by jstarry** [comment]
Thanks! Yeah sorry it wasn't deployed yet. Will make sure that gets accepted soon
