### ISSUE TITLE
Candy machine only accepts integers for price

### ISSUE THREAD

**Issue by 21e8** [metaplex-foundation/metaplex#308]
Hi,

this is somewhat unexpected behviour for some:
The rust code for candy machine specifies `u64` as the type for sale price of candy machine NFTs. I would very much like to propose to change this to `f32` or `f64` but I am unaware of what the consequences might be or why it was chosen to be an integer in the first place.

However, with rising prices, I am pretty certain the community will want to do fractions.

Price is being casted both in JS and in Rust, the JS part is a one-liner but the Rust part would need to be redeployed and the cli would need to updated with that new deployement, if I did not misunderstand the concept.

For now I wanna add a warning to CLI for users to have predictable results, as currently the casting is silent and pretty significant.

Would love to help in any way possible.

**Comment by DevonBernard** [comment]
@21e8 is the sale price represented in lamports or Sol? I'm guessing it'd be in lamports, but I'm not sure (haven't checked out that part of the codebase). If it is in lamports though, a whole-number amount would presumably be fine because 1 lamport ~= 0.000000001 SOL.

**Comment by 21e8** [comment]
@DevonBernard 

> @21e8 is the sale price represented in lamports or Sol? I'm guessing it'd be in lamports, but I'm not sure (haven't checked out that part of the codebase). If it is in lamports though, a whole-number amount would presumably be fine because 1 lamport ~= 0.000000001 SOL.

SOL, pretty sure.

Here the argument is mutilplied to lamports:
https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/cli.ts#L560

And here it is being consumed:
https://github.com/metaplex-foundation/metaplex/blob/master/rust/nft-candy-machine/src/lib.rs#L516

I tested candy machine with sub-1 values and was asked for nothing but tx fees.

I wanted to test this further but have not yet been able to

**Comment by 21e8** [comment]
it defaults to `1` which is what happened with aurory I think

**Comment by 21e8** [comment]
My workaround was to create a transfer instruction from the frontend but should someone find the uuids they could mint at a price that is floored to the next smallest integer, at least that is what my suspicion so far told me.

**Comment by 21e8** [comment]
I tried changing the CLI code to respect floats but the program would not do that properly.
Gotta check back with this tomorrow

**Comment by BertrandBev** [comment]
https://github.com/metaplex-foundation/metaplex/pull/321

**Comment by uaktags** [comment]
https://github.com/metaplex-foundation/metaplex/commit/929a5e269736147b58d846c0398c9804ddb407a4
merged with that commit.

**Comment by 21e8** [comment]
@uaktags sorry but `Math.ceil(parseFloat(solPriceStr))` is still being rounded up. will do this myself

**Comment by 21e8** [comment]
https://github.com/metaplex-foundation/metaplex/pull/333

**Comment by uaktags** [comment]
with #333 closed, doesn that mean the Math.Ceil is still considered correct?

**Comment by 21e8** [comment]
@uaktags `Math.ceil` is being called on the product of `price` and `LAMPORTS_PER_SOL` to make a lamport integer. It is fine.

try it: `Math.ceil(parseFloat('0.05') * 1000000000)` will give you `LAMPORTS_PER_SOL / 2`

**Comment by 21e8** [comment]
they want to avoid feeding floats to the contract which I completely understand

**Comment by arboretum-life** [comment]
I'm experiencing the same (i.e., when I set a price of 0.5 SOL, it only charges the buyer the transaction fee).
