### ISSUE TITLE
Unable to connect the store due to timeout error

### ISSUE THREAD

**Issue by Shery11** [metaplex-foundation/metaplex#31]
I have successfully connected my phantom wallet. I am using testnet but when i try to create initiate my store i get the following error. Can you please tell me what this issue is. 
Please check the screenshot. 
![Screenshot 2021-06-12 at 12 16 41 AM](https://user-images.githubusercontent.com/21175010/121739224-bf0cbe80-cb14-11eb-9980-180c117ec20f.png)

**Comment by bartosz-lipinski** [comment]
Metaplex is not deployed yet on testnet, we will deploy it to testnet this weekend. Please use devnet or mainnet for now.

**Comment by MartinSchere** [comment]
Having the same issue here. Using devnet

**Comment by Amirjab21** [comment]
Also have the same issue when using devnet.

Are you sure it works on devnet?
