### ISSUE TITLE
Strange behaviour in the candy machine uploadFile3 service

### ISSUE THREAD

**Issue by thmlemke** [metaplex-foundation/metaplex#318]
There seems to be some strange behaviour in the 'https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile3' service used in the candy machine CLI. Is the repo for this open?

The service returns successful upload of PNG even if it doesn't seem to succeed to fech the data after the fact, and it replaces the type parameter in the JSON in the metadata if it is "image/png" (regex match on 'image.png'?), Ex:

`{
    "name": "test0",
    "symbol": "",
    "seller_fee_basis_points": 0,
    "image": "https://www.arweave.net/yD_duhm2VnclBHQUlRy0g8rB3MF8DVS5v5EIkCn3cvs?ext=png",
    "properties": {
        "creators": [
            {
                "address": "uhC3gJN5pmz4wF9VxK1JWwHuz4wBw1K5DPkFk26z8rV",
                "share": 100
            }
        ],
        "files": [
            {
                "uri": "https://www.arweave.net/yD_duhm2VnclBHQUlRy0g8rB3MF8DVS5v5EIkCn3cvs?ext=png",
                "type": "https://www.arweave.net/yD_duhm2VnclBHQUlRy0g8rB3MF8DVS5v5EIkCn3cvs?ext=png"
            }
        ]
    }
}`

**Comment by thmlemke** [comment]
I replaced the type descriptor with Image/png and it did not replace that.

**Comment by bartosz-lipinski** [comment]
this should be resolved now. Please name images with  0-N e.g. 0.png and matching json file.
