### ISSUE TITLE
I cant see data`s of my website(site isnt loading)

### ISSUE THREAD

**Issue by samanara** [metaplex-foundation/metaplex#322]
![nopa](https://user-images.githubusercontent.com/69543087/132258331-52aceecc-a6c4-42c1-9cc4-1ba3d7605e9a.jpg)
 I cant reach metaplex,its been 2 days maybe someone can help me. I redeployed with vercel but its still not loading.

**Comment by samanara** [comment]
https://solshrooms.shop/#/

**Comment by pencaster** [comment]
You can see the ended auctions.
Probably there is no Solana in your wallet?
![image](https://user-images.githubusercontent.com/3015704/132547774-b7fcbe9a-53ce-43f4-9138-1a214fce10e2.png)

**Comment by marsupilak** [comment]
I have the same problem but you seem solving it. How do you solve? My page is not loading now!

**Comment by samanara** [comment]
> I have the same problem but you seem solving it. How do you solve? My page is not loading now!
A guy replied my question on Solsea it broke my store and a few others

I have the code to check if something is undefined, it fixes it. give me a sec

it's metaplex code not anticipating something solsea did :slight_smile:

in the file https://github.com/DunnCreativeSS/metaplex/blob/master/js/packages/web/src/contexts/meta/processMetaData.ts

const isMetadataAccount = (account: AccountInfo<Buffer>) => {
  if (account != undefined) {
    return (account.owner as unknown as any) === METADATA_PROGRAM_ID;
  } else {
    return false;
  }
};

**Comment by jordansexton** [comment]
@samanara it sounds like you fixed the issue? I'm closing this issue for now, but if this is a bug in Metaplex, please do open a PR with your fix.
