### ISSUE TITLE
After connecting wallet the create/sell buttons do not appear.

### ISSUE THREAD

**Issue by BrokenSkullzNFT** [metaplex-foundation/metaplex#324]
After connecting wallet the create/sell buttons do not appear, anyone else had this issue?

**Comment by TheNFTenigma** [comment]
Yes! I’ve tried a few times & always same - no create/sell buttons 🤬 Have you managed to get a fix? (Using Phantom)

**Comment by BrokenSkullzNFT** [comment]
Yeah same phantom, but after initialising the store as you say it just doesn't show, and no, no fix as of yet, hope someone can help.

**Comment by TheNFTenigma** [comment]
Update - changed wallet address in .env to a Solflare address & rebuilt store & now works - everything shows up.

**Comment by BrokenSkullzNFT** [comment]
Oh wow really? I'll try it out asap, thank you

**Comment by BrokenSkullzNFT** [comment]
I changed the wallet address in .env and rebuilt/deployed but when i press connect with solfare an extra window pops up with solfare website, my wallet opens but on the metaplex store it still says connect.

**Comment by saraspaudel** [comment]
+1 Still facing this issue

**Comment by samuelvanderwaal** [comment]
Closing due to no response/inactivity.
