### ISSUE TITLE
What is IS_BIG_STORE?

### ISSUE THREAD

**Issue by israelidanny** [metaplex-foundation/metaplex#327]
I see this environment variable but it's not well documented.

**Comment by israelidanny** [comment]
From what I understand, currently the only utility is that IS_BIG_STORE decides to forego the loading of metadata filtered by creator accounts and just loads the whole entire 500k+ metadata accounts from the blockchain.

Is this something that has real utility? Once I hit that limitation - the frontend became practically unusable. It'd seem to be far better to explain the 3 creators as a hard limit than try to load up the whole Metaplex blockchain universe into the browser.

**Comment by AlexLeung** [comment]
Is there a way we can just load some specific nfts? Perhaps by mint authority
