### ISSUE TITLE
Metaplex loads HUNDREDS of megabytes of data & crashes browser

### ISSUE THREAD

**Issue by israelidanny** [metaplex-foundation/metaplex#328]
<img width="1440" alt="Screen Shot 2021-09-07 at 15 53 48" src="https://user-images.githubusercontent.com/1970424/132347986-50b7e9df-607a-4318-af41-4a4c84a72730.png">

The only thing I did was pull master and add a 4th creator. It seems that I can no longer reach a loadable state for the Metaplex store. It's loading literally hundreds of MB from the blockchain and eventually just eats up all my available RAM and crashes the tab.

IF by some miracle it doesn't crash, the store displays correctly.

But this is absolutely insane. What is it downloading?

**Comment by uaktags** [comment]
did you click on it and view the response to see what its returning?

**Comment by israelidanny** [comment]
Not without the browser crashing😁 I'll need to setup a proxy debugger and fetch the contents there

**Comment by uaktags** [comment]
Gotcha, yea i dind't think about how it'd feel about trying to load it.

**Comment by BrokenSkullzNFT** [comment]
I thought so when I load the site, my computers fan goes into hyper drive.

**Comment by israelidanny** [comment]
Here's the request that gets the huge payload back.
<img width="811" alt="Screen Shot 2021-09-07 at 20 42 30" src="https://user-images.githubusercontent.com/1970424/132387985-7a5f24ab-85c0-405a-b310-04799113f600.png">

**Comment by israelidanny** [comment]
If I'm understanding this code correctly:
https://github.com/metaplex-foundation/metaplex/blob/9d5a5c6d668cd9c597cff8c63dfba00dee2f72f0/js/packages/web/src/contexts/meta/loadAccounts.ts#L152

At some point, the code thinks "Hey, it seems like you have more than 3 creators going on, so let's just, umm, load up the whole entire universe, how about that?" and loads all the storefronts, ever... Am I right?

This seems to be connected to:
https://github.com/metaplex-foundation/metaplex/issues/327

At this point I'm reverse engineering intent, so it'd be nice to hear about this constraint from the team & document it somewhere.

**Comment by shadow111** [comment]
Actually the problem is that the mataplex programId: `metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ` owns around `587973` accounts which it takes around `82.445 seconds` to fetch ( directly from solana)
here is my  code snippet : 
```
import {
  AccountInfo,
  clusterApiUrl,
  Connection,
  Keypair,
  PublicKey,
} from "@solana/web3.js";
async function getAccounts() {
  const connection = new Connection(clusterApiUrl("mainnet-beta"), "confirmed");
  await connection.getProgramAccounts(
    new PublicKey("HTjU33PoAtxJFxiWg47fdpJ7BEC6U8aHfHWXcS5kcQ9Y"),
    {commitment: "finalized"}
  ).then((account) => console.log(account));
}
```

**Comment by israelidanny** [comment]
@shadow111 yup that's exactly what I'm saying. What I don't understand though is the rationale for dropping the filters in the code if the store has more than 3 creators .

**Comment by uaktags** [comment]
I'd say to just remove that else condition. I'd rather have a blank store because there's 0 whitelisted creators, than waiting more than 2seconds for something I don't care about to load.

**Comment by israelidanny** [comment]
@uaktags I'm working on a PR with a much better solution. Will circle back most likely today.

**Comment by israelidanny** [comment]
So the issue appears to be that Metaplex smart contracts are highly normalized (not necessarily a bad thing, as Solana doesn't really have 'Transaction Batching' as a concept, so maintaining denormalized data would be extremely difficult).

Loading everything in such a normalized structure would take hundreds of RPC calls, which would run into most rate limits very quickly for a decently large store.

However, the compromise here of loading ALL the Metaplex, Vault, Auction e.t.c accounts (and all Meta accounts if store has more than 3 creators) is simply non realistic, especially with the growth the ecosystem is experiencing.

At this point the moment you pass 3 creators in the marketplace - you start downloading hundreds of MB.

These are the obvious few options:
1. Denormalize the data on-chain. This isn't really a great option because it would make updates much less reliable (no batching/transactions) but it would make reading off the blockchain a much better experience.
2. Introduce a GraphQL cache server layer. Why GraphQL? Because the highly nested and normalized data model here would work great with resolvers and caching resolver outputs by PublicKey would be fairly trivial.

Regardless of the solution, there are a few things that must be done to help people understand the current limitations of this frontend:
* Document the tradeoffs (normalization, RPC call limits)
* Document the obvious limits of usefulness of this particular frontend at its' current state (no more than 3 creators)
* Document what IS_BIG_STORE is (it directly relates to this whole issue)

**Comment by lilesper** [comment]
added a 4th creator RIP my metaplex instance

**Comment by lilesper** [comment]
bumped that const MAX_CREATORS to 10 and changed the hardcoded 3 creator limit to get around this/
should we be deploying our own version of the metaplex program to prevent this slowness?

**Comment by lilesper** [comment]
couldn't we use the getTokenAccountsByOwner from the list of creators method instead of getAllProgram accounts when hydrating the state of the app? and then only grab existing auctions from those mint addresses???
current approach is mad inefficient.... there must be a better way

**Comment by Merrick17** [comment]
@israelidanny if i deploy to K8s Cluster with Loadbalancer will it make it a little bit faster ?!

**Comment by israelidanny** [comment]
@Merrick17 this isn't something K8s will help with. The team has something in the works from what I understand to address this specific woe. I don't wanna announce anything before them so keep posted.

**Comment by myyellowshoe** [comment]
@israelidanny i've thought the same thing looking at this. Graphql/Apollo instance would be perfect for this.

Ugh and my basically empty metaplex instance takes 40 seconds to fully load. How is this ok lol.

**Comment by lilesper** [comment]
@myyellowshoe graphql on getprogramaccounts would slap

**Comment by myyellowshoe** [comment]
@lilesper 
I'd agree there. If i do anything on the graphql front i'll be sure to drop a pr. Just trying to better understand the archtecture/calls so far.

It looks like someone is already moving in that direction as well. https://github.com/metaplex-foundation/metaplex/pull/331

@israelidanny Would we be spinning our wheels here if there are some updates coming to address the speed issues?
