### ISSUE TITLE
Unhandled Runtime Error  TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by ahl1395** [metaplex-foundation/metaplex#335]
Hi, I'm getting this error when I try to mint on Metaplex and get to the "Your creation is being uploaded to the decentralized web...
This can take up to 1 minute." screen.

I've installed the latest build and have followed the instructions of putting my store key address and owner address in my web/.env 

Do you guys know what the problem might be? 

Thanks.

**Comment by lenyz** [comment]
Same problem here

**Comment by ahl1395** [comment]
Was fixed somehow for some reason. Works now, though I didn't do anything.
