### ISSUE TITLE
Candy machine CONFIG_LINE_SIZE definition

### ISSUE THREAD

**Issue by alikopasa** [metaplex-foundation/metaplex#338]
Hello,

Why we are adding **200** here? what is the definition of 200?

`export const CONFIG_LINE_SIZE = 4 + 32 + 4 + 200;`

Thank you very much, for your answers.

**Comment by uaktags** [comment]
Can you list where this is coming from?

**Comment by alikopasa** [comment]
https://github.com/metaplex-foundation/metaplex/blob/4a1b7d2f674013bc8bd3149294c66b03b27120d0/js/packages/cli/src/helpers/constants.ts
