### ISSUE TITLE
I dont see a Create or sell button after connectiong my wallet on the homepage

### ISSUE THREAD

**Issue by frutasdelsol** [metaplex-foundation/metaplex#342]
Hi there,

everything is working great except that after connecting my wallet on my forked metaplex website, there s no create or sell button?
I did the .env.

frutasdelsol.org

Thanks a lot,

**Comment by BrokenSkullzNFT** [comment]
#324

**Comment by frutasdelsol** [comment]
Thanks. 

Workaround for me: open the metaplex webpage with a private firefox window - dont know why but that worked.

**Comment by TheAli711** [comment]
@frutasdelsol The phantom extension cannot be used in private/incognito mode. Only the init store button comes when I connect to testnet (of the phantom wallet).
