### ISSUE TITLE
Issue with CLI Arweave uploads

### ISSUE THREAD

**Issue by drbh** [metaplex-foundation/metaplex#344]
`https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile4` is not working as expected.

I'm attempting to upload a manifest that looks like 
```json
{
  "name": "Another One!",
  "symbol": "ANO",
  "description": "This is another one",
  "seller_fee_basis_points": 500,
  "image": "image.png",
  "external_url": "",
  "properties": {
    "files": [{ "uri": "image.png", "type": "image/png" }],
    "category": "image",
    "creators": [
      {
        "address": "4HNFNynsnjA1niRihv5hcq8qUFhyx8T1K3a4eFFoBK6G",
        "share": 100
      }
    ]
  }
}
```

and the `upload` function seems to handle the image file correctly (adding the arweave url to the manifest JSON blob). However, it seems to cut off the first `{` when storing the manifest on arweave.

The file stored looks like 
```json
  "name": "Another One!",
  "symbol": "ANO",
  "description": "This is another one",
  "seller_fee_basis_points": 500,
  "image": "https://www.arweave.net/m5L7eMjxGjOvOKNkWAsQDvXq8SstPrPWn5e8ECPG5xg?ext=png",
  "external_url": "",
  "properties": {
    "files": [
      {
        "uri": "https://www.arweave.net/m5L7eMjxGjOvOKNkWAsQDvXq8SstPrPWn5e8ECPG5xg?ext=png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "4HNFNynsnjA1niRihv5hcq8qUFhyx8T1K3a4eFFoBK6G",
        "share": 100
      }
    ]
  }
}
```
**Notice the missing opening curly bracket**

and is available at https://3tq57e6f52znghuofhguq6imzc7lsdawmodvkp7sqrbmz2yjm7bq.arweave.net/3OHfk8XustMejinNSHkMyL65DBZjh1U_8oRCzOsJZ8M

also the image file does not load...

Is the source code for the functions available to view? Is there a way I can fix the JSON blob? Any insight is super helpful. Thanks! 🙏

**Comment by drbh** [comment]
@bartosz-lipinski tagging you since this seems similar to this closed issue: https://github.com/metaplex-foundation/metaplex/issues/318 

Thanks in advance 🙂

**Comment by drbh** [comment]
@bhgames any insight here? Thanks!

**Comment by drbh** [comment]
This seems to be related https://github.com/metaplex-foundation/metaplex/issues/357

**Comment by bhgames** [comment]
That's super weird. I don't have much experience with this upload function, @bartosz-lipinski is the guy
