### ISSUE TITLE
metaplex cli upload

### ISSUE THREAD

**Issue by Vitu02** [metaplex-foundation/metaplex#346]
Hi I had this error when upload assets:

![image](https://user-images.githubusercontent.com/72853691/132670281-8cff1512-9e1c-453c-8cb4-eccf5998f833.png)

**Comment by joaoh82** [comment]
running into same issue.

**Comment by samuelvanderwaal** [comment]
Recommended to use Typescript with ts-node to run the CLI:

`ts-node /path/to/src/candy_machine_cli.ts upload`

Also, this shouldn't be the issue but `testnet` is typically for testing new Solana releases while `devnet` is recommended for developers to experiment with. See this for more info: https://docs.solana.com/clusters.
