### ISSUE TITLE
Missing option to build binary

### ISSUE THREAD

**Issue by wandrzejczak** [metaplex-foundation/metaplex#348]
I've been trying to build the megaplex binary on Ubuntu.
Unfortunately, I got an error when I run `yarn package:linux`
`--no-bytecode and no source brakes final executable`

I've found a solution:
https://github.com/vercel/pkg/pull/1140

by adding "--public-packages=*" to the package.json solve the problem.

**Comment by jordansexton** [comment]
@wandrzejczak can you confirm if @drbh's PR fixed your issue?

**Comment by samuelvanderwaal** [comment]
Closing due to no response. Re-open if the issue is still present.
