### ISSUE TITLE
Publish recent version of spl-token-metadata to Crates (0.0.1 is not functional)

### ISSUE THREAD

**Issue by dvcrn** [metaplex-foundation/metaplex#349]
The current version 0.0.1 of `spl-token-metadata` is not usable from within Rust due to a bug in `create_metadata_accounts` that marks `writable` accounts as `readonly`. This has since been fixed. 

Can we get a more recent version up on cargo?

**Comment by acamill** [comment]
Any update on this

**Comment by dvcrn** [comment]
Okay I see, that is currently not clear at all. Maybe metaplex should consider publishing an official crate in that case and point users to that instead, or see if the published one can be taken over 💭

**Comment by samuelvanderwaal** [comment]
`metaplex-token-metadata` is now available on crates.io: https://crates.io/crates/metaplex-token-metadata
