### ISSUE TITLE
Long Load Times api.devnet.solana.com

### ISSUE THREAD

**Issue by themaxjames77** [metaplex-foundation/metaplex#352]
api.devnet.solana.com 2.8 min to load. Entire site takes up to 8.4 Min to load

![Screen Shot 2021-09-09 at 2 36 22 PM](https://user-images.githubusercontent.com/36860841/132743665-793fae56-92f9-4f2f-9d6a-81e7c8899310.jpg)
![Screen Shot 2021-09-09 at 2 33 50 PM](https://user-images.githubusercontent.com/36860841/132743671-2b1c8173-21dc-4a68-beb4-0146b47fcc5b.jpg)

**Comment by whiteyhat** [comment]
Same here...

**Comment by samuelvanderwaal** [comment]
Public APIs are aggressively rate-limited due to the abuse they receive but also the storefront has known speed issues which are being actively worked on.
