### ISSUE TITLE
Notifications Broken

### ISSUE THREAD

**Issue by themaxjames77** [metaplex-foundation/metaplex#353]
I believe this is due to the long load times but after waiting more than 10 min I have not received a notification to settle the auction that had completed. Going to /billing after the auction url gets me to where I need to go but there used to be a notification the populated.

**Comment by jordansexton** [comment]
Thanks for the report @themaxjames77. Can you provide steps to reproduce this issue?

**Comment by samuelvanderwaal** [comment]
Closing due to no response.
