### ISSUE TITLE
PNG upload has content-length of 0

### ISSUE THREAD

**Issue by mistermann87** [metaplex-foundation/metaplex#357]
There seems to be a problem with uploading pngs through the upload cli script.
The attached file is created on a windows machine (in this case with photoshop).
![0](https://user-images.githubusercontent.com/1434986/132850445-1364da58-d0c6-4764-840b-ea94a0585d82.png)

I testet uploading this file directly to arweave with "arweave deploy" which works as expected.
When I use the file with the metaplex cli uploader I get the following output:
https://3dc4bsyzlmfovxh2vc6fpv7ebzs7aqk3rnpcwtwh7m2lt7ac27fa.arweave.net/2MXAyxlbCurc-qi8V9fkDmXwQVuLXitOx_s0ufwC18o/
`{"name":"Test NFT #1","symbol":"TST","description":"Testcription","seller_fee_basis_points":420,"image":"https://www.arweave.net/fD63aNZxxE6Y2K9bTBrr6YIBU4vjE4B1sdats59hdrA?ext=png","attributes":[{"trait_type":"Background","value":"Purple"},{"trait_type":"Base","value":"Blue"},{"trait_type":"Eyes","value":"Sunglasses"},{"trait_type":"Mouth","value":"Line"},{"trait_type":"Accessory","value":"Cigarette"},{"trait_type":"Head","value":"Bucket"}],"collection":{"name":"Test NFT Coll","family":"Testfamily"},"properties":{"files":[],"category":"image","creators":[{"address":"FPjFimhB5eU25esrxh9RhrcJWD6E927GbF4HumnuTe8q","share":100}]}}`

Here is the linked image, which has a content-length of 0
https://pq7lo2gwohce5ggyv5nuygxl5gbacu4l4mjya5nr22w3hh3bo2ya.arweave.net/fD63aNZxxE6Y2K9bTBrr6YIBU4vjE4B1sdats59hdrA

I logged the file size locally before it is added to FormData and the file has a size (so the file has the correct path).
So I think, something is broken in the upload script at 'https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile4' 

One interesting fact: I downloaded another image, that already lived on arweave and uploaded that through the script, than it worked. If I save this file again (e.g with Photoshop on a windows system) that it is not working again. 

Hope you can help. Thanks in advance!

Edit: Small image sizes seem to lead to the problem (see my comment below and the link to the discussion in the discord channel). After some playing around they noticed that images with ~16kB and below are not properly uploaded to arweave. Images with a bigger size ar uploaded correctly.

**Comment by mistermann87** [comment]
@bartosz-lipinski Can you help please?

**Comment by mistermann87** [comment]
In the discord dev chat there is a supposition, that the problem may be small image sizes:
https://discord.com/channels/848060988636921856/849844496941842432/885618365664727060

**Comment by penneydude** [comment]
I've seen this issue as well with an image 14k in size. Larger than 25k seem to work fine

**Comment by trust0212** [comment]
I have same issue.

**Comment by 0xsolsurfer** [comment]
Had the same issue, I upscaled my images so that they are > 25 kb and it's working. Not sure what's going on.

**Comment by samuelvanderwaal** [comment]
Images below about 20kB are not currently supported.
