### ISSUE TITLE
After successfully uploading an asset using metaplex it fails to find the cache file

### ISSUE THREAD

**Issue by Hossman333** [metaplex-foundation/metaplex#361]
After it successfully uploads and initializes with candy machine it then has issues doing anything else on the mainnet. (for example I ran metaplex verify and then it spits out that error down below. Same with minting. Everything works on devnet for me though)

I've seen multiple people in the metaplex discord channel say they ran into this as well. Not exactly sure what the problem is, but it seems to be with the temp cache file being loaded up incorrectly or something.

```
(node:38645) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'program' of undefined
    at /snapshot/js/packages/cli/build/cli.js:423:63
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.next (/snapshot/js/packages/cli/build/cli.js:45:53)
    at fulfilled (/snapshot/js/packages/cli/build/cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by alejandrade** [comment]
works for me. what is the order you are trying to run the methods?

**Comment by Hossman333** [comment]
Interesting! I wonder why it's breaking for me then. After double checking I'm on the correct config I simply run 

```
metaplex upload . --env mainnet-beta --keypair ~/.config/solana/id.json
```

And then it does that whole thing successfully and then I try and run `metaplex verify --keypair ~/.config/solana/id.json` afterwards for example and it breaks!

Same goes for trying to mint the freshly uploaded asset.

**Comment by Hossman333** [comment]
I'm on the latest commit too.

**Comment by alejandrade** [comment]
run it in this order
```
metaplex upload . --env mainnet-beta --keypair ~/.config/solana/id.json
metaplex create_candy_machine. --keypair ~/.config/solana/id.json
metaplex set_start_date. --keypair ~/.config/solana/id.json

**Comment by Hossman333** [comment]
Hello! Thanks for the suggestion. Still didn't work, weird.....

![image](https://user-images.githubusercontent.com/2993997/132898104-b1b36be8-b4ec-4c4f-9cfd-f9c6d4c2f78c.png)

**Comment by Hossman333** [comment]
My metadata(`0.json`) file does indeed have the same address under the creators field that `solana address` produces. Thought maybe i'd double check that, but yeah they're the same.

**Comment by alejandrade** [comment]
I always put assets in a different directory. idk if that makes a difference. 
``` rm -rf .cache/
metaplex upload ./assets -e "devnet" -k /home/sephto/solana-wallet/candy-machine-test.json
metaplex create_candy_machine -k "/home/sephto/solana-wallet/candy-machine-test.json" -p 2
metaplex set_start_date -k "/home/sephto/solana-wallet/candy-machine-test.json"

```

**Comment by Hossman333** [comment]
Have you only been testing on `devnet`? I think that is the biggest difference. I'm trying to upload to mainnet. devnet works for me. Is there something special I have to do to get it on mainnet?

BTW, thanks for responding and helping me out. I can try a new directory to see if that helps

**Comment by Hossman333** [comment]
R.I.P same issue with a directory. @alejandrade you're costing me a pretty penny 😝 Nah, i'm just playing. Just a few USD dollars haha.

**Comment by uaktags** [comment]
@Hossman333 
within your directory "blah" is that where .cache lives?

also, i note that you ran
``metaplex upload . --env mainnet-beta --keypair ~/.config/solana/id.json``
but you did not pass the --env for verify. Try that please.

**Comment by Hossman333** [comment]
Wow! That was it! I just simply didn't pass the env to it! 🤦🏻‍♂️ Wow, I was confused by that haha. Thank you @uaktags !!!

**Comment by uaktags** [comment]
You're welcome.

For reference guys, as of current commit 4a1b7d2 
by default --env is set to devnet, --cache-name is set to temp, and metaplex cli looks in the directory you're currently running the command from ``./`` for .cache directory. This directory will hold a temporary json file that will be named the value of --env with the value of --cache-name. so if you don't do anything for --env or --cache-name, it will look in .cache/ for a file called "devnet-temp". 

If you upload on --env mainnet-beta or testnet, then this file will be "mainnet-beta-temp" or "testnet-temp". 

So use the arguments throughout your process.
