### ISSUE TITLE
Error deploying config to Solana network Non-base58 Character

### ISSUE THREAD

**Issue by furiah1** [metaplex-foundation/metaplex#372]
Trying to run metaplex upload for personal NFT project for university.

PS C:\users\ryan\desktop\nft\testgg> metaplex upload . --keypair /users/ryan/.config/solana/id.json -n 1

Processing file: 0
initializing config
Error deploying config to Solana network. Error: Non-base58 character
    at Object.decode (C:\Users\Ryan\IdeaProjects\metaplex\js\packages\cli\node_modules\base-x\src\index.js:115:11)
    at new PublicKey (C:\Users\Ryan\IdeaProjects\metaplex\js\packages\cli\node_modules\@solana\web3.js\lib\index.cjs.js:135:50)
    at C:\Users\Ryan\IdeaProjects\metaplex\js\packages\cli\build\cli.js:210:42
    at Array.map (<anonymous>)
    at C:\Users\Ryan\IdeaProjects\metaplex\js\packages\cli\build\cli.js:208:64
    at step (C:\Users\Ryan\IdeaProjects\metaplex\js\packages\cli\build\cli.js:64:23)
    at Object.next (C:\Users\Ryan\IdeaProjects\metaplex\js\packages\cli\build\cli.js:45:53)
    at fulfilled (C:\Users\Ryan\IdeaProjects\metaplex\js\packages\cli\build\cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Started awaiting confirmation for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
REST null result for iJCjt4dr1mKJkDJBvCTgKTZwAFcpsGb3yL7W77UYh3zhwFsiaHCKyyhQjwkusFGUEFbC5EgEtosqQJtoHqNSUgm null
Rejecting for timeout...

**Comment by trust0212** [comment]
Did you fill address field of your json file?

**Comment by furiah1** [comment]
Hi @trust0212 

You were correct, I had left the template address field in my json file, thank you.

When running metaplex upload, I now appear to be in a neverending loop 
`Done, Successful = False
upload not successful. rerunning`

Is this because I am on the devnet?
