### ISSUE TITLE
Cannot send NFT minted with metaplex candy machine to another wallet

### ISSUE THREAD

**Issue by soualid** [metaplex-foundation/metaplex#374]
Hello,

I used the CLI tools provided by metaplex to upload NFT, then created a candy machine and used it to mint some NFTs to a devnet account.

Everything worked well, but when I am trying to send the resulting collectible to another wallet, it fails with the following error (using both Phantom and Sollet.io "send" feature).

```
failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
```

Is it a known issue?

**Comment by soualid** [comment]
Well, it just worked with solflare wallet but maybe something to dig with Phantom and Sollet.io both failing with the same error message.

Feel free to close this issue if it's not relevant.

**Comment by pwgreco** [comment]
Running into this same issue. Any advice? Seems like I've configured everything correctly.

**Comment by pwgreco** [comment]
So just to update my reply. This appears to be an issue with Phantom only on devnet. Should work fine with Solflare and Sollet!

**Comment by quarterpound** [comment]
did you manage to test this on mainnet?

**Comment by soualid** [comment]
Not yet sorry!

**Comment by saraspaudel** [comment]
I am facing the same issue. I can't send NFT to another wallet either. When I load my mnemonic into Solflare the NFT doesn't show up. It shows on Phantom.

**Comment by quarterpound** [comment]
Seems to be a Phantom dev net issue
