### ISSUE TITLE
Metaplex store infinitely loads on init

### ISSUE THREAD

**Issue by rohanm19** [metaplex-foundation/metaplex#380]
Hi,

My metaplex store keeps on loading infinitely and the console has the below error:
719.764b52bed528109a7f8b.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'owner')
    at Ei (719.764b52bed528109a7f8b.js:1)
    at Mi (719.764b52bed528109a7f8b.js:1)
    at 719.764b52bed528109a7f8b.js:1
    at l (main-c368593b47f801644b2b.js:1)
    at Generator._invoke (main-c368593b47f801644b2b.js:1)
    at Generator.next (main-c368593b47f801644b2b.js:1)
    at r (704.1d497b90862d3bea3173.js:1)
    at c (704.1d497b90862d3bea3173.js:1)

**Comment by rohanm19** [comment]
Just to add, the error comes from this line:


const isMetadataAccount = (account: AccountInfo<Buffer>) => {
  return (account.owner as unknown as any) === METADATA_PROGRAM_ID;
};

TypeError: Cannot read properties of undefined (reading 'owner')

I have only provided the REACT_APP_STORE_OWNER_ADDRESS_ADDRESS (my wallet address) in the .env file. (.env.production is empty)

**Comment by nQuery512** [comment]
Same error here,

Is it related to the network overload ?

**Comment by hmltheskeptic** [comment]
same error. it doesnt stop loading. I can only connect the wallet but cant do anything else
