### ISSUE TITLE
Feature request: URI and name templates

### ISSUE THREAD

**Issue by soualid** [metaplex-foundation/metaplex#382]
Hello,

For large collections of collectible (10K or more), instead of storing each single configuration on-chain, it would be great to have a way to set the URI and names as template using the index of the token in the candy machine.

A possible implementation could be a `is_templated_metadata` in `ConfigData` that triggers a  computed version of `get_config_line` instead of the one stored on chain.

ie, `is_templated_metadata = true` and this single configuration line is stored in the configuration array:

```
{
  "name": "My dope NFT #{i}", 
  "uri: "https://some-server.com/metadatas/{i}.json"
}
```

This single configuration line could then be used in `get_config_line` to derive the proper configuration line from the template using the `index` parameter.

Implementing this would save a lot of storage for a typical use case in the NFT world, which is large collections of collectible. Actually, the NFT candy machine is barely usable in these use cases because storing 10K metadatas on chain would cost ~2000USD.

Thanks for reading!

**Comment by soualid** [comment]
I implemented this approach locally and tested it on devnet (ie. sample [token #4](https://explorer.solana.com/address/8JndBAPe8E91ACVcafzeKcPFBXtq1KQtXBFJCGGZgh2t?cluster=devnet) and sample [token #20](https://explorer.solana.com/address/BVYCTbDJWoa5eAtmeJwmUWRuWQUTVmQWUSbND5qg2N2S?cluster=devnet)), I'll try to clean up the rust implementation a bit, and finalize the implementation of the required options on the CLI tool before submitting a PR for early feedbacks.

**Comment by samuelvanderwaal** [comment]
The storage cost concern should be solved by the [withdraw function](https://docs.metaplex.com/create-candy/withdraw). The PR was closed due to inactivity so I am closing this issue as well.
