### ISSUE TITLE
Why forbid smaller number than files in folder - upload function

### ISSUE THREAD

**Issue by uaktags** [metaplex-foundation/metaplex#387]
https://github.com/metaplex-foundation/metaplex/blob/76de057a0ce0c436f42cdd1027fef1469daf4bb2/js/packages/cli/src/cli.ts#L52
```
    if (parsedNumber < pngFileCount) {
      throw new Error(`max number (${parsedNumber})cannot be smaller than the number of elements in the source folder (${pngFileCount})`);
    }
```
parsedNumber is the number we pass via -n (--number) which is quoted to say "Number of images to upload". So it seems logical that parsedNumber should either be == or <= that of pngFileCount (the number of png Files in the asset folder)

**Comment by trust0212** [comment]
I think so
