### ISSUE TITLE
Mainnet Metaplex Upload error

### ISSUE THREAD

**Issue by SolPandas** [metaplex-foundation/metaplex#394]
Running the metaplex upload command returns the error:
metaplex-master\js\packages\cli>metaplex upload ./pandaAssets -k ~/solWalletOfficial/keypairImportant.json --url https://api.mainnet-beta.solana.com --env mainnet-beta
Processing file: 50
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.

Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Connection.sendEncodedTransaction (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:6649:21)
    at async Provider.send (C:\snapshot\js\node_modules\@project-serum\anchor\dist\cjs\provider.js:84:22)
    at async Object.rpc [as initializeConfig] (C:\snapshot\js\node_modules\@project-serum\anchor\dist\cjs\program\namespace\rpc.js:11:31) {
  logs: []
}
Error deploying config to Solana network. SendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
    at Connection.sendEncodedTransaction (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (C:\snapshot\js\node_modules\@solana\web3.js\lib\index.cjs.js:6649:21)
    at async Provider.send (C:\snapshot\js\node_modules\@project-serum\anchor\dist\cjs\provider.js:84:22)
    at async Object.rpc [as initializeConfig] (C:\snapshot\js\node_modules\@project-serum\anchor\dist\cjs\program\namespace\rpc.js:11:31) {
  logs: []
}
Started awaiting confirmation for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
REST null result for nA24jDDEgoFgmfQ6K7atiJM8KV5uhpJQCXC5ESBmaXAfgE4oo2onPcHg7BCePqR7r8WnCYKvNQSy9rWMqcK7aGJ null
Rejecting for timeout...
Timeout Error caught { timeout: true }
(node:12424) UnhandledPromiseRejectionWarning: Error: Timed out awaiting confirmation on transaction
    at C:\snapshot\js\packages\cli\build\helper.js:173:31
    at step (C:\snapshot\js\packages\cli\build\helper.js:41:23)
    at Object.throw (C:\snapshot\js\packages\cli\build\helper.js:22:53)
    at rejected (C:\snapshot\js\packages\cli\build\helper.js:14:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:12424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Have checked solana config get:
Config File: REDACTED\.config\solana\cli\config.yml
RPC URL: https://api.mainnet-beta.solana.com
WebSocket URL: wss://api.mainnet-beta.solana.com/ (computed)
Keypair Path: ~/solWalletOfficial/keypairIMPORTANT.json
Commitment: confirmed

And balance is at 2.5 SOL (uploading 20 file pairs)

The files have been tested on devnet successfully all the way through minting and viewing in phantom wallet

**Comment by thecookingsenpai** [comment]
Same issue here, tried on commit of 6 Sept too

**Comment by wandrzejczak** [comment]
You have written in the error log:
"Transaction simulation failed: Attempt to debit an account but found no record of a prior credit."

Your Solana account does not have any funds ($$).

**Comment by richardj97** [comment]
I get this error too, even though I have 2.9 SOL in my mainnet balance -.-

**Comment by adrzadrz** [comment]
getting this same error now, balance still has a lot of SOL.

**Comment by richardj97** [comment]
Its weird isn't it lol. I was getting that error about the not having enough SOL and then i changed my wallet and now mine is timing out after 60 seconds and not uploading anything lol, can't win -.-

**Comment by adrzadrz** [comment]
Then when running `metaplex verify` I'm getting errors for every single entries
`Name  or uri  didnt match cache values of [redacted]#2701 and https://arweave.net/[redacted] marking to rerun for image 2701`

**Comment by richardj97** [comment]
At least yours is uploading lol mine is not uploading a single one and says: Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed.

**Comment by SolPandas** [comment]
My solana account has 4.01 SOL currently (verified by solana balance, solana config get also returns the same keypair path)

**Comment by richardj97** [comment]
Yeah I don't think mainnet-beta is working atm because its down. They have disabled all calls to the mainnet I believe

**Comment by SolPandas** [comment]
The mainnet was functional at the time of original post yesterday (aside from trying to use the metaplex upload command)

**Comment by SolPandas** [comment]
Resolved as of latest commit + mainnet back online

**Comment by jia-ayo** [comment]
[2/4] Initializing upload
▪▪▪▪▪ Connected

[3/4] Uploading image files 

Sending data: (Ctrl+C to abort)

Error running command (re-run needed): Failed to get config item at index '06'
what might cause this error

**Comment by Flaming19** [comment]
Can I mint 1 NFT few time(20 times) on Solana sugar?
