### ISSUE TITLE
Error: Transaction was not confirmed in 60.01 seconds.

### ISSUE THREAD

**Issue by richardj97** [metaplex-foundation/metaplex#400]
I'm receiving the error: 'Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed' when trying to upload via the mainnet-beta, here's the command:

> metaplex upload src/nft --env mainnet-beta --keypair ~/.config/solana/mainnet.json

It just keeps timing out.

> solana config get
> Config File: C:\Users\###\.config\solana\cli\config.yml
> RPC URL: https://api.mainnet-beta.solana.com
> WebSocket URL: wss://api.mainnet-beta.solana.com/ (computed)
> Keypair Path: ~/.config/solana/mainnet.json
> Commitment: confirmed

Edit: devnet works fine!

**Comment by ja-leo** [comment]
same error here, is it related with the Solana network issue in the last two days?
