### ISSUE TITLE
Service unavailable error in upload after transfering payment

### ISSUE THREAD

**Issue by thmlemke** [metaplex-foundation/metaplex#403]
Candy Machine approves and transfers funds before verifying that the upload service is capable of uploading.

Hi, so I spent north of 10 sol on uploading 6174 NFTs with metadata and the WS returning 503 errors from the get-go.
Would it be an idea to open source this black box WS so we can develop a or expose a method to check if it's available before paying lump sums into the ether?

**Comment by cdric** [comment]
Yeah I am experiencing the same issue on the devnet. You pay the transaction first and then you cross your finger that your asset will be uploaded. Worse... if the upload fails, the program retries and take the fee again...

And from your experience, it seems that the logic is pretty similar on maindev. Seems terrible to have to spend that much SOL for invalid images. I've noticed that people are opening PR to allow the ability to use a different provider to store your image which would be great and would also speedup the upload process a lot!

**Comment by samuelvanderwaal** [comment]
The `withdraw` method allows you to reclaim SOL from config accounts and the Google Cloud function will be deprecated at some point in the near future. 

https://docs.metaplex.com/create-candy/withdraw
