### ISSUE TITLE
Where can i find hash table?!

### ISSUE THREAD

**Issue by marsupilak** [metaplex-foundation/metaplex#404]
Guys im just an artist that dont really know whats going on with the codes etc. i manage to create my metaplex store but in order to verify my work i need to present my hash table. I guess its somewhere in the code but couldnt find where.
I would be appreciated if you guys just tell me where the hell is my hash table (or hash list i donno) supposed to be.

Thanx in advance :)

**Comment by mistermann87** [comment]
+1 for this issue. How is it possible to retrieve a hash table of all mints in a candy machine? 
I already scanned the explorer, but am not able to find the relevant information. Thanks!

**Comment by mistermann87** [comment]
I found a way to achive this. I try to create a pull request for that this week.

**Comment by Taheerj** [comment]
> I found a way to achive this. I try to create a pull request for that this week.

Can you at least share the method you found? I'm also trying to find a way to do this.

**Comment by mistermann87** [comment]
My current (not final) local solution is adding these lines at `js/packages/cli/src/commands/signAll.ts:96`:
`
  const mintHashes = [];
  metadataByCandyMachine.forEach(meta => {
      mintHashes.push(new PublicKey(meta[0].mint).toBase58());
  });
  saveCache('mints', env, mintHashes.join(os.EOL));
`

for that to work, env needs to be passed through to `signAllMetadataFromCandyMachine`

Afterwards there is a file .cache/devnet-mints which holds the hashes

**Comment by gbolame** [comment]
What address should I paste on the website I made use of my wallet address the pdf us blank

**Comment by mistermann87** [comment]
Account of candy machine

**Comment by gbolame** [comment]
i made use of my candy machine public key the array is still blank 
this is my candy machine public key 

5By1baVLbDrx7SpiFyPjC3hzSVop6Z6ryynucJHyLgK8

**Comment by gbolame** [comment]
I also tried the other method stated above after adding the code i got this error  --cndy can't be found

**Comment by gbolame** [comment]
@mistermann87 help

**Comment by mistermann87** [comment]
You really used candy machine id and not config by accident? And you should not set the checkbox (even if one should expect that).

I also got it working with this here:
https://github.com/samuelvanderwaal/metaboss

**Comment by gbolame** [comment]
i did all that i also made use of the metaboss it seems i can't get the hashes for my upcoming nft until i sell out. @mistermann87

**Comment by gbolame** [comment]
can this be because i made use of the older version of metaplex and candy machine
