### ISSUE TITLE
Small filesizes don't show up on Arweave

### ISSUE THREAD

**Issue by TheGemCreator** [metaplex-foundation/metaplex#412]
This has been a commonly cited issue in the Metaplex Discord.
It's not 100% predictable, as the exact minimum size hasn't been tracked down.
But a common guess is currently ~20KB.
To reproduce the error reliably, just use a very small <5kb PNG image.

This is probably being caused by the closed-source `uploadFile4` cloud function.

**Comment by meany** [comment]
wow I've wasted a few hours trying to figure out why my assets weren't being displayed and it's because I was using some test PNGs which were under 20Kb. After increasing the size it worked.

**Comment by venables** [comment]
Also have hit this issue frequently.   Upload seems to succeed with `uploadFile4` but the image 404s when accessing the URL on arweave.  Pre-paying for the storage is cheap but unfortunate that this fails. 

I'd be happy to try to put up a fix if `uploadFile4` gets open sourced!

**Comment by samuelvanderwaal** [comment]
The Google Cloud function will be deprecated in favor of using Bundlr's SOL native feature or direct Arweave uploads, and at that point file limitations will due to Arweave and not a Metaplex implementation.
