### ISSUE TITLE
incompatible with this module

### ISSUE THREAD

**Issue by ramakrishnaj** [metaplex-foundation/metaplex#419]
error cross-env@7.0.3: The engine "node" is incompatible with this module. Expected version ">=10.14". Got "6.17.1"

**Comment by ethanolivertroy** [comment]
I got.

@solana/web3.js@1.28.0: The engine "node" is incompatible with this module. Expected version ">=12.20.0". Got "12.16.3"

**Comment by acamill** [comment]
Same issue

**Comment by ramakrishnaj** [comment]
you need to update node version

**Comment by acamill** [comment]
Seems I need a downgrade Expected version "~14.17". Got "16.9.1". But I'm wondering why it's not using some local stuff instead
