### ISSUE TITLE
Not able to upload nft assets

### ISSUE THREAD

**Issue by alvaroartano** [metaplex-foundation/metaplex#426]
I get this error when trying to run the upload command

**Command I'm running:** `metaplex upload asset/ --env devnet --keypair keypair.json`

![image](https://user-images.githubusercontent.com/28715114/133823797-4f731ba3-7562-4524-acea-fa49e360ea63.png)

this is my json file
```json
{
  "name": "alvaro's test NFT",
  "symbol": "",
  "description": "Testing NFT",
  "seller_fee_basis_points": 0,
  "collection": {
     "name": "Test NFT collection",
     "family": "Test" 
  },
    "creators": [
      {
        "address": "therealaddygoeshere",
        "share": 100
      }
    ]
  }
```

Thanks!

**Comment by BurgercubeNFT** [comment]
Keypair directory should look like this --keypair ~/.config/solana/devnet.json

**Comment by alvaroartano** [comment]
> Keypair directory should look like this --keypair ~/.config/solana/devnet.json

it doesn't have any relation with that

**Comment by Eggathan** [comment]
Missing     "properties": {
        "files": [
            {
                "uri": "image.png",
                "type": "image/png"
            }
