### ISSUE TITLE
Metaplex upload loop 

### ISSUE THREAD

**Issue by sergitejada** [metaplex-foundation/metaplex#427]
When I try to create the nft I get an infinite loop

Error:
![image](https://user-images.githubusercontent.com/49126831/133867604-fbc0e369-92d8-4a12-baa7-7e5437e7777c.png)

Json:
![image](https://user-images.githubusercontent.com/49126831/133867579-6b2ebe41-847a-4b82-b437-9b9e5f4cb1c0.png)

Cache response :
`{"program":{"uuid":"4LmSXc","config":"4LmSXc7YdfTNxyDRpe1E5J1f25EBXTz8NTJLE7XPjMBy"},"items":{"0":{"link":"https://arweave.net/lt0h2E80WxfwPSVKA0nOENhuarw_irYCgd30Urbwv-A","name":"lightcycle #0","onChain":false}}}`

Link:
![image](https://user-images.githubusercontent.com/49126831/133867625-340974c2-c881-40c4-ac88-1a34ca2500e8.png)

**Comment by ojasuno** [comment]
yep, i have started to see the same error as well

**Comment by alvaroartano** [comment]
anyone solved?

**Comment by Joemalope** [comment]
Yes, I'm still having this issue

**Comment by Joemalope** [comment]
> report
Yes, I'm still having this issue

**Comment by stegaBOB** [comment]
Candy machine v1 has been deprecated. If you are still having the same issues with v2, please open a new issue. Thanks!
