### ISSUE TITLE
Any chance to have a port for Sveltekit ?

### ISSUE THREAD

**Issue by lgs** [metaplex-foundation/metaplex#437]
Metaplex project looks grate, but unfortunately React is not a a framework for me and my team to invest in. Is there any chance to have a port for [Sveltekit](https://kit.svelte.dev/)?

**Comment by jordansexton** [comment]
Closing this issue as a duplicate of your other issue: https://github.com/metaplex-foundation/metaplex/issues/23

Please don't open multiple issues for the same feature request. If you are interested in implementing this, a separate repo is the way to go.
