### ISSUE TITLE
spliting minting funds in 2 wallets

### ISSUE THREAD

**Issue by kpvy2002** [metaplex-foundation/metaplex#438]
is it possible to add 2 wallets on treasury to receive half mint amount in each wallets.

**Comment by strange1120** [comment]
@kpvy2002 yes just add another object under `creators` with the share percentage of `seller_fee_basis_points` . so say `seller_fee_basis_points` is 500 or 5%. in the creators array, for each object the amount for `share` would be 50. 

metaplex nft standards json sample doc here https://docs.metaplex.com/nft-standard

**Comment by kevinfaveri** [comment]
This is about the royalties @strange1120. But I think @kpvy2002 is speaking about the minting funds. When someone mints something, there is a mint price. So, how to split this minting value? Using the creator's key is not the way to do it since it only relates to when the NFT is sold.

**Comment by Ru5ty0ne** [comment]
I'm capable of solving this issue but I doubt that I'll ever find time to actually implement the solution since there is no monetary insantive to do this and time of anyone that can write smart-contracts valued very high on the market right now.

**Comment by soldevcm** [comment]
I'm also interested in using this. How much would you charge @Ru5ty0ne

**Comment by Ru5ty0ne** [comment]
@soldevcm if you want personalized contract DM me on discord Rusty 0ne#9756 or mail me(you can find it in my github profile). But I was talking about general solution for Metaplex foundation that can be deployed once and used by everyone. I will be interested in working on this kind of PR if one of mainteners allow me to include some arbitrary small flat fee for each treasury withdraw. Size of it can be chosen by the maintainer.

**Comment by jordansexton** [comment]
Closing as questions like this are better suited for Discord. Please ask there!
