### ISSUE TITLE
metaplex: command not found

### ISSUE THREAD

**Issue by AcoustiCoder** [metaplex-foundation/metaplex#443]
```
cd metaplex/js/packages/cli
metaplex help
metaplex: command not found
```

i cant reach metaplex. how can i fix this issue?

Edit: I am using windows and using Ubuntu

**Comment by strange1120** [comment]
@AcoustiCoder you need to build the cli with 

```
    yarn install
     yarn build 
     yarn run package:macos
```

then link the directory to your path 

more info here https://hackmd.io/@levicook/HJcDneEWF

**Comment by myungjunChae** [comment]
@strange1120 
I don't have executable file on path `"metaplex/js/packages/cli"`
Could you let me know, where the executable metaplex file is located.

**Comment by zarifaziz** [comment]
For anyone following levi cook's tutorial:
https://hackmd.io/@levicook/HJcDneEWF

`ts-node ~/src/metaplex/js/packages/cli/src/candy-machine-cli.ts upload` is basically used instead of `metaplex upload`

**Comment by AcoustiCoder** [comment]
> For anyone following levi cook's tutorial:
> https://hackmd.io/@levicook/HJcDneEWF
> 
> `ts-node ~/src/metaplex/js/packages/cli/src/candy-machine-cli.ts` is basically used instead of `metaplex`

Answer! Thank you so much
