### ISSUE TITLE
Error uploading file XXX FetchError: invalid json response body

### ISSUE THREAD

**Issue by SolarDustNFT** [metaplex-foundation/metaplex#454]
I'm trying to upload to the SOLAN main-net the collection and see a lot of errors such as
```
Error uploading file 3506 FetchError: invalid json response body at https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile4 reason: Unexpected token < in JSON at position 1
    at /mnt/sd/meta/metaplex/js/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
````
The same files with meta was successfully uploaded to dev-net. 
When I'm trying to upload by small parts 5-10 nft, it sometimes successfully sometimes not ...

Cannot understand if it SOLANA net issue (looks like) or maybe metaplex issue. Or maybe there is a possibility increase timeouts

**Comment by kefalet98** [comment]
exactly same issue over here seems like this do not creates a problem but still annoying to see same problem during a 10 hours process
