### ISSUE TITLE
Upload assets error

### ISSUE THREAD

**Issue by ITsolution1014** [metaplex-foundation/metaplex#458]
![image](https://user-images.githubusercontent.com/83181173/134244348-f07cf627-1191-4495-aed3-aae7b998a30b.png)
When uploading assets on testnet, I got this error

**Comment by ITsolution1014** [comment]
I have solved this issue

**Comment by devbrooklyn** [comment]
How? I'm facing the same here.

**Comment by ashfaqmehmood** [comment]
I'm facing the same issue.
