### ISSUE TITLE
Metaplex upload giving A has_one constraint was violeted

### ISSUE THREAD

**Issue by krunkroach** [metaplex-foundation/metaplex#459]
I cant use metaplex upload throwing error, the screenshot is attached. Also i am following the hckmd guide to create candy machine during the process this error came up. Downloaded new metaplex code just now and tried again same issue.
<img width="1170" alt="Screenshot 2021-09-22 at 3 05 47 AM" src="https://user-images.githubusercontent.com/90852060/134251247-289cee82-d878-430b-b1b1-bf584eb2fa65.png">

**Comment by KhemnarMayuresh** [comment]
If you are trying second time After first successful upload then make sure you have deleted the 'devnet-temp' file in .cache folder.
folder path: js\packages\cli\.cache
Then try upload command.

**Comment by krunkroach** [comment]
thank you so much, resolved my issue
