### ISSUE TITLE
uploadFileProd2 CORS error

### ISSUE THREAD

**Issue by cajotafer** [metaplex-foundation/metaplex#462]
I deployed my website here https://metaplex-cajotafer.vercel.app/ when I try to create a new item, in the last step, this happens, a CORS error that I don't know how to solve.
![image](https://user-images.githubusercontent.com/41461969/134317003-be670234-9e44-4a6b-9520-e404553be35f.png)
![image](https://user-images.githubusercontent.com/41461969/134317033-57556fe1-7f40-45ee-8185-9ad976ec65d6.png)

I tried to add `mode: no-cors` to that fetch but then I got a Error 403.

**Comment by cajotafer** [comment]
> @cajotafer try installing chrome cors extension and turning it on. that worked for me in the meantime before a fix is deployed

Thank you. Yep, that's what I had to do.

**Comment by jordansexton** [comment]
Thanks for the report. This sounds like it may be an issue with the CORS configuration of the server you're trying to reach. Can you clarify what's causing this?
