### ISSUE TITLE
Uploaded Successful but unable to create_candy_machine

### ISSUE THREAD

**Issue by dhevasnft** [metaplex-foundation/metaplex#464]
Reproducing steps
1) upload and create_candy_machine on devnet with keypair called devnet.json
2) test minting with frontend successful
3) moved on to mainnet, uploaded all 5,000 assets with metaplex upload, it was a success! Spent 9 SOL doingthis
4) run create_candy_machine with the same keypair from the first one, causes an error below. 
5) Already checked that program config id is live on mainnet explorer owned by NFT Candy Machine program.

Any help would be much appreciated on this

wallet public key: 7icLP7LtQLeF9iAhouNDruHn36TSPMtuk64UDddNHWZq
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 21857 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as initializeCandyMachine] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 21857 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
(node:55253) UnhandledPromiseRejectionWarning: Error
    at Function.parse (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/error.js:31:20)
    at Object.rpc [as initializeCandyMachine] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:55253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:55253) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by adigupta13** [comment]
Same error

**Comment by adigupta13** [comment]
Same error but on devnet only. After upload, unable to create candy machine

**Comment by swampygators** [comment]
same error here but wouldnt verify. decided to download metaplex again but now everything is changed

**Comment by stegaBOB** [comment]
There's a small chance that the candy machine might actually be uploaded already. Its a longshot, but there's a chance trying to update the price with update_candy_machine may actually work.

**Comment by dhevasnft** [comment]
> There's a small chance that the candy machine might actually be uploaded already. Its a longshot, but there's a chance trying to update the price with update_candy_machine may actually work.

I tried update_candy_machine it's hitting a different program error.

 metaplex update_candy_machine -p "0.15" --env mainnet-beta --keypair ~/.config/solana/devnet.json
wallet public key: 7icLP7LtQLeF9iAhouNDruHn36TSPMtuk64UDddNHWZq
Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0xa1
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 2588 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0xa1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1

**Comment by ifeLight** [comment]
and i also, any solution yet

**Comment by dhevasnft** [comment]
Are you guys at the same place, upload successfully on mainnet and can't do create_candy_machine?

**Comment by dhevasnft** [comment]
I got the solution guys!!!!!!!!

**Comment by dhevasnft** [comment]
You just needed to check your .cache/ items sometimes the local file and the cache file are not in sync

**Comment by easydeveloppement** [comment]
what do you mean not in sync ? How can we check if it's syncing correctly ?

**Comment by spaceseedtoken** [comment]
same issue, it was using the wrong cache file, I corrected the name but the JSON file is empty, what is supposed to be inside it ?

**Comment by spaceseedtoken** [comment]
I cloned the project & restart from scratch, now it's working
I switched node version as well

**Comment by dhevasnft** [comment]
Hey guys, so the fix to after uploading and unable to create is you should clone the metaplex console and run it with node build/candy...cli then in the command for verify, you wanna log out every single one that doesn't have any problem. Go back to your .cache file and manually adjust that to onChain:false. Run the upload again then run the verify. Should be no problem. If you having other issues, hit me up at https://twitter.com/swans_lab Happy to help out. 

Also my project is here https://dhevas.co minting 0.2SOL per Dhevas. please show support <3

**Comment by Zaft** [comment]
Hey, I'm getting the same error when doing create_candy_machine. What do you mean by "in the command for verify, you wanna log out every single one that doesn't have any problem". After re-cloning, did you run the verify command? Or did reclone, build, then run upload again?
