### ISSUE TITLE
Close account

### ISSUE THREAD

**Issue by marplondon** [metaplex-foundation/metaplex#47]
How do I close my account - I cannot click on icon to change my personal info - please assist thx

**Comment by bartosz-lipinski** [comment]
what do you mean by close an account?

**Comment by marplondon** [comment]
Close GitHub - I don't want to receive any emails. I signed up out of curiosity but didn't know that I would be receiving tons of emails

**Comment by marplondon** [comment]
I can't find a place on GitHub where I can delete my personal data as my email. Only found the option to sign out but that's all. Very odd.
