### ISSUE TITLE
Upload of mp4 failing with 413, no refund on failing to upload

### ISSUE THREAD

**Issue by stranzhay** [metaplex-foundation/metaplex#472]
Each time I try to upload an mp4 with a gif cover image, the call to arweave fails with 413 meaning file size is too large. I have reduced file size to under 10 MB and still failing with 413. Metaplex is not refunding the solana back to my wallet each time it fails and the UI is also not flagging the file size. 

![Screen Shot 2021-09-22 at 9 55 15 PM](https://user-images.githubusercontent.com/16522636/134444157-217bcba0-534f-49c4-b1e5-7b352d4a39f4.png)

**Comment by DesignerPaco** [comment]
I am also facing the same issue while uploading `.mp4` assets to `devnet `?? still got no `solution`
![upload_issue](https://user-images.githubusercontent.com/59694837/141700238-0a393f72-8b92-496f-828b-1b06b25daaf5.png)
.

**Comment by DesignerPaco** [comment]
hello i am also facing issues in uploading .`mp4 ` to `devnet`  can any one have solution??
![issue404](https://user-images.githubusercontent.com/59694837/141702054-522bec3c-1148-491c-a126-ccb81384babe.png)
