### ISSUE TITLE
UploadFile returning metadata with URI to unrelated images

### ISSUE THREAD

**Issue by thmlemke** [metaplex-foundation/metaplex#475]
After an upload from the candy machine cli, the metadata URIs returned from the config contain the correct metaplex metadata, but the inner URI for some of the metadata links to images I have never seen before, from some other people's collections.

**Comment by fletchertyler914** [comment]
Another reason this code should be open sourced, and optional.

**Comment by uaktags** [comment]
Adding #232 as a reference
@bartosz-lipinski do you have the uploadFile code opensourced yet?
