### ISSUE TITLE
why i can find build folder after yarn build

### ISSUE THREAD

**Issue by mohan00710** [metaplex-foundation/metaplex#477]
after yarn build cant find build folder

**Comment by jlittlecameo** [comment]
"/Users/name/Documents/GitHub/metaplex/js/build/web." default settings ignore this so its not in your fork repo normally and only locally. You should see this path if you run the command from the same dir.

**Comment by jordansexton** [comment]
Thanks for answering @jlittlecameo. Questions like this are better suited for Discord where more people can see and answer them. Hopefully your issue is fixed, but please ask there if not!
