### ISSUE TITLE
How is the candy-machine cli uploading files to arweave when --env is devnet?

### ISSUE THREAD

**Issue by jpez16** [metaplex-foundation/metaplex#478]
How does this work? I am much confusion. How is the $AR getting made for the upload?

**Comment by uaktags** [comment]
It's uploaded Arweave via the cloudfunctions.
https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/helpers/upload/arweave.ts 
that's where the "magic" happens. 

Basically, for each upload, we send payment to an address, specifically ``HvwC9QSAzvGXhhVrgPmauVwFWcYZhne3hVot9EbHuFTm`` . We then take that transaction and the env that's set, and send it via an HTTP Post to cloudfunctions. Unfrotunately I still ahvent' seen the cloudfunctions uploadFile's sourcecode get released (was said it was going to be released a while back), so we'd assume that there's a check in their uploadFile script that validates that you paid via the uploaded transaction and will then upload to the respected environment.

**Comment by justinpezzack** [comment]
@uaktags I understand that part! What I'm confused about is that my wallet has 0 Arweave in it and my things are getting uploaded...

**Comment by justinpezzack** [comment]
Is metaplex taking the hit on the arweave to upload?

**Comment by uaktags** [comment]
You're paying metaplex (that address above) in Solana.
They are then taking that as receipt and are paying the arweave fee from their own wallet.

So they're not taking a hit, we're essentially using them as a payment processor. Paying in SOL to an intermediary who is going to transfer to Arweave.

**Comment by justinpezzack** [comment]
I am on devnet though, my mainnet account balance is 0.

**Comment by uaktags** [comment]
I'm not sure if I follow why that's an issue. You're on devnet which is not mainnet, so the balance there doesn't matter.

**Comment by stegaBOB** [comment]
As of now, Arweave is covering the cost for uploads via metaplex. It shouldnt cost you anything to upload regardless of what network you are on. The sole cost with the candymachine is during the create_candy_machine, after everything is uploaded to arweave.

**Comment by stegaBOB** [comment]
> 
> 
> I'm not sure if I follow why that's an issue. You're on devnet which is not mainnet, so the balance there doesn't matter.

Arweave doesn't have a testnet, so I think thats where the confusion was coming from. The upload process is the same regardless of what network you are on... i.e., free.

**Comment by raptorenpls** [comment]
I don't understand why I have to pay 0.0023 to HvwC9QSAzvGXhhVrgPmauVwFWcYZhne3hVot9EbHuFTm at each upload! It seems a lot, and when I remove this address I'm still able to upload json + png on Arweave. So I don't understand...

**Comment by raptorenpls** [comment]
@edwinzeng2005 "image.png" , well thank you I did'n know about your method, but isn't too annoying to parse manually Arweaves links into your json file ?
