### ISSUE TITLE
Add view for ended auctions

### ISSUE THREAD

**Issue by bartosz-lipinski** [metaplex-foundation/metaplex#48]
Home page should navigate to a list of ended auctions with the ability to filter: 
* Only auctions I placed bids on
* Auctions with my royalties.

**Comment by SimonJamesOdell** [comment]
I've created a branch and a new view for this, how do I load the historical data?

**Comment by bhgames** [comment]
Kind of done already with Participation tab and Ended tab being fixed. Will be following up with proper Profile page. Closing this for now.
