### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by ThreadShakur** [metaplex-foundation/metaplex#484]
All is working fine on localhost dev server, but on production i got CORS error when trying make request to solana api
![image](https://user-images.githubusercontent.com/17909421/134622118-3ff9e5b2-5549-410e-8c3e-f63aaaab6a87.png)
Has anyone encountered this?

**Comment by lap-sys** [comment]
I am also encountering CORS error from localhost to the mainnet via Phantom (https://solana-mainnet.phantom.tech, which i added in the connection.tsx file btw)

**Comment by ThreadShakur** [comment]
> I am also encountering CORS error from localhost to the mainnet via Phantom (https://solana-mainnet.phantom.tech, which i added in the connection.tsx file btw)

Its works, thanks a lot!!!

**Comment by woozorg** [comment]
Sorry can you elaborate on the fix?

**Comment by Vkzem** [comment]
> Sorry can you elaborate on the fix?

did you ever find a fix for this?

**Comment by val-samonte** [comment]
To anyone affected by this: the mainnet public rpc does not accept prod domains now - you have to contact them via discord to whitelist your site or just use a paid rpc provider. I think @ThreadShakur meant is he used the rpc from phantom and it works, but tried it and I think it does the same thing now as the mainnet public rpc.
