### ISSUE TITLE
Metaplex-SolSea metadata incompatibility! Metaplex cannot read owner metadata of NFTs on SolSea

### ISSUE THREAD

**Issue by necro-mancer** [metaplex-foundation/metaplex#485]
I am getting this error on my metaplex website ([sshmatrix.art](https://www.sshmatrix.art)): 

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'owner')`

It appears that the app is unable to read the owner properties of the tokens/NFTs. Ideas? 

Console log:

`Unhandled Runtime Error`
`TypeError: Cannot read properties of undefined (reading 'owner')`

`  86 | `
`  87 | const isMetadataAccount = (account: AccountInfo<Buffer>) => {`
`  88 |   return (account.owner as unknown as any) === METADATA_PROGRAM_ID;`
`  >> Error`                
`  89 | };`
`  90 | `
`  91 | const isMetadataV1Account = (account: AccountInfo<Buffer>) =>`

**Comment by dex2code** [comment]
Same problem!
This problem appears when I minted some NFTs on solsea.io

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'owner')

Source
../common/dist/lib/contexts/meta/processMetaData.js (61:0) @ isMetadataAccount

  59 | exports.processMetaData = processMetaData;
  60 | const isMetadataAccount = (account) => {
  **61 |     return account.owner === utils_1.METADATA_PROGRAM_ID;**
  62 | };
  63 | const isMetadataV1Account = (account) => account.data[0] === actions_1.MetadataKey.MetadataV1;
  64 | const isEditionV1Account = (account) => account.data[0] === actions_1.MetadataKey.EditionV1;
Call Stack
Object.processMetaData
../common/dist/lib/contexts/meta/processMetaData.js (8:0)
pullEditions
../common/dist/lib/contexts/meta/loadAccounts.js (288:0)
async Object.loadAccounts
../common/dist/lib/contexts/meta/loadAccounts.js (253:0)
async update
../common/dist/lib/contexts/meta/meta.js (72:0)

**Comment by necro-mancer** [comment]
> Same problem!
> This problem appears when I minted some NFTs on solsea.io
> 
> Unhandled Runtime Error
> TypeError: Cannot read properties of undefined (reading 'owner')
> 
> Source
> ../common/dist/lib/contexts/meta/processMetaData.js (61:0) @ isMetadataAccount
> 
> 59 | exports.processMetaData = processMetaData;
> 60 | const isMetadataAccount = (account) => {
> **61 | return account.owner === utils_1.METADATA_PROGRAM_ID;**
> 62 | };
> 63 | const isMetadataV1Account = (account) => account.data[0] === actions_1.MetadataKey.MetadataV1;
> 64 | const isEditionV1Account = (account) => account.data[0] === actions_1.MetadataKey.EditionV1;
> Call Stack
> Object.processMetaData
> ../common/dist/lib/contexts/meta/processMetaData.js (8:0)
> pullEditions
> ../common/dist/lib/contexts/meta/loadAccounts.js (288:0)
> async Object.loadAccounts
> ../common/dist/lib/contexts/meta/loadAccounts.js (253:0)
> async update
> ../common/dist/lib/contexts/meta/meta.js (72:0)

You are right! This problem started appearing after I minted some on SolSea! Dayum

**Comment by dex2code** [comment]
Exactly )

This is my issue opened few days ago :)

https://github.com/metaplex-foundation/metaplex/issues/463

**Comment by necro-mancer** [comment]
> Exactly )
> 
> This is my issue opened few days ago :)
> 
> #463

I might try to patch a bridge since I know where the issue is. Thanks! I'll let you know if something comes up

**Comment by necro-mancer** [comment]
It seems like this error is due to the licensing addendum to SolSea mints. The license metadata tag on SolSea prohibits the Metaplex API from accessing metadata about the NFTs minted on SolSea. Just need to recode this bit to allow handling exceptions due to the license.

**Comment by dex2code** [comment]
Who breaks the rule? ))) SolSea or Metaplex? )

**Comment by necro-mancer** [comment]
SolSea for adding a feature and Metaplex for not foreseeing it :)

**Comment by dex2code** [comment]
Why it's still not a major bug? How many people use metaplex and solsea?

**Comment by necro-mancer** [comment]
I think it's a major bug but maybe SolSea just came online couple of days ago and we are not hearing noise. It will soon start ringing bells.

**Comment by necro-mancer** [comment]
Here is the fix! Replace lines 87-89 in file ./js/packages/web/src/contexts/meta/processMetadata.ts

```
const isMetadataAccount = (account: AccountInfo<Buffer>) => {
  return (account.owner as unknown as any) === METADATA_PROGRAM_ID;
};
```

with

```
const isMetadataAccount = (account: AccountInfo<Buffer>) => {
  if (account != null) {
    return (account.owner as unknown as any) === METADATA_PROGRAM_ID;
  } else {
    console.log('Metadata unrecognisable');
    return;
  }
};
```

and rebuild. Your unlicensed NFTs will show! ;)

**Comment by dex2code** [comment]
You're great! ) Thank you!

**Comment by necro-mancer** [comment]
If you are running via CLI, then you will need to edit only ./js/packages/common/src/contexts/meta/processMetaData.ts

If you build the web app, both versions gets synced. You are right. I built the web app directly.
