### ISSUE TITLE
Burning NFTs

### ISSUE THREAD

**Issue by Raed-sh** [metaplex-foundation/metaplex#491]
hello guys,
I've been uploading a collection of NFTs with metaplex and for some reason, I  need to burn them but I can't find how I can do this
any help will be appreciated

**Comment by SolariumNFT** [comment]
Hey mate, highly recommend sending them to a Solflare which has a burn NFT function built in. Probably not for large collections but for a few failed mints it’s really effective. Removes it completely from the site, I’ve tested it.

**Comment by Raed-sh** [comment]
actually, I'm looking to burning a huge collection with an implemented function from metaplex if it's available

**Comment by jordansexton** [comment]
Closing as questions like this are better suited for Discord. Please ask there!

**Comment by jordansexton** [comment]
Hey @SolariumNFT, I can totally appreciate the sentiment. There are a lot of Github issues open and we have to make that manageable for maintainers so we can get more of them addressed, that's all.
