### ISSUE TITLE
Metaplex verify throws - 'Failed to get info about account'

### ISSUE THREAD

**Issue by krunkroach** [metaplex-foundation/metaplex#492]
I uploaded 70 nfts to mainnet using ' metaplex upload ./assets --keypaid <my_keypair_path> --env mainnet-beta
i successfully uploaded 70 nfts to arweave (before running the upload command i deleted the previous .cache folder).

no after running upload i want to run metaplex verify command.
As shown in the image i tried running it but it gives me this error. Any idea why?
<img width="1166" alt="Screenshot 2021-09-25 at 5 48 43 AM" src="https://user-images.githubusercontent.com/90852060/134751469-a3c2f41d-ab02-48dd-ac46-d42008cebca2.png">

**Comment by notjordan** [comment]
Any update with this? I am having the same issue. Upload works fine and says successful but verify fails

**Comment by emersonthis** [comment]
I'm having the same issue. I attempted the `upload` command but it throw errors, so I deleted the .cache/ file and tried again... but got this same error. `Error: failed to get info about account CggtNXg...RghEvSF`

**Comment by emersonthis** [comment]
I still don't understand the error, but after a bit of Googling I found the suggestion to add `/` to the end of the `--rpc-url` option and this actually seems to have fixed the problem for me. 🤯
