### ISSUE TITLE
Metaplex Store not loading after minting on Solsea.io

### ISSUE THREAD

**Issue by yogeshj25** [metaplex-foundation/metaplex#498]
Hello, my metaplex store ( https://happyhappies.art/ ) has not been loading for the past 2 days. Everything was working fine for the past month until now. I did not make any changes during this time; however I was active on, solsea.io .  
I created a new collection and listed 2 nfts, Here is a link to the collection: https://solsea.io/collection/6148fdcca862da896a89e502

I noticed the problem began right around the time I minted my first NFT on the solsea collection.

Also I listed a few metaplex nfts on solsea (which I have delisted now for troubleshooting purposes).

The sol address i used for both metaplex and solsea are the same: FtryTt8rDbANCHYLwwffrmBgLnnNzS8fLAUfPsm6csFd
And I use phantom wallet to connect to both sites.

Here is an error screenshot:

![Screen_Shot_2021-09-25_at_2 55 23_AM](https://user-images.githubusercontent.com/89832892/134767380-62766581-811f-44f7-8a4d-98376e1ddedc.png)

Can someone please help me resolve this issue?

Thank you!
Yog

**Comment by yogeshj25** [comment]
thank you for the solution @danter83 ; however this is still not working for me. perhaps I am doing something wrong?

**Comment by yogeshj25** [comment]
3 months later, still waiting for a solution. can some one please take a look at this. need help!

**Comment by aNicePlayer** [comment]
Using WayBack Machine gives the attached link from the video description.

Not sure if it will help you guys, but I'm gonna try and use it

https://github.com/staccDOTsol/metaplex/commit/40f11a52ede592fdbb5817c9961391dd1c3cd588
