### ISSUE TITLE
Candy Machine tokenMint null

### ISSUE THREAD

**Issue by AlexLeung** [metaplex-foundation/metaplex#507]
Whenever I use the CLI to create a candy machine instance,  then load the candy machine state via
https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/fair-launch/src/candy-machine.ts#L134

`getCandyMachineState`

I get back a candy machine state where the `tokenMint` field is `null`. For example on dev net 4tzo9VEpQsKw5ENq4fDW5b2csqSTJMSKzBGgVQgPZSTb

```json
{
    "authority": {
        "_bn": "7297dc02b1a174a34d635d952df3621a44eba1c747a7fe79965eb00cab3cfa83"
    },
    "wallet": {
        "_bn": "7297dc02b1a174a34d635d952df3621a44eba1c747a7fe79965eb00cab3cfa83"
    },
    "tokenMint": null,
    "config": {
        "_bn": "684b759168b0a1ceee9573fc6209fb559a5a5ae72f3daad35c81aa8925356cdf"
    },
    "data": {
        "uuid": "8288xE",
        "price": "b2d05e00",
        "itemsAvailable": "01",
        "goLiveDate": null
    },
    "itemsRedeemed": "00",
    "bump": 255
}
```

based on the code in the repo, I can't call `mintOneToken` without running into errors

```typescript
await mintOneToken(candyMachine, wallet.publicKey)
```

Because [in the `mintOneToken` code it expects](https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/fair-launch/src/candy-machine.ts#L212) the `tokenMint` to be non-null

```typescript
  const userPayingAccountAddress = (
    await getAtaForMint(candyMachine.state.tokenMint, payer)
  )[0];
```

What can I do to ensure the field is defined?

**Comment by Yuriy-Ihor** [comment]
Hello, have you managed to fix this?

**Comment by Yuriy-Ihor** [comment]
https://github.com/exiled-apes/candy-machine-mint
With this repo everything is fine
I've noticed that this error only occurs when I try to use my repo's with SPL token support. Idk why
