### ISSUE TITLE
GIF support for Candy Machine

### ISSUE THREAD

**Issue by dev-1iam** [metaplex-foundation/metaplex#511]
Candy machine currently only supports PNGs. 
I tried adding it myself but have had troubles getting past the arweave upload. 
(https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/helpers/upload/arweave.ts#L9-L21 returns invalid-json)

**Comment by jamesturnernz** [comment]
Also missing MP4 file support in Candy Machine.
When I upload the JSON to Arweave, it still has the 0.mp4 file name, no Arweave URI like it does for the PNG.

**Comment by kevinfaveri** [comment]
I'm thinking about developing support for this on my repo https://github.com/kevinfaveri/solana-candy-factory in the near future. In fact, I'm thinking about creating a UI to do all this stuff that happens using the CLI right now. This can be easily done by forking the Metaplex CLI, I think.

**Comment by uaktags** [comment]
That's because it's hardcoded for PNG and its trivial to update it to work. Without knowing if uploadFile has any limitations, you only need to make a number of small changes to get other files to upload.

You'll need to change the logic for pngFileCount in ``candy_machine_cli.ts``
Change logic for the files seen/existingInCache/ and newFiles, and change up the manifestContent to look for your new filetypes in ``upload.ts``
Lastly fix in ``arweave.ts`` for the data.append for your new filetype and mime type.

I tested with JPEG and GIFs.

**Comment by kevinfaveri** [comment]
> That's because it's hardcoded for PNG and its trivial to update it to work. Without knowing if uploadFile has any limitations, you only need to make a number of small changes to get other files to upload.
> 
> You'll need to change the logic for pngFileCount in `candy_machine_cli.ts` Change logic for the files seen/existingInCache/ and newFiles, and change up the manifestContent to look for your new filetypes in `upload.ts` Lastly fix in `arweave.ts` for the data.append for your new filetype and mime type.
> 
> I tested with JPEG and GIFs.

Thanks bro, bookmarked

**Comment by dev-1iam** [comment]
> That's because it's hardcoded for PNG and its trivial to update it to work. Without knowing if uploadFile has any limitations, you only need to make a number of small changes to get other files to upload.
> 
> You'll need to change the logic for pngFileCount in `candy_machine_cli.ts` Change logic for the files seen/existingInCache/ and newFiles, and change up the manifestContent to look for your new filetypes in `upload.ts` Lastly fix in `arweave.ts` for the data.append for your new filetype and mime type.
> 
> I tested with JPEG and GIFs.

Would you mind sharing your changes? Like I said, I did everything that you mentioned and wasn't able to get past the cloud function fetch: 'https://us-central1-principal-lane-200702.cloudfunctions.net/uploadFile4'. I might have missed something small. I still think it's worth adding support rather than leaving it hardcoded so that it works out of the box. Especially if it's a trivial change

**Comment by uaktags** [comment]
@dev-1iam do you have a repo of your recent attempt? I can probably just show you that way. Otherwise, i'll make a gist later today and rerun through it. Only quickly did it to validate what was needed and that it was possible, but tend to keep my local repo pretty unmodified so to best help answer questions in discord.

**Comment by uaktags** [comment]
https://gist.github.com/uaktags/17dc90ccce2ce7034c1a5c2126e77dfa

GIF/JPEG/JPG/PNG work
AVI/MP4/WMV seems to give me issues with lib.rs. Going to look at this for about another hour before i move on.

**Comment by Aoiwim** [comment]
> This is a pretty hacky attempt to do this, threw it together in about 30minutes without really thinking about optimizations.
> 
> https://gist.github.com/uaktags/17dc90ccce2ce7034c1a5c2126e77dfa
> 
> 
> 
> GIF/JPEG/JPG/PNG work
> 
> AVI/MP4/WMV seems to give me issues with lib.rs. Going to look at this for about another hour before i move on. 

Any luck on getting mp4 to work? What needs to be changed?

**Comment by kevinfaveri** [comment]
For getting MP4 and other types to work it should use the "animation_url" and not the images

**Comment by adilanchian** [comment]
Hey all!

I would love some more insight from folks here. [These docs from Metaplex](https://docs.metaplex.com/nft-standard) specifically call out supported all these other formats, but looking through the CLI code, it doesn't look like it supports anything but pngs :eyes:

Curious if I am missing something here or there are PRs in flight? I've been searching around this repo with no luck =/

**Comment by Creeland** [comment]
I managed to get HTML files working. [You can check out exactly what I did in this commit.](https://github.com/Creeland/metaplex/commit/878d91e46a7ec7aa0a324a88f9d09a6d4a614013)

# Changes 
## **js/packages/cli/src/candy-machine-cli.ts**

Went through and replaced all the PNG extensions and "image" language. 

This one was a little tricky. `.text` on check was broken with fetches on `animation_url`. This checks for a redirect and makes a fetch on the redirect URL that the initial fetch returns. 
```
if (parsed.animation_url) {
  let check = await fetch(parsed.animation_url);
  
  if (check.redirected) {
    check = await fetch(check.url)
  }
```

## **js/packages/cli/src/commands/upload.ts**
Made sure to pass the HTML file to the arweave function. Replaced PNG extensions

## **js/packages/cli/src/helpers/upload/arweave.ts**
Replace image param with htmlFile. Changed filename and content type

## **js/packages/cli/src/commands/verifyTokenMetadata/index.ts**
Made sure to change file type to text/html. Replace image with animation_url

**Comment by JoisBoss121** [comment]
Has anyone been able to do GLB files?

**Comment by DanteAddon** [comment]
Hey everyone, I tried to build candymachine with Gif files, when I ran upload command, it started but it was showing as [object, Object] when upload was running, It completed and when I minted NFTs, it's gif was good at arweave link, but it didn't show the art in any wallet, not even on sol scan when I looked at token info, it just keep loading infinitely. 

Please help me, what am I doing wrong?
Note: I have worked with Pngs several times, and I didn't make any changes in metaplex or candymachine when I started working on gifs. 

Please help me. Thanks in advance.

**Comment by stegaBOB** [comment]
The .gif upload should be fixed now. Adding support for uploading more types is on the roadmap! Closing for now.

**Comment by tusharLamba11** [comment]
Is there any update on mp4 ?
