### ISSUE TITLE
Add an optional whitelist to metaplex of those people who can place bids

### ISSUE THREAD

**Issue by beautyfree** [metaplex-foundation/metaplex#517]
For example, in order to approve(add) these users through KYC

**Comment by emlcpfx** [comment]
Following for updates.

**Comment by AlfieDarko** [comment]
also following

**Comment by AlfieDarko** [comment]
> Hey friends, are there any plans to do this? If not, what would be the best approach here? I see a few potential approaches, without having looked at the code in detail
> 
> * send the program a list of addresses which can mint
> * store a map from addresses -> # of mints that address is allowed to do
> * store a map from tokens -> bools, then check that the minter owns that token (a sort of "mint pass" approach)
> 
> Thoughts?

This looks cool to me. Also a switch to turn the whitelisting check off and it would be perfect
