### ISSUE TITLE
panic in nft-candy-machine/src/lib.rs:318:18

### ISSUE THREAD

**Issue by earth04190419** [metaplex-foundation/metaplex#518]
Hello, community. I ran into this strange trap.
I just run metaplex cli upload.
![image](https://user-images.githubusercontent.com/86136164/134852428-b4dbee0a-9b61-434d-9f6f-fd5d18211356.png)
But this kind of error happend.
![image](https://user-images.githubusercontent.com/86136164/134852517-c6346eef-8763-46c8-b7c1-1f0f9bce7d3f.png)
Following is nft metadata json file.
![image](https://user-images.githubusercontent.com/86136164/134852610-3ce95a84-4174-4d69-8471-114a3fa9a317.png)

Does anybody know this issue? :(

**Comment by saraspaudel** [comment]
Getting the same error

**Comment by uaktags** [comment]
Getting that as well, thought it was due to trying video files, but now i'm not sure.

**Comment by saraspaudel** [comment]
@uaktags Please join Discord. Try with another cache e.g. `-c temp2` does it work?

**Comment by uaktags** [comment]
I am in discord, been there for weeks helping people in Dev channel (Tags).

This isn't an issue that the cache will solve. I've both cleared the cache by manually deleting devnet-temp as well as creating a new temp file with the -c.

No, changing cache doesn't fix problem.
