### ISSUE TITLE
Signing with HW crypto-wallets is not supported

### ISSUE THREAD

**Issue by ivan-homoliak-sutd** [metaplex-foundation/metaplex#519]
First of all, thank you guys for your great effort on this project!

Unfortunately, singing within some commands using HW wallets (such as Ledger) is not supported. For example in the **upload** command of candy machine CLI.

Would be really nice to use something like this:
**ts-node ./metaplex/js/packages/cli/src/candy-machine-cli.ts upload ./assets --env mainnet --keypair usb://ledger**

**Comment by ivan-homoliak-sutd** [comment]
Hi guys, I just realized that with regard to this issue, the easiest solution would be just to add another parameter -- new minting authority for **update_candy_machine** command. Although this might be another issue/extension.

**Comment by catsonmats** [comment]
Also noticed usb://ledger is not recognized

**Comment by markm1992** [comment]
Are you on WSL on Windows or some virtualization platform? WSL doesn't support USB passthrough. Try on a Linux/Mac machine (not virtualized).
