### ISSUE TITLE
Hide NFT after mint for 24 hours

### ISSUE THREAD

**Issue by Tas-mayuresh** [metaplex-foundation/metaplex#520]
Is there a way to hide NFTs behind some placeholder so that it not visible, and then reveal that some point in the future (may be after 24 hours), after mint?

**Comment by devbrooklyn** [comment]
Check https://github.com/metaplex-foundation/metaplex/issues/420

**Comment by israelidanny** [comment]
You can do so by setting all the mints to a temporary image, and then writing a script that would load all the Metadata accounts (`getProgramAccounts`) with a `memcmp` filter by `updateAuthority`. 

Make sure your metadata stays mutable.

Then you run an `update_metadata_account` operation.

Once you're done updating - you can set the Metadata to immutable and the NFT is then frozen forever in the final state.

**Comment by Tas-mayuresh** [comment]
Sorry, but I am new to this, can you please specify how can I 
- set metadata mutable
- call getProgramAccounts filter by updateAuthority.
- call update_metadata_account 

I am using candy-machine part for minting and setting candy machine.

**Comment by israelidanny** [comment]
- Metadata is mutable by default unless you explicitly made it immutable
- https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getParsedProgramAccounts (also look up how to filter  by memcmp - https://solana-labs.github.io/solana-web3.js/modules.html#MemcmpFilter)
- For update_metadata_account you can see how it happens in the source code: https://github.com/metaplex-foundation/metaplex/blob/02fd9c0d1384bca247b2035cb85aa799a2cdf035/js/packages/common/src/actions/metadata.ts#L497
If you still have trouble let me know.

**Comment by kevinfaveri** [comment]
How to make metadata explicitly immutable even before mint using the Candy Machine @israelidanny? A JSON object key called "is_mutable": true on the NFT object?

**Comment by israelidanny** [comment]
I'm not sure that Candy Machine exposes this setting. AFAIK all Candy Machine NFT are minted as mutable. Just to make sure (because you had it unclear in your comment):
Mutable = Changeable
Immutable = Non Changeable

So to make it *immutable* you would need mutable to be *false*. But it's not in the JSON, it's on the actual Metadata program account.

I'm not sure Candy Machine exposes this. From what I understand you'd simply need to update all your metadata yourself after mint and make it immutable if you wish.

**Comment by israelidanny** [comment]
> So when we need to modify this image, if arweave is immutable, then we must upload another image and change the link?
Yes, exactly.

**Comment by YogaaDev** [comment]
Ok, so can i use this file modification to do that : https://github.com/metaplex-foundation/metaplex/pull/640/files ?

**Comment by YogaaDev** [comment]
Ok so after that, how to link new image to mint nft ?

**Comment by bojhher** [comment]
Can you guys 
Make a list for the commands a example it in normal words plz

**Comment by garrettbear** [comment]
ya lets get a tutorial on this. seeing so many people asking about this on discord

**Comment by Looktazz** [comment]
Hi ! I would like to update all metadata of my 10,000 NFT in order to do a reveal but I don't find a script that allow me to do that. Somebody has a solution ? Thanks a lot
