### ISSUE TITLE
seller_fee_basis_points of NFT's JSON does not behave as expected

### ISSUE THREAD

**Issue by ivan-homoliak-sutd** [metaplex-foundation/metaplex#532]
Hi guys, I tested royalties (seller_fee_basis_points in JSON of NFT)  on the mainnet using the Solflare wallet's send NFT functionality. However, the beneficiary specified in json does not obtain anything after sending NFT. Does anyone experienced the same issue or do you know how to resolve? 

See my JSON below:

{
  "name" : "TODO #0",
  "symbol" : "SFTY",
  "description" : "TODO",
  "image" : "0.png",
  "seller_fee_basis_points" : 500,
  "attributes" : [ {
    "value" : "Q2",
    "trait_type" : "quadrant"
  }, {
    "value" : "BIG",
    "trait_type" : "scale"
  }, {
    "value" : "EASY",
    "trait_type" : "difficulty"
  }, {
    "value" : "SEVEN",
    "trait_type" : "palette"
  }, {
    "value" : "ORDINARY",
    "trait_type" : "paletteRarity"
  }, {
    "value" : "BASIC",
    "trait_type" : "stampRarity"
  } ],
  "properties" : {
    "category" : "image",
    "creators" : [
    {
      "address" : "Ev8WDBR5zx4JCpH5hhmx39cfy8NMfxohfW7RcPCB3k1Z",
      "share" : 0
    },
    {
      "address" : "GP7KVwUe5HXrG1koFHWRmYdf2qfzi56ssunb5KaQs85r",
      "share" : 100
    } ],
    "files" : [ {
      "uri" : "0.png",
      "type" : "image/png"
    }, {
      "uri" : "https://todo/0_preview.png?dl=0",
      "type" : "image/png",
      "cdn" : true
    }, {
      "uri" : "https://todo/0_preview.png",
      "type" : "image/png",
      "cdn" : true,
      "preview" : true
    } ]
  }
}

**Comment by israelidanny** [comment]
I think that the JSON is merely for easy off-chain linking. The actual fee array lives on the Metadata program account

**Comment by ivan-homoliak-sutd** [comment]
I see. Thank you. Would be curious how to update the Metadata program's state after deployment. In my case, **seller_fee_basis_points** is zero and creators are empty. I used https://gist.github.com/dvcrn/c099c9b5a095ffe4ddb6481c22cde5f4 to retrieve Metadata.

**Comment by israelidanny** [comment]
The fee on the JSON is for presentational purposes only. You also need to make sure the actual Metadata program account has the creators array identical to the JSON with the correct fee basis points.
