### ISSUE TITLE
error: unknown command 'generate_art_configurations'

### ISSUE THREAD

**Issue by walter-grace** [metaplex-foundation/metaplex#534]
when running 'metaplex generate_art_configurations ./assets' in cli folder this error comes up

**Comment by MrArchiiitect** [comment]
having a simmilar issue, been trying 'generate_art_configurations' to the traits directory to create the .json file and been hitting a {metaplex command not regocnized}

**Comment by hyperion186** [comment]
would like to solve the same problem too. any fixes?

**Comment by uaktags** [comment]
Not for nothing, but are you guys sure you've repackaged metaplex using the latest pull from github?

do a ``metaplex`` command by itself or do a ``metaplex -h``
you should get 
```
 metaplex
Usage: candy-machine-cli [options] [command]

Options:
  -V, --version                                      output the version number
  -h, --help                                         display help for command

Commands:
  upload [options] <directory>
  verify_token_metadata [options] <directory>
  verify [options]
  verify_price [options]
  show [options]
  create_candy_machine [options]
  update_candy_machine [options]
  mint_one_token [options]
  sign [options]
  sign_all [options]
  generate_art_configurations [options] <directory>
  create_generative_art [options]
  help [command]                                     display help for command
```

**Comment by supercarsforall** [comment]
When I do a `metaplex -h` I get: 
Is latest pull from github
```
.nvm/versions/node/v14.17.6/bin/metaplex: line 1: use strict: command not found
.nvm/versions/node/v14.17.6/bin/metaplex: line 2: syntax error near unexpected token `('
.nvm/versions/node/v14.17.6/bin/metaplex: line 2: `var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {'
```

**Comment by uaktags** [comment]
@supercarsforall your metaplex didn't package correctly as per your output is erroring on the -h parameter. 

retest wtih ts-node instead (per documentation) to check if any issues with the actual cli prior to packaging, if no issues, then repackage again and check for any output

**Comment by supercarsforall** [comment]
@uaktags Thanks for the help.
It won't package properly. I get byte errors when using `yarn run package:macos`
When I try to `ts-node cli generate_art_configurations ./traits`
I get:

```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './cli'
Require stack:
- /Users/workstation/Code/metaplex/js/packages/cli/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at requireResolveNonCached (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:320:16)
    at getProjectSearchDir (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:290:35)
    at main (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:192:27)
    at Object.<anonymous> (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:350:5)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
'Code/metaplex/js/packages/cli/imaginaryUncacheableRequireResolveScript'
  ]
```

**Comment by studentofcoding** [comment]
> @uaktags Thanks for the help. It won't package properly. I get byte errors when using `yarn run package:macos` When I try to `ts-node cli generate_art_configurations ./traits` I get:
> 
> ```
> internal/modules/cjs/loader.js:892
>   throw err;
>   ^
> 
> Error: Cannot find module './cli'
> Require stack:
> - /Users/workstation/Code/metaplex/js/packages/cli/imaginaryUncacheableRequireResolveScript
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>     at Function.resolve (internal/modules/cjs/helpers.js:98:19)
>     at requireResolveNonCached (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:320:16)
>     at getProjectSearchDir (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:290:35)
>     at main (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:192:27)
>     at Object.<anonymous> (/Users/workstation/.nvm/versions/node/v14.17.6/lib/node_modules/ts-node/dist/bin.js:350:5)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
> 'Code/metaplex/js/packages/cli/imaginaryUncacheableRequireResolveScript'
>   ]
> ```

This is the same error I get on my end, I think when npm build, the script missed building the `cli.js`

You can reproduce this error when running the script on `~js/packages` directory like example below 

```
Error: Cannot find module 'E:\Project\Consultant\whatever_metaplex\js\packages\cli\build\cli.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by uaktags** [comment]
If you're both ( @studentofcoding and @supercarsforall  ) on the latest, there is no cli.ts anymore so @supercarsforall  your command is never going to work (if you're up to date, since like 1-2weeks ago). That's why it says cli doesn't exist, because it doesnt. Look within the js/packages/cli/src folder, you should see candy_machine_cli.ts.

bytecode *warnings* are not *errors*, if you packaged and it said "Done" then you should have your binary in js/packages/cli/bin/macos/metaplex. 

If that gives you trouble, you have the options of doing ``ts-node candy_machine_cli.ts -h`` or after doing a ``yarn build`` you can do a ``node js/packages/cli/build/cli/candy_machine_cli.ts``. These are 3 options to do the same exact thing.

**Comment by studentofcoding** [comment]
> If you're both ( @studentofcoding and @supercarsforall  ) on the latest, there is no cli.ts anymore so @supercarsforall  your command is never going to work (if you're up to date, since like 1-2weeks ago). That's why it says cli doesn't exist, because it doesnt. Look within the js/packages/cli/src folder, you should see candy_machine_cli.ts.
> 
> bytecode *warnings* are not *errors*, if you packaged and it said "Done" then you should have your binary in js/packages/cli/bin/macos/metaplex. 
> 
> If that gives you trouble, you have the options of doing ``ts-node candy_machine_cli.ts -h`` or after doing a ``yarn build`` you can do a ``node js/packages/cli/build/cli/candy_machine_cli.ts``. These are 3 options to do the same exact thing.

What is the Metaplex versioning you have on your end? I believe it's not really a recent one no?

And also the problem mainly on create_generative_art functionality

**Comment by uaktags** [comment]
@studentofcoding you're asking me what version I have? I have the latest, i compile with every new commit.

**Comment by supercarsforall** [comment]
@uaktags Thanks for the education on this, really appreciate it. New to JS and git thanks for being patient.

**Comment by TheRecode** [comment]
@uaktags @studentofcoding how to package it correctly because i'm getting an error when i using -h parameter

**Comment by omergoksoy** [comment]
I'm getting same error too.
couple times deleted and re-pull repo but nothing changed.
