### ISSUE TITLE
unhandled runtime error

### ISSUE THREAD

**Issue by earth04190419** [metaplex-foundation/metaplex#558]
I just build the project and start the project.
But it displayed unhandled runtime issue.
![image](https://user-images.githubusercontent.com/86136164/135477280-21ef7fd8-87e0-4dc5-8a4c-53d560d60901.png)

**Comment by jordansexton** [comment]
Unfortunately there isn't enough context in this issue to replicate the problem. If this is still happening for you, please open a new Bug Report issue with detailed reproduction steps.
