### ISSUE TITLE
Error: not all NFTs checked out. check out logs above for details

### ISSUE THREAD

**Issue by chrisbrooks** [metaplex-foundation/metaplex#566]
I'm a developer but new to Crypto and the NFT world. I've been following the guides for metaplex from here:

```
https://medium.com/@giacavicchioli/ultimate-metaplex-candy-machine-guide-on-solana-7643ed3b7267
and
https://hackmd.io/@levicook/HJcDneEWF
```

I seem to come stuck at the point below when i'm doing the upload to arweave. I'm using the latest master branch as of making this issue.
```
ts-node src/candy-machine-cli.ts upload assets --env devnet --keypair ~/.config/solana/devnet.json --log-level trace --number 1
File uploaded: https://arweave.net/m8c9WtAPZJUhyBP5Qwdv__rXeWJSjng0Eg75-UsAq5I
setting cache for  0
Writing indices 0-0
Done. Successful = true.
ended at: 2021-10-01T05:14:01.652Z. time taken: 00:00:35
```

However when I go to arweave url:
```
https://arweave.net/m8c9WtAPZJUhyBP5Qwdv__rXeWJSjng0Eg75-UsAq5I
```
and try to load the image url in that json blob below it just returns a blank page.
```
https://www.arweave.net/SDLvwwuH_6Yy9DLmmTg12F-CS56HQ8VHXvwG6XruYYA?ext=png1
``` 

If I then run the verify step below it just returns the error `Error: not all NFTs checked out. check out logs above for details`

```
ts-node src/candy-machine-cli.ts verify --env devnet --keypair ~/.config/solana/devnet.json
```

wondering if anyone has actually used the metaplex cli to do all of this and it's been successful on devnet? Sending the exact same metadata from the web application still fails but I can't seem to work out the bug in the api call, they seem pretty different to the cloudfunction uploadFile4 api.

**Comment by AcoustiCoder** [comment]
I cant verify either..

**Comment by lz2470** [comment]
Same here!! is there a problem with arweave?

**Comment by SethCalkins** [comment]
Same here. Any solution guys?

**Comment by chrisbrooks** [comment]
> Same here!! is there a problem with arweave?

I don't think it's an arweave issue because using the metaplex web app works with the same metadata and same image. Must be something from the cli perspective that's not correct. When I have time will debug it but the devs who built this would have a better idea.

**Comment by TheSupremeNoob** [comment]
Same issue here... weird thing was I managed to upload successfully 2 days ago and now its happening on all my uploads. Even tried it on mainnet. Same thing.

**Comment by thom9346** [comment]
I had the same issue. It seems the problem for me was that my images was too small. Their size was about ~4KB, which caused the same error. With larger images (for me 600KB) worked just fine.

**Comment by z3000z3000z3000** [comment]
with images >25k work fine?

**Comment by chrisbrooks** [comment]
Can confirm this seems to work for large image sizes. I just did one for 800kb and it worked. I also did one for 80kb and it didn't. Also not sure on the threshold but it's still an issue. Pretty annoying either way and the example traits in this repository in the cli directory will not work if you use the generator to make the image. They only amount to about 5kb.

**Comment by chrisbrooks** [comment]
closing for now as it's not a metaplex issue tbh. Will open something with arweave.
