### ISSUE TITLE
change arweave node provider on react

### ISSUE THREAD

**Issue by jossemii** [metaplex-foundation/metaplex#572]
A few weeks ago i posted an issue on the Metaplex's github repo.
arweave mint NFT code.    Issue #232 

I need the code of mint an nft because i want to exec it on the react app and change the arweave node provider (arweave.net) to another.

Could you help me?

Thanks.

**Comment by uaktags** [comment]
You can look into arweave-js and implement your own version of what they're doing. cloudfunctions uploadFile, from what i can gather and just understand, is simply listening for HTTP POSTs, validates that someone paid the fee on SOL to metaplex, and then they forward the POST'ed data to arweave (possibly using arweave-js as well, or some other arweave integration).

So, all you need is to rethink the logic to replace the cloudfunctions useage to your own inhouse version (either building Arweave-js into the script or by hosting your own http server page to do the same thing).

Sorry, i don't have any code as well and have been waiting for the same opensource commitment.
