### ISSUE TITLE
how to set a custom provider?

### ISSUE THREAD

**Issue by Nikola43** [metaplex-foundation/metaplex#594]
I am trying to upload 10k images to the testnet and I always have an error, several developers have told me to use quicknode, but I don't know how to establish a custom provider, if someone can help me I would really appreciate it, I already spent 34 sol uploading it to the mainnet without success. ...

**Comment by cdric** [comment]
Well if you check the PR some people have offers solutions but not all of these have been merged to MASTER yet. Maybe you could try to deploy these PR locally. 

Some people are offering a solution to use IPFS like with this PR:
https://github.com/metaplex-foundation/metaplex/pull/467/

Good luck!

**Comment by jordansexton** [comment]
Closing since questions like this are better suited for Discord where more people can see and answer them. Please ask there!
