### ISSUE TITLE
candy-machine-cli.ts verify --env devnet | not all NFTs checked out

### ISSUE THREAD

**Issue by cdric** [metaplex-foundation/metaplex#608]
After a successful upload of my asset via candi-machine upload, I'm getting an error while verifying.
I've tried immediately after upload and 15 minutes after upload and still having the same issue

```
ts-node js/packages/cli/src/candy-machine-cli.ts verify --env devnet --keypair [REDACTED] --log-level trace
setting the log value to: trace
wallet public key: 4bs2EqspQMtF67AvSK62zcm3vqmvRfEu9X9wuezgw6C5
program id from anchor cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ
Looking at key  0
Name #3 with https://arweave.net/v-RmZIUT-3KUW79KzGP4YvYe4DYi-UrCziLqh48FTAg returned non-200 from uploader 404
/.../metaplex/js/packages/cli/src/candy-machine-cli.ts:53
  .option(
                      ^
Error: not all NFTs checked out. check out logs above for details
    at /.../metaplex/js/packages/cli/src/candy-machine-cli.ts:275:11
    at step (/.../metaplex/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/.../metaplex/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/.../metaplex/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Here is the content of https://arweave.net/v-RmZIUT-3KUW79KzGP4YvYe4DYi-UrCziLqh48FTAg

`{"name":"#3","description":"This is the description of a test NFT project","image":"https://www.arweave.net/PaZ_phCVhZq_3BbypgXqlBr34jk9VmEWXlJ3iZjZ_Us?ext=png","edition":3,"date":1633343413736,"symbol":"","seller_fee_basis_points":1000,"properties":{"files":[{"uri":"https://www.arweave.net/PaZ_phCVhZq_3BbypgXqlBr34jk9VmEWXlJ3iZjZ_Us?ext=png","type":"image/png"}],"creators":[{"address":"REDACTED","share":100}]},"attributes":[{"trait_type":"1layer background","value":"Nft 6"},{"trait_type":"2layer body","value":"Nft 5"},{"trait_type":"3layer sparkles","value":"Nft 3"},{"trait_type":"4layer eyes","value":"Nft13"},{"trait_type":"5layer mouth","value":"Nft 3"},{"trait_type":"6layer headwear","value":"Nft 5"},{"trait_type":"7layer action","value":"Nft 3"}]}`

**Comment by cdric** [comment]
I've tried again with a new set of assets and same error

The problem seems to be related to this line in the log
`Name #00005 with https://arweave.net/YwEC5PwJQnxg5wC0KTUM2ILn5nS4w7ft3EL656dZPf0 returned non-200 from uploader 404`

**Comment by cdric** [comment]
Can this be an issue because I'm uploading on the devenv? I haven't tried yet on the mainnet...

**Comment by ajpierce** [comment]
I ran into something similar today.

The first thing I did was uncomment this block here, because this is where verify was failing:

https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/candy-machine-cli.ts#L200

When I ran verify (on devnet), the first 130 items would check out, but when it got to 131:

```
Name Pesky Penguins #130 with https://arweave.net/ws0LZSWWeiEk6F01zqB-qSlI_jAEJiSdVd6OQqFcI_Q checked out
Looking at key  130
Name () or uri () didnt match cache values of (Pesky Penguins #131)and (https://arweave.net/hqDM4ROdRQ1w7vkR7bTEyySgvKVNQF23NM4wZyGo_iQ). marking to rerun for image 131
(node:25697) UnhandledPromiseRejectionWarning: Error: not all NFTs checked out. check out logs above for details```

Here you can see that the values it's getting from the config.data, name and uri are blank: https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/candy-machine-cli.ts#L191

I've tried running upload half a dozen times since then and it always fails here.  Do I just need to keep running upload until they all pass?

**Comment by cdric** [comment]
Thanks for your insights. I think we might have two different issue that are leading to the same error message: Error: not all NFTs checked out

Let me explain more. In my case, after a successful upload, the images are not available on arweave and this seems to be producing this error

If you looking up my NFT json file that I put in my first comment, the image for my NFT point to https://www.arweave.net/PaZ_phCVhZq_3BbypgXqlBr34jk9VmEWXlJ3iZjZ_Us?ext=png which doesn't return a valid URL.

In you case, I was able to access the image of your NFT correctly by accessing this link: https://www.arweave.net/lQXvP1UqedRtI5HqSH1ZAsm2E29JJLNFVPcUvutbBBc?ext=png

So then I am wondering if something might be wrong with arweave when upload on devend.
Are you running this on the devenv as well?

**Comment by JIVIN0902** [comment]
@cdric Even I have an issue like yours. My metadata is uploaded but the images on arweave are not. And when I verify it gives the same error ->>> Error: not all NFTs checked out

**Comment by ajpierce** [comment]
Yes! I am running this on devnet, and I _also_ ran into an issue where my images were not showing up on arweave.  The solution was actually to _increase_ the size of my image files; most images were around 4kb, but when I blew them up to >25kb, arweave started taking them.

I used imagemagick to blow up all my images at once with the following command (note: this MUTATES your files, so copy them before you run the command)

```
mogrify -resize 2000 *.png
```

The 2000 in the above command enlarges it to 2000px wide (maintains aspect ratio); previously our images were 512px square.

Once you embiggen your images, you'll need to start the upload over again.  Remember to use a different cache or delete the old cache file before you upload again!

**Comment by JIVIN0902** [comment]
@ajpierce i recloned the git repo and did the same procedure and I still get these errors

**Comment by cdric** [comment]
@ajpierce - Hey Andrew. This is good to know that it is working for you on devnet.
For me though, I tried to increase the file size from 11K to 45K and re-run the upload and this is still failing for me.

```
Looking at key  4
Response body {"dna":"fddd2c22f70c001805ae2b4f5998906b85f94ed5","name":"#00005","description":"SecretNFTProject001","image":"https://www.arweave.net/ZJze2XGenx9pJsc90Y4lf2m5hLw7uaoHuqmAW1hROgE?ext=png","edition":4,"date":1633359934895,"symbol":"","seller_fee_basis_points":1000,"properties":{"files":[{"uri":"https://www.arweave.net/ZJze2XGenx9pJsc90Y4lf2m5hLw7uaoHuqmAW1hROgE?ext=png","type":"image/png"}],"creators":[{"address":"4bs2EqspQMtF67AvSK62zcm3vqmvRfEu9X9wuezgw6C5","share":100}]},"attributes":[{"trait_type":"test/Background","value":"Nft 6"},{"trait_type":"test/Body","value":"Nft 5"},{"trait_type":"test/Sparkles","value":"Nft 3"},{"trait_type":"test/Eyes","value":"Nft2"},{"trait_type":"test/Mouth","value":"Nft 3"},{"trait_type":"test/Headwear","value":"Nft 3"},{"trait_type":"test/Action","value":"Nft 5"}]}
Parsing image https://www.arweave.net/ZJze2XGenx9pJsc90Y4lf2m5hLw7uaoHuqmAW1hROgE?ext=png
Name #00005 with https://arweave.net/0Rx-NhGQfkM2Oy2mF6dgYU1ps3QwJnaGSx0xOnAlMec returned non-200 from uploader 404
/Users/cedric/Dev/Crypto/metaplex/js/packages/cli/src/candy-machine-cli.ts:53
  .option(
                      ^
Error: not all NFTs checked out. check out logs above for details

```

Does your verify command works right after your upload command? Or is there a delay for arweave to make them available? 

Thanks!

**Comment by cdric** [comment]
Ok I tried again today and everything is working well now. So I'm gonna close this issue.
