### ISSUE TITLE
Minting failed! Please try again! custom program error: 0x36 

### ISSUE THREAD

**Issue by swagzhang** [metaplex-foundation/metaplex#610]
When I try to mint from candy machine this error is shown? 
![image](https://user-images.githubusercontent.com/14337160/135882532-6d49a928-3ed0-4c52-824c-e29c3f9e784c.png)

**Comment by ThreadShakur** [comment]
have the same

**Comment by lz2470** [comment]
I believe is metaplex update some new stuff one hour ago that causing it!

**Comment by dy618i5ECC** [comment]
same. anyone can fix it?

**Comment by hmzakhalid** [comment]
I had the same issue but it suddenly started working

**Comment by cdric** [comment]
Gheez. Can the metaplex just break like this if we need to us it for production scenario? This would then be worrisome won't it?
