### ISSUE TITLE
mint_one_token fails with "You cannot unilaterally verify another creator, they must sign"

### ISSUE THREAD

**Issue by penneydude** [metaplex-foundation/metaplex#611]
I used to be able to mint a token with the creator wallet, but now I'm receiving this error. Full text here (dirs and addresses redacted with ***):

`wallet public key: ***
Rejected via websocket { InstructionError: [ 4, { Custom: 54 } ] }
Timeout Error caught {
  err: { InstructionError: [ 4, [Object] ] },
  slot: 99745847,
  confirmations: 0
}
(node:2932) UnhandledPromiseRejectionWarning: Error: Transaction failed: You cannot unilaterally verify another creator, they must sign
    at /***/metaplex/js/packages/cli/src/helpers/transactions.ts:136:19
    at step (/***/metaplex/js/packages/cli/src/helpers/transactions.ts:33:23)
    at Object.next (/***/metaplex/js/packages/cli/src/helpers/transactions.ts:14:53)
    at fulfilled (/***/metaplex/js/packages/cli/src/helpers/transactions.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

It seems like this could be related to #609. Is there a new process for minting a token or is this a bug?

**Comment by penneydude** [comment]
And just to provide context, I'm attempting this from update authority wallet, which is also listed in the creators array, along with two other addresses.

**Comment by solanacryptodev** [comment]
Yes, it's failing for me too

**Comment by dy618i5ECC** [comment]
same. anyone can fix it?

**Comment by AlexLeung** [comment]
sent a DM to @bhgames on twitter. seems like an update to the candy machine contract may have introduced a breaking change

**Comment by arnaubennassar** [comment]
Same here

**Comment by AlexLeung** [comment]
Do we need to update the creators metadata to unblock this?

**Comment by AlexLeung** [comment]
I'm seeing the issue fixed by https://github.com/metaplex-foundation/metaplex/pull/614

**Comment by penneydude** [comment]
Also seeing this fixed by #614, closing
