### ISSUE TITLE
CandyMachine/Metaplex/Token program ids have changed.

### ISSUE THREAD

**Issue by uaktags** [metaplex-foundation/metaplex#612]
https://github.com/metaplex-foundation/metaplex/commit/17c2ca80e0d7ffc6892f0bc04f6dba5f2d86f88f has changed the vaults and every other program.

What are these new programs, why haven't the constants in the cli updated, etc?

@bhgames

**Comment by jordansexton** [comment]
Thanks @uaktags. My understanding is that this is fixed now?
