### ISSUE TITLE
Candy Machine Error

### ISSUE THREAD

**Issue by justinpezzack** [metaplex-foundation/metaplex#633]
saving config line 9991-10000 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: My position in vec is 9991 my mask is going to be 1, the old value is 254',
    'Program log: My new value is 255 and my position from right is 0',
    'Program log: Increasing count',
    'Program log: My position in vec is 9992 my mask is going to be 128, the old value is 0',
    'Program log: My new value is 128 and my position from right is 7',
    'Program log: Increasing count',
    'Program log: My position in vec is 9993 my mask is going to be 64, the old value is 128',
    'Program log: My new value is 192 and my position from right is 6',
    'Program log: Increasing count',
    'Program log: My position in vec is 9994 my mask is going to be 32, the old value is 192',
    'Program log: My new value is 224 and my position from right is 5',
    'Program log: Increasing count',
    'Program log: My position in vec is 9995 my mask is going to be 16, the old value is 224',
    'Program log: My new value is 240 and my position from right is 4',
    'Program log: Increasing count',
    'Program log: My position in vec is 9996 my mask is going to be 8, the old value is 240',
    'Program log: My new value is 248 and my position from right is 3',
    'Program log: Increasing count',
    'Program log: My position in vec is 9997 my mask is going to be 4, the old value is 248',
    'Program log: My new value is 252 and my position from right is 2',
    'Program log: Increasing count',
    'Program log: My position in vec is 9998 my mask is going to be 2, the old value is 252',
    'Program log: My new value is 254 and my position from right is 1',
    'Program log: Increasing count',
    'Program log: My position in vec is 9999 my mask is going to be 1, the old value is 254',
    'Program log: My new value is 255 and my position from right is 0',
    'Program log: Increasing count',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'index out of bounds: the len is 2401505 but the index is 2401505', nft-candy-machine/src/lib.rs:340:36",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
Done. Successful = false.

**Comment by justinpezzack** [comment]
Any help? Somewhat urgent

**Comment by cdric** [comment]
Can you share steps for us to reproduce your issue? For instance, what command are you running that is triggering this? Or this a log from the website? Thanks!

**Comment by justinpezzack** [comment]
@cdric sorry! In a bit of panic mode! This happens upon `metaplex upload`

**Comment by cdric** [comment]
Is this on dev? Do you have money on your wallet? Upload request 0.0023 SOL per file upload to https://www.arweave.org/. Not sure if you use a different hosting provider. (Disclaimer: I'm not part of the dev team)
