### ISSUE TITLE
Does arweave has some restriction on image size? (Like being >25Kb)

### ISSUE THREAD

**Issue by cdric** [metaplex-foundation/metaplex#635]
According to this issue (https://github.com/metaplex-foundation/metaplex/pull/584), it looks like image need to be at least 25K to be stored by arweave. 

Questions:
1) Is this true?
2) Do we know what other requirement arweave might require on file being uploaded?
3) Is there a delay from the time the candy_machine upload success and the time the asset or available online?

For more details on the candy_machine verify issue I'm running please refer to: https://github.com/metaplex-foundation/metaplex/issues/608

Note: I am doing all of this using the devenv of candymachine.

Thanks! 

```
ts-node js/packages/cli/src/candy-machine-cli.ts verify --env devnet --keypair [REDACTED}--log-level trace                           
setting the log value to: trace
wallet public key: [REDACTED}
program id from anchor [REDACTED}
Looking at key  0
Name #00001 with https://arweave.net/LQ1vWX5Vdf_OmYRL24lZ_07jdnzS-_Clqk_CX5iaPYg returned non-200 from uploader 404
Looking at key  1
Name #00002 with https://arweave.net/6GeuFwlbu6j-LKsN4yCibt89PV-VU5Wel-6eFBuzErA returned non-200 from uploader 404
Looking at key  2
Name #00003 with https://arweave.net/uyuILDkgKKjbOWBKWKnXZQS6aVfO-dYJxl95OJ6Xvno returned non-200 from uploader 404
Looking at key  3
Name #00004 with https://arweave.net/MQ9Yx-2sLuV1CT4pkQQfN4bTuI54b-DpYBiN2oKV2CA returned non-200 from uploader 404
Looking at key  4
Name #00005 with https://arweave.net/XEKBIVbrv37s0JQyH_7ip_6mt13R2O6QtbrYaowGbcY returned non-200 from uploader 404
/Users/cedric/Dev/Crypto/metaplex/js/packages/cli/src/candy-machine-cli.ts:53
  .option(
                      ^
Error: not all NFTs checked out. check out logs above for details
    at /[REDACTED}/metaplex/js/packages/cli/src/candy-machine-cli.ts:273:11
    at step (/[REDACTED}/metaplex/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/[REDACTED}/metaplex/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/[REDACTED}/metaplex/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by cdric** [comment]
Thank you @JonLMyers - Would the link stills works?
For me I get a 404 when access the URL link of my image.

Example: https://www.arweave.net/xSOYpbWJMwKkbEJgOXQxDLY1rf3gfDUkeO_yfd3ZB5o?ext=png
Do you also get 404 when your image is less than 20Kb? Or do you just get a blank image?

**Comment by rosmcmahon** [comment]
there is no size restriction on Arweave, nor does data get changed like this.
there must be a bug/limitation in either Bundlr or Metaplex software. 

edit: on further reading, I'm leaning towards an issue in Metaplex's devnet.
