### ISSUE TITLE
ARWeave Links to Metadata are broken (404 Not found/Error not all nfts checked out)

### ISSUE THREAD

**Issue by musaab27** [metaplex-foundation/metaplex#638]
Currently upload will set all my metadata to onchain: true. There are a variety of links related to the metadata stored on arweave that are broken when clicked upon. Numerous people are having this issue.

**Comment by gkiri** [comment]
+1 ,facing same issue!

**Comment by calebporzio** [comment]
+1 for the issue. Steps to reproduce:

* Installed everything fresh (ts-node, solana, metaplex)
* Created a new wallet using solana-keygen
* Airdropped 5 SOL to that wallet on the devnet
* Created an assets folder like the following:
  * `assets/0.png`, `assets/0.json`, etc...
  * Here's an example of the json in `[n].json`:
```json
{
    "name": "Test NFT #1",
    "symbol": "",
    "description": "My first test NFT",
    "seller_fee_basis_points": 5,
    "image": "0.png",
    "properties": {
        "files": [
            {
                "uri": "0.png",
                "type": "image/png"
            }
        ],
        "creators": [
            {
                "address": "...",
                "share": 100
            }
        ]
    }
}
```
* Ran `metaplex upload ./assets --env devnet --keypair ~/.config/solana/devnet.json`
* Everything looks good: (`...Done. Successful = true.`)
* I now have a `assets/.cache/devnet-temp` with arweave URLs in it
* I wait 30 minutes for arweave to do its thing
* I run: `metaplex verify --keypair ~/.config/solana/devnet.json`
* I get the following error:

```
Name Test NFT #1 with https://arweave.net/[removed for github] returned non-200 from uploader 404

[...]

Error: not all NFTs checked out. check out logs above for details
    at /Users/calebporzio/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:273:11
[...]
```

If I visit the arweave URL in my browser, I get the metadata, but if I visit the actual `?ext=png` link for the image, it's a 404 "Not Found".

Tried messing with the source JSON, reinstalling stuff, updating metaplex, etc... no dice.

Thanks for everyone's hard work on this project. Let me know if I can help on this any further!

**Comment by mirkzu74** [comment]
+1 ,facing same issue! also in MainNetBeta

**Comment by cesarLazcano** [comment]
+1, facing exact same issue

**Comment by mirkzu74** [comment]
> Not experiencing this at the moment, there is a good chance there is an issue on Arweave's end. The code for uploading to Arweave has not changed in months, nor seem to have any problems. Are your images above Arweave's limit?

now seems ok for all my previous minted NFTs, seems a Arweave's problems not connected in any way to Metaplex
and self resolved

**Comment by justinpezzack** [comment]
On further investigating this was changed 5 days ago: https://github.com/metaplex-foundation/metaplex/commit/e6caaada02d7e8e7f6a857eeee473a4ad86f155a#diff-5b93dafb7e9a301e98543fc434eadb678a1292cbac29f9396ccd671e141b1f6d

Possible that if you are uploading large enough files, the fixed value is not sufficient to store.

@bartosz-lipinski what was the motivation for this change? That amount fo SOL would be overpaying a ton for the majority of assets.

**Comment by kefalet98** [comment]
+1 for the issue.

now i'm trying to re upload everything by deleting items in the cache file. for now i can see the links but do not know how it will end, i'll cameback when process finish and inform you.

**Comment by Brueni92** [comment]
> On further investigating this was changed 5 days ago: [e6caaad#diff-5b93dafb7e9a301e98543fc434eadb678a1292cbac29f9396ccd671e141b1f6d](https://github.com/metaplex-foundation/metaplex/commit/e6caaada02d7e8e7f6a857eeee473a4ad86f155a#diff-5b93dafb7e9a301e98543fc434eadb678a1292cbac29f9396ccd671e141b1f6d)
> 
> Possible that if you are uploading large enough files, the fixed value is not sufficient to store.
> 
> @bartosz-lipinski what was the motivation for this change? That amount fo SOL would be overpaying a ton for the majority of assets.

hmm, good question, best would be a fee calculation on the go based on the asset's file size, wouldn't it?

**Comment by calebporzio** [comment]
Unfortunately, still facing the same problem.

The assets I'm uploading are 446 bytes, which would be well within the amount of SOL paid to arweave right?

**Comment by HRK44** [comment]
@calebporzio I'm noticing the same behavior, my small images (~5kb) don't display but the higher ones (300kb+) are showing on arweave. All of them say "successful upload" but the smaller ones don't show for some reason, any idea why?

**Comment by nftinkerer** [comment]
Seems like the default `example-assets` have this issue as well, so lowering that min or making them larger is probably a good idea

**Comment by HRK44** [comment]
Here's a small script I wrote to increase the png image size:

```typescript
import png from 'png-metadata';
import fs from 'fs';

const desiredSize = 32000;
const folder = './mint/';

const bumpImageSize = async (file: string) => {
    if (file.endsWith('.png')) {
        const filePath = folder + file;

        let fileSize = (await fs.promises.stat(filePath)).size;

        if (fileSize <= desiredSize) {
            console.log('bumping ' + filePath);

            // load from file
            let s = png.readFileSync(filePath);
            // split
            let list = png.splitChunk(s);
            // append
            let iend = list.pop(); // remove IEND

            const creatorString = 'Matrica Labs - Pixels NFT on Solana';
            const creatorSize = getBytes(creatorString);

            let creatorChunk = png.createChunk('aaAa', creatorString);
            list.push(creatorChunk);
            fileSize += creatorSize;

            let fillingString = 'https://matricalabs.io ';

            while (fileSize + getBytes(fillingString) <= desiredSize) {
                // const fillingSize = getBytes(fillingString);
                fillingString += 'https://matricalabs.io ';
            }

            let fillingChunk = png.createChunk('aaAb', fillingString)

            list.push(fillingChunk);
            list.push(iend);

            // join and save
            let newpng = png.joinChunk(list);
            fs.writeFileSync(filePath, newpng, 'binary');
        }
    }
}

function getBytes(string) {
    return Buffer.byteLength(string, 'utf8')
}

fs.readdirSync(folder).forEach(file => bumpImageSize(file));

```

Using this helpful package: https://www.npmjs.com/package/png-metadata

**Comment by SquidSid** [comment]
> @SquidSid Yes it fixed it for me 👍 Need to add this to all the community guides

Thanks for the answer! What would you say the ideal size should be? Right now our images are 15-17kb each, would doubling that work or should I aim for higher (what did you end up with for file sizes?)? Thanks again! 😊

**Comment by saraspaudel** [comment]
For me, 154kb worked. Please join Discord, some people are talking about workarounds.
