### ISSUE TITLE
Candy Machine Minting Non Predictable Behavior. 

### ISSUE THREAD

**Issue by hmzakhalid** [metaplex-foundation/metaplex#639]
I'm on Devnet.
I uploaded 2 NFTs and it was worked, Uploaded, Deployed and Minted Both of them without any issue.

Then I created a new Metaplex Project and a new Candy Machine and Uploaded 3 NFTs with the exact same process. The Upload was successful but when I tried to mint them, they failed. I waited 2 hours and tried to mint again and it failed. After 10 hours I tried minting again and it worked all of a sudden. I didn't  change anything and it started working for some reason. No clue how.

Last night I created a new Metaplex Project and a new Candy Machine and Uploaded 10 NFTs with the exact same process. The Upload was successful but I got the same error `Minting failed! Please try again!`. I've waited 14 hours and still get the same error and its not Minting. Can someone explain what is going on?

**Comment by hmrawal** [comment]
I am facing the same issue. Few days back I uploaded few NFTs on devnet everything went smooth.
Today I followed the exact same procedure and uploaded the iamges.
Although the files were uploaded successfully I am unable to see it on arweave.
When I click on the link it throws an error 'Not found'
