### ISSUE TITLE
how to install metaplex on windows

### ISSUE THREAD

**Issue by Sachinr2** [metaplex-foundation/metaplex#641]
unable to insall metaplex in this code on the windows

**Comment by chilitechno** [comment]
Are you running it under Windows Subsystem for Linux 2?

**Comment by uaktags** [comment]
``yarn run package:win`` to package as a .exe

If you're running from within WSL, then compile it the same last Linux with package:linuxb

**Comment by jordansexton** [comment]
Closing since questions like this are better suited for Discord where more people can see and answer them. Please ask there!
