### ISSUE TITLE
I cant create_candy_machine < custom program error: 0x139 >

### ISSUE THREAD

**Issue by judink** [metaplex-foundation/metaplex#643]
I succeeded in uploading 2,000 nfts but failed when I did create_candy_machine  
with (ts-node js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env mainnet-beta --keypair ~/.config/solana/mainnet-test.json --price 0.1). 
Please help me.
////////////////////////

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20320 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (C:\Users\judink\Desktop\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\Users\judink\Desktop\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (C:\Users\judink\Desktop\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\judink\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\judink\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20320 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
(node:20328) UnhandledPromiseRejectionWarning: Error:
    at Function.parse (C:\Users\judink\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (C:\Users\judink\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kkwl777** [comment]
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20320 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139

Same error with  20320 of 200000 compute units. Not sure what determines the amount though, I've seen others get 0x139 with different units

**Comment by Happyprince65** [comment]
I am having the same error. Did you find any solution?

**Comment by Happyprince65** [comment]
> Same error. Does anybody now a solution for this?

not perfectly but there must be some issue in config files. run verify command multiple times. we you get a error on any file. remove its like from config and onchain to false. it will upload those files again. then run verify again untill it says ready to deploy . ]

**Comment by avalanx** [comment]
> > Same error. Does anybody now a solution for this?
> 
> not perfectly but there must be some issue in config files. run verify command multiple times. we you get a error on any file. remove its like from config and onchain to false. it will upload those files again. then run verify again untill it says ready to deploy . ]

verify somehow simply doesn't work for me, I am getting an error all the time.
But I found a solution that fixed everything for me so that i could simply run _metaplex create_candy_machine_ 
without any errors.

I openend the temp file in the .cache folder and changed all "onChain":true to "onChain":false, then I ran _metaplex upload_ again. all files were indexed again, this took some time, but after that _metaplex create_candy_machine_  worked without any errors.

**Comment by avalanx** [comment]
> > I had the exact same problem. What I did was, i opened temp file in .cache folder and change all "onChain":true to "onChain":false. then i ran metaplex upload again. now it is updating all indexes, which takes some time. After that the error with create_candy_machine was gone. I did a lot of searching about this error, and only found threads with questions, but no answers. so i tried until i found smthng. so plz, if you find a solution, post it. that saves others so much time. thx.
> 
> so this solved your problem right? now there is no error?

sorry that this did not come out more clearly. Yes, i immediately did metaplex create_candy_machine after that, and it worked without any error. did you try? do you still have errors?

**Comment by loosebucks** [comment]
sorry i'm a beginner, what are you inputting to run metaplex again after changing all of the onChains to false?

**Comment by avalanx** [comment]
hi. exactly the same metaplex command that you have run before. for me that was: metaplex upload ./assets --env mainnet-beta -k ~/.config/solana/mainnet.json
