### ISSUE TITLE
Failure to Reclaim NFT from Secondary Marketplace

### ISSUE THREAD

**Issue by CompendiumFi** [metaplex-foundation/metaplex#645]
Several users are experiencing the inability to reclaim an "Instant Sale" NFT from the Secondary marketplace tab.

Need to add function for reclaiming item manually upon failure to sell when listed as "Instant Sale" or their NFT's will be stuck forever. There is no set "end time" for Instant Sale transactions like other auction-based sales.

**Comment by ncarrara** [comment]
Experiencing the same kind of issue. I have mint NFT with a candy machine. When selling them in the store as a secondary sale, the user buying them won't get receive them in his wallet, even after a claim. Wondering if instant is production-ready.
