### ISSUE TITLE
TypeError: Cannot read property 'data' of null - metaplex upload on Testnet

### ISSUE THREAD

**Issue by tjs9731** [metaplex-foundation/metaplex#650]
When trying to upload my assets onto the test net, I receive this error

![image](https://user-images.githubusercontent.com/91381727/136282411-168e7bff-67b3-450b-9212-d49a598febdd.png)

It's working absolutely fine on the devnet.

**Comment by dev-1iam** [comment]
Also seeing this. Anyone have an update?

**Comment by dev-1iam** [comment]
It looks like the program is only live on devnet and mainnet-beta. Can see that the program is not executable on the explorer: https://explorer.solana.com/address/cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ?cluster=testnet

**Comment by PabloHirsh** [comment]
Got the same issue on testnet and mainnet, but it works on devnet.
