### ISSUE TITLE
Can only initialize store on devnet

### ISSUE THREAD

**Issue by VAdemiju** [metaplex-foundation/metaplex#651]
I tried initializing the store and it kept giving the failed to initialize store on all clusters except devnet

**Comment by Arrowana** [comment]
Do you have SOL in the wallet? It worked for me with master + mainnet-beta

**Comment by jordansexton** [comment]
Thanks @Arrowana. Closing as this is likely due to lack of funds in the wallet. Please let me know if that doesn't fix the issue @VAdemiju.
