### ISSUE TITLE
Dynamic Royalty Split post Minting

### ISSUE THREAD

**Issue by anvitmangal** [metaplex-foundation/metaplex#654]
After an NFT is minted, I can split the royalties every time the NFT is sold in the secondary market, between 2 entities: Sellers and Creators by specifying `seller_fee_basis_points` and `creators.share`. But what if: I want to split the royalties with the minters as well, ie a 3 way split. 

My idea was to add the minter as a dummy creator in NFT metadata. But how do we change the NFT metadata after the NFT is minted? Does any one have any clues as to how this can be done or any workarounds?

**Comment by anvitmangal** [comment]
@israelidanny Understood. To summarise there are two concerns connected to this:
1. What kind of security threats I can face if `is_mutable=true`?
2. Is there a security threat of adding a non-creator (in this case the minter) as a creator, even if I keep `verified=false`?

**Comment by emersonthis** [comment]
1. My understanding is that "ownership" of the metadata and the (NFT) token are actually separate. So a classic NFT sale would normally transfer ownership of the token, but not the rights to change the metadata (although you could transfer both). The `is_mutable` property allows the `updateAuthority` address to edit the metadata. In other words, it means the original creator can still update the metadata. Therefore, as long as you are not transferring the metadata, this should not be a security threat.

2. The verification of creators is not a security matter. It's more about authenticity. If you want to "prove" that the additional creator actually made the NFT, that creator signs it to affirm they actually did. Anyone can add any address as a creator, but the creator is the only one who can change the corresponding verification value to `true`.
