### ISSUE TITLE
Store is not initialized yet

### ISSUE THREAD

**Issue by lionft** [metaplex-foundation/metaplex#658]
Hi i have that problem ,Store is not initialized yet even if i click on initiailze and trasaction popup on my wallet .
please He
![ph](https://user-images.githubusercontent.com/91878137/136437503-110dc4c6-0e24-4847-add8-4d8b760c5a6d.PNG)
lp

**Comment by jordansexton** [comment]
Closing as there isn't enough information here to determine a cause. If you haven't resolved the issue, please provide more details.
