### ISSUE TITLE
[Error: Allocate space for the account] for Instant sale for 1000+ copies

### ISSUE THREAD

**Issue by myyellowshoe** [metaplex-foundation/metaplex#671]
Getting an error when creating an Instant Sale

`Caught failure Error: Transaction failed: Allocate space for the account.`
Which seams to be coming from this line in the rust program.
https://github.com/metaplex-foundation/metaplex/blob/f6e6a7b7767f18824950326fba20b59872f2a2e2/rust/metaplex/program/src/utils.rs#L242

I'm guessing I'm hitting a memory limit of some kind? Lower amounts seam to work fine. < 100

**Comment by VadimGrozinok** [comment]
The same issue as this one #885 
Suppose we can close this and work on #885
