### ISSUE TITLE
Own Candy Machine

### ISSUE THREAD

**Issue by volodymyrhudyma** [metaplex-foundation/metaplex#679]
Hey,

I managed to deploy my own candy machine (with some extra logic added), got a `programId`, but for some reason when I replace `CANDY_MACHINE_PROGRAM_ID` in the metaplex, it throws an error while trying to upload assets:

```
(node:1332408) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of null
    at Function.fetchIdl (/home/Projects/metaplex-fork/js/node_modules/@project-serum/anchor/src/program/index.ts:311:51)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Could you please advice how to connect custom candy machine properly?

The main purpose is to be able to see the changes done in `/rust/nft-candy-machine/src/lib.rs`.

**Comment by uaktags** [comment]
You need to let anchor know about the idl that's what's missing

FetchIDL searches anchor for the idl and then helps it to know it.

It was a pita for me to figure that one out but I'll look tomorrow to find the steps I took to deploy my own.

If I don't update by the time you see this (some time tomorrow or later) please ping me.

**Comment by volodymyrhudyma** [comment]
@uaktags Thanks for providing the direction, I was missing idl :)

`anchor idl init -f target/idl/nft_candy_machine.json <YOUR_PROGRAM_ID>` did the trick
