### ISSUE TITLE
Metaplex Upload - RangeError: encoding overruns Buffer

### ISSUE THREAD

**Issue by lisncruhs** [metaplex-foundation/metaplex#680]
Arweave upload appears complete (all images and json files are accessible on arweave) but metaplex upload starts looping through this. Any ideas?

>Writing indices 0-9
>Writing indices 1000-1009
>Writing indices 2000-2009
>Writing indices 3000-3009
>Writing indices 4000-4009
>Writing indices 5000-5009
>Writing indices 6000-6009
>Writing indices 7000-7009
Writing indices 8000-8009
Writing indices 9000-9009
saving config line 0-9 failed RangeError: encoding overruns Buffer
    at Blob.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:2334:13)
    at Structure.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1272:26)
    at WrappedLayout.encode (/snapshot/js/node_modules/@project-serum/borsh/dist/lib/index.js:65:28)
    at WrappedLayout.encode (/snapshot/js/node_modules/@project-serum/borsh/dist/lib/index.js:65:28)
    at Structure.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1272:26)
    at /snapshot/js/node_modules/buffer-layout/lib/Layout.js:1117:25
    at Array.reduce (<anonymous>)
    at Sequence.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1116:22)
    at Structure.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1272:26)
    at WrappedLayout.encode (/snapshot/js/node_modules/@project-serum/borsh/dist/lib/index.js:65:28)
Done. Successful = false.
upload was not successful, rerunning

**Comment by z3000z3000z3000** [comment]
Same for me. always on devnet with size > 10

**Comment by z3000z3000z3000** [comment]
add some debug
![Screenshot from 2021-10-11 01-35-59](https://user-images.githubusercontent.com/43447817/136715114-2acce143-28d9-41c3-93d2-2a8b679d82e3.png)
![Screenshot from 2021-10-11 01-35-50](https://user-images.githubusercontent.com/43447817/136715116-90b13b40-fd08-46c1-ab38-000462b8b254.png)

**Comment by jakewhiteley** [comment]
Same here.

Any collection > 10 fails due to the above error.

Running on windows 64bit, up to date metaplex repo.

**Comment by richardan90** [comment]
I have the same issue. I hope they fix it soon

**Comment by summerplaybook** [comment]
any solutions?

**Comment by lisncruhs** [comment]
Hey @summerplaybook, @richardan90 @jakewhiteley @z3000z3000z3000, I got this to work in the end. The issue was that the "name" item in my JSON files was too long. There are limits on the fields which were not documented anywhere at the time of posting this.

As the upload had already completed (and the 16+ SOL used), I just opened my cache file in the candymachine cli folder and did a 'find and replace' to shorten the 'name' to <20 chars. I then ran the metaplex upload command again and it finished successfully. It didn't have to re-upload the files, it just skipped to the indices etc.

The 'metaplex verify' command then failed (likely as a result of doing the above), but I did some manual spot-checks on the cache file to confirm that arweave links were in there and working/correct. After that, I just went on to running the 'metaplex create_candy_machine' command and everything worked out fine (the mint worked, holders are able to transfer, selling on Magic Eden etc.).

Good luck and flick me a NFT if you're feeling generous: E4xSsHxatwJU8832ZLy5LMwAdJhRCivG5cJf8U7E7HJh

**Comment by summerplaybook** [comment]
@lisncruhs you totally saved me on this and will do once I get this up - running into this now if you've seen it! https://github.com/metaplex-foundation/metaplex/issues/1293

**Comment by lisncruhs** [comment]
> @lisncruhs you totally saved me on this and will do once I get this up - running into this now if you've seen it! #1293

Glad to hear it! Sorry, haven’t encountered that issue.

**Comment by 0xnimi** [comment]
this issue still remains for candy machine v2, please fix, thanks!

**Comment by metaballix** [comment]
issue persists
