### ISSUE TITLE
parsing metadata of nft

### ISSUE THREAD

**Issue by easydeveloppement** [metaplex-foundation/metaplex#685]
Hello,
i'm trying to get NFT list, and then decode metadata to display them.
I followed this : https://nippycodes.com/coding/get-metadata-from-metaplex/
I have the following error when i try to parse the metadata (this error is in borsh file index) : 
TypeError: reader[capitalizeFirstLetter(...)] is not a function, thrown on this line of borsh : 
if (typeof fieldType === 'string') {
			return reader[`read${capitalizeFirstLetter(fieldType)}`]();
        }

the filedType is pubkeyAsString

any one have an idea about this problem ?!

**Comment by easydeveloppement** [comment]
i found my solution, i was doing it outside of metaplex, i just used metaplex js files
the solution was that this method (pubkeyAsString) is implemented by metaplex, so you have to add it to the prototype of borsh like metaplex does

**Comment by roccomuso** [comment]
correct,
that's what is needed in the prototype in order to make it work: https://gist.github.com/dvcrn/c099c9b5a095ffe4ddb6481c22cde5f4#file-metadata-ts-L29-L40
