### ISSUE TITLE
0x66 error

### ISSUE THREAD

**Issue by tkddlf0717** [metaplex-foundation/metaplex#699]
Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x66
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 4274 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x66
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66
    at Connection.sendEncodedTransaction (C:\Users\psi\Desktop\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\Users\psi\Desktop\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (C:\Users\psi\Desktop\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\psi\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as initializeConfig] (C:\Users\psi\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x66',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 4274 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x66'
  ]
}
Error deploying config to Solana network. ProgramError: 
    at Function.parse (C:\Users\psi\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\error.ts:36:14)
    at Object.rpc [as initializeConfig] (C:\Users\psi\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42) 
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 102,
  msg: 'The program could not deserialize the given instruction'
}
(node:22232) UnhandledPromiseRejectionWarning: Error:
    at Function.parse (C:\Users\psi\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\error.ts:36:14)
    at Object.rpc [as initializeConfig] (C:\Users\psi\Desktop\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42) 
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)       
(node:22232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

--------

Anyone unable to proceed due to this error?

I want to seek help. ty

**Comment by chancetalkington** [comment]
I also had the same problem and the issue is with your metadata.  I used the repo https://github.com/0xEnrico/arweave-nft-uploader#arweave-nft-uploader and copied the template.json and it worked.  Hope this helps some other folks like me.

**Comment by heymarye** [comment]
> I also had the same problem and the issue is with your metadata. I used the repo https://github.com/0xEnrico/arweave-nft-uploader#arweave-nft-uploader and copied the template.json and it worked. Hope this helps some other folks like me.

Hey! What did you mean by "copied template.json"?

**Comment by emersonthis** [comment]
Adding the "symbol" key solved the issue for me, too

**Comment by piscespieces** [comment]
Adding the "symbol" key also worked for me:

I had prev issues before running into this one, so I'll share how the `1.json` should look like to get it to work:

```
{
  "name": "Simple NFT #2",
  "image": "1.png",
  "symbol": "",
  "properties": {
    "creators": [
        {
          "address": "9JrSfn4oUafRfBn9u8LVBan9wQVNn9gg2yKVF8aHyenZ",
          "share": 100
        }
    ],
    "files": [
      {
        "uri": "1.png",
        "type": "image/png"
      }
    ]
  }
}
```

**Comment by pavel-leonenko** [comment]
I've just encountered the same issue when I had a too long symbol, more than 10 characters in it.

**Comment by nonfriendlytypes** [comment]
> 

Having the same issue, did u solve it?

**Comment by samuelvanderwaal** [comment]
> > 
> 
> Having the same issue, did u solve it?

This is often caused by a badly formatted JSON file. Check that your JSON file has all the required fields and doesn't exceed any of the length limits for them: https://hackmd.io/@archaeopteryx/By4bpbA4F#General-CM-CLI-Troubleshooting.

**Comment by Theo4** [comment]
Same problem here, but I'm having an "ESC" Symbol for every Nfts so 3 chars should be ok..

**Comment by nypam** [comment]
You can also get this error if you miss one parameter for the **CM V2**

[Minimal parameters for CM V2](https://docs.metaplex.com/candy-machine-v2/configuration#minimal-configuration)

`{
    "price": 1.0,
    "number": 10,
    "gatekeeper": null,
    "solTreasuryAccount": "<YOUR WALLET ADDRESS>",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "25 Dec 2021 00:00:00 GMT",
    "endSettings": null,
    "whitelistMintSettings": null,
    "hiddenSettings": null,
    "storage": "arweave-sol",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}`

**Comment by xapeslab** [comment]
> You can also get this error if you miss one parameter for the **CM V2**
> 
> [Minimal parameters for CM V2](https://docs.metaplex.com/candy-machine-v2/configuration#minimal-configuration)
> 
> ```json
> {
>     "price": 1.0,
>     "number": 10,
>     "gatekeeper": null,
>     "solTreasuryAccount": "<YOUR WALLET ADDRESS>",
>     "splTokenAccount": null,
>     "splToken": null,
>     "goLiveDate": "25 Dec 2021 00:00:00 GMT",
>     "endSettings": null,
>     "whitelistMintSettings": null,
>     "hiddenSettings": null,
>     "storage": "arweave-sol",
>     "ipfsInfuraProjectId": null,
>     "ipfsInfuraSecret": null,
>     "awsS3Bucket": null,
>     "noRetainAuthority": false,
>     "noMutable": false
> }
> ```

thank you so much bro I spent almost 5-6 hours thought its issue in the generated json file but realised the issue after checking this....

**Comment by alexgidge** [comment]
I had this error due to missing values in my CandyMachine config.json
I deleted "hiddenSettings" instead of having the value as null - I believe this will happen if you miss any required values for CandyMachine v2 CLI

**Comment by Zaryab-Programmer** [comment]
After a lot of struggle, I resolved the issue and came to the point, Kindly complete the config.js file.
Follow this configuration each and every step: https://docs.metaplex.com/candy-machine-v2/configuration
Thanks
