### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by YogaaDev** [metaplex-foundation/metaplex#700]
Hi, I'm looking to do a whitelist, everybody have an idea ? thanks

**Comment by YogaaDev** [comment]
Ok, if i use this function : https://github.com/BertrandBev/metaplex/blob/update-nft-metadata/js/packages/cli/src/cli-nft.ts

I can update metadata to a "base58 mint key" ? I think this base58 is the address of the owner of the nft ?

**Comment by uaktags** [comment]
You would need to update the CandyMachines SOL code which is written in Rust and then redeploy it as your own. Unfortunately CandyMachine doesn't have a whitelist.

**Comment by uaktags** [comment]
Sounds good, just know and understand the limitations of such an implementation.

**Comment by Yuriy-Ihor** [comment]
Hey guys, I have to implement whitelist as well.
But I'd like to store my whitelist somewhere on my server. My idea is to store somewhere in candy-machine URL to json file, which will contain all pubkeys. And then, when user mints NFT, program will asynchronously load that list and check if user exists there. Is it ok solution?
