### ISSUE TITLE
yarn build issue 

### ISSUE THREAD

**Issue by AVieraUY** [metaplex-foundation/metaplex#717]
**Describe the bug**
When running `yarn build` command after `yarn install` it throws an error

**To Reproduce**
> yarn build
yarn run v1.22.11
$ tsc -p ./src
src/helpers/upload/arweave.ts:62:31 - error TS2339: Property 'messages' does not exist on type 'unknown'.

62   const metadataFile = result.messages?.find(
                                 ~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

node --version
v14.18.0

npm --version
6.14.15

yarn --version
1.22.11

**Comment by jvierauy** [comment]
MacOS Big Sur 11.5.2 Intel

**Comment by jvierauy** [comment]
Problem solved..
In the file src/helpers/upload/arweave.ts I put 
`const metadataFile = (result as any)`
instead of 
`const metadataFile = result`
