### ISSUE TITLE
Cannot Read Property Program of Undefined

### ISSUE THREAD

**Issue by solanacryptodev** [metaplex-foundation/metaplex#730]
**Describe the bug**
I came across this error before when trying to run a devnet temp file when my config was set to mainnet-beta...but when I ran the upload command successfully, my config was set to mainnet-beta, so now I'm wondering why I'm getting this error message regarding..

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'program' of undefined

I gave my .cache file a cacheName of "giveaway," but even when I run the command to verify the uploaded NFTs on Mainnet, I still get the above error message. I'm not sure what is causing this specifically as this command worked a couple days ago. The only thing I did now that I don't normally do is create my own cache name.

**Expected behavior**
I should be able to run this command and verify my NFTs. I get the same error as above when when I run create_candy_machine, so nothing is working. This is what I'm running in the CLI...

node build/candy-machine-cli.js verify -e "mainnet-beta" -k ./wallet/wallet.json -l trace -c "giveaway"

I was successfully able to upload to Mainnet-beta and Arweave. The .cache file says onChain: true for all 50 and every Arweave link I pull up works. I updated my repo to the most recent version of Metaplex and I'm wondering if something was changed that might have broken something because this wasn't happening a couple days ago.

**Screenshots**
<img width="2004" alt="cm error 3" src="https://user-images.githubusercontent.com/52287356/137398880-1f18f9a2-ed9e-43e7-b7f5-393e4fe357b1.png">

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by Vince-vegas** [comment]
![Untitled](https://user-images.githubusercontent.com/55544488/138001246-03e5d3e6-b330-413c-9a62-1fadea3bd396.png)

Did you solve that in nft
