### ISSUE TITLE
Metadata update fail if update authority is not in the creators array

### ISSUE THREAD

**Issue by HuchotP** [metaplex-foundation/metaplex#734]
**Describe the bug**
When updating metadata, the updateAuthority address must be in the new creator array even if it was not originally included.

Is this a bug or a feature ?

**To Reproduce**
1. Set up a candy machine
2. Do not include the update authority in the array of creators
3. Mint an NFT
4. Try to update metadata
5. See error : "If using a creators array, you must be one of the creators listed"

You can still update metadata, but you have to include the update authority in the new creators array.

**Expected behavior**
If this behavior is not intended, you should be able to update a token metadata without including the update authority in the creator array.

**Comment by MuskanBartaula** [comment]
How are you updating the metadata? Can you share the instruction?

**Comment by blockchainlover2019** [comment]
Hey, @HuchotP!
How can I use 'updateMetadata' and 'sendTransactionWithRetryWithKeypair'?
Did you import all code of metaplex?
I used '@metaplex/js' and this is my code.
`
import { programs } from '@metaplex/js';
export const updateMetadataV1 = async () => {
  let { metadata : {Metadata, UpdateMetadata, MetadataDataData, Creator} } = programs;
  let signer = loadWalletKey(keyfile);
  let nftMintAccount = new PublicKey("my mint key");
  let metadataAccount = await Metadata.getPDA(nftMintAccount);
  const metadat = await Metadata.load(solConnection, metadataAccount);
  let newUri = "https://arweave.net/my arweave address";
  if (metadat.data.data.creators != null) {
    const creators = metadat.data.data.creators.map(
      (el) =>
          new Creator({
              ...el,
          }),
    );
    let newMetadataData = new MetadataDataData({
      name: metadat.data.data.name,
      symbol: metadat.data.data.symbol,
      uri: newUri,
      creators: [...creators],
      sellerFeeBasisPoints: metadat.data.data.sellerFeeBasisPoints,
    })
    const updateTx = new UpdateMetadata(
      { feePayer: signer.publicKey },
      {
        metadata: metadataAccount,
        updateAuthority: signer.publicKey,
        metadataData: newMetadataData,
        newUpdateAuthority: signer.publicKey,
        primarySaleHappened: metadat.data.primarySaleHappened,
      },
    );
    let result = await sendAndConfirmTransaction(solConnection, updateTx, [signer]);
    console.log("result =", result);
  }
}
`
But, I have some problem.
The transaction result has no error, it means transaction success.
But the metadata doesn't chage. What's the matter?

**Comment by AlexLup06** [comment]
> Hey, @HuchotP How can I use 'updateMetadata' and 'sendTransactionWithRetryWithKeypair'? Did you import all code of metaplex? I used '@metaplex/js' and this is my code.
> 
> ```
> import { programs } from '@metaplex/js';
> 
> export const updateMetadataV1 = async () => {
>   let { metadata : {Metadata, UpdateMetadata, MetadataDataData, Creator} } = programs;
>   let signer = loadWalletKey(keyfile);
>   let nftMintAccount = new PublicKey("my mint key");
>   let metadataAccount = await Metadata.getPDA(nftMintAccount);
>   const metadat = await Metadata.load(solConnection, metadataAccount);
>   let newUri = "https://arweave.net/my arweave address";
>   if (metadat.data.data.creators != null) {
>     const creators = metadat.data.data.creators.map(
>       (el) =>
>           new Creator({
>               ...el,
>           }),
>     );
>     let newMetadataData = new MetadataDataData({
>       name: metadat.data.data.name,
>       symbol: metadat.data.data.symbol,
>       uri: newUri,
>       creators: [...creators],
>       sellerFeeBasisPoints: metadat.data.data.sellerFeeBasisPoints,
>     })
>     const updateTx = new UpdateMetadata(
>       { feePayer: signer.publicKey },
>       {
>         metadata: metadataAccount,
>         updateAuthority: signer.publicKey,
>         metadataData: newMetadataData,
>         newUpdateAuthority: signer.publicKey,
>         primarySaleHappened: metadat.data.primarySaleHappened,
>       },
>     );
>     let result = await sendAndConfirmTransaction(solConnection, updateTx, [signer]);
>     console.log("result =", result);
>   }
> }
> ```
> 
> But, I have some problem. The transaction result has no error, it means transaction success. I checked it on Solana Explorer. But the metadata doesn't change. What's the matter?

where did you get the `sendAndConfirmTransaction` function from?

**Comment by blockchainlover2019** [comment]
```import { sendAndConfirmTransaction } from '@solana/web3.js';```
sendAndConfirmTransaction is from @solana/web3.js

**Comment by JoshuaPerk** [comment]
Where does the function `loadWalletKey()` come from?

**Comment by JoshuaPerk** [comment]
> Where does the function `loadWalletKey()` come from?

[Found it](https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/helpers/accounts.ts)
