### ISSUE TITLE
Error while uploading images

### ISSUE THREAD

**Issue by elonplant** [metaplex-foundation/metaplex#736]
I USED THIS COMMAND TO UPLOAD IMAGES
PS C:\Windows\system32\metaplex> ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair ~/.config/solana/mainnet-beta.json
Beginning the upload for 2 (png+json) pairs
started at: 1634298990119
wallet public key: C4PoqpcGaG916Mi9RVQzHLLzknrkKpg4pJT6EFCX5CYp
Processing file: 0
initializing config
Error deploying config to Solana network. TypeError: Cannot read properties of undefined (reading 'map')
    at Object.<anonymous> (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:104:52)
    at step (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:44:23)
    at Object.next (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:25:53)
    at fulfilled (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:104
            creators: manifest.properties.creators.map(creator => {
                                                   ^
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.<anonymous> (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:104:52)
    at step (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:44:23)
    at Object.next (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:25:53)
    at fulfilled (C:\Windows\system32\metaplex\js\packages\cli\src\commands\upload.ts:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
GOT THIS ERROR
If anybody can help it will be awesome!

**Comment by jscrui** [comment]
Same here... cannot figure out.

**Comment by Mamu9** [comment]
Getting the same error with sample "simple-collection run. My jason are very simple. Is it something to do with the arweave?

**Comment by Mamu9** [comment]
{
  "name": "Simple NFT #2",
  "image": "1.png",
  "properties": {
    "files": [
      {
        "uri": "1.png",
        "type": "image/png"
      }
    ]
  }
}

**Comment by adilanchian** [comment]
If you look in the `upload.ts` file they are referencing - there is `createConfig` that is getting called:

```javascript
const res = await createConfig(anchorProgram, walletKeyPair, {
            maxNumberOfLines: new BN(totalNFTs),
            symbol: manifest.symbol,
            sellerFeeBasisPoints: manifest.seller_fee_basis_points,
            isMutable: mutable,
            maxSupply: new BN(0),
            retainAuthority: retainAuthority,
            creators: manifest.properties.creators.map(creator => {
              return {
                address: new PublicKey(creator.address),
                verified: true,
                share: creator.share,
              };
            }),
          });
```

If you look at this line specifically `manifest.properties.creators.map` it looks like it's trying to access the `creators` property in the `properties` object. So this is where it's breaking - BUT the bigger issue here is in the intro instructions they don't say anything about this being a requirement :)

So at the very least that should be updated.

**Comment by adilanchian** [comment]
You'll probably run into another issue that looks something like this - 

`Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66`

Looks like the `symbol` property is also required 😅. That fixed this for me!
