### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript: (ARWEAVE.TS LINE 60)

### ISSUE THREAD

**Issue by ezpzzz19** [metaplex-foundation/metaplex#742]
When I run this command from Windows Command  prompt: 

**ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair C:\Users\etrem\solana\SolanaWallet\my-solana-wallet\my-keypair.json**

I get this follow error : 

TSError: ⨯ Unable to compile TypeScript:
js/packages/cli/src/helpers/upload/arweave.ts:62:31 - error TS2339: Property 'messages' does not exist on type 'unknown'.

62   const metadataFile = result.messages?.find(

I downloaded typewriter, ts-node and yarn. I do not understand why I get this. 

Thank you for your help

**Comment by Jaecobd1** [comment]
Find an answer?

**Comment by qleguennec** [comment]
I got the same issue.
