### ISSUE TITLE
Arweawe returned non-200 from uploader 404

### ISSUE THREAD

**Issue by Enz000** [metaplex-foundation/metaplex#754]
**Describe the bug**
Some picture returned the this error : returned non-200 from uploader 404
When i check online, some are not avalaible '404 not found'
**To Reproduce**
1. Run verify command

**Screenshots**

![Capture](https://user-images.githubusercontent.com/62953579/137763628-beb0d241-ea91-4f74-95e3-c620c5076127.PNG)

**Desktop (please complete the following information):**
win

**Additional context**

**Comment by yurenji** [comment]
+1 same issue here

**Comment by zkhalapyan** [comment]
Have this issue as well; seems like when you call verify, it ends up setting link properties in the .cache file to null. Verification steps should not be mutating the cache file.
