### ISSUE TITLE
Add a per-wallet limit to the Metaplex Candy Machine

### ISSUE THREAD

**Issue by MellenIO** [metaplex-foundation/metaplex#756]
**Is your feature request related to a problem? Please describe.**
A lot of projects recently have gotten rekt (eg: Drippy Penguins) by the fact that Metaplex has no on-chain limitation per wallet. If a frontend says "you may only mint 3", a sneaky individual can simply mint more directly on-chain. In the case of Drippy Penguins, a single bot minted approx. 500 NFTs!

**Describe the solution you'd like**
Add an optional `--limit-per-wallet` option to the create/update commands for Candy Machine. When the `mint_nft` function is called, check if the wallet in question has already minted more than the configurable limit. If so, deny the request.
The option should be **optional**, with a default value of 0 (for no limit).

**Describe alternatives you've considered**
You can achieve this on your frontend, but again this only prevents people who are already playing the game fairly.

**Additional context**
I was planning to implement this myself but I'm not a Rust developer so wasn't able to get anything reasonable sorted out. I _think_ this can be achieved by adding a `BTreeMap<Pubkey>` to the candy machine data, and simply incrementing & checking it during the `mint_nft` function.

**Comment by timashov** [comment]
Any updates on this? Still no limits per wallet?

**Comment by aheckmann** [comment]
Correct, no limits per wallet because it does not help prevent bot activity. However, we have other very promising solutions in the works. Stay tuned.
