### ISSUE TITLE
Status 429 message when using IPFS

### ISSUE THREAD

**Issue by DevMarcosss** [metaplex-foundation/metaplex#760]
Hello, I am getting error 429 when trying to upload to IPFS.
after a few upload, it sends the following error;

![Screenshot_3](https://user-images.githubusercontent.com/56926590/137927855-f4ac7221-db46-4fc1-b905-61daf3632f33.png)

I use this command;
`metaplex upload ./assets --env "devnet" --keypair "keypair" --log-level "debug" --number "10" --storage "ipfs" --ipfs-infura-project-id $ipfsprojectid --ipfs-infura-secret $ipfssecret`

I allowed my own ip address and http user-agent from my infurna account.
btw I even though use ipfs i see the upload cost is the same like Arweave.

Please help me with this. I want to upload to ipfs by reducing the upload cost.

**Comment by dvdlevy** [comment]
any feedback on this? same issues

**Comment by tjs9731** [comment]
~/metaplex/js/packages/cli/src/helpers/upload/ipfs.ts

Line 62 - change the sleep function from 500 to 10000 (10 seconds)

**Comment by FaisalAli19** [comment]
Thanks that works for me
