### ISSUE TITLE
Images and icons are not shown after deploying to github pages.

### ISSUE THREAD

**Issue by osielmesa** [metaplex-foundation/metaplex#765]
**Describe the bug**
I follow step by step guide of how to deploy store to gh pages, everything went perfect but the only problems is I cannot see any icon and 404 error code is triggered for all of them

**To Reproduce**
1. Deploy totally new project of the store to github pages

**Expected behavior**
All icons should be visible. All paths should be ok and do not produce 404 error.

**Comment by rolandstudios** [comment]
getting same issue

**Comment by ck256-2000** [comment]
months on this issue- this should be re-opened or the docs need to state that the package is only available to put on its own top level site.  

Another work around is to take the public files and drop them into the root folder.  gets messy fast, but it works.  

Again - just clearly state capabilities so we can follow along and not waste hours -
