### ISSUE TITLE
How to find candy machines configs (allocated space) ids funded by a specific wallet address?

### ISSUE THREAD

**Issue by kevinfaveri** [metaplex-foundation/metaplex#774]
**Is your feature request related to a problem? Please describe.**
The problem is simple: people are setting up their candy machines, and somehow deleting their cache files, thus losing the reference to their Candy Machine Config address (which is where the config lines are written). So, a ton of people are losing money, and this matters. Despite we having a ton of whales on Solana, most small projects can't afford to lose 10 SOL.

**Describe the solution you'd like**
I think we could have a feature on the Cli for getting Candy Machine Addresses that have been funded by the wallet connected to the Solana CLI

Also, a workaround for now would be a possible filter (I can't think of any but...) for filtering by the authority who funded the Candy Machine Config ID

**Comment by elcarosol** [comment]
Solution: Deploy all your assets on following the dev-net candy deploy instructions, then copy the config after the upload is completed to your main-net deployment and deploy your machine. 

Alternatively, upload directly with arweave and save yourself 30 sol from using metaplexs wallet/faucet.

@imnotelcaro if you have any specific questions.

**Comment by paulinhoAlmeida** [comment]
> Found a good way to do this using a filter: https://twitter.com/aiphotos_/status/1451733014204014592 !

this only works for the mainnet, what about the devnet
