### ISSUE TITLE
error timestamp : NaN (22)

### ISSUE THREAD

**Issue by tounstounsi** [metaplex-foundation/metaplex#780]
Hello, 

I have launch the command npx ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair ~/config/solana/monster.json --price 0.001 --date "22 Oct 2021 17:00:00 GMT"

and i have this 
wallet public key: FuzoJ8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 - updated startDate timestamp: NaN (22)
 - updated price: 1000000 lamports (0.001 SOL)
update_candy_machine finished 254EdFSLhETLvH3K8i4kZghKxxxxxxxxxxxxxxxxxxxxxxxxxxxx

The startDate can't be updated, it's null
Can you help me please ?

**Comment by LadsNFT** [comment]
> I had this same issue, when I pass the date the code doesn't read it fully, just the first digits of the day.
> 
> What I did is I went to candy-machine-cli.ts , line ~605, where we get the command opts. and called a new string variable of the date I want, and noticed that it works.
> 
> So the problem isn't in the parsing but when reading the command arguments (I use : Windows 10)

could you help me?
