### ISSUE TITLE
Store address not displayed

### ISSUE THREAD

**Issue by epomatti** [metaplex-foundation/metaplex#782]
**Describe the bug**

After initiating the store it doesn't display the store address.

As per documentation:

![image](https://user-images.githubusercontent.com/6530769/138543294-f361df66-ccd4-4645-9536-06961e59ebe9.png)

What I get:

![image](https://user-images.githubusercontent.com/6530769/138543279-36b6dd26-00e7-4498-b29e-9eaeb42311ed.png)

**To Reproduce**

https://docs.metaplex.com/create-store/init-store

**Expected behavior**
Should display the store address.

**Desktop (please complete the following information):**
 - OS: Windows 10 + WSL Ubuntu 20
 - Browser: Chrome
 - Version 95.0.4638.54

**Comment by Do0dle** [comment]
I have the save problem, did you find a fix?

**Comment by epomatti** [comment]
@Do0dle not yet.

**Comment by Carlosru** [comment]
is there a way to recover the REACT_STORE_OWNER_ADDRESS_ADDRESS to configure .env?
