### ISSUE TITLE
Deploying CandyMachine required sending funds and now they are stuck - how to recover?

### ISSUE THREAD

**Issue by dannydeezy** [metaplex-foundation/metaplex#790]
I deployed a candymachine contract a few weeks back and it was requiring that i attach a balance of 14 SOL. I figured this was to pay for fees on the minting or something, but apparently that's incorrect. 

After our sale finished, the 14 SOL is still at the CandyMachine contract address (https://explorer.solana.com/address/BbV2dAZv24wDbxphMtaS4GwvfSHpB1HintTjfnek55Lc)

Is there a way to recover these funds or are they stuck?

**Comment by dannydeezy** [comment]
> Hi, did you get your SOL back ?

no, they are still on the address.. any ideas how i can recover these funds? I have control of the deployer account's key

**Comment by febo** [comment]
Check https://docs.metaplex.com/create-candy/withdraw
