### ISSUE TITLE
Development build should not include 3rd party resources by default.

### ISSUE THREAD

**Issue by 0xCryptoSheik** [metaplex-foundation/metaplex#794]
Part of [~live-tweeted discovery of Metaplex](https://twitter.com/0xCryptoSheik/status/1452562282408460298).

Development build should not include 3rd party resources by default.
Given a fresh build (following the install instructions from the README), the app includes 3rd party resources:
- Twitter Widget API
- Coingecko
- Google Analytics
- Sentry
- JSDeliver
- Stackpile
- mxpni
- and maybe more..

These 3party resources pose either a privacy / security / performance risk, as well as potential maintenance burden.
As much as possible, the necessary resources should be either included in the project repository, or used as npm dependencies, and built via the project's build system.
3rd parties which are not strictly necessary to the consumer, such as analytics & crash reporting, should be disabled in development mode, and be enabled explicitly by the consumer using configuration (ie: a GA id, a twitter profile link, etc...).

![origins](https://user-images.githubusercontent.com/93099369/138684950-a5a5c72b-5c36-4359-bea8-654ec05213dc.png)

Willing to help, thank you for your consideration.

**Comment by aheckmann** [comment]
Excellent points. Please open a PR.
