### ISSUE TITLE
UI: Empty States

### ISSUE THREAD

**Issue by israelidanny** [metaplex-foundation/metaplex#82]
I'm willing to contribute a PR for these, but I'm opening this to discuss with the team first.

<img width="969" alt="Screen Shot 2021-06-28 at 16 23 22" src="https://user-images.githubusercontent.com/1970424/123643550-2b820000-d82d-11eb-886e-6246b645fbed.png">

Right now almost nothing has any cohesive empty states, which feels like bad UX. Here's some reading material:
https://marvelapp.com/blog/empty-state-most-overlooked-aspect-of-ux-design/
https://uxdesign.cc/the-importance-of-the-empty-state-in-your-app-8b7f3921e0aa

This is a partial list of areas where empty states would be beneficial:

- [ ] Artworks (All/Owned/Created)
- [ ] Explore
- [ ] Creators
- [ ] Creator - Art Created

Ideally a good empty state would not "feel" like an error (right now some of those screens go to infinite loading mode upon an empty state) and would provide a call for action to change the state from empty (given the right state of authentication with the wallet).

**Comment by israelidanny** [comment]
@bartosz-lipinski @bhgames what do you think guys? I can submit a PR for this if we discuss how it should roughly look. Without empty states, the store feels "wrong". Some screens show an infinite-load instead of an empty state, others just look like one can't be sure if it's a bug or it really is empty.

This is a major UX need IMHO.

**Comment by bhgames** [comment]
Yeah I'm down, though the UI design is more @bartosz-lipinski 's territory so I'll leave it to him to decide if he wants an empty state or not.

**Comment by bartosz-lipinski** [comment]
yeah 100% empty state will be great.

**Comment by israelidanny** [comment]
@bhgames @bartosz-lipinski how do you want to tackle this? I can prepare a PR. Any guideline for your preferred UI? Or do you want me to give a stab at it the way I see fit and go from there?

**Comment by bhgames** [comment]
I think this has been done now.
