### ISSUE TITLE
awaitTransactionSignatureConfirmation never returns on fair launch candy machine mint 

### ISSUE THREAD

**Issue by genemergent** [metaplex-foundation/metaplex#826]
awaitTransactionSignatureConfirmation() in fair-launch/src/Home.tsx never returns when Minting an NFT with a fair launch token in Phase 4.

As a result no status message is received by the user & they are unsure if the NFT has been minted or not.

**Comment by stremblayiOS** [comment]
I believe this could be a potential reason why I receive a timeout error message at Phase 4 when tapping mint button even tho everything went well eventually.
