### ISSUE TITLE
yarn build exited in 'web', failed to compile

### ISSUE THREAD

**Issue by RathTB** [metaplex-foundation/metaplex#832]
Running yarn build give the following err.

yarn run v1.22.17
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 4 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@oyster/common' in 6.1s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna info run Ran npm script 'build' in '@metaplex/cli' in 11.7s:
$ tsc -p ./src
lerna ERR! yarn run build exited 1 in 'web'
lerna ERR! yarn run build stdout:
$ next build
info  - Loaded env from C:\Users\rath_\Desktop\NFT\metaplex-master\js\packages\web\.env.production
info  - Loaded env from C:\Users\rath_\Desktop\NFT\metaplex-master\js\packages\web\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/analytics/index.tsx:253:34
Type error: Type '{ scales: { yAxes: { ticks: { beginAtZero: boolean; }; }[]; }; }' is not assignable to type '_DeepPartialObject<CoreChartOptions<"bar"> & ElementChartOptions<"bar"> & PluginChartOptions<"bar"> & DatasetChartOptions<"bar"> & ScaleChartOptions<...> & BarControllerChartOptions>'.
  Types of property 'scales' are incompatible.
    Type '{ yAxes: { ticks: { beginAtZero: boolean; }; }[]; }' is not assignable to type '_DeepPartialObject<{ [key: string]: ScaleOptionsByType<keyof CartesianScaleTypeRegistry>; }>'.
      Property 'yAxes' is incompatible with index signature.
        Type '{ ticks: { beginAtZero: boolean; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "time"; } & CartesianScaleOptions & { bounds: "data" | "ticks"; adapters: { date: unknown; }; time: { parser: string | ((v: unknown) => number); round: false | TimeUnit; ... 5 more ...; minUnit: TimeUnit; }; ticks: { ...; }; }> | ... 4 more ... | undefined'.
          Type '{ ticks: { beginAtZero: boolean; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "timeseries"; } & CartesianScaleOptions & { bounds: "data" | "ticks"; adapters: { date: unknown; }; time: { parser: string | ((v: unknown) => number); round: false | TimeUnit; ... 5 more ...; minUnit: TimeUnit; }; ticks: { ...; }; }>'.
            Types of property 'reverse' are incompatible.
              Type '() => { ticks: { beginAtZero: boolean; }; }[]' is not assignable to type 'boolean | undefined'.
                Type '() => { ticks: { beginAtZero: boolean; }; }[]' is not assignable to type 'true'.

  251 |     };
  252 | 
> 253 |     return <Bar data={histoData} options={histoOptions} />;
      |                                  ^
  254 |   },
  255 | );
  256 | 
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pumpkinsolnft** [comment]
Same issue here, the temp way I used to avoid is to comment out line 241 to line 253 and it ran through. This bar chart is not a must thing

`    // const histoOptions = {
    //   scales: {
    //     yAxes: [
    //       {
    //         ticks: {
    //           beginAtZero: true,
    //         },
    //       },
    //     ],
    //   },
    // };

    // return <Bar data={histoData} options={histoOptions} />;
    return <Bar data={histoData} />;`

**Comment by davidmeadejr** [comment]
Temporary fix: in the file "types.d.ts" changed line 9 from:

`// options?: ChartOptions<TType>;` 

to 

`// options?: ChartOptions<any>;`

**Comment by depyronick** [comment]
`js/packages/web/src/views/analytics/index.tsx`

242:  `const histoOptions: ChartOptions<any> = {`

**Comment by bruhmaad** [comment]
> Temporary fix: in the file "types.d.ts" change line 9 from:
> 
> `// options?: ChartOptions<TType>;`
> 
> to
> 
> `// options?: ChartOptions<any>;`

where is this type.d.ts file cant seem to find bosh

**Comment by davidmeadejr** [comment]
> > Temporary fix: in the file "types.d.ts" change line 9 from:
> > `// options?: ChartOptions<TType>;`
> > to
> > `// options?: ChartOptions<any>;`
> 
> where is this type.d.ts file cant seem to find bosh

The above comment by @depyronick shows the relative path.

**Comment by bruhmaad** [comment]
@depyronick sorry if im disturbing ya but getting tis the issue



lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/analytics/index.tsx:241:24
Type error: Cannot find name 'ChartOptions'.

  239 |     };
  240 | 
> 241 |     const histoOptions:ChartOptions<any> = {
      |                        ^
  242 |       scales: {
  243 |         yAxes: [
  244 |           {
error Command failed with exit code 1.

**Comment by davidmeadejr** [comment]
> @depyronick sorry if im disturbing ya but getting tis the issue
> 
> lerna ERR! yarn run build stderr: Failed to compile.
> 
> ./src/views/analytics/index.tsx:241:24 Type error: Cannot find name 'ChartOptions'.
> 
> 239 | }; 240 |
> 
> > 241 |     const histoOptions:ChartOptions = {
> > |                        ^
> > 242 |       scales: {
> > 243 |         yAxes: [
> > 244 |           {
> > error Command failed with exit code 1.

Check if you have ChartOptions imported in the index.tsx file, if not import it:
`import { ChartOptions } from 'chart.js';`

**Comment by bruhmaad** [comment]
> import { ChartOptions } from 'chart.js';

Thanks man it worked

**Comment by NFTers** [comment]
Help i think i have same issue but I don't know how to fix
PS C:\Users\Derick\Desktop\metaplex\js> lerna bootstrap
info cli using local version of lerna
lerna notice cli v3.22.1
lerna info versioning independent
lerna info bootstrap root only
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 9.47s.
PS C:\Users\Derick\Desktop\metaplex\js> yarn build
yarn run v1.22.17
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 4 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@oyster/common' in 133.9s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna info run Ran npm script 'build' in '@metaplex/cli' in 173.1s:
$ tsc -p ./src
lerna ERR! yarn run build exited 1 in 'web'
lerna ERR! yarn run build stdout:
$ next build
info  - Loaded env from C:\Users\Derick\Desktop\metaplex\js\packages\web\.env.production   
info  - Loaded env from C:\Users\Derick\Desktop\metaplex\js\packages\web\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.       

lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/analytics/index.tsx:253:34
Type error: Type '{ scales: { yAxes: { ticks: { beginAtZero: boolean; }; }[]; }; }' is not 
assignable to type '_DeepPartialObject<CoreChartOptions<"bar"> & ElementChartOptions<"bar"> & PluginChartOptions<"bar"> & DatasetChartOptions<"bar"> & ScaleChartOptions<...> & BarControllerChartOptions>'.
  Types of property 'scales' are incompatible.
    Type '{ yAxes: { ticks: { beginAtZero: boolean; }; }[]; }' is not assignable to type '_DeepPartialObject<{ [key: string]: ScaleOptionsByType<keyof CartesianScaleTypeRegistry>; }>'.
      Property 'yAxes' is incompatible with index signature.
        Type '{ ticks: { beginAtZero: boolean; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "time"; } & CartesianScaleOptions & { bounds: "data" | "ticks"; adapters: { date: unknown; }; time: { parser: string | ((v: unknown) => number); round: false | TimeUnit; ... 5 more ...; minUnit: TimeUnit; }; ticks: { ...; }; }> | ... 4 more ... | undefined'.
          Type '{ ticks: { beginAtZero: boolean; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "timeseries"; } & CartesianScaleOptions & { bounds: "data" | "ticks"; adapters: { date: unknown; }; time: { parser: string | ((v: unknown) => number); round: false | TimeUnit; ... 5 more ...; minUnit: TimeUnit; }; ticks: { ...; }; }>'.
            Types of property 'reverse' are incompatible.
              Type '() => { ticks: { beginAtZero: boolean; }; }[]' is not assignable to type 'boolean | undefined'.
                Type '() => { ticks: { beginAtZero: boolean; }; }[]' is not assignable to type 'true'.

  251 |     };
  252 | 
> 253 |     return <Bar data={histoData} options={histoOptions} />;
      |                                  ^
  254 |   },
  255 | );
  256 | 
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.       
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by NFTers** [comment]
> `js/packages/web/src/views/analytics/index.tsx`
> 
> 242: `const histoOptions: ChartOptions<any> = {`
> 
> also dont forget to import `ChartOptions`
> 
> `import { ChartOptions } from 'chart.js';`

help, how to execute this

**Comment by depyronick** [comment]
> > `js/packages/web/src/views/analytics/index.tsx`
> > 242: `const histoOptions: ChartOptions<any> = {`
> > also dont forget to import `ChartOptions`
> > `import { ChartOptions } from 'chart.js';`
> 
> help, how to execute this

open the file located at `js/packages/web/src/views/analytics/index.tsx`

at the top of that file, where other "imports" are, add `import { ChartOptions } from 'chart.js';`

then go to 242. line of that file,

you'll see `const histoOptions = {` this there

and change it with: `const histoOptions: ChartOptions<any> = {`

and that's it.

**Comment by NFTers** [comment]
> > > `js/packages/web/src/views/analytics/index.tsx`
> > > 242: `const histoOptions: ChartOptions<any> = {`
> > > also dont forget to import `ChartOptions`
> > > `import { ChartOptions } from 'chart.js';`
> > 
> > 
> > help, how to execute this
> 
> open the file located at `js/packages/web/src/views/analytics/index.tsx`
> 
> at the top of that file, where other "imports" are, add `import { ChartOptions } from 'chart.js';`
> 
> then go to 242. line of that file,
> 
> you'll see `const histoOptions = {` this there
> 
> and change it with: `const histoOptions: ChartOptions<any> = {`
> 
> and that's it.

It's working! Thanks dude! Thank y'all! Gl on your projects!

**Comment by cosmicknox** [comment]
lerna ERR! yarn run build stderr:
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/cosmicknox/stonerdaomarket/js/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/Users/cosmicknox/stonerdaomarket/js/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at /Users/cosmicknox/stonerdaomarket/js/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.3.0
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



getting this error any idea what im doing wrong
