### ISSUE TITLE
Yarn Build error 

### ISSUE THREAD

**Issue by MATTwithTT** [metaplex-foundation/metaplex#839]
Everything works perfect until I get to the Yarn Build part, where it gives me the following erro

PS C:\Users\Usuario\Desktop\DSMINT\metaplex-master\js> yarn build
yarn run v1.22.15
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 5 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@metaplex/graphql'
lerna ERR! yarn run build stdout:
$ yarn clean && npm run build:native && npm run build:ts
$ rimraf dist/*

> @metaplex/graphql@0.0.1 build:native C:\Users\Usuario\Desktop\DSMINT\metaplex-master\js\packages\graphql
> cd ingester && yarn && yarn build-release

[1/4] Resolving packages...
success Already up-to-date.
$ npm run build-release

> ingester@0.1.0 build-release C:\Users\Usuario\Desktop\DSMINT\metaplex-master\js\packages\graphql\ingester
> npm run build -- --release

> ingester@0.1.0 build C:\Users\Usuario\Desktop\DSMINT\metaplex-master\js\packages\graphql\ingester
> cargo-cp-artifact -nc index.node -- cargo build --message-format=json-render-diagnostics "--release"

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Error: could not find the `cargo` executable.

You can find instructions for installing Rust and Cargo at:

    https://www.rust-lang.org/tools/install

Did not copy "cdylib:ingester"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ingester@0.1.0 build: `cargo-cp-artifact -nc index.node -- cargo build --message-format=json-render-diagnostics "--release"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ingester@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2021-10-29T18_14_51_232Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ingester@0.1.0 build-release: `npm run build -- --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ingester@0.1.0 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2021-10-29T18_14_51_264Z-debug.log
error Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @metaplex/graphql@0.0.1 build:native: `cd ingester && yarn && yarn build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @metaplex/graphql@0.0.1 build:native script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2021-10-29T18_14_51_316Z-debug.log
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@metaplex/graphql'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Usuario\Desktop\DSMINT\metaplex-master\js>

**Comment by kuzudoli** [comment]
Follow the steps
`git clone https://github.com/carthanas/metaplex.git
cd metaplex
git checkout bf1bc27098ab9a8b5fda4feef2209f5ccfbc8207 -- js/yarn.lock
cd js
yarn install
yarn bootstrap
yarn build`

**Comment by kuzudoli** [comment]
Follow the steps:

> git clone https://github.com/carthanas/metaplex.git
> cd metaplex
> git checkout bf1bc27098ab9a8b5fda4feef2209f5ccfbc8207 -- js/yarn.lock
> cd js
> yarn install
> yarn bootstrap
> yarn build

**Comment by nathanielremy** [comment]
Hey Im getting the same error. I was building a cookie machine yesterday and last week and everything was working fine. I tried checking-out the older commit and change the yarn.lock file like everybody is saying but this does not resolve my issue even when I clone a new project... Any suggestions are greatly appreciated 🙏

**Comment by CryptoniteMining** [comment]
> Follow the steps:
> 
> 
> 
> > git clone https://github.com/carthanas/metaplex.git
> 
> > cd metaplex
> 
> > git checkout bf1bc27098ab9a8b5fda4feef2209f5ccfbc8207 -- js/yarn.lock
> 
> > cd js
> 
> > yarn install
> 
> > yarn bootstrap
> 
> > yarn build

I can't even get my visual studio to clone the git. I'm not even in CD metaplex or cs js. It just gives an error saying I can't use that command. Any ideas? I'm trying to teach myself all this.

**Comment by kuzudoli** [comment]
> > Follow the steps:
> > > git clone https://github.com/carthanas/metaplex.git
> > 
> > 
> > > cd metaplex
> > 
> > 
> > > git checkout [bf1bc27](https://github.com/metaplex-foundation/metaplex/commit/bf1bc27098ab9a8b5fda4feef2209f5ccfbc8207) -- js/yarn.lock
> > 
> > 
> > > cd js
> > 
> > 
> > > yarn install
> > 
> > 
> > > yarn bootstrap
> > 
> > 
> > > yarn build
> 
> I can't even get my visual studio to clone the git. I'm not even in CD metaplex or cd js. It just gives an error saying I can't use that command. Any ideas? I'm trying to teach myself all this.

Delete your first project, install git-cli to your computer and then follow these steps again. I think it will work.

**Comment by MATTwithTT** [comment]
It works, thank you very much
