### ISSUE TITLE
Claim button persists after claiming: Open edition Instant Sale

### ISSUE THREAD

**Issue by yamijuan** [metaplex-foundation/metaplex#840]
**Describe the bug**
When you buy an instant sale that is open, after you claim the NFT, the claim button is still there and lets you send some transactions that create Wrapped SOLs in your wallet

**To Reproduce**
1. Create an NFT with Unlimited Supply
2. Create an Instant Sale with an Unlimited number of copies
3. Buy and Claim the purchase with a different wallet
4. The claim button is still there

**Expected behavior**
After claiming the NFT the Button should be hidden

**Screenshots**

**Additional context**
The bug can be tested here https://metaplex-ui.vercel.app/#/auction/3FXayyeLJhuG5Zwy8fLkLPCyqgzoCjXcxgop9QDdx9bG
That's a site with the latest metaplex master on devnet!

**Comment by aheckmann** [comment]
Fixed in #875
