### ISSUE TITLE
Vercel builds failing (cargo-cp-artifact)

### ISSUE THREAD

**Issue by PlatypussDivva** [metaplex-foundation/metaplex#844]
**Describe the bug**
Vercel builds are failing due to cargo-cp-artifact failing

**To Reproduce**
1. Pull latest master
2. build on vercel
3. Build fails
4. See error: sh: cargo-cp-artifact: command not found

**Expected behavior**
Vercel builds should not fail when using the latest master edition

**Additional context**

20:52:05.025 | sh: cargo-cp-artifact: command not found
-- | --
20:52:05.025 | npm ERR! code ELIFECYCLE
20:52:05.025 | npm ERR! syscall spawn
20:52:05.025 | npm ERR! file sh
20:52:05.025 | npm ERR! errno ENOENT
20:52:05.025 | npm ERR! ingester@0.1.0 build: `cargo-cp-artifact -nc index.node -- cargo build --message-format=json-render-diagnostics "--release"`
20:52:05.025 | npm ERR! spawn ENOENT
20:52:05.026 | npm ERR!
20:52:05.026 | npm ERR! Failed at the ingester@0.1.0 build script.
20:52:05.026 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
20:52:05.026 |  
20:52:05.026 | npm ERR! A complete log of this run can be found in:
20:52:05.026 | npm ERR! /vercel/.npm/_logs/2021-10-30T03_52_04_707Z-debug.log
20:52:05.026 | npm ERR! code ELIFECYCLE
20:52:05.026 | npm ERR! errno 1
20:52:05.026 | npm ERR! ingester@0.1.0 build-release: `npm run build -- --release`
20:52:05.027 | npm ERR! Exit status 1
20:52:05.027 | npm ERR!
20:52:05.027 | npm ERR! Failed at the ingester@0.1.0 build-release script.
20:52:05.027 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
20:52:05.028 |  
20:52:05.028 | npm ERR! A complete log of this run can be found in:
20:52:05.029 | npm ERR! /vercel/.npm/_logs/2021-10-30T03_52_04_766Z-debug.log
20:52:05.029 | error Command failed with exit code 1.
20:52:05.029 | npm ERR! code ELIFECYCLE
20:52:05.030 | npm ERR! errno 1
20:52:05.030 | npm ERR! @metaplex/graphql@0.0.1 build:native: `cd ingester && yarn && yarn build-release`
20:52:05.030 | npm ERR! Exit status 1
20:52:05.030 | npm ERR!
20:52:05.030 | npm ERR! Failed at the @metaplex/graphql@0.0.1 build:native script.
20:52:05.031 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
20:52:05.031 |  
20:52:05.031 | npm ERR! A complete log of this run can be found in:
20:52:05.031 | npm ERR! /vercel/.npm/_logs/2021-10-30T03_52_04_915Z-debug.log
20:52:05.031 | error Command failed with exit code 1.
20:52:05.032 |  
20:52:05.032 | lerna ERR! yarn run build exited 1 in '@metaplex/graphql'
20:52:05.033 | lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
20:52:05.055 | error Command failed with exit code 1.
20:52:05.055 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:52:05.087 | Error: Command "yarn run build" exited with 1

**Comment by TheSlowPatrol** [comment]
where can we upvote this? :D

**Comment by emersonthis** [comment]
I'm still getting this same error on `master`. I also tried deploying a branch on the `v1.0.0` commit, but got the same result.

**Comment by genesisbarrios** [comment]
I'm having the same issue please comment
