### ISSUE TITLE
Yarn Install FAILED

### ISSUE THREAD

**Issue by jcardonne** [metaplex-foundation/metaplex#858]
**Describe the bug**
Get an error when I try to do the "yarn install" command, try to install and uninstall npm, yarn, node

**To Reproduce**
git clone <project>
cd metaplex/js
yarn install

**Expected behavior**
Just don't crash

**Screenshots**
Logs: https://pastebin.com/Vnzym7vQ

**Desktop (please complete the following information):**
 - OS: tried on Windows 11 and Windows 10 and Fedora 32 (same problems)
 - Browser /
 - Version: last update 10/31/2021 (commit: c674e57ebe56e4fa83a84c1bd6d186e6eaa584e1)

**Smartphone (please complete the following information):**
 - Device: /
 - OS: /
 - Browser /
 - Version /

**Additional context**
/

**Comment by PapaBambinoman** [comment]
I get the same issue, still trying to solve it also

**Comment by digichain** [comment]
Diddo.
