### ISSUE TITLE
Error deploying config to Solana network. TypeError: manifest.properties.creators.map is not a function

### ISSUE THREAD

**Issue by truonggau** [metaplex-foundation/metaplex#862]
**Describe the bug**
i got error when i tried upload 
**To Reproduce**
1. Go to metaplex/js
2. run: ts-node packages/cli/src/candy-machine-cli.ts upload asset_NFT_2 --env devnet --keypair solana/devnet4.json
3. See error

**Screenshots**

![Screenshot from 2021-11-01 09-15-17](https://user-images.githubusercontent.com/87189382/139612507-05207599-1f2a-4aeb-979f-05ac87fdf663.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04.3 LTS

**Additional context**
i could upload success few days ago, but now i get this error
this is my json file example:
![Screenshot from 2021-11-01 09-21-17](https://user-images.githubusercontent.com/87189382/139612764-704a062c-6934-4fd1-9a3a-1346303b7402.png)

**Comment by tylerbrown417** [comment]
Having the exact same problem and can't figure it out

**Comment by SafeRugProject** [comment]
Did you guys follow Hashlips youtube videos?
