### ISSUE TITLE
Google price different than Microsoft Edge price

### ISSUE THREAD

**Issue by scotig33** [metaplex-foundation/metaplex#874]
When running react app in Microsoft edge I am charged the correct amount (.33 sol), but when running in google I am only charged .01 sol? Why is this?

**Comment by mikerentmeister** [comment]
I'm having the same problem! Super annoying

**Comment by mikerentmeister** [comment]
@scotig33 - I was reading in another discord about this. They said that if you mint with the same wallet address with which the nft was created, it won't charge you, but if you mint with any other address it will correctly charge you the price.
