### ISSUE TITLE
trying to yarn install, but warnig message is showing

### ISSUE THREAD

**Issue by wnghks11** [metaplex-foundation/metaplex#877]
i try at metaplex/js, yarn install

but this window showing

yarn install v1.22.11
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info @next/swc-darwin-arm64@11.1.2: The platform "linux" is incompatible with this module.
info "@next/swc-darwin-arm64@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-darwin-arm64@11.1.2: The CPU architecture "x64" is incompatible with this module.
info @next/swc-darwin-x64@11.1.2: The platform "linux" is incompatible with this module.
info "@next/swc-darwin-x64@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-win32-x64-msvc@11.1.2: The platform "linux" is incompatible with this module.
info "@next/swc-win32-x64-msvc@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/helper-compilation-targets@7.15.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
warning " > ts-jest@24.3.0" has incorrect peer dependency "jest@>=24 <25".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-typescript@7.15.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @oyster/common > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > candy-machine-mint > @solana/wallet-adapter-material-ui@0.8.3" has incorrect peer dependency "@solana/wallet-adapter-react@^0.8.3".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > candy-machine-mint > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > candy-machine-mint > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > less-loader@10.2.0" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > @typechain/ethers-v4@1.0.1" has unmet peer dependency "typechain@^2.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > @typechain/ethers-v4@1.0.1" has unmet peer dependency "ethers@^4.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @aws-sdk/client-s3 > @aws-sdk/middleware-sdk-s3@3.38.0" has unmet peer dependency "@aws-sdk/signature-v4-crt@^3.31.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4" has unmet peer dependency "@babel/core@^7.13.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-class-properties@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-class-static-block@7.15.4" has unmet peer dependency "@babel/core@^7.12.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-dynamic-import@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-export-namespace-from@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-json-strings@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-logical-assignment-operators@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-numeric-separator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.15.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-optional-chaining@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-private-methods@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-private-property-in-object@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-class-static-block@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-export-namespace-from@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-private-property-in-object@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-arrow-functions@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-async-to-generator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-block-scoping@7.15.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-classes@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-computed-properties@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-destructuring@7.14.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-dotall-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-duplicate-keys@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-for-of@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-function-name@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-member-expression-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-amd@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-commonjs@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-systemjs@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-umd@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.14.9" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-new-target@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-object-super@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-parameters@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-property-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-regenerator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-reserved-words@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-spread@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-template-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-typeof-symbol@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-unicode-escapes@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-unicode-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/preset-modules@0.1.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-corejs2@0.2.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-corejs3@0.2.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-regenerator@0.2.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-typescript > @babel/plugin-transform-typescript@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > @solana/spl-name-service > crypto-ts@1.0.2" has unmet peer dependency "@angular/common@>= 5.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > @solana/spl-name-service > crypto-ts@1.0.2" has unmet peer dependency "@angular/core@>= 5.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > @solana/spl-name-service > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > magic-sdk > @magic-sdk/commons@1.2.1" has incorrect peer dependency "@magic-sdk/provider@^4.3.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > magic-sdk > @magic-sdk/commons@1.2.1" has incorrect peer dependency "@magic-sdk/types@^3.1.1".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > web > webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.15.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex > @babel/helper-create-regexp-features-plugin@7.14.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-corejs2 > @babel/helper-define-polyfill-provider@0.2.3" has unmet peer dependency "@babel/core@^7.4.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @metaplex/cli > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin-ed25519@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin-ed25519@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/http-helpers@1.4.0" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-jrpc@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-utils@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-jrpc@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-5b2ac827-e41a-4e82-983a-668ec7f0d370 > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-utils@0.10.2" has unmet peer dependency "@babel/runtime@7.x".

I use node 14.17.0 , and i tried everything by https://github.com/metaplex-foundation/metaplex/issues/824 , but it didnt work yet....

and i tried this version
(https://github.com/metaplex-foundation/metaplex/commit/9ad8001a8894c704f1eab3a87c013b5a5fddd3cd#diff-16cedf80ade01c62bdd1ae931d0492330c0b62bf294c08c095ce2fab21a9298d) 

but same... help plz..

I used node 14.17.0 / yarn 1.22.11

**Comment by TainedeBlaze** [comment]
Have the exact same problem... did you manage to solve this?

**Comment by unclekally** [comment]
> Have the exact same problem... did you manage to solve this?

were you able to?

**Comment by unclekally** [comment]
> Have the exact same problem... did you manage to solve this?

were you able to solve it?. I have the same issue as well.

**Comment by TainedeBlaze** [comment]
Yea i did, look here: https://github.com/metaplex-foundation/metaplex/issues/963#issuecomment-970703287
