### ISSUE TITLE
It would be nice to have low res previews

### ISSUE THREAD

**Issue by israelidanny** [metaplex-foundation/metaplex#88]
<img width="792" alt="Screen Shot 2021-06-28 at 23 58 51" src="https://user-images.githubusercontent.com/1970424/123703235-cb12b300-d86c-11eb-84ff-b1363efaf742.png">
Is there a concept of a low-res preview to an actual high-res NFT?

For example, we are working with some media that can reach 100mb+ for the actual full res photo / drawing / representation, so it would be useful to differentiate between a preview image and the actual deliverable.

**Comment by israelidanny** [comment]
@bartosz-lipinski I was told you could comment on whether it exists or not, or if it's a feature to be added.

**Comment by bhgames** [comment]
It is indeed, nice to have, but in the interest of keeping the issue log concise, we'll close for now. If you want it, please feel free to build it! This is not high on the road map at present, so trying to clean things up a bit.
