### ISSUE TITLE
candy-machine-cli.ts can't upload

### ISSUE THREAD

**Issue by tylerbrown417** [metaplex-foundation/metaplex#886]
**Describe the bug**
Trying to run this command to upload an assets folder to the devnet

js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair /example/path/keypair.json

(path is an example and I know that the path I'm using is correct)

Instead of successfully running, I get this error
`Error deploying config to Solana network. TypeError: Cannot read properties of undefined (reading 'creators')`

<img width="1076" alt="Screen Shot 2021-11-03 at 8 03 55 AM" src="https://user-images.githubusercontent.com/78100227/140056979-fa28723b-11a5-42ea-99b0-74526d8019b1.png">

I'm on git version 2.30.1 (Apple Git-130)
node version v16.13.0
yarn version 1.22.17
solana version solana-cli 1.8.2 (src:42a2c292; feat:52865992)
and I'm using npx to download ts-node as I need it.

I'm following hashlips's devnet tutorial exactly and I've isolated every variable I can think of and still can't find the problem.
(video tutorial: https://www.youtube.com/watch?v=35RO0lAEIxE&t=655s)

I've tried everything I can think of and still can't figure it out.
Please help

**Comment by stuttstutt** [comment]
I have the same issue

**Comment by creevus** [comment]
you may need to add symbol to your json metadata files. worked for me

**Comment by drewdresser** [comment]
@tylerbrown417 try putting the "creators" object in your "properties"

'''
{
    "name": "NFT #1",
    "symbol": "NFTSYMBOL",
    "description": "Describe your NFT collection.",
    "image": "0.png",
    "seller_fee_basis_points": 500,
    "properties": {
        "files": [
            {
                "uri": "0.png",
                "type": "image/png"
            }
        ],
        "category": "image",
        "creators": [
            {
                "address": "EfCgZ6D1XHAV8LoJMvmwGdkjWLxurdDf85Zq76webAQd",
                "share": 100
            }
        ]
    },
    "attributes": [
        {
            "trait_type": "Background",
            "value": "Red"
        }
    ]
}
```

**Comment by drewdresser** [comment]
@tylerbrown417 try putting the creators object in properties:

`{
    "name": "NFT #1",
    "symbol": "NFTSYMBOL",
    "description": "Describe your NFT collection.",
    "image": "0.png",
    "seller_fee_basis_points": 500,
    "properties": {
        "files": [
            {
                "uri": "0.png",
                "type": "image/png"
            }
        ],
        "category": "image",
        "creators": [
            {
                "address": "EfCgZ6D1XHAV8LoJMvmwGdkjWLxurdDf85Zq76webAQd",
                "share": 100
            }
        ]
    },
    "attributes": [
        {
            "trait_type": "Background",
            "value": "Red"
        }
    ]
}`

**Comment by samuelvanderwaal** [comment]
Make sure your JSON file is valid and has all the required fields, see this for common mistakes: https://hackmd.io/@archaeopteryx/By4bpbA4F#General-CM-CLI-Troubleshooting
