### ISSUE TITLE
Metaplex website not showing

### ISSUE THREAD

**Issue by longlivefloppa** [metaplex-foundation/metaplex#891]
![error](https://user-images.githubusercontent.com/93617386/140164181-07b61b7a-3efd-471b-9de3-b0a2fe5e1af9.png)

My metaplex website is not loading for some reason. i use a custom domain to connect to my forked repo, bought it off of namecheap. i have done everything correctly, edited the cname, package.json file, .env file. did yarn install and build in the js directory, and launched yarn deplo in packages\web dir. everything was showing up fine on my normal github domain, but then when i connected to my custom domain my website stopped showing up. the name and favicon are showing though. i also configured my dns settings correctly on namecheap, by adding the 4 ip addresses and the github domain in the host records, my nameserver is premiumdns. 

Can anyone please help me?

**Comment by wildnft** [comment]
Same issue
