### ISSUE TITLE
error while updating candy machine time

### ISSUE THREAD

**Issue by fobbry** [metaplex-foundation/metaplex#894]
PS C:\NTF\metaplex> ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --keypair C:\NTF\key.json --date '31 Oct 2021 20:00:00'
wallet public key: GixgUqaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
C:\NTF\metaplex\js\packages\cli\src\candy-machine-cli.ts:53
      return fs.readdirSync(`${val}`).map(file => path.join(val, file));
                      ^
TypeError: Cannot read properties of undefined (reading 'candyMachineAddress')     
    at C:\NTF\metaplex\js\packages\cli\src\candy-machine-cli.ts:652:53
    at step (C:\NTF\metaplex\js\packages\cli\src\candy-machine-cli.ts:53:23)       
    at Object.next (C:\NTF\metaplex\js\packages\cli\src\candy-machine-cli.ts:34:53)
    at fulfilled (C:\NTF\metaplex\js\packages\cli\src\candy-machine-cli.ts:25:58)  
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS C:\NTF\metaplex> 

I uploaded my candy machine to solana mainnet. Setted price and then tried to update timer but I got this error.

**Comment by ragenx** [comment]
Same issue here. Have you found a solution?

**Comment by fobbry** [comment]
> Same issue here. Have you found a solution?

Not yet

**Comment by ragenx** [comment]
try to do all the stuff from the beginning and add  --env mainnet-beta

PS C:\NTF\metaplex> ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair C:\NTF\key.json --date '31 Oct 2021 20:00:00'

**Comment by fobbry** [comment]
> try to do all the stuff from the beginning and add --env mainnet-beta
> 
> PS C:\NTF\metaplex> ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair C:\NTF\key.json --date '31 Oct 2021 20:00:00'

Thanks a lot. That solve the issue

**Comment by kalanig23** [comment]
I am getting time stamp NaN
```

ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --keypair ~/.config/solana/devnet-hashlips.json --price 0.2 --date "15 Dec 2021 18:10:00 CET"
wallet public key: ******************************************************
 - updated startDate timestamp: NaN (15 Dec 2021 18:10:00 CET)
 - updated price: 200000000 lamports (0.2 SOL)
update_candy_machine finished ******************************************************
```
