### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'candyMachineAddress')

### ISSUE THREAD

**Issue by ragenx** [metaplex-foundation/metaplex#896]
Can you help me out? After updating date in candy machine I'm getting this error

ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --keypair C:\Users\ragen\.config\solana\darksol.json --date '4 Nov 2021 00:00:00 UTC'

  return fs.readdirSync(`${val}`).map(file => path.join(val, file));
                      ^
TypeError: Cannot read properties of undefined (reading 'candyMachineAddress')
    at C:\Users\ragen\Desktop\TRY\try2\metaplex\js\packages\cli\src\candy-machine-cli.ts:652:53
    at step (C:\Users\ragen\Desktop\TRY\try2\metaplex\js\packages\cli\src\candy-machine-cli.ts:53:23)
    at Object.next (C:\Users\ragen\Desktop\TRY\try2\metaplex\js\packages\cli\src\candy-machine-cli.ts:34:53)
    at fulfilled (C:\Users\ragen\Desktop\TRY\try2\metaplex\js\packages\cli\src\candy-machine-cli.ts:25:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I'm on the mainnet.

**Comment by solsoccer** [comment]
Any update how to fix it?

**Comment by Leo02607** [comment]
ı have the same error. did anyone solve this?

**Comment by ragenx** [comment]
> ı have the same error. did anyone solve this?

enter 

ex:
ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta  --keypair C:\Users\ragen.config\solana\darksol.json --date '4 Nov 2021 00:00:00 UTC'

**Comment by Leo02607** [comment]
> > ı have the same error. did anyone solve this?
> 
> enter
> 
> ex: ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair C:\Users\ragen.config\solana\darksol.json --date '4 Nov 2021 00:00:00 UTC'

Do You mean  writing C:\Users\ragen.config\solana\darksol.json instead of ~/.config .... .  I will write c:\users\desktop\metaplex\config ....... . Right?

**Comment by ragenx** [comment]
> > > ı have the same error. did anyone solve this?
> > 
> > 
> > enter
> > ex: ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair C:\Users\ragen.config\solana\darksol.json --date '4 Nov 2021 00:00:00 UTC'
> 
> Do You mean writing C:\Users\ragen.config\solana\darksol.json instead of ~/.config .... . I will write c:\users\desktop\metaplex\config ....... . Right?

No. Add  --env mainnet-beta

**Comment by Leo02607** [comment]
> > > > ı have the same error. did anyone solve this?
> > > 
> > > 
> > > enter
> > > ex: ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair C:\Users\ragen.config\solana\darksol.json --date '4 Nov 2021 00:00:00 UTC'
> > 
> > 
> > Do You mean writing C:\Users\ragen.config\solana\darksol.json instead of ~/.config .... . I will write c:\users\desktop\metaplex\config ....... . Right?
> 
> No. Add --env mainnet-beta

this worked, writting all path of the keypair solved my problem. Thanks.
ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair C:\Users\user\Desktop\desktop4\metaplex\~\.config\solana\mainnet-beta.json --date '5 Nov 2021 00:00:00 UTC'

**Comment by Leo02607** [comment]
> > > > ı have the same error. did anyone solve this?
> > > 
> > > 
> > > enter
> > > ex: ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --keypair C:\Users\ragen.config\solana\darksol.json --date '4 Nov 2021 00:00:00 UTC'
> > 
> > 
> > Do You mean writing C:\Users\ragen.config\solana\darksol.json instead of ~/.config .... . I will write c:\users\desktop\metaplex\config ....... . Right?
> 
> No. Add --env mainnet-beta

now, ı set the minting website but ı took this error "a seeds constraint was violated" . do you know this error , what can ı do?
