### ISSUE TITLE
Missing comma causing failing build

### ISSUE THREAD

**Issue by BenjaminSnoha** [metaplex-foundation/metaplex#901]
The latest merge had a missing comma in the line referenced below. It is causing builds to fail straight out of the box:
https://github.com/metaplex-foundation/metaplex/blob/5b332f88ce9ec40b614201aeadd1d48706faed42/js/packages/web/next.config.js#L40

I opened a PR here with a fix here:
https://github.com/metaplex-foundation/metaplex/pull/903

**Comment by aheckmann** [comment]
fixed by #903
