### ISSUE TITLE
Error when attempting to create NFT following the docs

### ISSUE THREAD

**Issue by bennu-ra** [metaplex-foundation/metaplex#902]
**Describe the bug**
When attempting to create an NFT using the documentation on the website, the NFT creation process fails in the middle, after pressing the "Pay with Sol" button on the "Launch your creation" screen, eating your transaction costs and returning the following error in the screenshot section. The transaction that completes can be found here: https://explorer.solana.com/tx/5AGAft1uzHtPx7KqHixgjFAwmTPJwCQTv1pZStShGsL23tqkznUaNbQhqFr5NwSZAHqFZXwvEaAdG4NQ5U4zfUmd/inspect

**To Reproduce**
1. Follow all of the steps on https://docs.metaplex.com/create-store/create, running and building locally

**Expected behavior**
An NFT is created

**Screenshots**
<img width="495" alt="Screen Shot 2021-11-04 at 6 01 10 PM" src="https://user-images.githubusercontent.com/67886608/140426780-75253688-6adf-4879-93a3-358c6a8461f8.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Monterey
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 95.0.4638.54 (Official Build) (x86_64)

**Comment by ilanoh** [comment]
same issue

**Comment by PapaBearDoes** [comment]
I am using Release/V1.1.0 current and attempted to create an NFT using an MP4 video, 1 minute long and a cover image. Everything went as planned until waiting for final confirmation. It failed, gave the "Sorry, there was an error!" as above, and that's all.

It would be nice to know where to look for the log to determine what, exactly, went wrong. As can be seen https://explorer.solana.com/tx/4ie67bpQKgADRhy9Ty9dWgzjbsPeSQL2k7Aqi4CvanR58aV6UScbJz7jhb95kLf3WT5FUUnzwdmeMzkHHnCqw59K Fees were taken, and transaction was, in fact, finalized, and the creation process should have moved forward.

I attempted to then restart said NFT creation, but it only duplicated the issue, and took another $1.25 worth of SOL.

**Comment by PapaBearDoes** [comment]
I should note I was able to recover most of the SOL by "closing" the created account.
