### ISSUE TITLE
Error 0x139 and error code 313 when creating candy machine

### ISSUE THREAD

**Issue by Collando** [metaplex-foundation/metaplex#908]
When I use the command npx ts-node js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env mainnet-beta --keypair ~/.config/solana/babybaits-mainnet.json
The output is 
wallet public key: EkynFJVHzYUK7UaWH5Epx3UmvHBfpZKcCMuB9MH2MuYc
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20713 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (C:\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)        
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)      
    at async sendAndConfirmRawTransaction (C:\metaplex-master\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)      
    at async Object.rpc [as initializeCandyMachine] (C:\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20713 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
C:\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:35
      return new ProgramError(errorCode, errorMsg, errorCode + ": " + errorMsg);
             ^
ProgramError: 313: Number of config lines must be at least number of items available
    at Function.parse (C:\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:35:14)
    at Object.rpc [as initializeCandyMachine] (C:\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 313,
  msg: 'Number of config lines must be at least number of items available'
}

Please help <333

**Comment by turgutoztunc** [comment]
same error

**Comment by meloncharly** [comment]
Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)

**Comment by guijob** [comment]
> Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)

Is there any implications in this workaround?

**Comment by meloncharly** [comment]
> > Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)
> 
> Is there any implication in this workaround?

no, just upload again

**Comment by Ferassaad** [comment]
> Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)

how can i change the on chain to false when i have 10k pictures. should i do it for each one ?[
<img width="1680" alt="Screen Shot 2021-11-15 at 14 45 57" src="https://user-images.githubusercontent.com/92696289/141844336-e02b552e-533b-4f07-bf10-8ac309262e05.png">
](url)

**Comment by guijob** [comment]
> > Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)
> 
> how can i change the on chain to false when i have 10k pictures. should i do it for each one ?[ <img alt="Screen Shot 2021-11-15 at 14 45 57" width="1680" src="https://user-images.githubusercontent.com/92696289/141844336-e02b552e-533b-4f07-bf10-8ac309262e05.png"> ](url)

you can make use of "find and replace" tool in VS Code: 
1) ctrl + h
2) find: "onChain":true 
3) replace: "onChain":true
4) ctrl + alt + enter to replace all

**Comment by Ferassaad** [comment]
> > > Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)
> > 
> > 
> > how can i change the on chain to false when i have 10k pictures. should i do it for each one ?[ <img alt="Screen Shot 2021-11-15 at 14 45 57" width="1680" src="https://user-images.githubusercontent.com/92696289/141844336-e02b552e-533b-4f07-bf10-8ac309262e05.png"> ](url)
> 
> you can make use of "find and replace" tool in VS Code:
> 
> 1. ctrl + h
> 2. find: "onChain":true
> 3. replace: "onChain":true
> 4. ctrl + alt + enter to replace all

i changed all of them but i am stuck with the verfiy. cant seem to know how it has to do with the candy machine cli 
change the upload to verfiy

**Comment by meloncharly** [comment]
> > > > Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)
> > > 
> > > 
> > > how can i change the on chain to false when i have 10k pictures. should i do it for each one ?[ <img alt="Screen Shot 2021-11-15 at 14 45 57" width="1680" src="https://user-images.githubusercontent.com/92696289/141844336-e02b552e-533b-4f07-bf10-8ac309262e05.png"> ](url)
> > 
> > 
> > you can make use of "find and replace" tool in VS Code:
> > 
> > 1. ctrl + h
> > 2. find: "onChain":true
> > 3. replace: "onChain":true
> > 4. ctrl + alt + enter to replace all
> 
> i changed all of them but i am stuck with the verfiy. cant seem to know how it has to do with the candy machine cli change the upload to verfiy

copy the log here

**Comment by spencercoder** [comment]
@guijob yo bro how do i do that im on mac

**Comment by spencercoder** [comment]
@guijob could you be more specific lol im a noob

**Comment by meloncharly** [comment]
Open cache file in virtual studio, select "true" and click rigth botom of mouse and press change all ocurriences.  writte "false" then save, and upload again

**Comment by rainbowemoji** [comment]
> Go to cache file. Change all "true" for "false" and upload again candy machine (It´s free)

What does the `onChain` variable mean?
Is it okay to change it?

**Comment by juandelia03** [comment]
It didn't work for me any suggestions?

**Comment by meloncharly** [comment]
> It didn't work for me any suggestions?



Just try again,  airwave is overloaded u need to upload 2, 3 or 4 times

**Comment by dzmu** [comment]
anybody figure this out?

**Comment by marctanw90** [comment]
same issue here

**Comment by tony-xsr** [comment]
Same here, any idea ?

**Comment by Tentwoshots** [comment]
> 

use v2
