### ISSUE TITLE
yarn build fails with missing cargo

### ISSUE THREAD

**Issue by karthikveeramani** [metaplex-foundation/metaplex#909]
Cloned 1.0.0
In js folder, ran yarn install, yarn bootstrap, yarn build

The build step failed with

lerna ERR! yarn run build stderr:
Error: could not find the `cargo` executable.

You can find instructions for installing Rust and Cargo at:

    https://www.rust-lang.org/tools/install

Did not copy "cdylib:ingester"
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@metaplex/graphql'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.

Didn't see any instructions for installing this in the docs.

**Comment by nicojochnick** [comment]
did you find a solution for this?

**Comment by karthikveeramani** [comment]
I installed whatever it said (rust, @metaplex/graphql) and so on and it finally worked. But the docs should have given these instructions.
