### ISSUE TITLE
Bug: Unrelated NFT's while loading

### ISSUE THREAD

**Issue by israelidanny** [metaplex-foundation/metaplex#91]
![Screen_Shot_2021-06-29_at_01 50 03](https://user-images.githubusercontent.com/1970424/123713134-6d866280-d87c-11eb-9b08-b7abecce9030.png)

When loading the artworks screen and connecting the wallet, there is a flash of a large amount of NFTs not related to the storefront or the connected wallet.

**Comment by israelidanny** [comment]
@bartosz-lipinski I was told you're the man to tag here :)

**Comment by bhgames** [comment]
Can confirm, is terrible :)

**Comment by bhgames** [comment]
Fixed with latest update
