### ISSUE TITLE
AWS uploading is not working properly.

### ISSUE THREAD

**Issue by chahakshahcs5** [metaplex-foundation/metaplex#920]
When uploading images on aws, NFT's image is not showing and also the image URL is also not working it says Access Denied.

**Comment by Kameeno** [comment]
What's your autorisation config? 

use this: 

`{
    "Version": "2012-10-17",
    "Id": "Policy1441664301333",
    "Statement": [
        {
            "Sid": "Stmt1441664293105",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [ "s3:GetObject"],
            "Resource": "arn:aws:s3:::pkmnsoltrainersbucket-devnet0/*"
        }
    ]
}`

and for the cors policy:

`[
    {
        "AllowedHeaders": [],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]`
