### ISSUE TITLE
Unable to initialize store when using a test validator on localhost

### ISSUE THREAD

**Issue by Cptweirdo** [metaplex-foundation/metaplex#922]
To reproduce:
* Checkout commit 83e68e3a245f2651d91e32873433d0657d02ea5e
* Modify ENDPOINTS in 'connection.ts' to make localhost selectable by adding to the array:
```
{
    name: 'localnet' as ENV,
    endpoint: 'http://127.0.0.1:8899',
    ChainId: ChainId.Devnet,
}
```
* Follow regular install instructions and start the store via 'yarn start'
* Connect your wallet and click "init store" when prompted

Expected:
Store would initialize

Result:
Store does not initialize, while a log 'REST null result for <Transaction ID>' is spammed. After a few retries method runs into a timeout.

**Comment by makcreative** [comment]
I have the same issue would really appreciate any help.

**Comment by ciripel** [comment]
I have the same issue on Devnet

**Comment by tiempham** [comment]
@Cptweirdo , @makcreative I think you both need to set network to dev net and add some sol to make transactions.
