### ISSUE TITLE
Problem with candy machine

### ISSUE THREAD

**Issue by EmileLp123** [metaplex-foundation/metaplex#928]
<img width="720" alt="bug" src="https://user-images.githubusercontent.com/93953222/140832354-121dd56b-35a7-49be-b759-e462e7b30e09.png">
I have this problem during uplaod, could you help me? I can pay

**Comment by Yuriy-Ihor** [comment]
Is it the second time when you run "upload" command?

**Comment by Yuriy-Ihor** [comment]
It's not an error with upload, but with creating candy machine. Did you run "upload *directory*" command?

**Comment by truonggau** [comment]
https://issueexplorer.com/issue/metaplex-foundation/metaplex/625 maybe help you
