### ISSUE TITLE
Modified files for uploading gif (etc) nfts?

### ISSUE THREAD

**Issue by NFTers** [metaplex-foundation/metaplex#929]
Anyone have modified files to upload gif nfts?, what files to modify?

**Comment by NFTers** [comment]
I just found out a way to upload gif nfts. I'm closing this now.

**Comment by JamisonO** [comment]
Hey how did you figure out how to do gif nfts with Metaplex/CandyMachine? I'm trying the same thing rn and I'd love to know.
