### ISSUE TITLE
State 

### ISSUE THREAD

**Issue by aheckmann** [metaplex-foundation/metaplex#930]
**Describe the bug**
There is a local UI state issue when switching from devnet to mainnet or changing stores which causes the app to not load properly.

Observations

1. Making changes to the packages/web/.env file and restarting the app does not always have the indented effect. The correct store or owner is not always used in RPC calls right away.
2. Switching from mainnet to devnet and vice versa does not always cause the app to connect to the configured environment, especially after changing the .env file and restarting

These smell like the same issue to me: a race condition in when we read state from the env at start up and connect to the correct environment vs reading the values from local storage or cookies etc.

The result is loss of precious time during development,.and a negative Developer Experience

Note: I've gotten into the habit of deleting the packages/web/.next directory but sometimes it's not enough. 

**To Reproduce**
1. Create a new wallet.
2. Start the app 
3. Connect the new wallet and set to devnet
4. Init a store / follow the instructions to update your .env file and restart the app
5. Create an NFT
6. Stop the app
7. `mv packages/web/.env packages/web/.env1`
8. Create a new wallet
1. Restart the app
1. Connect the new wallet and set to mainnet
2. Create a new store, init and create a new NFT
1. Stop the app
1. `mv packages/web/.env packages/web/.env2`
2.  `mv packages/web/.env1 packages/web/.env`
2. Restart the app

Continue similar combinations of these steps until you see the app not loading right, timing out, waiting for a long time.

**Expected behavior**
The app should always honor the settings in packages/web/.env and mainnet/devnet wallet setting

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: All

**Comment by 0xCryptoSheik** [comment]
@austbot @aheckmann is this no longer reproducible on your side after #958 ?

I expected #958 to be a good first step but not necessarily to fix this issue completely:
I believe there are still multiple areas in the code where a race condition or side-effect related to previous settings is posible.

Of course I'm also fine with creating more specific issues around this if/when needed.
