### ISSUE TITLE
Incorrect founds calculation On Candy Machine command

### ISSUE THREAD

**Issue by wandrzejczak** [metaplex-foundation/metaplex#931]
**Describe the bug**
I don't know why, but I think this is not intended behavior.
When uploading the images to the candy machine, a new config account is created.
The problem is that the "size" variable is configured in the way that it takes a lot of the SOL from the main account.
SOL's funds are assigned to the Candy Machine Address. 
As far I see, there is no usage of the transferred funds.
When I reduce the "size" manually, everything also works.
When I upload 600 images, it takes ca. 1 SOL from my Wallet.
When I replace maxNumberOfLines to return "2", it takes just a tiny, tinny fraction SOL from my Wallet.
 
```
export async function createConfigAccount(
  anchorProgram,
  configData,
  payerWallet,
  configAccount,
) {
  const size =
    CONFIG_ARRAY_START +
    4 +
    configData.maxNumberOfLines.toNumber() * CONFIG_LINE_SIZE +
    4 +
    Math.ceil(configData.maxNumberOfLines.toNumber() / 8);

  return anchor.web3.SystemProgram.createAccount({
    fromPubkey: payerWallet,
    newAccountPubkey: configAccount,
    space: size,
    lamports:
      await anchorProgram.provider.connection.getMinimumBalanceForRentExemption(
        size,
      ),
    programId: CANDY_MACHINE_PROGRAM_ID,
  });
}

```

Everything that I've changed is to set getMinimumBalanceForRentExemption(1)
```
export async function createConfigAccount(
  anchorProgram,
  configData,
  payerWallet,
  configAccount,
) {
  const size =
    CONFIG_ARRAY_START +
    4 +
    configData.maxNumberOfLines.toNumber() * CONFIG_LINE_SIZE +
    4 +
    Math.ceil(configData.maxNumberOfLines.toNumber() / 8);

  return anchor.web3.SystemProgram.createAccount({
    fromPubkey: payerWallet,
    newAccountPubkey: configAccount,
    space: size,
    lamports:
    
     // here
      await anchorProgram.provider.connection.getMinimumBalanceForRentExemption(
        1,
      ),

    programId: CANDY_MACHINE_PROGRAM_ID,
  });
}
```

**My Question:**
What is/was the intention of this functionality?
Is this intended behavior or a bug?
Pre-Allocating data space/size is not the same as imports/account balance, right?

I'd be grateful for clarification.

**UPDATE**
I've just finished uploading test 6'000 NFT's with the import change described above. In total it cost me 0.089740596 SOL (21.5 USD). In comparison using the original script, it took over 14 SOL to do the same job.

**Comment by facundocajen** [comment]
Hello zak, can you further explain the process?

You said that you modified _maxNumberOfLines_ to return "2", yet the only change I see on your code is the following:

`await anchorProgram.provider.connection.getMinimumBalanceForRentExemption(
        1,
      ),`

I am really interested in trying this out, both on devnet and mainnet so I can let you know my exact results and maybe implement this on my own project.

Have a nice day pal!

**Comment by samuelvanderwaal** [comment]
The transferred funds are used to pay Solana rent storage fees to keep the config account alive until minting is finished. After that you can [withdraw](https://docs.metaplex.com/create-candy/withdraw) your funds from the config account.
