### ISSUE TITLE
Setting mint price too low fast forwarded candy machine by 11 slots

### ISSUE THREAD

**Issue by shibaji** [metaplex-foundation/metaplex#936]
**Problem Statement**
To test the mint on mainnet-beta, I had set the mint price as -p 0.00001, however, with that, when I minted the first token, out of 10000 supply, it returned my token 11 after skipping first 11 tokens numbered 0 to 10. Then I had updated the price to 0.50 sol, and it started minting sequentially.

**To Reproduce**
Set candy machine mint price to 0.00001

**Expected behavior**
No abnormal behavior like jumping ahead of the token sequence, leaving first few token unminted.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome

**Additional context**
(1) Why did it happen? Is there a minimum mint price requirement? (2) What will happen to the first 11 unminted NFTs?

**Comment by shibaji** [comment]
Anyone?

**Comment by jasonruncie** [comment]
The issue you experienced was most likely just bots buying the first several NFTs out of the candy machine.

**Comment by samuelvanderwaal** [comment]
You got botted. Don't set candy machines with very low prices on mainnet as bots look for this and mint automatically.

**Comment by digz6666** [comment]
> You got botted. Don't set candy machines with very low prices on mainnet as bots look for this and mint automatically.

You mean bots mint themselves and get them using SOL in my wallet?
