### ISSUE TITLE
All creators need to be active by default

### ISSUE THREAD

**Issue by ValiDraganescu** [metaplex-foundation/metaplex#937]
**Is your feature request related to a problem? Please describe.**
In my store, I want to allow any user to mint NFTs (already doable by setting the public store setting)
But after a user creates an NFT, they cannot see it in the My Items page and they can't sell the NFT because these users are not active and require a manual operation to activate them. (Although selling is not a big concern right now for me, I would like that they be at least able to see their NFTs. I checked and the NFTs minted by this kind of users are visible in the Phantom wallet but not on the storefront)

**Describe the solution you'd like**
I would like there to be a setting that will make all users that minted an NFT to be active by default

**Describe alternatives you've considered**
A solution would be to store data about new NFTs in my database and thus will be able to display them in the storefront, but I feel like this is not a real solution.

**Additional context**
In my store, the NFTs will be created on-demand. The users can create how many they want because they are functional NFTs, not art NFTs (although they might be considered art, they are not affected by rarity and they can be doubled)

**Comment by Moikapy** [comment]
Is this being looked into or a solution found? I'm running into this error and was hoping to find a way around this issue.
I tried using the public setting under /admin, but it doesn't seem to be working unless I manually add a user to the whitelist

**Comment by sarik93** [comment]
Does anyone have any ideas for a solution?

**Comment by ughodera** [comment]
Hi @ValiDraganescu ,

Please check this link

I did small changes in js and rust program

Metaplex_program Rust side: disabled admin check, so any creator adds him as white list creator. It is a one time process at the time of creating the first nft.
Marketplace JS side: Admin page is only visible to the store owner.

Use this link to validate from your end: https://ughodera.github.io/metaplex#/
Select cluster: Devnet

Note: It takes 1 or 2 refresh of page to see nft created in owned tab
