### ISSUE TITLE
"Error uploading file xxx Error: Timed out awaiting confirmation on transaction" when running upload command on mainnet

### ISSUE THREAD

**Issue by Gitzi777** [metaplex-foundation/metaplex#949]
Hi, I try to upload my collection on  solana mainnet by launching the necessary command, at the beginning everything goes correctly then there was this error message for some nft of the collection: "Error uploading file 487 Error: Timed out awaiting confirmation on transaction."
Then the upload works again for the next nft until the error message comes back and so on.

when I look in the cache file, it turns out that some have been uploaded and others have not (for example the 450 451 452 are in the list then there is a gap up to the 460 etc.)

Here the screen of the cache file and the error message where I drew a red line
<img width="1406" alt="Capture d’écran 2021-11-12 à 15 48 28" src="https://user-images.githubusercontent.com/94183240/141486317-e757d1b7-bc86-4f50-a896-579917adacd3.png">
<img width="1092" alt="Capture d’écran 2021-11-12 à 15 49 07" src="https://user-images.githubusercontent.com/94183240/141486334-014de3b4-d0ce-488c-abf6-e71270ad613f.png">

**Comment by Nicekolk** [comment]
Same problem tried with smaller file sizes didn't seem to work

**Comment by jinzzzzzzz** [comment]
Did you ever resolve this?

**Comment by jclmnop** [comment]
I changed the `DEFAULT_TIMEOUT` constant in `js/packages/cli/src/helpers/constants.ts` from `15000` to `20000` and so far it seems to have helped.

**Comment by eideri** [comment]
is happening same for me but in devnet also.. Any solution?

**Comment by jclmnop** [comment]
> is happening same for me but in devnet also.. Any solution?

Yeah, sign up for an account here and use their free RPC endpoint plan: https://datahub.figment.io

**Comment by aliekmekcii** [comment]
> > is happening same for me but in devnet also.. Any solution?
> 
> Yeah, sign up for an account here and use their free RPC endpoint plan: https://datahub.figment.io

How can we use RPC ?

**Comment by jclmnop** [comment]
> > > is happening same for me but in devnet also.. Any solution?
> > 
> > 
> > Yeah, sign up for an account here and use their free RPC endpoint plan: https://datahub.figment.io
> 
> How can we use RPC ?

Once you get your RPC endpoint url with your api key in it, you put that url in your solana config where the default devnet/mainnet url is.

**Comment by 1Crypt0** [comment]
> > > > is happening same for me but in devnet also.. Any solution?
> > > 
> > > 
> > > Yeah, sign up for an account here and use their free RPC endpoint plan: https://datahub.figment.io
> > 
> > 
> > How can we use RPC ?
> 
> Once you get your RPC endpoint url with your api key in it, you put that url in your solana config where the default devnet/mainnet url is.

Please can you explain a bit more, I have the datahub plan just having trouble getting it working. what do you mean exactly by solana config? I am using metaplex and have tried apending to the upload command with the --rpc url flag, thanks in advance for any help on this!

**Comment by jclmnop** [comment]
> > > > > is happening same for me but in devnet also.. Any solution?
> > > > 
> > > > 
> > > > Yeah, sign up for an account here and use their free RPC endpoint plan: https://datahub.figment.io
> > > 
> > > 
> > > How can we use RPC ?
> > 
> > 
> > Once you get your RPC endpoint url with your api key in it, you put that url in your solana config where the default devnet/mainnet url is.
> 
> Please can you explain a bit more, I have the datahub plan just having trouble getting it working. what do you mean exactly by solana config? I am using metaplex and have tried apending to the upload command with the --rpc url flag, thanks in advance for any help on this!

You should have the solana cli tools installed (if not, then you should go to the solana website and follow their instructions). 

If you run the command `solana config get` it will show you your current config. 

`solana config set --url putyourdatahubthinghere.com/thisbitwillbeyourapikey` will set the url to your new RPC. 

Datahub has a devnet and a mainnet RPC, so just use whichever one is appropriate.

**Comment by 1Crypt0** [comment]
Thanks for the reply,

I have ran the solana config --url  as advised and generated a keypair,
added the private key to the wallet and funded. I have set the kepair and
confirmed solana balance.
I then Downloaded Metaplex, ran npm yarn install, cd into js and ran yarn
install, build, bootstrap, cd.. back up
Then I run the upload with
npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env
mainnet-beta --keypair ~/.config/solana/key-mainnet.json --rpc-url
https://solana--mainnet.datahub.figment.io/apikey/myapikey

This results in the 429 - too many requests, some files seem to be working
and datahub shows in logs activity but command stops running after a time
with unsubscribe error.

I see in datahub I get instruction
curl https://solana--mainnet.datahub.figment.io/apikey/
a1ff99b2d59d2dd31927b9fda9ccefd0/health

Is it correct to leave out the curl and /health part?

I'm asking myself - Is my upload command correct or maybe I need to do
something with the phantom wallet or do I need an arweave wallet with
arweave tokens
I was further confused by an article about this
https://github.com/kevinrodriguez-io/solana-figment-rpc-endpoint-cors-gcr
that made it sound quiete a big job haha

Thanks very much for the help, a very grateful novice am I :)

**Comment by Khushhal23** [comment]
Use quicknode

**Comment by jclmnop** [comment]
> Is it correct to leave out the curl and /health part?

Yes. Although it's not a bad idea to run 
```
curl https://solana--mainnet.datahub.figment.io/apikey/<redacted>/health
```
to check that you're actually connecting to the RPC and it's working properly. Run this is a standalone command in your terminal. Also, edit your post to remove your RPC api key and/or generate a new API key. 

>  or do I need an arweave wallet with arweave tokens

No, the CM handles all of this automatically for you.

**Comment by 1Crypt0** [comment]
> > Is it correct to leave out the curl and /health part?
> 
> Yes. Although it's not a bad idea to run
> 
> ```
> curl https://solana--mainnet.datahub.figment.io/apikey/<redacted>/health
> ```
> 
> to check that you're actually connecting to the RPC and it's working properly. Run this is a standalone command in your terminal. Also, edit your post to remove your RPC api key and/or generate a new API key.
> 
> > or do I need an arweave wallet with arweave tokens
> 
> No, the CM handles all of this automatically for you.

Thanks for the heads up missed that one. I did run that curl command in the terminal for the datahub link and got back an ok, a lucky guess. Would I expect to still see all the errors that come up if it were working properly?

I have no idea how many requests I would expect to get through on quicknode but not wanting to rack up a huge bill tbh haha

**Comment by emersonthis** [comment]
I tried switching to the free Datahub RPC endpoint. I also tried with a a paid Quicknode endpoint. With both I still get this timeout error most of the time. Is candy machine automatically using the default config.yml ? Or do I need to add additonal options to the command? 

```
$ solana config get
Config File: /Users/me/.config/solana/cli/config.yml
RPC URL: https://misty-dawn-glade.solana-mainnet.quiknode.pro/<REDACTED>/ 
WebSocket URL: wss://misty-dawn-glade.solana-mainnet.quiknode.pro/<REDACTED>/ (computed)
Keypair Path: /Users/me/.config/solana/devnet.json 
Commitment: confirmed 
```

```
$ ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/keypair.json -cp ./config.json -c cache_name ./nft_assets
```

Why do these timeouts keep happening? After three different endpoints, this doesn't feel like an issue with the rpc endpoints.

**Comment by emersonthis** [comment]
> Is candy machine automatically using the default config.yml ? Or do I need to add additional options to the command?

We need to add `--rpc-url https://example.com/` in order for the custom endpoint to be used. Also note that at the time of writing this, the URL _must_ end in `/` or other errors will happen.

PS: even with a paid Quicknode RPC endpoint, I'm still getting timeouts frequently :-(

**Comment by Khushhal23** [comment]
Those timeouts are because of the solana blockchain, not because of the
custom rpc

**Comment by TranslatorDlique** [comment]
I'm having the same issue even after upgrading to Quicknode Pro. It's taken me around ~3 hours and 300 000 responses to the RPC to upload 2500 assets for a 10000 asset project

**Comment by Hangman2arb** [comment]
I tried all of this thread and nothing works... I have the same issue... Any solution? If I leave metaplex running, will this resolve itself? I mean, since it looks like it's trying in a loop, maybe it's uploading all the missing NFTs.

**Comment by ASGDLO** [comment]
do this "solana config set -u https://api.devnet.solana.com" and waiting 5minute and try agin

**Comment by TranslatorDlique** [comment]
> I tried all of this thread and nothing works... I have the same issue... Any solution? If I leave metaplex running, will this resolve itself? I mean, since it looks like it's trying in a loop, maybe it's uploading all the missing NFTs.
> 
> My error: ... ... Timeout Error caught { timeout: true } Error uploading file 1524.png Error: Timed out awaiting confirmation on transaction at sendSignedTransaction (C:\Users...\metaplex-master\js\packages\cli\src\helpers\transactions.ts:131:13) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5) at async sendTransactionWithRetryWithKeypair (C:\Users...\metaplex-master\js\packages\cli\src\helpers\transactions.ts:59:26) at async arweaveUpload (C:\Users...\metaplex-master\js\packages\cli\src\helpers\upload\arweave.ts:87:14) at async C:\Users...\metaplex-master\js\packages\cli\src\commands\upload.ts:276:41 at async Promise.all (index 3) at async uploadV2 (C:\Users...\metaplex-master\js\packages\cli\src\commands\upload.ts:218:7) at async Command. (C:\Users...\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:216:7) Rejecting for timeout... Timeout Error caught { timeout: true } Error uploading file 278.png Error: Timed out awaiting confirmation on transaction at sendSignedTransaction (C:\Users...\metaplex-master\js\packages\cli\src\helpers\transactions.ts:131:13) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5) at runNextTicks (internal/process/task_queues.js:64:3) at processTimers (internal/timers.js:497:9) at async sendTransactionWithRetryWithKeypair (C:\Users...\metaplex-master\js\packages\cli\src\helpers\transactions.ts:59:26) at async arweaveUpload (C:\Users...\metaplex-master\js\packages\cli\src\helpers\upload\arweave.ts:87:14) at async C:\Users...\metaplex-master\js\packages\cli\src\commands\upload.ts:276:41 at async Promise.all (index 9) at async uploadV2 (C:\Users...\metaplex-master\js\packages\cli\src\commands\upload.ts:218:7)

The issue for me was using arweave rather than arweave-sol in my config.json file. What happened was that all the metadata was uploaded but not the images so I ended up with metadata that did not include uris to images. I fixed this by clearing the metadata URIs in the .cache folder (just the data between the [ ] where the metadata lives (back up the file before altering it). After that I re-ran the upload using arweave-sol. It still took around 10 hours to upload but without the timeout issue and hundreds of thousands of RPC calls.

**Comment by Hangman2arb** [comment]
Thaks ASGDLO And TranslatorDlique It was a funds problem, but I will have in count all about you say 😄

**Comment by saibaneer** [comment]
> I changed the `DEFAULT_TIMEOUT` constant in `js/packages/cli/src/helpers/constants.ts` from `15000` to `20000` and so far it seems to have helped.
> 
> Edit: It has not. Instead I've now changed the code so that it retries a file if it times out, and I've written a bash script to retry the whole command if it fails because of a FetchError.

Can you share your bash script for this?

**Comment by saibaneer** [comment]
Unsure if the solana network is actually quite bad, or if it is Metaplex, but this timeout issue needs a solution. It is not feasible to mint NFTs like this.
