### ISSUE TITLE
Transaction failed: Share total must equal 100 for creator array

### ISSUE THREAD

**Issue by cormacncheese** [metaplex-foundation/metaplex#950]
**Describe the bug**
When attempting to mint with multiple co creators I get the follower error:
Transaction failed: Share total must equal 100 for creator array

However the creator amounts add up to 100 in the creators array (see screenshot):
<img width="248" alt="Screen Shot 2021-11-12 at 7 11 33 AM" src="https://user-images.githubusercontent.com/64498165/141489483-2396fe36-e473-43d6-a5c7-1f10cbd1b69f.png">

**To Reproduce**
1. Mint asset
2. Add 3 creators
3. split 2.5/2.5/95
4. Submit mint

**Expected behavior**
Expected to split 2.5% 2.5% and 95%

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Chrome, latest metaplex version

**Additional context**
It may have something to do with the verified attribute but not quite sure how to mark as true since I added the co-creators from admin

**Comment by 21e8** [comment]
you cannot have decimals here since the rust program onlt accepts integers
