### ISSUE TITLE
Allow mutable limited edition NFT metadata

### ISSUE THREAD

**Issue by PopcornPaws** [metaplex-foundation/metaplex#951]
**Is your feature request related to a problem? Please describe.**
I would like to be able to modify the metadata of limited edition NFTs to be different than their master edition's metadata, e.g. contain a different image uri and name.

**Describe the solution you'd like**
In the metadata program's source code, in `src/utils.rs` the `mint_limited_edition` function calls the `process_create_metadata_accounts_logic` function with a hard-coded `is_mutable = false` parameter, thus it's not possible to update the metadata of the newly minted "child edition" NFT.

**Describe alternatives you've considered**
I saw that NFT families on solanart consist of master edition NFTs whose metadata is straightforward to be set to a unique value. However, as far as I know, these master editions are not connected in any way, except for their metadata. It would be nice though, to keep the underlying logic/structure that master and subsequent editions have with each other.

**Additional context**
Maybe I'm missing something, or limited editions shouldn't be used like this, but it doesn't seem to be a huge task, and I would be happy to open a PR that enables updating limited edition NFT metadata, if it's something that would make sense.

**Comment by samuelvanderwaal** [comment]
This is a deliberate design choice and won't be changed at this time.
