### ISSUE TITLE
Generative art is sometimes layered in the wrong order by the CLI tool

### ISSUE THREAD

**Issue by candymandev** [metaplex-foundation/metaplex#967]
**Describe the bug**
There is a bug that results in trait PNG being layered in the wrong order in some cases. The portion of the CLI tool that does the layering is vulnerable to a race condition here: https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/commands/createArt.ts#L16. The promises are kicked off in the correct order but can finish in different orders. Most of the time, it works fine. However in some cases the promises finish in different orders.

**To Reproduce**
- Run the tool over and over again on the sample data with `-n <number_of_images>` set to at least 500
- Observe that in some cases the generated images are missing eyes, mouth, faces, etc. This happens when the layering is done out of order. For example, a face layered over the eyes hides the eyes completely.

**Expected behavior**
The generated image should ensure that each trait is rendered in the right order for each generated image.

**Screenshots**
Here is a good generated image:
![correct-sample](https://user-images.githubusercontent.com/94403944/141854783-9b4f1f36-0e80-4bff-ae88-ff834c2583d3.png)

Here are some bad generated images caused by this bug:
![bad-sample-3](https://user-images.githubusercontent.com/94403944/141854776-cae84404-6d32-42b2-9d11-e05626d82a8e.png)
![bad-sample-2](https://user-images.githubusercontent.com/94403944/141854778-79826af4-02e6-4cbb-b7cc-90f1eeee19cc.png)
![bad-sample-1](https://user-images.githubusercontent.com/94403944/141854782-f558eedf-6903-440e-ab72-1f17305bb156.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by 0xCryptoSheik** [comment]
Ah, this might be my fault... (#899) Sorry about that, taking a look.

**Comment by candymandev** [comment]
Yes the race condition was already there, so your hands are clean 😄 . Agreed this will make the script slower, but it will always be correct. Good tradeoff 👌 

Thanks for jumping right on this!

**Comment by candymandev** [comment]
I'll submit a PR to fix this.

Like you said the fix is simple. I'll change the `Promise.all` to a `for...of` loop so each worker loops over the traits sequentially to construct the layered image.

**Comment by 0xCryptoSheik** [comment]
@candymandev Ok, thanks :)

By the way, looking at this I think I just found a way to make up for the lost speed, and make the overall script even faster than it is now, by pre-loading the image traits before `createImage` and passing the loaded images to `createImage`, will experiment and open a PR if it's worth it, cheers :)

**Comment by candymandev** [comment]
@0xCryptoSheik Great idea! We are loading the trait image each time they are used, but we maybe we only have to load each trait image once. Tag me in the PR if you end up trying that out!

PR to close this out is submitted.
