### ISSUE TITLE
error when i run cd js

### ISSUE THREAD

**Issue by Wallos1** [metaplex-foundation/metaplex#969]
cd : Cannot find path 'C:\Users\14702\Desktop\Solana Bros\metaplex-master\.js' because it does not exist.
At line:1 char:1
+ cd .js
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\14702\...plex-master\.js:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by Kameeno** [comment]
just `cd 'C:\Users\14702\Desktop\Solana Bros\metaplex-master\js`
