### ISSUE TITLE
yarn build problem

### ISSUE THREAD

**Issue by spencercoder** [metaplex-foundation/metaplex#970]
![Screen Shot 2021-11-15 at 18 42 24](https://user-images.githubusercontent.com/93333477/141877531-08fb1668-947c-4849-b235-37f036c6162f.png)

**Comment by alexajwhite** [comment]
I have the same issue at the moment

**Comment by jmorettoni** [comment]
the same issue for me

**Comment by spencercoder** [comment]
on mac?

**Comment by alexajwhite** [comment]
yes

**Comment by spencercoder** [comment]
could you send a pic of how your error looks like?

**Comment by alexajwhite** [comment]
I managed to fix it by commenting out the lines that gave the error

**Comment by spencercoder** [comment]
how do i do that?

**Comment by alexajwhite** [comment]
go into js/packages/web then whatever the error shows and comment out the line with design and info and the title line

**Comment by spencercoder** [comment]
im such a noob lol, is there anyway you could guide me a little easyr

**Comment by spencercoder** [comment]
how do i get into js/packages/web, in folder you mean

**Comment by spencercoder** [comment]
@alexajwhite could you help

**Comment by alexajwhite** [comment]
So just open it up in explorer, go from the root Metaplex folder, then js, then packages, then web, src, views, packCreate, components, header, data.ts and comment out line 17, 18, and 19 using // as a prefix

**Comment by orlyjamie** [comment]
What implications is it going to have if these lines are commented out? packCreate sounds important

**Comment by aheckmann** [comment]
Fixed in #987
