### ISSUE TITLE
not able to see the create button for NFT

### ISSUE THREAD

**Issue by davnav** [metaplex-foundation/metaplex#971]
I did follow the steps mentioned in the metaplex documentation. After yarn deploy , the my gh pages  https://davnav.github.io/metaplex#/ is not showing "create" button in the home page to create NFT. It showing only "sell" option

![solana metaplex issue](https://user-images.githubusercontent.com/1313332/141882816-765fdf6a-e1a1-40d2-929f-90039b550818.png)

Please advise anyone else facing the issue ? is it my build issue ?

**Comment by mkim1620** [comment]
I've been having the same issue

**Comment by numisman** [comment]
I think your wallet has to be listed as one of the creators.

**Comment by sarik93** [comment]
I think duplicate #937

**Comment by PhilSole** [comment]
I'm still experiencing this issue. Fresh local Metaplex install
