### ISSUE TITLE
big issue

### ISSUE THREAD

**Issue by investpedia** [metaplex-foundation/metaplex#973]
not solved many issues, this is big issue from this repo.
i think you have to make from scratch again, cause this repo near dead...

**Comment by aheckmann** [comment]
thanks for your feedback. we have a plan to address the repo and are making progress. if you have anything specific you'd like to call out or would like to help, let us know.

**Comment by investpedia** [comment]
Dear aaron, with regards.
Please make a complete document for metaplex , cause the users cant
understand howto's.
And i hope you know about the power of community.
i like u r repo, and completely reforge that for my purposes.
Good luck
