### ISSUE TITLE
cant add a custom rpc because it cant find the command

### ISSUE THREAD

**Issue by spencercoder** [metaplex-foundation/metaplex#982]
error: unknown option '--rpc-url'

**Comment by 1Note-io** [comment]
It seems that you are not calling the program correctly.
The following command could be used as help:

**// This command is tested and works. You can use --rpc-url here:**
`ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts upload /UPLOAD_PATH/ --env mainnet-beta --keypair /KEYPAIR_PATH/keypair.json --rpc-url https://api.mainnet-beta.solana.com`

**Comment by spencercoder** [comment]
hey

**Comment by spencercoder** [comment]
thanks for responding @1Note-io 
should i try to use the command you have sent me? and add my custom rpc url ?
im a noob at this lol

**Comment by spencercoder** [comment]
and my own keypair?

**Comment by spencercoder** [comment]
the error that happens is error: unknown option '--rpc-url'
but when i do the help command rcp is not in there
![Screen Shot 2021-11-16 at 16 25 34](https://user-images.githubusercontent.com/93333477/142076021-dc677efd-53cb-4c62-b8a2-4f67b420f8b7.png)

**Comment by 1Note-io** [comment]
You can customize Solana's default RPC. You do this with the config command:
![solanaconfig](https://user-images.githubusercontent.com/93943427/142077760-fa6dd746-4254-41c9-8ea1-7c3df910f665.png)

Works like:
solana config set --url *NETWORK URL*

More information: https://docs.solana.com/cli/choose-a-cluster

Only this has nothing to do with Metaplex, metaplex is not part of the "Solana" command.
The --prc-url you are talking about can for example be used in the **candy-machine-cli.ts**

**Comment by spencercoder** [comment]
@1Note-io but i already config set the custom rpc
but it cat find the command when i use the command

**Comment by spencercoder** [comment]
@1Note-io look

MacBook-Air:metaplex-master biohairtransplant$ solana config get
Config File: /Users/biohairtransplant/.config/solana/cli/config.yml
RPC URL: https://falling-divine-dust.solana-mainnet.quiknode.pro/9b09906a2342f284065736260bfc7bcae28/ 
WebSocket URL: wss://falling-divine-dust.solana-mainnet.quiknode.pro/9b09906a2342f284065736260bfc7bcae28/ (computed)
Keypair Path: /Users/biohairtransplant/.config/solana/phase1spencer-mainnet.json 
Commitment: confirmed
