### ISSUE TITLE
Regerssion: Can't add creator in latest master

### ISSUE THREAD

**Issue by etodanik** [metaplex-foundation/metaplex#99]
I get the following error (wasn't happening previously):
```
3.eb939614.chunk.js:2 Uncaught (in promise) Error: unknown signer: BiDqzZdVeUKxoXGGijD7M7FShNtxFfKyju18Er6SqF5e
    at e.value (3.eb939614.chunk.js:2)
    at e.value (3.eb939614.chunk.js:2)
    at inpage.js:487
    at Array.map (<anonymous>)
    at a.<anonymous> (inpage.js:487)
    at Generator.next (<anonymous>)
    at r (inpage.js:487)
```

I'm properly connected with the store owner wallet.

**Comment by israelidanny** [comment]
So... After trying a few times, it worked. So not a regression? Still, not sure if it's good or bad that it happens, since it's clearly what appears to be a bug.

**Comment by bhgames** [comment]
Hmm, see if you can figure out repro steps. I'll leave this open.

**Comment by israelidanny** [comment]
I'm seeing another bug for now, that seems to be fairly constant. If you init a store and go straight to make creators, it will fail with uncaught error about `.toString()` not existing on something. This happens to me quite constantly if I init a store. Still trying to reproduce the above bug.

**Comment by PigeonSolToken** [comment]
you need to make changes to js\packages\common\src\contexts\connection.tsx

go to sendTransactionWithRetry and modify:

  if (includesFeePayer) {
    transaction.setSigners(...signers.map(s => s.publicKey));
  } else {
    try{
    transaction.setSigners(
      // fee payed by the wallet owner
      wallet.publicKey,
      ...signers.map(s => s.publicKey),
    );
  }
  catch (err) {
    console.error('Not logged in');
    return { 'txid': '0', 'max': 0 };
  }
  }

  if (signers.length > 0) {
    transaction.partialSign(...signers);
  }
  if (!includesFeePayer) {
    try{
    transaction = await wallet.signTransaction(transaction);
    }
    catch (err) {
      console.error('Transaction cancelled');
      return { 'txid': '0', 'max': 0 };
    }
  }


Also go to sendTransactions and modify:

    transaction.recentBlockhash = block.blockhash;
    try{
    transaction.setSigners(
      // fee payed by the wallet owner
      wallet.publicKey,
      ...signers.map(s => s.publicKey),
    );
    }
    catch (err) {
      console.error('Not logged in');
      return 0;
  }

    if (signers.length > 0) {
      transaction.partialSign(...signers);
    }

    unsignedTxns.push(transaction);
  }

  let signedTxns: any; 
  try{
    signedTxns = await wallet.signAllTransactions(unsignedTxns);
  }catch (err) {
    console.error('Transaction cancelled');
    return 0;
  }

**Comment by bhgames** [comment]
Alright we'll take a further look here thanks, might be related to another fix

**Comment by israelidanny** [comment]
So, just to clarify, there are two distinct errors:
1. Easily reproducible: Just connect a wallet, init a store and without refreshing try to add a new creator. It will complain about some toString() related error.
2. I couldn't find a solid way to reproduce it, but it was the `Error: unknown signer` error. Happened intermittently also after init-ing a fresh store.

**Comment by bhgames** [comment]
this still happening?
