### ISSUE TITLE
yarn dev error command

### ISSUE THREAD

**Issue by Aysel9** [metaplex-foundation/metaplex#990]
$ yarn dev
yarn run v1.22.11
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by aheckmann** [comment]
There is no dev command. Please share more details about the issue you are experiencing and your expectations.

**Comment by Aysel9** [comment]
Can't I make changes now? for front end stock? please help

**Comment by Aysel9** [comment]
I want to make the front side of the site from 0, I say the area with the connect button @aheckmann

**Comment by aheckmann** [comment]
If you'd like to create a new front-end, the best place to start would be with our [JS SDK](https://github.com/metaplex/js)
