### ISSUE TITLE
when i run the mainnet upload command it cant find the directory 

### ISSUE THREAD

**Issue by spencercoder** [metaplex-foundation/metaplex#993]
command i run: npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair (PATH)

zsh: no such file or directory: /Users/biohairtransplant/metaplex/js/packages/cli/src/candy-machine-cli.ts

**Comment by georgiod9** [comment]
If you navigate to metaplex/js/packages/cli/src can you locate candy-machine-cli.ts?
Also, i found it's better to copy file path from within visual studio and use it as the location in the command
