### ISSUE TITLE
Payouts Not Working

### ISSUE THREAD

**Issue by cormacncheese** [metaplex-foundation/metaplex#994]
**Describe the bug**
After a successful sale, both the main artist and co-creators are not receiving any funds to their phantom wallet. The buyer however is successfully charged the purchase price amount and can successfully view the NFT in their items.

When looking at the buyer wallet transactions, there are three transactions. A couple of which interact with the Metaplex contract sending the purchase price to the contract, however it's not clear where the funds go from there. 

**To Reproduce**
1. Mint NFT with a co-creator
2. Put minted item for sale for a fixed price
3. Purchase from another wallet
4. Buyer is charged but funds do not show up in any of the creators' wallets

**Expected behavior**
Expect payouts to happen immediately, looks like they don't happen at all

**Comment by yamijuan** [comment]
Payouts don't happen immediately. The sale needs to end (either auction or instant sale) then the creator will be able to settle the funds of the sale. If you go to <auction_url>/billing you will see how much is in the escrow

**Comment by cormacncheese** [comment]
@yamijuan Super helpful. Thank you!

**Comment by sarik93** [comment]
@yamijuan can this be done automatically? that is, immediately after the sale, the funds are distributed to all creators (theoretically, the contract knows how much and to whom to send)
